### ISSUE TITLE
Revised Data Bundle SOP

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#10]
The Data Bundle SOP document needs revision now that we have a V3 of the schema

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-12)
┆Project Name: azul
┆Issue Number: AZUL-12

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
