### ISSUE TITLE
Exclude old EMTAB5061 (healthy_diabetic_pancreas) dataset in prod

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#1000]
The EMTAB5061 (healthy_diabetic_pancreas) dataset is being re-ingested in prod.

Could the older version of the dataset (submission ID: 5c054a529460a300074f5007; project UUID: 1a0f98b8-746a-489d-8af9-d5c657482aab) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cda8757d96dad000856d2ae; project UUID: ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad) is currently exporting and has already started appearing in the Browser, with additional metadata! 👍

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-625)
┆Project Name: azul
┆Issue Number: AZUL-625

**Comment by zperova** [comment]
@xbrianh
