### ISSUE TITLE
Exclude old cerebral organoid dataset in prod

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#1005]
The cerebral organoid (treutlein) dataset has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5c2dfb101603f500078b28de; project UUID: d96c2451-6e22-441f-a3e6-70fd0878bb1b) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cdbdd7dd96dad0008592f28; project UUID: 005d611a-14d5-4fbf-846e-571a1f874f70) is exported and has already started appearing in the Browser, with additional metadata! 👍

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-627)
┆Project Name: azul
┆Issue Number: AZUL-627

**Comment by zperova** [comment]
@xbrianh

**Comment by zperova** [comment]
Please hold on with this issue until the pipelines team have confirmed that analysis has successfully finished.
