### ISSUE TITLE
Exclude old tissue sensitivity dataset in prod

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#1013]
The tissue sensitivity (meyer) dataset has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5c8acacd53367400073122db; project UUID: 5dfe932f-159d-4cab-8039-d32f22ffbbc2) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cdc5ab4d96dad000859cebf; project UUID: c4077b3c-5c98-4d26-a614-246d12c2e5d7) is exported and has already started appearing in the Browser, with additional metadata! 👍

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-629)
┆Project Name: azul
┆Issue Number: AZUL-629

**Comment by zperova** [comment]
@xbrianh

**Comment by zperova** [comment]
Please hold on with this issue until the pipelines team have confirmed that analysis has successfully finished.
