### ISSUE TITLE
Exclude old mouse melanoma dataset in prod

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#1014]
The mouse melanoma dataset has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5cadbf5ad96dad0008504a58; project UUID: ccd8370a-84b8-464d-a87e-e688ac3e4f62) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cda9de6d96dad00085796b9; project UUID: 8c3c290d-dfff-4553-8868-54ce45f4ba7f) is exported and has already started appearing in the Browser, with additional metadata! 👍

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-630)
┆Project Name: azul
┆Issue Number: AZUL-630

**Comment by zperova** [comment]
@xbrianh
