### ISSUE TITLE
Exclude old bone marrow (ido_amit) dataset in prod

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#1017]
The bone marrow (ido_amit) dataset has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5cb8e061d96dad000854f36e; project UUID: e1f2a0e4-1ec8-431e-a6df-c975b3a1131f) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cdd1fcdd96dad00085af1ae; project UUID: a29952d9-925e-40f4-8a1c-274f118f1f51) is exported! 👍

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-633)
┆Project Name: azul
┆Issue Number: AZUL-633

**Comment by zperova** [comment]
@xbrianh
