### ISSUE TITLE
Exclude old neuron_diff dataset in prod

### ISSUE THREAD

**Issue by willrockout** [DataBiosphere/azul#1018]
The neuron_diff dataset has been re-ingested in prod.

Could the older versions of the dataset (submission ID: 5cb75991d96dad0008532bdb; project UUID: b6dc9b93-929a-45d0-beb2-5cf8e64872fe) and (submission ID: 5bf53a6a9460a300074dc824; project UUID: f8880be0-210c-4aa3-9348-f5a423e07421) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cdb0344d96dad000858fff4; project UUID: 2043c65a-1cf8-4828-a656-9e247d4e64f1) is exported!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-634)
┆Project Name: azul
┆Issue Number: AZUL-634

**Comment by willrockout** [comment]
@xbrianh

**Comment by zperova** [comment]
@xbrianh Please hold on with this issue until the pipelines team have confirmed that analysis has successfully finished.
