### ISSUE TITLE
Exclude old CD4+_lymphocytes (EGEOD106540) dataset in prod

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/azul#1019]
The CD4+_lymphocytes (EGEOD106540) dataset has been re-ingested in prod.

Could you please remove the OLD version of this dataset:
Submission ID: 5c055aca9460a300074f87da
Project UUID: 0ec2b05f-ddbe-4e5a-b30f-e81f4b1e330c

The NEW version is:
Submission ID: 5cdd6c44d96dad0007e3cc8f
Project UUID: 90bd6933-40c0-48d4-8d76-778c103bf545

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-635)
┆Project Name: azul
┆Issue Number: AZUL-635

**Comment by malloryfreeberg** [comment]
@xbrianh
