### ISSUE TITLE
Eliminate `hits[*].projectSummary` element from `/projects` response

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1021]
All but `donorCount` can be gotten from other elements of the same hit.

TODO: fill in details, add ticket for replacing `donorCount`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-637)
┆Project Name: azul
┆Issue Number: AZUL-637

**Comment by danielsotirhos** [comment]
Where to find values previously in /repository/projects `hit['projectSummary']`

```
/repository/projects

hit['projectSummary']['donorCount']         => (length of array) len(hit['donorOrganisms'][0]['id'])
hit['projectSummary']['totalCellCount']     => hit['cellSuspensions'][0]['totalCells']
hit['projectSummary']['genusSpecies']       => hit['donorOrganisms'][0]['genusSpecies']
hit['projectSummary']['libraryConstructionApproach'] => hit['protocols'][0]['libraryConstructionApproach']
hit['projectSummary']['disease']            => hit['specimens'][0]['disease']
hit['projectSummary']['organTypes']         => hit['samples'][0]['effectiveOrgan']
hit['projectSummary']['cellCountSummaries'] => (/repository/summary) hit['cellCountSummaries']
```

**Comment by NoopDog** [comment]
The updates for this for data browser are deployed through to staging. Please feel free to deploy this update to dev and we can validate that all still is ok. Thanks!

**Comment by hannes-ucsc** [comment]
Demoed on 7/22
