### ISSUE TITLE
Exclude old fetal-maternal interface dataset in prod

### ISSUE THREAD

**Issue by zperova** [DataBiosphere/azul#1025]
The fetal-maternal interface dataset has been re-ingested in prod.

Could you please remove the OLD version of this dataset:
Submission ID: 5c48410e1603f500078b4c3a
Project UUID: aabbec1a-1215-43e1-8e42-6489af25c12c

The NEW version is:
Submission ID: 5cdc1b4ad96dad0008593302
Project UUID: f83165c5-e2ea-4d15-a5cf-33f3550bffde

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-641)
┆Project Name: azul
┆Issue Number: AZUL-641

**Comment by zperova** [comment]
Please hold on with this issue until the pipelines team have confirmed that analysis has successfully finished.

**Comment by hannes-ucsc** [comment]
> Please hold on with this issue until the pipelines team have confirmed that analysis has successfully finished.

@zperova, Scheduling conditions like that are too intractable for my team to implement. I propose that exclusion tickets are filed only after all other conditions on their resolution are met such that they can be acted upon immediately. I think this makes for a simpler, more reliable process.

**Comment by zperova** [comment]
@hannes-ucsc I agree this is not the best implementation - I wish there was a way to indicate such dependencies better. Would you prefer to close all the exclusion tickets for now and open one by one again once we hear back from pipeline team on a particular dataset?

**Comment by hannes-ucsc** [comment]
@zperova All of the exclusions are live on on prod now.

**Comment by hannes-ucsc** [comment]
… and my preference would be that future exclusions are filed when they can be acted on, not before. Is that possible?
