### ISSUE TITLE
Generate Project TSVs for the Japan demo

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#1027]
Missing Projects:
74b6d569-3b11-42ef-b6b1-a0454522b4a0
e1f2a0e4-1ec8-431e-a6df-c975b3a1131f
a29952d9-925e-40f4-8a1c-274f118f1f51
90bd6933-40c0-48d4-8d76-778c103bf545
a9c022b4-c771-4468-b769-cabcf9738de3
ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad
005d611a-14d5-4fbf-846e-571a1f874f70
1630e3dc-5501-4faf-9726-2e2c0b4da6d7
027c51c6-0719-469f-a7f5-640fe57cbece
ccd8370a-84b8-464d-a87e-e688ac3e4f62
8c3c290d-dfff-4553-8868-54ce45f4ba7f
b6dc9b93-929a-45d0-beb2-5cf8e64872fe
4129d036-67b9-4981-9d6d-3aaa235236d5
2043c65a-1cf8-4828-a656-9e247d4e64f1
dadbdb31-5f69-485b-85f3-b244b74123f1
5e6c0ede-5648-4b0e-83ce-4644c437b4c0
cddab57b-6868-4be4-806f-395ed9dd635a
209e6402-d854-49ea-815f-421dae5e3f4d
c4077b3c-5c98-4d26-a614-246d12c2e5d7

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-643)
┆Project Name: azul
┆Issue Number: AZUL-643

**Comment by GPelayo** [comment]
The missing TSVs have been uploaded to the bucket.

http://url.data.humancellatlas.org/projects/74b6d569-3b11-42ef-b6b1-a0454522b4a0.tsv
http://url.data.humancellatlas.org/projects/e1f2a0e4-1ec8-431e-a6df-c975b3a1131f.tsv
http://url.data.humancellatlas.org/projects/a29952d9-925e-40f4-8a1c-274f118f1f51.tsv
http://url.data.humancellatlas.org/projects/90bd6933-40c0-48d4-8d76-778c103bf545.tsv
http://url.data.humancellatlas.org/projects/a9c022b4-c771-4468-b769-cabcf9738de3.tsv
http://url.data.humancellatlas.org/projects/ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad.tsv
http://url.data.humancellatlas.org/projects/005d611a-14d5-4fbf-846e-571a1f874f70.tsv
http://url.data.humancellatlas.org/projects/1630e3dc-5501-4faf-9726-2e2c0b4da6d7.tsv
http://url.data.humancellatlas.org/projects/027c51c6-0719-469f-a7f5-640fe57cbece.tsv
http://url.data.humancellatlas.org/projects/ccd8370a-84b8-464d-a87e-e688ac3e4f62.tsv
http://url.data.humancellatlas.org/projects/8c3c290d-dfff-4553-8868-54ce45f4ba7f.tsv
http://url.data.humancellatlas.org/projects/b6dc9b93-929a-45d0-beb2-5cf8e64872fe.tsv
http://url.data.humancellatlas.org/projects/4129d036-67b9-4981-9d6d-3aaa235236d5.tsv
http://url.data.humancellatlas.org/projects/2043c65a-1cf8-4828-a656-9e247d4e64f1.tsv
http://url.data.humancellatlas.org/projects/dadbdb31-5f69-485b-85f3-b244b74123f1.tsv
http://url.data.humancellatlas.org/projects/5e6c0ede-5648-4b0e-83ce-4644c437b4c0.tsv
http://url.data.humancellatlas.org/projects/cddab57b-6868-4be4-806f-395ed9dd635a.tsv
http://url.data.humancellatlas.org/projects/209e6402-d854-49ea-815f-421dae5e3f4d.tsv
http://url.data.humancellatlas.org/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7.tsv

**Comment by theathorn** [comment]
These are mostly data sets from the May 2019 reingestion and areanu not displayed for the Japan demo.
Cleanup will be needed once reingestion is succesfully completed.
