### ISSUE TITLE
Replace direct DSS bucket access with caching of bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1032]
Cache bundle metadata verbatim in S3 so we can later access it during deletions without having to resort to directly accessing the bundle manifest and metadata files in the DSS main S3 bucket.

Each object in the cache should represent one bundle version. The objects key should be bundle and version separated by dot. TBD: what bucket and key prefix.

The cache will also accelerate reindexing.

![UNADJUSTEDNONRAW_thumb_91](https://user-images.githubusercontent.com/5143256/58137220-54fbe680-7be6-11e9-8aca-72f67df68206.jpg)

Note the second call to `get_bundle` which is crucial to eliminate races with deletions.

The green version in the diagram uses READ before WRITE to S3 and therefore has to deal with the resulting eventual read-after write consistency in S3. The black arrow indicates where the handling of the addition would have to be interrupted by a deletion AND for a false miss in the deletion handling to cause problems. The green version deals with that by retrying on misses.

The purple version does not READ before WRITE, does not have to deal with eventual consistency in S3 but does not accelerate reindexing or duplicate notifications.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-646)
┆Project Name: azul
┆Issue Number: AZUL-646

**Comment by theathorn** [comment]
Closing - DSS is deprecated.
