### ISSUE TITLE
First assertion with 13k failures

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1044]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-652)
┆Project Name: azul
┆Issue Number: AZUL-652

**Comment by jessebrennan** [comment]
This is the failing assertion
```
 	: AssertionError
Traceback (most recent call last):
  File "/var/task/app.py", line 155, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 275, in write
    indexer.aggregate(writer, tallies)
  File "/var/task/azul/indexer.py", line 167, in aggregate
    assert len(tallies) == len(actual_tallies)
AssertionError

```

**Comment by theathorn** [comment]
Fixed?

**Comment by jessebrennan** [comment]
This was fixed, likely as a result of #947 or #611

**Comment by jessebrennan** [comment]
This happened again during the last re-index.
```
: AssertionError
Traceback (most recent call last):
File "/var/task/app.py", line 175, in new_handler
return old_handler(self, event, context)
File "/var/task/chalice/app.py", line 1422, in __call__
return self.func(event_obj)
File "/var/task/app.py", line 293, in write
indexer.aggregate(tallies)
File "/var/task/azul/indexer.py", line 246, in aggregate
assert len(tallies) == len(actual_tallies)
AssertionError
```
![assertion-error-graph.png](https://images.zenhubusercontent.com/5bfc77a68ffeb454062a138a/ae80a13c-6ac8-40f5-90af-ab1b598c7bbc)

**Comment by melainalegaspi** [comment]
Hannes: "after the deletion of the bundles  in the first 3 blockers and the resolution of the 4th blocker trigger a reindex and determine if this issue still occurs."

**Comment by danielsotirhos** [comment]
Ticket addressed by "[Research most recent index failures #1693](https://github.com/DataBiosphere/azul/issues/1693)" (PR https://github.com/DataBiosphere/azul/pull/1716)
