### ISSUE TITLE
Integration test may fail during teardown

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1049]
This happens if `self.num_bundles` isn't yet set when teardown is called.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-654)
┆Project Name: azul
┆Issue Number: AZUL-654

**Comment by hannes-ucsc** [comment]
Example here: https://gitlab.explore.data.humancellatlas.org/azul/azul/-/jobs/130
