### ISSUE TITLE
Enable versioning for Terraform bucket

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1053]
It's possible to make some really crazy, silly mistakes that overwrite you Terraform state. Maintaining versioning on this bucket is good safeguard so that state can be recovered in case of emergency.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-656)
┆Project Name: azul
┆Issue Number: AZUL-656

**Comment by jessebrennan** [comment]
https://s3.console.aws.amazon.com/s3/buckets/org-humancellatlas-azul-dev-config/?region=us-east-1&tab=properties versioning should be selected. Assigning @hannes-ucsc to review.

**Comment by jessebrennan** [comment]
If there is a separate bucket for prod, I do not have access to it.

**Comment by hannes-ucsc** [comment]
Just enabled it for prod. Here is proof for multiple versions on `dev`:

<img width="1029" alt="Screen Shot 2019-08-07 at 3 04 03 PM" src="https://user-images.githubusercontent.com/5143256/62661064-c1a09a80-b924-11e9-8888-e0c25786bb52.png">

No such proof for `prod` yet. When demoing this, we will look at the prod bucket. Hopefully we'll have done a `prod` deployment by then, creating multiple versions of the files in that bucket.
