### ISSUE TITLE
Document destroy process for a deployment of Azul

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1054]
Currently my understanding is:
1) `cd terraform`
2) `make destroy`
3) wait 5 min for certificates to be destroyed
4) `make destroy` again to update terraform state
5) `cd ../lambdas/indexer`
6) `make delete`
7) `cd ../service`
8) `make delete`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-657)
┆Project Name: azul
┆Issue Number: AZUL-657

**Comment by hannes-ucsc** [comment]
Steps 3 and 4 are conditional on step 2 failing, correct?

Otherwise LGTM

**Comment by jessebrennan** [comment]
Yes, that's my understanding.
