### ISSUE TITLE
Integration tests may fail intermittently

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1060]
Not sure exactly what caused the first failure. Rerunning the tests allowed it to pass fine.

https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/1934

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-660)
┆Project Name: azul
┆Issue Number: AZUL-660

**Comment by hannes-ucsc** [comment]
Closing as dupe of #1174.

**Comment by jessebrennan** [comment]
Looks like this is happening again 

https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/4343
