### ISSUE TITLE
Add `file_uuid` and `file_version` columns to full metadata TSV

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1068]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-664)
┆Project Name: azul
┆Issue Number: AZUL-664

**Comment by hannes-ucsc** [comment]
See https://github.com/HumanCellAtlas/hca_bundles_to_csv/issues/12

**Comment by theathorn** [comment]
Automation is not required for General Availability. Removing from epic.
