### ISSUE TITLE
Export bundle data as participants to temporarily workaround Terra API limitations

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1070]
The Terra API for importing data does not currently support the `bundle` entity type, and this has been blocking progress on the overall handoff initiative. However, there are a couple of small changes that can be made as a temporary workaround to enable the HCA data to be imported to Terra. These are:

[ ] Change the filename in the BDBag from `samples.tsv` to `participants.tsv`
[ ] Change the header of the first column in this file from `entity:bundle_id` to `entity:participant_id`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-666)
┆Project Name: azul
┆Issue Number: AZUL-666

**Comment by theathorn** [comment]
Verified working in dev.
