### ISSUE TITLE
Replace `.` with `_` for entity ids in the HCA/Terra export file as a temporary workaround

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1071]
Currently, Terra does not allow a `.` in the entity id values of data it imports.
As a temporary workaround, replace all `.` characters in the values of the first column of the file exported from HCA to Terra. These are bundle FQIDs (<UUID>.<version>), which contain two `.` each.

This is a temporary workaround until Terra is changed to allow `.` in entity id values.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-667)
┆Project Name: azul
┆Issue Number: AZUL-667

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/blob/c4235bc4426259c8eaada435adb002e8155a7003/src/azul/service/responseobjects/hca_response_v5.py#L351

**Comment by theathorn** [comment]
Verified working in dev.
