### ISSUE TITLE
Support import of TSV with the bundle entity type through the Terra API

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1072]
https://broadworkbench.atlassian.net/browse/CA-496

The HCA handoff to Terra uses the `bundle` entity type, as recommended by the Broad.
However, the Terra API `https://app.terra.bio/#import-data?url=...` used by HCA does not currently support TSV files with the `bundle` entity type, and this support needs to be added to Terra/FireCloud for the HCA handoff to Terra to work.

I believe there are two independent code changes required:
* Enhance the FireCloud API to provide a new endpoint which is a variant of the existing `flexableImportEntities` endpoint that takes a URL as the source of the TSV data, rather than obtaining the TSV content from the POST body. This is necessary to support a URL pull model for scalability.

* Change the Terra API to expose the method above through the Terra `https://app.terra.bio/#import-data?url=...` API, perhaps with an additional query parameter identifying that that `flexableImportEntities` should be used for the import (or perhaps that is the new default?).

[edit: hannes-ucsc] Revert cf43fa6d94d0ea74178bdd96e35b8d90b170b3a9 when done.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-668)
┆Project Name: azul
┆Issue Number: AZUL-668

**Comment by theathorn** [comment]
Deprioritized as adopting the Avro/PFB format will render this redundant.

**Comment by theathorn** [comment]
@mikebaumann Is this why the Terra "TABLES" shows "participant" instead of "bundle"?

**Comment by theathorn** [comment]
Could be supported by Avro/PFB or flexibleImportEntities.
