### ISSUE TITLE
Allow '.' in entity identifiers for Terra

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1073]
https://broadworkbench.atlassian.net/browse/AS-116
https://broadworkbench.atlassian.net/browse/CA-495
https://broadworkbench.atlassian.net/browse/SATURN-1016

Currently, Terra/FireCloud does not allow the `.` (dot/period) character to be used in entity identifiers.
This is blocking the import of HCA data into Terra because the HCA TSV files use the `bundle` entity type and the entity id is the fully-qualified/canonical HCA bundle id, which has the format: <UUID>.<version>

This is reported to be a historical artifact as FireCloud formerly used a graph database that used `.` as the separator for navigation. However, that database is no longer being used and this constraint can likely be removed. However, careful code review and testing is required to ensure there are no other/remaining issues in Terra/FireClould that would present problems if `.` were used in entity ids.

[edit: @hannes-ucsc]

Revert 09a24cfc0bbb0fefc9569852862d74845a588745 when done.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-669)
┆Project Name: azul
┆Issue Number: AZUL-669

**Comment by theathorn** [comment]
From Cara: The Q4 deliverable for the handoff for  "Allow '.' in entity identifiers" is now complete and in production.

**Comment by achave11** [comment]
Why was this close?

**Comment by theathorn** [comment]
Hannes to verify if we can now undo our string replacement.

**Comment by theathorn** [comment]
Closing as this is deployed in Terra production.
Opened a separate ticket for the Azul work to resume use of periods.

**Comment by hannes-ucsc** [comment]
https://github.com/databiosphere/azul/issues/1493
