### ISSUE TITLE
Add Terra's Google Service Account for HCA to the HCA's Google Checkout buckets

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1078]
This entails adding an additional service account to the HCA DSS Google checkout bucket ACLs with Storage Object Viewer permissions. This is consistent with what is being done for the Broad's Mint team for cloud native URL access to the HCA DSS data.
It appears that this simply involves adding the service account identifier (name/email) to the HCA DSS `DSS_CHECKOUT_BUCKET_OBJECT_VIEWERS` environment variable.

The may be reassigned to the HCA DSS team, but is currently in the Azul project for visibility and to prompt that communication/collaboration with the DSS team.

For more information, please see: [Terra/Cromwell Access to Files Identified by DRS URIs for the HCA/Terra MVP](https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-674)
┆Project Name: azul
┆Issue Number: AZUL-674

**Comment by hannes-ucsc** [comment]
Please let's not create tickets about the creation of tickets. Because this is what this will ultimately end up being: a ticket in the data-store repo.

**Comment by mikebaumann** [comment]
For the MVP, the plan for allowing Terra/FireCloud access to the HCA Google data has changed from using a minimal HCA Bond provider to instead simply adding the Google Group GROUP_All_Users@firecloud.org will be added to the HCA Google checkout bucket ACL with the Storage Object Viewer role. Consequently, the changes described in this issue are no longer needed. 

The following document has been updated to reflect this change: [Terra/Cromwell Access to Files Identified by DRS URIs for the HCA/Terra MVP](https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg)

This issue was satisfied/completed by the following PR for the HCA DSS:
https://github.com/HumanCellAtlas/data-store/pull/2211
