### ISSUE TITLE
Add logging to Azul DRS endpoint that includes key request/response values 

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1079]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-675)
┆Project Name: azul
┆Issue Number: AZUL-675

**Comment by hannes-ucsc** [comment]
> Add logging to Azul DRS endpoint that includes key request/response values

While it's obvious which request elements are key (uuid and version), the same determination is not as obvious for the response. My commit adds logging of the first 1KiB of the response, but only if `AZUL_DEBUG` is set to 1.
