### ISSUE TITLE
Export bundle entity data as a single file using the Terra flexibleImportEntities endpoint (when available)

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1080]
~[edit @hannes-ucsc] Revert cf43fa6d94d0ea74178bdd96e35b8d90b170b3a9 when done.~

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-676)
┆Project Name: azul
┆Issue Number: AZUL-676

**Comment by theathorn** [comment]
Closing - will be superseded by Avro/PFB.
