### ISSUE TITLE
Terra allows some characters in column headers, yet prevents their use as workflow variables

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1089]
https://broadworkbench.atlassian.net/browse/CA-497
https://broadworkbench.atlassian.net/browse/SATURN-1018

Terra allows the dash (‘-‘) open bracket ('[') and close bracket (']') characters in imported column headers, yet prevents such columns from being used when configuring workflow variables. This is a problem, as the HCA data exported to Terra currently uses dash, open bracket, and close bracket extensively in column headers.

Excerpts from emails regarding the issue:

![image.png](https://images.zenhubusercontent.com/5a5fd4a94b5806bc2bc32d38/337db0f3-a080-4df0-a740-d0299606f70c)

The error message text is:
    Failed at line 1, column 9: identifier part expected

Googling around, I found this article that seemed potentially related:

Workspace Reference Data - "identifier part expected”
https://support.terra.bio/hc/en-us/community/posts/360042965272-Workspace-Reference-Data-identifier-part-expected-

The gist of the article is that Terra was having some problem (not clearly described) with dash `-` in variable names and that some kind of fix (not clearly described) was released a day ago.
Well, okay, the variable value I had configured was:

	this.bam-dos_url

So, I:
1. exported the workspace data TSV from Terra
2. replaced all dashes with underscore in the column headers
3. created a new workspace
4. imported the edited TSV
5. imported the md5sum workflow from Dockstore into the new workspace
6. reconfigured the workflow as I had before, but this time with this.bam_dos_url
7. and .. no more error!

So, it seems that although Terra allows dash in column header names, it does not allow column headers with a dash to be used as workflow variables?!?!?!
What was the nature of the fix that was reportedly made and released according to the article above?
Was it a fix to allow dash in variable names, or was it a change to remove dash from column headers in the reference data?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-680)
┆Project Name: azul
┆Issue Number: AZUL-680

**Comment by hannes-ucsc** [comment]
Maybe we should switch to double underscore `__`?

**Comment by mikebaumann** [comment]
For what it’s worth, double underscore was the first alternative that came to my mind as well.

**Comment by mikebaumann** [comment]
This same problem appears to apply to the '[' and ']', which are an important part of the current HCA algorithm for flattening the HCA metadata into column headers.

I'll update the description of this issue accordingly.

![image.png](https://images.zenhubusercontent.com/5a5fd4a94b5806bc2bc32d38/68bcba71-b517-4ff7-8510-518c1192f4a6)

**Comment by theathorn** [comment]
Deprioritized as adopting the Avro/PFB format will render this redundant.

**Comment by theathorn** [comment]
Moving to Avro without changing schema does not fix this issue.
