### ISSUE TITLE
Broad: Terra/Cromwell/Martha does not work for DRS URIs that resolve to cloud native URLs that are accessible without any additional credentials

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1090]
Terra/Cromwell as it stands does not appear to work for DRS URIs that resolve to cloud-native URLs and are accessible without any additional credentials, either because the cloud-native URLs are publicly accessible or are accessible by the Terra user’s Proxy Group.

Excerpt from email describing this issue:

Reviewing the workflow log, I noticed that the dev deployment of the HCA Data Browser (https://dev.data.humancellatlas.org/explore/projects) is using the HCA DSS staging deployment (intentionally, and for good reason).
So, I added the Terra/FC Proxy Groups to the HCA DSS Google checkout bucket for staging instead (“org-humancellatlas-dss-checkout-staging”).
I then tried rerunning the same md5sum workflow configuration from the same Terra workspace … and got the same result, failure, with the same log content as before.

Looking for other possible problems, I again verified that Martha is returning the correct Google cloud native URL for the DRS URI in the Terra workspace, which it is:

 $ curl --request POST \
>   --url https://us-central1-broad-dsde-prod.cloudfunctions.net/martha_v2 \
>   --header 'content-type: application/json' \
>   --data '{ "url": "dos://service.dev.explore.data.humancellatlas.org/7c800467-9143-402f-b965-4e7cad75c1e6?version=2019-05-26T130511.722646Z" }'
{"dos":{"data_object":{"id":"7c800467-9143-402f-b965-4e7cad75c1e6","urls":[{"url":"https://service.dev.explore.data.humancellatlas.org/dss/files/7c800467-9143-402f-b965-4e7cad75c1e6?version=2019-05-26T130511.722646Z&replica=aws&wait=1&fileName=merged.bam"},{"url":"gs://org-humancellatlas-dss-checkout-staging/blobs/8713ae74c6378311f1f3f0c2ead08a2402d90035d7823bbbc2d68d147f898789.06af02fe3b4bf718cd7d4ec35e3f624387548b86.a34f51039b67d4bf3418c5ad1b94a1ea.c6c25e15"}],"size":"22403106","checksums":[{"checksum":"8713ae74c6378311f1f3f0c2ead08a2402d90035d7823bbbc2d68d147f898789","type":"sha256"}],"aliases":["merged.bam"],"version":"2019-05-26T130511.722646Z","name":"merged.bam"}}}

I then checked what happens when Martha is invoked with a bearer token, as it is from Cromwell.
Although I just used a bogus bearer token value, the results seem informative:

$   curl --request POST \
>   --url https://us-central1-broad-dsde-prod.cloudfunctions.net/martha_v2 \
>   --header 'content-type: application/json' \
>   --header 'Authorization: Bearer ABC123' \
>   --data '{ "url": "dos://service.dev.explore.data.humancellatlas.org/7c800467-9143-402f-b965-4e7cad75c1e6?version=2019-05-26T130511.722646Z" }'
{"status":401,"response":{"req":{"method":"GET","url":"broad-bond-prod.appspot.com/api/link/v1/dcf-fence/serviceaccount/key","headers":{"user-agent":"node-superagent/3.8.3","authorization":"Bearer ABC123"}},"header":{"content-type":"application/json","x-cloud-trace-context":"23a2ab1fc041e2219401d9b3adcac1b7;o=1","date":"Thu, 13 Jun 2019 13:22:17 GMT","server":"Google Frontend","content-length":"204","connection":"close"},"status":401,"text":"{\n \"error\": {\n  \"code\": 401, \n  \"errors\": [\n   {\n    \"domain\": \"global\", \n    \"message\": \"Invalid authorization token\", \n    \"reason\": \"required\"\n   }\n  ], \n  \"message\": \"Invalid authorization token\"\n }\n}"}}

It looks like if a bearer token is provided in the request to Martha, Martha tries getting credentials from the “dcf-fence” Bond provider, and in this case, fails.
This is consistent with the behavior I expected from reading the Martha code (and why I gave this less than a 50/50 chance yesterday :).

So, it seems some tweaks are needed to the Broad Martha/Bond plumbing to handle the case of DRS returning a cloud native URL that is accessible without additional credentials / service account key. This case may legitimately arise either because the cloud native URL is publicly accessible, or is in a bucket that the Terra user’s service account has access to.

If my interpretation is correct, this needs to be fixed.

The name of the workspace I have been using for these experiments is "mbaumann test workflow no dash headers 20190612_2029” and I have added Alex, Brad and Brian O. as Owners.
Feel free to share it with whomever else you like to further the investigation. Again, it is all public data.

I have also added "GROUP_All_Users@firecloud.org” to the “org-humancellatlas-dss-checkout-staging” bucket with the “Storage Object Viewer” role, so theoretically you all should be able to access the data in it.

At this point, I think I have done all I can and the ball is in the Broad’s court.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-681)
┆Project Name: azul
┆Issue Number: AZUL-681

**Comment by mikebaumann** [comment]
This issue requires changes to two Broad components, Martha and Cromwell.

The changes to Martha are being addressed in this PR:
https://github.com/broadinstitute/martha/pull/125

A change is also required to Cromwell to handle the valid case of a DRS URI resolving to a Google cloud-native URL without any additional credentials. The current problematic code is as follows:
https://github.com/broadinstitute/cromwell/blob/6d737b056aca1f3c56c0e7bc212267ea912812bc/filesystems/drs/src/main/scala/cromwell/filesystems/drs/DrsPathBuilderFactory.scala#L66

**Comment by bradtaylor** [comment]
Martha PR has been merged and should be released tomorrow
https://github.com/broadinstitute/martha/pull/125

**Comment by mikebaumann** [comment]
Hi @bradtaylor, thanks for the great news!
I can see by the following command that Martha in the Broad dev deployment is now working as needed by HCA!

```
$   curl --request POST \
>    --url https://us-central1-broad-dsde-dev.cloudfunctions.net/martha_v2 \
>    --header 'content-type: application/json' \
>    --header 'Authorization: Bearer ABC123' \
>    --data '{ "url": "dos://service.dev.explore.data.humancellatlas.org/7c800467-9143-402f-b965-4e7cad75c1e6?version=2019-05-26T130511.722646Z" }'
{"dos":{"data_object":{"id":"7c800467-9143-402f-b965-4e7cad75c1e6","urls":[{"url":"https://service.dev.explore.data.humancellatlas.org/dss/files/7c800467-9143-402f-b965-4e7cad75c1e6?version=2019-05-26T130511.722646Z&replica=aws&wait=1&fileName=merged.bam"},{"url":"gs://org-humancellatlas-dss-checkout-staging/blobs/8713ae74c6378311f1f3f0c2ead08a2402d90035d7823bbbc2d68d147f898789.06af02fe3b4bf718cd7d4ec35e3f624387548b86.a34f51039b67d4bf3418c5ad1b94a1ea.c6c25e15"}],"size":"22403106","checksums":[{"checksum":"8713ae74c6378311f1f3f0c2ead08a2402d90035d7823bbbc2d68d147f898789","type":"sha256"}],"aliases":["merged.bam"],"version":"2019-05-26T130511.722646Z","name":"merged.bam"}}}
```
That is not yet the case in the Broad production deployment, but it sounds like it will be there soon, too!

As I know you are aware, we still need the Cromwell change identified in the following PR for the HCA data to flow, and system integration testing to begin:
https://github.com/DataBiosphere/azul/issues/1090

Hoping that will be arriving soon, too! :)

**Comment by mikebaumann** [comment]
Hi @bradtaylor, thanks for the great news!
I can see by the following command that Martha in the Broad dev deployment is now working as needed by HCA!

$   curl --request POST \
>    --url https://us-central1-broad-dsde-dev.cloudfunctions.net/martha_v2 \
>    --header 'content-type: application/json' \
>    --header 'Authorization: Bearer ABC123' \
>    --data '{ "url": "dos://service.dev.explore.data.humancellatlas.org/7c800467-9143-402f-b965-4e7cad75c1e6?version=2019-05-26T130511.722646Z" }'
{"dos":{"data_object":{"id":"7c800467-9143-402f-b965-4e7cad75c1e6","urls":[{"url":"https://service.dev.explore.data.humancellatlas.org/dss/files/7c800467-9143-402f-b965-4e7cad75c1e6?version=2019-05-26T130511.722646Z&replica=aws&wait=1&fileName=merged.bam"},{"url":"gs://org-humancellatlas-dss-checkout-staging/blobs/8713ae74c6378311f1f3f0c2ead08a2402d90035d7823bbbc2d68d147f898789.06af02fe3b4bf718cd7d4ec35e3f624387548b86.a34f51039b67d4bf3418c5ad1b94a1ea.c6c25e15"}],"size":"22403106","checksums":[{"checksum":"8713ae74c6378311f1f3f0c2ead08a2402d90035d7823bbbc2d68d147f898789","type":"sha256"}],"aliases":["merged.bam"],"version":"2019-05-26T130511.722646Z","name":"merged.bam"}}}
That is not yet the case in the Broad production deployment, but it sounds like it will be there soon, too!

As I know you are aware, we still need the Cromwell change identified here for the HCA data to flow, and system integration testing to begin.
Hoping that will be arriving soon, too! :)

**Comment by theathorn** [comment]
@mikebaumann to check if PR has been merged to Master and be deployed to production 8/7/19.

**Comment by mikebaumann** [comment]
I verified this is working by exporting data from the HCA data browser to Terra then running a workflow on that data, which completed successfully.

**Comment by theathorn** [comment]
Closing as verified..
