### ISSUE TITLE
Temporary workaround: replace special characters in manifest column headers with underscore(s)

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1091]
Terra allows the dash (‘-‘) and square bracket ("[" and "]") characters in imported column headers, yet prevents such columns from being used when configuring workflow variables. This is a problem, as the HCA data exported to Terra currently uses these characters extensively in column headers.

Proposed workaround is to replace these characters with single or double underscores until Terra documents and enforces a set of allowable non-alphanumeric characters.

The workaround will allow the Cambridge demo on June 20 to proceed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-682)
┆Project Name: azul
┆Issue Number: AZUL-682

**Comment by hannes-ucsc** [comment]
Brackets also need to be replaced: https://github.com/DataBiosphere/azul/issues/1089#issuecomment-501762327

**Comment by hannes-ucsc** [comment]
Demoed on 7/22
