### ISSUE TITLE
Reindexing seems to be slower since we added bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1093]
During reindexing, when number of unindexed bundles reached zero we used to have on 10k unindexed documents. We now have several 100k. I'm seeing a significant increase in ScanErrors (#1031).

We should verify that the newly added `bundles` index is indeed the culprit here by disabling indexing into the bundles index (don't revert the commit), add `if False` conditionals disable the sections of code for that index.

We should also try out reducing the number of nodes and instead increasing the instance type. There are various sources out there that indicate that reducing # of nodes while keeping the overall cluster memory the same. So we should halve the # number of nodes, double the instance type, and maybe increase the instance type even more to accommodate the bundles index.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-683)
┆containerName: azul
┆Issue Number: AZUL-683

**Comment by hannes-ucsc** [comment]
I observed the above on the shared `dev` cluster. I did not look at the `prod` cluster yet.

**Comment by jessebrennan** [comment]
Next week I will be release engineer and will observe if this is still a problem while reindexing production.

**Comment by hannes-ucsc** [comment]
Can't reproduce.
