### ISSUE TITLE
Clean up all unused deployments

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1094]
We ran out of buckets and I do remember seeing a bunch of unused deployments, each deployment creates at least one bucket.

Namely: 

* david4096
* noopdog
* mjkrause
* jesse1 (unless Jesse prefers to have two)

Ask these individuals to delete their deployments. 

```
make -C lambdas/indexer delete
make -C lambdas/service delete
make -C terraform destroy
```

Document the above in a README section.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-684)
┆Project Name: azul
┆Issue Number: AZUL-684

**Comment by hannes-ucsc** [comment]
@theathorn to triage

**Comment by GPelayo** [comment]
The new tfstates of the old deployments (`noopdog`, `david4096`, `mjkrause`) in the `org-humancellatlas-azul-dev-config` bucket list no longer list any resources. Also, the resources listed in the old tfstates are no longer deployed in the AWS HCA account.

**Comment by hannes-ucsc** [comment]
There are some roles in IAM left over from older deployments. Not sure why they didn't get cleaned up. Maybe a Chalice bug or, actually, I think we set them up via a script from `lambdas/*/Makefile`.

Anyhow, please check IAM for left overs and remove if necessary.

**Comment by GPelayo** [comment]
I checked the IAM and found and deleted the roles from the `mjkrause`, `noopdog`, and `david4096` deployments.

**Comment by GPelayo** [comment]
Closing issue. Left over roles have been deleted

**Comment by hannes-ucsc** [comment]
There are still roles left over for non-existing deployments. Please create an exhaustive list of deployment currently in active (!) use. Post the list here. Delete all left-over roles belonging to deployments not in that list.

**Comment by GPelayo** [comment]
Here's a list of active developer deployments currently in use:

- abraham
- daniel
- geryl
- hannes
- jessie0

Also for completion's sake, here's a list of the main deployments,

- dev
- sandbox
- integration
- staging

**Comment by hannes-ucsc** [comment]
@GPelayo, looks good. You can go ahead and delete any cloud resources associated with any deployments not mentioned in your two lists. The only deployment-specific resources we shouldn't delete for now are the TF state objects in our config bucket.

**Comment by GPelayo** [comment]
Removed the following resources with the listed deployments. Should I also remove the CloudWatch logs from these unused deployments, @hannes-ucsc? Do think there might be anything substantial in the logs?

IAM Role
- dnastack
- elasticstest
- hancock
- jesse
- jesse1
- jesse2
- jyo
- samples

API Gateways
- dnastack
- hancock
- alex (+ Base Path Mappings)
- jyo

AMC Certificates
- dnastack2

Route 53 (A and CNAME)
- alex

**Comment by hannes-ucsc** [comment]
I think the stipulation is to retain logs for 5 years. Looks like you are done.
