### ISSUE TITLE
Hide integration test projects

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1095]
@hannes-ucsc Keep in mind that these (integration tests) will show up while the test is running but should disappear when the test is finished. If those projects showing up even temporarily is a problem. We could hide it by default. Similar problem to not showing projects in active ingestion.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-685)
┆Project Name: azul
┆Issue Number: AZUL-685

**Comment by hannes-ucsc** [comment]
We don't have DCP-wide IT in DCP/2.
