### ISSUE TITLE
Per project analysis and summary results

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1096]
Create a processing framework and web service that supplies, per project in the HCA, summary statistics and plots. These will be shown on individual project pages in the HCA portal.

We need to start showing some analysis and summary results on project pages in the HCA portal, for example:

https://prod.data.humancellatlas.org/explore/projects/74b6d569-3b11-42ef-b6b1-a0454522b4a0

Here are the steps overall, please make sub-stories as needed:

1) create a cron job triggered Python script that will iterate over the available projects in the HCA DCP on a nightly basis (OK to hit Azul to find this list) and, for each, retrieve the loom-based gene expression matrix for that project from the matrix service

2) take that gene by cell matrix per project and then use ScanPy to generate:
  - genes that yield the highest fraction of counts in each single cells, across all cells (plot and data table)
  - violin plot of the computed quality measures (plot)
  - Identify highly-variable genes (plot) and extract the table of the top 20

3) this output should then be served behind a flask based web service of your own design, so that the results can be called by Javascript components in the portal to display each.

4) run this process nightly so the results are no more than 24 hours old

5) work with the portal team and Clever Canary to incorporate this information in the portal project pages

This will help quite a bit: https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html
It gives you the code you need to do what’s requested.

Also, see the portal and matrix service developers for how to call the matrix service: https://prod.data.humancellatlas.org/apis/api-documentation/matrix-service-api

For more general info see https://scanpy.readthedocs.io/en/stable/index.html

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-686)
┆Project Name: azul
┆Issue Number: AZUL-686

**Comment by theathorn** [comment]
@mjkrause Please take the lead on breaking into stories and ping @briandoconnor when you have questions.

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

@mjkrause can you link stories to this epic?

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

See Michael's google doc here:

https://docs.google.com/document/d/1l-_Er-mltFMuaPRkTPw9YYjUMuijqacZWdNCag3mOGU/edit#heading=h.rqdyitauun9e

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

I’ve manually linked the (already-linked in ZenHub) stories in Jira as well.

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

Thanks, [~theathor]

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/1.
