### ISSUE TITLE
Create design spec for matrix summary stats

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1099]
Find the design specification for the per-project analysis and summary statistics (#1096) at https://docs.google.com/document/d/1l-_Er-mltFMuaPRkTPw9YYjUMuijqacZWdNCag3mOGU/edit?usp=sharing

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-688)
┆Project Name: azul
┆Issue Number: AZUL-688
┆Epic: jira:ucsc-cgl.atlassian.net:18368

**Comment by NoopDog** [comment]
@mjkrause here is the list of buckets from our slack convo:

The bucket names are:

dev.project-assets.data.humancellatlas.org
ux-dev.project-assets.data.humancellatlas.org
integration.project-assets.data.humancellatlas.org
staging.project-assets.data.humancellatlas.org
project-assets.data.humancellatlas.org

Let’s use a new sub folder called project-stats to hold the images and any image related metadata. 

e.g. /project-assets/project-stats

Giving a prod url of:

project-assets.data.humancellatlas.org/project-assets/project-stats

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/9.
