### ISSUE TITLE
check metadata compatibility with all boxes

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#11]
this is related to continuous integration. We need to verify functionality with all boxes when a new metadata release is made.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-11)
┆Project Name: azul
┆Issue Number: AZUL-11

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
