### ISSUE TITLE
Add support for subscribing to DSS with personal service account creds

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#110]
Follow-up on #104

Don't use the shared service account and its creds from AWS secrets manager, but use the current developers' service account.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-89)
┆Project Name: azul
┆Issue Number: AZUL-89

**Comment by theathorn** [comment]
Closing - DSS is deprecated.
