### ISSUE TITLE
Evaluate Avro as an alternative to the Broad's flexible entity TSV format for import to Terra

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1103]
Apache Avro (https://avro.apache.org/) is a space-efficient serialization mechanism for structured data. Portable Format for Biomedical Data (PFB) is a specific Avro schema designed by the University of Chicago's Gen3 team to support the interchange of biomedical information (e.g., phenotypic/clinical data records, etc.). This format is being used to handoff controlled access clinical metadata from Gen3 to Terra and Seven Bridges as part of the DataSTAGE/biodata Catalyst and AnVIL programs. The Broad's Terra team is currently developing support for the highly-scalable importation of PFB data. The Avro/PFB format is also a candidate for future standardization by GA4GH as a data-interchange format.

HCA's use of Avro/PFB overs multiple advantages over the current BDBag export format:
* The BDBag support in Terra is legacy code from the Data Commons Pilot program and is currently only used by HCA. Future support for the BDBag format is questionable at best.
* The current BDBag support in Terra requires tables/entity-types to be named "participants" or "samples", which is inappropriate for HCA data.
* The current BDBag format faces substantial scalability limitations for both export and import, which are unlikely to change. 
* Avro/PFB enables the creation/use of multiple tables/entity-types within a single file and enables data to be exported as a graph structure if desired.

Currently, the documentation regarding the PFB format is very limited. The University of Chicago Gen3 team said they will be publishing a paper on that soon.

Evaluate Avro and the schema and tools presented by U.Chicago as an export/import format to Terra, relative to the Broad's flexible entity TSV format/API.

Done when:
* The relative strengths/weaknesses of the two formats have been evaluated wrt the HCA requirements
* The HCA effort to change to each of these formats (independently) has been sized

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-692)
┆Project Name: azul
┆Issue Number: AZUL-692
┆Epic: Avro format hand-off

**Comment by theathorn** [comment]
Closing on favor of #1403.

**Comment by theathorn** [comment]
Closing on favor of #1430.
