### ISSUE TITLE
Create roadmap for HCA handoff to Terra

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1104]
Create a roadmap of HCA handoff to Terra for the next 6 to 12 months to facilitate coordination, resource planning, scheduling, etc. In addition to finishing the MVP, there are multiple upcoming changes that will require changes/evolution of the HCA handoff to Terra.
These include, but are not limited to:
* Change in export format
* Changes required by HCA support for controlled access data
* Support for GA4GH DRS 1.0
* Support for matrix files
* ...

Done when:
A draft roadmap has been created, and negotiations/refinement can begin.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-693)
┆containerName: azul
┆Issue Number: AZUL-693

**Comment by theathorn** [comment]
Covered by #606.
