### ISSUE TITLE
Create Jupyter notebook to demonstrate per project summary plots

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1105]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-694)
┆Project Name: azul
┆Issue Number: AZUL-694
┆Epic: jira:ucsc-cgl.atlassian.net:18368

**Comment by theathorn** [comment]
https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/8.
