### ISSUE TITLE
Create class to compute summary statistics from matrix

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1106]
* get list of URLs of matrix loom files persisted on S3
* download each matrix loom file
* Explore utility of package loompy to iterate over (or scan) columns / rows of matrix in loom file
    * create genes-by-cells matrix in memory
    * this may not be necessary if we can use loompy's `map()` or `scan()` methods, in combination with numpy's summary statistics methods
    * explore whether matrix files from different library construction methods require differential processing
* Utilize package ScanPy to create plots of relevant values
* Upload and persist on S3 (for later use by portal team to display it)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-695)
┆Project Name: azul
┆Issue Number: AZUL-695
┆Epic: jira:ucsc-cgl.atlassian.net:18368

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/7.
