### ISSUE TITLE
Request matrix from project

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1108]
* get list of projects using Azul's /repository/projects endpoint or the HCA matrix-service API
* check if matrix file exists for project, if so, requests matrix in loom format (that persists the matrix on S3 and returns a (signed?)URL to it)
* return list of all matrix URLs S3

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-696)
┆Project Name: azul
┆Issue Number: AZUL-696
┆Epic: jira:ucsc-cgl.atlassian.net:18368

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/2.
