### ISSUE TITLE
Display summary stats plots on portal

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1109]
Work with @NoopDog and the portal team to display summary statistics plots.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-697)
┆Project Name: azul
┆Issue Number: AZUL-697
┆Epic: jira:ucsc-cgl.atlassian.net:18368

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/3.
