### ISSUE TITLE
Use microservice to invoke summary stats functionality

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1110]
Summary statistics should be computed per project once a day. Discuss with @hannes-ucsc whether this should be part of Azul's `webservice` Lambda, or whether it should run in a separate service.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-698)
┆Project Name: azul
┆Issue Number: AZUL-698
┆Epic: jira:ucsc-cgl.atlassian.net:18368

**Comment by mjkrause** [comment]
@hannes-ucsc  and I found that the deployment package size exceeds the limit allowed for an AWS Lambda. The main reason is the size of large libraries in that package, such as `scipy`, `scanpy`, `pandas` and `numpy`, all of which are installed when `scanpy` is installed. The uncompressed size of the deployment package was > 250 MB, [exceeding the limit](https://docs.aws.amazon.com/lambda/latest/dg/limits.html). 
That observation makes the approach of using an AWS Lambda to post summary figures to S3 not viable.

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/6.
