### ISSUE TITLE
Include summary stats functionality in integration test

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1111]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-699)
┆Project Name: azul
┆Issue Number: AZUL-699
┆Epic: jira:ucsc-cgl.atlassian.net:18368

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/4.
