### ISSUE TITLE
Exclude old ICA dataset in prod

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#1112]
The ICA (Regev, Census of Immune Cells) project has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5bffae409460a300074f3815; project UUID: 179bf9e6-5b33-4c5b-ae26-96c7270976b8) please be excluded from the Browser.

The new version of the dataset (submission ID: 5d1c67c688fa640008aff7cc; project UUID: cc95ff89-2e68-4a08-a234-480eca21ce79) is exported and has already started appearing in the Browser, with additional metadata! 👍

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-700)
┆Project Name: azul
┆Issue Number: AZUL-700

**Comment by malloryfreeberg** [comment]
@xbrianh

**Comment by theathorn** [comment]
Exclusion from the Azul index will require a reindex unless we tombstone the older project instead.
If we do the reindex let's cleanup the current blacklist to remove all the projects that have already been tombstoned.
