### ISSUE TITLE
DRS 1.0 Support

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1115]
DRS 1.0.0 is now officially released and the specifications are here:
* DRS main page: https://ga4gh.github.io/data-repository-service-schemas/
* Specification (HTML): https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.0.0/docs/
* Swagger API: https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.0.0/swagger-ui/#/DataRepositoryService/

There are a few factors driving when this support should be added:

Terra will be moving from using DOS to only supporting DRS, likely sometime in 2020.
The Broad needs all their partners using DOS (primarily(/only?) UChicago and HCA) to add support for DRS before making that switch, and it may take a while for UChicago to add DRS support.

The pending/upcoming integration of HCA and Seven Bridges should use DRS (1.0.0) from the start.

Fortunately, the DOS and DRS API endpoint paths are different, so it is very feasible and appropriate to add support for DRS while retaining support for DOS. This enables HCA to add DRS support now (e.g. for the Seven Bridges integration), while still allowing the current integration with Terra to continue working until Terra switches over to using DRS as well.

Architecturally, HCA support for DRS is really in the scope/domain of the HCA Data Store.
The current HCA DOS support was added to the Azul web service largely out of expediency for the HCA/Terra MVP. Now that DRS 1.0.0 has been finalized, it seems like a good time for the HCA Data Store to pick up the responsibility for supporting DRS. The DRS API could either be "built-in" to the HCA Data Store _per se_ or be added as an ancillary service, at the discretion of the HCA Data Store team. In any case, now seems like a good time to consider that transition. The DOS support in Azul could then be deprecated and perhaps eventually removed, taking into account the references that exist in Terra user workspaces. This migration should be facilitated by the format of the `drs://` URIs currently exported by the HCA Data Browser to Terra, as these URIs do *not* include the full canonical DOS path, but instead just a hostname, an HCA file id (UUID), and a version. The Broad's Martha service currently inserts the necessary DOS path elements into the given URI before accessing the DOS endpoint to perform the resolution. So, when the time comes for Terra to transition to DRS, Martha can substitute in the DRS path elements (and perform any other necessary transformations to the URI) instead. As I recall, the hostname in the `drs://` URI currently exported by HCA (`drs.data.humancellatlas.org`) can also be retargeted to the HCA Data Store provided service when it is available, further facilitating the migration.

The HCA DRS support should support presigned URLs as the data access mechanism, as I believe this is the mechanism that should be used for the Seven Bridges integration, and eventually be used by Terra. Cloud-native URLs (e.g., "gs://") could also be provided for as long as they are required by Terra.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-702)
┆Project Name: azul
┆Issue Number: AZUL-702
┆Epic: Terra hand-off

**Comment by theathorn** [comment]
Michael, when should we be doing this?

**Comment by theathorn** [comment]
Evaluate difficulty and estimate.

**Comment by mikebaumann** [comment]
Hi @jessebrennan, I see this is in progress now. Is the plan to have DRS 1.0 support be provided by the HCA Data Store, rather than the Azul web service? I think the former is the right way to go, yet I wanted to check where that decision stands at this point. It's not my decision to make, although I am an interested party. :-)
Thanks!

**Comment by jessebrennan** [comment]
@mikebaumann the plan is for https://github.com/HumanCellAtlas/data-store/issues/1893 and this ticket to be worked on simultaneously, with the assumption that this one will finish first, but will be phased out in place of the DSS implementation when it's ready. This way other Azul work is unblocked as fast as possible, but the final implementation will live in the DSS.

**Comment by jessebrennan** [comment]
To avoid triggering multiple checkout with the DSS, the token will need to be encoded into the access id for DRS. Otherwise, the translation to DRS will be straightforward.
