### ISSUE TITLE
Health endpoint overloading ES when doing all API endpoints

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1124]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-705)
┆Project Name: azul
┆Issue Number: AZUL-705

**Comment by achave11** [comment]
- Need to fix test that were changed from 503 to 200 in order to pass API endpoints tests.

**Comment by achave11** [comment]
Revert expected when fixed
```
    def _expected_api_endpoints(self, endpoint_states: Mapping[str, bool]) -> JSON:
        # FIXME https://github.com/DataBiosphere/azul/issues/1124
        return {
            'api_endpoints': {
                'up': all(up for endpoint, up in endpoint_states.items()),
                **({
                    config.service_endpoint() + endpoint: {
                        'up': up
                    } if up else {
                        'up': up,
                        'error': f'503 Server Error: Service Unavailable for url: {config.service_endpoint()}{endpoint}'
                    } for endpoint, up in endpoint_states.items()
                })
            }
        }
```

**Comment by jessebrennan** [comment]
When hitting the original `/health` endpoint with the Route 53 health check the request interval was 30 seconds. According to AWS docs, there are ~15 health checkers running which means that a request is sent about every 2-3 seconds (closer to 2 unless the request takes a long time). The health check for the service sends a request about once ever 2 seconds. The health check for the indexer also hits `/health/basic` so the indexer receives about 1 request per second.

@GPelayo's change to the health endpoint which added further requests to 5 other endpoint caused the webservice to receive ~6 requests per second. As this change propagated to the higher environments the shared Elasticsearch instance was being overwhelmed with ~18 requests per second.

The first and simplest fix was to revert Geryl's change. This helped.

Also we plan to reduce the frequency of health check polling to about once every 20 seconds.

**Comment by jessebrennan** [comment]
At first we thought that @achave11's metadata generation changes were causing the slow indexing so these changes were reverted in an attempt to fix Azul. These changes will be reinstated.
