### ISSUE TITLE
Exclude old Tabula Muris dataset in prod

### ISSUE THREAD

**Issue by cjvillar** [DataBiosphere/azul#1128]
The Tabula Muris dataset has been re-ingested in prod.

Could the older version of the dataset (submission ID:5bb1f6172b39cd00070f18cf ; project UUID: f306435b-4e60-4a79-83a1-159bda5a2c79) please be excluded from the Browser.

The new version of the dataset (submission ID: 5d24eda088fa640008b02b26 ; project UUID: e0009214-c0a0-4a7b-96e2-d6a83e966ce0 ) 

 Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-706)
┆Project Name: azul
┆Issue Number: AZUL-706

**Comment by theathorn** [comment]
I don't see the new project UUID in prod, either in the tracker or in the Data Browser.
Also the SOP is to raise a ticket in data-store to tombstone the old project rather than maintain a Data Browser black list.

**Comment by cjvillar** [comment]
Thanks, @theathorn I just found out about the change of policy today. I prematurely made this ticket when I hit the submit button for the new TM submission. I assumed it would actually submit and there would be a need to Tombstone the old project. This wasn't the case.   I'll close this ticket.

**Comment by jahilton** [comment]
We'll use the ticket in data-store to track the desired action: https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-store/2268
