### ISSUE TITLE
Update statistics on Home Page at regular intervals

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#113]
The Data Portal Home Page has summary statistics for Cells/Organs/Donors/Projects/Labs (the blue bar) and per-organ cell counts for the human body hover-over.
We need a way to update these counts when new bundles are indexed.
Perhaps a background job that runs once an hour or once a day?

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-91)
┆Project Name: azul
┆Issue Number: AZUL-91
┆Epic: Data Portal Home Page integration with Browser

**Comment by theathorn** [comment]
Relates to #47, #51 and #89.

**Comment by hannes-ucsc** [comment]
PR #152 fixes #47. That concludes the work in Azul that was necessary to support periodically updated stats on the portal home page. Work on the portal continues here.

https://github.com/HumanCellAtlas/data-portal/issues/175
https://github.com/HumanCellAtlas/data-portal/issues/176
