### ISSUE TITLE
Support the Avro/PFB format for hand-off to tertiary portals

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1132]
┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-708)
┆containerName: azul
┆Issue Number: AZUL-708

**Comment by bvizzier-ucsc** [comment]
@hannes-ucsc : "Made obsolete by: https://github.com/DataBiosphere/azul/issues/2693"
