### ISSUE TITLE
Update subscription to DSS to only receive data adhering to compatible schemas

### ISSUE THREAD

**Issue by maniarathi** [DataBiosphere/azul#1140]
This is required in order to receive data that adheres to a schema versions with which data browser/Azul is compatible.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-713)
┆Project Name: azul
┆Issue Number: AZUL-713

**Comment by maniarathi** [comment]
It looks like I am not able to modify the metadata about this ticket so I will write it down here:

Assignee: maniarathi
Milestone: Q3 2019 Milestone 2
Estimate: 2
Epics: https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/438

**Comment by theathorn** [comment]
This should be an optional step for each component, and Azul will opt out.
