### ISSUE TITLE
Generate TSVs and move TSV and matrix files to the project-asset buckets

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#1141]
From the comments thread in https://github.com/HumanCellAtlas/data-browser/issues/708.

Regenerate Project TSVs, and populate the `project-assets.data.humancellatlas.org` bucket with the working matrix files and newly generated TSVs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-714)
┆Project Name: azul
┆Issue Number: AZUL-714

**Comment by GPelayo** [comment]
Links to the Project TSVs
https://prod.data.humancellatlas.org/project-assets/project-metadata/005d611a-14d5-4fbf-846e-571a1f874f70.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/008e40e8-66ae-43bb-951c-c073a2fa6774.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/027c51c6-0719-469f-a7f5-640fe57cbece.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/2043c65a-1cf8-4828-a656-9e247d4e64f1.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/29f53b7e-071b-44b5-998a-0ae70d0229a4.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/74b6d569-3b11-42ef-b6b1-a0454522b4a0.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/8c3c290d-dfff-4553-8868-54ce45f4ba7f.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/90bd6933-40c0-48d4-8d76-778c103bf545.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/a29952d9-925e-40f4-8a1c-274f118f1f51.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/a9c022b4-c771-4468-b769-cabcf9738de3.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/c4077b3c-5c98-4d26-a614-246d12c2e5d7.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/cc95ff89-2e68-4a08-a234-480eca21ce79.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/cddab57b-6868-4be4-806f-395ed9dd635a.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/f306435b-4e60-4a79-83a1-159bda5a2c79.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/f81efc03-9f56-4354-aabb-6ce819c3d414.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/f83165c5-e2ea-4d15-a5cf-33f3550bffde.tsv
https://prod.data.humancellatlas.org/project-assets/project-metadata/f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc.tsv

Links to Matrix Files
https://prod.data.humancellatlas.org/project-assets/project-matrices/2043c65a-1cf8-4828-a656-9e247d4e64f1.csv.zip
https://prod.data.humancellatlas.org/project-assets/project-matrices/2043c65a-1cf8-4828-a656-9e247d4e64f1.loom
https://prod.data.humancellatlas.org/project-assets/project-matrices/2043c65a-1cf8-4828-a656-9e247d4e64f1.loom.zip
https://prod.data.humancellatlas.org/project-assets/project-matrices/2043c65a-1cf8-4828-a656-9e247d4e64f1.mtx.zip
https://prod.data.humancellatlas.org/project-assets/project-matrices/cddab57b-6868-4be4-806f-395ed9dd635a.csv.zip
https://prod.data.humancellatlas.org/project-assets/project-matrices/cddab57b-6868-4be4-806f-395ed9dd635a.loom
https://prod.data.humancellatlas.org/project-assets/project-matrices/cddab57b-6868-4be4-806f-395ed9dd635a.loom.zip
https://prod.data.humancellatlas.org/project-assets/project-matrices/cddab57b-6868-4be4-806f-395ed9dd635a.mtx.zip

**Comment by NoopDog** [comment]
Looks to be working ok. Thanks.

**Comment by GPelayo** [comment]
Awesome. Thanks.
