### ISSUE TITLE
Exclude old Human Hematopoietic Profiling dataset in prod

### ISSUE THREAD

**Issue by willrockout** [DataBiosphere/azul#1144]
The Human Hematopoietic Profiling (Pe'er, Profiling of CD34+ cells from human bone marrow to understand hematopoiesis) project has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5c06cf339460a30007501909; project UUID: 29f53b7e-071b-44b5-998a-0ae70d0229a4) please be excluded from the Browser.

The new version of the dataset (submission ID: 5d30e0c49be88c0008a9b236; project UUID: 091cf39b-01bc-42e5-9437-f419a66c8a45) is exported and has already started appeared in the Browser.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-715)
┆Project Name: azul
┆Issue Number: AZUL-715

**Comment by hannes-ucsc** [comment]
@willrockout, I think we don't do exclusions anymore but instead delete the data from the DSS. The DSS team lead, @xbrianh should be able to help you with that. Feel free to reopen if I am wrong.
