### ISSUE TITLE
Set cache control headers for matrix files in project-assets bucket

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#1146]
We are running into a problem where once we download a matrix file in chrome, chrome is caching the file, and then, when we next reload the project details page and do an AJAX HEAD request for the file, chrome attempts to answer this for the cached file and this generates a CORS error locally.

This seems to be fine on dev.

To fix this we would like to set a: Cache-Control: no-store, must-revalidate header on the objects in the project-matrix folder.

As this is only affecting localhost this is not urgent but we would like to have this added to the script that uploads the matrix files to prevent confusion over errors in the local console going forward.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-717)
┆Project Name: azul
┆Issue Number: AZUL-717

**Comment by theathorn** [comment]
Should not be necessary once https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/matrix-service/351 is implemented.
