### ISSUE TITLE
Auto supress Integration Tests in prod

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1148]
It doesn't look good to have Integration Test projects show up in the Data Browser in prod, even temporarily.
If possible, we should consider "auto black listing" any Integeration Test projects,
@hannes-ucsc How feasible is this? I presume the Integration Tests must be indexed by Azul in order to "pass", which may make supressing them from the Data Browser difficult.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-719)
┆Project Name: azul
┆Issue Number: AZUL-719

**Comment by hannes-ucsc** [comment]
Isn't this the same as https://github.com/DataBiosphere/azul/issues/1095?

**Comment by theathorn** [comment]
Yep..
