### ISSUE TITLE
Clean out black list for prod

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1161]
The following projects have been tombstoned/deleted and can be removed from the Azul black list:

project_uuid=179bf9e6-5b33-4c5b-ae26-96c7270976b8 (1M Immune Cells)

project_uuid=29f53b7e-071b-44b5-998a-0ae70d0229a4 (Pe'er)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-724)
┆Project Name: azul
┆Issue Number: AZUL-724

**Comment by hannes-ucsc** [comment]
@achave11, we need PR for backport to `develop`.
