### ISSUE TITLE
Each release engineer candidate should be subscribed to Airbrake

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1169]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-728)
┆Project Name: azul
┆Issue Number: AZUL-728

**Comment by hannes-ucsc** [comment]
Quoting @mweiden from Slack:

> I’ve just invited many of you to the Airbrake account (https://humancellatlas.airbrake.io/projects/179579) that `@Parth Shah` set up for us. Please check it out and start debugging the exceptions in your applications that show up there. If you did not get an invite and want one, DM me. Airbrake is an error aggregation service that consolidates all of the errors in our logs in one place. It should make the visibility, triage, and resolution of issues in our system smoother.

IOW: DM @mweiden for an invite if you don't have one yet.

**Comment by achave11** [comment]
Have joined Airbrake, removing assignation.

**Comment by danielsotirhos** [comment]
Airbrake account activated.

**Comment by hannes-ucsc** [comment]
I use this gmail filter:

<img width="501" alt="Screen Shot 2019-07-31 at 1 08 32 PM" src="https://user-images.githubusercontent.com/5143256/62244535-77ec0900-b394-11e9-8d8c-f88eaab1b465.png">

**Comment by hannes-ucsc** [comment]
For the demo, each RE shows that they have received email messages from Airbrake.
