### ISSUE TITLE
Include workflow type in hits

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1170]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-729)
┆Project Name: azul
┆Issue Number: AZUL-729

**Comment by hannes-ucsc** [comment]
We do already return it: 
<img width="1063" alt="Screen Shot 2019-07-29 at 1 40 41 PM" src="https://user-images.githubusercontent.com/5143256/62081126-daaf9a00-b206-11e9-909f-943f30b0e873.png">
