### ISSUE TITLE
Create Docker image container to generate summary figures

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#1172]
I raised this issue after the idea of accomplishing the generation of the summary figures using an AWS Lambda has been abandoned, as described in #1110. The thinking following a discussion with @hannes-ucsc is that any alternative approach of addressing this problem would necessitate running the code inside a container.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-731)
┆Project Name: azul
┆Issue Number: AZUL-731

**Comment by theathorn** [comment]
Moved to https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal-summary-stats/5.
