### ISSUE TITLE
Fix translated None values in response

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1179]
Values translated by #989 are not being un-translated before being returned in the response termFacets. (eg. A None value returned as "__null__")
Also the field `totalCellCount` in the /summary response is incorrectly including the translated None values into the calculation producing a large negative number.

![Screen Shot 2019-07-31 at 4 15 03 PM](https://user-images.githubusercontent.com/46407464/62254845-9ca1aa00-b3af-11e9-82d4-91dff7e2153f.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-736)
┆Project Name: azul
┆Issue Number: AZUL-736

**Comment by hannes-ucsc** [comment]
I think this was demoed.
