### ISSUE TITLE
create environment variable to use for Boardwalk to Xena

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#12]
the URL for Xena should be specified through an environment variable and not hard coded in the dashboard service

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-21)
┆Project Name: azul
┆Issue Number: AZUL-21

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
