### ISSUE TITLE
Filter by None misses missing fields

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1202]
Filter by None (eg. `filters={"pairedEnd":{"is":[null]}}`) currently finds results for fields that were specified with a `null` value, however it does not find results for fields that were not specified.

A possible solution is at index time to add any missing fields with a None/null value.
An alternate solution is to perform a `missing` (aka `must_not exists`) query when filtering by None, and to combine the `missing` results with the results of fields present but with a None/null value.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-749)
┆Project Name: azul
┆Issue Number: AZUL-749

**Comment by hannes-ucsc** [comment]
Demoed on 8/19
