### ISSUE TITLE
Raise exception if filtered field isn't in mapping

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1205]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-752)
┆Project Name: azul
┆Issue Number: AZUL-752

**Comment by achave11** [comment]
Manifest generation query for :
```
https://service.explore.data.humancellatlas.org/fetch/manifest/files?filters={"file":{"projectId":{"is":["cddab57b-6868-4be4-806f-395ed9dd635a"]},"fileFormat":{"is":["matrix"]}}}&format=full'
```
Generates the following error:
```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 901, in __call__
    return self.func(event, context)
  File "/var/task/app.py", line 913, in generate_manifest
    response = es_td.transform_manifest(event['format'], event['filters'])
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 598, in transform_manifest
    entity_type=entity_type)
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 253, in _create_request
    filters = self._translate_filters(filters, field_mapping)
  File "/var/task/azul/service/responseobjects/elastic_request_builder.py", line 105, in _translate_filters
    assert isinstance(one(value.values()), list)
  File "/var/task/more_itertools/more.py", line 535, in one
    raise too_long or ValueError('too many items in iterable (expected 1)')
ValueError: too many items in iterable (expected 1)
```

The offending query is malformed, `service_config.translation` does not support `file` key.

**Comment by hannes-ucsc** [comment]
A fix for this issue should therefore cause a 400 status response and should not log an exception.

**Comment by melainalegaspi** [comment]
from Hannes: "the blocker was too far out, and we need a fix for this bug now, so we'll do a manual validation."

**Comment by achave11** [comment]
This was solved by PR #1660 to be demoed.

**Comment by melainalegaspi** [comment]
Yes ^

**Comment by jessebrennan** [comment]
We have a lingering FIXME for this issue https://github.com/DataBiosphere/azul/blob/c77448084fffea1b29ed0f057b1ba57521674627/src/azul/service/elasticsearch_service.py#L128

I suspect the try-except block should be removed as well.

**Comment by theathorn** [comment]
@jessebrennan to raise a new ticket for the leftover work.
