### ISSUE TITLE
Fix Content-Type header for production matrix files

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#1206]
In the prod deployment of the data browser, the per-project matrix files have the incorrect `Content-Type` HTTP header. The `.csv.zip` and `.mtx.zip` files should have their `Content-Type` headers set to `application/zip` and that same header for `.loom` files should be set to `application/vnd.loom`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-753)
┆Project Name: azul
┆Issue Number: AZUL-753

**Comment by hannes-ucsc** [comment]
@GPelayo would you mind adding a description of the problem?

**Comment by GPelayo** [comment]
@mckinsel has already uploaded matrix files with the correct `Content-Type` header. Closing this ticket.
