### ISSUE TITLE
Capture Code Coverage Metrics

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1210]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-756)
┆Project Name: azul
┆Issue Number: AZUL-756

**Comment by hannes-ucsc** [comment]
Code coverage is tracked by Travis via Codecov and Coverage.io on all branches.

**Comment by stahiri** [comment]
@hannes-ucsc --- would you please associate this closed ticket with dcp/524 instead of dcp/420?
