### ISSUE TITLE
`len(hits)` may not match `hits.total` in ES search response

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1211]
This seems to just be the result of eventual consistency in Elasticsearch. Probably failing here is the correct option, but a more concise log message and exception should be raised.

```
AssertionError
Traceback (most recent call last):
  File "/var/task/app.py", line 152, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 270, in write
    indexer.aggregate(tallies)
  File "/var/task/azul/indexer.py", line 191, in aggregate
    contributions = self._read_contributions(total_tallies)
  File "/var/task/azul/indexer.py", line 245, in _read_contributions
    assert len(hits) == total_hits
AssertionError

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-757)
┆Project Name: azul
┆Issue Number: AZUL-757

**Comment by hannes-ucsc** [comment]
It's worth noting that we temporarily augmented the assertion and observed `len(hits)` to always be less than `total_hits` even though the committed code does not reveal that.

**Comment by hannes-ucsc** [comment]
It (`hits.total`) seems to have always been an approximation but in 7 this is made explicit:

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response

We raise a EC exception now:

https://github.com/DataBiosphere/azul/blob/0c6959a5be16b098c8b9d33fcb0217867866c732/src/azul/indexer/index_service.py#L353
