### ISSUE TITLE
Tabula muris incomplete in production

### ISSUE THREAD

**Issue by parthshahva** [DataBiosphere/azul#1212]
https://tracker.data.humancellatlas.org/?projectUUID=e0009214-c0a0-4a7b-96e2-d6a83e966ce0

Expected bundle count (available in aws dss): 99840
Current bundle count: 38396

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-758)
┆Project Name: azul
┆Issue Number: AZUL-758

**Comment by hannes-ucsc** [comment]
Looking at bundle `abff76ef-98ce-46da-a20e-6d8aea37c530.2019-08-01T200147.724899Z` as one of the examples of the absent 61444=99840-38396 bundles, and `ffc377ae-0e4c-40ce-8208-8ce4736fecba.2019-08-01T200147.202020Z` as an example of the 38396 present ones. 

Azul did *not* receive a notification for the absent bundle and DSS did not queue one either. Azul did receive a notification for the present bundle and DSS did queue one. There are multiple warning messages in Kibana, emitted by DSS code, about the bundle being absent from the `aws` replica and no notification being sent.

@DailyDreaming informally reported a large number of inconsistencies in the DSS index yesterday, so at this point I will venture to say that Azul is in the clear. I assume that DSS reindexed overnight which must have fixed the inconsistencies on their end. I will trigger a reindex now.

Post mortem: Assuming that my assertions above are correct, it would be helpful if the DSS team notified downstream components explicitly and prominently after a outages like that. Apologies if that already happened and I just wasn't tuned into the right channels. As a rule of thumb, any DSS index inconsistency will affect Azul during reindexing of its own index. Any issues with DSS notifications will affect Azul as well during normal processing. cc: @kozbo

I will post the Kibana logs as evidence.

**Comment by hannes-ucsc** [comment]
Logs for the absent bundle `abff76ef-98ce-46da-a20e-6d8aea37c530.2019-08-01T200147.724899Z`: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/snippets/6

Logs for the present bundle `ffc377ae-0e4c-40ce-8208-8ce4736fecba.2019-08-01T200147.202020Z`: https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/snippets/5

**Comment by hannes-ucsc** [comment]
@parthshahva I believe the reindexing fixed this for now. However, due to `https://github.com/HumanCellAtlas/data-store/issues/2333` this can occur again at any time. Could you verify the fix and close?

**Comment by parthshahva** [comment]
Looks good. Thanks for the detailed investigation @hannes-ucsc!
