### ISSUE TITLE
Enable download of 'matrix' type files (e.g. zarray files)

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1226]
A user downloaded the manifest for a project and expected to get all the files for the project, including the secondary analysis matrix files (.zattrs and .zarr).

ATM we exclude these files from the manifest.

Request is to include all related zarray files if the user has selected file type "matrix" in the Data Browser, even though we only show the zattrs files (and not the zarr files) in the Files tab.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-764)
┆Project Name: azul
┆Issue Number: AZUL-764

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/397
https://github.com/HumanCellAtlas/metadata-schema/issues/579
https://github.com/HumanCellAtlas/metadata-schema/issues/623
