### ISSUE TITLE
Implement `GET /integrations` portal API endpoint

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1243]
Implement the APIs used by the Data Browser to get the list of registered portals and their integrations.

Initially populate the database with hard -code information for the SCP, SCEA and Terra MVP portal hand-offs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-773)
┆Project Name: azul
┆Issue Number: AZUL-773

**Comment by theathorn** [comment]
Initial implementation:
    1) Terra
    2) SCP
    3) SCEA

**Comment by theathorn** [comment]
@danielsotirhos Please note changes to the SCP endpoint in humancellatlas/data-browser#762.

**Comment by danielsotirhos** [comment]
Updating SCP portal details as mentioned in https://github.com/HumanCellAtlas/data-browser/issues/761#issuecomment-533689180
