### ISSUE TITLE
Firefox truncates full manifest file name

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1247]
1) Request a full manifest on the command line

```
$ http 'https://service.dev.explore.data.humancellatlas.org/fetch/manifest/files?filters=%7B%22projectId%22%3A%7B%22is%22%3A%5B%22ae5237b4-633f-403a-afc6-cb87e6f90db1%22%5D%7D%2C%22fileFormat%22%3A%7B%22is%22%3A%5B%22json%22%2C%22tiff%22%5D%7D%7D&format=full'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 232
Content-Type: application/json
Date: Fri, 30 Aug 2019 06:02:38 GMT
Via: 1.1 ecff0a3897db9f1faffff0a0f23cefbb.cloudfront.net (CloudFront)
X-Amz-Cf-Id: XMuqDuIZuuUkTWUKsUIuTzLGyd1OfPeHYPeM1bW0jNX5AjJEDwp7-A==
X-Amz-Cf-Pop: LAX3-C2
X-Amzn-Trace-Id: Root=1-5d68bbfd-50d17f12e192399770f3da99;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: fOJPqHnioAMF8XQ=
x-amzn-RequestId: c9ff9644-4a6c-4d43-a9a8-8390793f4938

{
    "Location": "https://service.dev.explore.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiZjU3ZjM0OWQtMjlhMS00ZTUxLTlkZDYtY2E3NTU2MzM4NGYxIiwgInJlcXVlc3RfaW5kZXgiOiAxfQ==",
    "Retry-After": 1,
    "Status": 301
}
```

2) Paste the Location URL from the above 301 response into Firefox address bar, hit enter

<img width="1673" alt="Screen Shot 2019-08-29 at 11 03 15 PM" src="https://user-images.githubusercontent.com/5143256/63996767-6f7d1000-cab1-11e9-832a-a5c69fcea1a9.png">

3) Click the link from the 302 response.

<img width="498" alt="Screen Shot 2019-08-29 at 11 03 40 PM" src="https://user-images.githubusercontent.com/5143256/63996838-aeab6100-cab1-11e9-8477-d5f5ed693aa9.png">

Actual: Firefox truncates the filename after the first space. The date and file extension are missing. 
Expected: The downloaded file's name should include the date and file extension.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-776)
┆Project Name: azul
┆Issue Number: AZUL-776

**Comment by hannes-ucsc** [comment]
Safari does not exhibit that behavior, BTW.

**Comment by achave11** [comment]
@hannes-ucsc ok to close? Already in prod, and demoed.

**Comment by hannes-ucsc** [comment]
I don't want to close this because 1) this change isn't observable in `staging` yet and 2) your CP commit overtook this commit so we should let this one progress naturally.
