### ISSUE TITLE
Dynamic TSV Downloads do not use the same format for the filename as the "Bucket TSV" downloads

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#1249]
The bucket TSV Downloads give file names like:

1M Neurons 2019-08-29 01.57.tsv

The same file in the dynamic implementation is called:

hca-manifest-8dc93a7c-1de4-472a-b736-8bf702e19a46.tsv

My understanding is that we would continue to use the human friendly file name.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-777)
┆Project Name: azul
┆Issue Number: AZUL-777

**Comment by hannes-ucsc** [comment]
What deployment did you observe this in?

**Comment by hannes-ucsc** [comment]
I'm *guessing* prod because UUID is v4 not v5. But please confirm. If it is `prod`, then this can be closed because it has been addressed by https://github.com/DataBiosphere/azul/issues/1139.

**Comment by theathorn** [comment]
Problem appears to be fixed in integration and staging but present in prod.

**Comment by hannes-ucsc** [comment]
So yes, this duplicates #1139.
