### ISSUE TITLE
Make assertions more strict in `test_hca_indexer`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#125]
https://github.com/DataBiosphere/azul/pull/105/files#r204261339

The field renames made by @caaespin in #105 should have required that he make changes to the assertions in the tests you added in #42. They didn't because the assertions are too weak. One of the tests should assert the result verbatim.

Check out `freeze()` and `thaw()` in `scripts/subscribe.py` for a way to make JSON structures comparable via `==`. Consider storing the expected response in a JSON file like you do for the test input.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-98)
┆Project Name: azul
┆Issue Number: AZUL-98

**Comment by alex-hancock** [comment]
I am going to update the result files on a case-by-case basis with reasonable changes. Any breakage after reasonable changes will be double-checked and then attributed to bugs that will be filed separately.

**Comment by alex-hancock** [comment]
Updated result files, improved logic for checking them. Only issue is that elasticsearch search returns non-deterministic orderings for internal lists. so multiple `document_id` entries will appear in different orders on subsequent runs. Patching this probably moves this to review territory.
