### ISSUE TITLE
Change HCA export to Terra from using schema "dos://" to "drs://"

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1252]
Terra/Cromwell recently changed from supporting the "dos://" schema to instead only supporting "drs://" schema, even though currently the actual protocol being used for resolution is still DOS and not yet DRS.

This is a late-breaking/fast-tracked change to Terra/Cromwell that was deployed to Terra production today (9/3/19). 

The Cromwell team elected to not to support both "dos://" and/or "drs://"  for both technical/implementation reasons and consistency going forward.

This is a small change to the HCA handoff code yet, as of today, HCA data handed-off to Terra will not be accessible by Terra until this change is made.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-778)
┆Project Name: azul
┆Issue Number: AZUL-778

**Comment by hannes-ucsc** [comment]
Marking this as `workaround` because I consider it a defect to be declaring DRS compatibility while actually implementing the older DOS protocol.
