### ISSUE TITLE
Web service endpoint to get failed bundles queue

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1260]
Expose the Azul failed-to-index-bundles queue so that the Data Browser can provide details (mainly for Data Ops) via a bundles status page.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-781)
┆Project Name: azul
┆Issue Number: AZUL-781
┆Epic: Broken bundles

**Comment by GPelayo** [comment]
The endpoint will implemented under the `health/failure` endpoint. It should return the uuid and version of bundle notifications in the fail queues and the count of messages that are not bundle notifications. The following is the response that will be returned by `health/failure` endpoint.

```
{
	failed_bundle_notifications: [
		{
			bundle_uuid: <uuid value>,
			bundle_version: <version value>
		}			
	],
	other_failed_messages: {
		count: 0
	}
}
```

**Comment by melainalegaspi** [comment]
This was relevant for DCP1, not DCP2.
