### ISSUE TITLE
Manually Generate full metadata.tsv for Diabetic Nephropathy snRNA-seq

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#1264]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-783)
┆Project Name: azul
┆Issue Number: AZUL-783

**Comment by hannes-ucsc** [comment]
The `prod` promotion tomorrow should resolve this. 

RE @achave11 to verify, though.

**Comment by theathorn** [comment]
No loner necessary - auto generation is working.
