### ISSUE TITLE
"Fetch Manifest TSV Full" does not error if null is provided for a project UUID

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1265]
From @NoopDog :

I am expecting that the project UUID is validated as a proper UUID that corresponds to an existing project. 

Request
https://service.explore.data.humancellatlas.org/fetch/manifest/files?filters=%7B%22projectId%22%3A%7B%22is%22%3A%5Bnull%5D%7D%7D&format=full

Response
{"Status": 301, "Location": "https://service.explore.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMmQxMGZjYjMtOTgyYi00NmQ2LTkzODEtMGEyNGQ1YWEyYjYwIiwgInJlcXVlc3RfaW5kZXgiOiAxfQ==", "Retry-After": 1}

There is a bug in the browser project detail page that exposes this bug on the server. We will stop sending null as the project UUID ASAP but wanted to record that we currenly get a TSV back if we send  null as the project ID.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-784)
┆containerName: azul
┆Issue Number: AZUL-784

**Comment by hannes-ucsc** [comment]
I hesitate to jump on this because `?filters={"<field>":{"is":[null]}}` could be a valid filter for certain fields. There has to be a `project.json` in every bundle so every file has to be associated with project.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"This isn't really impacting any users and we don't want to hard code which fields can / cannot be null."
