### ISSUE TITLE
Allow use of full manifest for CLI downloads

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1273]
This just means making the column names for file and bundle FQIDs compatible between both.

It's entirely possible that this is already the case.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-789)
┆Project Name: azul
┆Issue Number: AZUL-789

**Comment by achave11** [comment]
By approval of @hannes-ucsc estimate change.
Requires modifications to the metadata generator to include and repurpose fields so that `full` manifest is compatible for CLI downloads.
