### ISSUE TITLE
Test mode doesn't block deletion notifications

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1276]
I'm not sure if this is a bug, but it's something we should consider. Probably the current behavior is fine the way it is, but I wanted to check.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-792)
┆Project Name: azul
┆Issue Number: AZUL-792

**Comment by achave11** [comment]
By approval of @hannes-ucsc the estimate for this ticket change.

**Comment by hannes-ucsc** [comment]
… because we extended the scope a bit to reduce duplication between the `POST /` and `POST /delete` handlers which requires removing the special `sync` mode for `/`.
