### ISSUE TITLE
No Content-Disposition header when manifest filename contains quotation marks

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#1283]
If Azul generates a presigned URL for a manifest with quotation marks in its filename, the response from the presigned URL won't have a Content-Disposition header.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-795)
┆Project Name: azul
┆Issue Number: AZUL-795

**Comment by hannes-ucsc** [comment]
@GPelayo Is there a reproduction or other evidence that this is indeed an issue?

**Comment by GPelayo** [comment]
I wrote this script for determining if a pre-signed URL of a manifest with certain filename returns a response with the correct Content-Disposition header. It's derived from `StorageServiceTest.test_presigned_url()` in `test_storage_service.py`. Since moto doesn't support the Content-Disposition response headers, I had to upload the test file to an actual s3 bucket in my personal deployment instead of relying on a mock S3 bucket. 

```
from azul.service.responseobjects.storage_service import StorageService
import json
import requests

sample_key = 'cd-test'
sample_content = json.dumps({"test": "content"})
storage_service = StorageService()
storage_service.put(sample_key, sample_content)

for file_name in 'foo.json', 'foo".json':
    presigned_url = storage_service.get_presigned_url(sample_key, file_name=file_name)
    response = requests.get(presigned_url)
    cd = response.headers.get('Content-Disposition')
    print(f'The Content Disposition for {file_name} is {cd}.')
```

While testing presigned URLs with a valid filename and a filename with quotation marks, I get the following results:
```
The Content-Disposition for foo.json is attachment;filename="foo.json".
The Content-Disposition for foo".json is None.
```

**Comment by hannes-ucsc** [comment]
I see. Your script is testing an internal interface that's not exposed externally. AFAICT, [this line](https://github.com/DataBiosphere/azul/blob/d10020208b78df91eb9e36ef29fdddc1322454b1/src/azul/service/responseobjects/hca_response_v5.py#L315) removes quotation marks from the project name which prevents this from being reproducible from the outside. Do you concur?
