### ISSUE TITLE
Adjust integration test prefix to match DSS content

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1284]
If the amount of bundles is a particular DSS stage changes suddenly, Azul's local integration tests may take too long or else fail outright. This fix would supersede the quick fix for #1282 which would need to be removed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-796)
┆Project Name: azul
┆Issue Number: AZUL-796

**Comment by melainalegaspi** [comment]
integration test always uses 64 bundles so this isn't necessary anymore
