### ISSUE TITLE
Action service page should display decoded base64 json input and arch worker log from VM

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#13]
Action service page should include the base64 json input from the dockstore tool runner translated to plain text so the input files to the pipeline are immediately readable and the arch_worker.log file from the worker VM to help in debugging when a workflow fails. 

Otherwise it is necessary to login to the worker node to see the worker log.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-15)
┆Project Name: azul
┆Issue Number: AZUL-15

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
