### ISSUE TITLE
Integrate orange box into inter-box integration test

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#130]
https://github.com/HumanCellAtlas/dcp/blob/master/.travis.yml#L16

The test should assert that both the test input bundle and the resulting analysis bundle appear in the Azul web service response for the respective deployment.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-102)
┆Project Name: azul
┆Issue Number: AZUL-102

**Comment by kozbo** [comment]
Update: feature branch passes, will create a PR, 2 commits

**Comment by alex-hancock** [comment]
Pull request merged into master

**Comment by kozbo** [comment]
merge into staging too
