### ISSUE TITLE
Improve deployment cleanup process

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1303]
A few steps are missing from the readme. A script should be made that deletes left over IAM roles (see https://github.com/DataBiosphere/azul/issues/1094#issuecomment-533268395).

The readme should include steps to:
 - run this script and
 - run `python scripts/reindex.py --delete`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-804)
┆Project Name: azul
┆Issue Number: AZUL-804

**Comment by theathorn** [comment]
Spike to investigate possible solutions.
