### ISSUE TITLE
Clean out integration and copy a subset of production bundles into it

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1315]
- [x] Ask Matrix Service team which bundles they would like to retain in integration
- [x] Produce list of bundles in integration not on that list
- [x] Pass list to DSS team to perform deletion (thanks @amarjandu for offering to help with this)
- [x] Once deletion is done, copy bundles from DSS prod to DSS integration using `scripts/copy_bundle.py --manifest …` as described on the README. 

Copy all projects. Use one manifest per project. Wait after copying each project until the Data Browser shows that project and the Azul queues are drained. For large projects (>1000 bundles), copy only 1/16th of the bundles in each of those projects using the `--prefix` option to `scripts/copy_bundle.py`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-808)
┆Project Name: azul
┆Issue Number: AZUL-808

**Comment by amarjandu** [comment]
@danielsotirhos can you please upload the complete whitelist here for record purposes?

**Comment by danielsotirhos** [comment]
Complete `integration` bundle whitelist uploaded. Contains bundles from previous whitelist https://github.com/HumanCellAtlas/data-store/issues/2294 along with bundles recently copied from `prod` to `integration`.

[bundles-whitelist.txt](https://github.com/DataBiosphere/azul/files/3692207/bundles-whitelist.txt)

**Comment by danielsotirhos** [comment]
> Complete `integration` bundle whitelist uploaded. Contains bundles from previous whitelist [HumanCellAtlas/data-store#2294](https://github.com/HumanCellAtlas/data-store/issues/2294) along with bundles recently copied from `prod` to `integration`.
> 

An issue has been discovered with the whitelist as given in my previous comment. Please consider this list invalid. A new whitelist will be provided shortly.

The issue in question has to do with the distribution of bundles in relation to their prefix. A prefix of '0' was used to limit the number of bundles preserved from some of the larger projects, however this unfortunate for integration testing which selects a random bundle prefix when testing, either causing a very large test data set if zero is chosen, or a small data set if a non zero prefix is used.

The new whitelist for bundles on integration will address this issue producing a more balanced distribution of bundles.

**Comment by danielsotirhos** [comment]
@amarjandu Full list of bundles to be whitelisted on `integration`.

[integration-bundles-whitelist.txt](https://github.com/DataBiosphere/azul/files/3719717/whitelist.txt)

**Comment by amarjandu** [comment]
@danielsotirhos We had an internal discussion to the deletion request, and don't currently have the bandwidth to accommodate this. We will reconsider deletion once our pipelines are more stable, if you need a feature to be promoted to a particular stage please do not hesitate to ask for a cherry-pick, in `humancellatlas/data-store/issues`

**Comment by danielsotirhos** [comment]
Last remaining item (DSS to use whitelist to delete all other bundles on integration) completed https://github.com/humancellatlas/data-store/issues/2558#issuecomment-561262654
