### ISSUE TITLE
Model per-project matrices in portal database

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1319]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-812)
┆Project Name: azul
┆Issue Number: AZUL-812
┆Epic: Generic Tertiary Portal Handoff

**Comment by theathorn** [comment]
Plan is to store per-project matrices in the Data Store.

**Comment by melainalegaspi** [comment]
This was relevant for DCP1, not DCP2.
