### ISSUE TITLE
Update Portal Integrations API integration DSS UUIDs

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1324]
Update the UUIDS for entities (projects) on integration DSS.
UUIDs should match production UUIDs as bundles from prod DSS will have been copied to integration DSS

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-814)
┆Project Name: azul
┆Issue Number: AZUL-814

**Comment by hannes-ucsc** [comment]
Labelling workaround since this was made necessary by the switch from DSS staging to DSS integration which cause by outage in DSS.
