### ISSUE TITLE
Handle entity_ids param differently if not given vs given empty

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1340]
Handle `&entity_ids==` differently to `entity_ids` being absent from the query.

`&entity_ids==` could be interpreted as "Give me all integrations that match the other two criteria and that don't have an entity_ids attribute".

https://github.com/DataBiosphere/azul/pull/1329#issuecomment-536842704

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-821)
┆Project Name: azul
┆Issue Number: AZUL-821

**Comment by hannes-ucsc** [comment]
See also #1353

**Comment by theathorn** [comment]
Waiting for #1383 to demo.
