### ISSUE TITLE
Integration tests need a bigger prefix

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1347]
Or else some stuff needs to be cleaned up from prod. During my last run of the `local_integration_test` I got 2562 docs in the queue. This may not be an actual issue though because it still took only 2.5 minutes to index all of these.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-825)
┆Project Name: azul
┆Issue Number: AZUL-825

**Comment by hannes-ucsc** [comment]
> Or else some stuff needs to be cleaned up from prod

You ran an integration test against prod?

**Comment by jessebrennan** [comment]
I miss-typed. Not prod, integration. Sorry for the confusion.
