### ISSUE TITLE
Document why specific bundle could produce duplicates

### ISSUE THREAD

**Issue by alex-hancock** [DataBiosphere/azul#135]
`test_projects.py`: in the test checking for no duplicate files in specimen, why is this specific bundle used?

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-107)
┆Project Name: azul
┆Issue Number: AZUL-107

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/blob/134c00c/test/indexer/test_projects.py#L112

@caaespin, could you elaborate on this in a comment on the test. or share the thinking here in a comment?

**Comment by caaespin** [comment]
The only reason is that it has two processes pointing to the same file. There was a bug a week or two ago in which the files sections had duplicated dictionaries representing files. It's worth noting that it appears that all files in production have 2 processes pointing to the same file.

**Comment by hannes-ucsc** [comment]
Thank you. @alex-hancock could you add a comment with @caaespin's response to the code in question?

**Comment by hannes-ucsc** [comment]
Also, I am still confused why the test was failing in the first place.  IOW, why did we have to modify the hard-coded document_id in the test to make it pass?

A few days ago, I fixed a bug in MetadataDownloader that would always download the latest version of a bundle and the files in it, regardless of what the notification specified as the version. Maybe the newest version of the bundle with the hard-coded UUID had that process with the two files in it.

@alex-hancock, could you verify @caaespin's statement that two processes point at the same file in that bundle. I would also like to add that assertion to the test code. This would have been good in the first place, both to ensure correctness of the test and to document its intention.

**Comment by alex-hancock** [comment]
The test was failing because I referenced a different dictionary than the one containing the bundles for the duplicate test. Had we checked the `bundle_uuid` we would have noticed that we weren't pulling the same bundle at all. I've already fixed this in the commit.

I will add that assertion anyways, it's a good addition.
