### ISSUE TITLE
Include user-provided IDs in full manifest

### ISSUE THREAD

**Issue by mshadbolt** [DataBiosphere/azul#1367]
As a data wrangler I think it is important for both contributors and downstream users to be able to access the original contributor provided id given to biomaterials and protocols. 

This would enable contributors to match their samples with samples in the DCP and compare their analysis with the standardised DCP analysis.

This would also enable downstream users to match published sample ids to ids in the HCA DCP.

The current behaviour is to provide the `*.provenance.document_id` field as the unique identifier for any entity as a uuid. This needs to be retained as it gives a unique id across all projects in the DCP but I believe it is also useful to have the user provided id for the reasons stated above.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-835)
┆containerName: azul
┆Issue Number: AZUL-835

**Comment by hannes-ucsc** [comment]
Agreed. We should do this.

**Comment by hannes-ucsc** [comment]
Just to clarify, this means including `biomaterial_id``, `protocol_id` and `process_id`. I am not aware of any other ID fields.

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
