### ISSUE TITLE
Switch to DSS v2 subscriptions

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1376]
Replace the v1 ElasticSearch-based subscriptions with a v2 JMESPath-based subscriptions of equivalent functionality. This means limiting the notifications to those for additions and deletions of bundles whose UUID starts with a given prefix and that contain a `project.json` or `project_0.json`.

Ideally, `make subscribe` would automatically remove the old v1 subscriptions and replace them with the equivalent v2 subscriptions. This is complicated by the fact that we use and old dcp-cli version that is [hacked](https://github.com/DataBiosphere/azul/blob/3788b6a57f649430c7855d2c98065f738ae0e6a1/src/azul/subscription.py#L61) to support v2. Rather making the hack even more complicated, we should upgrade our dcp-cli dependency (https://github.com/DataBiosphere/azul/issues/1379), first.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-840)
┆Project Name: azul
┆Issue Number: AZUL-840

**Comment by theathorn** [comment]
Closing - DSS is deprecated.
