### ISSUE TITLE
Move portal integration DB to S3

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1383]
Move the hard-coded portal integrations DB created in https://github.com/DataBiosphere/azul/issues/1243 to a AWS S3 bucket.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-844)
┆Project Name: azul
┆Issue Number: AZUL-844
┆Epic: Generic Tertiary Portal Handoff

**Comment by noah-aviel-dove** [comment]
I would benefit from some more specific instructions. From reading the commit history of #1243, it would seem that your're referring to [this JSON](https://github.com/DataBiosphere/azul/commit/9b12986bf0915dfa0b12b5f5b4bc3c562f3838a6#diff-48eef37b4334bc720ffa086b444fd6a1). 

Does it go into an existing bucket or a new one? If new, are there naming or organization conventions? 

I searched for 'azul' in the HCA S3 buckets and it's not obvious that there's a correct implementation.

**Comment by hannes-ucsc** [comment]
Good questions. Yes, the JSON structure you link to is the portal database. 

In S3, it should go into the "config" bucket, the same place where the Terraform state is kept (the bucket name is controlled by the `azul.config.terraform_backend_bucket` property. The key of the object should be `f"azul/{azul.config.deployment_stage}/portals/db.json"`.

To ease the roll-out of this feature, the hard-coded DB should remain in place in the source tree and should be used to create the object if it doesn't exist. This roll-out behaviour should be covered by the tests. Note that we use `moto` to mock S3 in unit tests. Once the feature is rolled-out to prod we'll remove the hard-coded version.

The "config" bucket has versioning enabled, so accidental deletions/overwrites of the object are not permanent and can be reverted.

**Comment by noah-aviel-dove** [comment]
Should the moto rollout test be added to `TestPortalIntegrationResponse`, `TestStorageService`, or somewhere else?

**Comment by hannes-ucsc** [comment]
The former, I think.

**Comment by noah-aviel-dove** [comment]
Why was this closed? I never even submitted a pull request.

**Comment by hannes-ucsc** [comment]
> Why was this closed? I never even submitted a pull request.

I must have closed this by accident when I attempted to use Github keyboard shortcuts.

**Comment by noah-aviel-dove** [comment]
Add integration test for concurrency

N threads simultaneously adding entries to portal DB, all entries must be present.
Only runs in sandbox deployment stage
