### ISSUE TITLE
Add Species Count to Summary Results

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/azul#1388]
We would like to display Species Count in the set of Summary Counts, to more clearly indicate how many species are selected in the current set of data:

![summary-counts.png](https://images.zenhubusercontent.com/57339587bf93871ccd9ae22c/2e1355a3-a2f7-4a42-a23e-a1932573aae0)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-847)
┆Project Name: azul
┆Issue Number: AZUL-847

**Comment by noah-aviel-dove** [comment]
What is the source of this image? I'm having trouble finding the code that produces this summary.

**Comment by achave11** [comment]
@noah-aviel-dove Inspect the https://dev.data.humancellatlas.org/explore/files request. And observe the Network -> XHR responses. Determine which of them produces the summary, and correlate that to Azul.
