### ISSUE TITLE
Manage API tokens for portal registration API

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1397]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-850)
┆containerName: azul
┆Issue Number: AZUL-850
┆Epic: Generic Tertiary Portal Handoff

**Comment by theathorn** [comment]
Now without Fusillade.

**Comment by hannes-ucsc** [comment]
Portal registration is [deprecated](https://github.com/DataBiosphere/azul/issues/6782).
