### ISSUE TITLE
Locust script is stale

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1398]
Make sure it still works.

- [x] Dust off and make sure it works again in current form
- [x] Check if manifest endpoints are covered
- [x] Check if DRS endpoints are covered
- [ ] Check if DOS endpoints are covered

For port see #2154 

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-851)
┆containerName: azul
┆Issue Number: AZUL-851

**Comment by noah-aviel-dove** [comment]
Currently very much does not work.

**Comment by melainalegaspi** [comment]
I may have forgotten to mark this as demoed, @noah-aviel-dove is confident he demoed it
