### ISSUE TITLE
Document auth endpoints

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1403]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-855)
┆containerName: azul
┆Issue Number: AZUL-855
┆Epic: OpenAPI Spec

**Comment by hannes-ucsc** [comment]
The current auth endpoints are dependent on DCP/1's auth infrastructure. They won't work for DCP/2.
