### ISSUE TITLE
CLI download & manifest file improvements

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1418]
┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-870)
┆containerName: azul
┆Issue Number: AZUL-870

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

See https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/dcp-cli/355 ( https://app.zenhub.com/workspaces/orange-5d680d7e3eeb5f1bbdf5668f/issues/humancellatlas/dcp-cli/355 )

**Comment by hannes-ucsc** [comment]
CLI is EOL
