### ISSUE TITLE
Add ability to sort on estimated cell count

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#142]
The UI table sort is now working for all table columns that are in a facet. We send over the facet name in the search api and all is good.

The 'Estimated Cell Count" is not on a facet or if it is I don't know the facet name. Can you advise on how to search by the estimated cell count?

Thanks,
D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-111)
┆Project Name: azul
┆Issue Number: AZUL-111

**Comment by hannes-ucsc** [comment]
@kozbo, let's get into the habit of triaging new tickets every morning. I think assigning ticket to you, like @NoopDog did here is a good way of signalling the need for triage.

**Comment by hannes-ucsc** [comment]
I think this is merely an oversight and we need to add this as a factet.
