### ISSUE TITLE
frozendict equality test returns false positive

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1423]
frozendict returns a false positive for equality when the contents differ by the values `0` and `False`

```
>>> from azul.vendored.frozendict import frozendict
>>> frozendict(a=0) == frozendict(a=False)
True

>>> from azul.json_freeze import freeze
>>> freeze({'foo': 0}) == freeze({'foo': False})
True
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-872)
┆Project Name: azul
┆Issue Number: AZUL-872

**Comment by hannes-ucsc** [comment]
https://docs.python.org/3.6/reference/datamodel.html

> numbers.Integral
>
> These represent elements from the mathematical set of integers (positive and negative).
>
>    There are two types of integers:
>
>    Integers (int)
>
> These represent numbers in an unlimited range, subject to available (virtual) memory only. For the purpose of shift and mask operations, a binary representation is assumed, and negative numbers are represented in a variant of 2’s complement which gives the illusion of an infinite string of sign bits extending to the left.
>
>    Booleans (bool)
>
> These represent the truth values False and True. The two objects representing the values False and True are the only Boolean objects. The Boolean type is a subtype of the integer type, and Boolean values behave like the values 0 and 1, respectively, in almost all contexts, the exception being that when converted to a string, the strings "False" or "True" are returned, respectively.
>

**Comment by theathorn** [comment]
Can we close this as not-a-bug?

**Comment by melainalegaspi** [comment]
invalid
