### ISSUE TITLE
test_multipart_upload_ok_with_n_parts is flaky

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1424]
https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/4533

I've seen this fail occasionally, but only on Gitlab if memory serves me right.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-873)
┆Project Name: azul
┆Issue Number: AZUL-873

**Comment by hannes-ucsc** [comment]
Happens on Travis, too: https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/snippets/1

**Comment by hannes-ucsc** [comment]
Since we still use MP uploads, we should fix the test.

**Comment by hannes-ucsc** [comment]
@jessebrennan to revalidate since reproduction is now gone (Gitlab instance was destroyed).

**Comment by jessebrennan** [comment]
I ran this 100 times and encountered no errors. Trying 1000...
