### ISSUE TITLE
Scale limitations of BDBag-based export to Terra

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#1440]
Based on casual, interactive scale tests I did in mid-2019, it seemed that:

* The HCA Data Browser can successfully export about 10k files to Terra and have them be successfully imported.
* The HCA Data Browser can export up to about 50-80k files without error, but the Terra import fails
* The HCA Data Browser export failed when more than 80-100k files were selected

This was based on a few (3-5?) files per bundle, and the BDBag export format in use at the time.

This is enough for some HCA/Terra use cases, yet does not scale sufficiently for other reasonable HCA/Terra use cases.

The BDBag format is essentially being deprecated by Terra, as it is now only used by HCA and it does not scale well. Future investment by the Broad in BDBag import scalability is unlikely.

Other formats should be explored instead, such as Avro/PFB, or scalable support for TSV.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-883)
┆Project Name: azul
┆Issue Number: AZUL-883

**Comment by theathorn** [comment]
Might be obsoleted by #1132
