### ISSUE TITLE
Unit tests, and potentially service, produce too much log output

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1444]
Regression from https://github.com/DataBiosphere/azul/issues/1413, I think most of it is due to the logging of ES queries in the service.

Before: 2.6k lines, https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/4717/raw
After: 30k lines, https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/4737/raw

Step one is to evaluate how much eliminating the ES query logging would save in terms of test output volume. We may want to make ES query logging conditional on `AZUL_DEBUG == 2`. I'm worried that the query logging not only affects the test output volume but also the service runtime performance and Kibana.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-886)
┆Project Name: azul
┆Issue Number: AZUL-886

**Comment by hannes-ucsc** [comment]
Also, I am linking to Gitlab builds but this should also be observable on Travis.

**Comment by achave11** [comment]
ES query log for `AZUL_DEBUG=2` [test](https://api.travis-ci.org/v3/job/611707896/log.txt)  is 14893  lines.

**Comment by achave11** [comment]
Setting `AZUL_DEBUG=0` for `sandbox` and Travis [test](https://api.travis-ci.org/v3/job/611721262/log.txt) is 3234 lines.

Note that there is not a significant reduction in run time for the Travis test.
