### ISSUE TITLE
Sorting by multi-valued fields

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1445]
It is very common, especially in aggregate documents, that a particular document field is the result of the set union of the field values from the contributions. How do we sort by these fields?

Ideally one would want a tuple-based comparison, i.e. `("a", "b") < ("a", "c")` but I don't think ES can do that. ES needs to be told to pick one value out of the many: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-sort.html#_sort_mode_option

Another option would be to used [script-based sorting](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-sort.html#_script_based_sorting) to sort by the concatenation of all values.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-887)
┆containerName: azul
┆Issue Number: AZUL-887

**Comment by theathorn** [comment]
Solved by #1446?
