### ISSUE TITLE
Add SCP registration for "Ischaemic sensitivity of human tissue by single cell RNA seq" project

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1455]
Add the URL for the study: https://portals.broadinstitute.org/single_cell/study/SCP495
for the project titled "Ischaemic sensitivity of human tissue by single cell RNA seq" (https://data.humancellatlas.org/explore/projects/c4077b3c-5c98-4d26-a614-246d12c2e5d7).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-893)
┆Project Name: azul
┆Issue Number: AZUL-893
┆Epic: Single Cell Portal

**Comment by danielsotirhos** [comment]
This ticket is an undo of https://github.com/databiosphere/azul/issues/1360
