### ISSUE TITLE
Filter out supplementary_files from file manifest

### ISSUE THREAD

**Issue by jahilton** [DataBiosphere/azul#1459]
Currently, the file manifest blacklists by file extension
https://github.com/DataBiosphere/azul/blob/34b304a9eb8e9559b4b049318e653484f57545a6/src/azul/project/hca/metadata_generator.py#L69
This has allowed for the inclusion of unwanted files (specifically, docx). 

Rather than keep this file extension list up-to-date, it should be filtered by the file type
There are currently 5 file type schemas: https://github.com/HumanCellAtlas/metadata-schema/tree/master/json_schema/type/file
supplementary_file & reference_file file types should be blacklisted

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-894)
┆containerName: azul
┆Issue Number: AZUL-894

**Comment by theathorn** [comment]
Demo blocked until re-indexing run in staging.
