### ISSUE TITLE
Update Azul section of HCA DCP Software Architecture doc

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1460]
https://docs.google.com/document/d/11a-0In72pg28vVBdMSz0G_y4JYm7nE5Gr3LwtLi6GLU/edit?ts=5d9678bc#heading=h.ew3xx9edkddl

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-895)
┆Project Name: azul
┆Issue Number: AZUL-895

**Comment by jessebrennan** [comment]
I've added some documentation here. @theathorn @hannes-ucsc Do either of you want to review? Or should I just close this issue directly?

**Comment by theathorn** [comment]
Looks perfect to me...

**Comment by hannes-ucsc** [comment]
LGTM.
