### ISSUE TITLE
Limit AZUL_DEBUG=0 to `make test` on Gitlab and Travis

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1464]
Currently `AZUL_DEBUG=0` in `.gitlab-ci.yml` build also affect the debug level of the deployment, when it should only be set for the gitlab test.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-898)
┆Project Name: azul
┆Issue Number: AZUL-898

**Comment by hannes-ucsc** [comment]
Even though Travis does perform deployments we should apply the same discretion there.

**Comment by hannes-ucsc** [comment]
This a problem because it forces AZUL_DEBUG=0 on every deployment that's being touched by Gitlab.

**Comment by hannes-ucsc** [comment]
Demo by showing any recent Gitlab and Travis build and how they don't display DEBUG. Show that `dev` lambdas are configured to 1.
