### ISSUE TITLE
Deal with broken bundles from all deployments

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1475]
At times, our IT fails because the randomly chosen bundle prefix happens to include a broken bundle, a bundle missing a data file, a bundle with a JSON that doesn't have the required `describedBy` attribute.

We could either attempt to gracefully handle those bundles and ignore them somehow or we could identify them all and ask the DSS team to delete them. 

A third option is to implement a blacklist in S3, DynamoDB or ElasticSearch that contains bundle we know are broken. We should also consider that bundle during normal indexing to skip indexing those bundles. We should consider that blacklist in the IT to prevent broken bundles to be part of the test set. If we didn't do the latter part, it would fire the assertion that checks for the bundles to be indexed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-905)
┆containerName: azul
┆Issue Number: AZUL-905

**Comment by theathorn** [comment]
Geryl to talk to Hannes about outstanding PR #1305 (#1260) and blacklist.

**Comment by hannes-ucsc** [comment]
DSS is EOL
