### ISSUE TITLE
Reindexing does not update structure in Elasticsearch if it changes.

### ISSUE THREAD

**Issue by caaespin** [DataBiosphere/azul#148]
See https://github.com/DataBiosphere/azul/blob/develop/src/azul/indexer.py#L161

```
            for bundle in cur_doc["bundles"]:
                if bundle["uuid"] == new_bundle["uuid"]:
                    latest_bundle = max(bundle,
                                        new_bundle,
                                        key=lambda x: x["version"])
                    updated_bundles.append(latest_bundle)
                    bundle_found = True
.
.
.
```

The problem is that during re-indexing  (inside the `if` statement) since the bundle `version` and the `uuid` are the same, we have a tie in the `max(...)` function, which returns the first positional argument (`bundle`). Swapping `bundle` with `new_bundle` (e.g. `max(new_bundle, bundle,  key=lambda x: x["version"])`) should solve the issue.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-114)
┆Project Name: azul
┆Issue Number: AZUL-114

**Comment by hannes-ucsc** [comment]
Deployed to `dev` now, and reindexing from `integration` instance of `dss` as I write this.
