### ISSUE TITLE
Update Gitlab

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1480]
![image](https://user-images.githubusercontent.com/5143256/69566931-15cf9900-0f6d-11ea-93ea-cc9bf5285f14.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-907)
┆Project Name: azul
┆Issue Number: AZUL-907

**Comment by hannes-ucsc** [comment]
This needs to be deployed to `prod` as well.

**Comment by hannes-ucsc** [comment]
Demo by showing version on `dev`.

**Comment by theathorn** [comment]
Still needs to be deployed to HCA prod.

**Comment by hannes-ucsc** [comment]
All three instances have been updated to latest Gitlab

SC: 43c50f0f
HCA dev: a49b098a
HCA prod: 71b214e7
