### ISSUE TITLE
Create Fusillade admin role(s) for Azul

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1482]
Bento007 writes

> I think this is the kind of functionality you were looking for to manage Azul assets.
```
{
  "roles": {
    "azul_admin": {
      "policy": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "azul_admin",
            "Effect": "Allow",
            "Action": [
              "fus:*"
            ],
            "Resource": [
              "arn:hca:fus:*:*:user/*",
              "arn:hca:fus:*:*:group/azul*",
              "arn:hca:fus:*:*:role/azul*"
            ]
          }
        ]
      }
    }
  }
}
```

We should consider splitting that into a role that the deployment on Azul's Gitlab instance runs as and a role that our release engineers assume. The former should have access to modify or add users.

Bento007 adds

> Also, here are all of the valid actions for fusillade https://github.com/HumanCellAtlas/fusillade/blob/master/docs/fusillade_resouce_actions.json

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-909)
┆Project Name: azul
┆Issue Number: AZUL-909

**Comment by theathorn** [comment]
Closing - Fusillade is deprecated.
