### ISSUE TITLE
Dedicated manifest format for Matrix service hand-off

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1489]
Since https://github.com/DataBiosphere/azul/issues/1226, the compact manifest contains a row per zarray member. This is great for downloading matrices directly from analysis bundles using the CLI but inefficient during Matrix Service hand-over, which only needs the bundle FQIDs. Implement a manifest format called `matrix_service` and generate it from the aggregate bundles index. Only include the `bundle_uuid` and `bundle_version` columns and any other columns the MS team would like to be included.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-915)
┆Project Name: azul
┆Issue Number: AZUL-915

**Comment by calvinnhieu** [comment]
`bundle_uuid` and `bundle_version` are currently required by the MS. `donor_organism.genus_species` is also a required field to be preserved according to this [work to parse species from the manifest](https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/matrix-service/407).

**Comment by hannes-ucsc** [comment]
Matrix service is EOL.
