### ISSUE TITLE
Stop replacing period with underscore in Terra participant_id column

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1493]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-918)
┆Project Name: azul
┆Issue Number: AZUL-918

**Comment by hannes-ucsc** [comment]
The underscores added [here](https://github.com/DataBiosphere/azul/blob/2a854f2c6f17ad784ae42020adc06defea7ecf01/src/azul/service/manifest_service.py#L641) and [here](https://github.com/DataBiosphere/azul/blob/2a854f2c6f17ad784ae42020adc06defea7ecf01/src/azul/service/manifest_service.py#L643) should be periods.

**Comment by theathorn** [comment]
Terra fix is done.
