### ISSUE TITLE
Expose specimen organ and part as a facet

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1497]
The proposed fix for https://github.com/HumanCellAtlas/data-browser/issues/901 is to display `hits[].specimen[].organ` and `hits[].samples[].organ` in a single column. The column header should contain the number of distinct values in that column. There is currently no way for DB to get the unique specimen values.

@NoopDog [proposed](https://github.com/HumanCellAtlas/data-browser/issues/901#issuecomment-561777565) to change the `organ` facet to count both sample and specimen organs but then we would anticipate a DB implementation detail in Azul. It's cleaner to report the distinct specimen organs separately from sample organs. ~The DB would then need to merge the two facet dicts by adding the values with the same key but that should be straight forward to do.~

Everything I said for `organ` applies to `organPart` as well.

In essence this change would entail

```diff
Index: src/azul/project/hca/__init__.py
<+>UTF-8
===================================================================
--- src/azul/project/hca/__init__.py	(revision 2a854f2c6f17ad784ae42020adc06defea7ecf01)
+++ src/azul/project/hca/__init__.py	(date 1575487672118)
@@ -102,6 +102,8 @@
                 "modelOrgan": "contents.samples.model_organ",
                 "modelOrganPart": "contents.samples.model_organ_part",
                 "effectiveOrgan": "contents.samples.effective_organ",
+                "specimenOrgan": "contents.specimen.organ",
+                "specimenOrganPart": "contents.specimen.organ_part",
                 "organismAge": "contents.donors.organism_age",
                 "organismAgeUnit": "contents.donors.organism_age_unit",
                 "organismAgeRange": "contents.donors.organism_age_range",
```

plus any test fixture and assertion changes.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-920)
┆Project Name: azul
┆Issue Number: AZUL-920

**Comment by theathorn** [comment]
Should be a quick fix that doesn't require re-indexing.

**Comment by hannes-ucsc** [comment]
@danielsotirhos PR was merged to `hca/develop` but needs to be ported to `develop` in another PR.

@NoopDog, build https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/pipelines/742 is currently deploying this to `dev`.

**Comment by hannes-ucsc** [comment]
We need to track this through the HCA deployments.
