### ISSUE TITLE
Run all unit tests with AWS_DEFAULT_PROFILE set to a special region

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1498]
There are now various places in the unit tests where `us-east-1` is hard-coded as the AWS region. This is the region that our real deployments live in. Apparently, some moto mocks require a region to be set (the one for SQS, for example). To accommodate those but also as a second line of defence against mocks [becoming ineffective](https://github.com/spulec/moto/issues/1793#issuecomment-512133301) and real resources being used, the test setup at a very high level, potentially `AzulTestCase.setupClass()` should patch AWS_DEFAULT_REGION to some other region, potentially even a made up one.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-921)
┆Project Name: azul
┆Issue Number: AZUL-921

**Comment by theathorn** [comment]
Hannes: PR not a strong enough improvement. No substantially better solution available at this time.
