### ISSUE TITLE
Sort the Dashboard Service tickets

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#15]
These tickets need to be gone through :https://ucsc-cgl.atlassian.net/issues/?jql=project%20%3D%20AZUL%20AND%20status%20%3D%20%22To%20Do%22%20AND%20labels%20%3D%20Dashboard%20ORDER%20BY%20Rank%20ASC

For each ticket it should fall into one of these categories:

* Reject
* Close
* Move to Azul
* Comment that it should be a Commons-Azul only

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-13)
┆Project Name: azul
┆Issue Number: AZUL-13

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
