### ISSUE TITLE
Use portal web site favicons as 'portal_icon' value in portal db

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1501]
To have some consistency in the pixel size of the portal icon images, set the 'portal_icon' property of each portal to the the favicon image from the portal's web site.

Terra Portal : https://app.terra.bio/favicon.png
Single Cell Portal : https://singlecell.broadinstitute.org/single_cell/assets/scp_favicon-1e5be59fdd577f7e7e275109b800364728b01b4ffc54a41e9e32117f3d5d9aa6.ico
Single Cell Expression Atlas : https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.3/images/logos/EMBL-EBI/favicons/favicon.ico
Xena : https://xena.ucsc.edu/icons-9ac0cb8372f662ad72d747b981120f73/favicon.ico

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-923)
┆Project Name: azul
┆Issue Number: AZUL-923

**Comment by theathorn** [comment]
PR #1502.
