### ISSUE TITLE
apidev.py exposes project directory to internet

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1504]
apidev.py seems to listen on all interfaces, note the `0.0.0.0` in the screenshot below.

![Screen Shot 2019-12-06 at 11 33 11 AM](https://user-images.githubusercontent.com/46407464/70350834-67550f00-181c-11ea-89f2-7c015c7dfc64.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-924)
┆Project Name: azul
┆Issue Number: AZUL-924

**Comment by danielsotirhos** [comment]
Closing as invalid.
Checked interface with `lsof` while apidev.py was being run to verify.

**Comment by jessebrennan** [comment]
The script does create a simply local server of your files, but the server is local.
