### ISSUE TITLE
Substitute check cached manifest expiration, deletion and generation

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1507]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-925)
┆Project Name: azul
┆Issue Number: AZUL-925

**Comment by jessebrennan** [comment]
Substitute with what?

**Comment by achave11** [comment]
https://github.com/DataBiosphere/azul/commit/aadb600941657d15056ac0ba87428ce3103c1b94#diff-c2aad48ac91ce2386409a633dfa0034cR234

https://github.com/DataBiosphere/azul/commit/aadb600941657d15056ac0ba87428ce3103c1b94#diff-56be7179c4cc5452d46a352e08d89560R984

**Comment by achave11** [comment]
Closing ticket as obsolete.
