### ISSUE TITLE
Token surplus 

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1515]
Kudos to @danielsotirhos for suggesting that token surplus during reindexing may be caused by duplicate SQS delivery.

[edit by @hannes-ucsc]: Changed the issue title to just specify the problem and moved the hypothesized explanation to the description. Essentially the problem is that we have tokens left over at the end of reindexing. These will circulate for a while and then expire. Expiration is slow, causing unnecessary cost. In addition to determining the cause for the surplus we should, as a workaround, more aggressively expire tokens. We can always rely on the nudge lambda to top up tokens.

**Comment by hannes-ucsc** [comment]
We don't use tokens anymore.
