### ISSUE TITLE
Add code to tag Gitlab and potentially ES instances with owner

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1517]
As required by https://giwiki.gi.ucsc.edu/index.php/Overview_of_Getting_and_Using_an_AWS_IAM_Account.

Not sure if ES instances CAN even be tagged. Start with implementing the Owner tag in the Gitlab instance. Research feasibility of ES instance and domain tagging. I asked our admins via email if tagging is required/desired. We'll decide on the ES tagging once its feasibility and necessity are known.

**Comment by jessebrennan** [comment]
Tagging an ES domain is straightforward
- AWS Docs: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-awsresourcetagging 
- Terraform: https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html

I think we should probably tag all of the resources Azul creates. I've been thinking about which tags would be sensible. Probably
- `AzulStage` : `dev`, or `staging`, etc.
- `AzulProvisionedBy`: `brennan@ucsc.edu
- etc.

**Comment by jessebrennan** [comment]
We will defer the tagging of the ES instance since it's not necessary to prevent automatic shutdown.

Further tagging work can be tracked in #1552
