### ISSUE TITLE
Create personal deployment in SC account

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1532]
Developers should have a personal deployment in both accounts, HCA and SC.

1) Have two separate local clones (I may somewhat incorrectly use the term *checkout* out of habit) of the Azul repo. One for HCA and one for SC.

2) In the SC checkout create a personal deployment (follow instructions in README, copy from example)

3) In the HCA clone checkout the `hca/develop` branch and run `make terraform && make deploy` to ensure that the deployment is up-to-date. If you have more than one personal HCA deployment, consider deleting all but one of them.

Tick the box below next to your name once you are done:

- [x] @GPelayo 
- [x] @hannes-ucsc 
- [x] @jessebrennan 
- [x] @achave11 
- [x] @danielsotirhos
- [x] @noah-aviel-dove

**Comment by hannes-ucsc** [comment]
Spike concludes with above edits to title, description and assignments.

**Comment by achave11** [comment]
My assignment is concluded. 
Service:  https://service.abrahamsc.dev.singlecell.gi.ucsc.edu/health/basic
Indexer:  https://indexer.abrahamsc.dev.singlecell.gi.ucsc.edu/health/basic

**Comment by danielsotirhos** [comment]
Creation completed. Reindex not yet run on sc deployment.
https://indexer.daniel.dev.explore.data.humancellatlas.org/health
https://service.daniel.dev.explore.data.humancellatlas.org/health
https://indexer.daniel.dev.singlecell.gi.ucsc.edu/health
https://service.daniel.dev.singlecell.gi.ucsc.edu/health

**Comment by noah-aviel-dove** [comment]
https://service.nadove.dev.singlecell.gi.ucsc.edu/health/basic
https://indexer.nadove.dev.singlecell.gi.ucsc.edu/health/basic

**Comment by GPelayo** [comment]
https://indexer.geryl.dev.explore.data.humancellatlas.org/health
https://service.geryl.dev.explore.data.humancellatlas.org/health
https://indexer.geryl.dev.singlecell.gi.ucsc.edu/health
https://service.geryl.dev.singlecell.gi.ucsc.edu/health

**Comment by hannes-ucsc** [comment]
To demonstrate I would like everyone to show a non-empty service response form their respective deployments.

**Comment by hannes-ucsc** [comment]
Demoed by @achave11 today.

**Comment by hannes-ucsc** [comment]
Demoed by @danielsotirhos.

**Comment by hannes-ucsc** [comment]
Demoed by @jessebrennan.

**Comment by hannes-ucsc** [comment]
Demoed by @noah-aviel-dove.

**Comment by hannes-ucsc** [comment]
Demoed by me.
