### ISSUE TITLE
Customize boto3/botocore client instances to use the AWS CLI credential cache

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1534]
The code added in https://github.com/DataBiosphere/azul/commit/4b1c051d41198090e13c61c1a16eb61b51403f4d and further improved in https://github.com/DataBiosphere/azul/commit/0c91f9986d361b88d37c07d0568f3a8ff0a65f86 works when the python interpreter is invoked from the same shell that `_preauth` was invoked from, but not when running/debugging code from within PyCharm (unless PyCharm was launched from a shell that already ran `_preauth`).

One solution would be to consolidate boto3 client instantiation in a central place and configure the client to use the AWS CLI credential cache just like `_preauth` function does. Care must be taken to not break, slow down or interfere with client allocation in other contexts, like Travis, Gitlab or AWS lambda.

Also see [this PR](https://github.com/DataBiosphere/azul/pull/846/files) for an previous effort to consolidate the client instantiation.

**Comment by jessebrennan** [comment]
A potential solution is to initialize boto3's botocore session to use a session that links to the CLI cache. This initialization should happen within `envhook.py` script so that it affects every Python process.
