### ISSUE TITLE
Move web service tests into their own respective classes

### ISSUE THREAD

**Issue by jyotheeshwar** [DataBiosphere/azul#154]
Web service tests (eg. summary end-point) are currently placed under the `FacetNameValidationTest` class. They should be separated into their own individual test classes.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-116)
┆Project Name: azul
┆Issue Number: AZUL-116

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/blob/feature/jyo/47-per-organ-cell-count/test/service/request_validation_test.py#L210

**Comment by jyotheeshwar** [comment]
@hannes-ucsc I took a look at `develop`, and I think we can close this issue. the `test_summary` test has now been moved to `test_response.py`.
