### ISSUE TITLE
Automate addition of "orange" label to pull requests

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1540]

**Comment by hannes-ucsc** [comment]
See https://github.com/HumanCellAtlas/azul-github-labeler-action and https://github.com/DataBiosphere/azul/blob/develop/.github/workflows/label.yml. As part of this effort we should also migrate the repo to DataBiosphere.

**Comment by hannes-ucsc** [comment]
As part of this ticket, the assignee, should also make PRs against all repos currently using the action to switch the organisation name in the `uses` entry and bump to the version.
