### ISSUE TITLE
Direct access region needs to be made configurable

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1560]
Follow-up from https://github.com/databiosphere/azul/issues/1536.

The region of the DSS bucket that we access directly is currently hardcoded. That needs to be made configurable.

**Comment by hannes-ucsc** [comment]
See above commit for relevant code sections.

**Comment by melainalegaspi** [comment]
@hannes-ucsc add more detail

**Comment by hannes-ucsc** [comment]
DSS is EOL
