### ISSUE TITLE
Sorting multi-valued fields with `None` fails during aggregation

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1571]
This was introduced in #1524 the fix for #1446

**Comment by theathorn** [comment]
Is this complete?

**Comment by danielsotirhos** [comment]
> Is this complete?

@theathorn Yes, has been merged into develop https://github.com/DataBiosphere/azul/pull/1573
and will be backported to hca/develop by https://github.com/DataBiosphere/azul/pull/1608
