### ISSUE TITLE
Rename `disease` facet to `sampleDisease`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1592]
Once DB switches to `specimenDisease` we can remove the `disease` facet.

Edit: We decided to rename the facet to `sampleDisease` instead of removing it.

**Comment by achave11** [comment]
@hannes-ucsc : "Instead of removing the `disease` facet, we should rename it to `sampleDisease` it might still be useful to filter by the disease of only those specimens that are samples"
