### ISSUE TITLE
Replace ! with / in file names in manifests

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1594]
Related to: https://github.com/HumanCellAtlas/dcp-cli/issues/515

**Comment by chmreid** [comment]
@jessebrennan I don't have enough information to know where to start on this ticket. Should the replacement of ! with / be happening in azul? Do you have any hints about where I might start?

**Comment by chmreid** [comment]
Is anyone able to provide a bundle with an "!" in one of the manifest file paths? I have spent several hours looking for a bundle with an "!" in a file path but have not turned up any.

**Comment by jessebrennan** [comment]
Old bundles that contain MatrixMarket format files are your best bet I
think, sorry I'm not more help.

**Comment by hannes-ucsc** [comment]
MatrixMarket file names don't contain the exclamation mark. Zarray files do:

```
http 'https://service.explore.data.humancellatlas.org/repository/files?filters={"fileFormat":{"is":["matrix"]}}&size=500&sort=fileName&order=asc' | jq '.hits[]|select(.files[].name|contains("!"))|(.bundles,.files)'
```
