### ISSUE TITLE
Some endpoints may return a 500 when mandatory arguments are omitted

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1609]
@noah-aviel-dove found that 

https://github.com/DataBiosphere/azul/blob/1859a365ee51529d3a8cd08fd00f5a41ca759f2f/lambdas/service/app.py#L1097

was lacking `or {}` at the end. That particular occurrence will be fixed in https://github.com/DataBiosphere/azul/pull/1586 but there may be other occurrences. The response should either be a 4xx status response if some or all parameters are required or a successful response otherwise.

**Comment by hannes-ucsc** [comment]
Make a pass over all endpoints to verify if this is an issue anywhere. Then fix as needed.

**Comment by noah-aviel-dove** [comment]
There are no remaining endpoints that produce 500 errors when arguments are missing.

**Comment by noah-aviel-dove** [comment]
`/dss/files` and `/fetch/dss/files` however do produce ugly stack traces when the `replica` parameter is omitted:

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1104, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1282, in fetch_dss_files
    body = _dss_files(uuid, fetch=True)
  File "/var/task/app.py", line 1348, in _dss_files
    dss_response.raise_for_status()
  File "/var/task/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://dss.staging.data.humancellatlas.org/v1/files/ee6a75bd-3252-41ee-b253-425bbd377f0c
```

However Azul doesn't actually require this parameter, it just forwards it to DSS, which does require it. `replica` is documented as required in the Swagger UI but is not checked during parameter validation. Given that we'll soon be migrating away from DSS I suspect it's not worth the bother of filing a PR at this.

**Comment by hannes-ucsc** [comment]
Unless the fix is complicated, I would like use to move forward with this.

**Comment by noah-aviel-dove** [comment]
The fix is trivial. I'll take care of it.
