### ISSUE TITLE
Investigate alternatives to Elasticsearch

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1620]
The current Data Browser index uses Elasticsearch using Amazon's hosted offering for it on AWS. An AWS Elasticsearch cluster that's properly scaled for the load incurred by the ETL processes during (re)indexing turns out to be oversized for normal Data Browser UI loads when serving user requests. Because scaling an ES cluster is relatively complicated and slow, we currently have to choose between low cost or high indexing performance. We will be considering alternative storage engines that scale more dynamically: contenders are Google's Cloud BigTable and Amazon's DynamoDB.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Probably never going to happen."
