### ISSUE TITLE
Proposal for hand-off to HCA GenePattern Notebook

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1640]
UCSD has developed a gene pattern workspace for HCA data adapted from Jupyter notebooks.

It connects to the DCP Matrix Service, passing along user query parameters.

Suggestions for connecting to GenePattern from the HCA Data Browser:
  - link per project in "External Resources" tab
  - link from "Download Project Expression Matrices" page (for pre-generated project matrices)
  - link from "Create Concatenated Expression Matrix" output dialog (for arbitrary expression matrices)
  - single landing page on HCA Notebook which accepts a matrix file URL and possibly a list of associated query parameters

Shared design discussion doc: https://docs.google.com/document/d/1BtAwDY6NsWttIC8oeowBUNhZxvFhrXn9QsJrXSwBRTE/

**Comment by hannes-ucsc** [comment]
I wrote the draft into the provided document.

**Comment by theathorn** [comment]
Proposal is good - waiting for DCP/2 to make further progress.
