### ISSUE TITLE
app.route `method_spec` param value overwritten by another app.route `method_spec`

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#1646]
The `method_spec` param of one `@app.route` is being overwritten by another `@app.route`'s `method_spec` when both `@app.route` have a shared `path_spec`.

Example:
```
swagger_test_path_spec = {
    'parameters': [
        params.query('foo', schema.optional({'type': 'string'})),
    ]
}


@app.route('/swagger-test-1', methods=['GET'], cors=True, path_spec=swagger_test_path_spec, method_spec={
    'summary': 'Swagger test 1',
    'description': 'Swagger test 1',
    'responses': {'201': {'description': 'OK'}}
})
def swagger_test_1():
    pass


@app.route('/swagger-test-2', methods=['GET'], cors=True, path_spec=swagger_test_path_spec, method_spec={
    'summary': 'Swagger test 2',
    'description': 'Swagger test 2',
    'responses': {'202': {'description': 'OK'}}
})
def swagger_test_2():
    pass
```

Expected Result: In the generated Swagger documentation both endpoints would have their unique `method_spec` values.

Acutal Result: The value of the `method_spec` from the `@app.route` last to occur in the source code is applied to both `@app.route`.

<img width="715" alt="Screen Shot 2020-03-18 at 10 34 10 AM" src="https://user-images.githubusercontent.com/46407464/76989944-685e0800-6904-11ea-9477-001bd3f75838.png">

Note that the effect can be negated with a shallow copy of the path_spec:
```
@app.route('/swagger-test-1', methods=['GET'], cors=True, path_spec=copy.copy(swagger_test_path_spec), ...
```

**Comment by hannes-ucsc** [comment]
Residual FIXMEs

https://github.com/DataBiosphere/azul/blob/65970a0947f38fae439a3bf8fd960d351787b7a3/lambdas/service/app.py#L1395
https://github.com/DataBiosphere/azul/blob/65970a0947f38fae439a3bf8fd960d351787b7a3/lambdas/service/app.py#L1460
