### ISSUE TITLE
Switch to SQS FIFO queue trigger for AWS lambda 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1653]
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-amazon-sqs-fifo-event-source/

https://aws.amazon.com/blogs/compute/new-for-aws-lambda-sqs-fifo-as-an-event-source/

It appears that we can now trigger the `azul-indexer-$AZUL_DEPLOYMENT_STAGE-write` lambda directly from the FIFO queue it is actually consuming. Until now, we've been emulating that with token messages in a standard queue.  That emulation is complex and imprecise logic. It affects performance negatively and increases cost by causing a significant number of idle receive message calls.

Remove the emulation, mainly the token concept, the token queue (azul-documents-$AZUL_DEPLOYMENT_STAGE) and the nudge lambda.

**Comment by amarjandu** [comment]
@hannes-ucsc i was looking into what changes we would have to make to the chalice wrappers, and i found this note within the chalice documentation; https://chalice.readthedocs.io/en/latest/topics/events.html#sqs-events it states that FIFO queues are currently not supported by chalice. Should we place this ticket into the backlog? I do not see any issues created to adding FIFO support to Chalice within their github page.

**Comment by hannes-ucsc** [comment]
This is so important to me that I would even consider adding FIFO queue support to Chalice, in a fork. I think we already use a fork anyways. Could you investigate what it would take to do that? I can't imaging it would be that difficult. You may also raise this with the Chalice team to see why the support is not there yet. I'm gonna spike this to one day to cover the research.

**Comment by amarjandu** [comment]
yeah, I'll raise the question with the chalice team and investigate what a solution would look like.

**Comment by amarjandu** [comment]
Issue Raised: https://github.com/aws/chalice/issues/1384
