### ISSUE TITLE
Rename `deploy` target since it doesn't actually deploy anything

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1654]
This isn't actually an issue at time of creating, but it will be once #556 is resolved.

**Comment by jessebrennan** [comment]
@amarjandu suggested `build` which I think is fitting.

**Comment by hannes-ucsc** [comment]
`build` is ambiguous. We say "Travis build", "Gitlab build", "the build failed" and so on. In a way running make with any target could qualify as a "build".

I like `package`.
