### ISSUE TITLE
Review the Broad data repository design

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1663]
https://docs.google.com/document/d/1KGsrHt6lpiSL7e6LQ981BnmXAYVsddlZLqxIvDrT_Mk/edit#

**Comment by theathorn** [comment]
Kathleen: To what extent (if any) can the data browser depend on the core Terra data model, rather than the schema, to support its current functionality?
Terra data model: https://github.com/DataBiosphere/terra-core-data-model

**Comment by theathorn** [comment]
@NoopDog @hannes-ucsc There's been a suggestion we could use htsget (http://samtools.github.io/hts-specs/htsget.html) for streaming downloads..

**Comment by hannes-ucsc** [comment]
Copy for our own comments: https://docs.google.com/document/d/1dJEhVaib4MYhW9EQVW1PfsIV03HDLszsIv9U9raa644/edit?usp=sharing

**Comment by theathorn** [comment]
Port comments for Kathy to original doc.
