### ISSUE TITLE
Swagger UI lists routes in arbitrary order

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1665]
This is screenshot of the sandbox but the code on the sandbox will be on `dev` in about 30 min.

![image](https://user-images.githubusercontent.com/5143256/78061281-d8777f80-7341-11ea-9339-00275b1e7891.png)

Note how the routes tagged Auxiliary are randomly ordered. 

Within a tag, the routes should be listed in the same order as the corresponding handlers are defined in the code. Ideally, the tags should be listed in the same order they are defined in `openapi_spec`.

**Comment by jessebrennan** [comment]
This will be solved by #1687
