### ISSUE TITLE
Test logs are too noisy

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1670]
There simply too many of these: https://travis-ci.org/github/DataBiosphere/azul/builds/670311272#L757

Either combine them in one log statement like https://travis-ci.org/github/DataBiosphere/azul/builds/670311272#L756 or demote them to DEBUG.

**Comment by amarjandu** [comment]
This might be useful. https://github.com/HumanCellAtlas/data-store/pull/2561
