### ISSUE TITLE
`make terraform` is not stable on Gitlab

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1673]
I'm using the term `stable` in the way it is used to describe stable sorts. Don't know if there is better term.

Two consecutive retries of the `deploy` job on  https://github.com/DataBiosphere/azul/pull/1635:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/1546
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/1547

Even though there were no changes to code or infrastructure between these two jobs, the second job redeployed the lambda and the gateway.

This is currently only reproducible on that PR branch but I am leaning towards merging that PR despite this issue so it will shortly be reproducible on the `develop` branch as well.

**Comment by jessebrennan** [comment]
I don't know how I overlooked this before, but Chalice now ensures that the ZIP that is generated is deterministc. https://github.com/aws/chalice/commit/635de7f2561357bbe0539b7da59173ef5c876962 

This appears in 13.1 at the earliest. I think the most sensible approach is just to update the version of Chalice that we use.

**Comment by hannes-ucsc** [comment]
#1725 was merged but `make terraform` still appears to be unstable:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/2911
