### ISSUE TITLE
Improve layout of daily AWS and GCP cost reports 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1674]
Work with the admins on that. I'm sure they'd be open to improving the usability of the report.

**Comment by theathorn** [comment]
@hannes-ucsc suggested HTML format.

**Comment by hannes-ucsc** [comment]
Her are my biggest cosmetic pain points:

- tables aren't tabular so columns don't align and rows look jagged
- Headings don't stick out enough
- headings are closer to the preceding section and look more like "footings"
- there should be anchor links from the top into each account

**Comment by natanlao** [comment]
After speaking with @hannes-ucsc, this ticket is being expanded to refactor some of the sensitive hardcoded configuration out of the script so that final changes can be reviewed without exposing sensitive data and while minimizing changes to the original script.

**Comment by theathorn** [comment]
Today's email has the latest changes and is ready for review.

**Comment by hannes-ucsc** [comment]
The report for GCP hasn't been updated.

**Comment by melainalegaspi** [comment]
@theathorn: "Should update the CGP cost report as well."

**Comment by natanlao** [comment]
Transferred to ucsc-cgp/cloud-billing-report#4.
