### ISSUE TITLE
Investigate EC2 cost spike in platform-sc account

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1675]

**Comment by hannes-ucsc** [comment]
The cost spikes can be attributed to data transfer through the EC2 NAT Gateway.

![image](https://user-images.githubusercontent.com/5143256/78598008-5684cc00-7803-11ea-842d-6129cc15aa78.png)

The release bucket with the h5ad files is fronted by a CF distro and the cellxgene container is given the public `https://` CF URL. I'm pretty sure this causes the traffic for accessing the files to be routed through the NAT Gateway.

The big question is if this only occurs when the container is started up or also during regular operation. As far as I understand `--backed` mode, the latter is entirely possible.

Same report on HCA prod:

![image](https://user-images.githubusercontent.com/5143256/78599563-39053180-7806-11ea-8915-ca40f7fa1cab.png)

I did launch the prod instances on Friday afternoon PDT (Sat in UTC) and that correlates with the spike there.

**Comment by hannes-ucsc** [comment]
The same graph for HCA dev does not show any spikes in the last seven days from which follows that the simply running and using the container does not cause excessive NAT traffic.

@noah-aviel-dove and I were able to correlate this to memory-starved containers continuously being restarted by the health checks. He will make sure that the system is not left in this state (either by ensuring that the config doesn't starve containers for memory or by tearing the deployment down at the conclusion of experiments).

**Comment by hannes-ucsc** [comment]
cellxgene containers, that is.

**Comment by melainalegaspi** [comment]
Hannes- "investigation complete, follow up on cellxgene-fargate#12"
