### ISSUE TITLE
Incorrect Default Sort Criteria is being Sent on /specimens response

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#169]
When we hit /specimens with no sort parameter specified, the server returns a paging object that sets the default sort.

This object has the default sort as `entity_id`. entity_id is the old name and it should be the specimen id field.

```
"pagination": {
    "count": 1,
    "total": 414,
    "size": 1,
    "search_after": "ff938e1c-f587-416d-8c3d-951bc7847ecb",
    "search_after_uid": "doc#ff938e1c-f587-416d-8c3d-951bc7847ecb",
    "search_before": null,
    "search_before_uid": null,
    "pages": 414,
    "sort": "entity_id",
    "order": "desc"
  },
```

When we send sort=entity_id back to you when a facet is selected we get an error "cant sort by this field entity_id".

I have temporarily disable the front end from reading in the bad default sort until this is fixed.

Thanks!
D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-125)
┆Project Name: azul
┆Issue Number: AZUL-125

**Comment by theathorn** [comment]
Dave says "yes" (default sort parameter  = specimenId)
