### ISSUE TITLE
`make reindex` exits prematurely

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1696]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/1613

As evident in the above log `make reindex` exists before the queues are empty.

1) `make reindex` should fail when it times out instead of just logging "NOT at the desired level"

2) The GL job timeout should be increased to accommodate the longest possible indexing time we've observed. I think 12h is sufficient. The goal is to ensure that `make reindex` times out before GL does.

3) `make reindex` should not timeout after just 1h when no prefix is specified. A reindex of DSS staging takes about 4-6 hours. A smart way to adjust the timeout would be to track the maximum number of messages in the notification queue (which approximates the # of bundles) and compute the timeout from that maximum. A linear relationship should do.

@danielsotirhos could be consulted for advice on this as well.

**Comment by achave11** [comment]
To conclude demo show reindex stage timeout/complete under the dynamically calculated timeout.

**Comment by theathorn** [comment]
@hannes-ucsc to reindex dev.
