### ISSUE TITLE
Bagit Generation should use ES to sort

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#17]
The generation of the bagit requires the TSV to be ordered by specimen UUID. We currently sort that in the Python code, and should instead request that Elasticsearch return the data already sorted.

This comes from issue https://github.com/DataBiosphere/dcc-dashboard/issues/9

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-17)
┆Project Name: azul
┆Issue Number: AZUL-17

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

Let's stall this  on Firecloud endpoint

**Comment by mjkrause** [comment]
obsolete
