### ISSUE TITLE
List facets included in Terra core data model

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1702]
Which facets are and are not represented in the [Terra core data model](https://github.com/DataBiosphere/terra-core-data-model)?

**Comment by danielsotirhos** [comment]
Comparison of fields indexed by Azul vs Terra Core Data Model [azul-x-terracore.txt](https://github.com/DataBiosphere/azul/files/4530702/azul-x-terracore.txt)

**Comment by theathorn** [comment]
From Kathy Reinold see: https://drive.google.com/drive/folders/1VRGG0Axi5Tx_u_6X9FDW0CyzAPVgHUxH

**Comment by melainalegaspi** [comment]
@theathorn : "Can close then open new tickets when we get back to Terra core data model."
