### ISSUE TITLE
Change ES instance snapshot time

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#1703]
The shared ES instance within `platform-sc` is set to snapshot at 2300UTC, which is around 3PM PST, we should change this to be 0800 UTC  to avoid running into reindex errors.

**Comment by hannes-ucsc** [comment]
Doesn't seem to be working anymore https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/3419

**Comment by hannes-ucsc** [comment]
Snapshot was stuck. DIfferent problem.
