### ISSUE TITLE
Create on-boarding doc

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1717]
This was suggested in retro. Would be helpful to have a central document/space that outlines all links to on-boarding resources: Azul overview, GitLab access, etc.

Add in README and have bulleted list of introductory/on-boarding steps

**Comment by amarjandu** [comment]
Standup: 4/21/2020
Request from Hannes. 
Touch base with Noah for using travis-test for (big-query + Terra):
