### ISSUE TITLE
AzulTestCase leaves Docker containers running on Linux

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#172]
Continued from https://github.com/DataBiosphere/azul/pull/145#discussion_r208332604.

Reproduction: 

1) Run `docker ps` and kill any containers for the docker.elastic.co/elasticsearch/elasticsearch:5.5.3 image.
2) Run tests in test_request_validation.py. 
3) Run `docker ps` again.

Expected: No container for docker.elastic.co/elasticsearch/elasticsearch:5.5.3 should be listed.
Actual: A container is listed.

If you run the test again, it will timeout during setup with:

```
./shared.py:49: AssertionError
---------------------------- Captured stderr setup -----------------------------
ERROR:shared:Docker container took more than a minute to set up
```

Additional information, but maybe unrelated:

On macOS, if you comment out `cls._es_docker_container.kill()` in `AzulTestCase.tearDownClass()` and then run the test it will obviously also leave a container running but when you run the test again the previous container is magically killed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-128)
┆Project Name: azul
┆Issue Number: AZUL-128

**Comment by theathorn** [comment]
Need to reproduce on Mac and Linux.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "cannot reproduce".
