### ISSUE TITLE
Verify consistency of process entries in links.json

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1720]
@hannes-ucsc: We know that the same links.json entry can be duplicated in multiple links.json files. But can more than one different links.json entry refer to the same process? IOW, for any two links (entries in any links.json in any bundle), if their `process` field is the same, can we assume that the other fields (`inputs`, `input_type`, `output`, `output_type`, `protocols`) are also the same in both links?

@NoopDog: This can be answered with a query, but it would seem to me that if the process document id is the same then the inputs and outputs need to also be the same.

Each process is a "process instance" and runs only once and produces a fixed set of output given some input.

Unless the links are a "partial" view of full set of inputs/outputs for a process run, the attributes for a link entry would have to be the same every place the process id is used.

It would be interesting to run a scan verifying this. Any place where the invariant is not true is likely a mistake in the data.

**Comment by hannes-ucsc** [comment]
Amar, since you are currently looking at all the links.json in the prod DSS. Could you also look for the biggest links.json you can find and point to it here?

**Comment by amarjandu** [comment]
@hannes-ucsc

I've searched through the data several times, and for the largest links.json file i get the following;

links.json:  `17e8d07f-238d-4c47-b193-a230a54afc47.2019-05-16T134201.527198Z`
`http "https://dss.data.humancellatlas.org/v1/files/17e8d07f-238d-4c47-b193-a230a54afc47?replica=aws&version=2019-05-16T134201.527198Z"`

which is part of:

bundle-fqid: `fe4e5fa7-dacf-4c88-af36-6cc75ec36116.2019-05-16T123000.511000Z`
See attachment for bundle-manifest, please note the manifest is large, if using the API it requests must be paged to view the complete manifest. 
[fe4e5fa7-dacf-4c88-af36-6cc75ec36116.2019-05-16T123000.511000Z.txt](https://github.com/DataBiosphere/azul/files/4524289/fe4e5fa7-dacf-4c88-af36-6cc75ec36116.2019-05-16T123000.511000Z.txt)

there are `769 links` present within the `links.json` file, the size within the DSS is `523527 bytes`

I'm double checking my work to answer the question from the OP. So far it would appear that for a given process_id, the other fields `(inputs, input_type, output, output_type, protocols)` are the same. 

I'll place any updates to my research here.

**Comment by theathorn** [comment]
Produce histogram of links.json link count in buckets (e.g. 0-10 links, 11_20 links, etc).

**Comment by amarjandu** [comment]
@hannes-ucsc I can make a histogram from the data, but it seemed very sparse and easier interpret by just looking at the values. 

```
# of links in links.json: # of occurrences 
{2: 80,
 3: 134161,
 4: 2619,
 5: 1768,
 7: 10141,
 11: 1733,
 14: 6,
 15: 6,
 17: 3,
 769: 25}
```

I can still make a histogram if you need one.

**Comment by hannes-ucsc** [comment]
Yes, a histogram is not necessary. Continued in #1724.
