### ISSUE TITLE
Review DRS compact identifier-based URI consensus PR

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1726]
From BrianO:
Hey Folks,

So after a lot of great conversations with a lot of different folks I wrote up what I think could be a consensus PR that gets us to compact identifier support in DRS URIs.  

https://github.com/ga4gh/data-repository-service-schemas/pull/318

You've all pretty much seen this exact proposal already, I just tweaked things like the order of sections in the spec.

We have a cloud work stream meeting on Monday (2pm pacific, see ga4gh.cloud).  If it's at all possible, could you all take a quick look at the PR and leave a comment with a thumbs up?  I'm trying to drive consensus in the group and I feel like we're close (we just have David G and Ian's PRs still open).  So your endorsement of this, I think, will help us reach agreement in the work stream.  Of course, if you have concerns or issues I definitely want to hear that as well, please comment on the PR.

Thanks for your help on this!!  With any luck we can use the Monday call to reach consensus.

**Comment by melainalegaspi** [comment]
We voted +1
