### ISSUE TITLE
Swagger editor does not predict errors in Swagger UI

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#1730]
OpenAPI spec that works perfectly in the swagger editor (via the apidev.py script), with no errors or warning, fails in deployment. This largely defeats the purpose of the apidev script since changes to the spec must be fully deployed to test for correct functionality.

The motivating example is the addition of an `example` property to the `filters` query parameter:

```
"content": {
    "application/json": {
        "schema": {
            "type": "object",
            "properties": {
                ...
            },
            "additionalProperties": false,
            "example": {
                "cellCount": {
                    "within": [
                        [
                            10000,
                            10000000000.0
                        ]
                    ]
                }
            }
        }
    }
}
```

In the Swagger editor/apidev script, this structure successfully renders the example and the console shows no errors. In the deployed Swagger UI, the entire `filters` parameter fails to render and the console shows the error `TypeError: Cannot read property 'get' of undefined`.

Regardless of whether the above JSON is perfectly correct we need to re-establish consistent behavior between the editor and the UI.

See the error in action [here](https://service.nadove.dev.singlecell.gi.ucsc.edu/#/Repository/get_repository_files).

Suggested fix to try: updating swagger UI.

**Comment by hannes-ucsc** [comment]
JS console logs

```
TypeError: "M is undefined"
    value parameter-row.jsx:175
    render root-injects.jsx:93
    React 7
        _renderValidatedComponentWithoutOwnerOrContext
        _renderValidatedComponent
        _updateRenderedComponent
        _performComponentUpdate
        updateComponent
        receiveComponent
        receiveComponent
root-injects.jsx:95:14
    render root-injects.jsx:95
    React 199
```

**Comment by hannes-ucsc** [comment]
First thing to try is to update both UI and editor to their respective latest versions.
