### ISSUE TITLE
Optimize lambda memory usage

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1732]
99.9% of all tallies can be processed with 1G of memory and only the remaining 0.1% need 3G. This means that we are paying three times more for the `-write` lambda than we need to.

We should create a more sophisticated two-stage pipeline for the -write lambda.

Stage 1 is driven by the documents queue. Its retry policy should be set to a single attempt. Stage 1 is configured to use 1G of memory. Failures in the first stage should go into a second documents queue. This queue drives the second stage, which is configured to use 3G (the max) and has a redrive policy of 10 attempts with failures going into the -fail queue.

Since this touches queue and lambda names, we should use the opportunity to fix the names. For example, rename the `…-documents` queue to `…-tally`.

**Comment by melainalegaspi** [comment]
Try reordering qualified resource name

**Comment by hannes-ucsc** [comment]
Bumped estimate to account for freebie #613.
