### ISSUE TITLE
Log when manifest content hash is computed

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1739]
This would indicate that the content-hash generated by the service is being recycled and used in the step-function. This is done in order to generate a manifest if one isn't already available from cache.

**Comment by hannes-ucsc** [comment]
It's fine to log the fact that a provided object key is reused, but more importantly, the code should emit a log statement before any long-running operation, and this includes the ES request that produces the content hash. I've edited the title accordingly.
