### ISSUE TITLE
Evaluate Terra's data-explorer and data-explorer-indexes

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#175]
https://github.com/DataBiosphere/data-explorer
https://github.com/DataBiosphere/data-explorer-indexers

Use as inspiration for making Azul web service more generic.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-129)
┆Project Name: azul
┆Issue Number: AZUL-129

**Comment by theathorn** [comment]
Codename Saturn now has an official name of Terra.

**Comment by hannes-ucsc** [comment]
TDR is the default repository for DCP/2.
