### ISSUE TITLE
Create DSS adapter script 

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1753]
https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit?usp=sharing

**Comment by hannes-ucsc** [comment]
scripts/dss_v2_adapter.py

Command line arguments should be the URL to the source DSS and the name of the v2 staging bucket as the destination.

**Comment by hannes-ucsc** [comment]
For now we can use the `travis-test` project for Google but as soon as #1766 is solved, we can switch to the v2-specific Google project.

**Comment by hannes-ucsc** [comment]
As an extension we should make the target (2nd) script argument a full `gs://bucket/prefix` URL so multiple adapter invocation can share a bucket in isolated prefixes. The standard invocation would be `gs://bucket/` (empty prefix).

**Comment by danielsotirhos** [comment]
Making this ticket a freebie of #1834
