### ISSUE TITLE
Configure ElasticsearchFakeDataLoader to use the Elasticsearch settings and mappings from IndexerProperties

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#176]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-130)
┆Project Name: azul
┆Issue Number: AZUL-130

**Comment by achave11** [comment]
@theathorn change assignee once they join git.

**Comment by shiroyuki** [comment]
@mpanik Here is the patch for this ticket.

[20180827_GH176.diff.txt](https://github.com/DataBiosphere/azul/files/2325565/20180827_GH176.diff.txt)

**Comment by shiroyuki** [comment]
@mpanik Here is the patch for this ticket.
[20180828_GH176.diff.txt](https://github.com/DataBiosphere/azul/files/2328465/20180828_GH176.diff.txt)

This patch also includes the update to prevent timeouts from failing the tests.

**Comment by shiroyuki** [comment]
@mpanik Here is the updated patch [20180828_GH176.diff.txt].(https://github.com/DataBiosphere/azul/files/2328658/20180828_GH176.diff.txt)

This removed `str.format(*args, **kwargs)`.

**Comment by shiroyuki** [comment]
Here is the final patch for this ticket, I believe.
[20180828_GH176.diff.v3.txt](https://github.com/DataBiosphere/azul/files/2329288/20180828_GH176.diff.v3.txt)

I took out the idea of using *Docker Compose* as it took too much work to hack around undocumented APIs.
