### ISSUE TITLE
Create new AWS account for DCP v2

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1765]
Should be called `platform-hca`. Same users and privileges as `platform-sc`.

**Comment by hannes-ucsc** [comment]
Also create new Google project and service accounts for each team member.

**Comment by theathorn** [comment]
Erich has created a new platform-hca account.

**Comment by theathorn** [comment]
Hannes to create follow on ticket(s) for infra work.

**Comment by melainalegaspi** [comment]
Duplicates #1766
