### ISSUE TITLE
Create new Google projects and AWS accounts for DCP v2

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1766]
There should be 2 Google projects: platform-hca-dev and platform-hca-prod. Additionally, there should be 2 AWS accounts with the same names. The platform-hca-dev AWS account and Google project should be provided by renaming the existing platform-sc account/Google project.

**Comment by hannes-ucsc** [comment]
Give access to team members so they can create their own service accounts.

**Comment by theathorn** [comment]
Over to @hannes-ucsc to answer Erich's question: "Can I delete the old "platform-hca-dev" (platform-sc)
GCP account first?".

**Comment by amarjandu** [comment]
Project "platform-sc" is now shut down and scheduled to be deleted after 7/19/20.

**Comment by hannes-ucsc** [comment]
This is done: the two GCP projects and the two AWS accounts exist.
