### ISSUE TITLE
Some deployments are failing and not logging to CloudWatch

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1775]
This is being investigated with AWS support. This is the support ticket:
https://console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=6979023071&language=en

**Comment by jessebrennan** [comment]
@hannes-ucsc asked me to run the following experiment to try to produce an incorrect key grant for the lambda's role:

1. `terraform destroy` one of the roles. Observe if any other resources were changes.
2. `make terraform` again.
3. Before and after each of these steps, take a snapshot of the grants and see what changes.

## Results

Before step 1., a normal deployment has key grants that reference the ARN of the role. I confirmed this before running `terraform destroy`.

I ran `terraform destroy -target aws_iam_role.indexer`. Terraform deleted the role *and* all of the attached lambdas. There is an explicit Terraform dependency here.

After running destroy, I took another snapshot of the key grants. The entries which were previously just ARN references, changed to ID references.

I ran `make deploy`. Interestingly I received an error that I hadn't seen in a long time:

```
Error: Error creating API Gateway Deployment: ConflictException: Another Deployment is in progress for rest api with id yrerhg8djg . Please try again later.

  on indexer/chalice.tf.json line 312, in resource.aws_api_gateway_deployment.rest_api:
 312:             }
```

As expected, this resolved after running `make deploy` again.

After running `make deploy` again, I examined how the grants had changed. The ID grants from the previous stage remained, but new grants were created. These new grants were all ARN grants.

## Conclusions

I have a possible explanation for how my `jesse0` deployment got screwed up in the first place. I don't remember exactly what I did that caused it to break, but I remember that I had to import some resources into terraform at some point. Assuming that is the case, it's possible that I imported a resource that had an ID grant, but the lambdas already existed. If the import didn't trigger an update to the lambdas then the grants would only reference the role IDs, not the role ARNs.

**Comment by hannes-ucsc** [comment]
> After running destroy, I took another snapshot of the key grants. The entries which were previously just ARN references, changed to ID references.

I would report that to AWS. The destruction of either the lambda function or the role causes the grants to revert from ARN to ID.

**Comment by hannes-ucsc** [comment]
@jessebrennan please check if #1911 has anything to do with this.

**Comment by jessebrennan** [comment]
Changing the value of the `iam_role_arn` reference in `lambdas/service/.chalice/config.json.template.py` to be a reference to the actual ARN, fixed the issue. `jesse0` is now working properly!
