### ISSUE TITLE
Promote all fixes and backports to DCP/1 `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1778]
Since for DCP/2 MVP analysis will be run using our Terra hand-off from our DCP/1 (!) `prod` instance we need to promote all bug fixes currently sitting on the `hca/dev` branch to `hca/prod`.

Some of them are breaking changes so promotion needs to be coordinated with DB team.

**Comment by theathorn** [comment]
@hannes Do we go straight from dev to prod or stop at staging for validation?

**Comment by hannes-ucsc** [comment]
`hca/dev` points at DSS integration so we should pause the promotion at `staging` since `hca/dev`.

@achave11, could you promote `dev` to `integration` and `integration` to `staging` and then trigger a reindex in staging (yes staging reindex first). When the staging reindex is finished, kick one off in `integration` and  `dev` (both at the same time is ok).

**Comment by hannes-ucsc** [comment]
@NoopDog: @achave11 promoted all outstanding backported fixes from `hca/develop` to `hca/staging`. Unless you ask me not to, we are planning on promoting them to `hca/prod` on Monday at noon. I'll send a G calendar invite.

**Comment by hannes-ucsc** [comment]
Invite was sent out. @achave11, please be prepared for the promotion.

**Comment by theathorn** [comment]
@achave11 Can we get the release notes as per the normal release process?
Similar to what @NoopDog does for the Data Browser/Portal.

**Comment by achave11** [comment]
@theathorn is this good, is there a specific location where you want the release notes to be posted? 

Release Notes `hca/develop`:
```txt
256d1f20 Update Gitlab to 12.9.2 (#1685)
```

Release Notes `hca/integration`:
```txt
 256d1f20 Update Gitlab to 12.9.2 (#1685)
 3e504625 Improve assertion messages for `translate_fields`
 d6dfb1ef Fix paging when sorting on fields with Null values (#1575)
 33caef26 Sorting by multi-valued fields (#1445)
 3486a3a6 Fix: TypeError aggregating multi-valued fields with None (#1571)
 2006281f Always sort multi-valued fields (#1446)
 6e84b9f2 Verify labCount in summary aggregation (#1188)
 dfaa77fe Backport: Add specimenDisease facet (#1624)
```

Release Notes `hca/staging`:
```txt
 256d1f20 Update Gitlab to 12.9.2 (#1685)
 3e504625 Improve assertion messages for `translate_fields`
 d6dfb1ef Fix paging when sorting on fields with Null values (#1575)
 33caef26 Sorting by multi-valued fields (#1445)
 3486a3a6 Fix: TypeError aggregating multi-valued fields with None (#1571)
 2006281f Always sort multi-valued fields (#1446)
 6e84b9f2 Verify labCount in summary aggregation (#1188)
 dfaa77fe Backport: Add specimenDisease facet (#1624)
```

Release Notes `hca/prod`:
```txt
 256d1f20 Update Gitlab to 12.9.2 (#1685)
 3e504625 Improve assertion messages for `translate_fields`
 d6dfb1ef Fix paging when sorting on fields with Null values (#1575)
 33caef26 Sorting by multi-valued fields (#1445)
 3486a3a6 Fix: TypeError aggregating multi-valued fields with None (#1571)
 2006281f Always sort multi-valued fields (#1446)
 6e84b9f2 Verify labCount in summary aggregation (#1188)
 dfaa77fe Backport: Add specimenDisease facet (#1624)
```

**Comment by theathorn** [comment]
How did we normally provide release notes for Azul when promoting to prod?
Here's an example [doc](https://docs.google.com/document/d/1Fjz4uAsDL4fHT9HDyQjj_ialxQB9waiedCUejjrNx3E/) for the Data Browser.

**Comment by achave11** [comment]
> How did we normally provide release notes for Azul when promoting to prod?
> Here's an example [doc](https://docs.google.com/document/d/1Fjz4uAsDL4fHT9HDyQjj_ialxQB9waiedCUejjrNx3E/) for the Data Browser.

Usually we would fill out a [template](https://docs.google.com/document/d/1tMAPzqdCtH1Yq3iWtvPABSeRtaLOPfQIurkOpHvl1Pc/edit#) for the Azul section. It seems like the doc for the Data Browser is using a different protocol.

**Comment by melainalegaspi** [comment]
no more outstanding work to be done
