### ISSUE TITLE
Determine if we can use GCS copy functionality between buckets

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1780]

**Comment by hannes-ucsc** [comment]
@danxmoran pointed me at https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite

> If the source and destination are the same location and storage class and use the same server-side encryption (either the default server-side encryption, or the same customer-supplied encryption key), the rewrite method returns in a single RPC, that is, you do not need to use additional calls specifying a rewriteToken.There are no additional I/O charges. If the source and destination are different locations or storage classes, or if they are encrypted differently, the rewrite method might require multiple calls and there will be I/O charges (see pricing).

I'll perform a quick test to confirm this.

**Comment by hannes-ucsc** [comment]
@noah-aviel-dove could you help with this? I would like to confirm whether use of the above API with two GS buckets in the same "location" does indeed return immediately "in a single RPC". The copied object should be reasonably big. As the source bucket use `org-hca-dss-staging` in the `travis-test` Google Cloud project. Use a big object from underneath the /blobs path. As the destination bucket use a temporary bucket created for this purpose.

**Comment by noah-aviel-dove** [comment]
I believe I have confirmed that this works, i.e., the operation does return immediately.
The request parameters were:

- sourceBucket: org-hca-dss-staging
- sourceObject: blobs/0002dcbc9cb01aa77c40fa2465acd11b09712c9d703eefb9bf811cf0db9ac48d.26c00e1c4f53b9f0800d1ef84020efc887eaa608.996840844b12323a10dd3c1e8bbb5a4e-7.488f068f
- destinationBucket: azul-1780-gcs-copy-test
destinationObject: test

The destination bucket was created by me and has the same location type, location, default storage type, and encryption as the source bucket. The file I selected is 446 MB.

The response (status code 200) was: 
```
{
 "kind": "storage#rewriteResponse",
 "totalBytesRewritten": "467796241",
 "objectSize": "467796241",
 "done": true,
 "resource": {
  "kind": "storage#object",
  "id": "azul-1780-gcs-copy-test/test/1588905110163926",
  "selfLink": "https://www.googleapis.com/storage/v1/b/azul-1780-gcs-copy-test/o/test",
  "name": "test",
  "bucket": "azul-1780-gcs-copy-test",
  "generation": "1588905110163926",
  "metageneration": "1",
  "contentType": "application/gzip; dcp-type=data",
  "timeCreated": "2020-05-08T02:31:50.163Z",
  "updated": "2020-05-08T02:31:50.163Z",
  "storageClass": "MULTI_REGIONAL",
  "timeStorageClassUpdated": "2020-05-08T02:31:50.163Z",
  "size": "467796241",
  "mediaLink": "https://content-storage.googleapis.com/download/storage/v1/b/azul-1780-gcs-copy-test/o/test?generation=1588905110163926&alt=media",
  "owner": {
   "entity": "user-nadove@ucsc.edu"
  },
  "crc32c": "SI8Gjw==",
  "componentCount": 1,
  "etag": "CNajseWco+kCEAE="
 }
}
```

`"done": true` and the absence of a token to be included with a subsequent request is the information I believe we are looking for. The object appeared in the destination bucket no more than five seconds later. The response itself appeared milliseconds after I submitted the request.

**Comment by noah-aviel-dove** [comment]
The test bucket is still up in case additional testing is requested. Otherwise I'll remove it when the issue is resolved to @hannes-ucsc's satisfaction.

**Comment by noah-aviel-dove** [comment]
Test bucket deleted.

**Comment by hannes-ucsc** [comment]
LGTM
