### ISSUE TITLE
Moto's dependency on `future` gets in the way

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1783]
It pulls in some urllib shim that pretends urlparse returns bytes. 

![image](https://user-images.githubusercontent.com/5143256/81436300-18d6d400-911e-11ea-8bec-2ae7ba4c14b9.png)

I think we should try to prevent `future` from being installed. Don't know if that's possible.

**Comment by melainalegaspi** [comment]
@achave11 sees a connection to the need for patching the maximum header count in test_deletions #1719

**Comment by hannes-ucsc** [comment]
I can't repro this anymore. It may have been fixed inadvertently by upgrading future to in PR #1882 for #1738. I used to have future 0.14.0 in my virtualenv but now I have 0.16.0. Gitlab builds have been reporting `future` to be at 0.16.0 for months.

The associated PR should just remove the FIXME and a demonstration should show that this can't be reproduced.

**Comment by hannes-ucsc** [comment]
Ignore previous comment. I am still able to [repro](https://github.com/DataBiosphere/azul/pull/1875#issuecomment-643478925) this.

I don't think this is `future`'s fault and I think the ticket description is wrong.
