### ISSUE TITLE
Move ! to / substitution in file names to metadata API

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1785]
We [currently](https://github.com/DataBiosphere/azul/commit/e1ed6357db9a142fdd56b3cdec3b0cd64667e8aa#diff-28c1078f1dd7e70fa2571b791e1eaad4R81) substitute ! for / in file names in Azul's HCA metadata plugin and in FullMetadata._handle_zarray_members. 

It would be easier to do in the metadata API. Remove the handling of ! from Azul and implement the substitution for both manifest entries and `file_core.file_name` in `hca-metadata-api`.

**Comment by melainalegaspi** [comment]
@hannes-ucsc needs description

**Comment by hannes-ucsc** [comment]
Description provided.
