### ISSUE TITLE
Delete "HDCA project: single cell transcriptomics" from prod & staging

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1797]
Project: https://data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774

Tombstone and delete all the files associated with this project and re-index in Azul.

- [x] tombstone bundles in DSS `prod`
- [x] delete bundles in DSS `prod`
- [x] check if project disappears in DB `prod`, if not file ticket and reindex Azul `prod`
- [x] delete associated files in DSS `prod`
- [x] notify @danielsotirhos to clear out his test buckets for the DCP v2 adapater he's working on
- [x] delete bundles in DSS `staging`
- [x] check if project disappears in DB `staging`, if not reindex Azul `staging`
- [x] delete associated files in DSS `staging`
- [x] tombstone bundles in DSS `integration`, if any
- [x] if applicable, check if project disappears in DB `integration`, if not reindex Azul `integration`
- [x] delete associated files in DSS `integration`, if any
- [x] reindex all platform-sc deployments since most if not all index (but aren't subscribed to) DSS `prod`

**Comment by theathorn** [comment]
It also needs to be deleted from the staging environment.

**Comment by amarjandu** [comment]
@theathorn  is this the correct project in `staging` https://staging.data.humancellatlas.org/explore/projects/008e40e8-66ae-43bb-951c-c073a2fa6774

**Comment by theathorn** [comment]
Reason: Needs to be removed from the DCP and has now been submitted to the EGA
due to GDPR restrictions.

**Comment by amarjandu** [comment]
Updated Tombstone List: https://gist.github.com/amarjandu/6f50176c7b6ce7e1ae32812a506b7bea

**Comment by amarjandu** [comment]
@danielsotirhos here is the object-reference-list for the deletion campaign on prod, please remove these objects from your migration bucket. [https://app.zenhub.com/files/139095537/e7ede5f3-0719-44af-851f-972cbaf298c7/download](https://app.zenhub.com/files/139095537/e7ede5f3-0719-44af-851f-972cbaf298c7/download)

**Comment by amarjandu** [comment]
project deletion complete in `dss-prod` and `dss-staging`

**Comment by danielsotirhos** [comment]
> @danielsotirhos here is the object-reference-list for the deletion campaign on prod, please remove these objects from your migration bucket. https://app.zenhub.com/files/139095537/e7ede5f3-0719-44af-851f-972cbaf298c7/download

DCP v2 adapater test buckets `danielsotirhos_tdr_test_bucket` and `tdr_test_staging_bucket` emptied of all copied data.

**Comment by amarjandu** [comment]
data deletion complete in old buckets `org-humancellaltas-dss-prod`
