### ISSUE TITLE
Ensure that sample ID is included in Terra handover

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1805]
https://humancellatlas.slack.com/archives/C01360XN04S/p1589488362033800

The existing BI pipelines rely on a sample ID column. In DCP v1 the [pipelines tools use](https://github.com/HumanCellAtlas/pipeline-tools/blob/0c27063711d79046329dcb240efa2e41d01fa78e/pipeline_tools/pipelines/smartseq2/smartseq2.py#L32) the metadata-api construct `bundle.sequencing_input[0].document_id` for this.

We need to ensure that we include that value in the `terra.bdbag` format that we hand over to Terra.

**Comment by danielsotirhos** [comment]
Azul doesn't access the metadata-api property `bundle.sequencing_input` directly, but it does walk the graph to find samples (biomaterials at the bottom of the ancestor tree).
The `document_id` value of these entities is available in the `terra.bdbag` format manifest in the `sample__provenance__document_id` column.

Source: https://github.com/DataBiosphere/azul/blob/08ed940851d0fb0d5c9f00a9024e959054257b4c/src/azul/plugins/metadata/hca/__init__.py#L145

Example: https://github.com/DataBiosphere/azul/blob/08ed940851d0fb0d5c9f00a9024e959054257b4c/test/service/test_manifest.py#L318

Screenshot of manifest column:
![Screen Shot 2020-05-18 at 9 52 27 AM](https://user-images.githubusercontent.com/46407464/82240088-ae2c5200-98ee-11ea-84d5-8d2cfce4de72.png)

**Comment by kbergin** [comment]
It seems like whatever is in that sample__biomaterial column that got cutoff in the above screenshot is more of what we're looking for? cc @jessicaway

**Comment by hannes-ucsc** [comment]
I agree with @danielsotirhos, `sample__provenance__document_id` is the closest approximation of what the pipelines tools used for v1 (bundle.sequencing_input[0].document_id). I think you should use that. The `sample_biomaterial_id` column is only guaranteed to be unique within a project.

The value from `sample_biomaterial_id` in the TSV is also displayed in the data browser as the first column in the [Samples tab](https://data.humancellatlas.org/explore/samples?filter=%5B%7B%22facetName%22%3A%22genusSpecies%22%2C%22terms%22%3A%5B%22Homo+sapiens%22%5D%7D%5D). Tragically, that column is called "Sample ID" but it is not a globally unique ID. If you want to retain a "meaningful" value provided by the submitter of the data AND have global uniqueness, you could concatenate the two columns.

**Comment by hannes-ucsc** [comment]
While there is an ongoing discussion about whether we should continue with the sample ID used by the v1 pipeline-tools (`bundle.sequencing_input[0].document_id`), we've shown here that `sample_biomaterial_id` it is close enough to the v1 sample ID and that by using it we can retain the existing v1 semantics. Closing.
