### ISSUE TITLE
Automate GitHub/ZenHub API script for velocity

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1807]
Measure the number of issues that go into ‘dev’ weekly/bi-weekly by tracking the following metrics:

- [ ] story points per week
- [ ] number of review cycles per PR
- [ ] normalized number of review cycles per PR based on number of lines in PR
- [ ] amount of time spent reviewing per week/per person
- [ ] same number normalized lines per PR
- [ ] ~per team~

**Comment by natanlao** [comment]
@hannes-ucsc @melainalegaspi What does "per team" mean in this context? I've interpreted this to mean "per ZenHub workspace" -- based on my notes, I neglected to ask this when we last discussed this.

**Comment by natanlao** [comment]
@hannes-ucsc has instructed me to drop the "per team" requirement. @achave11 pointed out that this functionality could be implemented within a single workspace using the GitHub organization teams feature (e.g. https://github.com/orgs/DataBiosphere/teams).
