### ISSUE TITLE
Migrate manifest entry properties

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1809]
https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.eeyjdjt197l9

These are the properties metadata-api extracts

https://github.com/DataBiosphere/hca-metadata-api/blob/8635a91df1b138f3bbd9a6a8a6f17e711b0c1074/src/humancellatlas/data/metadata/api.py#L586

Of those, these are what Azul indexes:

https://github.com/DataBiosphere/azul/blob/08ed940851d0fb0d5c9f00a9024e959054257b4c/src/azul/plugins/metadata/hca/transformers.py#L383

**Comment by danielsotirhos** [comment]
Making this ticket a freebie of #1834
