### ISSUE TITLE
Rewrite links.json to comply with updated schema

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1814]
https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg/edit#heading=h.6h4eqvm2zreu

https://github.com/HumanCellAtlas/metadata-schema/pull/1279/files

Don't forget to update the schema URL in `describedBy`. I think it will be

https://schema.humancellatlas.org/system/2.0.0/links

It's not yet published but planned for Thu.

**Comment by hannes-ucsc** [comment]
The most difficult aspect of this will be determining the concrete type of the referenced inputs, outputs and process.

**Comment by danielsotirhos** [comment]
Making this ticket a freebie of #1834
