### ISSUE TITLE
Change internal repository naming conventions

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#1820]
Follow up to #1724 

There are functions / classes / test case classes that need to have their `repository` reference renamed to `index`.

> There are a few
functions (repository_search, validate_repository_search) classes (RepositoryService) and test case classes (RepositorySpecimenEndpointTest, DataRepositoryServiceEndpointTest, RepositoryProjectsEndpointTest) whose reference to 'repository' might now be outdated.

see review comments on #1790 for more information.

**Comment by hannes-ucsc** [comment]
This was fixed when I refactored/plugin-ifed the service.
