### ISSUE TITLE
Add more "Diff" columns to AWS daily report

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1822]
Add a daily cost difference column for the following tables:
  - "Totals by account"
  - "EC2 Breakdown by Owner"

**Comment by natanlao** [comment]
After discussing with @theathorn and @hannes-ucsc, this ticket is rescoped to only add a diff for totals by account. The current database schema stores EC2 costs only in aggregate; a schema change would be required to implement diffs by owner.

**Comment by theathorn** [comment]
Diff update to "Totals by account" is not in today's email.

**Comment by natanlao** [comment]
@theathorn Miscommunication on my part -- I misunderstood your approval of the changes. I am pushing the update to Erich now.

**Comment by theathorn** [comment]
Today's email looks good - closing.

**Comment by hannes-ucsc** [comment]
Should we give Natan a chance to demo this quickly?
