### ISSUE TITLE
Inventory projects hosted by HCA/DCP allspark GitLab instances

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1830]
@xbrianh : "I’ve requested a license renewal from GitLab, which is free for open source projects. I’ll report back when they respond."

@hannes-ucsc : "Someone should do an inventory of all the projects currently hosted on those instances and reach out to their respective owners, asking if they intend to continue to use them."

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Please list the projects hosted on allspark and along with the emails of the associated project owners."

**Comment by amarjandu** [comment]
ingest team uses allspark for end-to-end testing, although this might change with with dcp-2.
ingest team does NOT use all spark for deployments

**Comment by amarjandu** [comment]
Email sent out after approval from @theathorn, emails omitted here to reduce spam. 

```
Hello,
You are being contacted because you own a respository that uses the CI/CD system(s) [allspark-dev](https://allspark.dev.data.humancellatlas.org/)
[allspark-prod](allspark-prod.data.humancellatlas.org/). If you need to continue to use the service please reply to this email. 
Regards,

```

**Comment by amarjandu** [comment]
So far the only response has been from the pipe-lines team who use the deploy functionality to update TLS certificates.

**Comment by theathorn** [comment]
From Rhian Anthony: "I reached out to the PMs here at the Broad and we do not believe that we need GitLab any longer for our deployments."

**Comment by melainalegaspi** [comment]
No further responses received, closing. See #1970 for more info
