### ISSUE TITLE
Missing pagination response header

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#1836]
It appears that the [Link header](https://tools.ietf.org/html/rfc5988) is missing from the response from the [files](https://service.dev.singlecell.gi.ucsc.edu/index/files) endpoint.
```
X-Firefox-Spdy: h2
access-control-allow-headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
access-control-allow-origin: *
content-length: 51637
content-type: application/json
date: Wed, 27 May 2020 17:03:59 GMT
via: 1.1 32814ee4b53f3642b74e20a0ba5944f7.cloudfront.net (CloudFront)
x-amz-apigw-id: NM2LqH9doAMF7Tw=
x-amz-cf-id: CKaBvCrqoRz1EumLWCwWCoWjDw1N9LJl9TcgjDWdy1AcAJ1g2RI41A==
x-amz-cf-pop: SFO5-C1
x-amzn-requestid: 579ba59a-93dc-4372-bd1d-d7ec1530efbb
x-amzn-trace-id: Root=1-5ece9d7d-eb79d9d8fb153204d52e923c;Sampled=0
x-cache: Miss from cloudfront

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Host: service.dev.singlecell.gi.ucsc.edu
TE: Trailers
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:76.0) Gecko/20100101 Firefox/76.0
```

There is no mention of `links` or `pagination` headers on the openapi spec page.
Including the `Links` header as well as headers such headers such as  `X-OpenAPI-Pagination` , `X-OpenAPI-Paginated-Content-Key`). The later being used within the `dcp-cli` client. 

Additionally the service api currently returns a `200` response rather than a `206` if additional pages are available for a client.

**Comment by hannes-ucsc** [comment]
We don't use pagination headers.
