### ISSUE TITLE
Azul IT should use dedicated indexes and delete them on exit/cleanup

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1840]
Azul Integration Test should have its isolated indexes in the share ES deployment. This should allow for cleanup on a failure to simply delete the indices.

**Comment by melainalegaspi** [comment]
Solved by #1929

**Comment by hannes-ucsc** [comment]
Demo by showing a Gitlab build and the index contents of the `it1` and `it2` catalogs.
