### ISSUE TITLE
Add sequencing process ID to `terra.bdbag` manifests

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1853]
Follow-up on #1805. As agreed in meeting with @kbergin, @ruchim and @jessicaway, the ID of the sequencing process is a better primary key for workflows than `bundle.sequencing_input[0].document_id` (metadata) or the equivalent `sample.document_id` (Azul index) because the latter would be duplicated if the same sample is sequenced twice.

During graph traversal in the indexer, record the `document_id` of every process associated with a `sequencing_protocol` and track that in the index as `content.sequencing_process.document_id`. Use a set accumulator with a size limit of 10 for that field. For now, don't expose that field in `/repository` (or `/index`). Only include the field in the `terra.bdbag` manifest as a new column called `sequencing_process.provenance.document_id`.

**Comment by hannes-ucsc** [comment]
Implement first as a PR against `hca/develop` and once merged, forward-port to `develop`.

**Comment by jessicaway** [comment]
wondering if there is a status update on this, would love to get this change merged! Thanks!

**Comment by hannes-ucsc** [comment]
It's been merged and can be observed on https://dev.data.humancellatlas.org/explore/, @jessicaway, but we need to promote it to `prod`.

The final column name is `sample__provenance__document_id` (we have to use double underscore because period isn't allowed by Terrra).

**Comment by jessicaway** [comment]
Thanks for the update and all the work on this!

**Comment by melainalegaspi** [comment]
Request @hannes-ucsc to reindex

**Comment by hannes-ucsc** [comment]
@jessicaway, @kbergin I made two edits, one to my [comment](https://github.com/DataBiosphere/azul/issues/1853#issuecomment-644922179) and one to the ticket description, fixing two mistakes I made.
