### ISSUE TITLE
Rewrite `analysis_process.reference_bundle` to `analysis_process.reference_file`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1854]
In the effort of switching from `analysis_process.input_bundles` to `.input_files` the MD team also switched `analysis_process.reference_bundle` to `analysis_process.reference_file`. While I have additional concerns about certain aspects of that switch, I want it to be on our radar.

https://github.com/HumanCellAtlas/metadata-schema/pull/1286/files

I don't think the `reference_bundle` property is currently used by any secondary bundles.

Step one is to confirm that 1) the property is optional and 2) that it's not currently used.

Then we'll just add an assertion about it's absence into the adapter code.

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "Amar to kick-off reindex in DSS-prod first. Then assign to @danielsotirhos ."

**Comment by amarjandu** [comment]
dss-prod-aws reindex complete.

**Comment by hannes-ucsc** [comment]
@danielsotirhos, you can now start looking for bundles with that property.

**Comment by hannes-ucsc** [comment]
Bumped estimate to account for the reindexing work.

**Comment by danielsotirhos** [comment]
`reference_bundle` is a required field according to metadata-schema https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/process/analysis/analysis_process.json

Checking bundles in DSS prod, it appears all `analysis_process_0.json` files contain the field `reference_bundle` with a value set to either `00000000-0000-0000-0000-000000000000` or `bf51d668-3e14-4843-9bc7-5d676fdf0e01`.

In the attached results, if a bundle had an `analysis_process_0.json` without a `reference_bundle` field it would be listed as "RefBundle:field-not-found". (Note: The script generating these results died after bundle "335..." due to a dropped internet connection)
[analysis_process_reference_bundle.txt](https://github.com/DataBiosphere/azul/files/4725406/analysis_process_reference_bundle.txt)

Results file excerpt: 
```
Bundle:00039bc5-86fc-4654-8ace-92eb6215155c_2019-05-15T220819.201000Z, FileUUID:ead89eb3-6bbd-47a5-bb93-b2325ddc961f, RefBundle:bf51d668-3e14-4843-9bc7-5d676fdf0e01
Bundle:00103dd7-dd95-4ac0-9d24-29bb493a5179_2019-10-09T182326.615292Z, FileUUID:3ce6d4d3-495c-4b0b-9317-3fb8b170cf49, RefBundle:00000000-0000-0000-0000-000000000000
Bundle:0016d876-3768-4c76-8957-8804bb7208e8_2019-11-06T183700.836653Z, FileUUID:70201a6c-362c-4797-a45f-8f88cc6aef11, RefBundle:00000000-0000-0000-0000-000000000000
Bundle:001df33d-3ac3-4e85-b145-512c85f525f4_2019-05-14T122401.090000Z, FileUUID:b007ea58-73ea-4818-a75b-7e04c53dcb83, RefBundle:bf51d668-3e14-4843-9bc7-5d676fdf0e01
...
```

**Comment by danielsotirhos** [comment]
Query to check all if `analysis_process` files have a `reference_bundle` field:

```
GET _search
{
    "query": {
        "bool": {
            "must": { "exists": { "field": "files.analysis_process_json" } },
            "must_not": { "exists": { "field": "files.analysis_process_json.reference_bundle" } }
        }
    }
} 
```

Results show no `analysis_process` files without a `reference_bundle` field:

```
{
  "took": 18,
  "timed_out": false,
  "num_reduce_phases": 2,
  "_shards": {
    "total": 896,
    "successful": 896,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

Query to show all unique values from `reference_bundle` field:

```
GET _search
{
    "query": {
        "exists": {"field": "files.analysis_process_json.reference_bundle"}
    },
    "aggs" : {
        "uniq_values" : {"terms" : {"field" : "files.analysis_process_json.reference_bundle", "size" : 100000}}
    },
    "size": 0
}
```

Results show only two unique values:

```
{
  "took": 46,
  "timed_out": false,
  "num_reduce_phases": 2,
  "_shards": {
    "total": 896,
    "successful": 896,
    "failed": 0
  },
  "hits": {
    "total": 28994,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "uniq_values": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "bf51d668-3e14-4843-9bc7-5d676fdf0e01",
          "doc_count": 23748
        },
        {
          "key": "00000000-0000-0000-0000-000000000000",
          "doc_count": 5246
        }
      ]
    }
  }
}
```

**Comment by danielsotirhos** [comment]
> Step one is to confirm that 1) the property is optional

`reference_bundle` is not optional.  https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/type/process/analysis/analysis_process.json

> and 2) that it's not currently used.

Field `reference_bundle` is being used however it was never implemented with real values. https://humancellatlas.slack.com/archives/C6C5S6B5W/p1590750410042000

**Comment by hannes-ucsc** [comment]
Ok, since the values are bogus, we don't need to worry about rewriting them. Closing but see https://github.com/DataBiosphere/hca-metadata-api/issues/17 post-MVP.
