### ISSUE TITLE
Estimate monthly cloud costs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1858]
For HCA we need to provide an estimate of ongoing cloud costs (AWS & GCP) for both the dev and prod instances
  - how do costs scale according to dataset size?
  - what is the re-index cost by dataset size?
  - what is the prod cost (without re-index) and how does it scale with number of users?

For LungMAP we need to provide a similar estimate for operation a LungMAP-specific prod instance.
@theathorn will contact LungMap for an estimate of number of sequence files, number of cells, etc.

**Comment by theathorn** [comment]
From LungMAP: "For the cloud compute/storage for the data browser/single-cell portal, can HCA costs be downsampled to the scope of LungMAP (AWS) as a very rough estimate? Again, should be on the scale of 30-70 samples per year over 5 years, probably for a dozen studies or so."

**Comment by theathorn** [comment]
From Nathan Salomonis, CCHMC/LungMAP: "My guess is up-to a dozen single cell datasets/year in years 2-5. For each dataset I would estimate 8 samples, with a total of 45,000 cells/dataset. In terms of visitors, I would base this off of the HCA/dataset."

**Comment by hannes-ucsc** [comment]
| Component | Resource type            | Monthly Cost [$] | Remarks                                                   |
|-----------|--------------------------|-----------------:|-----------------------------------------------------------|
| ES        | Instances                | **1168**             | per metadata volume unit                                  |
|           | Storage                  | **9**                | per metadata volume unit                                  |
| Lambda    | Invocations (other)      | **279**              | constant                                                  |
|           | Invocations (reindexing) | **33**               | per reindexing operation and metadata volume unit squared |
| Gitlab    | EC2 instances            | 112              |                                                           |
|           | Load balancers           | 34               |                                                           |
|           | NAT Gateway              | 69               |                                                           |
|           | EBS Volumes              | 10               |                                                           |
|           | Total for Gitlab         | **225**              | constant                                                  |
|           | Gitlab EBS Snapshots            | **5**                | per snapshot, one additional snapshot every month         

The metadata volume unit is defined as all metadata stored in HCA production instance of the DSS as of today.

The monthly cost of one metadata volume unit (w/o Gitlab) with 5 reindexing operations during that month would be $1621 (`1168+9+279+5*33`). For two units that would rise to $3293 (`2*1168+2*9+279+4*5*33`). Please note the quadratic relationship between reindexing cost and volume and linear relationship between reindexing cost and the frequency with which we reindex.

We need to further investigate the cost impact of the number of visitors to the Data Browser. The cost of the current visitor load on the site is included in the constant portion of the Lambda cost in the table above.

A big question mark to this is how we implement controlled access data. If we do it via snapshots, a snapshot would equal one metadata volume unit.

**Comment by theathorn** [comment]
@hannes-ucsc Are these costs per environment (e.g dev vs prod)? Or is GitLab shared between envs?

**Comment by theathorn** [comment]
Create a spreadsheet with formulas.

**Comment by hannes-ucsc** [comment]
Gitlab can be shared between lower environments, like `dev` and `staging` but `prod` needs its own Gitlab instance.

**Comment by hannes-ucsc** [comment]
With the improvements from #1732, the cost of reindexing dropped from $33 to $14 for each reindexing. Overall a reindexing now takes 40% longer (6.75h as opposed to 4.5h) and so there is more tweaking to do. I think it can be made cheaper than $33 AND faster than 4.5h. IOW, while we optimize the trade-off between cost and performance, this is still in flux and I would not want to reduce my estimate above for the time being.

**Comment by theathorn** [comment]
[Cost calculator](https://docs.google.com/spreadsheets/d/1Au-_jd0GDWdb8iLaQk2tZh25L24n0AlvpI3IPKy5jyk).

**Comment by hannes-ucsc** [comment]
I made a few changes to the sheet. I think we should account for two lower envs: `dev` and `staging`.
