### ISSUE TITLE
Delete `platform-sc` Google Cloud project

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1860]
The name of the project is currently `platform-sc` but the ID is `platform-hca`. There are some resources in it and we should contact the people who have access to that project and ask them to evict the project, either delete their resources or migrate them to the right project.

Give people one week to do so. Then remove their access, wait another week and delete the project.

**Comment by amarjandu** [comment]
email sent to people with a service account on `platform-sc` 

```
Howdy,

You are being contacted because you have an IAM account within the `platform-sc` (also known as `platform-hca`) google project. 
Please migrate or delete resources that you are using within this google-project by 06.12.2020.
Your access to the project shall be removed on 06.12.2020 at 4pm pst.
This project shall be marked for terminated on 06.18.2020.

If you have questions feel free to contact me.

Regards,
Amar
``

**Comment by amarjandu** [comment]
Access to account has been limited by removing IAM & accounts from the project.

**Comment by amarjandu** [comment]
>> what resources are allowed to be present when trying to delete the project?

@hannes-ucsc : "just try to delete the project and see what happens"

**Comment by amarjandu** [comment]
Project "platform-sc" is now shut down and scheduled to be deleted after 7/19/20.

**Comment by melainalegaspi** [comment]
Will re-demo in 30 days due to Google Cloud projec's deletion policy
