### ISSUE TITLE
Delete platform-sc DSS instance 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1869]

**Comment by amarjandu** [comment]
infra from `$DSS_HOME/infra` destruction complete.

**Comment by amarjandu** [comment]
deleted SNS, StepFunctions, SQS resources in AWS

**Comment by amarjandu** [comment]
deleted api-gateway, route53 zones

**Comment by amarjandu** [comment]
deleted parameter store

**Comment by amarjandu** [comment]
backup terraform state files, double check IAM and lambda layers.
