### ISSUE TITLE
CLI questions

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1879]
How does the upload service login within the CLI?

What services are available in the CLI?

**Comment by amarjandu** [comment]
> `What services are available in the CLI? `

DSS, Fusillade, Upload Service

**Comment by amarjandu** [comment]
> `How does the upload service login within the CLI?`

https://github.com/HumanCellAtlas/upload-service/blob/b7c470706f729bdee34a4254555f798558877095/upload/common/upload_area.py#L85

The upload service performs an `sts.assume_role` then returns the temp credentials obtained, the IAM policy used restricts the bucket access to the `uuid` prefix that was provided in the request. 

https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html

There is also https://github.com/HumanCellAtlas/upload-service/blob/db82bf55de6053b4e2c5bbf0d4b15e60cdfb5f01/upload/lambdas/api_server/__init__.py#L54

Which indicates that there is a key that is stored within AWS Secrets Manager which is matched against the request.header.Api-Key, this appears to be how the service was restricted to the `ingest team`, and allows CRUD of the `uuid` mentioned above.

**Comment by amarjandu** [comment]
Double check that the cli does not expose service operations that require authentication via the secret-token `Api-Key`

**Comment by amarjandu** [comment]
None of the CLI operations make use of the `Api-Key` authentication mechanism. None of the commands use the locked `ingest only` endpoints as seen on https://upload.data.humancellatlas.org/

**Comment by hannes-ucsc** [comment]
Questions answered satisfactorily. Closing. No demo.
