### ISSUE TITLE
Fix tests in feature/commons branch of azul/webservices

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#189]
Currently 7 of the 24 tests in `azul/webservices` fail.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-140)
┆Project Name: azul
┆Issue Number: AZUL-140

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
