### ISSUE TITLE
Add exception handling to tally aggregation

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#1890]
If there is an AssertionError that occurs if when the index_service attempts to aggregate tallies; the values of the tallies that were being used are not available for inspection.

Related to #1845

**Comment by hannes-ucsc** [comment]
> were being used are not available for inspection

Not easily available. It is possible to correlate the log message that announces work on the tally with the message containing exception trace when looking a a single log stream but that would have to be done individually for every exception.

**Comment by amarjandu** [comment]
@hannes-ucsc: "Hannes to reindex dev, Amar need to check if exception is raised."
