### ISSUE TITLE
Check DSS file version is not used by indexer

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1892]

**Comment by noah-aviel-dove** [comment]
I could not find any references to file version in the indexer itself, but there are several  in the HCA metadata plugin. I'm a bit unclear on the intended meaning behind "used" in the ticket title. File version info is definitely included in the index but that seems obvious.

**Comment by hannes-ucsc** [comment]
The `version` field from the DSS manifest entry for a data file is used in the following places:

- the HCA plugin places it into `contents.files.version` of contributions
- the HCA plugin uses it together with a file's UUID during aggregation to ensure that each inner file is only counted once
- it's included in the full metadata entries of the `bundles` index
- DRS/DOS and the DSS file proxy uses it together with a file's UUID to request files from DSS
- the manifest service uses it together with a file's UUID to place file references and compose in the compact and bdbag manifests
- the repository service uses it to generate URLs that point at the DSS file proxy

Whenever there is a collision between two JSON documents for the same entity, the indexer uses the version of the bundle from which either object originated, and not the version of the metadata file containing the document, or for data files, the version of the data file.

`Document` instances use a separate integral version. For instances of the `Contribution` class, one of two subclasses of `Document`, the document ID in ES is the tuple `(entity_id, bundle_uuid, bundle_version, "deleted"|"deleted")`. For instances of Aggregate, the other subclass of `Document`, the document ID in ES is just the `entity_id`.

**Comment by hannes-ucsc** [comment]
To close at stand-up.
