### ISSUE TITLE
Modify Gitlab permissions to accommodate data-portal and data-browser deployment

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1893]

**Comment by hannes-ucsc** [comment]
This has been merged and deployed. If the [requested](https://github.com/humancellatlas/data-portal/issues/698#issuecomment-639660129) permissions are correct and sufficient, the DB and DP builds should now pass.

**Comment by theathorn** [comment]
@hannes-ucsc : "Initial policy incorrect - waiting for updated policy from @NoopDog".

**Comment by hannes-ucsc** [comment]
Updated policy here:

https://github.com/HumanCellAtlas/data-portal/issues/698#issuecomment-648579207
