### ISSUE TITLE
Backport: DRS endpoint should include ability to return a gs:// URL

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1903]
We need the hand-off to Terra in DCP/1 to work with DRS 1.0 as DOS is being deprecated.

**Comment by theathorn** [comment]
It's not clear when DOS will be deprecated in Terra, so back-porting this change to DCP/1 (which will be retired in a few months) may not be necessary.

**Comment by hannes-ucsc** [comment]
DCP/1 is EOL.
