### ISSUE TITLE
Rename `project_shortname` to `project_short_name`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#191]
Low priority. The metadata group renamed that field, `metadata-api` supports both names. We may want to be consistent.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-141)
┆Project Name: azul
┆Issue Number: AZUL-141

**Comment by GPelayo** [comment]
Will require a reindexing after merging.

**Comment by NoopDog** [comment]
@GPelayo can you provide before and after example of the how this modifies the API.
