### ISSUE TITLE
Delete old CloudWatch log groups

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1917]
After the lambda names changed, the old log group names stuck and are polluting the CloudWatc insights UI.

**Comment by amarjandu** [comment]
Removed `/aws/lambda/azul-*-geryl-*` cloudwatch log groups

**Comment by amarjandu** [comment]
Need to remove: 
- [ ] Nudge 
- [ ] Write

**Comment by amarjandu** [comment]
@hannes-ucsc 
i attempted to: 
1. Destroy infra for my local deployment
2. create a throw away branch off develop (waiting for #1918 to land)
3. deploy

It appears that the cloudwatch logs are not created at deploy time.

![Screen Shot 2020-06-29 at 1.02.46 PM.png](https://images.zenhubusercontent.com/5bfc94ffa6759a229d994558/3d756550-9cc6-4566-8ab6-0c6f972d6d47)

I was looking within the terraform files for explicit creations of cloudwatch logs, it does not appear that we manage them as we do other infra.

**Comment by amarjandu** [comment]
When deploying off develop, the lambda's deployed are:

```
azul-indexer-amar
azul-indexer-amar-aggregate
azul-indexer-amar-aggregate_retry
azul-indexer-amar-contribute
azul-indexer-amar-indexercachehealth
azul-service-amar
azul-service-amar-cartexportpush
azul-service-amar-cartitemwrite
azul-service-amar-jwt_auth
azul-service-amar-manifest
azul-service-amar-servicecachehealth
```
Removing any other `aws/lambda/` cloudwatch groups for deployments.

**Comment by amarjandu** [comment]
Cleaned Deployments:
```
abrahamsc
amar
daniel
hannes
jesse0,jesse1
nadove,
dev
sandbox
natan
```

**Comment by hannes-ucsc** [comment]
Skipping review. Demo as usual.
