### ISSUE TITLE
Sketches for compliance: system overview and data flow diagrams

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1937]
In order to do a compliance risk assessment, we need diagrams of the overall system architecture and data flow for the Data Portal & Browser (including Azul).

The first step is to produce sketches that can be used as the basis for input to a drawing tool.

**Comment by hannes-ucsc** [comment]
Two in one: https://drive.google.com/file/d/1slLhCoXSNjd3vYME02olShbLbwyaCk2o/view?usp=sharing

**Comment by hannes-ucsc** [comment]
@theathorn, could you review and decide next steps?

**Comment by nolunwa** [comment]
@melainalegaspi can you please create another ticket and link to this. All diagram need to be accomplished by a narrative / brief description. Refer to the shared drive for sample

**Comment by theathorn** [comment]
Sketches are complete and diagrams are now in Lucidchart - closing.
