### ISSUE TITLE
ISO 27001 Compliance

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1938]
Compliance with ISO standards:
  - [ISO 27000](https://webstore.ansi.org/Standards/ISO/ISOIEC270002018) Information security management systems overview and vocabulary
  - [ISO 27001](https://webstore.ansi.org/Standards/ISO/ISOIEC270012013) Information security management systems requirements
  - [ISO 27002](https://webstore.ansi.org/Standards/ISO/ISOIEC270022013) Guidance on applying ISO/IEC 270001 controls
  - [ISO 27005](https://webstore.ansi.org/Standards/ISO/ISOIEC270052018) Conducting an information security risk assessment
  - [ISO 27017](https://webstore.ansi.org/Standards/ISO/ISOIEC270172015) Cloud services information security controls
  - [ISO 27018](https://webstore.ansi.org/Standards/ISO/ISOIEC270182019) Data Privacy
  - [ISO 27032](https://webstore.ansi.org/Standards/ISO/ISOIEC270322012) Cybersecurity best practices

[Compliance Project Plan](https://docs.google.com/spreadsheets/d/1zKEAnRa2fMoB8HFYfdST4QXwOmaIbTCUQVVYn6p5yBQ)

[Compliance documentation directory](https://drive.google.com/drive/folders/1UzbReOncBEdifYluVcgc1wd7k9ikgjpE)

**Comment by nolunwa** [comment]
HCA ISO/IEC 27001 compliance project plan https://docs.google.com/spreadsheets/d/1zKEAnRa2fMoB8HFYfdST4QXwOmaIbTCUQVVYn6p5yBQ/edit#gid=0

**Comment by nolunwa** [comment]
@melainalegaspi can you link a ticket here to study all the standard mentioned above. Thanks

**Comment by theathorn** [comment]
Switching to FedRAMP (#2480) - closing.
