### ISSUE TITLE
Add narratives/brief descriptions to compliance diagrams 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1941]
Compliance diagram https://drive.google.com/file/d/1slLhCoXSNjd3vYME02olShbLbwyaCk2o/view?usp=sharing needs narratives/brief descriptions for task to be considered complete. 

Related to #1937

Add to [Scope and Boundaries](https://docs.google.com/document/d/1wzZ3qoNirDE1Z0fWsbe6nI6XgKp3SBDL8DZYG5xX7RE)

**Comment by jessebrennan** [comment]
@hannes-ucsc I've added some details here, explaining most of the interactions within the system. Questions I have and things still to do I highlighted in yellow. Please let me know what you think! (The link to the document is in the issue description).

**Comment by hannes-ucsc** [comment]
Answered the questions in the document.

**Comment by hannes-ucsc** [comment]
I don't think this is relevant anymore.
