### ISSUE TITLE
Complete compliance diagrams from sketch 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1943]
Add to [Scope and Boundaries](https://docs.google.com/document/d/1wzZ3qoNirDE1Z0fWsbe6nI6XgKp3SBDL8DZYG5xX7RE)

**Comment by theathorn** [comment]
[Lucidchart diagrams](https://app.lucidchart.com/invitations/accept/712461bf-a5eb-4b3a-a76d-d63fbd13e852).

Page 1: Build/Deployment Process
Page 2: System Architecture/Data Flow

@hannes-ucsc @nolunwa We should discuss if this is the correct approach or if we need separate diagrams for system architecture and data flow. I copied most of Hannes info from his sketch, but I found having many arrows double ended in green/black with accompanying text was confusing.

**Comment by nolunwa** [comment]
@theathorn @hannes-ucsc am sorry if I was misunderstood but the initial request was to have separate diagrams and all Diagram must come with narrative/description. The idea is that your collaborators, auditor, compliance and security personal can view and understand the system architecture. @theathorn its best we separate the diagrams which are the system architecture diagram and data flow diagram. The system diagram should portrays the Authorization Boundary (scope of the system) and all its connections ( front end and back end) and components( aws services S3, EC2 etc), including the means for monitoring ( IDPS , WAF) and controlling communications( SAML, OAUTH, Open ID connect) at the external boundary (interconnect with Terra and EBI) and even if at this point the team has not decided its best to have it in the diagram and label TBD.

**Comment by nolunwa** [comment]
@theathorn @hannes-ucsc the Data flow diagram describe protections implemented at all entry and exit points in the data flow as well as internal controls between customer and project users. Include data flows for privileged and non-privileged authentication/authorization to the system for internal and external users. The diagram should describe data flow in and out of system dependence ( other third party application outside of AWS ) like github, gitlab, slack etc

**Comment by nolunwa** [comment]
Also i list of Inventory that highlight all the asset of the system.

i should also add we will need other diagram such as system environment describing the different instances/environment ( development, staging, production and maintenance ) and how they interconnect but this can be done later

**Comment by theathorn** [comment]
Recombine Data Flow and System Architecture diagrams into a single Data Flow diagram.
  - empty arrowhead points to a client that reads
  - no arrowhead = client that writes
  - filled arrowhead = server that reads

Double check arrows with Hannes original sketch.

Rename Instances diagram to System Architecture and add AWS and Google region info and all metadata/data assets.

Describe every box and every arrow.

**Comment by jessebrennan** [comment]
Given yesterday's Slack conversation, it seems that for now, we only need a single diagram of the system architecture. This is the "recombined" diagram mentioned in @theathorn's comment above.

I've updated the arrows in this diagram. It's available here: https://app.lucidchart.com/documents/edit/5a362477-88dc-418d-9fd5-ce2f7612a0c7/IYifRq-_eVYE

**Comment by jessebrennan** [comment]
@danielsotirhos can you review the document and verify that the arrows match your understanding and Hannes's original drawing? The original drawing is here https://drive.google.com/file/d/1slLhCoXSNjd3vYME02olShbLbwyaCk2o/view

**Comment by danielsotirhos** [comment]
Overall the 'System Architecture' chart looks great. Here are some questions I had while doing my review:

- The legend on the chart differs from Trevor's [comment](https://github.com/DataBiosphere/azul/issues/1943#issuecomment-658911297). Is the chart's legend or the comment the desired arrowhead description?
- The Data Browser has an empty arrowhead signifying it writes, but to what? The API Gateway?
- Could we add the box colors to the legend (blue = google cloud, yellow = public internet)?
- What does the label `on Terra's side. We currently whitelist the` mean and/or relate to?
- (nitpick) The `API Gateway` is connected directly to `User's Machine`, shouldn't the `Internet` be in the middle of that?

**Comment by jessebrennan** [comment]
@danielsotirhos, thanks for the thorough review!

> The legend on the chart differs from Trevor's comment. Is the chart's legend or the comment the desired arrowhead description?

:facepalm: nice catch! The original was correct

>The Data Browser has an empty arrowhead signifying it writes, but to what? The API Gateway?

This was a mistake, it's fixed.

> Could we add the box colors to the legend (blue = google cloud, yellow = public internet)?

Done.

> What does the label on Terra's side. We currently whitelist the mean and/or relate to?

I'm not sure what label you're talking about...

> (nitpick) The API Gateway is connected directly to User's Machine, shouldn't the Internet be in the middle of that?

Good catch.

For your next review, try using the LucidChart comment feature. Thanks again.

**Comment by danielsotirhos** [comment]
> I'm not sure what label you're talking about...

Odd, it was a label near the `S3 URL Shortener Bucket` however it's no longer present.

> For your next review, try using the LucidChart comment feature.

Unfortunately I couldn't find anything else to comment on.

Approved.

**Comment by jessebrennan** [comment]
@theathorn @hannes-ucsc, Daniel has viewed and approved my updates to the diagram. I'm not sure what the next step is for this, but I've assigned Hannes and moved it into review.

**Comment by hannes-ucsc** [comment]
LGTM

**Comment by hannes-ucsc** [comment]
I don't think this is relevant any more.
