### ISSUE TITLE
List of all metadata fields referenced by the indexer and web service

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#1952]
For managed access datasets, some metadata fields may be "public access" while others are "restricted access".
We may provide to contributors and DACs a list of the metadata fields we wish to make "public access".
Potentially the contributor/DAC (Data Access Committee) may "opt out" of some of these fields or require the value to be made "fuzzy" (e.g. "age range" vs "specific age").

This ticket requests a [spreadsheet](https://docs.google.com/spreadsheets/d/1samS9VdtxtnXt398nW9N3JXkAdajK14shvdvuyg9lk4) (Google Sheets) listing all metadata fields referenced by the Azul indexer and web service. The JSON metadata field name, a brief human-friendly description, and an example value should be sufficient.

See [notes](https://docs.google.com/document/d/17S4Y6G7YhgN0Sf2oas-q79GYKvFI3jPaeFsb6eyLeCU) from 7/1/20 meeting with HCA Ethics Working Group.

**Comment by danielsotirhos** [comment]
[Azul metadata fields](https://docs.google.com/spreadsheets/d/1iun8e3aKDz-gJHvVEuuKmxOHEx9nH5TgaRKda_dGKt0/edit?usp=sharing)

**Comment by danielsotirhos** [comment]
Assigned ticket to @achave11 for review (no PR, see https://github.com/databiosphere/azul/issues/1952#issuecomment-659065789 for link to Google Sheet)

**Comment by achave11** [comment]
Looks good, great job! +1 on the estimate.

**Comment by danielsotirhos** [comment]
Assigned to @theathorn for review.

**Comment by theathorn** [comment]
Looks good.

**Comment by danielsotirhos** [comment]
Putting ticket in triage to determine if listing response fields instead of metadata fields is sufficient.

**Comment by danielsotirhos** [comment]
Added a "HCA Metadata Schema Field" column.
Assigning ticket to Trevor for review.

**Comment by theathorn** [comment]
Looks good - closing.

**Comment by hannes-ucsc** [comment]
Re-opening so I can add as blocker.
