### ISSUE TITLE
Turn off HCA Allspark 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1970]
- [x] Disable `dev` for a week
- [x] Destroy `dev`
- [x] Disable `prod` for a week
- [x] Destroy `prod`

**Comment by amarjandu** [comment]
updating EKS allspark cluster to check if scaling down the EKS cluster works as an intended "shutdown" like concurrency reduction on lambdas.

**Comment by amarjandu** [comment]
updating EKS cluster did not show options to reduce scaling. 
allspark dev disabled

**Comment by amarjandu** [comment]
allspark-prod ec2 instances have been shutdown.

**Comment by amarjandu** [comment]
@hannes-ucsc - "inspect the volumes for the sum being larger than 110GB, if so get back to me, otherwise snapshot the volumes then delete the instances"

**Comment by amarjandu** [comment]
snapshots were verified for `allspark-prod` and `allspark-dev`both have regular snapshot policies active, and have been completed successfully.

**Comment by amarjandu** [comment]
delete snapshots except for the most recent one, migrate the snapshots to `platform-hca-dev` then delete instances

**Comment by amarjandu** [comment]
snapshots shared with `platform-hca-dev` copies made within that account.

**Comment by amarjandu** [comment]
auto-scaling groups deleted, EKS cluster deleted, ec2 instances terminated.
