### ISSUE TITLE
TestHCAIndexer.test_concurrent_specimen_submissions() isn't working under TravisCI

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#198]
TestHCAIndexer.test_concurrent_specimen_submissions() runs fine in other environments, but when running the test in TravisCI, the test throws the following exception.

```
Traceback (most recent call last):
  File "/home/travis/build/DataBiosphere/azul/test/indexer/test_hca_indexer.py", line 193, in test_concurrent_specimen_submissions
    self.assertEqual(3, num_hits)
AssertionError: 3 != 1
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-146)
┆Project Name: azul
┆Issue Number: AZUL-146

**Comment by alex-hancock** [comment]
Thanks to @hannes-ucsc for debugging with me. Very interesting problem:

The patched `extract_bundle` method previously set a static return of the given metadata/manifest pair. In the rest of the functions, this was fine. In the concurrent specimen submission test this patch was declared globally and applied to both threads, causing both files and the specimen documents to produce conflicts. Changing the patched `extract_bundle` to return a dynamic metadata/manifest pair depending on the bundle input (which is guaranteed different for each thread) removes the file conflicts, reducing the number of conflicts to 1.
