### ISSUE TITLE
Promote from hca/dev all the way to hca/prod

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#1986]
- [x] Check if `hca/dev` was reindexed during most recent deployment. If not, reindex `hca/dev`.
- [x] Promote to `hca/integration` and reindex
- [x] Promote to `hca/staging` and reindex
- [x] Smoke test Data Browser instance for `hca/staging`
- [x] Prepare relesae notes; announce on Slack `#dcp-ops` channel
- [x] Check in with @theathorn and @hannes-ucsc 
- [x] Promote to `hca/prod` and reindex
- [x] Smoke test Data Browser instance for `hca/prod`

This to get #1982 out the door.

**Comment by melainalegaspi** [comment]
No failed notifications or tallies in the queues after the most recent reindex in prod.
