### ISSUE TITLE
Inventory of Assets

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#1991]
Suggested template [spreadsheet](https://docs.google.com/spreadsheets/d/1_ZfIz6GcPesynsJvAxu6KRMOw8d4tSphi3fzp3gQWPU).

**Comment by nolunwa** [comment]
Questions from @danielsotirhos On the page "1. Inventory" each row contains columns for "Software", "Hardware", and other categories. Should I try to fill out as much as I can on one row (eg. 1 row would have laptop and software details), or should I use 1 row per item (eg. 1 row for a laptop hardware details, and another row for the software installed on it)?
- Which column (if any) is for the owner/user of an item (eg. a laptop or software)
- My team uses an AWS account and has various services provisioned (EC2 instances, S3 Storage Buckets,  Elasticsearch instances, Lambda functions, DynamoDB tables, Route 53 (DNS) configurations, etc..) Is it required to include all the items in these categories in the inventory or only some categories such as the EC2 instances?
- I don't believe we have any "Service" items to list, could you provide an example so I understand what might go in that category?

**Comment by nolunwa** [comment]
@danielsotirhos to respond to your question and just incase I misunderstood we can have a 30 mins. you should fill out hardware details ( laptop ) and another column software. owner/user name not required. all aws services provisioned (EC2 instances, S3 Storage Buckets, Elasticsearch instances, Lambda functions, DynamoDB tables, Route 53 (DNS) configurations, etc..) Is it required to included.

Service are other third-party solution the team acquires that is not part of AWS for eg clever canary, github, zenhub is a service. Does that make sense

**Comment by danielsotirhos** [comment]
[Inventory of Assets (Azul)](https://docs.google.com/spreadsheets/d/1xYBQdbdELDA8csGOlgc3P3-JUJEB7MF-XWPYoMc-rqg/edit?usp=sharing)

**Comment by theathorn** [comment]
@nolunwa Does the "Inventory" tab seem like the correct level of info required?

**Comment by nolunwa** [comment]
@theathorn @danielsotirhos no information on other third-party solution the team acquires that is not part of AWS for eg clever canary, github, zenhub is a service.

**Comment by theathorn** [comment]
@danielsotirhos Please add a brief description (i.e. "used for") to "Google Cloud service accounts".

@nolunwa Does this look sufficient now?

**Comment by danielsotirhos** [comment]
> @danielsotirhos Please add a brief description (i.e. "used for") to "Google Cloud service accounts".

done.

**Comment by theathorn** [comment]
@hannes-ucsc @danielsotirhos I'm hesitant to include any reference to DSS in our ISO compliance docs as a) we won't be using it at all post MVP and b) it won't ever conform to the compliance requirements.

By the time we achieve compliance the DCP/1 will have been deleted and there will be no DSS instances running.

**Comment by theathorn** [comment]
Remaining:
  - @danielsotirhos to remove references to DSS
  - @NoopDog @MillenniumFalconMechanic to add assets for the Data Browser/Portal

**Comment by danielsotirhos** [comment]
> * @danielsotirhos to remove references to DSS

done.

**Comment by theathorn** [comment]
@NoopDog has updated the spreadsheet for the UI components.

**Comment by hannes-ucsc** [comment]
Looks good to me.

**Comment by theathorn** [comment]
Closing as completed.
