### ISSUE TITLE
`terraform` make target should depend on `package`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#1997]
Otherwise switching deployments could lead to stale `terraform/{indexer,service}/chalice.tf.json` files which can seriously mess up a deployment.

**Comment by jessebrennan** [comment]
Most Terraform commands should be run only after `make package` has been run, but it would be difficult express these dependencies with only `make`. We could perhaps even configure `make package` to be run as a TF local-exec provisioner to ensure that it is always run when needed.

**Comment by achave11** [comment]
Target `terraform` was renamed to `deploy`.

**Comment by achave11** [comment]
Add additional target to `terraform` directory make file that packages the lambdas by running `make -C lambdas/* …` at the lambda make file level. Current terraform `config` targets depends on new target.
