### ISSUE TITLE
Port monkey patch for assume-role creds from chalice 1.1.0 to latest

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#2]
Follow up on #39. We had to downgrade chalice to make the monkey patch work.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-8)
┆Project Name: azul
┆Issue Number: AZUL-8

**Comment by cricketsloan** [comment]
➤ Hannes Schmidt commented:

Actually, the downgrade from 1.3.0 was the fix. IOW, it still needs to be confirmed that the monkey patch does or does not works with 1.2.3 (or whatever the latest version < 1.3 is). And we need to confirm that we still need the monkey patch on 1.2.3. Maybe we don't have the problem anymore.

Also need to figure our what causes the original problem in 1.3.x we thought the monkey patch addressed.

**Comment by hannes-ucsc** [comment]
Upgrading to Chalice 1.6.0 (#179) makes this obsolete.
