### ISSUE TITLE
Add integration test for /dss/files and /fetch/dss/files

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2008]

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"The files proxy will soon be retired, no need to add test coverage."

**Comment by hannes-ucsc** [comment]
The equivalent generic endpoint is covered by IT:

https://github.com/DataBiosphere/azul/blob/70ca8dbb0f617aac69d73bf12933c4b1dbf3e62d/test/integration_test.py#L411
