### ISSUE TITLE
One project failed to be aggregated for 'hca/prod' deployment

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2013]
The following logs …
```logs
[INFO]	2020-07-11T05:58:45.705Z	78135580-57f6-5444-acbe-020300b432f5	Attempt 10 of handling 99460 contribution(s) for entity projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0
[INFO]	2020-07-11T05:58:45.836Z	78135580-57f6-5444-acbe-020300b432f5	Reading 174593 expected contribution(s) using scan().
REPORT RequestId: 78135580-57f6-5444-acbe-020300b432f5	Duration: 300068.02 ms	Billed Duration: 300000 ms	Memory Size: 2048 MB	Max Memory Used: 2048 MB
2020-07-11T06:03:26.447Z 78135580-57f6-5444-acbe-020300b432f5 Task timed out after 300.07 seconds
```

… indicate that project UUID  `e0009214-c0a0-4a7b-96e2-d6a83e966ce0` tallies in `hca/prod` failed to be aggregated in its totality due to a memory exhaustion failure "... Max Memory Used: 2048 MB"

Backporting #1732 into `hca` deployments could be a solution.

**Comment by hannes-ucsc** [comment]
I don't think #1732 is the solution here. It is about optimizing cost and was fairy complex and invasive. IIRC, we had a ticket that just increased lambda memory for the lambda that's timing out in this case and that's what we need to backport. @achave11 can you try to find that ticket?

**Comment by achave11** [comment]
It seems like the lambda memory upgrade was introduced by the work on ticket #1693 PR #1716. #1732 seems to be follow up work to #1693 such that memory is optimally used.
