### ISSUE TITLE
Take control of name services for data.humancellatlas.org

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2014]
CZI does not wish to maintain or directly pay for the account that controls the AWS Route 53 name servers that resolve data.humancellatlas.org.

We need to setup these services and then contact the Sanger to get the "data" sub-domain registration changed.

See also HumanCellAtlas/data-portal#717.

**Comment by theathorn** [comment]
We have control of the Route 53 servers, so this is not a blocker for the DCP/2 MVP.
It's planned that the CZI HCA cloud accounts will be retired at the end of 2020.

**Comment by theathorn** [comment]
The end of 2020 is in sight, so we need to complete this before the end of the year.

**Comment by hannes-ucsc** [comment]
TF config for this hosted here: https://github.com/DataBiosphere/dcp2

For demo, create record in zone, resolve and delete again.
