### ISSUE TITLE
Register indexer SA with Broad's SAM during deployment

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2025]
In order to be allow-listed for access to TDR, an SA needs to be registered with SAM.

This is how we register an account using `gcloud`:

`curl https://sam.dsde-dev.broadinstitute.org/register/user/v1 -d ""  -H "Authorization: Bearer $(gcloud auth --account $service_account_name print-access-token)"`

For the real solution, the access token should not be obtained using gcloud, but programmatically somehow, probably using https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html#google_auth_oauthlib.flow.InstalledAppFlow.fetch_token

We still need to allow-list the account here: https://bvdp-saturn-dev.appspot.com/#groups/JadeStewards-dev but maybe we can automate that as well if we make all developers and Gitlab admin for the JadeStewards-dev group.

**Comment by noah-aviel-dove** [comment]
This is what I was able to work out when we discussed this previously:
```
from google.oauth2.service_account import Credentials
from google.auth.transport.requests import Request

def get_access_token():
    creds = Credentials.from_service_account_file(os.environ['GOOGLE_APPLICATION_CREDENTIALS'])
    creds = creds.with_scopes(['email'])
    creds.refresh(Request())
    return creds.token
```
