### ISSUE TITLE
Estimate storage cost for all DCP/1 data transferred to DCP/2 staging area

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2047]
There's 30TB of data in DCP/1.
The DCP/2 staging area is a Google bucket currently paid for by CZI.
We should know the daily/monthly cost before proceeding.

**Comment by danielsotirhos** [comment]
According to the [Google Cloud Storage pricing tables](https://cloud.google.com/storage/pricing#price-tables) the cost of storing 30 TB (30,720 GB) is $798.72

$0.026 * 30,720 = $798.72 per month for 30TB

https://cloud.google.com/products/calculator/#id=aee9a822-ab40-4352-b868-f7cc82d5fcac

Note that this estimate is for the `US (multi-region)` location. Selecting a single location could offer a small reduction in price.

$0.020 * 30,720 = $614.40 per month for 30TB in us-east1 (South Carolina)

Lastly there are different types of storage offered at different prices, however these might not be compatible with our needs with a reduction of availability, agreements of minimium storage duration, and costs for data access.

$0.026 GB/mo [Standard storage](https://cloud.google.com/storage/docs/storage-classes#standard)
$0.010 GB/mo [Nearline storage](https://cloud.google.com/storage/docs/storage-classes#nearline)
$0.007 GB/mo [Coldline storage](https://cloud.google.com/storage/docs/storage-classes#coldline)
$0.004 GB/mo [Archive storage](https://cloud.google.com/storage/docs/storage-classes#archive)

**Comment by theathorn** [comment]
Closing - Broad will take over provision of the staging area (#2062).
