### ISSUE TITLE
Transfer all DCP/1 data and metadata to DCP/2 staging area

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2048]
..excluding secondary analysis files.

**Comment by theathorn** [comment]
@hannes-ucsc I think we agreed to two areas in the staging bucket:

1. All versions of DCP/1 Primary data and metadata
2. All versions of DCP/1 Secondary Analysis data and metadata

Then:

1. Import the Primary (meta)data and snapshot as a basis for the DCP/2 MVP
2. Import the Secondary (meta)data and snapshot as a DCP/1 provenance.archive

**Comment by danielsotirhos** [comment]
All DCP/1 data and metadata has been transferred to `gs://broad-dsp-monster-hca-prod-ucsc-storage` .

Analysis Bundles:
```
$ gsutil ls gs://broad-dsp-monster-hca-prod-ucsc-storage/prod/analysis/links | wc -l
14497
```

Non-Analysis Bundles:
```
$ gsutil ls gs://broad-dsp-monster-hca-prod-ucsc-storage/prod/no-analysis/links | wc -l
136007
```

Previous copy of all DCP/1 metadata (without data files):
```
$ gsutil ls gs://azul-dss-adapter-dev/dev/links | wc -l
150504
```
