### ISSUE TITLE
Promote from hca/dev all the way to hca/prod

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2063]
- [x] Check if `hca/dev` was reindexed during most recent deployment. If not, reindex `hca/dev`.
- [x] Promote to `hca/integration` and reindex
- [x] Promote to `hca/staging` and reindex
- [x] Smoke test Data Browser instance for `hca/staging`
- [x] Prepare relesae notes; announce on Slack `#dcp-ops` channel
- [ ] Check in with @theathorn and @hannes-ucsc 
- [ ] Promote to `hca/prod` and reindex
- [ ] Smoke test Data Browser instance for `hca/prod`

This to get #2013 to `hca/prod`.

**Comment by theathorn** [comment]
Added #2051 to the list of fixes to deploy.
