### ISSUE TITLE
Add endpoint for listing available catalogs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2066]
Add GET /index/catalogs to return a JSON response that lists all configured catalogs:

```json
{
    "default_catalog": "dcp2",
    "catalogs": {
        "dcp2": {
            "atlas": "hca",
            "plugins": [
                {
                    "type": "repository",
                    "name": "tdr"
                },
                {
                    "type": "metadata",
                    "name": "hca"
                }
            ]
        },
        "lungmap": {
            "atlas": "lungmap",
            "plugins": [
                {
                    "type": "repository",
                    "name": "tdr"
                },
                {
                    "type": "metadata",
                    "name": "hca_lungmap"
                }
            ]
        }
    }
}
```

The atlas a catalog belongs to is currently not configured anywhere so we need to modify the syntax of AZUL_CATALOGS as follows:

```diff
Index: environment.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/environment.py b/environment.py
--- a/environment.py	(revision 22985eb9af3a432beba960297eb9fcfa9598bada)
+++ b/environment.py	(date 1611087791519)
@@ -32,9 +32,11 @@
         #
         # The syntax of each catalog is
         #
-        # catalog_name, (':', plugin_type, '/', plugin_package)+
+        # atlas, ':', catalog_name, (':', plugin_type, '/', plugin_package)+
         #
-        # `catalog_name` is the name of the catalog and its syntax is fairly
+        # where `atlas` is the name of the atlas the catalog belongs to
+        # and `catalog_name` is the name of the catalog. The atlas name and 
+        # catalog names follow the same syntax, which is fairly
         # restrictive (see azul.IndexName.validate_catalog_name for details).
         # `plugin_type` is the name of a child package of `azul.plugins` and
         # `plugin_package` is the name of a child package of that package. The
```

This will introduce some upgrade pain. The parser for AZUL_CATALOGS should detect a missing atlas name and raise an obvious error, rather than one that complains about a an error in the plugin part of the syntax.

**Comment by melainalegaspi** [comment]
@hannes-ucsc provide more details in the description

**Comment by hannes-ucsc** [comment]
Done with spike.

**Comment by jessebrennan** [comment]
@hannes-ucsc, estimate?

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/2066#zh-event-60074853e5960adaf4af8ed3

**Comment by hannes-ucsc** [comment]
Note this is in the Backlog, so don't start working on this yet.

**Comment by jessebrennan** [comment]
> Note this is in the Backlog, so don't start working on this yet.
Got it.

Not sure how I missed the estimate, I think it has to do with the issue that Zenhub keeps signing out on my machine.

**Comment by theathorn** [comment]
Do we want something like an "attribute" in the response that would e.g. be set to "hidden" for the "staging" catalog in prod?

**Comment by hannes-ucsc** [comment]
I think any non-default catalog should be considered hidden as in that it requires a special action to select it. Happy to discuss any additional attribution with DB team.

**Comment by theathorn** [comment]
@NoopDog @MillenniumFalconMechanic : WDYT? When there are multiple catalogs per environment, I think we would present a drop-down list for the user. However, for prod, "staging" is a catalog we don't want to present to the end user.

**Comment by hannes-ucsc** [comment]
The visibility of a catalog in the UI bears no relevance to Azul. The relevant information for Azul is which catalogs exist. which catalog is the default one and how each catalog is configured (which plugins and what the source is). The atlas a catalog belongs to isn't relevant either at the moment but it might become useful in the future to limit reindexing to only the catalogs in an atlas, so I'm going to leave that in.

**Comment by theathorn** [comment]
OK, so the UI will need its own configuration for "prod" so that it doesn't list the "staging" catalog to end users, but does list all the other "prod" catalogs (e.g. potentially "dcp2" plus all the catalogs for "historical data releases").

**Comment by hannes-ucsc** [comment]
Yes, keep in mind that it is easier to deploy a change to the DB than deploying one for Azul because Azul has a more involved architecture and build process. So if a configuration value solely affects DB, it should be configured in the DB and not Azul.

Another thing to note is that ultimately what's visible to a user will depend on who they are. If they don't have access to any snapshots in a catalog, they shouldn't see that catalog in the UI element with which they chose the catalog. This is the most elegant solution because it requires no configuration and no secret UI mechanism for selecting a hidden catalog.

Until we have that feature, the hidden catalog should be configured in the DB. Alternatively, we can set up a naming convention by which we the lexicographical ordering of catalog names represents their historical ordering. Any catalog with a name that's greater than the name of the default catalog should be considered hidden.
