### ISSUE TITLE
Delete DSS leftovers in us-west-2

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2074]
![image](https://user-images.githubusercontent.com/5143256/88466857-8379ef00-ce85-11ea-9953-07fdc10989a5.png)

**Comment by amarjandu** [comment]
Deleted: stepfunctions, sqs, sns, dynamodb

**Comment by amarjandu** [comment]
deleted: secrets + parameters

**Comment by amarjandu** [comment]
removed api-gateway + mappings
