### ISSUE TITLE
Reindex script sends catalog's index notifications out of order

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2085]
Since the `dict_keys` which contains the catalog's names is converted to a set, the index notifications for `dcp1` catalog may be sent before `dcp2`.

I've experienced this in the debugger, and this may partly explain why @hannes-ucsc reported that the DCP1 catalog was indexed before the DCP2 catalog.

Edit:
Proof that catalogs is converted to a set:
```
Python 3.8.3 (default, Dec  4 2020, 12:30:22) 
[GCC 9.3.0] on linux
>>> from scripts.reindex import *
>>> args = parser.parse_args([])
>>> type(args.catalogs)
<class 'set'>
>>> list(args.catalogs)
['dcp2', 'dcp2ebi']
```
In this particular case the order was *not* reversed, but I just got (un)lucky. Here is the relevant line that causes that conversion to a set: https://github.com/DataBiosphere/azul/blob/482d491e0a9c275639801ff3248bdf9baf5bb27a/scripts/reindex.py#L64

The order of items is therefore not guaranteed when we iterate through the set of catalogs to send out notifications for each https://github.com/DataBiosphere/azul/blob/482d491e0a9c275639801ff3248bdf9baf5bb27a/scripts/reindex.py#L114.

**Comment by theathorn** [comment]
@hannes-ucsc "To be verified".

**Comment by hannes-ucsc** [comment]
In order to save time, my time, let's reverse the burden of proof. The description lacks a reproduction, so @jessebrennan should fill that in.

**Comment by jessebrennan** [comment]
@hannes-ucsc proposed to solve using an ordered set, or manually converting set difference to a list comprehension.
