### ISSUE TITLE
Include `cell_suspension.*.biomaterial_id` in metadata manifests

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2090]
From @ESapenaVentura :

## User story

As a user, I would like to link the original's author IDs provided in the HCA's loom file with the cell suspension they come from so that I can link the metadata from that cell suspension to the actual cells/gene expression.

This field's name should be consistent with the output of the conversation here https://humancellatlas.slack.com/archives/C01360XN04S/p1595966378198200 (Conversation still in progress)

## Definition of done
- [ ] The metadata manifests include a field with the user-provided ID, named consistently with the name of the field in the  output matrix files

**Comment by hannes-ucsc** [comment]
#2051 and #2081 add this to the terra.bdbag manifest for v1 and v2 respectively. Is that sufficient?

**Comment by hannes-ucsc** [comment]
We should spike to confirm that `full` has the field.

If that's the case we only need to add it to the `compact` manifest and we may not even need to do that.

**Comment by danielsotirhos** [comment]
`compact` and `terra.bdbag` have the field, `full` does not.

On `https://dev.singlecell.gi.ucsc.edu` &  `https://dev.data.humancellatlas.org`:
- `compact` -> cell_suspension.biomaterial_core.biomaterial_id
- `full` -> **n/a**
- `terra.bdbag` -> cell_suspension__biomaterial_core__biomaterial_id

Where each manifest type can be obtained from Browser:
- `compact`: Projects tab -> Select project -> Export data -> Request a File Manifest
- `full`: Projects tab -> Next to project name, click download link in "Metadata" column
- `terra.bdbag`: Projects tab -> Select project -> Export data -> Export to Terra

**Comment by danielsotirhos** [comment]
The above comment applies to `staging.data.humancellatlas.org` as well.

**Comment by danielsotirhos** [comment]
Results of index sizes after a reindex with and without the `biomaterial_id` field included in `FullMetadata`.
[index-sizes-with-without-biomaterial_id.txt](https://github.com/DataBiosphere/azul/files/5007994/index-sizes-with-without-biomaterial_id.txt)

**Comment by hannes-ucsc** [comment]
The average on the last line doesn't seem right.

How did you measure the index size?

**Comment by hannes-ucsc** [comment]
And full metadata is stored only in the `bundles` index so we only need to record that. 

But we do want the contributions for bundles which is missing above.

**Comment by danielsotirhos** [comment]
> The average on the last line doesn't seem right.

I used 1024 as a MiB: ((1.01 * 1024) + 1023.18) / 2) = 1028.71

> How did you measure the index size?

Index sizes were taken from AWS console (I confirmed these values were count=0, size=near-zero after each `make delete create` before each `make reindex`):

![Screen Shot 2020-07-31 at 10 43 11 AM](https://user-images.githubusercontent.com/46407464/89062088-ad666200-d31a-11ea-9ad2-2c2c34c2dac8.png)

**Comment by hannes-ucsc** [comment]
Could you cross-check the `bundles` index sizes against the native ES stats API (using kibana_proxy.py)?

No need to reindex, just trying make sure that the two measuring approaches give consistent results.

**Comment by danielsotirhos** [comment]
Certainly. Looks like the sizes obtained from AWS Console and kibana_proxy.py line up exactly.

AWS Console:
```
azul_v2_daniel_dcp1_bundles_aggregate
Count 598
Size in bytes 14.46 MiB
```

scripts/kibana-proxy.py:
```
GET /azul_v2_daniel_dcp1_bundles_aggregate/_stats
"indices" : {
    "azul_v2_daniel_dcp1_bundles_aggregate" : {
      "uuid" : "ZuZUm_DdRFO3_IKLohsEmQ",
      "primaries" : {
        "docs" : {
          "count" : 598,
          "deleted" : 0
        },
        "store" : {
          "size_in_bytes" : 15157281
        },
```
        
```
15157281 / 1024 / 1024 = 14.455109596252441
```

----

AWS Console:
```
azul_v2_daniel_dcp1_bundles
Count 598
Size in bytes15.81 MiB
```

```
scripts/kibana-proxy.py:
GET /azul_v2_daniel_dcp1_bundles/_stats
  "indices" : {
    "azul_v2_daniel_dcp1_bundles" : {
      "uuid" : "yUMQeNOyQj-EKJodrNM2kw",
      "primaries" : {
        "docs" : {
          "count" : 598,
          "deleted" : 0
        },
        "store" : {
          "size_in_bytes" : 16582668
        },
```

```
16582668 / 1024 / 1024 = 15.814464569091797
```
