### ISSUE TITLE
Review list of controlled access questions

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2095]
See this [doc](https://docs.google.com/document/d/1yWXDtWVhSU0t7TXKdg8S4DWohnDkxloQmbqCkXZUzoM).

Review the list of questions prior to @theathorn setting up a meeting with the TDR team.

**Comment by theathorn** [comment]
Meeting is on Monday 8/10 at 8:00AM.

**Comment by melainalegaspi** [comment]
Meeting held 8/10
