### ISSUE TITLE
Prepare IS3 policy into a spreadsheet

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2099]

**Comment by nolunwa** [comment]
@theathorn https://docs.google.com/spreadsheets/d/1H61l4tN-kzA5WTOdF_R5RUJ-FsJRjrJW_yGQGT-gQZs/edit#gid=0

**Comment by nolunwa** [comment]
@theathorn UCOP IS3 policy in spreadsheet format https://docs.google.com/spreadsheets/d/1H61l4tN-kzA5WTOdF_R5RUJ-FsJRjrJW_yGQGT-gQZs/edit#gid=0

**Comment by theathorn** [comment]
No longer relying on ITS - closing.
