### ISSUE TITLE
UCSC ITS Guideline - Security Baseline Configuration for AWS Installations

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2104]
Respond to how DCP v2.0 meets any portion of the minimum security baseline.

**Comment by theathorn** [comment]
[Guidelines](https://docs.google.com/document/d/1KKL82sfhqpyZJShuRXRdxPOSowyh_uYHfdRPVHGFa24)

**Comment by danielsotirhos** [comment]
Assigned to @hannes-ucsc for review.
All answers were added to the "Service/System" column of the [Guidelines](https://docs.google.com/document/d/1KKL82sfhqpyZJShuRXRdxPOSowyh_uYHfdRPVHGFa24) document

**Comment by hannes-ucsc** [comment]
LGTM

**Comment by theathorn** [comment]
No longer relying on ITS - closing.
