### ISSUE TITLE
Indexer tests are sensitive to AZUL_INDEXER_CONCURRENCY

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2107]
`test_indexing()` fails with `AZUL_INDEXER_CONCURRENCY` set to `8` and passes with `64`.
It should be noted that `8` is the value specified in `deployments/.example.local/environment.py`

Example of test failure:
https://travis-ci.org/github/DataBiosphere/azul/builds/714550542#L3857

**Comment by danielsotirhos** [comment]
Issue not triggered with `dev` deployment selected.

Temporary workaround fix for personal deployments is to modify personal deployment's `environment.py` to set `AZUL_INDEXER_CONCURRENCY` to `64` instead of `8`, or just comment out the line to inherit value from `azul/environment.py`

**Comment by hannes-ucsc** [comment]
The fix is likely going to be to pin AZUL_INDEXER_CONCURRENCY for unit tests but I'd like to first find out why the `sort` field in responses is sensitive to the number of shards (which is derived from that variable).

**Comment by jessebrennan** [comment]
Unfortunately, I still don't know why the sort field in the response is sensitive to the number of shards. I do know a bit more about the field however.

The sort field shows up on the hits if a sort is specified in the search. It contains the elements of the hit that is being sorted on. If we sort on `_id`, then the sort field will contain a list of the ID's value. By default, the Python `scan()` function specifies `"sort": "_doc"`. I'm not totally sure what this means. From what I know, `_doc` is the default type mapping. The ES docs also mention:

> Scroll requests have optimizations that make them faster when the sort order is _doc. If you want to iterate over all documents regardless of the order, this is the most efficient option

Examining the value that's present doesn't give any obvious clues to its meaning. It's consistently a single digit number. If there are many shards, the value is low.

Pinning the indexer_concurrency is one option to make this predictable, but I found another work-around. If the scroll (`scan()`) request is made without specifying a sort order, then the `sort` field is omitted from the response, making it consistent regardless of the number of shards. 

I'll make a pull request with these changes shortly.
