### ISSUE TITLE
Add metadata field to hide test projects in data browser

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#212]
See https://docs.google.com/document/d/1isYNP_l8y6he5GjcJ-ABkZ19do_-l6x0tjh3vN4qMPQ/edit?ts=5b6d9e22#heading=h.1m391awqmqc9.

We propose to leverage the inclusion of an enum (or similar) in a "provenance" field in the metadata schema. This field could store flags such as:
 
"testing data"
"benchmarking data"
"draft-schema"
"development data"

Initially, the Data Browser will filter this field, hiding data by default that contain any of the above flags.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-151)
┆Project Name: azul
┆Issue Number: AZUL-151

**Comment by theathorn** [comment]
Moved to azul repo as https://app.zenhub.com/workspace/o/databiosphere/azul/issues/212

**Comment by hannes-ucsc** [comment]
Hannes to comment on naming choice. There already is a "provenance" section in the metadata.

**Comment by hannes-ucsc** [comment]
Well, we can't skip indexing such test bundles but we should be able to index them using a special filter facet that the browser *always* specifies in its requests to Azul. This property should be defined on the project entity. It would prevent those test projects being displayed in the browser, while still exposing them to the assertions in the DCP integration test.

**Comment by hannes-ucsc** [comment]
There are no "test projects" in DCP/2. We'll use hidden catalogs for that.

**Comment by hannes-ucsc** [comment]
that = hiding ongoing analysis work
