### ISSUE TITLE
SAM registration should use dev instance, not prod

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2120]
Currently `AZUL_SAM_SERVICE_URL` points to `'https://sam.dsde-prod.broadinstitute.org/'`.

Noah: "Is this a mistake, then?"

Hannes: "I think so.  The TDR instance is dev so it should be using the dev instance of SAM."

**Comment by hannes-ucsc** [comment]
That variable was introduced for #2025 which is still open because the demo revealed issues with it. We should either close this or make it a freebie of PR #2096.

**Comment by noah-aviel-dove** [comment]
Added as a freebie to https://github.com/DataBiosphere/azul/pull/2116. Sorry for jumping on this without asking, I didn't notice it was still in Triage.
