### ISSUE TITLE
Implement subgraph stitching for DCP/2

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2122]
DCP/1 analysis bundles were self-contained due to a feature called *copy forward*. An analysis bundle was a strict superset of the input bundle. DCP/2 analysis subgraphs are not self-contained. The `links.json` produced by analysis workflows only references the input files as inputs of the the analysis_process but it does not include the process(es) that produce those input files or any other graph edges above those. This is desirable because we wanted to eliminate the duplication in DCP/1 resulting from copy forward since it makes updates harder.

For one, this difference between DCP/1 and DCP/2 needs to mentioned explicitly in the spec document.

I'm pretty sure we also need to extend the TDR plugin to extend the dangling edges in the analysis subgraphs. In other words we need to stitch the graphs together to create a self-contained emulation of the analysis bundle in memory.

The challenge will be to determine which `links.json` to stitch on, since we only know the `sequence_file_id `of the input files, not the `links_id` of the subgraph that links them up to *their* parent entities. There may even be more than one subgraph to stitch on, if the the analysis had multiple input subgraphs, something that was never possible in DCP/1 but that we want to implement in DCP/2 at some point (cc @kbergin).

**Comment by hannes-ucsc** [comment]
I would like us to spike one aspect of this: is it possible to query the `links` TDR table for all rows whose `contents` column contains a link refering to a given input entity? And is that going to be slow? If it is slow, we may need to ask @raaidbroad to extract all inputs to from a links.json on input and expose them as a special column, potentially with an index on it.

**Comment by theathorn** [comment]
See https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/108.

**Comment by hannes-ucsc** [comment]
I don't understand the connection to that ticket EBI ticket, @theathorn.

**Comment by theathorn** [comment]
My mistake. This ticket is for DCP-generated matrices, not contributor submitted ones.

**Comment by noah-aviel-dove** [comment]
This query finds the FQIDs of all bundles containing a process link containing a particular entity id as input:

https://console.cloud.google.com/bigquery?sq=153363065845:b772902db4ca430087f495e3cfa0f898

It is not very performant, requiring ~6 seconds to complete for a single entity. It's also incompatible with TinyQuery. Since I still have a little time left in the spike I'm going to try another approach.

**Comment by noah-aviel-dove** [comment]
I realized that the performance of this approach would be largely unaffected by searching for multiple entities simultaneously, and a quick experiment seems to confirm that. This updated version could be used to retrieve all upstream bundles for all the entities in a downstream bundle, and still takes about 6 seconds.

https://console.cloud.google.com/bigquery?sq=153363065845:a6adbe7426674e61b0d01ae8b7e46275

Still hopelessly incompatible with TinyQuery.

**Comment by noah-aviel-dove** [comment]
A quick(er) hack would be just scan the content column for a textual occurrence of the string `"input_id":"{entity_id}"` without trying to parse the JSON. Obviously this is brittle. It could be made less brittle by fetching the `content` column, parsing the JSON with python, and verifying the input ids at that point, but fetching `content` might increase network latency. I'm not going to thoroughly test the actual performance this approach yet because 1. I think it's silly and 2. I'm out of time on the spike.

**Comment by hannes-ucsc** [comment]
Let's rerun the query on the all-bundles, no-data snapshot to get a better idea of the performance.

**Comment by noah-aviel-dove** [comment]
I ran both approaches (nested subqueries, string occurrence search with client-side JSON parsing) on the snapshot `hca_dev_20200817_dssPrimaryOnly` using the BigQuery Python API. I searched for all bundles containing a link containing an input id matching one of three entities. Oddly, performance was much better than when I tested the same queries using the BigQuery web console. I observed only 2.5 seconds for the nested subquery approach to finish and 1.1 seconds for the client-side approach. I verified that the list of bundles FQIDs returned matched between the two methods and with my earlier experiments. Perhaps BigQuery prioritizes programmatic access over manual interactions with the console.

**Comment by hannes-ucsc** [comment]
Sounds good. Let's triage today.

**Comment by theathorn** [comment]
Snapshot hca_dev_20201001_ebi17v3___20201022_analysis1 contains the new DCP?2 datasets plus Optimus and SS2 analysis outputs.

**Comment by theathorn** [comment]
From Raaid: The snapshot hca_dev_20201001_ebi17v3___20201023_analysis2 should have the fixes Noah pointed out.

**Comment by hannes-ucsc** [comment]
> From Raaid: The snapshot hca_dev_20201001_ebi17v3___20201023_analysis2 should have the fixes Noah pointed out.

It had more issues.

Today's candidate staging areas:

gs://fc-ac2f3a8d-d1f4-48a2-8c3b-6d75ec942289/staging_10_26_20_v1/
gs://fc-299d55fe-e355-45ea-8f59-c1eb111b4681/staging_10_26_20_v1/

Snapshot is in the [works](https://humancellatlas.slack.com/archives/C01360XN04S/p1603727117249900?thread_ts=1603433805.210700&cid=C01360XN04S):
