### ISSUE TITLE
Design process for tracking spike estimates separately 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2130]

**Comment by natanlao** [comment]
After some thought, the label method suggested by Hannes (where we have a set of `spike:` labels to indicate spike estimates) is the best option.

Alternative options considered:

* We could identify the last estimate before the `spike` tagged is removed as the spike estimate. I was correct in identifying there GitHub does not expose label modification times through their API, though I've found that a preview API to do so exists (https://docs.github.com/en/rest/overview/api-previews#timeline). This reduces the need for additional labels, but introduces some further complexity; we would need to compare times provided by GitHub's API and ZenHub's API, and I have observed inconsistencies with the latter. Further, correcting an erroneous spike estimate would be unintuitive.

* We could use some special comment syntax in an issue to denote the spike estimate. This could work, but is not as intuitive as using labels.

The advantage of using labels as described: 
* Spike estimates are clearly visible from the ZenHub workspace
* Spike estimates can easily and intuitively be corrected after they are first set
* Minimizes overloading of the issue estimate and make it easy to differentiate the issue and spike estimate

**Comment by natanlao** [comment]
@hannes-ucsc signed off on this during standup and identified `spike:1`, `spike:2`, `spike:3`, `spike:5`, and `spike:8` as labels

**Comment by natanlao** [comment]
<img width="576" alt="Screen Shot 2020-08-12 at 12 04 30 PM" src="https://user-images.githubusercontent.com/23219746/90057618-7e92a900-dc95-11ea-99ef-2d045536161a.png">

**Comment by theathorn** [comment]
This is complete and in use - closing,
