### ISSUE TITLE
Set up bucket for contributor-generated matrices

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2136]
We need to create a location for EBI to drop user-generated matrices into.

We can go ahead and create a GCS bucket in the `platform-hca-prod` project. Assignee may need to be given access by me.

We are waiting on the list of EBI people to give write access to.

**Comment by lauraclarke** [comment]
Please give access to Rolando Fernandez and Rodrey Goite from EMBL-EBI

**Comment by danielsotirhos** [comment]
Bucket created `hca-prod-ebi-matrices`

**Comment by danielsotirhos** [comment]
Access granted to Rolando Fernandez and Rodrey Goite.

**Comment by hannes-ucsc** [comment]
@danielsotirhos, could you post link to bucket in console so Rolando and Rodrey don't have that problem you ran into with the bucket BI provided to us.

**Comment by danielsotirhos** [comment]
gs://hca-prod-ebi-matrices
https://console.cloud.google.com/storage/browser/hca-prod-ebi-matrices

**Comment by hannes-ucsc** [comment]
Looks good.

**Comment by lauraclarke** [comment]
Sorry, can you give a couple of other people access, 

Marion Shadbolt
Ray Stefancisk
Ami Day, I will tag them on the slack thread too

**Comment by mshadbolt** [comment]
hi @danielsotirhos I can see the bucket but I can't seem to upload any data to it, this is what it looks like to me:
![Screenshot 2020-08-13 at 13 51 17](https://user-images.githubusercontent.com/13007987/90136455-1a8ee400-dd6c-11ea-9eec-2befc2d33306.png)

When I try to use the buttons to upload files or upload folder it gives me the message '0 of 0 files successfully uploaded'

**Comment by danielsotirhos** [comment]
@mshadbolt Oh, sorry about that. Please confirm you're logged in with your `mshadbolt@ebi.ac.uk` address. If you need me to change the address granted access just let me know. Also I've gone ahead and changed your role in the bucket from "Storage Object Creator" to "Storage Object Admin". You should certainly have upload permission with this role.

**Comment by danielsotirhos** [comment]
Related to https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/108
