### ISSUE TITLE
Update entry for Tuatara in HCA DNS

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2139]
From Clay:
We had an Amazon EC2 instance on the CZI account to hold our project tracker, Tuatara. It can be reached at tuatara.data.humancellatlas.org.

Galt has just moved our server to an internal machine, which he currently has available at tuatara.gi.ucsc.edu. We would like to change the DNS to point to this new machine. 

From @hannes-ucsc:
The DNS zones haven't been moved to our AWS account yet but I have admin access to CZI's prod account so I can set this up now. It would be migrated organically along with all the other names once we move the zones to our own AWS account.

I can do either a CNAME or A record. Which one would you like? For an A record I would use IP 128.114.198.55. Let me know if you'd like to use a different one.

From Galt:
Let's do the CNAME. It should work and be fairly easy.
Please let us know when it takes effect so that we can do some quick follow-up testing!

**Comment by hannes-ucsc** [comment]
Before

```
$ dig tuatara.data.humancellatlas.org

; <<>> DiG 9.16.1-Ubuntu <<>> tuatara.data.humancellatlas.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9735
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;tuatara.data.humancellatlas.org. IN	A

;; ANSWER SECTION:
tuatara.data.humancellatlas.org. 293 IN	CNAME	ec2-52-91-92-236.compute-1.amazonaws.com.
ec2-52-91-92-236.compute-1.amazonaws.com. 7193 IN A 52.91.92.236

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Aug 11 13:45:02 PDT 2020
;; MSG SIZE  rcvd: 130
```

after

```
$ dig tuatara.data.humancellatlas.org

; <<>> DiG 9.16.1-Ubuntu <<>> tuatara.data.humancellatlas.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32821
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;tuatara.data.humancellatlas.org. IN	A

;; ANSWER SECTION:
tuatara.data.humancellatlas.org. 300 IN	CNAME	tuatara.gi.ucsc.edu.
tuatara.gi.ucsc.edu.	7199	IN	A	128.114.198.55

;; Query time: 387 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Aug 11 14:00:33 PDT 2020
;; MSG SIZE  rcvd: 109
```
