### ISSUE TITLE
Add 'organismAge' special filtering requirement to schemas so that it is enforced by generic validation

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2166]
@hannes-ucsc : "At the very least the is branch should allow unit-value dicts as facet values. Alternatively we could make this even more rigid by tying the value type to the facet name via field types. Every facet maps to a document path and every document path maps to a FieldType instance."

From [PR review](https://github.com/DataBiosphere/azul/pull/1909/commits/ec728a3f654985167687aa40541a6da647010cd9#r467208379).

**Comment by hannes-ucsc** [comment]
Superseded by #2254.
