### ISSUE TITLE
Guidelines missing from contribution guide 

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2169]
https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst

- [x] Minimize diffs
- [x] Explain `hold warm`
- [x] Testing of chained PRs (adding base branch of chained PR to `.travis.yml`)
- [x] Last sentence on chains makes no sense
- [x] Naming mappings https://github.com/DataBiosphere/azul/pull/2121#discussion_r468193791
- [x] Naming variables in comprehensions https://github.com/DataBiosphere/azul/pull/2121#discussion_r468183740
- [x] Explain do/donts of subtests https://github.com/DataBiosphere/azul/pull/2121#discussion_r469453453
- [x] Pass all or none as kwargs, with exception for boolean args from pep8
- [x] Mention that messages of split commits should have a body for distinction

**Comment by jessebrennan** [comment]
Should these be added to this ticket?
- https://github.com/DataBiosphere/azul/pull/2121#discussion_r468193791
- https://github.com/DataBiosphere/azul/pull/2121#discussion_r468183740
- https://github.com/DataBiosphere/azul/pull/2121#discussion_r469453453

**Comment by jessebrennan** [comment]
Consider adding a sentence that clarifies that multi-commits should have a commit body explaining the changes.

**Comment by hannes-ucsc** [comment]
Last sentence on chains in C guide makes no sense.

**Comment by natanlao** [comment]
Should process on testing chained PRs be documented in the guide (i.e., adding base branch of chained PR to .travis.yml)? It's mentioned in passing but not documented explicitly

**Comment by hannes-ucsc** [comment]
@jessebrennan 

> Consider adding a sentence that clarifies that multi-commits should have a commit body explaining the changes.

By "multi-commits" do you mean the `[1/2]` , `[2/2]` style?

**Comment by jessebrennan** [comment]
> do you mean the [1/2] , [2/2] style?

Exactly that.

**Comment by amarjandu** [comment]
This should be added to the ticket: 
https://github.com/DataBiosphere/azul/pull/1849#discussion_r481373291
https://github.com/DataBiosphere/azul/pull/1849#discussion_r481374154

**Comment by amarjandu** [comment]
@hannes-ucsc " consider removing requirement for else branch with body of if branch contains bailout"

**Comment by amarjandu** [comment]
request to add section for instructions within documentation, see https://github.com/DataBiosphere/azul/pull/2291#discussion_r493116351

**Comment by jessebrennan** [comment]
Paraphrasing @hannes-ucsc, if a function has positions *and* keyword arguments, the keyword arguments should be made [keyword-only](https://www.python.org/dev/peps/pep-3102/).
