### ISSUE TITLE
Assert that Orange indexes analysis bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#217]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-153)
┆Project Name: azul
┆Issue Number: AZUL-153

**Comment by alex-hancock** [comment]
Pull request [here](https://github.com/HumanCellAtlas/dcp/pull/113)

**Comment by alex-hancock** [comment]
Need to add issue (and possibly fix in this PR?) to address [this](https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/4958) by assuring that we retry 500 errors.

**Comment by hannes-ucsc** [comment]
Resolved by https://github.com/HumanCellAtlas/dcp/commit/29d9cca453a7478379bfa5502cfb5a6f300d161b
