### ISSUE TITLE
Sorting by cell count ignores grouping of cell suspensions by organ

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2176]
The facet `cellCount` backed by the indexed field `contents.cell_suspensions.total_estimated_cells` is inadequate for sorting the `/index/projects` endpoint response for hits containing multiple `cellSuspensions` due to the grouping aggregation on cell suspension by organ.

The total cell count per hit is being calculated and shown by the browser however the hits returned by Azul are not sorted by this total cell count per hit, but instead by the lowest cell count for any organ.

![sorting-index-projects-on-cellcount](https://user-images.githubusercontent.com/46407464/90450973-afad1800-e09f-11ea-8d54-60fecb57eb4e.jpg)

**Comment by hannes-ucsc** [comment]
@danielsotirhos please determine what the current sort behaviour is. Does it sort by the lowest, highest or an arbitrary cell count entry within each document.

**Comment by hannes-ucsc** [comment]
… and edit the description accordingly.

**Comment by hannes-ucsc** [comment]
Replaced blocking relationship with epic.

**Comment by danielsotirhos** [comment]
Results are sorted by the lowest cell count entry.
From `ElasticsearchService._apply_paging()`:
```
es_search = es_search.sort({_sort: {"order": _order, "mode": 'min'}},
                           {'_uid': {"order": 'desc'}})
```
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/sort-search-results.html#_sort_mode_option

And results confirmed:
```
$ http 'https://service.dev.singlecell.gi.ucsc.edu/index/projects?filters=%7B%7D&size=150&sort=cellCount&order=asc' | jq '.hits[].cellSuspensions[].totalCells'

##  a star has been added to each lowest value per hit

0       *
0
0
--
0       *
-
0       *
0
--
0       *
0
0
0
--
0       *
--
0       *
0
--
3274
3185
180     *
--
4149
10561
951
2464
5355
7115
1961
2663
1391
5862
865     *
1151
1432
1638
1923
1718
981
1580
--
2244    *
--
2544    *
--
3514    *
--
4000    *
--
9500    *
--
12404   *
--
44615
15175   *
--
16893   *
--
19916   *
--
20000   *
--
30952
27083   *
54166
--
30000   *
--
30000   *
--
93267
40025   *
66553
--
44000   *
--
230800  *
--
274182
253910  *
--
339089  *
--
1330000 *
--
1480000 *
```

**Comment by danielsotirhos** [comment]
Solution will be to use sort mode 'sum' for numeric fields including cell count. The desired sort mode should be obtained from `FieldType.sort_mode()`
