### ISSUE TITLE
Edge detection on wait_for_queue_level status in Queues is unreliable

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2178]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5436

It seems to have caught the exact moment in time where the approximate queue lengths were zero. Technically this is impossible because a `reindex` action message isn't deleted before the resulting bundle notifications are queued. Nevertheless, these counts are called approximate for a reason so we should code for that.

Also, the exception message is `Timeout. The queues are NOT at the desired level`. The desired level is 0 so the message is incorrect, too, since the queues appear to be empty (they are not, but that's covered in the paragraph above).

**Comment by hannes-ucsc** [comment]
There isn't exactly a blocking relationship between this and #2147 but I think the two tickets should be assigned the same person and be solved at the same time.

**Comment by hannes-ucsc** [comment]
Replace blocking relationship with epic.

**Comment by hannes-ucsc** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5845

**Comment by hannes-ucsc** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/7618

This is becoming annoying. We should fix.

**Comment by hannes-ucsc** [comment]
The fix from PR #2492 does not appear to work correctly:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/8535

**Comment by melainalegaspi** [comment]
Freebie of #2645
