### ISSUE TITLE
Manifest generation fails without a catalog selected

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2179]
With no `catalog` selected (the default behavior) all 3 types of manifests (compact, terra.bdbag, full) fail to generate on https://dev.singlecell.gi.ucsc.edu/ due to the `catalog` parameter being included in the call to Azul's `/fetch/manifest/files` endpoint but with no value specified (eg. ".../fetch/manifest/files?**catalog=**&filters=%7B%22...&format=full" )

![Screen Shot 2020-08-18 at 9 34 48 AM](https://user-images.githubusercontent.com/46407464/90540448-15e47a00-e136-11ea-85ef-a0a9193f9b5f.png)
![empty-catalog-parameter](https://user-images.githubusercontent.com/46407464/90541093-f9950d00-e136-11ea-979c-fce18582841e.jpg)

**Comment by danielsotirhos** [comment]
One solution would be for the data-browser not to include the `catalog` parameter if no value is set as then Azul would use the default catalog, or another solution would be for Azul to use the default value if `catalog` is specified with no value.

**Comment by hannes-ucsc** [comment]
This is a browser bug. `?catalog=&` is specifying a catalog, one whose name is the empty string. That's not a valid catalog name. As always, I don't want to conflate no catalog name with empty catalog name because that limits our freedom in the future to distinguish between them.

**Comment by theathorn** [comment]
Fixed by humancellatlas/data-browser#1309.
