### ISSUE TITLE
Add throttling to BigQuery requests to prevent 403 rateLimitExceeded errors

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2189]
From https://cloud.google.com/bigquery/troubleshooting-errors:
```
rateLimitExceeded: 403

This error returns if your project exceeds a short-term rate limit by sending too many requests too quickly. For example, see the rate limits for query jobs and rate limits for API requests.

https://cloud.google.com/bigquery/quotas#query_jobs

Concurrent rate limit for interactive queries — 100 concurrent queries
Concurrent rate limit for interactive queries against Bigtable external data sources — 4 concurrent queries

https://cloud.google.com/bigquery/quotas#api_requests

API requests per second, per user — 100
Concurrent API requests, per user: 300
```

From CloudWatch `dev` logs:
```
[ERROR] Forbidden: 403 Exceeded rate limits: too many concurrent queries for this project_and_region. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors
(job ID: b5e9ff04-a0c6-4b32-939a-8506eab6d534)
-----Query Job SQL Follows-----
1:
2: SELECT content, analysis_process_id, version, BYTE_LENGTH(content) AS content_size, JSON_EXTRACT_SCALAR(content, "$.schema_type") AS content_type
3: FROM hca_dev_20200817_dssPrimaryOnly.analysis_process
4: WHERE analysis_process_id = "bfd9e10b-5fa9-405c-ba1f-dc54aa296029"
5:
Traceback (most recent call last):
  File "/var/task/app.py", line 112, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 1430, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 121, in contribute
    app.index_controller.contribute(event)
  File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
    contributions = self.transform(catalog, notification, delete)
  File "/var/task/azul/indexer/index_controller.py", line 172, in transform
    bundle = self.repository_plugin(catalog).fetch_bundle(bundle_fqid)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 101, in fetch_bundle
    bundle = self.emulate_bundle(bundle_fqid)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 213, in emulate_bundle
    rows = future.result()
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/var/lang/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 199, in retrieve_rows
    rows = self._query_latest_version(f'''
  File "/var/task/azul/plugins/repository/tdr/__init__.py", line 143, in _query_latest_version
    groups = itertools.groupby(sorted(iter_rows, key=key), key=key)
  File "/opt/python/google/cloud/bigquery/job.py", line 3378, in __iter__
    return iter(self.result())
  File "/opt/python/google/cloud/bigquery/job.py", line 3196, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/opt/python/google/cloud/bigquery/job.py", line 818, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/opt/python/google/api_core/future/polling.py", line 130, in result
    raise self._exception
```

![dev-403-errors](https://user-images.githubusercontent.com/46407464/90692296-bbc4e100-e229-11ea-8c35-e41e1655435d.jpg)

**Comment by hannes-ucsc** [comment]
https://cloud.google.com/bigquery/docs/running-queries#batch

> BigQuery also offers batch queries. BigQuery queues each batch query on your behalf, and starts the query as soon as idle resources are available in the BigQuery shared resource pool. This usually occurs within a few minutes. If BigQuery hasn't started the query within 24 hours, BigQuery changes the job priority to interactive.

> Batch queries don't count towards your concurrent rate limit, which can make it easier to start many queries at once. Batch queries use the same resources as interactive (on-demand) queries. If you use flat-rate pricing batch queries and interactive queries share your allocated slots.

**Comment by hannes-ucsc** [comment]
When BQ is accessed from outside of a lambda, we don't recover from this type of error:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/5700

**Comment by hannes-ucsc** [comment]
We may want to add an explicit retry to A) add resilience to this outside of lambda and B) avoid discarding progress made when indexing a subgraph (each subgraph requires as many queries as there are entity types in the subgraph).

**Comment by amarjandu** [comment]
There appears to already be retries added to the `bigquery.query` method in the `bigquery` client. 
https://github.com/googleapis/python-bigquery/blob/master/google/cloud/bigquery/client.py#L2703

rateLimitExceeded is within the set of errors that is retired on. 
https://github.com/googleapis/python-bigquery/blob/aa1613c1bf48c7efb999cb8b8c422c80baf1950b/google/cloud/bigquery/retry.py#L19

Looking at adding explicit retry within plugin.

**Comment by hannes-ucsc** [comment]
Just happened again in IT https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/6353.

**Comment by amarjandu** [comment]
> Just happened again in IT https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/6353.

The timestamps listed before the error align with me performing a reindex of prefix `0` on my personal deployment.

**Comment by amarjandu** [comment]
Reindex without explicit retry or concurrency reduction  Reindex that ran late 10/16/2020 into 10/17/2020 was selected

| Question  | Count  |
| -------------| -----:|
| How many requests against BigQuery cause the trip for limit?   | 10762 |
| How many requests to BigQuery?   | 1610089 |
| Number of failed lambda invocations?   | 10762 |

The following cloudwatch insight was used, remove the comment from line as needed if trying to run it. 

```
#fields @timestamp, @message | filter @message like '[ERROR]'  | stats count(*) as ERROR # 10762 total hits
#fields @timestamp, @message | filter @message like /Retrieved|ERROR/  | stats count(*) as Total_TDR_Requests # 1610089 total hits
fields @timestamp, @message | filter @message like /fail/  | stats count(*) as Lambda_Failures # 10762 total hits
```
