### ISSUE TITLE
Running md5sum workflow in Terra on file exported from Data Browser fails with "502 Bad Gateway" error

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2204]
Following on from #2203, I selected one row and attempted to run an md5sum workflow check against "this.__fastq_read1_0__drs_url" which terminated with "ErrorReport(rawls,http error calling uri https://us-central1-broad-dsde-prod.cloudfunctions.net/martha_v2,Some(502 Bad Gateway),List(),List(),None)
ErrorReport(rawls,http error calling uri https://us-central1-broad-dsde-prod.cloudfunctions.net/martha_v2,Some(502 Bad Gateway),List(),List(),None)".

**Comment by noah-aviel-dove** [comment]
Error reproduced.

**Comment by noah-aviel-dove** [comment]
DRS URI being provided to the workflow is accepted by Terra (200 response).

**Comment by noah-aviel-dove** [comment]
DRS URI is also accepted by the upstream Broad server that generates the 502 error (`POST https://us-central1-broad-dsde-prod.cloudfunctions.net/martha_v2` with body=`drs://jade.datarepo-dev.broadinstitute.org/v1_e48def68-3d1a-48a6-94f0-85f33e1e6279_d3782a24-1a38-43a6-997f-43b0748fa5e0` -> status 200)

**Comment by noah-aviel-dove** [comment]
I see two possibilities: 
1. This is a bug in Terra.
2. This is a manifestation of the fact that we cannot yet actually download the DRS objects the URIs in our manifests point to. That's the only step I can test with the DRS URIs that doesn't succeed. The only reason I'm not 100% confident that this is the issue is because I'm not sure what credentials are used when the Terra workflow requests the DRS object.

**Comment by noah-aviel-dove** [comment]
I get a 401 when attempting the download with my SA credentials, but it's conceivable that this causes a 502 in the workflow since the error  is coming from a different server.

**Comment by noah-aviel-dove** [comment]
Spike concluded.

**Comment by theathorn** [comment]
From Kyle Vernest: "Trevor, this is a bug in Terra and unfortunately will take us a little bit to fix as there are several services that need updating. I might be a few weeks before this is resolved."
