### ISSUE TITLE
Terra export from dcp2ebi catalog fails with import error in Terra workspace

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2225]
https://dev.singlecell.gi.ucsc.edu/explore/projects?filter=%5B%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D%5D

Select DCP2EBI

Export Selected Data

Start (under Export to Terra (Beta))

![image](https://user-images.githubusercontent.com/5143256/92019339-5124a280-ed0b-11ea-9755-cc0d5a88f0ce.png)

Proceed with new workspace in Terra.

![image](https://user-images.githubusercontent.com/5143256/92019448-7dd8ba00-ed0b-11ea-9aad-37d51f904c49.png)

```
{
  "statusCode": 400,
  "source": "rawls",
  "timestamp": 1599069570333,
  "causes": [],
  "stackTrace": [],
  "message": "Invalid input: __fastg.gz_1__file_uuid. Input may only contain alphanumeric characters, underscores, and dashes."
}
```

When selecting only `fastq.gz` the export works. When selecting all three `.fastq.gz`, `fastg.gz` and `fastq.gz` the export fails with a different error.

```
{
  "statusCode": 400,
  "source": "FireCloud",
  "timestamp": 1599068936555,
  "causes": [],
  "stackTrace": [],
  "message": "java.lang.ArrayIndexOutOfBoundsException - 512\nHint: Number of columns processed may have exceeded limit of 512 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can have\nEnsure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse\nParser Configuration: CsvParserSettings:\n\tAuto configuration enabled=true\n\tAutodetect column delimiter=false\n\tAutodetect quotes=false\n\tColumn reordering enabled=true\n\tEmpty value=\n\tEscape unquoted values=false\n\tHeader extraction enabled=null\n\tHeaders=null\n\tIgnore leading whitespaces=true\n\tIgnore trailing whitespaces=true\n\tInput buffer size=1048576\n\tInput reading on separate thread=false\n\tKeep escape sequences=false\n\tKeep quotes=false\n\tLength of content displayed on error=-1\n\tLine separator detection enabled=true\n\tMaximum number of characters per column=16384\n\tMaximum number of columns=512\n\tNormalize escaped line separators=true\n\tNull value=\n\tNumber of records to read=all\n\tProcessor=none\n\tRestricting data in exceptions=false\n\tRowProcessor error handler=null\n\tSelected fields=none\n\tSkip bits as whitespace=true\n\tSkip empty lines=true\n\tUnescaped quote handling=nullFormat configuration:\n\tCsvFormat:\n\t\tComment character=#\n\t\tField delimiter=\\t\n\t\tLine separator (normalized)=\\n\n\t\tLine separator sequence=\\n\n\t\tQuote character=\"\n\t\tQuote escape character=\"\n\t\tQuote escape escape character=null\nInternal state when error was thrown: line=0, column=513, record=0, charIndex=14568"
}
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Spike: Why do we get 2 different error messages depending on the selection? Should we protect ourselves against these types of metadata errors? What is the relationship to #2182?"

**Comment by theathorn** [comment]
Should have been fixed by latest EBI snapshot - please verify.

**Comment by kbergin** [comment]
LGTM - not sure why the file size has undefined units. 

![image](https://user-images.githubusercontent.com/9449764/93627631-3745b980-f9b3-11ea-94f5-239252b01da8.png)

**Comment by hannes-ucsc** [comment]
Thank you. I opened https://github.com/HumanCellAtlas/data-browser/issues/1337 for the `undefined` issue.

**Comment by jessebrennan** [comment]
I'm able to import this fine. #2182 would have prevented the invalid chars issue, but it's now moot. I assume this was fixed by the snapshot update. Waiting for approval from @hannes-ucsc or @theathorn before closing.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Issue cannot be reproduced anymore."
