### ISSUE TITLE
Import errors on scripts/provision_credentials.py

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2228]
Import errors when trying to destroy google_service_account using Terraform
see error in:
https://gitlab.dev.singlecell.gi.ucsc.edu/snippets/7

Note that the service account that was being used was still destroyed as requested.

**Comment by amarjandu** [comment]
@hannes-ucsc 'ideally errors would not be present, if not, explain that they are benign either in the process output, or within the README.md'

**Comment by amarjandu** [comment]
Note that in the attached log there terraform command that was run was
`terraform destroy -target=google_service_account.service_account`
while from the `develop` branch the command is 
`terraform destroy -target=google_service_account.indexer`
The error is the same regardless of the changes to the resource name.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Don't know why this was spiked. To be triaged."

**Comment by amarjandu** [comment]
@hannes-ucsc this was spiked to confirm that the errors were infant benign.

**Comment by jessebrennan** [comment]
The printed stack traces are benign. The warning that precedes them explains the issue. It's possible to filter them out https://github.com/googleapis/google-api-python-client/issues/299#issuecomment-255793971 which is what I'll do.
