### ISSUE TITLE
What are the Units for the Counts in TermFacets for /specimens?

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#223]
In Term Facets we have counts like:

```
"laboratory": {
      "terms": [
        {
          "term": "Regev Lab",
          "count": 127
        },
        {
          "term": "MRC Cancer Unit",
          "count": 53
        },
        {
          "term": "Sarah Teichmann",
          "count": 53
        },
        {
          "term": "Cambridge Biorepository for Translational Medicine",
          "count": 1
        },
        {
          "term": "Human Cell Atlas (Mike Stubbington)",
          "count": 1
        },
        {
          "term": "Molecular Immunity Unit, Department of Medicine",
          "count": 1
        }
      ],
```

My question is.. what are these counts of?

For the /files endpoint they used to be files. For the /specimens endpoint are these specimens?

Currently we show these counts in the term picker drop downs but we don't label them.   We need to add a label but I want it to be right. Also, if this changes depending on the tab that was selected we need to know. 

Thanks!
D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-157)
┆Project Name: azul
┆Issue Number: AZUL-157

**Comment by GPelayo** [comment]
Hi @NoopDog. The counts are the quantity of whatever tab is selected in the browser. If the "specimen" tab is selected, then that "counts" field is number of "specimen" entities. If "projects" is selected, then "counts" is the number of "projects".

You can use "entity" as an alternative label. It is the generic term that could describe specimen, project, etc.
