### ISSUE TITLE
Potential faceting errors on the 17 new DCP/2 projects

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2233]
From Marion:
The faceting seems a bit weird for some things, for example if you use the ‘Method’ drop down, for `Paired End` there are 15 projects with ‘false’, 2 with ‘true’ and 17 with ‘unspecified’, whereas I think in reality there might only be one project with unspecified. A similar thing seems to be happening with the library construction method, I don’t think there should be any with an ‘Unspecified’ library construction method but it is saying there are 16. Same for ‘Instrument Manufacturer Model.

**Comment by danielsotirhos** [comment]
The values reported in the ticket description do not match the current values.
![Screen Shot 2020-09-04 at 12 09 07 PM](https://user-images.githubusercontent.com/46407464/92277385-af868800-eea7-11ea-9752-987d3a7538c9.jpg)

**Comment by melainalegaspi** [comment]
@mshadbolt We cannot reproduce this. Please reopen with screenshot if you can still see this issue.
