### ISSUE TITLE
Spec for `filters` argument should be driven by field types

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2254]
The spec for the `filters` request parameter does not currently tie the facet name to the operator or the type of the values that are permissable as a right-hand side of the operator. For example, the spec does not indicate that 

`{"fileFormat": {"within": [{"unit": "foo", "value": "bar"}]}}`

is invalid because `within` only works with numeric values and `unit/value` only works with measured facets such as `organismAge`.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to decide next steps.

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "I rebased and resolved conflicts. However this needs more work since it is currently not functional. I will take this on."

**Comment by hannes-ucsc** [comment]
For demo, show changes in the OpenAPI specification of the `filters` parameter (removal of redundant `oneOf`, increased specificity of schema describing individual values, increased specificity of the set of supported relations for each field).
