### ISSUE TITLE
Terraform timed out updating a lambda

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2266]
This may just be a transient error, I've only seen it once so far. Regardless, I figured I'd document and if this keeps cropping up we'll have a place to track it.

```
Error: Error modifying Lambda Function Configuration azul-service-jesse1-jwt_auth: timeout while waiting for state to become 'success' (timeout: 1m0s)

  on service/chalice.tf.json line 363, in resource.aws_lambda_function.jwt_auth:
 363:             }
```

**Comment by jessebrennan** [comment]
As expected, re-running `make deploy` fixed this.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Haven't seen this in awhile."
