### ISSUE TITLE
Same auth token sent in TDR request is given back for reuse

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2268]
The auth token used when requesting the `https://jade.datarepo-dev.broadinstitute.org/ga4gh/drs/v1/objects/` endpoint is the same auth token given back in the response to be used to download the file.

![Screen Shot 2020-09-15 at 4 09 34 PM](https://user-images.githubusercontent.com/46407464/93274109-661f1e00-f76e-11ea-9066-0aa1ff7a2f71.png)

**Comment by melainalegaspi** [comment]
@hannes-ucsc :" I talked to the TDR team and it's implemented as designed. In order to avoid leaking the azul service account token, azul will mint signed urls on its own."
