### ISSUE TITLE
During aggregation 'total_estimated_cells' is being accumulated such that None == 0

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2271]
In the grouping aggregation of cell suspensions, a `SumAccumulator` with a default value of `0` is used to accumulate the value of `total_estimated_cells`. This is problematic for 2 reasons:

1) The default value of `0` ensures the aggregated value will never be `None`
2) The `SumAccumulator` skips over values of `None` such that `1 + 2 + None` would equal `3`. This needs further discussion however we probably want this to equal `3, None`

**Comment by amarjandu** [comment]
@hannes-ucsc "[None] becomes None, [None, 0] becomes 0, [None,1,2] becomes 3, [] becomes None, [None,None] becomes None"

Attempt to modify a canned bundle that is not used in many tests, and see if our assertion added to that test, if not then
add another test that modified the bundle on the fly, load it, modify the json, then index it, perform assertions. 

Canned bundle with prefix: `94f2` might be helpful, but it might not have organs to sort by which would mean there are no cell-suspensions present.

**Comment by amarjandu** [comment]
Can leverage deepdiff to find differences in large metadata documents. 
see https://gist.github.com/amarjandu/2c8eb6cd1f9754a041de4eabf0434555

**Comment by amarjandu** [comment]
from our discussion today the following question was raised - `would like to figure out why its (sort) is populated`.

I was not able to find the source code that is around this, however i did find https://www.elastic.co/guide/en/elasticsearch/reference/6.8/getting-started-search.html which refers to `hits.sort - the document’s sort position (when not sorting by relevance score) ` In our testcase the `hits._score` value is `null`. 

In this example https://kb.objectrocket.com/elasticsearch/how-to-sort-a-query-by-a-numeric-field-in-elasticsearch-6 the value of `hits.sort` is the same as the hits value for the field that was sorted on (quantity in their example). During our scan operation this is set to `_doc` https://github.com/elastic/elasticsearch-py/blob/738bda1e3b4e70dde2f55ee59af3f9e8dceaece3/elasticsearch/helpers/actions.py#L521. Further investigation can be done to see why the `hits.sort` value is incremented with the changes introduced here.

**Comment by amarjandu** [comment]
```
Index: test/indexer/test_hca_indexer.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- test/indexer/test_hca_indexer.py	(revision 8620eb230fd6f7221f03f01345c85da95a81a25b)
+++ test/indexer/test_hca_indexer.py	(date 1606350492878)
@@ -116,6 +116,14 @@
 
 class TestHCAIndexer(IndexerTestCase):
 
+    def _get_hits_no_scan(self):
+        search_es = self.es_client.search(body={'query': {'match_all': {}}, 'size': 100},
+                                          index=','.join(self.index_service.index_names(self.catalog)),
+                                          doc_type="doc")
+        for hit in search_es['hits']['hits']:
+            self._verify_sorted_lists(hit)
+        return search_es['hits']['hits']
+
     def _get_all_hits(self):
         hits = list(scan(client=self.es_client,
                          index=','.join(self.index_service.index_names(self.catalog)),
@@ -152,7 +160,7 @@
         self.maxDiff = None
         self._index_canned_bundle(self.old_bundle)
         expected_hits = self._load_canned_result(self.old_bundle)
-        hits = self._get_all_hits()
+        hits = self._get_hits_no_scan()
         self.assertElasticsearchResultsEqual(expected_hits, hits)
 
     @mock.patch('http.client._MAXHEADERS', new=1000)  # https://stackoverflow.com/questions/23055378
```

The following patch can be used to inspect the hits which have a `hits._score` attribute set, and do not have a `hits._sort` value set. Note that comparison will fail here, and that its inefficient to not use scan.

**Comment by melainalegaspi** [comment]
@danielsotirhos to define reproduction.
