### ISSUE TITLE
Setup production instance of Azul for DCP/2

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2280]

**Comment by theathorn** [comment]
DCP/1 will be shutdown by CZI by 12/31/20.

We should setup the DCP/2 production instance soon, so that the environment is available/tested, with the prod data to follow.

The Broad is asking what data/snapshot they should initially setup in the TDR prod instance?
This could be a throwaway dataset used just to test the prod environment.

**Comment by hannes-ucsc** [comment]
I don't think there's much value in trying to save space or compute by using a small staging area. We have high confidence in the staging area with the DCP/1 primary bundles so why not save time and start with that?

**Comment by hannes-ucsc** [comment]
Things left to do and create tickets for:

- Many tests depend on AZUL_DSS_ENDPOINT (https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/3)

**Comment by hannes-ucsc** [comment]
https://service.azul.data.humancellatlas.org/
https://gitlab.azul.data.humancellatlas.org/
