### ISSUE TITLE
Install build controller aka operator

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2284]
Derived from retrospective and to be implemented in the future. A couple options to explore this further: produce a checklist or Hannes to demo his process and/or coach whoever assumes this role. 

Potential candidates for role: Abraham, Daniel, Amar

**Roster sequence: Amar, Abraham, Daniel, Jesse, Noah**

**Comment by amarjandu** [comment]
Operator manual has been added to https://github.com/DataBiosphere/azul/wiki/Operator-Manual 
Please add or change as needed.

**Comment by jessebrennan** [comment]
This was assigned to me when I was operator. I'm not sure what purpose it serves at this point. I think we should close this ticket. I moved back to triage so we can evaluate.

**Comment by theathorn** [comment]
@hannes-ucsc "assignee to create documentation".

**Comment by theathorn** [comment]
@hannes-ucsc "Close after everyone has been operator at least once".

**Comment by noah-aviel-dove** [comment]
I've been operator for a few days now, think we can close this now.

**Comment by theathorn** [comment]
Assigned so far:

- Amar - 4
- Abraham - 3
- Noah - 2
- Jesse - 2
- Daniel - 3

New sequence: Jesse, Noah, Jesse, Noah, Abraham, Daniel, <sequence from description>.

**Comment by melainalegaspi** [comment]
Team Boardwalk calendar has been updated according to the new and continued sequence: https://calendar.google.com/calendar/embed?src=ucsc.edu_04ngru5t340tigtqnjad96nc9k%40group.calendar.google.com&ctz=America%2FLos_Angeles
