### ISSUE TITLE
Velocity report action cannot update existing report on Gitlab

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/azul#2294]
Manually requesting a report will not update a report for the same date already published to Gitlab. Instead, it will fail silently.

**Comment by natanlao** [comment]
On reconsideration, this can be accomplished by first deleting the page on Gitlab then triggering report generation.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Check if #2458 resolves this automatically."

**Comment by natanlao** [comment]
Will be resolved by #2458
