### ISSUE TITLE
Retire /dss/files and /fetch/dss/files

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2311]
- [x] Resolve all FIXME's that refer to this issue
- [x] [~Add a unit test to cover `azul.plugins.repository.tdr.Plugin.file_download_class` similar to how `test_dss_proxy` covers `azul.plugins.repository.dss.Plugin.file_download_class`.~ #2610](https://github.com/DataBiosphere/azul/issues/2610)  Convert `test_dss_proxy` to use `/fetch/repository/files`. (Re)name the two test modules and the test cases therein to be consistent with each other.
- [x] Adjust the `lambdas.service.app.ServiceApp.file_url` method to point at the new endpoint.

**Comment by hannes-ucsc** [comment]
The blocker is invalid: https://github.com/HumanCellAtlas/data-browser/issues/1340#issuecomment-702269107

**Comment by achave11** [comment]
@hannes-ucsc: "Coverage of the TDR plugging, will be more difficult than I originally thought. Will be extracting that into a separe ticket and down scope this ticket."

**Comment by achave11** [comment]
Separe ticket is https://github.com/DataBiosphere/azul/issues/2610
