### ISSUE TITLE
Security vulnerability in urllib3

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2324]
https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1014645

**Comment by achave11** [comment]
@hannes-ucsc it seems like a [merged PR from Oct 22](https://github.com/DataBiosphere/azul/commit/e4a00ea6242dc199770db7253ba3f362e16afa14) contains a compliant `urllib3` version of  "1.25.9 or higher". Should `urllib3` be updated to the latest version, which is 1.26.2 ?

**Comment by hannes-ucsc** [comment]
Nah, I probably just forgot to link that PR to this ticket.

**Comment by hannes-ucsc** [comment]
Thanks for tracking this down.
