### ISSUE TITLE
Check dcp2ebi catalog for schema violations

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2327]
The fix for schema validation on descriptors has failed to deploy, so the most recent dcp2ebi snapshot (#2319) was created without that in place. EBI has indicated that the schema violations were addressed but since the validation was in place at import time, we should check for those manually.

To smoke test the violation fixes, find files with uppercase characters in checksums and versions with more or less than six digits in the fractional seconds field.

**Comment by noah-aviel-dove** [comment]
No violations found. 
```
$ python3 my-scripts/check_tdr_bq_schema.py dcp2ebi
2020-10-06 14:48:22,700 INFO    MainThread: catalog = 'dcp2ebi', dataset = 'hca_dev_20201001_ebi17v3_20201002'
2020-10-06 14:48:22,710 INFO    MainThread: Found credentials in environment variables.
2020-10-06 14:48:25,801 INFO    MainThread: All good!
```
[Here's my checker script](https://github.com/DataBiosphere/azul/blob/issues/noah-aviel-dove/2327-dcp2ebi-schema-violations-no-pr/my-scripts/check_tdr_bq_schema.py). Feel free to delete the branch once you're satisfied since I wn't be filing a PR.

**Comment by hannes-ucsc** [comment]
Looks good. Please delete the branch, thanks.

**Comment by theathorn** [comment]
@hannes-ucsc "Did you delete the branch?"

**Comment by noah-aviel-dove** [comment]
> @hannes-ucsc "Did you delete the branch?"

Yes. This could have easily been verified by trying to follow the link in my first comment.

**Comment by hannes-ucsc** [comment]
> This could have easily been verified by trying to follow the link in my first comment.

That's a bit cheeky, just like your original assertion that I should have deleted your branch for you.

**Comment by noah-aviel-dove** [comment]
> > This could have easily been verified by trying to follow the link in my first comment.
> 
> That's a bit cheeky, just like your original assertion that I should delete your branch for you.

Apologies, I'll monitor my tone more closely in the future.

**Comment by hannes-ucsc** [comment]
Your tone was fine.
