### ISSUE TITLE
Version of pip used by build ignores wheel for gevent

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2332]
For example:

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/6702#L350

```
Running setup.py bdist_wheel for gevent: started
Running setup.py bdist_wheel for gevent: still running...
Running setup.py bdist_wheel for gevent: still running...
Running setup.py bdist_wheel for gevent: finished with status 'done'
```

The "still running" messages indicate that it's taking a couple of minutes to build the wheel.

Ideally we should be using a ~base image~ pip version ~for which pypy has~ that uses the wheel for gevent ~and other packages~.

Not only does this affect Gitlab builds, it also slows down `make requirements_update`, where it's actually affecting productivity.

**Comment by hannes-ucsc** [comment]
https://github.com/docker-library/docs/issues/904

**Comment by hannes-ucsc** [comment]
It isn't the image that causes the gevent wheel to be built from source. It's the fact that gevent uses the manylinux2010 tag for its wheel combined with the fact that the ancient pip version 10.0.1 that we use doesn't recognize that tag.

Image build times and wheels built from source per pip version:

| pip version | build time | wheels built from soutce                                                                                                                                                                                    |
| ----------- | ---------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 10.0.1      | 3m05       | chalice gevent moto pygithub pyyaml requirements-parser strict-rfc3339 watchdog tinyquery arrow jsondiff pathtools ply pyrsistent aws-requests-auth future hca-metadata-api jmespath jsonobject bagit wrapt |
| 19.2.3      | 1m20       | chalice moto pygithub pyyaml requirements-parser strict-rfc3339 watchdog tinyquery arrow jsondiff pathtools ply pyrsistent aws-requests-auth future hca-metadata-api jmespath jsonobject bagit wrapt        |
| 20.2.3      | 1m24       | chalice moto pygithub pyyaml requirements-parser strict-rfc3339 watchdog tinyquery arrow jsondiff pathtools ply pyrsistent aws-requests-auth future hca-metadata-api jmespath jsonobject bagit wrapt        |

I'll rephrase the issue description and title.
