### ISSUE TITLE
Reindex job log exceeds Gitlab limit

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2337]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/6603

![image](https://user-images.githubusercontent.com/5143256/95481112-7d05fa00-0941-11eb-9544-0fe4fb3f2867.png)

**Comment by amarjandu** [comment]
Based on this document https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section 
we would need to set the `output_limit` in the `[[runners]]` section of the configuration file. 

```
[[runners]]
output_limit = 8192
```

The location of the configuration file changes based on the OS and User that is used when the Runner is executed.

-  /etc/gitlab-runner/config.toml on *nix systems when GitLab Runner is executed as root (this is also path for service configuration)
- ~/.gitlab-runner/config.toml on *nix systems when GitLab Runner is executed as non-root
- ./config.toml on other systems 

The changes should be picked up 5 min after the file has been saved.

**Comment by hannes-ucsc** [comment]
Thank you. I'll make the change.

**Comment by hannes-ucsc** [comment]
https://console.aws.amazon.com/codesuite/codecommit/repositories/azul-gitlab-config/commit/d454b3f01d6d9a617f153c569b8efaae65d780c1?region=us-east-1

**Comment by hannes-ucsc** [comment]
For demo, show that a reindex log on `dev` is NOT truncated anymore.

**Comment by amarjandu** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/7067
