### ISSUE TITLE
Verify that the hand-off to Terra for selected project contains only single-ended data

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2358]
Project: [Single-cell RNA-seq analysis of human pancreas from healthy individuals and type 2 diabetes patients](https://dev.singlecell.gi.ucsc.edu/explore/projects/ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad)

Data Browser shows "Paired End = false" for everything in this project.

[Slack thread](https://app.slack.com/client/T2EQJFTMJ/C01360XN04S/thread/C01360XN04S-1602864014.127900) claims the hand-off to Terra contains Paired End data.

Can we inspect the Terra hand-off manifest and verify it's correctness in this regard?

**Comment by theathorn** [comment]
EBI claiming this is caused by the presence of some "__fastq_read2_drs_url" entries in the hand-off manifest.

**Comment by hannes-ucsc** [comment]
Can't reproduce

https://humancellatlas.slack.com/archives/C01360XN04S/p1602883907131100?thread_ts=1602864014.127900&cid=C01360XN04S
