### ISSUE TITLE
Terra UI crashes when trying to display null values imported from PFBs from Azul

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2370]
Terra ticket tracking this work: https://broadworkbench.atlassian.net/browse/AS-521

**Comment by jessebrennan** [comment]
A work around for Azul would be to simply use an empty string whenever there is a null value.

**Comment by theathorn** [comment]
[AS-521](https://broadworkbench.atlassian.net/browse/AS-521) has been marked as "Done" and released to "Staging".

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "In lieu of a reproduction, we cannot verify the resolution. We trust upstream's word on it."
