### ISSUE TITLE
Allow mappings in openapi.schema.enum

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2375]
This ticket was created to track the status of a TODO that was added in #1465 .
The TODO is allow for looser `isinstance` checks on parameters that are passed to schema.enum.

**Comment by amarjandu** [comment]
This ticket was created by request https://github.com/DataBiosphere/azul/pull/1849#discussion_r508862816

**Comment by theathorn** [comment]
@amarjandu to provide a concise description of what needs to be done.

**Comment by amarjandu** [comment]
@hannes-ucsc "There must have been a misunderstanding, schema.enum should only get iterables, never mappings."
