### ISSUE TITLE
Travis builds are queueing for a long time

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/azul#2379]
PR builds are sitting in the Travis build queue for a long time, sometimes hours. Migrating from travis-ci.org to travis-ci.com may alleviate longer-than-usual build times. (https://travis-ci.community/t/builds-hang-in-queued-state/10250/6)

**Comment by natanlao** [comment]
Findings:

* [Travis announcement](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom) says that travis-ci.org will be shut down on 31 Dec 2020

* [Travis CI staff member implies, but does not say explicitly,](https://travis-ci.community/t/builds-hang-in-queued-state/10250/6) that migrating repositories from travis-ci.org to travis-ci.com will alleviate long build times

* [Travis documentation outlines](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) a migration process that is still in beta (!)

* [User reports indicate](https://travis-ci.community/t/will-builds-logs-be-migrated-upon-org-com-migration/7906) that while build history is migrated with the migration tool, builds logs may not be migrated.

Recommendations:

* Migrate to travis-ci.com now. Though impact on build times is unclear, the migration may need to occur anyway, and migrating early would allow us to identify and resolve migration issues on our own terms before travis-ci.org is shut down. This can likely be accomplished with no code changes.

Alternatively, migrate to another CI platform entirely. In either case, it is unclear whether build logs can be retained (if they need to be). Keeping travis-ci.org is not a realistic long-term option as it will no longer be possible past the end of 2020.

**Comment by natanlao** [comment]
Hannes advises that I should proceed with migration. We may consider moving to Gitlab entirely if the migration is problematic.

**Comment by natanlao** [comment]
Scope revised: verify that all repositories in the Orange workspace have been migrated.

**Comment by natanlao** [comment]
There are twelve repositories tracked in the Orange ZenHub workspace. Of those twelve, two repositories use Travis but are not migrated to travis-ci.com:
* HumanCellAtlas/dcp-cli
* HumanCellAtlas/metadata-schema

Of those twelve, two repositories are not migrated to travis-ci.com, but do not currently use Travis services:
* HumanCellAtlas/data-portal
* DataBiosphere/cloud-billing-report

**Comment by natanlao** [comment]
Migration complete for:

* HumanCellAtlas/dcp-cli
* HumanCellAtlas/metadata-schema
* HumanCellAtlas/data-portal

Not migrated:

* ucsc-cgp/cloud-billing-report (does not, and likely will not, use Travis)

**Comment by hannes-ucsc** [comment]
Looks good.
