### ISSUE TITLE
Use dynamic length prefix in integration tests

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2380]
Modify integration test's `_prepare_notifications()` so that it not only removes random bundles from the selection if the count is more than desired, but also incrementally removes characters from the bundle prefix to obtain more bundles if the count is less than desired.

**Comment by hannes-ucsc** [comment]
Freebie of https://github.com/DataBiosphere/azul/pull/2645

**Comment by hannes-ucsc** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/8556 made this necessary.

**Comment by theathorn** [comment]
For demo, show build logs on GitLab.

**Comment by hannes-ucsc** [comment]
Demo: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/9015#L446
