### ISSUE TITLE
Improve performance of bulk download

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2386]
Evaluate current "curl" performance with a large (terabytes) quantity of data and investigate potential improvements.
Suggestions from the DCP Demo Meeting included using multiple threads and/or "wget".

**Comment by theathorn** [comment]
I'm getting about 8MB/s download speed using my home network.

**Comment by hannes-ucsc** [comment]
Speculative, ill-defined, not reproducible.
