### ISSUE TITLE
Use gitlab for dev deployments

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#239]
See https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/77

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-166)
┆Project Name: azul
┆Issue Number: AZUL-166
┆Epic: Production Ready Indexer/Web Service/Browser

**Comment by theathorn** [comment]
For indexer and web service.

**Comment by alex-hancock** [comment]
Possibly extend to cover the data browser too and for the portal

Config for gitlab in our project
Possibly makefile (or just the GitLab yml file - Hannes preferred) target to deploy to staging/integration
(runs more fine-grained targets defined at the end of README)

last step: script is triggered by a push to the respective branch (check out integration, merge develop, resolve conflicts, git push those changes)

DOD: there should be one plan that checks out the main branch runs make terraform and make deploy (deploy to dev)

there should be a plan to promote from dev to integration, integration to staging, and from staging to production

Coordinate with Dave to avoid duplication of work (with data-browser and data-portal)
