### ISSUE TITLE
Protect against invalid or harmful file paths in `curl` manifest

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2398]
The curl manifest is essentially a list of signed URLs to files in TDR's GCS bucket. When the signed URLs were created, the file's original relative file path as provided by the submitter, is baked into the URL such that GCS, when responding to a request for that URL, returns a Content-Disposition header that suggests to the client (curl in this case) to use that particular file path when storing the response locally on disk. Depending on the user's operating system, curl may fail to store the file at the path suggested by the system.

We should transliterate the file path before they are baked into the URL such that they work on all systems.

First, spike to see how curl on Windows, Unix and macOS handles file paths with forward slashes in them.

Ideally, curl should create the necessary subdirectory on the fly, even on Windows.

Assuming that this is the case, the transliteration would be

1) Fail if characters `\x00` to `\x1F` or `\` (backslash) occur in file paths.

2) Translate the following characters in the file path to `_` (underscore)

   - `<` (less than)
   - `>` (greater than)
   - `:` (colon)
   - `"` (double quote)
   - `|` (vertical bar or pipe)
   - `?` (question mark)
   - `*` (asterisk)

3) Fail if the file path does not match the regex `^(\.?[^./ ])([^/]*[^./ ])?(/(\.?[^./ ])([^/]*[^./ ])?)*$`

4) Fail if any component in the file path is `CON`, `PRN`, `AUX`, `NUL`, `COM1`, `COM2`, `COM3`, `COM4`, `COM5`, `COM6`, `COM7`, `COM8`, `COM9`, `LPT1`, `LPT2`, `LPT3`, `LPT4`, `LPT5`, `LPT6`, `LPT7`, `LPT8`, or `LPT9`. A component is any element of the result of `path.split('/')`

References: 

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names

**Comment by achave11** [comment]
Spike:

* Windows 10 build 17063+, curl 7.55.1; creates full file path if filename contains a forward slash.
* Unix Ubuntu 18.04, curl 7.58.0; creates full file path if filename contains a forward slash.
* macOS 10.15.6. curl 7.64.1;  creates full file path if filename contains a forward slash.
