### ISSUE TITLE
New pricing model for travis-ci.com

### ISSUE THREAD

**Issue by natanlao** [DataBiosphere/azul#2401]
Effective 2 Nov 2020, [Travis pricing is changing](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). Relevant excerpt:

> * For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> * We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.
>
> Beginning on Monday the 2nd of November 2020, customers impacted by pricing changes listed above will be gradually upgraded to the new pricing scheme upon their plan expiration date.

Without having access to Azul usage data, it is likely that we will be impacted by this change. 1000 minutes affords us about 50 twenty-minute builds in a month.

**Comment by jessebrennan** [comment]
I was looking into this this morning, and have some thoughts.

* We could speed up our builds to fit the new pricing model. This would have the added benefit of faster builds ;)
  - Lots of build time is spent waiting for docker containers and indexing documents into Elasticsearch.
  - We aren't using parallelization from pytest either, which could speed things up.
* Find another CI system that's free for open source. I just learned of https://cloud.drone.io/

**Comment by natanlao** [comment]
Found stats on our usage: https://travis-ci.org/github/DataBiosphere?tab=insights

**Comment by melainalegaspi** [comment]
Communicate with Nadine in order to subscribe to the $249 plan with 5 concurrent builds.

**Comment by natanlao** [comment]
Change plan here: https://travis-ci.com/organizations/DataBiosphere/plan

**Comment by natanlao** [comment]
@majomart will take it from here, act as the billing contact, and notify if anything else is needed.

**Comment by theathorn** [comment]
Purchase complete - closing.
