### ISSUE TITLE
Two files of the same name in manifest overwrite each other

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2403]

**Comment by melainalegaspi** [comment]
Spike to determine if curl can be prevented from clobbering existing files.

**Comment by danielsotirhos** [comment]
This feature is listed in `curl`'s current TODO list: https://curl.se/docs/todo.html#prevent_file_overwriting

> Add an option that prevents curl from overwriting existing local files. When used, and there already is an existing file with the target file name (either -O or -o), a number should be appended (and increased if already existing). So that index.html becomes first index.html.1 and then index.html.2 etc.

The only current `curl` ability we could use is to use the option `-J, --remote-header-name` in conjunction with `-O, --remote-name`, however this (1) gets the filename from the server-specified Content-Disposition filename which  Azul does not currently provide, and (2) `curl` will error if the filename to save as already exists locally.

**Comment by danielsotirhos** [comment]
Example of multiple files within 1 project all with the same filename:
https://dev.singlecell.gi.ucsc.edu/explore/files?catalog=dcp1&filter=%5B%7B%22facetName%22:%22fileFormat%22,%22terms%22:%5B%22csv.gz%22%5D%7D,%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%22c4077b3c-5c98-4d26-a614-246d12c2e5d7%22%5D%7D%5D

![Screen Shot 2020-12-16 at 11 02 28 AM](https://user-images.githubusercontent.com/46407464/102394265-593ce100-3f8e-11eb-9f5c-06919b658420.png)

**Comment by danielsotirhos** [comment]
To prevent these files from being overwritten when downloading with a curl-format manifest it is necessary to modify the file name and/or path of the file when listed in the curl-format manifest.

Unfortunately, it seems the best solution is to always use each file's bundle UUID as a folder to hold the file. This will (1) ensure different files with the same name are not overwritten, (2) not downloaded multiple copies of the same file to different local files, and (3) allow Idempotence by not downloading a file to a different folder regardless of the filter used to generate the manifest.
