### ISSUE TITLE
Add to TestManifestResponse to cover missing aspects

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2414]
(From https://github.com/DataBiosphere/azul/pull/2390#discussion_r516402386)
`TestManifestResponse` currently verifies the `/fetch/manifest/files` response using a mocked `get_cached_manifest`, and does not verify the `/manifest/files` response.

Add test cases to `TesstManifestResponse` so that both `/fetch/manifest/files` and `/manifest/files` responses are verified,
 and that the cache-miss path of `handle_manifest_generation_request` is covered for both endpoints as well.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Do not understand description, discuss."

**Comment by theathorn** [comment]
Hannes to re-evaluate after Daniel's edit.

**Comment by hannes-ucsc** [comment]
The description is not well written. I had to read my original review comment to understand what this is about.

Clearly state what the problem is in the description. Then specify the solution. In this case it would be acceptable to include the solution in the description (as opposed to a separate comment) but the problem and the solution should be distinguishable.

**Comment by hannes-ucsc** [comment]
Description looks good.

**Comment by achave11** [comment]
@hannes-ucsc: '
- [x] cache-miss is already covered by `TestManifestController`, 
- [ ] coverage of manifest/files should be added to `TestManifestResponse.test_fetch_manifest`, 
- [ ] that method should be renamed to `test_manifest` and 
- [ ] TestManifestController should be extended to [cover the case where the objectKey request parameter is present](https://codecov.io/gh/DataBiosphere/azul/src/7d3edbe890f8b47939571b547cc2cab20cf18f65/src/azul/service/manifest_controller.py#L94)'

**Comment by hannes-ucsc** [comment]
For demo, show coverage gain in Codecov or Coveralls.
