### ISSUE TITLE
Integration test should retry 500+ status codes

### ISSUE THREAD

**Issue by alex-hancock** [DataBiosphere/azul#242]
DCP Integration's Azul Agent failed [this job](https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/dcp/-/jobs/4958) due to a 502 response on the webservice request. The Python requests library contains logic to retry 500+ codes, and we should find and use that logic.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-168)
┆Project Name: azul
┆Issue Number: AZUL-168

**Comment by alex-hancock** [comment]
```http.request('GET', 'http://example.com/', retries=Retry(10))```

**Comment by alex-hancock** [comment]
@hannes-ucsc pushed these changes to the #217 pull request. There's no evidence that they will successfully retry 500 errors unless we introduce one, so I'm leaving it to your discretion.

**Comment by hannes-ucsc** [comment]
Resolved by https://github.com/HumanCellAtlas/dcp/commit/5f773abe8b51bd79c08106b1466be4abdfaf8550
