### ISSUE TITLE
TDR plugin unit tests conflate entity UUID with file_id

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2426]
Currently, the TDR plugin unit tests re-uses entity UUIDs as the `file_id` attribute when creating descriptors for the mocked TDR tables. This makes it impossible to tell whether the Plugin is erroneously making the same conflation.

Suggested solution: generate random `file_id`'s when creating the canned TDR bundle.

**Comment by hannes-ucsc** [comment]
Freebie of #2374.
