### ISSUE TITLE
500 errors from TDR's DRS endpoints

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2429]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/7364

**Comment by theathorn** [comment]
From Nicolas Malfroy-Camine: "Hi Hannes, we had an upgrade migration issue on our end in TDR that should now be resolved".

**Comment by hannes-ucsc** [comment]
I need to back out the work-around.

**Comment by hannes-ucsc** [comment]
Or the workaround needs to be backed out.

**Comment by hannes-ucsc** [comment]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/7467
