### ISSUE TITLE
Loom files from analysis subgraphs are shown as unknown

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2446]
![image](https://user-images.githubusercontent.com/5143256/98700651-46027a00-232d-11eb-845e-0e95fcbb3211.png)
![image](https://user-images.githubusercontent.com/5143256/98703495-66800380-2330-11eb-8f1e-4881b7079e89.png)

**Comment by jessebrennan** [comment]
@hannes-ucsc, "Check corresponding metadata to see it it's "unknown" there. If it is, then contact analysis team. Otherwise this is our bug."

**Comment by noah-aviel-dove** [comment]
Not our bug. The file format is specified as "unknown" in TDR.

```
SELECT
  JSON_EXTRACT_SCALAR(content, '$.file_core.format') AS file_format,
  JSON_EXTRACT_SCALAR(descriptor, '$.content_type') AS content_type
FROM hca_dev_20200819___20201105_optimusb.analysis_file
WHERE ENDS_WITH(JSON_EXTRACT_SCALAR(descriptor, '$.file_name'), '.loom')
```

```
Row | file_format | content_type
-- | -- | --
1 | unknown | application/unknown |  
2 | unknown | application/unknown |  
3 | unknown | application/unknown |  
4 | unknown | application/unknown |  
5 | unknown | application/unknown |


```

**Comment by hannes-ucsc** [comment]
The `file_format` property should be `loom` and `content_description` should be something like 

```json
{
    "text": "Matrix",
    "ontology": "data:2082",
    "ontology_label": "Matrix"
}
```

or preferably a more concrete subclass of that. 

See http://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Fdata_2082

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "@noah-aviel-dove, did you contact anyone about this bug?"

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc Yes, https://humancellatlas.slack.com/archives/C01360XN04S/p1605058720419400

**Comment by noah-aviel-dove** [comment]
Next step: check snapshot `hca_dev_20201023_ebiv4___20201121` once it is indexed in `dcp2ebi`

**Comment by noah-aviel-dove** [comment]
Snapshot still has not been indexed.

**Comment by noah-aviel-dove** [comment]
Snapshot now indexed.

**Comment by noah-aviel-dove** [comment]
Not seeing any change in TDR or the browser.

```
SELECT DISTINCT 
  JSON_EXTRACT_SCALAR(content, '$.file_core.format') AS file_format,
  JSON_EXTRACT_SCALAR(descriptor, '$.content_type') AS content_type
FROM hca_dev_20201023_ebiv4___20201121.analysis_file
WHERE ENDS_WITH(JSON_EXTRACT_SCALAR(descriptor, '$.file_name'), '.loom')

Row | file_format | content_type
-- | -- | --
1 | unknown | application/unknown
```

Filtering by file format in catalog DCP2EBI (dev browser) shows an option for "unknown" but none for "loom". Selecting unknown shows 22 loom files.

**Comment by noah-aviel-dove** [comment]
Jessica Way: "The snapshot has not been made since we did not have all the files needed to do the import. We cannot import the files until we have all the adapter files needed"

**Comment by noah-aviel-dove** [comment]
Appears fixed on snapshot `hca_dev_20201217_test4___20210107`:
![Screenshot from 2021-01-12 13-15-14](https://user-images.githubusercontent.com/48401926/104375513-56bf9f80-54d8-11eb-95d6-7c57dda0fb7e.png)
![Screenshot from 2021-01-12 13-14-58](https://user-images.githubusercontent.com/48401926/104375525-5a532680-54d8-11eb-96be-571449708aef.png)
