### ISSUE TITLE
Migrate personal deployments to new Google project and SAM group

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2447]
Migrate personal deployments from `human-cell-atlas-travis-test` to `platform-hca-dev` and to `azul-dev` SAM group.

**Comment by hannes-ucsc** [comment]
Blocker is in `dev` so people can go ahead and do this.

Slack [notification] went out.

**Comment by amarjandu** [comment]
Checkbox once you have finished migrating to the new Google project: 
- [ ] achave11
- [x] amarjandu
- [ ] danielsortirhos
- [ ] jessebrennan
- [ ] noah-aviel-dove

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"All personal deployments have been upgraded and human-cell-atlas-travis-test project has been deleted."
