### ISSUE TITLE
Full manifest fails to generate for large requests

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2452]
Can reproduce on dev by trying to generate this manifest:
https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?catalog=dcp1&filters=%7B%22fileFormat%22%3A%7B%22is%22%3A%5B%22matrix%22%5D%7D%7D%0A&format=full

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">@timestamp</th>
<th title="Field #2">@message</th>
</tr></thead>
<tbody><tr>
<td>2020-11-11 01:44:44.764</td>
<td>END RequestId: 3478faf7-012c-4da4-af56-61352aef3803<br/></td>
</tr>
<tr>
<td>2020-11-11 01:44:44.764</td>
<td>REPORT RequestId: 3478faf7-012c-4da4-af56-61352aef3803	Duration: 60530.69 ms	Billed Duration: 60600 ms	Memory Size: 1024 MB	Max Memory Used: 123 MB	Init Duration: 1987.06 ms	<br/></td>
</tr>
<tr>
<td>2020-11-11 01:44:44.762</td>
<td>[WARNING]	2020-11-11T01:44:44.753Z	3478faf7-012c-4da4-af56-61352aef3803	Upload vlcba6CUr0InlJvPmPBnBusFYkXeZsTjMTIyerbtiAG3CK3PXIf3SH8i_V26lT1lPbxb3ZPPF3lhrqG4TzpWKHKm30zv9waa2W0S790HVbxcR49gY38QuZ6pTlsZD3U38s_PH7sDZhZQaDcvsyNYc6N3SvrMRETynkUAB8Xke6c-: Aborted<br/></td>
</tr>
<tr>
<td>2020-11-11 01:44:44.689</td>
<td>[ERROR]	2020-11-11T01:44:44.687Z	3478faf7-012c-4da4-af56-61352aef3803	Upload vlcba6CUr0InlJvPmPBnBusFYkXeZsTjMTIyerbtiAG3CK3PXIf3SH8i_V26lT1lPbxb3ZPPF3lhrqG4TzpWKHKm30zv9waa2W0S790HVbxcR49gY38QuZ6pTlsZD3U38s_PH7sDZhZQaDcvsyNYc6N3SvrMRETynkUAB8Xke6c-: Error detected within the MPU context.<br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 426, in _make_request<br/>    six.raise_from(e, None)<br/>  File &quot;&lt;string&gt;&quot;, line 3, in raise_from<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 421, in _make_request<br/>    httplib_response = conn.getresponse()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 1347, in getresponse<br/>    response.begin()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 307, in begin<br/>    version, status, reason = self._read_status()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 268, in _read_status<br/>    line = str(self.fp.readline(_MAXLINE + 1), &quot;iso-8859-1&quot;)<br/>  File &quot;/var/lang/lib/python3.8/socket.py&quot;, line 669, in readinto<br/>    return self._sock.recv_into(b)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1241, in recv_into<br/>    return self.read(nbytes, buffer)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1099, in read<br/>    return self._sslobj.read(len, buffer)<br/>socket.timeout: The read operation timed out<br/><br/>During handling of the above exception, another exception occurred:<br/><br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/requests/adapters.py&quot;, line 439, in send<br/>    resp = conn.urlopen(<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 724, in urlopen<br/>    retries = retries.increment(<br/>  File &quot;/opt/python/urllib3/util/retry.py&quot;, line 403, in increment<br/>    raise six.reraise(type(error), error, _stacktrace)<br/>  File &quot;/opt/python/urllib3/packages/six.py&quot;, line 735, in reraise<br/>    raise value<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 670, in urlopen<br/>    httplib_response = self._make_request(<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 428, in _make_request<br/>    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 335, in _raise_timeout<br/>    raise ReadTimeoutError(<br/>urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=&#39;search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com&#39;, port=443): Read timed out. (read timeout=60)<br/><br/>During handling of the above exception, another exception occurred:<br/><br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/elasticsearch/connection/http_requests.py&quot;, line 129, in perform_request<br/>    response = self.session.send(prepared_request, **send_kwargs)<br/>  File &quot;/opt/python/requests/sessions.py&quot;, line 646, in send<br/>    r = adapter.send(request, **kwargs)<br/>  File &quot;/opt/python/requests/adapters.py&quot;, line 529, in send<br/>    raise ReadTimeout(e, request=request)<br/>requests.exceptions.ReadTimeout: HTTPSConnectionPool(host=&#39;search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com&#39;, port=443): Read timed out. (read timeout=60)<br/><br/>During handling of the above exception, another exception occurred:<br/><br/>Traceback (most recent call last):<br/>  File &quot;/var/task/azul/service/manifest_service.py&quot;, line 279, in _generate_manifest<br/>    base_name = generator.write_to(text_buffer)<br/>  File &quot;/var/task/azul/service/manifest_service.py&quot;, line 770, in write_to<br/>    sources = list(self.manifest_config[&#39;contents&#39;].keys())<br/>  File &quot;/opt/python/boltons/cacheutils.py&quot;, line 610, in __get__<br/>    value = obj.__dict__[self.func.__name__] = self.func(obj)<br/>  File &quot;/var/task/azul/service/manifest_service.py&quot;, line 809, in manifest_config<br/>    response = es_search.execute()<br/>  File &quot;/opt/python/elasticsearch_dsl/search.py&quot;, line 702, in execute<br/>    es.search(<br/>  File &quot;/opt/python/elasticsearch/client/utils.py&quot;, line 84, in _wrapped<br/>    return func(*args, params=params, **kwargs)<br/>  File &quot;/opt/python/elasticsearch/client/__init__.py&quot;, line 851, in search<br/>    return self.transport.perform_request(<br/>  File &quot;/opt/python/elasticsearch/transport.py&quot;, line 351, in perform_request<br/>    status, headers_response, data = connection.perform_request(<br/>  File &quot;/opt/python/elasticsearch/connection/http_requests.py&quot;, line 144, in perform_request<br/>    raise ConnectionTimeout(&quot;TIMEOUT&quot;, str(e), e)<br/>elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeout(HTTPSConnectionPool(host=&#39;search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com&#39;, port=443): Read timed out. (read timeout=60))</td>
</tr>
<tr>
<td>2020-11-11 01:44:44.689</td>
<td>[INFO]	2020-11-11T01:44:44.689Z	3478faf7-012c-4da4-af56-61352aef3803	Upload vlcba6CUr0InlJvPmPBnBusFYkXeZsTjMTIyerbtiAG3CK3PXIf3SH8i_V26lT1lPbxb3ZPPF3lhrqG4TzpWKHKm30zv9waa2W0S790HVbxcR49gY38QuZ6pTlsZD3U38s_PH7sDZhZQaDcvsyNYc6N3SvrMRETynkUAB8Xke6c-: Aborting<br/></td>
</tr>
<tr>
<td>2020-11-11 01:44:44.687</td>
<td>[WARNING]	2020-11-11T01:44:44.682Z	3478faf7-012c-4da4-af56-61352aef3803	GET https://search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443/azul_v2_dev_dcp1_bundles_aggregate/_search [status:N/A request:60.050s]<br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 426, in _make_request<br/>    six.raise_from(e, None)<br/>  File &quot;&lt;string&gt;&quot;, line 3, in raise_from<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 421, in _make_request<br/>    httplib_response = conn.getresponse()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 1347, in getresponse<br/>    response.begin()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 307, in begin<br/>    version, status, reason = self._read_status()<br/>  File &quot;/var/lang/lib/python3.8/http/client.py&quot;, line 268, in _read_status<br/>    line = str(self.fp.readline(_MAXLINE + 1), &quot;iso-8859-1&quot;)<br/>  File &quot;/var/lang/lib/python3.8/socket.py&quot;, line 669, in readinto<br/>    return self._sock.recv_into(b)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1241, in recv_into<br/>    return self.read(nbytes, buffer)<br/>  File &quot;/var/lang/lib/python3.8/ssl.py&quot;, line 1099, in read<br/>    return self._sslobj.read(len, buffer)<br/>socket.timeout: The read operation timed out<br/><br/>During handling of the above exception, another exception occurred:<br/><br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/requests/adapters.py&quot;, line 439, in send<br/>    resp = conn.urlopen(<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 724, in urlopen<br/>    retries = retries.increment(<br/>  File &quot;/opt/python/urllib3/util/retry.py&quot;, line 403, in increment<br/>    raise six.reraise(type(error), error, _stacktrace)<br/>  File &quot;/opt/python/urllib3/packages/six.py&quot;, line 735, in reraise<br/>    raise value<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 670, in urlopen<br/>    httplib_response = self._make_request(<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 428, in _make_request<br/>    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)<br/>  File &quot;/opt/python/urllib3/connectionpool.py&quot;, line 335, in _raise_timeout<br/>    raise ReadTimeoutError(<br/>urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=&#39;search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com&#39;, port=443): Read timed out. (read timeout=60)<br/><br/>During handling of the above exception, another exception occurred:<br/><br/>Traceback (most recent call last):<br/>  File &quot;/opt/python/elasticsearch/connection/http_requests.py&quot;, line 129, in perform_request<br/>    response = self.session.send(prepared_request, **send_kwargs)<br/>  File &quot;/opt/python/requests/sessions.py&quot;, line 646, in send<br/>    r = adapter.send(request, **kwargs)<br/>  File &quot;/opt/python/requests/adapters.py&quot;, line 529, in send<br/>    raise ReadTimeout(e, request=request)<br/>requests.exceptions.ReadTimeout: HTTPSConnectionPool(host=&#39;search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com&#39;, port=443): Read timed out. (read timeout=60)</td>
</tr>
<tr>
<td>2020-11-11 01:43:44.631</td>
<td>[INFO]	2020-11-11T01:43:44.631Z	3478faf7-012c-4da4-af56-61352aef3803	Found credentials in environment variables.<br/></td>
</tr>
<tr>
<td>2020-11-11 01:43:44.606</td>
<td>[DEBUG]	2020-11-11T01:43:44.605Z	3478faf7-012c-4da4-af56-61352aef3803	Creating ES client [search-azul-index-dev-atlcgwfjbk6dvrtmiaskbs2swa.us-east-1.es.amazonaws.com:443]<br/></td>
</tr>
<tr>
<td>2020-11-11 01:43:44.443</td>
<td>[INFO]	2020-11-11T01:43:44.443Z	3478faf7-012c-4da4-af56-61352aef3803	Cached manifest not found: manifests/9a7fa6d1-e63e-5c24-86ce-df124dcd3b88.tsv<br/></td>
</tr>
<tr>
<td>2020-11-11 01:43:44.247</td>
<td>[INFO]	2020-11-11T01:43:44.247Z	3478faf7-012c-4da4-af56-61352aef3803	Found credentials in environment variables.<br/></td>
</tr>
<tr>
<td>2020-11-11 01:43:44.232</td>
<td>START RequestId: 3478faf7-012c-4da4-af56-61352aef3803 Version: $LATEST<br/></td>
</tr>
</tbody></table>

**Comment by theathorn** [comment]
@hannes-ucsc "1. Try to reproduce locally and 2. Determine if we can reduce the size of the response so it doesn't take as long".

**Comment by hannes-ucsc** [comment]
"Locally" means selecting `dev` and using `make local` or instantiating ManifestService in a little throw-away Python script.

**Comment by melainalegaspi** [comment]
@hannes-ucsc "Can be reproduced locally according to @achave11 , but size can't be reduced. Instead we'll partition the query that populates the header fields. "

**Comment by hannes-ucsc** [comment]
I cannot repro with the URL in the description. But I can with this one.

https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?catalog=dcp1&filters=%7B%7D&format=full

**Comment by hannes-ucsc** [comment]
The fix from PR #2473 [does not work](https://github.com/DataBiosphere/azul/pull/2473#issuecomment-745876620) and was reverted.

**Comment by hannes-ucsc** [comment]
Bumping estimate to reflect scope creep with additional experiments.

**Comment by hannes-ucsc** [comment]
Can still repro on prod

```
$ curl 'https://service.azul.data.humancellatlas.org/fetch/manifest/files?catalog=dcp1&filters=%7B%22fileFormat%22%3A%7B%22is%22%3A%5B%22matrix%22%5D%7D%7D&format=full'
{"Status":301,"Location":"https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMzg1ZDk5ZWItZDJhYy00YTYxLWIzNzEtZTc5YjFiZjE5MjFiIiwgInJlcXVlc3RfaW5kZXgiOiAxfQ%3D%3D","CommandLine":{},"Retry-After":1}
$ curl 'https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMzg1ZDk5ZWItZDJhYy00YTYxLWIzNzEtZTc5YjFiZjE5MjFiIiwgInJlcXVlc3RfaW5kZXgiOiAxfQ%3D%3D'
{"Status":301,"Location":"https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMzg1ZDk5ZWItZDJhYy00YTYxLWIzNzEtZTc5YjFiZjE5MjFiIiwgInJlcXVlc3RfaW5kZXgiOiAyfQ%3D%3D","CommandLine":{},"Retry-After":1}
$ curl 'https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMzg1ZDk5ZWItZDJhYy00YTYxLWIzNzEtZTc5YjFiZjE5MjFiIiwgInJlcXVlc3RfaW5kZXgiOiAyfQ%3D%3D'
{"Status":301,"Location":"https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMzg1ZDk5ZWItZDJhYy00YTYxLWIzNzEtZTc5YjFiZjE5MjFiIiwgInJlcXVlc3RfaW5kZXgiOiAzfQ%3D%3D","CommandLine":{},"Retry-After":4}
$ curl 'https://service.azul.data.humancellatlas.org/fetch/manifest/files?token=eyJleGVjdXRpb25faWQiOiAiMzg1ZDk5ZWItZDJhYy00YTYxLWIzNzEtZTc5YjFiZjE5MjFiIiwgInJlcXVlc3RfaW5kZXgiOiAyfQ%3D%3D'
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 1135, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 1465, in start_manifest_generation_fetch
    wait_time, manifest = handle_manifest_generation_request()
  File "/var/task/app.py", line 1504, in handle_manifest_generation_request
    return async_service.start_or_inspect_manifest_generation(app.self_url(),
  File "/var/task/azul/service/async_manifest_service.py", line 92, in start_or_inspect_manifest_generation
    time_or_manifest = self._get_manifest_status(token['execution_id'], request_index)
  File "/var/task/azul/service/async_manifest_service.py", line 154, in _get_manifest_status
    raise StateMachineError(status, output)
azul.service.step_function_helper.StateMachineError: ('Failed to generate manifest', 'FAILED', None)
```

**Comment by hannes-ucsc** [comment]
To repro on your personal deployment use snapshot `hca_dev_20201203___20201210` as on develop in commit cddaee92100980927f73b1607d96230306471b4d without prefix and an indexer concurrency of 64. Ping me before actually reindexing so I can purchase slot commitment for BQ and ping me after, too, so I can delete the commitment again.

**Comment by achave11** [comment]
Experiments to diagnose the problem and assist with devising a potential solution:
1.  Using `ThreadPoolExec` execute ES-request sequentially (one worker) and after each request, sleep for 60 seconds. Note time consumed by each request.
2. Using `ThreadPoolExec` execute ES-request sequentially (one worker), note time consumed by each request.
3. Tune number of workers to optimize ES-request execution time per thread. Note times.
4. Increase execution timeout for ES-requests.
