### ISSUE TITLE
ES returns too many headers during bundle deletion

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2455]
When a bundle is deleted within ElasticSearch there can be over 100 headers that are send with the request from the ElasticSearch client. 

Following the advise from https://stackoverflow.com/a/38815673/2205587. There is a `mock.patch` that was added to the test where this occurs.
 https://github.com/DataBiosphere/azul/blob/1bfd4835410c42bde53f60f1007ad514396b4cc0/test/indexer/test_hca_indexer.py#L158 

By commenting out the `mock.patch`, its possible to see that the HTTP exception is raised for large bundles, and the smaller one is able to be deleted without raising exceptions. 
![Screen Shot 2020-11-12 at 11 12 33 AM](https://user-images.githubusercontent.com/1947534/98985164-07f58980-24d8-11eb-8416-a962f627a3fa.png)

The headers that are being sent with the deletion request should be investigated. Additionally it might be worthwhile to investigate if a large bundle is able to be deleted within an actual deployment, as there does not appear to be any modifications to the `http.client._MAXHEADERS` within the codebase.

**Comment by hannes-ucsc** [comment]
Spike to determine what headers are being sent.

**Comment by amarjandu** [comment]
For the sub_test above the headers that cause the alert are 
```
000 = {bytes: 105} b'Warning: 299 Elasticsearch-6.8.0-65b6179 "Deprecated field [_version] used, expected [version] instead"\r\n'
001 = {bytes: 115} b'Warning: 299 Elasticsearch-6.8.0-65b6179 "Deprecated field [_version_type] used, expected [version_type] instead"\r\n'

002 = {bytes: 323} b'Warning: 299 Elasticsearch-6.8.0-65b6179 "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [azul_v2_amar_test_files_...
```

The headers from 002 to 100 have the warning
```
b'Warning: 299 Elasticsearch-6.8.0-65b6179 "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [azul_v2_amar_test_files_aggregate], type [doc], id [d5294332-19b5-4ff1-b298-6c1cf500cb35])"\r\n'
`

**Comment by amarjandu** [comment]
headers were located by running sub_test with mocks removed, and a breakpoint set within `/Users/amar/.pyenv/versions/3.8.2/lib/python3.8/http/client.parse_headers`

**Comment by amarjandu** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/optimistic-concurrency-control.html

**Comment by amarjandu** [comment]
https://www.elastic.co/blog/elasticsearch-sequence-ids-6-0

**Comment by amarjandu** [comment]
unable to locate bundle `2a87dc5c-0c3c-4d91-a348-5d784ab48b92` in `dcp2` or `dcp` catalogs.

**Comment by hannes-ucsc** [comment]
Spike increased to cover analysis of how we would have to modify `Document.to_index`. But should really be time-boxed to eight hours. Don't go over that, @amarjandu .

**Comment by amarjandu** [comment]
It would appear that `_seq_no` and `primary_term` are always present in the responses there is nothing that indicates the value is conditionally returned in the response. 

https://www.elastic.co/guide/en/elasticsearch/reference/7.11/docs-get.html#docs-get-api-response-body
