### ISSUE TITLE
Release snapshot of all DCP/1 primary, analysis and project matrix data for MVP

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2459]
The hard deadline for CZI to shutdown the current DCP/1 environment is 12/31/20.
We need a contingency plan for the case of the new DCP/2 analysis outputs not being ready before then.
That plan is to copy all DCP/1 data to TDR in order to just replicate the data currently available in DCP/1.
Raaid will import data from the DCP/1 primary and DCP/1 secondary analysis staging buckets into a TDR prod dataset.
Daniel will provide metadata and data for the DCP/1 pre-generated project matrices in another staging bucket which will then be added to the TDR prod dataset and snapshotted.
Azul will index this snapshot in a prod DCP/1 Catalog and we'll verify the data looks identical to the current DCP/1 prod site.
We can then make a late call on publishing this setup in DCP/2 prod (~for now we will proceed with the full DCP/2 re-analysis plan~).

~We also need to replicate any S3 buckets containing non-DSS data (e.g. project-level matrices) into UCSC-controlled buckets.~

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "Waiting for TDR snapshot."

**Comment by theathorn** [comment]
See #2506.
