### ISSUE TITLE
Occasional KeyError on `/index/summary` endpoint

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2461]
Not sure of the steps to generate this, but I selected the DCP2 Catalog, file type as "unspecified" then clicked on something and got:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/def4dde7-ef15-4d2a-ae0d-72def27cc1d0)

**Comment by hannes-ucsc** [comment]
I don't think this is caused by what @theathorn was doing at the time but rather a random race condition. The summary endpoint runs three or so requests in parallel and that exposes a thread-safety issue with boto3 sessions: https://github.com/boto/boto3/issues/1592

**Comment by theathorn** [comment]
From @kbergin : Got this error when trying to do a handoff from dcp2.data.humancellatlas.org. I selected a project and clicked the export button and it gave me this error. I hit the back button then clicked it again and got the export selection page with no error.
