### ISSUE TITLE
Allow null values in PFBs 

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2462]
Remove the work around for #2370 when https://broadworkbench.atlassian.net/browse/AS-521 is fixed.

**Comment by hannes-ucsc** [comment]
I want to solve this, and thereby verify the upstream resolution, before we get deeper into the verbatim hand-over epic (#2693). In fact, I will add this to that epic.

**Comment by nadove-ucsc** [comment]
For demo, create and download a reasonably small PFB manifest using the Swagger UI. Confirm the presence of null values using `pfb show`. Then perform a handover to Terra via the Data Browser using the same set of filters. Confirm presence of null values in the workspace.
