### ISSUE TITLE
`curl` manifests for catalogs that use the DSS plugin exhaust curl's maximum # of redirects

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2470]
To reproduce, download a `curl` manifest against a catalog that uses the DSS repository plugin, say, `dcp1` at this moment in time.

When downloading the files in the manifest using the prescribed command line, one sees many 0 lines and sometimes a warning about a redirect limit being exceeded.

**Comment by hannes-ucsc** [comment]
`curl` does not support the Retry-After response header so we would need to include the `wait` parameter in the file URLs in the manifest, to throttle the redirect loop on the server side.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"DSS is soon to be end of life so we probably won't need to fix this."

**Comment by hannes-ucsc** [comment]
DSS is EOL
