### ISSUE TITLE
TDR gets confused by # in file names

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2475]
Potentially other characters, too

**Comment by theathorn** [comment]
Waiting for a TDR snapshot which has a fix to allow the # character.

**Comment by hannes-ucsc** [comment]
This appears to be fixed, at least in `prod`. I've removed the workaround and the IT isn't failing any more. I also had to add to add a [heuristic](https://github.com/databiosphere/azul/issues/2479#issuecomment-733410253) as a permanent workaround for unescaped `#` in gs:// URI returned by TDR's DRS endpoint.
