### ISSUE TITLE
Document all high-level procedures for all controls in the FedRAMP Spreadsheet

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2476]
https://docs.google.com/spreadsheets/d/1rwJPuoVRenRNpn_fDmXHeOG-qnaSu_0o-owy9-GEAA8/edit#gid=1533617571

@nolunwa add additional description

**Comment by theathorn** [comment]
Hannes to fill in Column I ("Procedure") on the 3rd tab ("AWS Shared/Customer Responsibility") with the high-level implementation plan.

**Comment by theathorn** [comment]
Need this before 1/7/21.

**Comment by hannes-ucsc** [comment]
1st and 2nd pass over the document are finished. It was counter-productive that a whole slew of controls was added between passes. Next time, we should settle on a set of controls first, before asking implementers for feedback. Many controls were assigned to me but are clearly non-technical, policy-only. I marked those with a comment.

**Comment by theathorn** [comment]
This task is complete and @nolunwa is creating individual control documents.
