### ISSUE TITLE
FedRAMP compliance

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2480]
[NIST SP 800-53 Rev. 4.0](https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/controls?version=4.0&security_baseline=Moderate).

[ FedRAMP_Security_Controls_Baseline for HCA Project](https://docs.google.com/spreadsheets/d/1rwJPuoVRenRNpn_fDmXHeOG-qnaSu_0o-owy9-GEAA8)

[Directory](https://drive.google.com/drive/u/0/folders/1oc1e6DIjLgONRxLjYbVzfk6wbb0yltjp) with HCA compliance docs.

[Directory](https://drive.google.com/drive/u/0/folders/17XlDfa7raxgbL0A_qc4M1GGbY-PWgpPV) with Dockstore compliance docs.

**Comment by hannes-ucsc** [comment]
Closing this super top level epic. The `compliance` label and columns serve the same purpose.
