### ISSUE TITLE
Files tab conflates contributor matrices and DCP2 matrices and intermediate matrices

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2491]

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Spike to see if this is actually an issue, and if it is come up with a solution."

**Comment by danielsotirhos** [comment]
Solution will be to add a `submitter` facet with a human-readable value. Currently the submitter id lookup table maps UUID to the name used to generate the UUID. Modify the lookup table to instead map to a tuple containing the name used to generate the UUID and a human-readable version to be used in the facet.

```
<    contributor_submitter_ids = {
<        'b7525d8e-8c7a-5fec-911a-323e5c3a79f7': 'arrayexpress',
<        'f180f1c3-9073-54a9-9bab-633008c307cc': 'contributor',
---
>    contributor_submitter_ids = {
>        'b7525d8e-8c7a-5fec-911a-323e5c3a79f7': ('arrayexpress', 'Array Express')
>        'f180f1c3-9073-54a9-9bab-633008c307cc': ('contributor', 'Contributor')
      ...
```

**Comment by NoopDog** [comment]
Hey  @danielsotirhos thanks for looking in to this,

A few questions:

1. What is the proposed full set of submitters envisioned? - Contributor, Array Express and HCA i presume?

1. What is Array Express left over from last year or is that an actual current value?

1. How will we distinguish between the HCA project stratified/project matrices and the intermediate matrices which are both submitted I presume by HCA?

Also note:

1. We have the concept of submitter already so perhaps this is a submitter_type? https://data.humancellatlas.org/metadata/dictionary/system/provenance#submitter_id

1. We may be able to use file_description for this if we modify the set of allowed values. https://data.humancellatlas.org/metadata/dictionary/file/file_core#content_description

We may wish to involve the metadata team to explore options for modeling this.

Cheers, 
D

**Comment by danielsotirhos** [comment]
> 1. What is the proposed full set of submitters envisioned? - Contributor, Array Express and HCA i presume?

Array Express, Contributor, GEO, HCA Release, SCEA, SCP, DCP/2, DCP/1 Matrix Service

> 2. What is Array Express left over from last year or is that an actual current value?

CGM that were specified with a 'file_source' value of 'arrayexpress' on the [import spreadsheet](https://docs.google.com/spreadsheets/d/1Te1FTUbdn-tFS3eLVTB7uMEApoFU0Il6krSoiq_LAAw/edit?ts=5f762d26#gid=671636652).
