### ISSUE TITLE
Unit and integration tests fail unless AZUL_DSS_ENDPOINT is set

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2496]
Left-over from https://github.com/databiosphere/azul/issues/2280#issuecomment-729468683:

Many unit tests depend on AZUL_DSS_ENDPOINT (https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/3). Not 100% sure that IT fails if AZUL_DSS_ENDPOINT is unset.

More disconcerting, those failing test seem to cause collateral failures, or worse, cause moto mocks to be bypassed (look for `BucketAlreadyExists` and `ResourceInUseException` in the above job log. Fix or create ticket.

**Comment by amarjandu** [comment]
1. Push commit #1 sandbox will fail in test job
2. Push commit #1,2,3 sandbox build will fail in integration test (unit tests are skipped)
3. Push all commits integration tests should pass (unit tests are skipped)
4. Remove drop commits (unit test + integration tests pass)

**Comment by hannes-ucsc** [comment]
The above is meant for the PR.
