### ISSUE TITLE
Create Happy Path Tests for Webservice

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#250]
Create tests that test the normal functionality of the web service.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-170)
┆Project Name: azul
┆Issue Number: AZUL-170

**Comment by hannes-ucsc** [comment]
@GPelayo could you identify possible areas in the code that need more coverage and are easy to cover. If there are none, please provide evidence and close this ticket.
