### ISSUE TITLE
Inconsistent behavior of comma in BigQuery vs TinyQuery

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#2501]
TinyQuery uses legacy SQL, making some queries incompatible between our unit tests and deployed code. Usually these will manifest as errors but there is an inconsistency with the comma operator that may silently undermine the correctness of the tests.

https://cloud.google.com/bigquery/docs/reference/legacy-sql#comma-as-union-all

In standard SQL the comma is the CROSS JOIN operator but in legacy SQL it is the UNION ALL operator.  A cross join can be unambiguously and consistently expressed in either dialect by writing `CROSS JOIN`, but this leaves us in the brittle position of ensuring we never use comma, and there is no likewise solution for `UNION ALL`.

**Comment by noah-aviel-dove** [comment]
(Current hacky workaround in an un-landed PR: https://github.com/DataBiosphere/azul/pull/2346/commits/4e5d0e162490420b01d08ddf94b2efbdbea3f327#diff-f7e494df87ed948185e10a4623a9da139b446bd1510c1384fcfa777e467e44acR446)

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Spike to determine if canning BigQuery results and thereby eliminating TinyQuery is a superior approach."

**Comment by noah-aviel-dove** [comment]
Proposed solution: Add a separate method for running queries joined by `UNION ALL` where subqueries are passed as separate arguments. `TestPlugin` overrides to join the subqueries using `,` for the unit tests.

**Comment by hannes-ucsc** [comment]
> subqueries are passed as separate arguments

should be 

subqueries are passed as a separate argument, of type list

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Postponing until cost discussions with Broad and Google folks are resolved."

**Comment by theathorn** [comment]
@noah-aviel-dove "No reason to do this if not planning to do #2333?"

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Not sure about this, let's assume it is necessary. We will revisit this if/when we decide to solve #2333."

**Comment by hannes-ucsc** [comment]
We now use BigQuery emulator instead of TinyQuery.
