### ISSUE TITLE
Provide a means to determine presence (or not) of matrices for a project

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2503]
From @NoopDog in humancellatlas.org/data-browser#1399:

We will need a way on the Azul projects response (if its not there already) to determine if a project has CGMs or HCA matrices.

Would be great to just have a boolean for each e.g. hasCGMs and hasProjectMatrices or similar.

A single "hasMatrices" would also work.

We do not need the list of matrices just information about the existence so we can show or not the matrix download icon.

Can you indicate if this exists on the DCP2 projects response and what the fields are or create a blocking ticket in Azul and block this ticket with it?

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Spike to determine if /index/projects/{uuid} and /index/projects  both return the matrix properties.If they do, there's nothing to do here."

**Comment by danielsotirhos** [comment]
Confirmed `hits[].projects[].contributorMatrices` (and `hits[].projects[].matrices` once #2428 is merged) are returned by both the `/index/projects` and `/index/projects/{uuid}` Azul endpoint response.

https://service.azul.data.humancellatlas.org/index/projects
https://service.azul.data.humancellatlas.org/index/projects/74b6d569-3b11-42ef-b6b1-a0454522b4a0
