### ISSUE TITLE
Stitching log message is confusing

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2507]
https://github.com/DataBiosphere/azul/blob/d6acd5c6abebe205c7dd1741605fc5fe07780b83/src/azul/plugins/repository/tdr/__init__.py#L233

if there is nothing to stitch on, this message should not be logged. If one subgraph is stitched on, "1" should be logged, not "2".

**Comment by theathorn** [comment]
@noah-aviel-dove to provide details as to why issue re-opened.

**Comment by hannes-ucsc** [comment]
Moved to Triage to ensure https://github.com/DataBiosphere/azul/issues/2507#issuecomment-784491371

**Comment by noah-aviel-dove** [comment]
The changes made in this PR were inadvertently undone here: https://github.com/DataBiosphere/azul/pull/2638/commits/2427d13e2dd03b5c8ad6103f2ea3ebab67d17ed0#diff-dce1aec57757304e7f56e949fd1b69f0725a3ea33ac127fa3772baff1c4305ccL298-L302

**Comment by melainalegaspi** [comment]
@hannes-ucsc :" @noah-aviel-dove to reintroduce the changes."
