### ISSUE TITLE
AC-5 SEPARATION OF DUTIES

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2513]
**The organization:**
 a. Separates [Assignment: organization-defined duties of individuals];
 b. Documents separation of duties of individuals; and
 c. Defines information system access authorizations to support separation of duties.

**Supplemental Guidance:**  Separation of duties addresses the potential for abuse of authorized privileges and helps to reduce the risk of malevolent activity without collusion. Separation of duties includes, for example: (i) dividing mission functions and information system support functions among different individuals and/or roles; (ii) conducting information system support functions with different individuals (e.g., system management, programming, configuration management, quality assurance and testing, and network security); and (iii) ensuring security personnel administering access control functions do not also administer audit functions. Related controls: AC-3, AC-6, PE-3, PE-4, PS-2.

**David Bernick cheat sheet:** There should be some attempt to separate duties -- example: don’t have all devs able to do all things -- have designated ways of elevating privileges. (a) Admin in an application shouldn’t be all-or-nothing

**Comment by theathorn** [comment]
@nolunwa : "AC-05 no gap, ticket can be closed".
