### ISSUE TITLE
AC-6 LEAST PRIVILEGE

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2514]
The organization employs the principle of least privilege, allowing only authorized accesses for users (or processes acting on behalf of users) which are necessary to accomplish assigned tasks in accordance with organizational missions and business functions.

**Supplemental Guidance:**  Organizations employ least privilege for specific duties and information systems. The principle of least privilege is also applied to information system processes, ensuring that the processes operate at privilege levels no higher than necessary to accomplish required organizational missions/business functions. Organizations consider the creation of additional processes, roles, and information system accounts as necessary, to achieve least privilege. Organizations also apply least privilege to the development, implementation, and operation of organizational information systems. Related controls: AC-2, AC-3, AC-5, CM-6, CM-7, PL-2.

**David Bernick cheat sheet:** Least privilege -- all users of a system (admins and regular users) should only be able to do what they need to do in order for the application to work.

**Comment by theathorn** [comment]
@nolunwa : "AC-06 no gap, ticket can be closed"
