### ISSUE TITLE
Document content of audit records

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2519]
The information system generates audit records containing information that establishes what type of event occurred, when the event occurred, where the event occurred, the source of the event, the outcome of the event, and the identity of any individuals or subjects associated with the event.

**Supplemental Guidance:**  Audit record content that may be necessary to satisfy the requirement of this control, includes, for example, time stamps, source and destination addresses, user/process identifiers, event descriptions, success/fail indications, filenames involved, and access control or flow control rules invoked. Event outcomes can include indicators of event success or failure and event-specific results (e.g., the security state of the information system after the event occurred). Related controls: AU-2, AU-8, AU-12, SI-11.

**Comment by hannes-ucsc** [comment]
https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit?disco=AAAAXq89Bvo

Assignee to discuss plan of action in PL.

**Comment by melainalegaspi** [comment]
@danielsotirhos spike to read the linked comment thread and to raise this in the next PL.

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "This will take some time and it will drag on for a bit because we don't have logging and log forwarding complete. In other words, we'll need to pick this up multiple times as the implementation progresses, hence the high estimate."

**Comment by danielsotirhos** [comment]
Created document [AU-3 Content](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit?usp=sharing)

Also saved the unabridged log entries for the following actions:
[insights - page request unauthenticated.csv](https://github.com/DataBiosphere/azul/files/9446947/insights.-.page.request.unauthenticated.csv)
[insights - page request authenticated.csv](https://github.com/DataBiosphere/azul/files/9446949/insights.-.page.request.authenticated.csv)
[insights - file download unauthenticated.csv](https://github.com/DataBiosphere/azul/files/9446950/insights.-.file.download.unauthenticated.csv)
[insights - file download authenticated.csv](https://github.com/DataBiosphere/azul/files/9446952/insights.-.file.download.authenticated.csv)
[insights - manifest compact unauthenticated.csv](https://github.com/DataBiosphere/azul/files/9446957/insights.-.manifest.compact.unauthenticated.csv)
[insights - manifest compact authenticated.csv](https://github.com/DataBiosphere/azul/files/9446954/insights.-.manifest.compact.authenticated.csv)
[insights - manifest curl unauthenticated.csv](https://github.com/DataBiosphere/azul/files/9446961/insights.-.manifest.curl.unauthenticated.csv)
[insights - manifest curl authenticated.csv](https://github.com/DataBiosphere/azul/files/9446963/insights.-.manifest.curl.authenticated.csv)
[insights - bulk download files curl manifest.csv](https://github.com/DataBiosphere/azul/files/9446964/insights.-.bulk.download.files.curl.manifest.csv)
[insights - manifest pfb export unauthenticated.csv](https://github.com/DataBiosphere/azul/files/9446966/insights.-.manifest.pfb.export.unauthenticated.csv)
[insights - manifest pfb export authenticated.csv](https://github.com/DataBiosphere/azul/files/9446968/insights.-.manifest.pfb.export.authenticated.csv)

**Comment by hannes-ucsc** [comment]
I left comments in the sheet. Please address.

**Comment by hannes-ucsc** [comment]
There is still too much duplication, which is noisy and distracting. I suggest a different way of organizing the spreadsheet: primarily by field and add a column in which even types (and note it's "events", not "actions") the field occurs.

Request headers and and query parameters aren't mentioned, nor is the path.

**Comment by dsotirho-ucsc** [comment]
A new tab/sheet "By field" has been added to [the document](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757).

**Comment by hannes-ucsc** [comment]
Nice. @nolunwa please review the spreadsheet Daniel links to above and include in any compliance documentation as you see fit.

**Comment by hannes-ucsc** [comment]
I take that back. We need to incorporate the CloudTrail log groups into the sheet.

**Comment by dsotirho-ucsc** [comment]
CloudTrail log fields have been added to the [document](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757).

**Comment by hannes-ucsc** [comment]
Assignee to keep spreadsheet updated as blockers land.

**Comment by hannes-ucsc** [comment]
Retriage to ask if assignee is on top of this. I think a couple more blockers have landed and need to be documented.

**Comment by dsotirho-ucsc** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757) updated for changes by #4868

**Comment by dsotirho-ucsc** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757) updated for changes by #4178

**Comment by dsotirho-ucsc** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757) updated for changes by #4176

**Comment by dsotirho-ucsc** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757) updated for changes by #4961

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "The GitLab host logs are way too diverse and voluminous to be catalogued this way. Focus on simply listing the specific messages that we filter for with alarms and list those in the Google sheet after the blockers have been resolved."

**Comment by dsotirho-ucsc** [comment]
Assignee to monitor blockers.

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc Annual review is required, ok to have this in a separate ticket. 

Ensure team reviews 

the rules enabled in CloudTrail, CloudWatch, S3 logs, System Manager logs, ELB logs, Security Hub, Guard Duty 

Review the logs

**Comment by dsotirho-ucsc** [comment]
Assignee (@nolunwa-ucsc) to create follow-up ticket about annual review mentioned above.

**Comment by nolunwa-ucsc** [comment]
Annual Review ticket opened - https://github.com/DataBiosphere/azul/issues/5989
