### ISSUE TITLE
Sponsor UCSC email extension for Alex

### ISSUE THREAD

**Issue by alex-hancock** [DataBiosphere/azul#252]
My UCSC account expires in December, but my AWS and Slack credentials rely on it. If I continue with the lab past December, I'll need a sponsorship to retain my access.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-172)
┆Project Name: azul
┆Issue Number: AZUL-172

**Comment by hannes-ucsc** [comment]
I know it is possible to request and extension to a `@ucsc.edu` account from ITS, provided that the request is sponsored by a current employee.

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Comment from Jira.

**Comment by theathorn** [comment]
Comment from zenhub.

**Comment by hannes-ucsc** [comment]
Alex is not actively contributing anymore.
