### ISSUE TITLE
CM-2(1) REVIEWS AND UPDATES

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2525]
The organization reviews and updates the baseline configuration of the information system: 
 (a)   [Assignment: organization-defined frequency];
 (b)   When required due to [Assignment organization-defined circumstances]; and
 (c)   As an integral part of information system component installations and upgrades.

**Supplemental Guidance:**  Related control: CM-5.

**David Bernick cheat sheet:** There must be some sort of approval process 
(a)Can happen at the code-level -- like a certain role can approve a change and then it can go through CI from there. 
(b)Using protected branches can help here or things like PullApprove 
(c)Security Impact has to be considered as part of this approval process (d) Make sure that there’s a record of this approval process. Related to CM-03, CM-04

**Comment by theathorn** [comment]
@nolunwa : Is the PR review process sufficiently covering this control?

**Comment by nolunwa** [comment]
@hannes-ucsc correct PR and release management overview

**Comment by theathorn** [comment]
@hannes-ucsc to amend PR checklist to include security impact analysis of every change and to require that this assessment is made by a person other than the author of the change, even for changes authored by the lead.
