### ISSUE TITLE
IA-2 IDENTIFICATION AND AUTHENTICATION (ORGANIZATIONAL USERS)

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#2528]
The information system uniquely identifies and authenticates organizational users (or processes acting on behalf of organizational users).

**Supplemental Guidance:**  Organizational users include employees or individuals that organizations deem to have equivalent status of employees (e.g., contractors, guest researchers). This control applies to all accesses other than: (i) accesses that are explicitly identified and documented in AC-14; and (ii) accesses that occur through authorized use of group authenticators without individual authentication. Organizations may require unique identification of individuals in group accounts (e.g., shared privilege accounts) or for detailed accountability of individual activity. Organizations employ passwords, tokens, or biometrics to authenticate user identities, or in the case multifactor authentication, or some combination thereof. Access to organizational information systems is defined as either local access or network access. Local access is any access to organizational information systems by users (or processes acting on behalf of users) where such access is
obtained by direct connections without the use of networks. Network access is access to organizational information systems by users (or processes acting on behalf of users) where such access is obtained through network connections (i.e., nonlocal accesses). Remote access is a type of network access that involves communication through external networks (e.g., the Internet). Internal networks include local area networks and wide area networks. In addition, the use of encrypted virtual private networks (VPNs) for network connections between organization- controlled endpoints and non-organization controlled endpoints may be treated as internal networks from the perspective of protecting the confidentiality and integrity of information traversing the network.

Organizations can satisfy the identification and authentication requirements in this control by complying with the requirements in Homeland Security Presidential Directive 12 consistent with the specific organizational implementation plans. Multifactor authentication requires the use of two or more different factors to achieve authentication. The factors are defined as: (i) something you know (e.g., password, personal identification number [PIN]); (ii) something you have (e.g.,
cryptographic identification device, token); or (iii) something you are (e.g., biometric). Multifactor solutions that require devices separate from information systems gaining access include, for example, hardware tokens providing time-based or challenge-response authenticators and smart cards such as the U.S. Government Personal Identity Verification card and the DoD common access card. In addition to identifying and authenticating users at the information system level
(i.e., at logon), organizations also employ identification and authentication mechanisms at the application level, when necessary, to provide increased information security. Identification and authentication requirements for other than organizational users are described in IA-8. Related controls: AC-2, AC-3, AC-14, AC-17, AC-18, IA-4, IA-5, IA-8.

**David Bernick cheat sheet:** Try to use 2FA with everything -- definitely for privileged users 
○ Understood it’s not always possible with users.

**Comment by nolunwa** [comment]
@hannes-ucsc Gap : Service accounts do not have 2FA implemented and have no timeout.

**Comment by nolunwa** [comment]
@theathorn this should be reassigned to Hannes see comment above

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "SAs don't support 2FA. I need to devise a strategy to address this gap. We could consider replacing personal SAs with `gcloud login`."

**Comment by hannes-ucsc** [comment]
Created #4424 to cover the migration from personal SAs to `gcloud login`.

For AWS we already enforce 2FA. Same for the Data Biosphere organization on GitHub. GitLab uses SSO with GitHub so GitLab user accounts are covered by that.

The remaining work is to 

- [x] enable 2FA for the GitLab root account on all GitLab instances
- [ ] have Clever Canary certify in writing (in a contract, for example) that they have 2FA enabled on their Google Workspace for clevercanary.com

**Comment by melainalegaspi** [comment]
@hannes-ucsc to solve first checkbox above.
