### ISSUE TITLE
Curl manifest for zarray matrices does not include related files

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2538]

**Comment by achave11** [comment]
Findings:

Manifest generation for `curl` format only includes placeholder postfix `/.zattrs` and no auxiliary files (`related_files`). The `full` manifest format has the same issue as `curl`, described in ticket #2468.

**Comment by theathorn** [comment]
Not a DCP 2.0 MVP show-stopper.

**Comment by theathorn** [comment]
http://broadinstitute.zendesk.com/agent/tickets/116461
