### ISSUE TITLE
20 subgraphs in snapshots `hca_prod_20201118_dcp1___20201123` and `…24` have ambiguous versions of `analysis_file`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2539]
Same as #2508, different table, different snapshot.

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-indexer-prod-contribute  
start-time: 2020-11-25T05:33:36.273Z  
end-time: 2020-11-25T14:30:00.000Z  
query-string:
```
fields notification.match.bundle_uuid, @requestId
| filter @message like 'Worker failed'
| filter @message like 'ValueError: too many items in iterable (expected 1)'
| stats count(@requestId) by notification.match.bundle_uuid
| limit 100
```
------------------------------------------------------------
|    notification.match.bundle_uuid    | count(@requestId) |
|--------------------------------------|-------------------|
| bf32e3f1-00e9-4837-9cfc-667a325e2dfb | 10                |
| 13cca7b6-b158-4e1c-a8f0-ea4e835fb0e8 | 10                |
| 80b4eadd-2fbb-4468-bd57-89d51b4e9f17 | 14                |
| c63a445c-4ba7-4e26-b732-6540e9a2fdbc | 10                |
| 1d877384-969c-401f-be0e-a331c1a8455c | 10                |
| dd086c20-62c4-4eb5-b9ff-20d7f50b9123 | 12                |
| bb834809-c46c-4822-b0d2-7858588e44d3 | 10                |
| e1d6a9bb-37dc-4f61-a7dd-69c734faaa98 | 10                |
| b3579f02-92bc-4255-8127-3cc028261f51 | 11                |
| 825039d5-8a99-46ea-92d1-2efc257654d5 | 10                |
| 705bdcf0-4f18-477e-b236-4e264bf296cd | 10                |
| 7e96ea61-96b0-4d6d-a7ef-f5d0c39d1556 | 10                |
| 8b7a37a1-e71e-4c7e-a960-9c697e563621 | 10                |
| 7e825dd0-b8c8-46ae-81cf-f9dc589794aa | 10                |
| b211cc4c-839a-4211-ae53-d41e03670a78 | 10                |
| 081399b8-ed10-43a1-890c-a657df472bd4 | 11                |
| 03f81aa0-734c-4e9f-88a2-e90a3095c1b8 | 11                |
| fab59898-3db9-4647-b3af-9cda96836937 | 10                |
| 2b0d6c0d-ab5b-4656-89bf-ccf1b88e0e31 | 10                |
| 0eaa712a-bb35-4b36-be51-7a4b9a19f9d6 | 11                |
------------------------------------------------------------

**Comment by hannes-ucsc** [comment]
Same issue in `hca_prod_20201118_dcp1___20201124`

**Comment by theathorn** [comment]
@hannes-ucsc "Verified fixed in snapshot hca_prod_20201118_dcp1___20201202"
