### ISSUE TITLE
Add submitter id to analysis output metadata

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2561]
Make sure Gordon (intermediate analysis files) and Jessica (stratified project matrices) fill in the submitter_id with the value corresponding to "dcp2" (uuid='e67aaabe-93ea-564a-aa66-31bc0857b707') .

**Comment by hannes-ucsc** [comment]
Also confirm that `analysis_protocol.protocol_id` is different between these two.

**Comment by hannes-ucsc** [comment]
The description contains a mistake: only the stratified project matrices should have a submitter ID. Intermediate files should not. The protocol _id should be different between them. The following proves both:

```sql
select 
    json_extract(analysis_file.content, "$.file_core.file_name") as file_name,
    analysis_protocol.analysis_protocol_id,
    json_extract(analysis_protocol.content, "$.computational_method") as computational_method,
    json_extract(analysis_file.content, "$.provenance.submitter_id") as submitter_id,
from `broad-jade-dev-data.hca_dev_20201217_test4___20210126.links` as links
join unnest(json_extract_array(links.content, '$.links')) as content_links 
    on json_extract_scalar(content_links, '$.link_type') = 'process_link'
join unnest(json_extract_array(content_links, '$.protocols')) as protocols
    on json_extract_scalar(protocols, '$.protocol_type') = 'analysis_protocol'
join `broad-jade-dev-data.hca_dev_20201217_test4___20210126.analysis_protocol` as analysis_protocol
    on json_extract_scalar(protocols, '$.protocol_id') = analysis_protocol.analysis_protocol_id
join unnest(json_extract_array(content_links, '$.outputs')) as outputs
    on json_extract_scalar(outputs, '$.output_type') = 'analysis_file'
join `broad-jade-dev-data.hca_dev_20201217_test4___20210126.analysis_file` as analysis_file
    on json_extract_scalar(outputs, '$.output_id') = analysis_file.analysis_file_id
where project_id = '4a95101c-9ffc-4f30-a809-f04518a23803'
limit 100
```

|file_name                           |analysis_protocol_id            |computational_method                  |submitter_id                                      |
|------------------------------------|--------------------------------|--------------------------------------|--------------------------------------------------|
|"294fe5d9-c1e8-4670-80d3-4c2b0a5e33c1.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"294fe5d9-c1e8-4670-80d3-4c2b0a5e33c1.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"t-cell-activation-human-lung-10XV2.loom"|432a7422-59b5-5c46-8983-a7953f196781|"optimus_post_processing_v1.0.0"      |"e67aaabe-93ea-564a-aa66-31bc0857b707"            |
|"098cc66a-d806-42db-a1c8-fa99a0317d7c.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"098cc66a-d806-42db-a1c8-fa99a0317d7c.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"d6536459-ab4e-4954-a0ce-5e6d07670039.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"d6536459-ab4e-4954-a0ce-5e6d07670039.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"a040dae6-e0b1-49cf-a9ee-9793d5ad7d9c.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"a040dae6-e0b1-49cf-a9ee-9793d5ad7d9c.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"219e1b92-9749-490c-b08a-f375ad4c9884.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"219e1b92-9749-490c-b08a-f375ad4c9884.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"3ddf143f-36bd-49c5-9bbf-f5b71e384063.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"3ddf143f-36bd-49c5-9bbf-f5b71e384063.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"t-cell-activation-human-blood-10XV2.loom"|432a7422-59b5-5c46-8983-a7953f196781|"optimus_post_processing_v1.0.0"      |"e67aaabe-93ea-564a-aa66-31bc0857b707"            |
|"bfbf2ca6-13e5-4fe0-bb03-a592e1e72648.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"bfbf2ca6-13e5-4fe0-bb03-a592e1e72648.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"24ae6c0b-d147-4051-a85b-c6204531b9d7.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"24ae6c0b-d147-4051-a85b-c6204531b9d7.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"fb72f4c2-7f35-40a6-af19-9b41d0680677.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"fb72f4c2-7f35-40a6-af19-9b41d0680677.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"c763f679-e13d-4f81-844f-c2c80fc90f46.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"c763f679-e13d-4f81-844f-c2c80fc90f46.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"c76d90b8-c190-4c58-b9bc-b31f586ec7f2.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"c76d90b8-c190-4c58-b9bc-b31f586ec7f2.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"58a18a4c-5423-4c59-9b3c-50b7f30b1ca5.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"58a18a4c-5423-4c59-9b3c-50b7f30b1ca5.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"t-cell-activation-human-hematopoietic-10XV2.loom"|432a7422-59b5-5c46-8983-a7953f196781|"optimus_post_processing_v1.0.0"      |"e67aaabe-93ea-564a-aa66-31bc0857b707"            |
|"36ca61c4-9752-4cdf-8bac-1e8da06d9ed1.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"36ca61c4-9752-4cdf-8bac-1e8da06d9ed1.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"fcbaa3c6-b2bf-4f87-8336-9966ac6a2bb6.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"fcbaa3c6-b2bf-4f87-8336-9966ac6a2bb6.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"58cf25fd-440a-4d33-ab94-9f7ba5a1036c.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"58cf25fd-440a-4d33-ab94-9f7ba5a1036c.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"6fcd2c86-76dc-4cfa-8805-20f7d8f6a678.loom"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"6fcd2c86-76dc-4cfa-8805-20f7d8f6a678.bam"|f1ed2cc3-220c-55d1-b93f-ae5bb8722cb2|"Optimus"                             |                                                  |
|"t-cell-activation-human-lymph-10XV2.loom"|432a7422-59b5-5c46-8983-a7953f196781|"optimus_post_processing_v1.0.0"      |"e67aaabe-93ea-564a-aa66-31bc0857b707"            |
