### ISSUE TITLE
DCP/2 CGM in prod fails to download 

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2580]
Go to https://dcp2.data.humancellatlas.org/explore/projects?filter=%5B%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D%5D&catalog=dcp2, click on the "Matrices" download icon for the first project (Human and Mouse Pancreas), click on the download icon for file GSE84133_RAW.tar and a screen with the following output appears:
{"Status": 302, "Location": "https://storage.googleapis.com/broad-datarepo-terra-prod-hca2-bucket/d30e68f8-c826-4639-88f3-ae35f00d4185/d1f2db24-c94d-4c66-95a9-556b5d508f6c/f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc.GSE84133_RAW.tar?Expires=1607020399&GoogleAccessId=azul-ucsc-0-prod%40platform-hca-prod.iam.gserviceaccount.com&Signature=VlUau8g8W4CFETSEP4f5ocghx5iVqJ9YE3745xsbeaEqGjJDKapWaykVH2LJLKYUgLZGp3Dh31Y1dWNsYUZeVATgeMUn2jPXFLGvpTgjaLYX32hE9ubHYFZiBcc4dDhrLubL%2BbZBr6HGA2jqthoWo787l%2Bmp64%2FgxIlOtf8jBgBQQlSt%2Bc%2FLYE8bH2EEcPqSQfvd3IymNnHn3kFcXpuaTgcmy9H9pYERa%2FLv97s9bFToaq%2BV%2FP6Taf2ViAqIKGGYuHAzGECa1uNHI3SvD0%2BoHuiOZVzU0sIwyAw32hYUL1J68%2FNgZraF6Zy0t%2BZt0ePqKUvrSyb%2BOi6CPXnVeHglzw%3D%3D&response-content-disposition=attachment%3B+filename%3Df86f1ab4-1fbb-4510-ae35-3ffd752d4dfc.GSE84133_RAW.tar"}

**Comment by theathorn** [comment]
@MillenniumFalconMechanic Data Browser not redirecting?

**Comment by MillenniumFalconMechanic** [comment]
@Trevor, I have created humanCellAtlas/data-browser#1440 to cover this.

**Comment by theathorn** [comment]
Dup - closing.
