### ISSUE TITLE
Decommission DCP/1 (DSS, Azul) infrastructure

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2594]
Assist CZI engineer (tbd) with decommissioning the DCP/1 infrastructure in dev, integration, staging and prod:
- [x] Delete personal deployments in dev AWS and GCP accounts
- [ ] Delete Azul instance
- [ ] Delete data from DSS (AWS & CGP)
- [x] Delete S3 buckets (containing e.g. project matrices)

CZI would be responsible for shutting down the Matrix Service and closing the AWS and GCP accounts.

**Comment by amarjandu** [comment]
- [ ] Inspect Azul deployment env files to ensure all AZUL_DSS_ENDPOINTS are set to `dss prod`

**Comment by amarjandu** [comment]
Destroyed dds-delete for `dev,integration,staging`

**Comment by amarjandu** [comment]
need to tear down gitlab dev
checkout `hca/develop`
source environment 
_select dev.gitlab
cd terraform/gitlab
make destory

same process for prod, dont do it without confirmation.

**Comment by melainalegaspi** [comment]
@hannes-ucsc will do prod deployments off Azul and GitLab and archive the DSS storage bucket and the project asset to Glacier.

**Comment by amarjandu** [comment]
"org-humancellatlas-upload-staging" found to have ~160TB of data within it, deleting bucket contents.

**Comment by amarjandu** [comment]
in process of removing high cost resources.

**Comment by hannes-ucsc** [comment]
Since we extended the scope of this ticket by volunteering to take all resources down and to archive important buckets in Glacier, I'll bump the estimate.

**Comment by hannes-ucsc** [comment]
AWS cost for `dev`, first column is a "normal" day before we did any deletions, last column is yesterday. That's also what we expect the daily cost to be going forward.

|Service                                    |2020-12-17|2020-12-23|2020-12-24|2020-12-29|
|-------------------------------------------|----------|----------|----------|----------|
|S3($)                                      |$189.60   |$33.44    |$7.27     |          |
|Elasticsearch Service($)                   |$129.23   |$0.91     |$0.91     |          |
|Redshift($)                                |$71.90    |$0.01     |          |          |
|EC2-Other($)                               |$56.73    |$13.83    |$10.82    |          |
|CloudTrail($)                              |$49.67    |$24.38    |$0.02     |          |
|Relational Database Service($)             |$35.64    |$0.04     |$0.04     |$0.04     |
|Lambda($)                                  |$10.83    |$5.69     |          |          |
|DynamoDB($)                                |$12.14    |$8.39     |          |          |
|GuardDuty($)                               |$13.47    |$9.35     |$0.39     |$0.32     |
|EC2-Instances($)                           |$15.17    |$2.27     |$1.86     |          |
|EC2-ELB($)                                 |$9.02     |$5.25     |          |          |
|CloudWatch($)                              |$7.05     |$7.11     |$2.98     |$2.93     |
|Elastic Container Service for Kubernetes($)|$7.20     |          |          |          |
|API Gateway($)                             |$4.53     |$1.50     |          |          |
|Secrets Manager($)                         |$3.46     |$0.45     |$0.05     |          |
|CloudFront($)                              |$3.80     |$0.61     |$0.07     |$0.06     |
|Route 53($)                                |$2.36     |$2.15     |$2.08     |          |
|EC2 Container Service($)                   |$2.10     |$1.14     |$0.32     |          |
|SQS($)                                     |$1.36     |$0.17     |$0.03     |$0.02     |
|Config($)                                  |$2.83     |$6.44     |$0.66     |$0.28     |
|X-Ray($)                                   |$0.47     |$0.17     |          |          |
|Key Management Service($)                  |$0.15     |$0.13     |$0.13     |$0.13     |
|Kinesis Firehose($)                        |$0.18     |$0.04     |          |          |
|Cloud Directory($)                         |$0.05     |$0.04     |          |          |
|EC2 Container Registry (ECR)($)            |$0.03     |$0.03     |$0.03     |$0.03     |
|SNS($)                                     |$0.07     |          |          |          |
|Total cost ($)                             |$629.06   |$123.54   |$27.66    |$3.82     |

**Comment by hannes-ucsc** [comment]
Same for `prod`

|Service                                    |2020-12-17|2020-12-23|2020-12-24|2020-12-29|
|-------------------------------------------|----------|----------|----------|----------|
|S3($)                                      |$129.31   |$119.61   |$571.64   |$8.82     |
|Elasticsearch Service($)                   |$115.96   |$97.86    |          |          |
|Redshift($)                                |$23.88    |$21.46    |          |          |
|Relational Database Service($)             |$21.44    |$19.22    |          |          |
|CloudTrail($)                              |$7.49     |$6.73     |          |          |
|Lambda($)                                  |$9.22     |$7.77     |          |          |
|DynamoDB($)                                |$5.28     |$5.28     |$5.28     |          |
|EC2-Other($)                               |$4.47     |$4.05     |$4.05     |$0.51     |
|EC2-ELB($)                                 |$4.02     |$3.26     |$3.25     |          |
|GuardDuty($)                               |$4.24     |$4.02     |$0.29     |$0.29     |
|EC2 Container Service($)                   |$3.97     |$2.52     |          |          |
|API Gateway($)                             |$2.00     |$1.27     |$1.26     |          |
|Elastic Container Service for Kubernetes($)|$2.40     |          |          |          |
|EC2-Instances($)                           |$2.70     |          |          |          |
|CloudWatch($)                              |$1.87     |$1.52     |$0.75     |$0.74     |
|Route 53($)                                |$0.86     |$1.29     |$1.27     |$1.81     |
|CloudFront($)                              |          |          |          |          |
|Secrets Manager($)                         |$0.89     |$0.89     |$0.89     |          |
|Step Functions($)                          |$0.53     |$0.32     |          |          |
|SQS($)                                     |$0.47     |$0.44     |$0.23     |          |
|Config($)                                  |$0.39     |$1.11     |$0.48     |$0.93     |
|Key Management Service($)                  |$0.27     |$0.26     |$0.26     |$0.26     |
|Kinesis Firehose($)                        |$0.04     |$0.03     |$0.01     |          |
|Cloud Directory($)                         |$0.02     |$0.02     |          |          |
|EC2 Container Registry (ECR)($)            |$0.01     |$0.01     |$0.01     |$0.01     |
|Total cost ($)                             |$341.71   |$298.94   |$589.67   |$13.36    |

**Comment by amarjandu** [comment]
All buckets within the `human-cell-atlas-travis-test` google project were removed.
The DSS primary storage bucket  within the project `hca-dcp-production` has retrained with its objects moved into cold-storage. 

All buckets in the AWS `hca-dev` account have been deleted.
Primary DSS AWS production storage bucket `org-hca-dss-prod` has been archived to glacier.

@danielsotirhos gave the `ok` to delete his bucket within the `human-cell-atlas-travis-test`.

**Comment by amarjandu** [comment]
There are a few CloudFront distributions within the `hca-dev` account that get stuck when trying to disable them, they are all tagged with the Clever Canary  group, might need to reachout to them for assistance in deletion if they are unable to be disabled.

**Comment by amarjandu** [comment]
Cloudfront distributions were deleted with the help of Dave.

**Comment by hannes-ucsc** [comment]
I sent email to central command. There is one pending billing support request that I filed challenging the recurring charges for Route 53 health checks that have been deleted but I'll deal with that if/when AWS responds. If they don't, so be it.

**Comment by hannes-ucsc** [comment]
The PR with the bucket deletion script still still pending. Reopening.
