### ISSUE TITLE
Topics for DCP Virtual F2F

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2598]
Fill in [survey](https://docs.google.com/forms/d/e/1FAIpQLSfc417tvuWOivM4Gd3Dq97oY00sukiNHBKtTYJfIaOhFAOJmg/viewform?usp=sf_link).

Some suggestions/thoughts:
  - Scalability of a single snapshot. Maybe we need finer granularity , such as 1 dataset/snapshot per project?
  - Managed access metadata: How will we separate open access and managed access data within a project? 2 snapshots per project/dataset?
  - Are we moving to the Terra Data Model? How to represent entity relationships (vs links.json)? Migration effort?
  - What priority is integration with tertiary portals? Which ones? cell-x-gene? Programmatic API expansion?
  - Do we need a regular or ad hoc architecture meetings (e.g. for managed access solutions)?
  - What do we need to support for versioning and "archived views" and when?

**Comment by theathorn** [comment]
@hannes-ucsc Let's have a quick meeting before you submit answers to the survey (before Wednesday 12/9/20).

**Comment by NoopDog** [comment]
Some notes for consideration/discussion:

## Feature Roadmap
Would like to see a discussion of the longer term roadmap and key features and roadmap items discussed / documented for any of the categories below.


1. What are the key DCP features needed by an “Atlas”? Can we define what an atlas might be and how this is different from the DCP? What other atlases are coming online? How can we use Atlas Builders” to help us focus our development. Note that “Atlas Builder” is not in our list of “Personas” at the moment.  

1. What key metrics are seen as indicative of significant progress by funders?

1. Will we function as an “Archive”? What is our commitment to providing long term access to the artifacts we create if any? How will this affect our approach to versioning?

1. Will we support storing / searching for “derived data”? For example outputs of processes run by third parties on the matrices,  primary or secondary data?

1. Will we be emphasizing our relationships with Terra / Dockstore to create a “Data Biosphere” or cloud-based research environment for the HCA?

1. What are the core requirements / roadmap for managed access data? Will we allow download of managed access data? How will we validate that users have met security requirements for handling data?

1. How can we make our metadata more useful and easier to use? What other concepts do we need to model? What models could use some cleanup / update?

1. Currently the metadata schemas do not specify links to other schemas and the links between entities are expressed in the links.json file. How can we make the relationships between entities more discoverable by users?


## Data Roadmap


1. When will we see other data types besides scRNASeq? In the past there has been a bit of discussion about spatial data / imaging.

1. Will we host contributor generated analysis as well as contributor generated matrices?

## Process

1. How can we increase our velocity? What are key impediments and how can we eliminate them? 

1. Could smaller tests datasets help by surfacing problems quicker and validating that changes have not introduced regressions?

1. How can we quickly determine if a new dataset is ingestible/processable?

**Comment by theathorn** [comment]
Dave's [F2F Discussion Points](https://docs.google.com/document/d/1JHctqa8geJVb8PO0kbiMHWP09eBkQUmM8mbi7j2-C-Y).

**Comment by theathorn** [comment]
Prepared [UCSC Roadmap Epics 2021 Q1-Q2](https://docs.google.com/document/d/1gFBDyaYf1YEw1YePUbJdXiyiTZVVj8tA5FUifkde2Bg) - closing.
