### ISSUE TITLE
Downloading a full metadata manifest from prod results in an exception

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2605]
Go to https://dcp2.data.humancellatlas.org/ and click on the "Metadata" icon for any project.
Result is an exception in Azul:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/08713a50-babb-46e7-88ff-cbb30a3c964b)

**Comment by danielsotirhos** [comment]
Duplicate of #2440

**Comment by theathorn** [comment]
Verified fixed in prod.
