### ISSUE TITLE
Supplementary files have 'Undefined' species and are excluded with default filter

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2606]
Supplementary files are indexed connected to a project but not the other metadata files in the project. This causes the supplementary files to be listed on the 'files' tab with the value 'Unspecified' for most columns (`species`, `organ`, etc) having the value `Unspecified`. This also causes the supplementary files to be excluded from the 'files' tab unless the user specifically removed the default `Genus Species: Homo sapiens` filter.

Note: #2603 is about this same issue however it is specific to CGM supplementary files which have stratification information that can be used to populate some of the columns.

## With 'species' filter specified

![files-3](https://user-images.githubusercontent.com/46407464/101540473-ea8bd200-3954-11eb-898d-8a6c74c66dbe.png)

## With 'species' filter cleared.

![files-4](https://user-images.githubusercontent.com/46407464/101540485-eeb7ef80-3954-11eb-8506-52bd57dfa14b.png)

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Supplementary files are only linked to the files, how would be know anything else about them?"

**Comment by melainalegaspi** [comment]
@hannes-ucsc to fill in details (same issue that Dave brought up, consider combination filters, consider removing filters when selecting a project).

**Comment by hannes-ucsc** [comment]
Unlike the non-supplementary files in that project and the project itself, these supplementary files are not directly associated with any of the biomaterial or analysis metadata properties and I would think that it is not safe to assume that they are: Let's say there is a project about mice and humans and that some supplementary PDF files talk about the human aspects while other talk about the mouse aspects. If we were to assume that all supplementary files in a project inherit the inner entities from the project, ALL supplementary files in that project would be associated with mouse AND human. I don't think that's desirable but I don't know for certain.

There currently is a way for users to discover these files: 

1) first discover the project on the Projects tab, then 
2) select the project and 
3) switch to the Files tab. No supplementary files are shown. 
4) Deselect all filters except the project filter that was added during step 2. Supplementary files are now shown.

We could make this more intuitive having the Data Browser perform step 4 automatically as part of step 3. Doing so would also address another issue the browser team brought up repeatedly in the past:  Consider the graph `f1 → e1 → p ← e2 ← f2` where `f1` and `f2` are sequence or analysis files, `e1` and `e2` are other, non-file entities and `p` is the project. If `e1.x = 'foo'` and `e2.y = 'bar'` (with `x` and `y` being metadata properties that Azul exposes as facets), the Azul filter `x is foo and y is bar` will return `p` but neither `f1` nor `f2`.

If we wanted to attribute all of a project's facets to all the supplementary files in that project (which I don't think we want, for the reasons outlined in the first paragraph), we don't currently have the means to do that in Azul. What we CAN do currently, is to contribute the same inner entities to a supplementary file as to the project. However, this would only contribute the inner entities from those subgraphs that actually mention the supplementary file. If there are subgraphs in the project that don't mention the supplementary file, their inner entities would only be contributed to the project, not the supplementary file. We'd have to somehow know the list of supplementary files in a project and then generate contributions to them, even when indexing subgraphs that don't mention any of those supplementary files. That's not something we can currently do.

**Comment by melainalegaspi** [comment]
@theathorn :"Talk to @NoopDog at standup."

**Comment by melainalegaspi** [comment]
@theathorn to schedule meeting to discuss this further.

**Comment by theathorn** [comment]
Noting that the "default species" selection will be removed as per HumanCellAtlas/DataBrowser#
