### ISSUE TITLE
Collateral test failures in test_versioning

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2611]
Found here: https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/3
Replicated with commit https://github.com/DataBiosphere/azul/commit/10d5301db654facee194f89bb843aa9308e5dc73 : https://travis-ci.com/github/DataBiosphere/azul/jobs/455791231#L4155

There are collateral test failures that occur when un-setting `DSS` related environment variables.
These tests fail with errors stating that resources cannot be allocated, however they should not be attempting to interface with live infrastructure, the setup of the resources should be mocked using the `moto` library.
These tests should be inspected by either observing the tests failure directly, or having the tests fail as collateral during a run of the unit-test suite.

**Comment by melainalegaspi** [comment]
Spike to determine cause.

**Comment by amarjandu** [comment]
Unable to replicate failures when removing patch performed by DSSTestCase.
`test_drs`, `test_mainfest`, `test_repository_proxy`, and `test_response` fail due to the missing patch
`test_portal_service` and `test_versioning` pass without failures

**Comment by hannes-ucsc** [comment]
I don't think the attempt to replicate this is adequate. A failure of test Y is called collateral if it follows a failure of test X and test Y passes when run in isolation. In any attempt of a reproduction we would need to observe at least test X failing. If test Y passes in that build and was run after X, only then can we claim inability to reproduce.

**Comment by amarjandu** [comment]
Attempted to recreated collateral failure with commit https://github.com/DataBiosphere/azul/pull/2770/commits/2d0774e48c9f2a26c6f2621ad1fa9442f0715c30 

Job failure seen https://travis-ci.com/github/DataBiosphere/azul/jobs/481378104 
test_portal_service and test_versioning both pass while the DSS dependent tests fail.

**Comment by amarjandu** [comment]
get to commit d81f9f186db032f846115862b6355c890fe42a96 from gitlab 
attempt to replicate unit-test failure
disable tests and search for the collateral, binary-search approach is probably fastest

**Comment by hannes-ucsc** [comment]
Binary search over failing tests required, which takes time. Increased spike estimate accordingly.

**Comment by amarjandu** [comment]
Unable to checkout commit: `d81f9f186db032f846115862b6355c890fe42a96`

https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/network/d81f9f186db032f846115862b6355c890fe42a96?utf8=%E2%9C%93&extended_sha1=&filter_ref=1

Using commit `f5515194` from `develop` branch, collateral failures are able to be reproduced.

Searching revealed that the failure in `test_portal_service` can cause a failure in `test_versioning`. If disabling DSS dependent tests, the test failures in `test_portal_service` and `test_versioning` still occur. 

`TestPortalService` and `TestVersionService` both share a parent class `VersionTableTestCase` which has a mock decorator applied at the class level. It appears that if there is an error raised within the moto library, subsequent calls to the boto library are not mocked, which appear to be collateral failures.

**Comment by amarjandu** [comment]
Was able to replicate the failure on `develop` within `test_portal_service` and `test_versioning` by not renaming `TDR_SOURCE` to `TDR_SOURCES` the failures occur in the same way.

**Comment by amarjandu** [comment]
The source of the collateral was narrowed down to how the teardown works in the test case. If the object fails to be created in S3, the test_case teardown can fail to delete the object, and the deletion of the bucket is never performed. On the following test run the S3 bucket already exists, so it cannot be created. These residuals that are left around exist at a global level, so its possible that a failure to clean up properly in the `test_portal_service` causes a collateral in `test_versioning`.
