### ISSUE TITLE
Set up "preview" catalog for prod environment

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2615]
Goal: to support secondary analysis runs of data in prod without disrupting the end-user environment.

Create a catalog "preview" that will index the latest snapshot in prod, while leaving the production Data Browser pointed at the released snapshot.

The Data Browser internal team member will select this "hidden" catalog by adding e.g. "/catalog=preview" to the URL.

**Comment by hannes-ucsc** [comment]
I want to wait on this until there is actually a need. Right now I would have to point this at the same snapshot as the dcp2 catalog and this would mean 50% increase in indexing time and cost at no value.

**Comment by hannes-ucsc** [comment]
Catalog will be called `dcp3` and marked as internal. We can't rename catalogs so "preview" is a poor choice for the name. When the preview catalog goes live, a new catalog would have to be created and reindexed. I think we would should settle into the habit of creating frequent releases and a simple integral version number does that.
