### ISSUE TITLE
Azul client's `wait_for_indexer` heuristic for timeout does not work

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2617]
The client assumes a fixed time to index one bundle to estimate the timeout for the overall reindex. This is too brittle. The indexing time of a bundle depends on 

* the indexing code itself and its performance, 
* which repository the bundle is stored in, 
* the request capacity of the repository it is stored in, 
* the number of Azul index workers (which may be temporarily increased manually to accelerate indexing), 
* the request capacity of the Elasticsearch instance. 

Some of these depend on other secondary factors. The request capacity of the Elasticsearch instance, for example, depends on the utilization of the Azul service by external users. The request capacity of the TDR repository depends on the size of the snapshot, the size of the dataset (a query against a snapshot table needs to visit every row in the dataset) and, most importantly, on the BigQuery slot commitment.

**Comment by hannes-ucsc** [comment]
The solution is not use a timeout but instead measure progress and exit if that measurement is within an epsilon of zero for a given period of time.

**Comment by melainalegaspi** [comment]
Discuss during Triage- consider reassigning for expediency.

**Comment by noah-aviel-dove** [comment]
Updated demo instructions:

For demo, insert `assert False` into the handling of a regular bundle notification.
