### ISSUE TITLE
Add snapshot ID to index and expose in manifests and /index responses

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2625]
Every outer entity should specify the TDR UUID of the snapshot it was taken from.

**Comment by hannes-ucsc** [comment]
Potential solutions: 

a) Add `snapshot_id` as a top_level property of index documents, containing the UUID of TDR snapshot. This would require a lookup against the TDR API when forming BQ queries.

b) Add `snapshot` as a top_level property of index documents, containing the name of the TDR snapshot. This would not require a lookup. I also think the name is immutable.

c) Include `snapshot_id` in the entity_id field, separated by colon.

d) Include the snapshot name in the entity_id field, separated by colon.

**Comment by jessebrennan** [comment]
@hannes-ucsc, "Ask Ruchi: will snapshot name always be a unique identifier for a snapshot? Can we count on this forever? Is it possible to rename a BQ query set? Will snapshots be spread out into different projects? We assume the ID is stable and unique, is the name also stable and unique?"

**Comment by jessebrennan** [comment]
@hannes-ucsc: "Snapshot attribute of documents should be called `repository_source_id`".
