### ISSUE TITLE
Some optional metadata properties are required de-facto

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2628]
There may be various metadata properties that Azul assumes exist but that are not actually required by the schema. I am currently aware of one such property: `provenance.document_id`: Azul depends on it, the DCP/2 schema spec depends on it, the DCP/2 analysis workflows depend on it but the metadata schemas declare [provenance](https://github.com/HumanCellAtlas/metadata-schema/blob/90b0ac22def50d35538891c6d145d07077a8f93a/json_schema/type/biomaterial/cell_line.json#L34) as [optional](https://github.com/HumanCellAtlas/metadata-schema/blob/90b0ac22def50d35538891c6d145d07077a8f93a/json_schema/type/biomaterial/cell_line.json#L5). I think either the schema should declare that property as required to reflect the de-facto nature of the property, or, if that meets opposition, we need to document the superset of DCP/2-required metadata properties in another place.

**Comment by melainalegaspi** [comment]
Fill in more details @hannes-ucsc

**Comment by hannes-ucsc** [comment]
Spike to determine an exhaustive list of all properties the DCP/2 depends on, but that the schema does not declare as required.

cc: @kbergin

**Comment by hannes-ucsc** [comment]
Details filled in.
