### ISSUE TITLE
Remove DynamoDB for portal registration database

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2630]
Since AWS has implemented strong consistency for S3 https://aws.amazon.com/s3/consistency/, we no longer need to use DynamoDB to keep track of the latest version.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"DynamoDB based versioning is not only used to workaround eventual consistency, but also to detect concurrent updates using optimistic locking."
