### ISSUE TITLE
Stage and snapshot lungmap mouse data

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2633]
Review the staging area, assist @raaidbroad in creating a dataset and snapshot it.

Definition of done: A snapshot of  exists in dev TDR.

From Eric Bardes: "So I uploaded a mouse dataset into a bucket called lungmap-gse122332.  We already know we’ll be making some updates to it, but at this point just looking at whether it seems to be reasonably compliant with HCA standards".

We need to review this metadata files and assist the LungMAP team with any needed corrections.

I believe the dataset is very small - 7 fastq files and ~2 dozen json metadata files.

**Comment by danielsotirhos** [comment]
Found issues:
- 4 JSON files failed schema validation
- "sequence_file" and "analysis_file" `file_name` field contains file path when it should only contain file_name
- file descriptors missing

**Comment by danielsotirhos** [comment]
The current version of the staging area `gs://lungmap-gse122332` has been reviewed and no errors were found.
Jeff & Raaid have been contacted to begin the import & snapshot process.

**Comment by danielsotirhos** [comment]
"Snapshot `lungmap_dev_20210203___20210204` has been created." https://humancellatlas.slack.com/archives/C01DQFA5F5Y/p1612449665017100?thread_ts=1611777089.012900&cid=C01DQFA5F5Y
