### ISSUE TITLE
Logging response while checking API access to TDR adds a lot of noise to deployment

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2654]
This occurs when running `make deploy`. Here's the response I receive:

> ...
> make[2]: Entering directory '/home/jesse/gi/azul/terraform'
> python /home/jesse/gi/azul/scripts/manage_health_checks.py --link
> 2020-12-21 11:25:46,487 INFO    MainThread: Found credentials in environment variables.
> 2020-12-21 11:25:46,912 INFO    MainThread: DCP wide health check does not exist for jesse1
> make[2]: Leaving directory '/home/jesse/gi/azul/terraform'
> make grafana
> make[2]: Entering directory '/home/jesse/gi/azul/terraform'
> python /home/jesse/gi/azul/scripts/update_grafana.py
> 2020-12-21 11:25:47,179 INFO    MainThread: Skipping publishing of Grafana dashboard
> make[2]: Leaving directory '/home/jesse/gi/azul/terraform'
> make[1]: Leaving directory '/home/jesse/gi/azul/terraform'
> make sam
> make[1]: Entering directory '/home/jesse/gi/azul'
> python /home/jesse/gi/azul/scripts/register_sam.py
> 2020-12-21 11:25:48,454 INFO    MainThread: Found credentials in environment variables.
> 2020-12-21 11:25:50,018 INFO    MainThread: Google service account previously registered with SAM.
> 2020-12-21 11:25:51,350 INFO    MainThread: TDR client is authorized for API access to snapshot 'hca_dev_20200819___20201105_optimusb' via the TDR API: {'id': '5a413a19-8c97-4f3f-8714-fa6a438fb00a', 'name': 'hca_dev_20200819___20201105_optimusb', 'description': 'Create snapshot hca_dev_20200819___20201105_optimusb', 'createdDate': '2020-11-05T19:47:07.862165Z', 'source': [{'dataset': {'id': '1b3cb1a7-8193-4558-b33a-13a477b6a47e', 'name': 'hca_ucsc_files', 'description': 'Human Cell Atlas', 'defaultProfileId': 'b94944a9-df3d-4b35-b573-c7d9b249ea52', 'createdDate': '2020-08-19T20:53:20.399042Z'}, 'asset': None}], 'tables': [{'name': 'imaging_protocol', 'columns': [{'name': 'imaging_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'ipsc_induction_protocol', 'columns': [{'name': 'ipsc_induction_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 2}, {'name': 'enrichment_protocol', 'columns': [{'name': 'enrichment_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 73}, {'name': 'differentiation_protocol', 'columns': [{'name': 'differentiation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 5}, {'name': 'supplementary_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'supplementary_file_id', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 187}, {'name': 'analysis_process', 'columns': [{'name': 'analysis_process_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 8}, {'name': 'imaging_preparation_protocol', 'columns': [{'name': 'imaging_preparation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'collection_protocol', 'columns': [{'name': 'collection_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 50}, {'name': 'project', 'columns': [{'name': 'project_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 28}, {'name': 'donor_organism', 'columns': [{'name': 'donor_organism_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 289}, {'name': 'reference_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'reference_file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 3}, {'name': 'analysis_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'analysis_file_id', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 14}, {'name': 'protocol', 'columns': [{'name': 'protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'cell_line', 'columns': [{'name': 'cell_line_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 25}, {'name': 'aggregate_generation_protocol', 'columns': [{'name': 'aggregate_generation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'links', 'columns': [{'name': 'links_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'project_id', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 135657}, {'name': 'image_file', 'columns': [{'name': 'image_file_id', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'dissociation_protocol', 'columns': [{'name': 'dissociation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 37}, {'name': 'sequencing_protocol', 'columns': [{'name': 'sequencing_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 40}, {'name': 'process', 'columns': [{'name': 'process_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 225006}, {'name': 'imaged_specimen', 'columns': [{'name': 'imaged_specimen_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'analysis_protocol', 'columns': [{'name': 'analysis_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 3}, {'name': 'cell_suspension', 'columns': [{'name': 'cell_suspension_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 88577}, {'name': 'organoid', 'columns': [{'name': 'organoid_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 12}, {'name': 'specimen_from_organism', 'columns': [{'name': 'specimen_from_organism_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 780}, {'name': 'library_preparation_protocol', 'columns': [{'name': 'library_preparation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 44}, {'name': 'sequence_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'sequence_file_id', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 278786}], 'relationships': [{'name': 'from_links.project_id_to_project.project_id', 'from': {'table': 'links', 'column': 'project_id'}, 'to': {'table': 'project', 'column': 'project_id'}}], 'profileId': '08d388da-b98f-4cf8-862b-3531bb75bf98', 'dataProject': 'broad-jade-dev-data'}
> 2020-12-21 11:25:53,705 INFO    MainThread: TDR client is authorized to access tables in BigQuery dataset 'hca_dev_20200819___20201105_optimusb' in Google Cloud project 'broad-jade-dev-data'
> 2020-12-21 11:25:54,270 INFO    MainThread: TDR client is authorized for API access to snapshot 'hca_dev_20201023_ebiv4___20201027' via the TDR API: {'id': '322fb381-f20f-483b-afdb-0102e20f9cfa', 'name': 'hca_dev_20201023_ebiv4___20201027', 'description': 'DCP2 with analysis and cgm', 'createdDate': '2020-10-27T15:23:25.333797Z', 'source': [{'dataset': {'id': 'ba009c32-fbc8-4e80-9b8d-45c9002f9423', 'name': 'hca_dev_20201023_ebiv4', 'description': 'Human Cell Atlas', 'defaultProfileId': 'b94944a9-df3d-4b35-b573-c7d9b249ea52', 'createdDate': '2020-10-23T14:26:07.073795Z'}, 'asset': None}], 'tables': [{'name': 'imaging_protocol', 'columns': [{'name': 'imaging_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'ipsc_induction_protocol', 'columns': [{'name': 'ipsc_induction_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'enrichment_protocol', 'columns': [{'name': 'enrichment_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 23}, {'name': 'differentiation_protocol', 'columns': [{'name': 'differentiation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'supplementary_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'supplementary_file_id', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 32}, {'name': 'analysis_process', 'columns': [{'name': 'analysis_process_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 4}, {'name': 'imaging_preparation_protocol', 'columns': [{'name': 'imaging_preparation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'collection_protocol', 'columns': [{'name': 'collection_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 20}, {'name': 'project', 'columns': [{'name': 'project_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 16}, {'name': 'donor_organism', 'columns': [{'name': 'donor_organism_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 169}, {'name': 'reference_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'reference_file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 1}, {'name': 'analysis_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'analysis_file_id', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 7}, {'name': 'protocol', 'columns': [{'name': 'protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'cell_line', 'columns': [{'name': 'cell_line_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'aggregate_generation_protocol', 'columns': [{'name': 'aggregate_generation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'links', 'columns': [{'name': 'links_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'project_id', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 2060}, {'name': 'image_file', 'columns': [{'name': 'image_file_id', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'dissociation_protocol', 'columns': [{'name': 'dissociation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 24}, {'name': 'sequencing_protocol', 'columns': [{'name': 'sequencing_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 24}, {'name': 'process', 'columns': [{'name': 'process_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 4298}, {'name': 'imaged_specimen', 'columns': [{'name': 'imaged_specimen_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'analysis_protocol', 'columns': [{'name': 'analysis_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 2}, {'name': 'cell_suspension', 'columns': [{'name': 'cell_suspension_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 1963}, {'name': 'organoid', 'columns': [{'name': 'organoid_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 0}, {'name': 'specimen_from_organism', 'columns': [{'name': 'specimen_from_organism_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 294}, {'name': 'library_preparation_protocol', 'columns': [{'name': 'library_preparation_protocol_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'content', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 25}, {'name': 'sequence_file', 'columns': [{'name': 'content', 'datatype': None, 'array_of': False}, {'name': 'file_id', 'datatype': None, 'array_of': False}, {'name': 'version', 'datatype': None, 'array_of': False}, {'name': 'sequence_file_id', 'datatype': None, 'array_of': False}, {'name': 'descriptor', 'datatype': None, 'array_of': False}], 'primaryKey': None, 'partitionMode': 'none', 'datePartitionOptions': None, 'intPartitionOptions': None, 'rowCount': 5589}], 'relationships': [{'name': 'from_links.project_id_to_project.project_id', 'from': {'table': 'links', 'column': 'project_id'}, 'to': {'table': 'project', 'column': 'project_id'}}], 'profileId': '390e7a85-d47f-4531-b612-165fc977d3bd', 'dataProject': 'broad-jade-dev-data'}
> 2020-12-21 11:25:55,961 INFO    MainThread: TDR client is authorized to access tables in BigQuery dataset 'hca_dev_20201023_ebiv4___20201027' in Google Cloud project 'broad-jade-dev-data'
> make[1]: Leaving directory '/home/jesse/gi/azul'

```

**Comment by noah-aviel-dove** [comment]
Freebie of #2504
