### ISSUE TITLE
Reindex integration and staging

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#266]
We forgot one post-processing step after landing https://github.com/DataBiosphere/azul/pull/231: The index names have changed and the new indices need to be repopulated. The old indices also need to be removed.

Select the `integration` deployment and run `make reindex`. Monitor the worker queue in AWS console. Delete the old `browser_…` indices. Repeat in staging.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-178)
┆Project Name: azul
┆Issue Number: AZUL-178

**Comment by GPelayo** [comment]
Reopened to investigate whether `staging` and `integration` indices are not correctly indexed and causing issue #330. After investigating both sets of indices, both sets of indices already have been indexed successfully. The error only occurred in the `prod` deployment of  the data-portal.
