### ISSUE TITLE
DistinctAccumulator ignores varying values for the same key

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2661]
DistinctAccumulator only accumulates a value if the key passed in has not already been accumulated.

We assume that whenever accumulate is called, it will be with the same key-value pair. This assumption is not enforced in the code, and the first value seen for a key-value pair is what's used.

**Comment by jessebrennan** [comment]
We can make this assumption explicit by tracking they keys (in addition to the values) that are passed in when accumulate() is called and raise and Exception when a new value doesn't match the old value for a given key.

**Comment by hannes-ucsc** [comment]
> We assume that whenever accumulate is called, it will be with the same key-value pair.

We don't. The keys have to be distinct, not the key value pairs.

https://github.com/DataBiosphere/azul/blob/db53009807456edf875cd646983c9cc2e02500e9/src/azul/indexer/aggregate.py#L362
