### ISSUE TITLE
Data Browser URLs and Azul catalogs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2665]
Implemented changes are [here](https://docs.google.com/document/d/1crEx7CaPJFLDbxQ_Ic9V3qBK323D1IHQE57gkFUeX24).

OBSOLETE:

<ol><li><p style="margin-bottom: 0.14in; border: none; padding: 0in; line-height: 138%; background: transparent">
	<span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">We
	change the Data Browser URL scheme to include an optional initial
	version identifier in the URL
	path.<br/>
<br/>
</span></span></span></font></font></span></font></span><a href="https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter="><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">https://data.humancellatlas.org/explore/</span></span></u></span></font></font></span></font></span><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><b><span style="background: transparent">v2/</span></b></u></span></font></font></span></font></span><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">projects?catalog=dcp1&amp;filter=</span></span></u></span></font></font></span></font></span></a><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">...</span></span></span></font></font></span></font></span></p>
	<li><p style="margin-bottom: 0.14in; border: none; padding: 0in; line-height: 138%; background: transparent">
	<span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">URLs
	that don't include the version identifier are assumed to be v1
	URLs<br/>
<br/>
</span></span></span></font></font></span></font></span><a href="https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter="><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">https://data.humancellatlas.org/explore/projects?catalog=dcp1&amp;filter=</span></span></u></span></font></font></span></font></span></a><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">...</span></span></span></font></font></span></font></span></p>
	<li><p style="margin-bottom: 0.14in; border: none; padding: 0in; line-height: 138%; background: transparent">
	<span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">To
	avoid ambiguity, an explicit v1 is not allowed. The
	URL<br/>
<br/>
</span></span></span></font></font></span></font></span><a href="https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter="><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">https://data.humancellatlas.org/explore/v1/projects?filter=</span></span></u></span></font></font></span></font></span></a><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">...<br/>
<br/>
for
	example, yields a 404.</span></span></span></font></font></span></font></span></p>
	<li><p style="margin-bottom: 0.14in; border: none; padding: 0in; line-height: 138%; background: transparent">
	<span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">v1
	URLs without the catalog parameter are redirected to a v2 URL that
	has the </span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Consolas, sans-serif"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">catalog</span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">
	parameter set to the value of a configuration property called
	</span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Consolas, sans-serif"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">v1_default_catalog</span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">.
	For example, and assuming </span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Consolas, sans-serif"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">v1_default_catalog</span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">
	is set to </span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Consolas, sans-serif"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">dcp1</span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">
	in prod, the
	URL<br/>
<br/>
</span></span></span></font></font></span></font></span><a href="https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter="><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">https://data.humancellatlas.org/explore/projects?filter=</span></span></u></span></font></font></span></font></span></a><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">...<br/>
<br/>
is
	redirected to
	<br/>
<br/>
</span></span></span></font></font></span></font></span><a href="https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter="><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter=</span></span></u></span></font></font></span></font></span></a><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">...</span></span></span></font></font></span></font></span></p>
	<li><p style="margin-bottom: 0.14in; border: none; padding: 0in; font-variant: normal; font-style: normal; font-weight: normal; line-height: 138%; background: transparent; text-decoration: none">
	<font color="#000000"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="background: transparent">Azul
	is changed to include a </span><font face="Consolas, sans-serif"><span style="background: transparent">/index/catalogs</span></font><span style="background: transparent">
	endpoint which lists the catalogs a particular Azul deployment
	supports. The response contains the names of the catalogs and
	designates one of them as the </span><i><span style="background: transparent">default
	Azul catalog</span></i><span style="background: transparent">. The
	default Azul catalog is the one Azul assumes when other Azul
	endpoints are hit without specifying a catalog parameter. There will
	always be at least one catalog in the response and exactly one
	default Azul catalog.&nbsp;</span></font></font></font></p>
	<li><p style="margin-bottom: 0.14in; border: none; padding: 0in; line-height: 138%; background: transparent">
	<span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">v2
	URLs without the </span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Consolas, sans-serif"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">catalog</span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">
	parameter are redirected to a v2 URL that has the </span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Consolas, sans-serif"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">catalog</span></span></span></font></font></span></font></span><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">
	parameter set to the default Azul catalog. For example, assuming
	that the default Azul catalog is 'dcp2', the
	URL<br/>
<br/>
</span></span></span></font></font></span></font></span><a href="https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter="><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">https://data.humancellatlas.org/explore/</span></span></u></span></font></font></span></font></span><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><b><span style="background: transparent">v2/</span></b></u></span></font></font></span></font></span><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">projects?filter=</span></span></u></span></font></font></span></font></span></a><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">...<br/>
<br/>
is
	redirected to
	<br/>
<br/>
</span></span></span></font></font></span></font></span><a href="https://data.humancellatlas.org/explore/v2/projects?catalog=dcp1&amp;filter="><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">https://data.humancellatlas.org/explore/</span></span></u></span></font></font></span></font></span><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><b><span style="background: transparent">v2/</span></b></u></span></font></font></span></font></span><span style="font-variant: normal"><font color="#1155cc"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><u><span style="font-weight: normal"><span style="background: transparent">projects?catalog=dcp2&amp;filter=</span></span></u></span></font></font></span></font></span></a><span style="font-variant: normal"><font color="#000000"><span style="text-decoration: none"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="font-style: normal"><span style="font-weight: normal"><span style="background: transparent">...</span></span></span></font></font></span></font></span></p>
	<li><p style="margin-bottom: 0.14in; border: none; padding: 0in; font-variant: normal; font-style: normal; font-weight: normal; line-height: 138%; background: transparent; text-decoration: none">
	<font color="#000000"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="background: transparent">In
	prod, the </span><font face="Consolas, sans-serif"><span style="background: transparent">v1_default_catalog</span></font><span style="background: transparent">
	configuration property is set to </span><font face="Consolas, sans-serif"><span style="background: transparent">dcp1</span></font><span style="background: transparent">;
	in dev it is set to </span><font face="Consolas, sans-serif"><span style="background: transparent">dcp2</span></font><span style="background: transparent">.
	The Azul default catalog is dcp2 in prod and dev.</span></font></font></font></p>
	<li><p style="margin-bottom: 0in; border: none; padding: 0in; font-variant: normal; font-style: normal; font-weight: normal; line-height: 138%; background: transparent; text-decoration: none">
	<font color="#000000"><font face="Arial"><font size="2" style="font-size: 11pt"><span style="background: transparent">The
	default Azul catalog </span><b><span style="background: transparent">will</span></b><span style="background: transparent">
	change over time as new versions of the catalog are released e.g.
	hca-dcp-3, hca-dcp-4, hca-dcp-5. The value of the </span><font face="Consolas, sans-serif"><span style="background: transparent">v1_default_catalog</span></font><span style="background: transparent">
	configuration property may also change but only to reflect a
	renaming of the referenced catalog. The contents of that catalog
	must stay the same.</span></font></font></font></p>
</ol>

**Comment by theathorn** [comment]
@NoopDog Can you please update the description to be accurate with the current implementation.
