### ISSUE TITLE
LocalAppTestCase does not emit the correct port in logs

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2668]
When a testcase uses LocalAppTestCase as a parent class it emits the message:
```
Serving on http://localhost:0
2021-01-05 11:59:27,097 INFO    Thread-7: Received GET request to '/health/basic' without parameters.
2021-01-05 11:59:27,099 DEBUG   Thread-7: Returning 200 response without headers. See next line for the first 1024 characters of the body.
{"up": true}
127.0.0.1 - - [05/Jan/2021 11:59:27] "GET /health/basic HTTP/1.1" 200 -
```

the `Serving on http://localhost:0` message is misleading as it cannot be used to connect to the local instance of the service due to the port value being incorrect.

**Comment by amarjandu** [comment]
The property `LocalAppTestCase.baseurl` can be emitted as this is the correct IP and port that is being used for the service.

**Comment by jessebrennan** [comment]
In the title, should ommit be emit?

**Comment by hannes-ucsc** [comment]
`localhost` should resolve to 127.0.0.1. If it doesn't, I think something is wrong on your system. On mine:

```
$ host localhost
localhost has address 127.0.0.1
localhost has IPv6 address ::1
$ ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.017 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.023 ms
^C
--- localhost ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1025ms
rtt min/avg/max/mdev = 0.017/0.020/0.023/0.003 ms
$ 
```

**Comment by hannes-ucsc** [comment]
It looks like the logged port is wrong (`0`), not the hostname.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"  @amarjandu to update description based on Hannes' comments."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
