### ISSUE TITLE
Service Swagger page contains outdated references to DRS, DSS and DCP CLI

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2671]

**Comment by achave11** [comment]
`spec` level tags in swagger schema should not contain references to DSS or DRS, since those endpoints have been retired.

**Comment by melainalegaspi** [comment]
@jessebrennan, why did you drag this from prod to sprint?

**Comment by jessebrennan** [comment]
![dss](https://user-images.githubusercontent.com/10734740/112884626-93854680-9084-11eb-887e-9cf545f76c8b.png)
References to DSS remain in swagger spec.
