### ISSUE TITLE
BAM files show up in matrix tree for DCP/2 test project in dev

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2685]
To reproduce

```
$ http 'https://service.dev.singlecell.gi.ucsc.edu/index/projects/4a95101c-9ffc-4f30-a809-f04518a23803?catalog=dcp2' | jq -r '.projects[].matrices | .. | .name? // empty' | grep -ve '.loom$'
6fcd2c86-76dc-4cfa-8805-20f7d8f6a678.bam
58cf25fd-440a-4d33-ab94-9f7ba5a1036c.bam
fcbaa3c6-b2bf-4f87-8336-9966ac6a2bb6.bam
36ca61c4-9752-4cdf-8bac-1e8da06d9ed1.bam
c763f679-e13d-4f81-844f-c2c80fc90f46.bam
fb72f4c2-7f35-40a6-af19-9b41d0680677.bam
58a18a4c-5423-4c59-9b3c-50b7f30b1ca5.bam
c76d90b8-c190-4c58-b9bc-b31f586ec7f2.bam
bfbf2ca6-13e5-4fe0-bb03-a592e1e72648.bam
3ddf143f-36bd-49c5-9bbf-f5b71e384063.bam
24ae6c0b-d147-4051-a85b-c6204531b9d7.bam
219e1b92-9749-490c-b08a-f375ad4c9884.bam
a040dae6-e0b1-49cf-a9ee-9793d5ad7d9c.bam
294fe5d9-c1e8-4670-80d3-4c2b0a5e33c1.bam
098cc66a-d806-42db-a1c8-fa99a0317d7c.bam
d6536459-ab4e-4954-a0ce-5e6d07670039.bam
```

Expected: No output
Actual: `.bam` files are listed

**Comment by hannes-ucsc** [comment]
In the Data Browser this manifests as follows:

![image](https://user-images.githubusercontent.com/5143256/103964099-75581c00-510f-11eb-80fe-b4cedaf4459e.png)

**Comment by danielsotirhos** [comment]
These files are being included in the matrices tree because they are analysis files that have a `submitter_id` value identifying them as `DCP/2 Analysis` matrices.

Example:
```
select content from hca_dev_20201217_test4___20210107.analysis_file where analysis_file_id = 'fd774b66-9a64-5f20-a767-991691a3c72d'

{
    "describedBy": "https://schema.humancellatlas.org/type/file/6.2.0/analysis_file",
    "file_core": {
        "content_description": [],
        "file_name": "6fcd2c86-76dc-4cfa-8805-20f7d8f6a678.bam",
        "format": "bam"
    },
    "provenance": {
        "document_id": "fd774b66-9a64-5f20-a767-991691a3c72d",
        "submission_date": "2020-11-20T23:33:26.000000Z",
        "submitter_id": "e67aaabe-93ea-564a-aa66-31bc0857b707"
    },
    "schema_type": "file"
}
```

**Comment by hannes-ucsc** [comment]
For Azul not to index these files as project-level DCP/2-generated matrices (and BAM files aren't matrices), the `provenance.submitter_id` field should be dropped from the `analysis_file` entity describing them.

**Comment by hannes-ucsc** [comment]
Notified Analysis team: https://humancellatlas.slack.com/archives/C01360XN04S/p1610154595426900?thread_ts=1608070223.310900&cid=C01360XN04S

**Comment by hannes-ucsc** [comment]
This is still the case in snapshot hca_dev_20201217_test4___20210112

For a more detailed analysis see the respective issue for intermediate looms: https://github.com/DataBiosphere/azul/issues/2686#issuecomment-759819298

**Comment by hannes-ucsc** [comment]
Confirmed fixed in snapshot hca_dev_20201217_test4___20210126:

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/600a9f29-0d8b-4791-91ef-1acbe3dbfda2)
