### ISSUE TITLE
Remove prepended project UUIDs from CGM files

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#2690]

**Comment by melainalegaspi** [comment]
As @theathorn suggests, reach out to EBI to inform them about this change so they don't prepend the project UUID to future file names

**Comment by danielsotirhos** [comment]
Notified EBI to request CGM filenames are not prefixed with the project UUID. https://humancellatlas.slack.com/archives/C01360XN04S/p1611262286001700

**Comment by theathorn** [comment]
Per humancellatlas/data-browser#1500, the Data Browser will no longer remove the prepended project UUIDs in the UI.

Instead we will update the existing CGM names in the staging area.

**Comment by melainalegaspi** [comment]
Spike to estimate @danielsotirhos.

**Comment by danielsotirhos** [comment]
The staging areas gs://broad-dsp-monster-hca-prod-ucsc-storage/cgm_dcp2 and gs://broad-dsp-monster-hca-prod-ucsc-storage/cgm_dcp2ebi have been emptied and repopulated for a rename of the data files.

Snapshot requested Thursday Feb 11: https://humancellatlas.slack.com/archives/C01360XN04S/p1613073640145600

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Waiting for snapshot that includes these staging areas, the unprefixed "no-analysis" staging area, and the test analysis staging areas."
