### ISSUE TITLE
One snapshot per project

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2691]
For MVP, all primary and analysis data resides in a single TDR snapshot. Post-MVP data releases will likely consist of multiple snapshots. There might be a snapshot per combination of project, access-control status (public, access controlled) and analysis level (primary vs secondary or tertiary analysis). This will facilitate controlling access to the data as well as accelerate the process of cutting and indexing snapshots. In Azul, this data model change will manifest as a catalog consisting of multiple snapshots.

Support multiple snapshots per catalog, one per project. The snapshots should be disjunctive and completely independent i.e. without subgraphs crossing the snapshot boundary. We'll drop the second limitation in epic #2624.

**Comment by melainalegaspi** [comment]
Create sub tickets for this epic @hannes-ucsc
