### ISSUE TITLE
Add `lungmap_external` as a submitter of CGMs

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2698]
Add `fedbcffc-4ebc-54f7-8a21-fc63836ef8bb` (generated from the string `lungmap external`)  to the list of known submitter IDs.

**Comment by hannes-ucsc** [comment]
Using space in the slug was a mistake (my mistake). We should sweep it under the carpet and use `_` instead in communication.

**Comment by hannes-ucsc** [comment]
Rug, not carpet.
