### ISSUE TITLE
Add file source to hits in service response

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2705]
Expose `contents.files.source` in the `/index/{entity_type}` repsonses at `hits[].files[].source`

**Comment by hannes-ucsc** [comment]
I don't think this should be just for `/index/files` but for all entity types. I edited the title and description accordingly.

**Comment by danielsotirhos** [comment]
> I don't think this should be just for `/index/files` but for all entity types. I edited the title and description accordingly.

`hits[].files[]` is returned as part of the `/index/files` response, and not from `/index/projects` or `/index/samples` where `hits[].fileTypeSummaries[]` is populated instead.

@hannes-ucsc Should the file `source` value be added to the `fileTypeSummaries` aggregated results?

**Comment by hannes-ucsc** [comment]
> @hannes-ucsc Should the file source value be added to the fileTypeSummaries aggregated results?

I don't see a reason not to. There is nothing special about this property and it should be treated like any other property of files. The only file properties that are special are `uuid`, `version` and any hashes because aggregating them usually creates a impractically large aggregate.
