### ISSUE TITLE
Remove subscribe stage from gitlab

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2710]
Gitlab runs a `subscribe` stage that was to subscribe to DSS notifications, as the DSS deployments have been torn down, this stage can be removed.

**Comment by amarjandu** [comment]
consider cleaning the `Makefile` for the subscribe operation as well.

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "This will be covered by the removal of the DSS plugin."
