### ISSUE TITLE
Reword Matrix descriptions for DCP 2.0 files

### ISSUE THREAD

**Issue by ekiernan** [DataBiosphere/azul#2713]
The description of the DCP-generated matrices for the newly processed data will need to change as the previous description is only applicable to DCP 1. 

The **previous description** reads:

"The 10x matrices include raw counts; Smart-seq2 matrices include TPMs. Matrices are in CSV, MTX, and Loom formats."

The **new description** should be: 

"The 10x matrices include raw counts; Smart-seq2 matrices include TPMs and estimated counts. Matrices are in Loom file format."

**Comment by theathorn** [comment]
Incorrect repo - closing in favor of humancellatlas/data-browser#1488.
