### ISSUE TITLE
Parameterize PortalService instances with current catalog

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#2716]
`PortalService` currently uses the default catalog in several places where it should instead rely on a catalog parameter.  Once the `PortalService` class is catalog-aware, a method should be added that accepts a `CatalogName` and returns either the current DSS stage or a has of the current TDR source depending on the active plugin.

The method should be called "catalog_source". It's return value should be included in the service response by the endpoint that's added by #2066, as `.catalogs[*].source`.

**Comment by hannes-ucsc** [comment]
Portal registration API is deprecated (#6782).
