### ISSUE TITLE
Preparation for a discussion with the Carter Group concerning NIST 800-53 compliance

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2723]
@nolunwa "spoke to the Anthony (Carter Group) about the HCA project and they are open to us scheduling a scoping meeting to discuss  and understand the system architecture. Hannes can ask questions and we can determine if Carter group is a good fit. It would be useful to send to Carter group a brief summary of the HCA DCP system and specific questions about the system architecture that Hannes will have so Anthony can know who to invite and prep so the meeting will be productive."

Document: "[Compliance Discussion with the Carter Group](https://docs.google.com/document/d/1nU-AW1aY9xsrJJC0n_1E2DBf4588k9om71d13piSLxc)".

**Comment by theathorn** [comment]
@hannes-ucsc I've added a "Questions" section to the foot of the discussion document (linked in the description above).

**Comment by hannes-ucsc** [comment]
Questions added, changes suggested.

**Comment by theathorn** [comment]
Document sent to @nolunwa - closing.
