### ISSUE TITLE
Add ability to remove a source from a catalog

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2748]
We'll be asked to support "updated" snapshot. This requires removing one snapshot from the catalog and adding another one to replace it. This ticket is about removing all entities that originated from a given source aka snapshot. With one snapshot per project, subgraphs (bundles) will not span snapshot boundaries, so we do not need to worry about reversing the effect of contributions in the same way we do for bundle deletions. We can simply delete all contributions and all aggregates from the indices belonging to a catalog.

Add an `--deindex <source> [<source> …]` command flag to `reindex.py`. It should be mutually exclusive with `--delete`, `--index` and `--create`.

Introduce a new `deindex` notification using the same partitioning as for `reindex`.

Handle the notification by issuing delete by query requests against ES, comparing the `repository_source` field against the source in the notification.

In #2766, we parameterized the `reindex` script with an optional source argument. If the source argument was given, run invoke `reindex.py --deindex` for the given source.

Variations: 

- Lookup the source ID (snapshot ID for TDR) for a given source name before sending out notifications. Compare against `repository_source_id` instead of `repository_source`

- Additionally partition notification by entity_type and/or aggregate vs contribution

**Comment by jessebrennan** [comment]
How do we reconcile this with the sources listed in the environment? I will bring this up in PL.

**Comment by jessebrennan** [comment]
I'm using the "delete by query API" for this. The API provides [slices](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-delete-by-query.html#docs-delete-by-query-slice) to parallelize and speed up deletions. Docs recommend using slices equal to the number of shards (and have an option for that---auto). 

> Query performance is most efficient when the number of slices is equal to the number of shards in the index. [...] Setting slices higher than the number of shards generally does not improve efficiency and adds overhead.

[source](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-delete-by-query.html#docs-delete-by-query-picking-slices)

This makes me wonder if we should even be using our own the prefix for the deletions or if it will just slow things down. I think testing best solution here, but I want to bring this up in PL before I get too far in either direction.

**Comment by jessebrennan** [comment]
@hannes-ucsc: "Start with the simplest solution: making a single delete by query on the machine that runs `reindex.py --deindex` with automatic slices enabled. Test this with personal deployment the same size as dev. If using `--deindex` `*` is not allowed for sources."

**Comment by hannes-ucsc** [comment]
For demo, show how to use this facility to deindex the managed access snapshot in `dev` and then index it again. In between show that the MA project is gone after deindexing and reappears 100% identically after indexing. Make all service requests as a user that has access to the MA snapshot.
