### ISSUE TITLE
Switch from Travis to GitHub Actions for CI

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2768]

**Comment by amarjandu** [comment]
Might be nice to also investigate the cost we might see by switching over.

**Comment by amarjandu** [comment]
Useful links:

https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Comment by melainalegaspi** [comment]
Spike to gather:
1. Separate jobs within a pipeline
2. Artifacts // Caching between jobs

**Comment by amarjandu** [comment]
3. Can we supply our own images to avoid building dependencies for each job run?

**Comment by melainalegaspi** [comment]
@jessebrennan spike to answer: 
1. Can we run ES docker containers on GitHub actions?
2. What are the rate limits on the free account, should we upgrade to the paid account? (currently we're paying $250 for 5 concurrent jobs)
3. Is there the ability to retry submission of coverage data to coveralls and codecov?
4. Is python 3.82 supported?
5. How much memory is avalable and how many cores are available?

**Comment by jessebrennan** [comment]
>Can we run ES docker containers on GitHub actions?

>What are the rate limits on the free account, should we upgrade to the paid account? (currently we're paying $250 for 5 concurrent jobs)

As best I can tell, there are no limits for public repos. Obviously there must be some limitations to prevent abuse, but I haven't found documentation yet on this.

>Is there the ability to retry submission of coverage data to coveralls and codecov?

>Is python 3.82 supported?

>How much memory is available and how many cores are available?

2-core CPU
7 GB of RAM memory
14 GB of SSD disk space

 Source https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
