### ISSUE TITLE
Move staging area validation tool to separate repository

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2772]
DataBiosphere/hca-importer-validation

**Comment by danielsotirhos** [comment]
Insufficient permissions to create a repository in DataBiosphere.
![Screen Shot](https://user-images.githubusercontent.com/46407464/107686323-eda78500-6c59-11eb-8d8c-b5b7107e07f4.png)

**Comment by danielsotirhos** [comment]
Staging area validator tool added to https://github.com/DataBiosphere/hca-import-validation
