### ISSUE TITLE
Process CGMs in Feb-2021 spreadsheet

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2779]
Process the CGMs described [here](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY) into the appropriate metadata files in the production staging area.

**Comment by danielsotirhos** [comment]
https://humancellatlas.slack.com/archives/C01360XN04S/p1614039709027500?thread_ts=1614018617.020800&cid=C01360XN04S

All files from the [02-2021 spreadsheet](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY) have been added into the `gs://broad-dsp-monster-hca-prod-ucsc-storage/cgm_dcp2ebi` staging area

**Comment by danielsotirhos** [comment]
Confirmed the CGM from the [02-2021 spreadsheet](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY) are available in the prod Data Browser catalog `dcp3` . Example projects: [d3a4ceac](https://data.humancellatlas.org/explore/projects/d3a4ceac-4d66-4984-9704-2570c0647a56/expression-matrices?catalog=dcp3), [559bb888](https://data.humancellatlas.org/explore/projects/559bb888-7829-41f2-ace5-2c05c7eb81e9/expression-matrices?catalog=dcp3), [c1810dbc](https://data.humancellatlas.org/explore/projects/c1810dbc-16d2-45c3-b45e-3e675f88d87b/expression-matrices?catalog=dcp3)

**Comment by theathorn** [comment]
For demo show all (15) projects from the 2nd spreadsheet that have CGMs in the Data Browser.

**Comment by danielsotirhos** [comment]
When the [02-2021 spreadsheet](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY) was originally used with the CGM Adapter (Feb 22) there were 57 rows consisting of 13 projects. Since then the spreadsheet has now been expanded to 75 rows consisting of 18 projects.

The original 13 projects UUIDs are:
```
1c6a960d-52ac-44ea-b728-a59c7ab9dc8e
3089d311-f9ed-44dd-bb10-397059bad4dc
41fb1734-a121-4616-95c7-3b732c9433c7
455b46e6-d8ea-4611-861e-de720a562ada
559bb888-7829-41f2-ace5-2c05c7eb81e9
6c040a93-8cf8-4fd5-98de-2297eb07e9f6
996120f9-e84f-409f-a01e-732ab58ca8b9
9d97f01f-9313-416e-9b07-560f048b2350
c1810dbc-16d2-45c3-b45e-3e675f88d87b
c893cb57-5c9f-4f26-9312-21b85be84313
ce33dde2-382d-448c-b6ac-bfb424644f23
d3a4ceac-4d66-4984-9704-2570c0647a56
efea6426-510a-4b60-9a19-277e52bfa815
```
