### ISSUE TITLE
Terra.bdbag IT fails if manifest has 1 row

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2790]
The Integration test fails when testing the `terra.bdbag` format manifest if the manifest contains only 1 row.

This bug is caused by `header, *rows = rows` which is taking the first row out of `rows` to parse out the headers, leaving `rows` empty in the case of a 1 row manifest.

**Comment by hannes-ucsc** [comment]
Reproduction needed. Or link to failed CI/CD job.

**Comment by danielsotirhos** [comment]
Making ticket a freebie of #2537, PR #2782

**Comment by danielsotirhos** [comment]
> Reproduction needed. Or link to failed CI/CD job.

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/9721

Note 2 failures:
- `2021-02-12 01:14:01,282 INFO    MainThread: Failed sub-test [manifest] {'catalog': 'it3lungmap', 'format': 'terra.bdbag', 'attempts': 1}`
- Timeout after `2021-02-12 01:14:02,055 INFO    MainThread: GET https://storage.googleapis.com/broad-jade-dev-data-bucket/e39f9182...attachment%3B+filename%3DBatch1_read2.fastq.gz`
