### ISSUE TITLE
Remove `organismAgeUnit` term facet

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2796]
The recently added `organismAge` facet combines the both unit and value. There is no use case for listing distinct age range units or age range values independently from each other. Even if there was a valid use case, these lists could be derived client-side from the `organismAge` facet.

Remove both facets and any index fields that solely exist to back them.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to fill in details.

**Comment by hannes-ucsc** [comment]
Spike done.

**Comment by hannes-ucsc** [comment]
For demo, show that the facet is absent from index endpoints.
