### ISSUE TITLE
Lungmap fastq files have format value 'text/fastq'

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2798]
Fastq files in the `lungmap` catalog have the `file_core.format` value of `text/fastq`.
These files should have a format value that matches the extension of the file (eg. `fastq.gz` for the file `Batch2_run1_read1.fastq.gz`)

**Comment by melainalegaspi** [comment]
@theathorn talked to Eric Bardes to change the file format to fastq.gz

**Comment by theathorn** [comment]
Confirmed "File Format" is now "fastq.gz" in [data browser](https://data-browser.dev.lungmap.net/explore/files?filter=%5B%7B%22facetName%22:%22projectId%22,%22terms%22:%5B%221bdcecde-16be-4208-88f4-78cd2133d11d%22%5D%7D,%7B%22facetName%22:%22fileFormat%22,%22terms%22:%5B%22fastq.gz%22%5D%7D%5D).
