### ISSUE TITLE
Lungmap catalog specimens have UUID for biomaterial_id

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#2799]
`specimen_from_organism` documents in the `lungmap` catalog duplicate their `provenance.document_id` value for their `biomaterial_core.biomaterial_id`.
To match values from other catalogs, the `biomaterial_core.biomaterial_id` should be a short descriptive name that uniquely identifies the specimen in the project. Examples: `PP011`, `DID_scRSq02_pancreas`, `Human_S4_UC_inflammed_colon`

**Comment by melainalegaspi** [comment]
@theathorn: "Lungmap stated that the UUID was taken from their system."

**Comment by theathorn** [comment]
I confirmed with Eric Bardes.
