### ISSUE TITLE
Add feature to reindex multiple specific bundles

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2803]
Currently there is no easy way to reindex multiple specific bundles.

**Comment by amarjandu** [comment]
A single bundle UUID can be passed as a prefix to `python scripts/reindex.py --index --prefix $UUID`. But if you have multiple bundles that you want to index (say all bundles for a project), you would have to wait for each bundle to complete, before explicitly calling the next bundle.

**Comment by amarjandu** [comment]
Here is a short discussion about this feature on Slack. https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1613155204260700
@hannes-ucsc has a suggestion for the approach within that thread.

**Comment by hannes-ucsc** [comment]
I haven't come across a single case in several years where I would have needed this.
