### ISSUE TITLE
Review FedRAMP POA&M

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2810]
[ [Gap Analysis] FedRAMP-POAM for Azul System Nov 2021](https://docs.google.com/spreadsheets/d/15aJIPlZHp-VIr_e3sCpcScVp0NIgfeAihciiQFNRhmU).

~[[Initial Draft] FedRAMP-POAM HCA DCP Data Browser System](https://docs.google.com/spreadsheets/d/1ghnkCJxkcLhpAaF3dclTubXhXmRWe316kLiRXXfEz8Y).~

**Comment by melainalegaspi** [comment]
@nolunwa to notify @hannes-ucsc and/or @theathorn when ready for review.

**Comment by nolunwa** [comment]
@theathorn @hannes-ucsc AC, AT, AU and CM controls in the POA&M is ready for review

**Comment by theathorn** [comment]
[Directory](https://drive.google.com/drive/folders/1BeqPadIgCqaCW0gBKFMvHLShGxLmGZuA) for Policy and Procedure docs.
