### ISSUE TITLE
Retrieve Matrix Service technical documentation

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2811]
The Matrix service documentation used to be located [here](https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/matrix-service/wikis/Technical-Architecture), but this link is invalid following the decommission of DCP/1.

@amarjandu : "There is a volume snapshot for both allspark-prod and allspark-dev on our UCSC AWS account, we might be able to mount these to an ec2 instance and get information out, are they just looking for Matrix-Service documentation?"

**Comment by amarjandu** [comment]
Attached is a folder containing all the missing architecture documents that were linked above.
[matrix-service-arch.zip](https://github.com/DataBiosphere/azul/files/6024969/matrix-service-arch.zip)

**Comment by theathorn** [comment]
Zip file satisfies this ticket's requirement.
