### ISSUE TITLE
`IndexerTestCase` uses DSS repository plugin

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2817]
https://github.com/DataBiosphere/azul/blob/8e01b48c82752599ec7c91e13558edbd3fb82a30/test/indexer/__init__.py#L103
This should probably be changed to TDR.

A more accurate title may be "Indexer tests use DSS bundles," but I wasn't sure so I'm leaving it as is.

It's possible this is a dupe of #2610, but again I wasn't sure.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Not a dupe of #2610."

**Comment by hannes-ucsc** [comment]
Some test cases use the DSS plugin, others use the TDR. Superseded by #6785.
