### ISSUE TITLE
Evaluate and respond to proposed metadata schema changes

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2821]
[Evolving the schema](https://docs.google.com/document/d/1Z4dJJrcgWRMRAdb4dXY9mTjU4EacUUmeH9PmS481rHY)

..with particular emphasis on the section "Key changes to the schema that we want to prioritise" / "Minor changes intended for first iteration".

..and [Evolving HCA Metadata Schema for Contributor-Generated [](Matrices](https://docs.google.com/document/d/1AaE0RCXOhvU8bOT2Tf9G3-0M1mKmlqOZRbubyS8uo4o))

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Focus on schema changes, not update mechanism."

**Comment by melainalegaspi** [comment]
@hannes-ucsc to link to the merged PRs and close this ticket.

**Comment by hannes-ucsc** [comment]
Spec: https://github.com/HumanCellAtlas/dcp2/pull/9
Schema: https://github.com/HumanCellAtlas/metadata-schema/pull/1371
Test data: https://github.com/HumanCellAtlas/schema-test-data/pull/8
