### ISSUE TITLE
Remove organismAgeValue term facet from service response

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#2824]
The term facets `organismAgeUnit` & `organismAgeValue` should be removed from the service response. The information provided by these fields can be reconstructed from the term facet `organismAge` which will remain in the response.

Ideally, this issue gets addressed in parity with or after #2254, removing these facets without addressing filtering will reduce the test coverage.

**Comment by theathorn** [comment]
@hannes-ucsc to fill in details/solution. Reminder: filtering.

**Comment by hannes-ucsc** [comment]
It makes sense to be able to filter by organism age unit and value. A user might want to see all samples from a donor A) whose unit was measured in years, or B) whose age is one, no matter the unit. The latter use case (B) is less useful. For every filterable field, we should include a termFacet entry that shows the possible values one can filter by. For high-cardinality fields (like biomaterial_id) this isn't practical but age unit is a low cardinality field. Age value could end up being a high cardinality field, given enough donors. That and the lower likelihood of use case B suggests that we should remove only the `organismAgeValue` facet, filter and underlying index field.

> Ideally, this issue gets addressed in parity with or after #2254, removing these facets without addressing filtering will reduce the test coverage.

Don't understand this. To be discussed during triage.

**Comment by hannes-ucsc** [comment]
Should also adjust the title if we decide to only remove `organismAgeValue`.

**Comment by achave11** [comment]
> > Ideally, this issue gets addressed in parity with or after #2254, removing these facets without addressing filtering will reduce the test coverage.

>Don't understand this. To be discussed during triage.

Resolved during parking lot. #2255 does't fully apply.

**Comment by hannes-ucsc** [comment]
@achave11 to ask DB team if this field is still being used.

**Comment by hannes-ucsc** [comment]
For demo, show that index field and affected response properties (hits, termFacets, and so on) are gone.
