### ISSUE TITLE
Backup allspark git repositories for dev and prod

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2828]

**Comment by theathorn** [comment]
@hannes-ucsc to decide where to put backup.

**Comment by hannes-ucsc** [comment]
Put both archives into this bucket: edu-ucsc-gi-orange-backup-dev. Then assign ticket to me,

I will create a corresponding prod bucket and move the prod archive into that bucket.

**Comment by amarjandu** [comment]
both archives for HCA repositories have been uploaded to the `edu-ucsc-gi-orange-backup-dev` bucket.
