### ISSUE TITLE
Return a 'Not Found' error response if the webservice url is invalid or misspelled

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#283]
Currently, if a user tries to access the webservice using an invalid endpoint such as '/repository/non-existing-entity', the webservice returns a 403 with the following message.
```
{
     message: "Missing Authentication Token"
}
```
The web service should return a 'Not Found' (404) response instead.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-187)
┆Project Name: azul
┆Issue Number: AZUL-187

**Comment by theathorn** [comment]
Dup of #448.
