### ISSUE TITLE
Clean up old versions of portal database in S3

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2830]
The portal registration integration tests generates a very large number of object versions. These should eventually be cleaned up.

**Comment by hannes-ucsc** [comment]
This should be done only for non-main deployments. In main deployments, every version should be retained. That IT isn't run there so they don't accumulate large number of objects.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Assignee to create an S3 lifecycle policy that expires old versions after a configureable time. This policy should only be enabled on personal deployments and the sandbox. The expiration should be 1 month."

**Comment by noah-aviel-dove** [comment]
The portal registration databases are all stored in the versioned bucket. This bucket is shared between the personal deployments and dev and is not managed by terraform (it is created manually during "3.1 One-time provisioning of shared cloud resources" in the README). As such I don't think a programmatic lifecycle policy will work because:

1. We would need to manage the bucket via terraform which would make possible to alter the shared bucket when deploying from a personal deployment
2. I suspect (have not confirmed) that the `prefix` field for the lifecycle policy is not advanced enough to filter out personal deployments from main deployments (we would need some kind of regex), and this seems to be our only tool for selectively applying the policy within the shared bucket.

**Comment by hannes-ucsc** [comment]
LIfe-cycle rules can filter on object tags. Think about how you could utilize that here.

**Comment by hannes-ucsc** [comment]
For demo, wait until 35 days after successful last successful sandbox build of this PR. Show that tags are applied to versions and that no versions older than 30 days exists. Show that versions were created between 31 and 35 days before demo date.

**Comment by noah-aviel-dove** [comment]
@noah-aviel-dove to open support ticket with AWS. Ticket should emphasize contradiction between S3 API, console, and lifecycle policy.

**Comment by noah-aviel-dove** [comment]
Can't reproduce the weirdness described above. For the portal objects in my personal deployment, the oldest extant version is only 32 days old, and most of the objects have been pruned down to only one version. To me this indicates that the lifecycle is working as intended, albeit with a certain degree of latency.

Here is the output of the script I use for analyzing the portal versions:

```
source key      #versions       oldest  newest  (newest - oldest)       (now - oldest)
129438cf30e00139424eea022435d711        1       2021-10-16 09:15:03     2021-10-16 09:15:03     0:00:00 123 days
4a7a09c68b75c75e855cc078dbaf51c4        1       2021-11-11 07:11:49     2021-11-11 07:11:49     0:00:00 97 days
5a7da4609f06015960be04818f22a3ca        1       2021-10-01 08:00:14     2021-10-01 08:00:14     0:00:00 138 days
5b172f18ced8c278b6f017db1486c534        406     2022-02-02 04:16:05     2022-02-03 00:07:34     19:51:29        14 days
6b1c9189ede1de182567d792ec8aac81        4551    2022-01-15 06:31:12     2022-02-16 03:14:01     31 days 32 days
75fc0295a9bc8d4105a50deb76d3f00c        1       2021-10-21 03:38:33     2021-10-21 03:38:33     0:00:00 118 days
84e00e4797b73b1b4417c509aae87789        1       20
21-09-22 04:13:01     2021-09-22 04:13:01     0:00:00 147 days
932771abcb7abf2bcdd247a7da01ea6b        1       2021-10-15 02:26:28     2021-10-15 02:26:28     0:00:00 124 days
981fb0ac2aa6b1868cb95737f54cb8fc        1       2021-11-03 23:57:06     2021-11-03 23:57:06     0:00:00 104 days
a017995285b835ffc4cec88b441a22a0        304     2022-01-20 23:19:44     2022-01-21 02:00:47     2:41:03 26 days
```

[source code](https://github.com/DataBiosphere/azul/files/8083652/2830.txt)

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "The above comment serves as our demo."
