### ISSUE TITLE
Move "DCP/2 System Design" document to markup in a GitHub repository

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2837]
Google [doc](https://docs.google.com/document/d/1NsibP8g-NeLnksxlcBWQsSj5Zg_uimCDaAF1qB_qkjg) to move.

**Comment by melainalegaspi** [comment]
Will assign to someone who knows reStructuredText during Triage.

**Comment by theathorn** [comment]
Should we move this repo to the HumanCellAtlas organization instead of DataBiosphere?
Otherwise we will have to authorize a bunch of EBI folks in DataBiosphere in order for them to submit PRs.

**Comment by hannes-ucsc** [comment]
I thought that org was going away. Anyways, we could move it there. Will need to decide on name (since hca- prefix would be redundant there). Then again, we could make it so anyone can file a PR against the repo. So it doesn't have to move.

**Comment by jessebrennan** [comment]
@theathorn @hannes-ucsc, now that https://github.com/DataBiosphere/hca-dcp#2 is merged, can we move this ticket to the merged or dev column?
