### ISSUE TITLE
Digests printed by build_image and other jobs don't match

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2844]
For this one build image tagged `1299`

<img width="1001" alt="Screen Shot 2021-03-01 at 1 08 19 PM" src="https://user-images.githubusercontent.com/1947534/109559260-4ca92e80-7a8f-11eb-82d6-f08ab43cb658.png">

the `build_image` job prints the manifest digest

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/10802#L103

while `setup` and subsequent jobs print the configuration digest 

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/10803#L7

That makes it hard to scrutinize build output and diagnose issues.

**Comment by hannes-ucsc** [comment]
Solution is probably to log both digest in `build_image`.

**Comment by hannes-ucsc** [comment]
Fixed now:

![CleanShot 2024-12-21 at 16 48 13@2x](https://github.com/user-attachments/assets/97c5ab6d-9177-47e7-883f-d525fa4b42a5)

![CleanShot 2024-12-21 at 16 48 38@2x](https://github.com/user-attachments/assets/b1360218-23fe-4d57-8271-922af817b411)
