### ISSUE TITLE
High level design of an ingest broker for managed access data

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2854]
The wrangling team (Clay + Parisa) work with submitters to generate HCA metadata spreadsheets along with the associated data files.
We need a process to convert the spreadsheet + data into the HCA staging are format.
This all needs to be done in a secure/compliant environment (potentially a Docker image running in Terra?).
We need to investigate what (if any) existing HCA ingest code could be repurposed for this.
Initial volume is expected to be very low (initially a few managed access projects).

**Comment by hannes-ucsc** [comment]
Not needed anymore.
