### ISSUE TITLE
Add facet for distinguishing matrix levels

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2860]
Add `hits[*].files[*].isIntermediate` and a corresponding `termFacets.isIntermediate` to to all endpoints. The value is an optional boolean that is 

- `true` for intermediate DCP/2 matrices (those without the dedicated `submitter_id`), 
- `false` for CGMs and project-level DCP/2 matrices (those with the dedicated `submitter_id`),
- `null` for any other file

Discuss with me how to implement this on endpoints that have `hits[*].fileTypeSummaries` instead of `hits[*].files`.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to spike for spec. _

**Comment by theathorn** [comment]
See HumanCellAtlas/data-browser#1595

**Comment by hannes-ucsc** [comment]
Spike done.

**Comment by hannes-ucsc** [comment]
For demo, show new field in all index endpoint responses with special attention to grouping.
