### ISSUE TITLE
Timeout/OOM for some subgraphs in snapshot hca_prod_20201120_dcp2___20210302

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2868]
The contribute lambda times out or runs out of memory for the following subgraphs

- `6a4dda81-d6c9-5be8-8608-c685eef62754`
- `fce68057-b0f0-5d11-b9a7-30e8fa3259a8`
- `79fa91b4-f1fc-534b-a935-b57342804a70`
- `93787442-244e-5d8a-a35e-f71646c26eab`
- `9697e762-96f2-5949-af7e-12fb4c4f22d0`
- `fd3f0e8e-d04c-53ca-b6c0-8e5baef5bf38`
- `4f7887aa-6ef8-5aa4-93f8-4eb42d2f4e7d`

For example, for `6a4dda81-d6c9-5be8-8608-c685eef62754` it times out

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/snippets/18

**Comment by hannes-ucsc** [comment]
After temporarily bumping the contribute lambda to 4096 MiB of memory and 15min timeout, four of the seven subgraphs were indexed quickly. The remaining three did not timeout or run out of memory either, but tripped another limit:

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-indexer-prod-contribute  
start-time: -10800s  
end-time: 0s  
query-string:
```
fields @timestamp, notification.match.bundle_uuid, @message
| filter @message like 'Worker failed'
# | filter @message not like 'MemoryError'
| filter @message like /93787442-244e-5d8a-a35e-f71646c26eab|9697e762-96f2-5949-af7e-12fb4c4f22d0|6a4dda81-d6c9-5be8-8608-c685eef62754/
# | filter @message like /Worker successfully handled|Worker handling|Worker failed/
# | filter @message like /Task timed out after|MemoryError/
# | filter @message like /START|END/
# | filter @requestId == '4792c56a-b3f2-5ef1-bdb3-9dd6e41f4f93'
# | filter @logStream like '2021/03/05/[$LATEST]e984d7a9f74746c7aa4728a18b482bea'
| limit 3
| sort @timestamp, asc
```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |    notification.match.bundle_uuid    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             @message                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|-------------------------|--------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2021-03-05 20:03:52.353 | 9697e762-96f2-5949-af7e-12fb4c4f22d0 | [WARNING] 2021-03-05T20:03:52.352Z 8ff848b1-27c6-5acf-ad3f-100da927ea0f Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': 'a9b3ba0b-e17b-4404-a686-3c8c33899d12', 'name': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210302'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '1dab3b26-2434-49e9-8a70-e89a3a6dd6f2', 'match': {'bundle_uuid': '9697e762-96f2-5949-af7e-12fb4c4f22d0', 'bundle_version': '2021-02-08T10:30:00.000000Z'}}, 'catalog': 'dcp3'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 147, in contribute     tallies = self.index_service.contribute(catalog, contributions)   File "/var/task/azul/indexer/index_service.py", line 202, in contribute     writer.write(contributions)   File "/var/task/azul/indexer/index_service.py", line 569, in write     self._write_bulk(documents)   File "/var/task/azul/indexer/index_service.py", line 608, in _write_bulk     for success, info in response:   File "/opt/python/elasticsearch/helpers/actions.py", line 218, in streaming_bulk     for data, (ok, info) in zip(   File "/opt/python/elasticsearch/helpers/actions.py", line 113, in _process_bulk_chunk     raise e   File "/opt/python/elasticsearch/helpers/actions.py", line 109, in _process_bulk_chunk     resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)   File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped     return func(*args, params=params, **kwargs)   File "/opt/python/elasticsearch/client/__init__.py", line 1556, in bulk     return self.transport.perform_request(   File "/opt/python/elasticsearch/transport.py", line 351, in perform_request     status, headers_response, data = connection.perform_request(   File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request     self._raise_error(response.status_code, raw_data)   File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error     raise HTTP_EXCEPTIONS.get(status_code, TransportError)( elasticsearch.exceptions.TransportError: TransportError(413, '{"Message":"Request size exceeded 104857600 bytes"}') |
| 2021-03-05 20:07:22.109 | 93787442-244e-5d8a-a35e-f71646c26eab | [WARNING] 2021-03-05T20:07:22.107Z c89bdb74-6e55-5266-b0ab-83c8e081adb0 Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': 'a9b3ba0b-e17b-4404-a686-3c8c33899d12', 'name': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210302'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '123a678c-3293-4149-b8bc-6e2cd362ebcc', 'match': {'bundle_uuid': '93787442-244e-5d8a-a35e-f71646c26eab', 'bundle_version': '2021-02-04T10:00:00.000000Z'}}, 'catalog': 'dcp3'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 147, in contribute     tallies = self.index_service.contribute(catalog, contributions)   File "/var/task/azul/indexer/index_service.py", line 202, in contribute     writer.write(contributions)   File "/var/task/azul/indexer/index_service.py", line 569, in write     self._write_bulk(documents)   File "/var/task/azul/indexer/index_service.py", line 608, in _write_bulk     for success, info in response:   File "/opt/python/elasticsearch/helpers/actions.py", line 218, in streaming_bulk     for data, (ok, info) in zip(   File "/opt/python/elasticsearch/helpers/actions.py", line 113, in _process_bulk_chunk     raise e   File "/opt/python/elasticsearch/helpers/actions.py", line 109, in _process_bulk_chunk     resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)   File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped     return func(*args, params=params, **kwargs)   File "/opt/python/elasticsearch/client/__init__.py", line 1556, in bulk     return self.transport.perform_request(   File "/opt/python/elasticsearch/transport.py", line 351, in perform_request     status, headers_response, data = connection.perform_request(   File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request     self._raise_error(response.status_code, raw_data)   File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error     raise HTTP_EXCEPTIONS.get(status_code, TransportError)( elasticsearch.exceptions.TransportError: TransportError(413, '{"Message":"Request size exceeded 104857600 bytes"}') |
| 2021-03-05 20:07:51.406 | 6a4dda81-d6c9-5be8-8608-c685eef62754 | [WARNING] 2021-03-05T20:07:51.400Z b30c3383-9446-5ae8-aa43-6b3f1a902a28 Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': 'a9b3ba0b-e17b-4404-a686-3c8c33899d12', 'name': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210302'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '50e97f10-697d-46cb-8fcf-584f7b7cac24', 'match': {'bundle_uuid': '6a4dda81-d6c9-5be8-8608-c685eef62754', 'bundle_version': '2021-02-04T10:00:00.000000Z'}}, 'catalog': 'dcp3'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 147, in contribute     tallies = self.index_service.contribute(catalog, contributions)   File "/var/task/azul/indexer/index_service.py", line 202, in contribute     writer.write(contributions)   File "/var/task/azul/indexer/index_service.py", line 569, in write     self._write_bulk(documents)   File "/var/task/azul/indexer/index_service.py", line 608, in _write_bulk     for success, info in response:   File "/opt/python/elasticsearch/helpers/actions.py", line 218, in streaming_bulk     for data, (ok, info) in zip(   File "/opt/python/elasticsearch/helpers/actions.py", line 113, in _process_bulk_chunk     raise e   File "/opt/python/elasticsearch/helpers/actions.py", line 109, in _process_bulk_chunk     resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)   File "/opt/python/elasticsearch/client/utils.py", line 84, in _wrapped     return func(*args, params=params, **kwargs)   File "/opt/python/elasticsearch/client/__init__.py", line 1556, in bulk     return self.transport.perform_request(   File "/opt/python/elasticsearch/transport.py", line 351, in perform_request     status, headers_response, data = connection.perform_request(   File "/opt/python/elasticsearch/connection/http_requests.py", line 161, in perform_request     self._raise_error(response.status_code, raw_data)   File "/opt/python/elasticsearch/connection/base.py", line 229, in _raise_error     raise HTTP_EXCEPTIONS.get(status_code, TransportError)( elasticsearch.exceptions.TransportError: TransportError(413, '{"Message":"Request size exceeded 104857600 bytes"}') |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by melainalegaspi** [comment]
@hannes-ucsc to spike for spec.

**Comment by hannes-ucsc** [comment]
The solution should be to 

1) replicate for contribution what we do for aggregation (add a retry queue and a lambda consuming it) and 
2) fix the request size issue

Re 2:

The chunk size is currently hard-coded to 10485760 (10MiB) which is less than the [AWS request size limit](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html#network-limits) of 100 MiB for the instance type we happen to be using. We should extract a constant attribute into Config and add a comment explaining the connection with the AWS limit. 

I generated all contributions for one of the offending bundles locally. It is an analysis bundle for a project level matrix. There are two contributions that stand out. A bundle and a project contribution:

![image](https://user-images.githubusercontent.com/5143256/110259394-4f5ac680-7f5c-11eb-936c-791d65c106c3.png)

With 131 MiB the bundle contribution not only bigger than the current max_chunk_size but also bigger than the maximum `max_chunk_size` that would be allowed by the AWS request size limit. The 2nd largest contribution is for the project and 254 KiB in size. Looking at the bundle contribution, two inner entity types stick out: files and metadata:

![image](https://user-images.githubusercontent.com/5143256/110259461-84ffaf80-7f5c-11eb-98cc-b55a622a73c4.png)

The project contribution has the same files:

![image](https://user-images.githubusercontent.com/5143256/110259488-bf694c80-7f5c-11eb-91e8-dd2bfbd92190.png)

This can only mean that it is the `metadata` inner entity that contributes the bulk of the 131 MiB size of that contribution.

I think the solution for 2) is to mark entities from stitched on bundles (subgraphs) and suppress any redundant contributions and inner entities, especially for the `metadata` inner entity. Specifics to follow.

**Comment by hannes-ucsc** [comment]
More on 2)

Only emit contributions for entities that are contained in the root bundle, not any stitched on bundles. This will greatly cut down on the number of contributions, probably even below the bulk threshold.

When generating one contribution (the outer entity) some transformers simply iterate over all entities of a particular type in order to find the starting entities for graph traversal That iteration should be limited to entities from the root bundle. This will greatly reduce the number of inner file entities.

When traversing the graph beginning at a starting entity, the traversal should NOT be limited, allowing entities from stitched on bundles to be traversed.

The key is how to distinguish between entities from stitched on bundles and entities from the root bundle. I think (and I am open to alternative ideas) we may need to stash the original bundle UUID and version in each document's manifest entry so that we can extract them later and set attributes of the API entity instance (`bundle_uuid` and `bundle_version`). The Entity constructor would have to be extended to accept the bundle UUID and version. If a manifest entry does not contain bundle UUID and version (presence of only one of them should result in an error) the UUID and version of the root bundle should be used. This will establish backwards compatibility.

**Comment by hannes-ucsc** [comment]
The queue reset function wasn't updated to include the new retry notifications queue:

https://github.com/DataBiosphere/azul/blob/eb61eee2652b57a117e768d112604a1948fc3663/src/azul/queues.py#L434

**Comment by hannes-ucsc** [comment]
Note that the same function also has an residual brittle coupling to the lambda name. The brittle coupling we can live with for a bit but not resetting the retry notifications queue we cannot. I will adjust blocking relationship accordingly.
