### ISSUE TITLE
Curl manifest expires after one hour

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#2875]
https://github.com/nunofonseca/fastq_utils/issues/12#issuecomment-774050310

Not sure this is valid, but we should check.

**Comment by melainalegaspi** [comment]
@achave11 to validate this ticket.

**Comment by theathorn** [comment]
@hannes-ucsc Per humancallatlas/data-browser#1565 "The manifest link is valid for seven days, not just one hour", so should we close this ticket?

**Comment by danielsotirhos** [comment]
Signed url has 1 hour expirattion.
![Screen Shot 2021-03-10 at 12 06 42 PM](https://user-images.githubusercontent.com/46407464/110690709-1c514680-8199-11eb-80f1-71b8366815df.png)

**Comment by melainalegaspi** [comment]
@achave11 to verify the hypothesis that we can use the original manifest url instead of the signed one in the curl command line without causing the manifest to be recreated.

**Comment by achave11** [comment]
Spike:

Requesting the manifest from /fetch/manifest/files as DB does, generates a new pre-signed URL pointing at the cached manifest. The request takes about 7/10 of a second.

Another viable solution is to increase the expiration time of the URL that provisions the manifest. 
In a personal deployment experiment, extending the expiration time for the manifest by four hours, allowed for the manifest to be returned at an hour and eight minutes after the original request. It was also valid after 2 hours from original request.

**Comment by achave11** [comment]
Spike cont'd:

Requesting a `curl` manifest from service, without specifying any filters also returns a cached manifest. This request takes 9.340s to execute and the execution time is consistent over three requests on a one day period.

**Comment by achave11** [comment]
Solution:

The location of the generated `curl` manifest (via `/fetch/manifest/files`) needs to point back to `/manifest/files` for Azul to handle the file provisioning. This would remove expiration issues from using pre-signed URLs. This implies `curl` manifest needs to handle redirects.

**Comment by achave11** [comment]
Estimate increase with approval of @hannes-ucsc.

**Comment by hannes-ucsc** [comment]
For demo, prepare a manifest 24h before the demo and note the command line. During the demo show some evidence that it was initially requested 24h before and show that the same command line still works during the demo. Delete the cached manifest, and run the command line again. It should fail with a 410 error.
