### ISSUE TITLE
Missing project matrices for hca_prod_20201120_dcp2___20210302

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2882]
[Slack thread](https://app.slack.com/client/T2EQJFTMJ/C9XD6L0AD/thread/C9XD6L0AD-1615234015.095300)

Kylee: two of the projects are also missing the 'optimus_post_processing' run and thus the dcp project matrices are not there:
https://data.humancellatlas.org/explore/projects/5b5f05b7-2482-468d-b76d-8f68c04a7a47?catalog=dcp3
and
https://data.humancellatlas.org/explore/projects/cc95ff89-2e68-4a08-a234-480eca21ce79?catalog=dcp3

**Comment by hannes-ucsc** [comment]
Confirmed as consequence (https://humancellatlas.slack.com/archives/C9XD6L0AD/p1615317130105100?thread_ts=1615234015.095300&cid=C9XD6L0AD)

**Comment by hannes-ucsc** [comment]
Leaving open to verify fix.

**Comment by melainalegaspi** [comment]
@theathorn to verify once catalog dcp3 on prod has been reindexed.

**Comment by theathorn** [comment]
I now see DCP generated matrices for both projects - closing.
