### ISSUE TITLE
Integration tests fail with "No snapshot found for DRS object id"

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2883]
The failed build: https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/11933

This happened on retry and in `sandbox` https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/11943 so, as Hannes said, I suspect this is beyond azul.

**Comment by melainalegaspi** [comment]
@amarjandu spike to come up with an isolated reproduction.

**Comment by amarjandu** [comment]
created stub #2885

**Comment by amarjandu** [comment]
Resolved see https://github.com/DataBiosphere/azul/issues/2885#issuecomment-796256716
