### ISSUE TITLE
Implement the indexer to support Projects Tab

### ISSUE THREAD

**Issue by shiroyuki** [DataBiosphere/azul#289]
Related to #226

Implement the index to support Project Tab.

### Technical Considerations

| Reviewed |
| --- |
| Not yet |

`azul.project.hca.config`
* Add `ProjectTransformer` in `IndexProperties.transformers`.
* Nice to have: change from returning `list` to use a generator (`yield`).

`azul.project.hca.transformers`
* Add `ProjectTransformer` (class).
* Write test for `ProjectTransformer` (functional, unit?).
* Nice to have: refactor `FileTransformer`, `SpecimenTransformer` and `ProjectTransformer` where:
  * `create_documents` remains the same signature,
  * however, anything after bundle retrival will be in a helper file.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-190)
┆Project Name: azul
┆Issue Number: AZUL-190

**Comment by Ben-Wu** [comment]
Wip changes to metadata api: https://github.com/HumanCellAtlas/metadata-api/issues/20
