### ISSUE TITLE
Orange labeler doesn't work on PRs from forks

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2895]
See https://github.com/DataBiosphere/azul/pull/2879/checks?check_run_id=2098829948

The title is my best guess for why this action is failing.

**Comment by theathorn** [comment]
@hannes-ucsc "no secure solution to this problem because we don't want external collaborators to have the ability to modify the GitHub action file".

**Comment by hannes-ucsc** [comment]
Well, I think the labeler action should not run at all on PRs from forks. I'd rather get no status check, than a failed one.

**Comment by melainalegaspi** [comment]
@jessebrennan to understand why the action is run on PRs from forks and why it then fails. Also, figure out how we can disable running the action on PRs from forks.

**Comment by jessebrennan** [comment]
According to Github

> In order to protect public repositories for malicious users we run all pull request workflows raised from repository forks with a read-only token and no access to secrets. This makes common workflows like labeling or commenting on pull requests very difficult.

But they go on to explain their solution

> In order to solve this, we’ve added a new pull_request_target event, which behaves in an almost identical way to the pull_request event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.

Source: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Our solution is simple, just change the event from `pull_request` to `pull_request_target`.

**Comment by jessebrennan** [comment]
I believe @hannes-ucsc had asked about why Travis was running on the forked PR. I looked into this too just in case, because we don't want rogue PRs using up all of our Travis compute time.

Travis seems only to worry about the security implications of running foreign code. 

>Travis CI makes encrypted variables and data available only to pull requests coming from the same repository [...] Pull requests sent from forked repositories do not have access to encrypted variables or data

Source: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions

But I couldn't find documented ways to limit when foreign code runs. One possible solution however is to use the `TRAVIS_SECURE_ENV_VARS` variable ([documented here](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings)) which will indicate if tests are running or not. But if this is a change within the `travis.yaml` file, I suppose foreign code could just overwrite it. :/

I haven't found a satisfactory way around this.

**Comment by jessebrennan** [comment]
@hannes-ucsc: "This ticket was ill-defined and its definition changed over time. We'll start from a clean slate, in #2984"
