### ISSUE TITLE
`Queues.manage_lambdas()` does not manage `contribute_retry`

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2913]
This method was overlooked when adding the new queue.

**Comment by noah-aviel-dove** [comment]
See also https://github.com/DataBiosphere/azul/issues/1848

**Comment by theathorn** [comment]
https://github.com/DataBiosphere/azul/issues/2868#issuecomment-803182782
https://github.com/DataBiosphere/azul/issues/2868#issuecomment-803184230
