### ISSUE TITLE
Add instructions for `sandbox` label in PR checklist

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2918]
"Branch pushed to Gitlab and build passes in sandbox or added no sandbox label" should be split into two steps:

1. Branch pushed to Gitlab (or PR is labeled `no sandbox`)
2.  build passes in sandbox and added `sandbox` label (or PR is labeled `no sandbox`)

**Comment by jessebrennan** [comment]
I may be confused about this, but shouldn't we add the sandbox label once it goes _into_ the sandbox? I thought that was how Hannes used to do it.

**Comment by hannes-ucsc** [comment]
It was how I did it and an operator can still choose to do it that way if it helps them keep track, but it would be hard to express the mutually exclusive semantics of the label in the checklist. So if an operator sets the label before or during the build, they have to remove it again if the build fails.
