### ISSUE TITLE
PR checklist includes steps for manual management of slot commitments

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2924]
Should have been addressed in https://github.com/databiosphere/azul/issues/2651. Checklist should not instruct operator to manually purchase or delete slots.

**Comment by theathorn** [comment]
Freebie of #2919

**Comment by noah-aviel-dove** [comment]
This isn't technically a freebie since #2919 is a `task` that won't have a PR filed for it.

**Comment by hannes-ucsc** [comment]
> This isn't technically a freebie since #2919 is a `task` that won't have a PR filed for it.

I agree. Changed estimate to 1.
