### ISSUE TITLE
Run GitLab reindex stage based on commit tags

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#2937]
It might be possible to have gitlab inspect the commit message for the `[r]` tag and start the reindexing automatically. This would reduce context switching for the operator. 

Reference: 
https://docs.gitlab.com/ee/ci/variables/where_variables_can_be_used.html#gitlab-internal-variable-expansion-mechanism
https://docs.gitlab.com/ee/ci/yaml/README.html#onlyexcept-advanced for how to implement

**Comment by noah-aviel-dove** [comment]
How would this work for PR's with multiple commits?

**Comment by amarjandu** [comment]
@noah-aviel-dove the operator should be following this instruction that we have for adding a merge commit to `develop`:
 `Collected commit title tags in merge commit title`. This would take care of the multiple commits, as the merge commit has the commit tag in place.

There might need to be reordering of the instruction boxes so that the PR merge commit is also ran in the sandbox rather than just the PR branch that has been rebased and auto-squashed (commit tags are not collected)

**Comment by noah-aviel-dove** [comment]
@amarjandu Remember that the merge commit exists on the `develop` branch, not the issue branch. If we push the merge commit to GitLab and the build fails, then we would need to force-push to `develop` after the failure has been addressed. The Operator doesn't have permission to force-push to protected branches. This feels like a strong motivation for maintaining the current checklist order and only merging the issue branch (and consolidating and the commit tags) _after_ the build passes on GitLab for the un-merged issue branch.

**Comment by melainalegaspi** [comment]
Closing in favor of #2727
