### ISSUE TITLE
Invoke TDR's list snapshots endpoint and cache the response as necessary

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2953]
For every incoming Azul request call the snapshots endpoint and make that response available globally for subsequent requests to use.

**Comment by theathorn** [comment]
Spike to determine latency and throughput of list snapshots endpoint to determine caching location (memory or persistent).

**Comment by noah-aviel-dove** [comment]
> * if endpoint can be invoked anonymously

The endpoint cannot be accessed without authenticating.

**Comment by noah-aviel-dove** [comment]
> * latency and throughput of list snapshots endpoint

By default, the `/api/repository/v1/snapshots` endpoint limits its response to 10 items. A higher limit can be specified, but there is no documented way to avoid the limit entirely (using -1 gives a 400 response). When the limit is set high enough to retrieve all accessible snapshots* in a single round trip, the average latency is 254 milliseconds (min 130, max 459, n=50). The API specifies that the limit is a 32 bit integer and the maximum accepted limit appears to be 2**31-1 (any higher gives a 400 response).

*When I hit the endpoint using the swagger API and authenticated using my TDR burner account, the endpoint lists 66 snapshots, but when using `azul.terra.TDRClient` it only lists 22. Probably due to different access permissions? Latency data is for the 22 snapshot response.

**Comment by noah-aviel-dove** [comment]
Should use page size of 100, fail if there are more than 100 snapshots

**Comment by noah-aviel-dove** [comment]
https://github.com/DataBiosphere/azul/issues/2978

**Comment by noah-aviel-dove** [comment]
1. Is there a significant difference in latency for a single request to DynamoDB vs. S3?
2. Is there a significant difference in cost between those requests?
3. Is there a significant difference in cost for storing small objects between the two?

**Comment by noah-aviel-dove** [comment]
1. DynamoDB is substantially faster:
```
2021-04-14 00:50:32,120 INFO    MainThread: It took 0.504s for cache miss in 'S3'
2021-04-14 00:50:32,351 INFO    MainThread: It took 0.231s for cache set in 'S3'
2021-04-14 00:50:32,636 INFO    MainThread: It took 0.285s for cache hit in 'S3'
2021-04-14 00:50:33,065 INFO    MainThread: It took 0.428s for cache miss in 'DynamoDB'
2021-04-14 00:50:33,170 INFO    MainThread: It took 0.105s for cache set in 'DynamoDB'
2021-04-14 00:50:33,266 INFO    MainThread: It took 0.095s for cache hit in 'DynamoDB'
```

**Comment by noah-aviel-dove** [comment]
3. DynamoDB's cost per GB is ~10x higher than S3, however the first 25 GB are free.

**Comment by noah-aviel-dove** [comment]
2. DynamoDB is overall cheaper for read and write requests. 

Cost per 1 million reads:
 * S3 (standard): $0.40 
 * DDB (eventually consistent):  $0.125
 * DDB (strongly consistent): $0.25
 
Coast per 1 million writes:
 * S3 (standard): $5.00 
 * DDB (eventually consistent): $0.625 
 * DDB (strongly consistent): $1.25

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc: "Leaning towards DynamoDB because of cost and speed advantage but we would have to implement manual expiration of stale cache values."

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc: "Together with snapshots, also cache the user's email, as returned by the user info oauth2 endpoint and log the email."

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc : "After retrieving the list of snapshots that the user has access to from the dynamodb cache, filter the list based on the configured sources for a given catalog. Add a new endpoint, `/repository/sources` to list the snapshots the user has access to. Add an integration test to hit this endpoint using a token generated from the service account credentials and assert that the list of accessible snapshots exactly matches the list of configured snapshots for the chosen catalog."

**Comment by hannes-ucsc** [comment]
For demo, request the new /repository/sources endpoint with and without authentication. Sow the resulting cache lines in DynamoDB. Show evidence of expiring cache lines and their refresh, if needed by artificially reducing the expiration.
