### ISSUE TITLE
Implicit filter on sources (snapshots) to which current user has access

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2954]
Exclude project, and potentially summary, endpoint.

**Comment by hannes-ucsc** [comment]
In `dev` hit the `/index/projects` endpoint anonymously and show the number total hits. Show that the managed access (MA) project's UUID is in the response. Show number of hits in the `/index/files`, `/index/bundles` and `/index/samples` responses. Sign in with burner and repeat. The MA project should still be contained in the `/index/projects` response and the number of hits should be the same. The number of hits returned by the files, samples and bundles endpoints should be higher.
