### ISSUE TITLE
Projects endpoint indicates projects not accessible to user

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2955]
As of #2954 we remove the /index/... hits to which the user has no access except for /index/projects. Add a boolean `accessible` response property to each `hits[].projects[]` object returned by that endpoint to indicate whether the project is accessible with the current credentials.

**Comment by hannes-ucsc** [comment]
For demo, show new field in all affected endpoints. Show that requesting the projects endpoint as a user with access to the MA snapshot toggles the flag on the hit for the MA project.

**Comment by danielsotirhos** [comment]
PR needs to be rebased on latest `develop` and file conflict resolved.

**Comment by theathorn** [comment]
@hannes-ucsc "Reverting #2957 will create conflicts with this ticket".
