### ISSUE TITLE
Enforce user authentication on curl download

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2956]
#3302 will ensure that any manifest only references hits the user has access to.

However, for the curl manifest we will still need the user to authenticate for individual file downloads.

If the initial request for the manifest (likely one made by the Data Browser or Swagger UIs) includes a valid OAuth2 token, the recommended curl command line in the response should include that token as an argument to the `--header` flag. The command line makes two `curl` invocations. Both invocations should be given the `--header` flag. The first invocation will hit the manifest endpoint again (this time with an object key to the manifest), while the second invocation will hit the the file endpoint for every file in the returned manifest. 

Passing an OAuth2 token to the manifest request will add a filter on the sources accessible to the user which may cause a cache miss on the manifest object. In case of a cache miss we should not kick off a new generation but return a `410 gone` response with instructions to essentially start from scratch, just like we do for expired manifest objects. 

If the OAuth2 token is valid and the accessible sources haven't changed, the request to the manifest endpoint redirects to a signed URL of the manifest object, curl (the first invocation) follows that and pipes the contents (a curl config file with individual file URLs) to the second curl invocation. This invocation also has the `--header` flag with the token as the argument and curl will send the token to the file endpoint when requesting each file in the config in turn. 

If the OAuth2 token expires during the download, one of those requests will fail with a 401 and curl will abort, not downloading any other files (assignee will need to confirm this). If the user retries the command line, the first curl invocation will detect the now expired header and send a 401 with instructions in the body to use the Data Browser to generate a new command line with a fresh token. Assuming that the accessible sources, the deployed version and the index contents haven't changed, the cached manifest will still be valid and a new command line will be returned quickly.

There's one problem with using OAuth2 tokens: they expire after one hour. Depending on the bandwidth and latency of the user's network connection, the number of files in the manifest and their respective size, the OAuth2 token may expire multiple times during this process, potentially frustrating to the user. If this is the case, we need to switch to using refresh tokens instead. I think we can go ahead with implementing the above solution, even if it will only work for small manifests. An implementation that uses refresh token will look very similar to this one.

**Comment by melainalegaspi** [comment]
@hannes-ucsc spike for specification.

**Comment by hannes-ucsc** [comment]
Spike completed.

**Comment by melainalegaspi** [comment]
Give estimate when @hannes-ucsc is back.

**Comment by noah-aviel-dove** [comment]
> Passing an OAuth2 token to the manifest request will add a filter on the sources accessible to the user which may cause a cache miss on the manifest object. In case of a cache miss we should not kick off a new generation but return a 410 gone response with instructions to essentially start from scratch, just like we do for expired manifest objects.

@hannes-ucsc: "We can postpone this if it turns out to be difficult to implement. Our current idea for solving this is to keep track of the hash of the source ids as a separate component of the object key (hash of source ids + '.' + hash of other inputs). This would enable us to compare the previous source ids with the current ones and decide the validity of the object key without recomputing the content hash. If we decide to postpone this, a user would be able to download manifests for one week even if their access was restricted."

**Comment by hannes-ucsc** [comment]
For demo in `dev`, evict all cached manifests. The prepare a filter that yields a small number of MA and public files. Using the Data Browser, request a curl manifest as 1) an anonymous user, 2) an authenticated user without access to the MA files, and 3) a an authenticated user with access to the MA files. Show that cases 1) and 2) only download public files matching the filter, while case 3) downloads all matching files. 

Show the cached manifest, there should be two.

Rerun the command line for each case to show that the cached manifests are used. Show the cached manifest, there should still be only two.

Revoke access to the MA files for the user from case 3 and rerun the case 3 command line. A 410 should be generated.

Restore access and rerun the case 3 command line. The cached manifest should be used again and downloads should work again.

Post demo:

Let the token expire (I think the duration is 1 hour) and rerun the case 3 command line. A 401 should be generated. Post screenshot on Slack. If the post-demo fails, remove the `demoed` label and discuss next steps in Slack or PL.

**Comment by hannes-ucsc** [comment]
We should discuss the scope of a DCP demo after the team-internal demo, next Tue.

**Comment by noah-aviel-dove** [comment]
> If the initial request for the manifest (likely one made by the Data Browser or Swagger UIs) includes a valid OAuth2 token, the recommended curl command line in the response should include that token as an argument to the --header flag. The command line makes two curl invocations. Both invocations should be given the --header flag.

Didn't get this right in the first PR. The first cURL invocation lacks the header.

**Comment by theathorn** [comment]
@hannes-ucsc : "For DCP demo, use the Data Browser to initiate a small curl manifest download as an anonymous user and as an authorized user. Show that the set of downloaded files reflects the authorization. The set of files downloaded as the authorized user should be a strict superset of the ones downloaded anonymously."
