### ISSUE TITLE
Enforce access controls on file downloads

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2957]
1. Determine if user has access to the requested file using the sources (snapshots) the file is part of, and the user's identity
2. Make request to TDR's DRS endpoint on behalf of the user
3. Sign the resulting gs:// URI using user's credential or service account credentials (TBD)

**Comment by theathorn** [comment]
@hannes-ucsc "Since TDR now offers signed URLs in their DRS implementation for GCS objects, we shoudl use those instead of signing ourselves".

**Comment by hannes-ucsc** [comment]
For demo, attempt to download a 1) file from the "managed access" project and a 2) file from another project a) without credentials, using the credentials b) of a user that is not registered with SAM, c) a user that is but that is not a member in the `azul-dev` group, and d) a user that is a member of the `azul-dev` group. That's eight cases in total.
