### ISSUE TITLE
Index organically described CGMs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#2958]

**Comment by melainalegaspi** [comment]
See also https://github.com/HumanCellAtlas/metadata-schema/pull/1371

**Comment by hannes-ucsc** [comment]
Spike first to determine if canned staging areas can be indexed in such a way that the startification tree can be derived from the metadata.

**Comment by theathorn** [comment]
Demo together with hca-metadata-api#38.

**Comment by theathorn** [comment]
@hannes-ucsc "Synthesize internal/external facet from source enum values in schema".

**Comment by hannes-ucsc** [comment]
For demo, show that https://github.com/databiosphere/azul/issues/3106 is resolved. Must be done in `prod` for now. Show that the CGM(s) in that project are associated with properties from upstream biomaterials.
