### ISSUE TITLE
Determine set of publicly accessible snapshots via TDR

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#2978]
When a user is signed in, we will hit TDR on their behalf to determine the snapshots they have access to. This will include publicly accessible snapshots and the access-controlled ones the user has been granted access to. When the user is not signed in (anonymous) they should still see al publicly accessible snapshots. Unfortunately, it is not possible to list snapshots without authenticating to TDR so we need to find another way. One possible solution is to create another service account that represents anonymous Azul users and ask the TDR team to assign anonymously accessible snapshots to a group of which said service account is a member of.

Another is to hard-code the IDs of those snapshots.

Edit: Based on the discussion below we'll go with a second SA

```diff
Index: environment.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/environment.py b/environment.py
--- a/environment.py	(revision 80ac68ed80c3b9f2be72aca4e5eabff4f4990552)
+++ b/environment.py	(date 1619632813991)
@@ -278,10 +278,15 @@
         'AZUL_DEPLOYMENT_INCARNATION': '0',
 
         # The name of the Google Cloud service account to be created and used
-        # in conjunction with DSS subscriptions. If unset, a canonical resource
-        # name will be used. That default allows one such account per Azul
-        # deployment and Google Cloud project.
-        'AZUL_GOOGLE_SERVICE_ACCOUNT': 'azul-ucsc-{AZUL_DEPLOYMENT_INCARNATION}-{AZUL_DEPLOYMENT_STAGE}',
+        # for accessing all (meta)data in Google-based repositories.
+        #
+        'AZUL_SERVICE_ACCOUNT': 'azul-main{AZUL_DEPLOYMENT_INCARNATION}-{AZUL_DEPLOYMENT_STAGE}',
+
+        # The name of the Google Cloud service account to be created and used
+        # for accessing public (not access-controlled) (meta)data in Google-
+        # based repositories anonymously i.e., without authentication.
+        #
+        'AZUL_PROXY_SERVICE_ACCOUNT': 'azul-proxy{AZUL_DEPLOYMENT_INCARNATION}-{AZUL_DEPLOYMENT_STAGE}',
 
         # The number of concurrently running indexer lambda executions. Chalice
         # creates one Lambda function for handling HTTP requests from API Gateway

```

**Comment by theathorn** [comment]
Spike to fill in description and blocking relationship.

**Comment by hannes-ucsc** [comment]
@ruchim, what do you think we should do here?

**Comment by ruchim** [comment]
Given that we display a public snapshot worth of info today without a user logging in -- is that already done with the service account model? I think we want to continue using whatever model we have today for displaying public snapshots into the future of managed access. Let me know if I'm missing something!

**Comment by hannes-ucsc** [comment]
The listing of snapshots is currently done with the one and only service account for Azul. That SA needs to have access to all snapshots, public and access-controlled because it is used to index them. We can't restrict that SA to only have access to public snapshots because then we wouldn't be able to index access controlled snapshots. What I am proposing is to create a second Azul-specific SA that is used only for listing public snapshots. The alternatives areexplicitly configuring the set of public snapshots (that would require redeploying Azul should the set change), determining it at indexing time (that would require reindexing should the set change) or making the TDR list snapshots endpoint not require authentication (which has other implication, like not being able to distinguish between HCA and non-HCA public snapshots.

**Comment by ruchim** [comment]
Right right, sorry now I understand. Yes, I like the model of a second Azul specific SA for public snapshots only.

**Comment by hannes-ucsc** [comment]
For demo, hit `/repository/sources` anonymously in `dev` and show the distinct snapshot IDs the response. Temporarily remove the public SA from `azul-public-dev` and hit endpoint again, it should return no snapshots. Undo removal.
