### ISSUE TITLE
Use `--extend-select` for flake8 configuration

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#2994]
Now that https://github.com/PyCQA/flake8/issues/1274 is merged we can address this `fixme`:

https://github.com/DataBiosphere/azul/blob/85703001f50eb30b1c1eddc1b8556f42704d1ae7/.flake8/conf#L4

(Note that the issue mentioned there doesn't match the one linked above because flake8 moved from Gitlab to Github)

**Comment by asottile** [comment]
this shouldn't use `extend-select`, you've just named your plugin incorrectly.  this line should be `AZU = ...` (note that letters are 3 characters at most, not 4): https://github.com/DataBiosphere/azul/blob/85703001f50eb30b1c1eddc1b8556f42704d1ae7/.flake8/conf#L12 and you should adjust your error codes to be `AZU###`

**Comment by hannes-ucsc** [comment]
Fixed in 365f761a816a159b1d26fc02d4883d2949e290db
