### ISSUE TITLE
Update Azul with the work of HCA to enable multiple deploys

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#3]
Given the current Azul indexer deployment process, this may simply be updating the readme.md with how to:

1. Manually configure the desired AWS API Gateway stage in the config.json (if necessary)
1. Run:  chalice deploy --stage _stage_name_

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-6)
┆Project Name: azul
┆Issue Number: AZUL-6
┆Epic: Re-implement the Azul and Dash

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

Hello, [~achave11] [~gpelayo1] I have put Abraham as the assignee and Geryl as the reviewer.  I just want to hand it to the two of you in what ever way

**Comment by cricketsloan** [comment]
➤ Lighthouse Point commented:

branch management now

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

It turns out the HCA team is currently developing improved deployment support for the Azul indexer, and we will update our Commons Azul indexer to use that mechanism when it is available. This changes the nature of this task from implementing the support ourselves to updating to use their support when it is available.

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
