### ISSUE TITLE
Re-implement the Azul and Dashboard services back into code base

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#30]
https://docs.google.com/document/d/1Xup4nh5yqBGK8xgHs2_WYyHD7fDUJJBj6sqaPHFaXgw/edit#

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-24)
┆Project Name: azul
┆Issue Number: AZUL-24

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
