### ISSUE TITLE
Add new Submitter ID values

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3000]
Add new submitter ID values to support the new `file_source` values specified on the latest [CGM spreadsheet](https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY/edit?ts=601bb5db#gid=0).

- `ENA`
- `other` 
- `paper supplements`

**Comment by melainalegaspi** [comment]
@danielsotirhos to consolidate the spreadsheet values with the enum values from the CGM schema pr. Specifically, are paper supplements the same as what we call publication? Also, see if something more specific than "other" can be used.

**Comment by danielsotirhos** [comment]
Current set of Azul supported `file source` values:
https://github.com/DataBiosphere/azul/blob/develop/src/azul/plugins/metadata/hca/transform.py#L272

- arrayexpress
- contributor
- dcp1 matrix service
- dcp2
- geo
- hca release
- lungmap external
- publication
- scea
- scp
- zenodo


Proposed set of `file_core.file_source` enum values in metadata-schema PR#1371:
https://github.com/HumanCellAtlas/metadata-schema/pull/1371/files

- ArrayExpress
- Contributor
- DCP/1 Matrix Service
- DCP/2 Analysis
- GEO
- HCA Release
- LungMAP
- Publication
- SCEA
- SCP
- Zenodo


Current set of `file_source` values on the contributor_matrices_metadata spreadsheet:
(new additions not yet supported by Azul marked with `*`)
https://docs.google.com/spreadsheets/d/1m9tXswoNAEYJDVlCKqc9L6p0c7hbOwddkQxdqxXydqY/edit?ts=601bb5db#gid=0

- arrayexpress
- contributor
- ENA *
- geo
- hca release
- other *
- paper supplements *
- publication
- scea
- scp
- zenodo

**Comment by danielsotirhos** [comment]
Closing ticket as invalid.
The 3 `file_source` values mentioned in the ticket description are no longer going to be added. The rows on the CGM spreadsheet using these values have been updated to use other existing `file_source` values.
