### ISSUE TITLE
Restrict GitHub Actions token permissions by default

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3015]
> You can set the default permissions granted to the GITHUB_TOKEN. For more information about the GITHUB_TOKEN, see "Authentication in a workflow." You can choose between a restricted set of permissions as the default or a permissive setting.

https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository

**Comment by jessebrennan** [comment]
Note that this will probably require refactoring some of our existing actions (specifically the labler) to explicitly grant the permissions they need.

**Comment by hannes-ucsc** [comment]
Archived repository

- [ ] https://github.com/HumanCellAtlas/azul-github-labeler-action
- [ ] https://github.com/HumanCellAtlas/metadata-api

Restricted permissions:

- [ ] https://github.com/DataBiosphere/azul
- [ ] https://github.com/DataBiosphere/azul-chalice
- [ ] https://github.com/DataBiosphere/azul-github-labeler-action 
- [ ] https://github.com/DataBiosphere/azul-tinyquery
- [ ] https://github.com/DataBiosphere/cellxgene-fargate
- [ ] https://github.com/DataBiosphere/dcp2-infra
- [ ] https://github.com/DataBiosphere/hca-import-validation
- [ ] https://github.com/DataBiosphere/hca-metadata-api
- [ ] https://github.com/DataBiosphere/sync-github-labels
- [ ] https://github.com/HumanCellAtlas/data-browser
- [ ] https://github.com/HumanCellAtlas/data-portal
- [ ] https://github.com/HumanCellAtlas/dcp2

Fixed labeler:

- [ ] https://github.com/DataBiosphere/azul
- [ ] https://github.com/DataBiosphere/azul-chalice
- [ ] https://github.com/DataBiosphere/azul-github-labeler-action 
- [ ] https://github.com/DataBiosphere/azul-tinyquery
- [ ] https://github.com/DataBiosphere/cellxgene-fargate
- [ ] https://github.com/DataBiosphere/dcp2-infra
- [ ] https://github.com/DataBiosphere/hca-import-validation
- [ ] https://github.com/DataBiosphere/hca-metadata-api
- [ ] https://github.com/DataBiosphere/sync-github-labels
- [ ] https://github.com/HumanCellAtlas/data-browser
- [ ] https://github.com/HumanCellAtlas/data-portal
- [ ] https://github.com/HumanCellAtlas/dcp2
