### ISSUE TITLE
GitHub action status check names are too unspecific

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3024]
![image](https://user-images.githubusercontent.com/5143256/116588585-94ea9e80-a8d0-11eb-9290-eb46c91c26c6.png)

That should be `github/actions/{test,label,codecov,coveralls}`

**Comment by jessebrennan** [comment]
I'm not sure where @hannes-ucsc took his original screenshot, I couldn't find a UI like that. What I did find isn't as bad as the original screenshot, but it doesn't match what Hannes asked the result to change to. ![checks-passing](https://user-images.githubusercontent.com/10734740/119919327-0e50cd80-bf1f-11eb-9388-836ebcf70534.png)

Is this satisfactory? Where was the original screenshot taken?

**Comment by jessebrennan** [comment]
The screenshot @hannes-ucsc posted is from a closed PR. There is a UI inconsistency. The current names are good enough for an open PR. @hannes-ucsc: "This can be closed as 'won't fix'".
