### ISSUE TITLE
Add tooling to aid in picking prefix for source

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3027]
There should be some sort of tooling that is used to help decide which prefix should be used when adding/updating a snapshot source.

**Comment by amarjandu** [comment]
may want to ping @hannes-ucsc when deciding on how the tool decides which prefix to suggest.

**Comment by jessebrennan** [comment]
I added [instructions in the operator manual for this](https://github.com/DataBiosphere/azul/wiki/Operator-Manual#adding-snapshots-to-dev) which might be sufficient to close this issue.

**Comment by jessebrennan** [comment]
I updated the language to reference 64 instead of ~100. This is ready for review.

**Comment by hannes-ucsc** [comment]
Looks good. For demo, show instructions.
