### ISSUE TITLE
Index hca_dev_20201203___20210426 into dcp2 on dev

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3028]
Important to do a post-mortem on this after reindexing since it adds SS2 analysis subgraphs we haven't seen before.

**Comment by achave11** [comment]
Post-mortem yield an additional [non-registered](https://github.com/DataBiosphere/azul/wiki/Operator-Manual#notes) failure.

```
[WARNING] 2021-04-30T22:38:19.136Z 216f4b41-051e-52b2-938c-12478c0ef72f Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': '446f8fa3-4244-42ba-b0a1-00e16b426cf4', 'name': 'tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210426'}, 'query': {}, 'subscription_id': '**', 'transaction_id': '**', 'match': {'bundle_uuid': '94565940-7b2f-5fd7-beb1-dc309687fe09', 'bundle_version': '2021-02-10T17:01:03.177554Z'}}, 'catalog': 'dcp2'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 145, in contribute
contributions = self.transform(catalog, notification, delete)
File "/var/task/azul/indexer/index_controller.py", line 175, in transform
bundle = plugin.fetch_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 217, in fetch_bundle
bundle = self._emulate_bundle(bundle_fqid)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 314, in _emulate_bundle
raise e
File "/var/lang/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/var/task/azul/plugins/repository/tdr/__init__.py", line 404, in _retrieve_entities
require(not missing,
File "/var/task/azul/__init__.py", line 1080, in require
reject(not condition, *args, exception=exception)
File "/var/task/azul/__init__.py", line 1095, in reject
raise exception(*args)
azul.RequirementError: Required entities not found in broad-jade-dev-data.hca_dev_20201203___20210426.project: {'2086eb05-10b9-432b-b7f0-169ccc49d270'}
```
The subgraph contains a reference to a project entity which isn't retrievable or not available in BQ.

**Comment by hannes-ucsc** [comment]
Looks like that is a duplicate of https://github.com/DataBiosphere/azul/issues/2870 which we already know about and expect (it's labelled as `expected`). 

Please post every failure that occurred during this reindexing here and link each one to the respective expected issue. 

And please change the operator notes to not list the failures explicitly but instead refer to the label (like so: https://github.com/DataBiosphere/azul/labels/expected). Make sure the labelled issue have a description that makes it easy to identify the corresponding expected message in the fail queue, so that future operators can quickly triage indexing failures against that list.

**Comment by achave11** [comment]
Index Failures:
["bundle_uuid": "c12a6ca2-3234-5182-ad0b-f8c2fb881ab5", "bundle_version": "2020-12-03T00:00:01.000000Z"
"bundle_uuid": "ae338c4e-650f-545b-8631-3c8d755aa2f9", "bundle_version": "2020-12-03T00:00:01.000000Z"
"bundle_uuid": "40733888-3b9f-500e-84fd-1a18a64aadbe", "bundle_version": "2020-12-03T00:00:01.000000Z"
"bundle_uuid": "9d0f5cd1-0ef6-5eed-8dd7-f15d36a34185", "bundle_version": "2020-12-03T00:00:01.000000Z"](https://github.com/DataBiosphere/azul/issues/2873) 
(all four captured in one ticket)
and
["bundle_uuid": "94565940-7b2f-5fd7-beb1-dc309687fe09", "bundle_version": "2021-02-10T17:01:03.177554Z"](https://github.com/DataBiosphere/azul/issues/2870)

All failures were [expected](https://github.com/DataBiosphere/azul/labels/expected) and already accounted for in open issues.
