### ISSUE TITLE
Left-over CloudWatch logs from older deployments in us-west-2

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3033]
There seems to be resources (AWS Lambdas) provisiones for `dev` and other deployments in Oregon region, unsure whether they are active.

**Comment by melainalegaspi** [comment]
@achave11 to improve description with reproduction.

**Comment by achave11** [comment]
![Screen Shot 2021-05-03 at 4 10 04 PM](https://user-images.githubusercontent.com/19215510/116944321-1ec89d80-ac2a-11eb-9dd1-7ff758071fc6.png)

Only CloudWatch has references to non existent deployment resources in different regions. Perhaps used for posterity purposes.

**Comment by hannes-ucsc** [comment]
I deleted them:

![image](https://user-images.githubusercontent.com/5143256/116948309-e5952b00-ac33-11eb-917b-b95b2d84f7c7.png)
