### ISSUE TITLE
Moto decorator usage is order-dependent

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3035]
Its possible that the ordering of multiple moto `@mock` decorators causes issues with how a response callback is handled from within Moto, we should be aware of this when working with the library to mock out AWS functionality in unittests.

See https://github.com/spulec/moto/issues/3790

**Comment by hannes-ucsc** [comment]
Upstream blocker is resolved.

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/pull/4562 [removes](https://github.com/DataBiosphere/azul/pull/4562/files#diff-66bb0bc92455abe70f26f42197a234d72e21308eaeb3a5fc17f669dc17707870L12-L13) the workaround.
