### ISSUE TITLE
Queue waiter waits a long time when the queues are empty

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3038]
The long wait time (10 minutes) was motivated by transient stalls but these always occur with something in the queue. We should wait for 10 minutes of no progress when the queues are non-empty and only 1 or 2 minutes when they are empty.

**Comment by noah-aviel-dove** [comment]
Spike after we have ~10 reindex jobs against sandbox to confirm whether the assumptions in the ticket description are correct.

**Comment by hannes-ucsc** [comment]
For demo, show a couple of Gitlab job logs for `sandbox` or `dev` that contain the "queues have emptied" message.
