### ISSUE TITLE
Be smarter about scheduling promotions and catalog updates 

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3040]
The most recent `prod` promotion included a change that required reindexing of all catalogs and a change that added a catalog for the upcoming release. The first change required reindexing everything while the second change would only have required reindexing the added catalog. Consequently we reindexed everything. Roughly 420k bundles. Since the notifications for different catalogs all go into one queue, essentially in random order, none of the catalogs is fully complete until the reindexing finishes.

Had we promoted first and then, in a separate push, added the new catalog, we could have shortened the time it took to render the new catalog.

**Comment by melainalegaspi** [comment]
@hannes-ucsc spike to come up with a solution.

**Comment by melainalegaspi** [comment]
The index manager will take care of this. See Epic #2727
