### ISSUE TITLE
Projects endpoint raises AssertionError on `dcp5` catalog

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3043]
The issue ~appears~ is limited to project `996120f9-e84f-409f-a01e-732ab58ca8b9` in the dpc5 catalog.

![image](https://user-images.githubusercontent.com/46407464/117228891-e31b0880-adce-11eb-815d-5faaf509f013.png)

Note: This issue did not occur with these files when the `dcp4` catalog was indexed.. https://data.humancellatlas.org/explore/projects/996120f9-e84f-409f-a01e-732ab58ca8b9/project-matrices?catalog=dcp4

**Comment by danielsotirhos** [comment]
The AssertionError was caused by project `996120f9-e84f-409f-a01e-732ab58ca8b9` having 2 CGM with  varying stratification dimensions. As explained in https://github.com/databiosphere/azul/issues/2443 this is currently not supported. As a quick fix the CGM file missing a `libraryConstructionApproach` value was given one, so now both CGM files for this project have the same stratification dimensions.

The question remains however why this error was not experienced with the `dcp4` catalog when both these files were included in the `dcp4` catalog. The answer is that only 1 of the 2 `GSE140231_RAW.tar` is listed as a CGM by Azul. The other file `41467_2020_17876_MOESM5_ESM.xlsx` is in the index however it was not identified as a CGM during reindex of the dcp4 catalog.

The current hypothesis is that the `submitter_id` value of this file was not recognized by Azul as a CGM `submitter_id` when the reindex occurred. Unfortunately a compiled timeline of events does not support this hypothesis.

02/04: Project 996120f9 files added to CGM spreadsheet
02/26: Project 996120f9 files added to staging area
03/04: support for 'Publication' Submitter ID merged in Azul https://github.com/DataBiosphere/azul/issues/2823
03/05: Prod reindexed
03/19: Ticket https://github.com/DataBiosphere/azul/issues/2823 moved to `prod` column
03/30: Prod reindexed for dcp4 catalg https://github.com/DataBiosphere/azul/issues/2923
04/05: Prod reindexed for dcp4 catalg https://github.com/DataBiosphere/azul/issues/2930
05/05: Prod reindexed for dcp5 catalg https://github.com/DataBiosphere/azul/issues/3036

Additional information:

Project `996120f9-e84f-409f-a01e-732ab58ca8b9`

File: `GSE140231_RAW.tar`
UUID: `50bc5432-2d73-5426-80af-fef35ceb8960`
submitter_id: `21b9424e-4043-5e80-85d0-1f0449430b57` (GEO)
Version: `2021-02-26T09:16:10.074754Z`

File: `41467_2020_17876_MOESM5_ESM.xlsx`
UUID: `b6fb9667-af07-54f0-9c69-48e423ab6bd5`
submitter_id: `210ca4c7-f6f6-5a0d-8b1c-88ab5349a8f3` (Publication)
Version: `2021-02-26T09:16:10.074754Z`
Note: Has no `libraryConstructionApproach` value

File Descriptor for `41467_2020_17876_MOESM5_ESM.xlsx`:
```
{
    "describedBy": "https://schema.humancellatlas.org/system/2.0.0/file_descriptor",
    "schema_type": "file_descriptor",
    "schema_version": "2.0.0",
    "file_name": "41467_2020_17876_MOESM5_ESM.xlsx",
    "size": 898308,
    "file_id": "b6fb9667-af07-54f0-9c69-48e423ab6bd5",
    "file_version": "2021-02-26T09:16:10.074754Z",
    "content_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "crc32c": "da7e3e1c",
    "sha256": "07d868b776b20b4601c898d2b67917bdd2eb12e5050321dc83257bb82ad5542a"
}
```

Metadata for `41467_2020_17876_MOESM5_ESM.xlsx`
```
{
    "describedBy": "https://schema.humancellatlas.org/type/file/2.2.0/supplementary_file",
    "schema_type": "file",
    "schema_version": "2.2.0",
    "file_core": {
        "format": "xlsx",
        "content_description": [
            {
                "text": "Contributor-generated matrix",
                "ontology": "data:2082",
                "ontology_label": "Matrix"
            }
        ],
        "file_name": "41467_2020_17876_MOESM5_ESM.xlsx"
    },
    "file_description": "genusSpecies=Homo sapiens;developmentStage=adult;organ=brain",
    "provenance": {
        "document_id": "b6fb9667-af07-54f0-9c69-48e423ab6bd5",
        "submission_date": "2021-02-26T09:16:10.074754Z",
        "submitter_id": "210ca4c7-f6f6-5a0d-8b1c-88ab5349a8f3",
        "update_date": "2021-02-26T09:16:10.074754Z"
    }
}
```

**Comment by hannes-ucsc** [comment]
I temporarily fixed this by manually patching the matrix tree in the aggregate document for that project in ES using Kibana. This means we need to perform the manual fix after every reindex of `dcp5` in `prod`. I'll leave this open to remind ourselves of that. We can close this only after the dcp5 catalog is deleted or we are given a snapshot for dcp5 that fixes this as outlined by @danielsotirhos above. Given the monthly release cadence the former remedy is more likely and will occur naturally during the release of `dcp6`.

**Comment by hannes-ucsc** [comment]
Assigned to @noah-aviel-dove as well since he will be operator next week.

**Comment by hannes-ucsc** [comment]
Since we're not very likely to get an updated snapshot for dcp5, this issue can only be fixed by deleting the dcp5 catalog. Until that happens, the manual workaround needs to be performed after every reindexing on prod that includes the `dcp5` catalog. This ticket can be closed when the dcp5 catalog is deleted, likely when the `dcp6` catalog becomes the default.

**Comment by theathorn** [comment]
dcp5 catalog has been deleted.
