### ISSUE TITLE
Disable velocity script

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3051]

**Comment by achave11** [comment]
Velocity action was disabled manually through GitHub UI.

![Screen Shot 2021-06-07 at 4 52 27 PM](https://user-images.githubusercontent.com/19215510/121101526-da906600-c7b0-11eb-8760-78a19b4628c0.png)

Should the script be `rm` or `mv` into the attic?

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "Move to the attic."
