### ISSUE TITLE
Document operating procedure for post-mortems on reindexing

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3056]
Check for fail messages, triage fail messages against expected failures, raise issues for unexpected failures, ping people on `#dcp2` about those issues, clear the fail queues so they are empty for the next reindexing.

**Comment by danielsotirhos** [comment]
https://github.com/DataBiosphere/azul/wiki/Operator-Manual
Added section `Failures during reindex`.

**Comment by amarjandu** [comment]
I think there is a step that was forgotten above which is to document the failures within the PR itself. IMO there should be a link to the example that Daniel created here https://github.com/DataBiosphere/azul/pull/3050#issuecomment-840033931

**Comment by amarjandu** [comment]
Added the step to document the failures within the PR.

**Comment by hannes-ucsc** [comment]
Wiki changes LGTM.
