### ISSUE TITLE
CommonMark dependency is breaking builds and deployments

### ISSUE THREAD

**Issue by Ben-Wu** [DataBiosphere/azul#306]
We are using `hca==4.1.0` (https://github.com/HumanCellAtlas/dcp-cli) which is using dependency `commonmark >= 0.7.4, < 1`.

The problem is the commonmark package was broken in 0.8.0 and isn't fixed yet so when install it via pip, the module will not be found.  This is causing deployments and travis builds to fail.

example: https://travis-ci.org/DataBiosphere/azul/builds/425407139

Our options are:
1. use `hca==4.3.3` which has `commonmark >= 0.7.4, < 0.8`.  I haven't checked if there are any issues with upgrading.

2. explicitly set `commonmark==0.7.5` which is easy but azul itself doesn't use commonmark so it's strange to have it in it's `requirements.txt`

3. wait until it's fixed let builds fail

I think we should go with 2 until commonmark is fixed and then we can take it out of `requirements.txt`

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-203)
┆Project Name: azul
┆Issue Number: AZUL-203

**Comment by mikebaumann** [comment]
In general, I would look first a moving to a newer version of the explicit dependency (`hca` in this case). It looks like `hca` 4.2.1 would resolve the commonmark issue, yet moving to `hca` 4.2.1 should include updating to the newer DSSClient initialization method described here: [https://hca.readthedocs.io](https://hca.readthedocs.io). Note that `hca` after 4.2.1 contain changes for authentication (Auth0) that may not be backwards compatible (would need to check).

Given the above, I would choose option 2 to resolve the immediate issue AND open an issue to update Azul to a newer version of `hca` that can be addressed when @hannes-ucsc is back from vacation.

**Comment by Ben-Wu** [comment]
Follow-up issue: https://github.com/DataBiosphere/azul/issues/309
