### ISSUE TITLE
Move parsing of prefix to SourceSpec

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3073]
PR #3047 for #2843 renames SourceName to SourceSpec. While SourceSpec defines the `prefix` attribute, it does not specify where in the string representation of a SourceSpec the prefix occurs and how it is separated from other components. This means that some parsing logic is duplicated in every subclass of SourceSpec, and that we can stop special-casing the DSS prefix which is currently NOT configured through the string representation of DSSSourceSpec but comes from a global environment variable. When a DSSSourceSpec is serialized and written to an index document, its prefix is discarded. If the environment variable changes, the original value cannot be reconstructed from the document, which might lead to confusion.

We should commit to having the prefix occur at the end of the string representation of any subclass of SourceSpec, preceded by a colon. IOW, the prefix should always follow the last colon in that string representation, which implies that there is always at least one colon in every string representation of any subclass of SourceSpec.

**Comment by theathorn** [comment]
@hannes-ucsc Spike for details.

**Comment by hannes-ucsc** [comment]
Spike is done.

**Comment by amarjandu** [comment]
Parking Lot w / @hannes-ucsc :

This is potentially a non-issue due to how we addressed #2843 Rename SourceName to SourceSpec.

---

> While SourceSpec defines the prefix attribute, it does not specify where in the string representation of a SourceSpec the prefix occurs and how it is separated from other components. This means that some parsing logic is duplicated in every subclass of SourceSpec, and that we can stop special-casing the DSS prefix which is currently NOT configured through the string representation of DSSSourceSpec but comes from a global environment variable. 

We opted to drop `DSSSourceSpec` in favor of modifying the `SimpleSourceSpec` to include a colon prefix `:{prefix}` value. 
https://github.com/DataBiosphere/azul/blob/9506935d1a65b9aa57bdc9621212ca4bff4b5c7d/src/azul/plugins/repository/dss/__init__.py#L81

---

> When a DSSSourceSpec is serialized and written to an index document, its prefix is discarded. If the environment variable changes, the original value cannot be reconstructed from the document, which might lead to confusion.

We have a test failure https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/21920#L5802 that was caused by the configured DSS prefix value being returned within an ES response.

A empty prefix is expected from the ES responses, https://github.com/DataBiosphere/azul/blob/cba5e0f110387347d586dcbded3cf60cefff4d64/test/service/test_response.py#L177

---

> We should commit to having the prefix occur at the end of the string representation of any subclass of SourceSpec, preceded by a colon. IOW, the prefix should always follow the last colon in that string representation, which implies that there is always at least one colon in every string representation of any subclass of SourceSpec.

I think is met within the `SimpleSourceSpec.parse` method where a colon is required.
https://github.com/DataBiosphere/azul/blob/9506935d1a65b9aa57bdc9621212ca4bff4b5c7d/src/azul/indexer/__init__.py#L102

**Comment by amarjandu** [comment]
@hannes-ucsc  "Add SourceSpec.parse and ._parse to subclasses. Combine AZUL_DSS_QUERY_PREFIX and AZUL_DSS_ENDPOINT into AZUL_DSS_SOURCE. The only place where `AZUL_DSS_SOURCE` is set will be in `DSSUnitTestCase.setUpClass`."
