### ISSUE TITLE
Compact manifest filename is non-human friendly

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3077]
In the short term we are switching the project metadata download from the full to the compact manifest.
It would be desirable to keep the human friendly filename for the full project manifest,

Project manifest download file names.
compact: hca-manifest-fc79357d-9377-5811-b133-366174afdd42.tsv
full: 1M Neurons 2021-05-24 23.40.tsv

**Comment by hannes-ucsc** [comment]
For demo, show that compact manifest is now downloaded to a local file with a meaningful name.
