### ISSUE TITLE
Update `hca` dependency version

### ISSUE THREAD

**Issue by Ben-Wu** [DataBiosphere/azul#309]
Follow-up of issue https://github.com/DataBiosphere/azul/issues/306

`commonmark` version was explicitly set to version 0.7.5 in PR https://github.com/DataBiosphere/azul/pull/308 but this isn't ideal because `commonmark` isn't a direct dependency of azul.  If `commonmark` is still broken we should look into upgrading to `hca` to a newer version.  It looks like the newer version introduces changes that make upgrading to it non-trivial.

`commonmark==0.7.5` should be removed from `requirements.txt`

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-204)
┆Project Name: azul
┆Issue Number: AZUL-204

**Comment by mikebaumann** [comment]
Reposting my comment made for issue #306 here, as the comment is most relevant to this issue:

In general, I would look first a moving to a newer version of the explicit dependency (hca in this case). It looks like hca 4.2.1 would resolve the commonmark issue, yet moving to hca 4.2.1 should include updating to the newer DSSClient initialization method described here: https://hca.readthedocs.io.
Also note that hca after 4.2.1 contain changes for authentication (moving to Auth0) that will need to be coordinated with updates to the DSS deployments being used.

Given the above, I would choose option 2 to resolve the immediate issue AND open an issue to update Azul to a newer version of hca that can be addressed when @hannes-ucsc is back from vacation.

**Comment by hannes-ucsc** [comment]
This is also needed to catch-up with the authentication changes that were rolled out to DSS in integration, staging and prod during my absence.
