### ISSUE TITLE
`Bam` and intermediate `loom` files have `null` file source

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3096]
We expect these files to have a file source value of `DCP/2 Analysis`.

They do not because we did not allocate a `submitter_id` value for these files.

**Comment by melainalegaspi** [comment]
@danielsotirhos spike for possible solutions.  @hannes-ucsc: "i.e. files produced by analysis_process entity."

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Bump estimate to 5 to account for adding `.is_matrix` to `api.File`."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce issue.
