### ISSUE TITLE
Merge  repository/summary/$entity_type to /repository/summary

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#310]
Wanted to suggest that the we move summary from under files as its really a summary of the whole repository across entities. This has a count of not just files but, projects and samples too.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-205)
┆Project Name: azul
┆Issue Number: AZUL-205

**Comment by theathorn** [comment]
@NoopDog See https://app.zenhub.com/workspace/o/databiosphere/azul/issues/244

**Comment by GPelayo** [comment]
@hannes-ucsc to summarize the design of the summary
