### ISSUE TITLE
Matrix for project `cellular immune response to COVID-19..` is  not displayed in Project Matrices tab

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3106]
The "managed access" project (uuid=b963bd4b-4bc1-4404-8425-69d74bc636b8) in the dcp6 catalog does not have file_source set, for the contributor-generated matrix file so it's not showing up in the Data Browser "Project Matrices" tab.

https://data.humancellatlas.org/explore/projects/b963bd4b-4bc1-4404-8425-69d74bc636b8?catalog=dcp6

**Comment by hannes-ucsc** [comment]
Blocker is in `prod`. Resolution is ready to be verified.

**Comment by theathorn** [comment]
Verified - there are now 2 project matrix files, annotation_200112.csv and covid_portal.h5ad.
