### ISSUE TITLE
Rename index field `contents.files.source` to `.file_source`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3111]
There are two conflicting notions of "source" in Azul. The indexer source (as in snapshot for TDR) and the `file_core.file_source` schema property. We need to make sure to avoid confusion as much as possible. We should also rename the response field `hits.files.source` to `.file_source` in order to match the name of the schema property. That is an backwards-incompatible API change.

**Comment by danielsotirhos** [comment]
Making ticket a freebie of #3171.
Note: this ticket requires coordination with Data Browser team.

**Comment by hannes-ucsc** [comment]
@theathorn ^^^ this is too internal to be worth demoing to the DCP

**Comment by hannes-ucsc** [comment]
For demo, show renamed field in index using Kibana.

**Comment by danielsotirhos** [comment]
Reopening ticket due to a bug discovered in implementation.
Bug: `hits[].files[].source` and `hits[].files[].fileSource` are always returned as `null`.
