### ISSUE TITLE
Multiple Files are in the files array  in each "hit" of /repository/files, expecting only one.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#312]
https://service.integration.explore.data.humancellatlas.org/repository/files?size=15&filters=%7B%7D

Looking at the hits in the response of the files tab, I am seeing multiple files.

This is on integration, here:
https://service.integration.explore.data.humancellatlas.org/repository/files?size=15&filters=%7B%7D

for example:

```
"hits": [
    {
      "processes": [
        {
          "processId": "process_id_32",
          "processName": null,
          "libraryConstructionApproach": null,
          "instrument": null,
          "protocolId": "dis_proc_1",
          "protocol": null
        },
        {
          "processName": [
            
          ],
          "libraryConstructionApproach": [
            
          ],
          "instrument": [
            
          ],
          "protocolId": [
            "seq_protocol_1",
            "lib_prep_1"
          ],
          "protocol": [
            
          ],
          "processId": "seq_proc_30"
        }
      ],
      "entryId": "ffffce6b-6e5a-4dd9-a964-652548bee34f",
      "files": [
        {
          "format": "pdf",
          "name": "d1e6c5c0-174a-4eae-9661-aa3197093f51_qc.quality_by_cycle.pdf",
          "sha1": "d8c51e20da0c8ae707764727844718483ea037aa",
          "size": 6110,
          "uuid": "8bf256f1-0cd2-4263-a62d-a62ff3efe9b4",
          "version": "2018-09-06T190441.915208Z"
        },
        {
          "format": "fastq.gz",
          "name": "SRR3934382_1.fastq.gz",
          "sha1": "bc836c215f2dd9aa14bfd1fd9864d06292f21e1d",
          "size": 52477054,
          "uuid": "f0223b68-2419-44a6-a863-d10fac2fa224",
          "version": "2018-09-06T180048.131811Z"
        },
        {
          "format": "fastq.gz",
          "name": "SRR3934382_2.fastq.gz",
          "sha1": "e4f004f37b881de9bb6d363bf1ede5d9c6f47493",
          "size": 55016801,
          "uuid": "ae406bf2-4ca5-4f52-b3e9-b11baa2e9543",
          "version": "2018-09-06T180048.345040Z"
        }
      ],
      "projects": [
        {
          "projectShortname": "scale\/gliob_200\/2018-09-06T17:42:54Z",
          "laboratory": [
            "Stephen Quake"
          ]
        }
      ],
      "specimens": [
        {
          "id": "BT_S2_T",
          "genusSpecies": [
            "Homo sapiens"
          ],
          "organ": [
            "brain"
          ],
          "organPart": [
            "temporal lobe"
          ],
          "organismAge": [
            
          ],
          "organismAgeUnit": [
            
          ],
          "biologicalSex": [
            "unknown"
          ],
          "disease": [
            
          ],
          "storageMethod": [
            
          ],
          "source": [
            "cell_suspension",
            "specimen_from_organism",
            "donor_organism"
          ],
          "totalCells": 1
        }
      ],
      "bundles": [
        {
          "bundleUuid": "7138a744-928c-406f-b9cf-24a8681ad092",
          "bundleVersion": "2018-09-06T190449.303445Z"
        }
      ]
    },
```

I am expecting to see only one file. Instead I see 2 fastq and a pdf.
Is this a data problem or problem with the index etc?

Cheers,
Dave

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-206)
┆Project Name: azul
┆Issue Number: AZUL-206

**Comment by achave11** [comment]
Is this a `File API` or a `File bundles` API @mikebaumann

**Comment by mikebaumann** [comment]
I agree with @NoopDog, the response from a files query should contain one file per hit/record returned. @NoopDog have you noticed a recent change to this behavior? It looks like the portion of indexer code that I think would be responsible for this was last changed by @caaespin two months ago. There is reason to believe it was that change that introduced this alternate/unexpected/unwanted behavior.

**Comment by mikebaumann** [comment]
@GPelayo I suspect this change in behavior was introduced in https://github.com/DataBiosphere/azul/commit/1ce208a101ef4d5285d509bdca65b8c6490eac6b

Specifically, in the change to `FileTransformer` (in transfomers.py).
I suspect it may be visiting the relatives of the file that is causing the additional files to be pulled in that should not be. I don't know if visiting the relatives is needed, @hannes-ucsc would know, and you may be able to figure that out.
```
        # Visit the relatives of file
        file.accept(visitor)  # Visit descendants
        file.ancestors(visitor)
```

**Comment by caaespin** [comment]
Appears I've been invoked.

A couple things:

- The hit in @NoopDog example is an Analysis bundle.
- Also notice that none of the file uuids in @NoopDog example match with the `entry_id`.
- The `entry_id` represents, I suspect, the uuid of the metadata file from Analysis (see the following snippet from GET bundle from DSS):
```
      {
        "content-type": "application/json; dcp-type=\"metadata/file\"",
        "crc32c": "a523fb9e",
        "indexed": true,
        "name": "analysis_file_20.json",
        "s3_etag": "5e5b43c3badb894993f37dc09cbb8a1d",
        "sha1": "72cf36f92236e555817e863b73f0bfb02554f661",
        "sha256": "0afbab4219f62350a725846c96e42e1f9fb4dda429f67e2110990238f3bdcf7a",
        "size": 460,
        "uuid": "ffffe349-f7c5-493e-94fd-d47321a3906f",
        "version": "2018-09-11T183059.995175Z"
      },
```

Look at how the indexer receives a bundle from analysis and unpacks it. Make sure the links provided follow the model that currently exists/is supported by the indexer.

It's also possible that the change of metadata schema/storing (1 metadata file vs multiple metadata files) could have resulted in this bug.

**Comment by mikebaumann** [comment]
Hi @caaespin! What a pleasant surprise! Hope you are doing well!
