### ISSUE TITLE
Install service software updates for ES in dev and sandbox

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3135]

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Do this using the AWS console and do it in dev first. Before upgrading sandbox, notify team."

**Comment by jessebrennan** [comment]
Latest service updates have been installed for `dev` and `sandbox`.

![dev](https://user-images.githubusercontent.com/10734740/124009906-01e2e900-d993-11eb-8d2b-53ba3fe3f696.png)
![sandbox](https://user-images.githubusercontent.com/10734740/124009908-027b7f80-d993-11eb-935e-79db5d920c4c.png)

**Comment by hannes-ucsc** [comment]
Looks good.
