### ISSUE TITLE
Increase `contribute` lambda concurrency and slots to 300 in prod

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3137]

**Comment by hannes-ucsc** [comment]
Demo is a bit complicated. We can only really demo this in `prod`. The operator should reindex `dev` after this lands there, for evidence that it doesn't break anything and that 100 slots are purchased. When we next perform a reindex in prod, I or whoever else has full access to `prod` should confirm that 300 slots are purchased and that the `-contribute` has a concurrency of 300 and take screenshots for evidence.

**Comment by hannes-ucsc** [comment]
For demo, when this lands in `prod` and a reindex was subsequently performed there, show evidence that 300 slots were automatically purchased. Show that concurrency settings of all `prod` indexer lambdas. Might need operator help with this demo.

**Comment by jessebrennan** [comment]
For demo:
- 300 slots were reserved
  ![prod-slots](https://user-images.githubusercontent.com/10734740/130154695-7c03f711-ef2f-4ea0-ac97-ace93c43ba44.png)
- concurrency was set to 300 for contribute lambda
![prod-concurr](https://user-images.githubusercontent.com/10734740/130154838-8d4e4334-aee6-42eb-9a4f-88c5fa53f8f1.png)
