### ISSUE TITLE
`terra.pfb` manifest IT fails on prod

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3138]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/3604#L1604

**Comment by melainalegaspi** [comment]
@jessebrennan spike for estimate.

**Comment by jessebrennan** [comment]
@hannes-ucsc: "Bumping estimate to account for using a newer bundle for `test_pfb_manifest()`."

**Comment by hannes-ucsc** [comment]
For demo, https://github.com/databiosphere/azul/issues/1430#issuecomment-857873601

**Comment by jessebrennan** [comment]
Demo blocked, see https://github.com/DataBiosphere/azul/issues/1430#issuecomment-866164486
