### ISSUE TITLE
Simplify / consolidate the Operator Manual

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3141]
... with a special emphasis in making simple checklists for procedures.

**Comment by amarjandu** [comment]
Adding the Sections and nested headers makes this much easier to read, nice work on the ToC as well.

It looks like in the `getting started section` roman numerals are used, then in the `prod deployment` section the formatting switches to digits, is there a way to get consistent digits?

**Comment by jessebrennan** [comment]
> It looks like in the getting started section roman numerals are used

They are used here because they are indented one level, under the bullet point. If there were no bullet points they would be Arabic. There is no way to force the formatting to Arabic, other than change the structure of the document, which I'd rather not do.

**Comment by hannes-ucsc** [comment]
LGTM

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/wiki/Operator-Manual
