### ISSUE TITLE
Include `CommandLine` response item on all `/fetch/manifest/files` responses

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3142]
The fix for #2875 causes that the final response from `/fetch/manifest/files` points back to `/manifest/files` instead of the signed URL of the manifest object in Azul's staging bucket. We did this because the `/manifest/files` URL doesn't expire. It will redirect to the signed URL.

This change requires that if curl is used to fetch the manifest, it needs to be given the `--location` flag in order to follow the redirect. Otherwise it silently succeeds without downloading anything.

We already have a `CommandLine` response item but it is currently only used for the `curl`-format manifest. We should include that item for all formats and mention the `--location` flag in that item.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Also add --remote-name (-O), and test whether that works."

**Comment by hannes-ucsc** [comment]
For demo, show new response item for all manifest formats.
