### ISSUE TITLE
Terra PFB import fails from personal deployment

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3148]

**Comment by melainalegaspi** [comment]
@jessebrennan spike to reproduce.

**Comment by jessebrennan** [comment]
It looks like Terra may be allow-listing what servers it accepts PFB imports from.

![terra-import-fail-pfb](https://user-images.githubusercontent.com/10734740/126852804-ec752bea-aa21-4709-8b00-7a6e9f90e798.png)

The URL shown in the screenshot: https://service.dev.singlecell.gi.ucsc.edu/manifest/files?catalog=dcp2&format=terra.pfb&filters=%7B%22fileFormat%22%3A+%7B%22is%22%3A+%5B%22bam%22%5D%7D%2C+%22genusSpecies%22%3A+%7B%22is%22%3A+%5B%22Mus+musculus%22%2C+%22Homo+sapiens%22%5D%7D%7D&objectKey=manifests%2Fc02d1e4d-9687-564e-9b45-a9e7d907dd04.avro was the URL listed with the 302 response from the /fetch/manifest/files endpoint. I assume this is the URL that the browser will use when it redirects to Terra.

This will probably be a Terra stub ticket.

**Comment by melainalegaspi** [comment]
@jessebrennan to reach out to Terra about this.

**Comment by theathorn** [comment]
From Matt Bemis on [this](https://humancellatlas.slack.com/archives/C018YPVKC73/p1627329947003500) Slack thread on 8/6/21: "Actually, we were able to squeeze a release in today. service.azul.data.humancellatlas.org and service.dev.singlecell.gi.ucsc.edu should now be supported on production"

**Comment by jessebrennan** [comment]
When trying to validate this I encounter an internal server error. I suspect the error is caused by #3313. I'll add a blocking relationship and we can validate / close this once #3313 is merged.

**Comment by melainalegaspi** [comment]
Triage to determine if blocked label is still justified.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Assignee to attempt to reproduce after #3313 lands in prod, close if not reproducible anymore."
