### ISSUE TITLE
Time zones for timestamps

### ISSUE THREAD

**Issue by david4096** [DataBiosphere/azul#315]
We believe we're observing malformed timestamps in the ES instance. Is it by design they shouldn't have a timezone? Are we right to add zulu?

Thanks!

https://github.com/DataBiosphere/dos-azul-lambda/issues/89

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-208)
┆Project Name: azul
┆Issue Number: AZUL-208

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
