### ISSUE TITLE
Purchase SmartGit licenses

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3151]
Spike to research SmartGit costs and benefits of commercial vs open source licensing.

**Comment by achave11** [comment]
http://www.syntevo.com/doc/display/SG/Commercial-only+features
![Screen Shot 2021-06-17 at 11 23 43 AM](https://user-images.githubusercontent.com/19215510/122595666-a6713c80-d01d-11eb-9191-1b0e5dc6f175.png)

* JIRA Integration
	- Allows to select a commit message directly from JIRA issues and to optionally mark issues as resolved on Push.
* GitHub Enterprise Integration
	- Tailored version of GH with more support and integrations with IDEs and pipeline tools.
* Bitbucket Server (Atlassian Stash) integration
	- Integrates with BitBucket Server, similar to GH integration on Atlassian Stash.
* License Additions:
	- Distributed Reviews
		+ Allows us to create Pull Request from one branch to another and to comment on pull requests and individual commits locally, when the branch is pushed the comments are posted. Comments can be deleted before pushing and don't get published.
	- DeepGit license included
		+ Enhanced version of git blame, easier to trace origin of file/changes.
		
Individual license purchase…
![Screen Shot 2021-06-18 at 11 19 34 AM](https://user-images.githubusercontent.com/19215510/122602576-ec330280-d027-11eb-93e7-fd608884ee6e.png)


… not too much info in company licenses, might need to contact their sales team.
![Screen Shot 2021-06-18 at 11 24 27 AM](https://user-images.githubusercontent.com/19215510/122602544-df161380-d027-11eb-899b-5e6b1ddf21fa.png)

**Comment by achave11** [comment]
@jessebrennan: "Non-Commercial Licenses
SmartGit can be used free of charge by Open Source developers, teachers and their students, or for hobby, non-paid usage. We are also supporting certain public welfare or charity organizations. If in doubt, please contact sales."

**Comment by achave11** [comment]
@hannes-ucsc: "By that definition we are open source developers, that we don't need any of the commercial only features, so we'll continue to use the non-commercial license "
