### ISSUE TITLE
`dss.Plugin.sources` has inconsistent and inaccurate type annotation 

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3155]
`azul.plugins.RepositoryPlugin` declares the abstract method `sources(self) -> AbstractSet[SOURCE_NAME]` ([ref](https://github.com/DataBiosphere/azul/blob/1fe9bf727490d5e7e1a9186633f23cf39d40ef05/src/azul/plugins/__init__.py#L186)). `azul.plugins.repository.dss.Plugin` implements this method and declares the return type annotation to be `AbstractSet[str]` ([ref](https://github.com/DataBiosphere/azul/blob/1fe9bf727490d5e7e1a9186633f23cf39d40ef05/src/azul/plugins/repository/dss/__init__.py#L100
)), contradicting the parent class's annotation. In addition to being inconsistent with the parent class, the type annotation is inaccurate, because the actual value returned is of type `Set[Optional[str]]`, not `Set[str]`.

**Comment by noah-aviel-dove** [comment]
There are also several type warnings in the Canned Plugin that seem to reflect the same issue, where `SimpleSourceName` is conflated with `str`.

**Comment by melainalegaspi** [comment]
@noah-aviel-dove to decide which PR to make this a freebie of.
