### ISSUE TITLE
Flake8 plugin does not enforce consistent ordering of import statements

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3156]
In `scripts/can_bundle.py`, the import statement:

```
from args import (
    AzulArgumentHelpFormatter,
)
```

Can be placed at multiple positions in the list of import statements without evoking an error from the flake8 plugin, which ought to enforce a uniquely correct sequence of import statements. The pertinent section of the contributing guide that is violated is:

```
We sort imports first by category, then lexicographically by module name and then by imported symbol. The categories are

i. Import of modules in the Python runtime
ii. Imports of modules in external dependencies of the project
iii. Imports of modules in the project
```

The `args` import can be placed at any position relative to categories (i), (ii), or (iii) so long as it does not interrupt a category.

**Comment by noah-aviel-dove** [comment]
The flake8 plugin runs in the project root directory, and thus is unable to resolve imports in subdirectories that are not in `$PYTHONPATH`, e.g. `scripts/`. Thus, the plugin cannot resolve the import statement `from args import AzulArgumentHelpFormatter` in `scripts/*.py` and skips the ordering check.

Potential fixes:
 - Add `scripts/` to `$PYTHONPATH` (very easy)
 - When failing to resolve an import, the plugin inspects the filename of the source file being checked and tries to manually find the file being imported (complicated and probably error prone)

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"To emulate Python's behavior of adding a script containing directory to the Python path, the flake8 plugin should temporarily patch sys.path to include /scripts while checking the script."

**Comment by noah-aviel-dove** [comment]
https://github.com/DataBiosphere/azul/issues/3254 Removes the case this ticket was originally met to address and implies a different strategy going forward. However its still valuable to detect these import resolution failures. Instead of warning about these failures, they should be errors, and we should hard-code exceptions for known and accepted resolution failures such as pydevd. This way we gain the benefits from the first commit of this PR while retaining compatibility with the original scope of the ticket.
