### ISSUE TITLE
If our configuration wasn't serialized in environment variables we could simplify it with more structured data

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3161]
I'm thinking specifically of `AZUL_CATALOGS` and `AZUL_TDR_SOURCES` which are partially redundant and could be stored more neatly if combined into a single data structure.

This would also remove the need to do any complicated parsing in `azul/__init__.py` since we would just import the correct config file for configuration.

**Comment by melainalegaspi** [comment]
duplicates #3114 and #2945. 

@hannes-ucsc : "We intentionally use environment variables such that configuration is implicitly by any child process of the shell that loaded the environment."
