### ISSUE TITLE
Cleanup unused indices from `prod` 

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3166]
Found unused indices in [dev](https://github.com/DataBiosphere/azul/issues/3164), `prod` should also be inspected for unused indices.

**Comment by hannes-ucsc** [comment]
![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/182f573f-ad5f-457a-8136-6ff7ec176d25)

61 lines

1 .kibana instance

6 catalogs * 2 sets * 5 entity types == 60

6 catalogs: dcp0, it0, dcp7, it7, lungmap, it0lungmap
2 sets: contributions, aggregates
5 entity types: projects, samples, files, cell_suspensions, bundles
