### ISSUE TITLE
HCA CloudWatch Event failures

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#317]
#data-portal-dev 9/13: Matt Weiden [9:25 AM]
Hey DataPortal eng team :wave: Heads Up: you have CloudWatch Event failures `https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~(metrics~(~(~'AWS*2fEvents~'FailedInvocations~'RuleName~'azul-indexer-hannes-worker~(stat~'Sum~period~60))~(~'...~'azul-indexer-jyo-worker~(stat~'Sum~period~60))~(~'...~'test~(stat~'Sum~period~60~visible~false)))~view~'timeSeries~stacked~false~region~'us-east-1);search=FailedInvocations;namespace=AWS/Events;dimensions=RuleName`

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-210)
┆Project Name: azul
┆Issue Number: AZUL-210

**Comment by hannes-ucsc** [comment]
Failures generated by personal deployments of Azul are to be expected and should not be cause for concern.
