### ISSUE TITLE
Canned repository refers to SourceName instead of SourceSpec

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3174]
Some references to SourceName were not updated to SourceSpec in #3047 
ex. 

https://github.com/DataBiosphere/azul/blob/925fb130913df5a14c8fd4d5bef76665a266cc41/src/azul/plugins/repository/canned/__init__.py#L100

**Comment by melainalegaspi** [comment]
Closing in favor of reopening #3047.
