### ISSUE TITLE
Provide body with command lines on responses to /manifest/files

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3177]
@hannes-ucsc: '301 and 302 can actually carry a body. We should include instructions to use the `--location` flag with `curl` in the body of those responses. We could also list the full command line, just like we do for the fetch endpoints. The actual implementation would be to be refined as we go using experiments with `curl` and what the look and feel is.'

Conv: https://github.com/DataBiosphere/azul/pull/3112#discussion_r655808294

**Comment by hannes-ucsc** [comment]
For demo, request `/manifest/files` with `curl` and no additional options. It should print the response body. Show that the body is included in both 301 and 302 responses.
