### ISSUE TITLE
Create Runbook of release and operations procedures

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#318]
See https://app.zenhub.com/workspace/o/humancellatlas/dcp/issues/70

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-211)
┆Project Name: azul
┆Issue Number: AZUL-211
┆Epic: Production Ready Indexer/Web Service/Browser

**Comment by theathorn** [comment]
Need a page in Allspark that links to the Azul readme.

**Comment by achave11** [comment]
Resolved by https://github.com/DataBiosphere/azul/pull/821

**Comment by jessebrennan** [comment]
I never made a link in the allspark page.

**Comment by jessebrennan** [comment]
https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home @theathorn is this to your satisfaction? Please review.
