### ISSUE TITLE
Terra handover broken due to change in final redirect URI

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3181]
I think https://github.com/DataBiosphere/azul/commit/f5a00434c822b7bc258faa250f333d451ef335d1 may have broken the Terra hand-over.

**Comment by hannes-ucsc** [comment]
Spike to verify.

**Comment by achave11** [comment]
By following the [export URL](https://bvdp-saturn-dev.appspot.com#import-data?url=https%3A%2F%2Fservice.dev.singlecell.gi.ucsc.edu%2Fmanifest%2Ffiles%3Fcatalog%3Ddcp2%26format%3Dterra.bdbag%26filters%3D%257B%2522fileFormat%2522%253A%2B%257B%2522is%2522%253A%2B%255B%2522pdf%2522%255D%257D%252C%2B%2522genusSpecies%2522%253A%2B%257B%2522is%2522%253A%2B%255Bnull%255D%257D%257D%26objectKey%3Dmanifests%252F27b52dbe-ad5f-53db-82ed-c9a2f33bc291.zip)
![Screen Shot 2021-06-24 at 3 54 29 PM](https://user-images.githubusercontent.com/19215510/123344194-332d6600-d508-11eb-838d-f45313b22979.png)

I was able to see the manifest data in a Terra workspace…
![Screen Shot 2021-06-24 at 3 55 31 PM](https://user-images.githubusercontent.com/19215510/123344311-6ec83000-d508-11eb-9773-50df2c4c0c8b.png)

… verifying that the Terra handover isn't broken. Terra handover in `prod` also behaves as expected.

**NOTE:** I was unable to see my terra workspace and get to the exported data in terra using Chrome. My spike was done using the Firefox browser.

**Comment by achave11** [comment]
**NOTE 2**: Reverting Chrome general setting for Allowed Cookies from `Block third-party cookies` to `Allow all cookies` fixed the chrome problem.
