### ISSUE TITLE
Deployment stage failing because of AWS outage

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3188]
I expect this will resolve soon, but I'm documenting the error for posterity.

I retried the build and it failed again with the same error.

Failing build:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/23150

![aws-outage.png](https://images.zenhubusercontent.com/5bfc77a68ffeb454062a138a/b3354232-c319-4f93-899c-e3ca9ce528d1)

https://status.aws.amazon.com/

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "The outage is now over."
