### ISSUE TITLE
Can new bundles from prod for matrix test cases

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3192]
#3096 depends on this.

Replace the modified canned bundles used in matrix-related test cases with newly canned bundles from `prod`.

The new canned bundles should include:

1) A hacky CGM subgraph (ideally same project as # 4)
2) A hacky DCP/1 matrix service subgraph (maybe same project as # 4)
3) An intermediate DCP/2 analysis subgraph (same project as # 4) (10x)
4) A top-level DCP/2 analysis subgraph (10x)
5) An organic CGM subgraph

After adding these new canned bundles, check the history of the existing canned bundles and revert any changes that were made to facilitate matrix related tests (example: see `f0731ab4-6b80-4eed-97c9-4984de81a47c.metadata.json`)

**Comment by hannes-ucsc** [comment]
For demo, show that cans have been reverted to their original content.
