### ISSUE TITLE
OSError writing contributions with parallel_bulk in `prod` (dcp7)

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3200]
```
[WARNING] 2021-07-03T12:56:05.092Z 2bc0b431-8d78-5f84-9a5b-ed6bed6d47ff Worker failed to handle message {'action': 'add', 'notification': {'source': {'id': '83752bf1-44fa-46d8-abec-0f5982e21cdd', 'spec': 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2__20210701_dcp7:'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': 'd0f3a049-1f42-4549-b0d1-5d1420c3d84d', 'match': {'bundle_uuid': '927e2488-a03e-4c4e-9e97-7e095223584c', 'bundle_version': '2021-06-04T07:09:38.070000Z'}}, 'catalog': 'dcp7'}.
Traceback (most recent call last):
File "/var/task/azul/indexer/index_controller.py", line 155, in contribute
tallies = self.index_service.contribute(catalog, contributions)
File "/var/task/azul/indexer/index_service.py", line 202, in contribute
writer.write(contributions)
File "/var/task/azul/indexer/index_service.py", line 577, in write
self._write_bulk(documents)
File "/var/task/azul/indexer/index_service.py", line 616, in _write_bulk
for success, info in response:
File "/opt/python/elasticsearch/helpers/actions.py", line 350, in parallel_bulk
pool = BlockingPool(thread_count)
File "/var/lang/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
Pool.__init__(self, processes, initializer, initargs)
File "/var/lang/lib/python3.8/multiprocessing/pool.py", line 196, in __init__
self._change_notifier = self._ctx.SimpleQueue()
File "/var/lang/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue
return SimpleQueue(ctx=self.get_context())
File "/var/lang/lib/python3.8/multiprocessing/queues.py", line 336, in __init__
self._rlock = ctx.Lock()
File "/var/lang/lib/python3.8/multiprocessing/context.py", line 68, in Lock
return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 38] Function not implemented
```

Affected subgraphs

- 46f6a11f-88ba-453c-a08d-27fa8ed5184a
- 927e2488-a03e-4c4e-9e97-7e095223584c

**Comment by theathorn** [comment]
@hannes-ucsc "spike to establish whether this is the first time we crossed the parallel bulk threshold or whetehr support for SemLock was recently removed from AWS Lambda runtime".

**Comment by jessebrennan** [comment]
Shared memory is not supported in Lambdas, see https://forums.aws.amazon.com/thread.jspa?threadID=219962 for the oldest official record I can find of that (2015).

A potentially useful resource I found from Amazon: https://aws.amazon.com/blogs/compute/parallel-processing-in-python-with-aws-lambda/

**Comment by jessebrennan** [comment]
Subgraph 46f6a11f-88ba-453c-a08d-27fa8ed5184a creates 2170 contributions.

**Comment by jessebrennan** [comment]
I also searched the dev CloudWatch logs all the way back in time and there are no records of parallel_bulk being used.

**Comment by jessebrennan** [comment]
@hannes-ucsc: "Estimating 2 assuming that the quick fix works."

**Comment by jessebrennan** [comment]
The simple fix works, but requires some additional tweaks in order to pass unit tests locally. Testing subgraph 46f6a11f-88ba-453c-a08d-27fa8ed5184a on my machine took 4min 22 seconds.

Tweaks that were necessary:
- decrease chunk size for bulk ES queries (see https://github.com/DataBiosphere/azul/issues/2903)
- decrease page size for scan from 1000 to 500

I suspect that these tweaks would not be necessary for a real ES instance.

**Comment by hannes-ucsc** [comment]
For demo, show that affected bundles are present in dcp7 catalog on prod. Wait until resolution lands in prod.

**Comment by jessebrennan** [comment]
For demo:

- https://service.azul.data.humancellatlas.org/index/bundles/46f6a11f-88ba-453c-a08d-27fa8ed5184a?catalog=dcp7
- https://service.azul.data.humancellatlas.org/index/bundles/927e2488-a03e-4c4e-9e97-7e095223584c?catalog=dcp7

**Comment by jessebrennan** [comment]
@hannes-ucsc to look at the contributions again to explain why the aggregate is so small despite the large number of contributions.

**Comment by hannes-ucsc** [comment]
I started canning one of those bundles again and saw that it had 2000+ cell suspensions. These are aggregated grouped by organ type which is why we only see one cell suspension in the bundle aggregate. All cell suspension have the same organ.

https://github.com/DataBiosphere/azul/blob/c927cfcb455fe7718ea58ace3ba61d581277ef30/src/azul/plugins/metadata/hca/aggregate.py#L106

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/4824357e-7622-48b6-9746-5a5b45a6f2d0)

So all is good.
