### ISSUE TITLE
Integration test fails due to unexpected entries

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3233]
Incomplete deletions are causing transient failures during IT. Rerunning the IT can resolve the issue,
see: 
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/24315

https://github.com/DataBiosphere/azul/blob/2d2016c0fcf2b3408197e25505c246d9c68aa6ff/test/integration_test.py#L686

**Comment by hannes-ucsc** [comment]
Also this one https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/24290

**Comment by melainalegaspi** [comment]
@hannes-ucsc spike to determine if this is a duplicate or not.

**Comment by hannes-ucsc** [comment]
Duplicates #2330. That might not be obvious from the symptoms in the description of that ticket, but we updated the assertion code and [later comments](https://github.com/DataBiosphere/azul/issues/2330#issuecomment-738344124) link to IT failures that resemble the symptom listed in this issue.
