### ISSUE TITLE
Create azul-public-prod in Terra `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3235]
… and grant it access to all snapshots. ~Without it, we can't promote to `prod`.~

Edit: We can fake it by adding the SA that we use as a proxy for anonymous users to the `azul-prod` group.

**Comment by hannes-ucsc** [comment]
This lost its urgency. It's not blocking the promotions. See my edit to the description.

**Comment by hannes-ucsc** [comment]
Pinged Monster about this: https://humancellatlas.slack.com/archives/C01360XN04S/p1626378703193200

**Comment by theathorn** [comment]
We asked Jeff Korte if "the snapshots that are supposed to be accessible publicly are marked as "public" in TDR prod" and he replied "yes.  That is standard operating procedure for us."
