### ISSUE TITLE
In Staging the "Estimated Cells" count is displaying zero in the Browser

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#324]
@NoopDog confirmed the summary API is returning zero.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-212)
┆Project Name: azul
┆Issue Number: AZUL-212

**Comment by hannes-ucsc** [comment]
<img width="1198" alt="screen shot 2018-09-26 at 11 38 14 pm" src="https://user-images.githubusercontent.com/5143256/46127357-4be88000-c1e5-11e8-87cb-b219d96b1925.png">

Can't reproduce.
