### ISSUE TITLE
Lambda layer issues

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3244]
While diagnosing an issue with a lambda layer that was missing a wheel, we @danielsotirhos and I encountered the following problems.

- Deployments shouldn't share layers. It's too risky to share them, the `dev` deployment shouldn't use a layer created on a local machine for a personal deployment. The local machine could be broken, the packaging code in the currently checked out Azul source tree could be broken. Two ways to solve this: store the layer in the storage bucket but that bucket may not yet exist when the layer is staged. The alternative is to keep the layer in the shared config bucket and use the deployment name as an additional "directory" component of the object key.

- The layer name is unnecessarily long. One hash over the content of all input files would suffice.

- The hash should include all relevant source files, including the Python script that post-processes the layer. Think hard about additional hash keys, the Chalice version comes to mind. But see next bullet.

- Tainting the layer is awkward. Use a layer major version number instead. Hard code that version in the layering script. If the content hash of the layering script is used as a hash key, you're done. If not, include the number verbatim in the object key (not in the hash).

- There should be a sanity check to protect against incomplete deployment package zip e.g. in case wheels are missing. Listing all `.dist-info` directories in the .zip and comparing their names against the entries in requirements*.txt should do the trick.
 
- A zip built on Linux contains duplicate entries for all wheel files, the wheel pip builds by itself and the a duplicate entry from the unzipped wheel in the vendor directory. At deploy time, generate the requirements files in the lambda dirs, filtering out the package/version tuples that match any wheels. If a package matches, but not the version we should fail because the wheel needs to be replaced.

- The `.so` for `grpcio` built on my ubuntu is 132MB, the downloaded one is 9MB, so locally built layers on Ubuntu are much bigger.  The duplicates now cause the prod layer to be too big https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/5231/raw
  a layer built on macos is 25 MB, a layer built on GH is 68 MB (https://s3.console.aws.amazon.com/s3/object/edu-ucsc-gi-azul-dcp2-prod-config.us-east-1?region=us-east-1&prefix=azul%2Flambda_layer%2Fb8b689c0f7e6b43adbe545ec6b27708d0bed2c39.e8101e9d969d309cd86a358543964eac19fe445b.zip&tab=versions) The previous bullet will fix this.

**Comment by jessebrennan** [comment]
For consideration, we could also potentially use [Chalice's native layering](https://aws.amazon.com/blogs/developer/using-aws-lambda-layers-with-aws-chalice/).

The biggest complication with this, that I'm aware of, is Chalice will put any dependencies in the `vendor/` directory into the layer. This won't work for Azul because we link all of Azul's code from the `vendor/` directory.

**Comment by hannes-ucsc** [comment]
> For consideration, we could also potentially use [Chalice's native layering](https://aws.amazon.com/blogs/developer/using-aws-lambda-layers-with-aws-chalice/).

Which of the above issues would that address?

**Comment by jessebrennan** [comment]
>* Tainting the layer is awkward. Use a layer major version number instead. Hard code that version in the layering script. If the content hash of the layering script is used as a hash key, you're done. If not, include the number verbatim in the object key (not in the hash).

Are you suggesting that, to regenerate a layer, one should make a code change to the version number in the layer script?

> * A zip built on Linux contains duplicate entries for all wheel files because pip builds the wheel by itself and the a duplicate entry from the unzipped wheel in the vendor directory. Filtering the requirements*.txt should do the trick. Instead of symlinking those files into the lambda/* subdir, copy them and remove any entry referring to a wheel.

I don't know what "Filtering the requirements*.txt should do the trick" means. I don't see any entries in the requirements file referring to a wheel. Don't we want the symlink so that the global req files stay in sync with what's in the layer? I've ready this whole bullet a lot of times and I'm just not grokking it.

**Comment by jessebrennan** [comment]
First we will upgrade Chalice, as in #3290, then revisit this ticket and see how many of these issues still apply. @hannes-ucsc approves this message.

**Comment by melainalegaspi** [comment]
@jessebrennan spike for an estimate.

**Comment by jessebrennan** [comment]
I would break this down into two separate tickets as suggested.

First ticket: estimate 1
- Move layers to per-deployment-storage bucket
- Shorten layer name. Layer scripts should be part of hash, Chalice version, all files in wheels dir, etc.
- Stop tainting layers. A more inclusive hash is sufficient to trigger a TF update.

Second ticket: estimate 3
- Add steps to layer generation that copies requirements files, filtering out any requirements listed in wheels directory.
- Add sanity check that lists everything in zip and compares against requirements.
