### ISSUE TITLE
Add filter for contributor name

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3251]
Allow for search by contributor name (project.contributors.name) as per the blocked data browser ticket.

**Comment by hannes-ucsc** [comment]
We do index that field but we don't have a filter for it. I adjusted the title accordingly. I'm assuming we don't need a corresponding `termFacets` entry. IOW, I assume that the search in DB will be done by typing the contributor's name, not selecting a contributor name from a facet drop down.

**Comment by bvizzier-ucsc** [comment]
@hannes-ucsc:  "Blockee was closed as obsolete."
