### ISSUE TITLE
Service makes a redundant HEAD request to check cache for every partition

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3258]
One might say that there is no point in continuing to look for a cached manifest for every partition and therefore every step of the step function execution. After all, the step function execution was kicked off *because* there was no cached manifest in the first place.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to create ticket about concurrency issue.

**Comment by hannes-ucsc** [comment]
Now part of #3271. Re-triage and close.
