### ISSUE TITLE
Represent SourceSpec instances as JSON, not strings of proprietary syntax

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3259]
In the index, instead of 

```json
{
    "source": {
        "id": "c3c588a8-be3f-467f-a244-da614be6889a",
        "spec": "tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201118_dcp1___20201209:/2"
    }
}
```

we could do

```json
{
    "source": {
        "id": "c3c588a8-be3f-467f-a244-da614be6889a",
        "spec": {
            "prefix": {
                "common": "",
                "partition": 2
            },
            "plugin": "tdr",
            "type": "snapshot",
            "name": "hca_prod_20201118_dcp1___20201209",
            "project": "broad-datarepo-terra-prod-hca2" 
        }
    }
}
```

Similarly for the service responses.

**Comment by noah-aviel-dove** [comment]
If we make this change it should also be applied to `/repository/sources` which matches the format of the `sources` element of the hits but constructs its response independently.

**Comment by hannes-ucsc** [comment]
I'm not sure we really need this level of detail. There is no law prohibiting embedding one syntax in another. It's quite common, actually. Programmatically, both options are equally convenient/inconvenient since we have ways to parse and generate either form.

The question really is whether the users care and whether we would ever filter or aggregate based on the parts of a spec.

**Comment by melainalegaspi** [comment]
See https://github.com/DataBiosphere/azul/issues/3114#issuecomment-884422589
