### ISSUE TITLE
Set up prod operator rotation 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3273]
~Discuss with Erich if it's possible to rotate operator role for prod.~

**Comment by hannes-ucsc** [comment]
Email sent.

**Comment by hannes-ucsc** [comment]
Added steps to 

https://github.com/DataBiosphere/azul/wiki/Operator-Manual#getting-started-as-operator

and emailed Erich to announce the emails by operators requesting access.
