### ISSUE TITLE
Document weekly prod promotion in operator manual

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3274]
Record in operator manual that every Wednesday at 3pm, production reindex should be kicked off. Also set up Slack reminder on for Tuesday the day before. 

Wait until Hannnes is back from PTO (the week of 8/2/2021) to implement this scheduled occurrence.

**Comment by jessebrennan** [comment]
I set up a Slack reminder, I guess we'll find out next Tuesday if it actually works.

**Comment by jessebrennan** [comment]
The manual is updated: https://github.com/DataBiosphere/azul/wiki/Operator-Manual#promoting-to-prod

**Comment by amarjandu** [comment]
There was a punctuation typo, I went ahead and fixed it. LGTM.
