### ISSUE TITLE
Delete `carlos` and 'alex' deployments

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#328]
Running out of resources, we need to delete unused deployments.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-214)
┆Project Name: azul
┆Issue Number: AZUL-214

**Comment by alex-hancock** [comment]
No need to revive `alex` deployment, it has been replaced. Destroying the other two deployments will suffice to close this issue.

**Comment by hannes-ucsc** [comment]
Check for ES indices, SQS queues and deployed lambdas.

**Comment by achave11** [comment]
Lambda Deleted Name |  | Runtime | Code size | Last modify
-- | -- | -- | -- | --
azul-indexer-hancock-index |   | Python 3.6 | 11.9 MB | last month
azul-indexer-hancock-write |   | Python 3.6 | 11.9 MB | last month
azul-service-hancock |   | Python 3.6 | 11.9 MB | last month
azul-indexer-hancock-nudge |   | Python 3.6 | 11.9 MB | last month
azul-indexer-hancock | | Python 3.6 | 11.9 MB | last month
azul-indexer-alex |   | Python 3.6 | 9.2 MB | 3 months ago
azul-indexer-alex-worker |   | Python 3.6 | 9.2 MB | 3 months ago
azul-service-alex |   | Python 3.6 | 9.2 MB | 3 months ago


Deleted Queue Name |
-- | 
azul-fail-alex
azul-notify-alex
azul-fail-hancock
azul-fail-hancock.fifo
azul-notify-hancock
azul-documents-hancock
azul-documents-hancock.fifo
