### ISSUE TITLE
Onboarding Baladithya Balamurugan to Azul

### ISSUE THREAD

**Issue by baladithyab** [DataBiosphere/azul#3283]
# Onboarding

By creating this ticket, you are requesting to be onboarded as a developer on the Azul team.
The action items in this ticket will be carried out by existing team members.
Your next step is to carefully read the following documents:

- [x] [Azul README.md](https://github.com/databiosphere/azul)

- [x] [Contributing Guidelines](https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst)

- [x] [AWS Credential Configuration](https://giwiki.gi.ucsc.edu/index.php/Overview_of_Getting_and_Using_an_AWS_IAM_Account)

Provide access to cloud infrastructure and tools:

- [x] @theathorn: [UCSC-CGL Slack](ucsc-cgl.slack.com) through your Project Manager
 
- [x] @hannes-ucsc: Push access to the Azul Repository on [#team-boardwalk](https://ucsc-cgl.slack.com/archives/C705Y6G9Z)

- [x] @hannes-ucsc: Access to development CI/CD systems on [#team-boardwalk](https://ucsc-cgl.slack.com/archives/C705Y6G9Z)

- [x] @theathorn, Erich Weiler [AWS Credentials](https://gi-gateway.signin.aws.amazon.com/console)

- [x] @hannes-ucsc: [GCP Credentials](https://console.cloud.google.com/)

- [x] Get access to the team calendar

**Comment by jessebrennan** [comment]
I've invited @Codeseys to Slack, so we can probably check that box.

**Comment by amarjandu** [comment]
Trevor has contacted Erich for cloud platform access.

**Comment by amarjandu** [comment]
@hannes-ucsc requested that we attempt to provision a service-account with `editor` access to the Google Cloud Project. Shall report if/when failures occur.

**Comment by baladithyab** [comment]
Personal deployment up and running successfully.

**Comment by baladithyab** [comment]
all items complete
