### ISSUE TITLE
Upgrade Chalice to at least 1.23.0 or later

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3290]
- [x] Remove vendored wheels for grpcio and fastavro. To do this we need to update Chalice so that it allows wheels for `manylinux2010` and `manylinux2014`. We vendor the wheels currently to work around this.

@jessebrennan "This will break the way we do our request logging. Request logging should probably be changed to use [Chalice's middleware API](https://aws.github.io/chalice/topics/middleware.html)"

**Comment by melainalegaspi** [comment]
@jessebrennan spike to estimate by exploring what other changes the chalice upgrade would entail.

**Comment by hannes-ucsc** [comment]
For demo, show that `make clean` removes the three `vendor` directories and that `git status` shows a clean working copy before and after.
