### ISSUE TITLE
Use dockerized Python interpreters on developer machines 

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3295]
PyCharm supports Python interpreters that run within Docker containers, it may be possible to utilize this feature to reduce setup/maintenance complexity of developer machines (related #3288).

There may have to be additional considerations to be made for terminal usage (scripts/make targets/etc).

<img width="951" alt="Screen Shot 2021-08-03 at 1 28 21 PM" src="https://user-images.githubusercontent.com/1947534/128082289-4a962afc-0dd9-490b-b33e-114eff73e9b5.png">

**Comment by amarjandu** [comment]
@hannes-ucsc wanted to reevaluate this in light of the MacOS issues @achave11 saw this week.

**Comment by melainalegaspi** [comment]
Iceboxing because team has more important priorities.
