### ISSUE TITLE
Analysis matrix files missing submitter_id / file_source

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3297]
The following 10 analysis files were found in the dcp7 catalog (and 1 in dcp8 catalog) with a `content_description` value of `data:3112` (Gene expression matrix), however they lack a `submitter_id` or `file_source` field. While the file_source field is not required, Azul/DataBrowser only show matrix files that have a file_source in the list of contributor generated matrices on project details page. 

```
analysis_file                           links_id                                project_id                              file_name
7a878935-fc9d-423c-843e-7578882500e1    10ebb2c5-3f73-436f-bf43-aece8e7e25a6    51f02950-ee25-4f4b-8d07-59aa99bb3498    GSE130973_matrix_raw.mtx.gz
c3cec7a4-73e8-485b-8c39-d5828976aa41    c8089427-dc20-4ee6-9876-1c29d47b0ba4    51f02950-ee25-4f4b-8d07-59aa99bb3498    GSE130973_matrix_filtered.mtx.gz
d09eed31-9694-42fd-ba92-a464d0ddd136    4029c7a5-ecf3-48f2-8dd3-45c4aaca08b8    d3ac7c1b-5302-4804-b611-dad9f89c049d    GSE141797_AHM7F7BGX5_rsem_fpkmTable.csv.gz
4434e9b2-799b-4288-bf05-d14957a5b401    4514694e-a1ef-4c29-b4f5-246f6baf6845    d3ac7c1b-5302-4804-b611-dad9f89c049d    GSE141797_AHM7F7BGX5_cuff_fpkmTable.csv.gz
e389da75-5725-4ea6-8a56-fdf20acf126a    615335eb-0dbd-44cb-831a-a454d4e0627e    d3ac7c1b-5302-4804-b611-dad9f89c049d    GSE141797_AHLWHFBGX5_rsem_fpkmTable.csv.gz
9ff93ab7-a63a-4f07-88ea-8746dd0759e3    b34f5177-1cb1-4feb-a351-170f6cd4e60c    d3ac7c1b-5302-4804-b611-dad9f89c049d    GSE138266_RAW.tar
773efd75-510b-4614-bd24-2e4715db678a    e5c13eda-e583-44a1-915f-85da7bc3114c    d3ac7c1b-5302-4804-b611-dad9f89c049d    GSE141797_AHLWHFBGX5_cuff_freatureCount.csv.gz
768eb998-ca69-4315-82f0-21616617e10e    e8892faa-5e4a-4396-8f02-235f141b28aa    d3ac7c1b-5302-4804-b611-dad9f89c049d    GSE141797_AHM7F7BGX5_cuff_freatureCount.csv.gz
d4e2ff66-847c-450f-b912-37c5668f7fcf    f17f1464-f938-4c8d-bfe9-5c08f86b2c28    d3ac7c1b-5302-4804-b611-dad9f89c049d    GSE141797_AHLWHFBGX5_cuff_fpkmTable.csv.gz
da86d37d-0dca-4fc7-81d8-12882a6c487d    702be28e-3d95-4812-a8d9-24ffdae7211a    df88f39f-01a8-4b5b-92f4-3177d6c0f242    GSE121267_RAW.tar
```

dcp8 catalog:
```
analysis_file                           links_id                                project_id                              file_name
0c308b25-2ed1-4445-9996-eb508895bf0d    834ee26e-8a92-4063-8252-dbb561196320    c5f46615-68de-4cf4-bbc2-a0ae10f08243    E-MTAB-8142.processed_1.zip
```

The queries used to find these results can be seen here: https://github.com/DataBiosphere/azul/pull/3182#discussion_r675909818

**Comment by melainalegaspi** [comment]
@danielsotirhos to reach out to the wranglers of the affected projects so they can update the metadata. Also confirm that these matrices are indeed missing from the details page of the affected projects.

**Comment by danielsotirhos** [comment]
https://humancellatlas.slack.com/archives/C9ENBPVNW/p1629751155004900

**Comment by ami-day** [comment]
Thanks @danielsotirhos I am just working on this now.

**Comment by danielsotirhos** [comment]
The 11 analysis files listed in the ticket description have been confirmed to be listed as CGM in their associated projects in the `dcp9` catalog. On the `Files` tab all these files are listed with a `File Source` value `GEO`.

https://data.humancellatlas.org/explore/projects/51f02950-ee25-4f4b-8d07-59aa99bb3498/project-matrices?catalog=dcp9

- GSE130973_matrix_filtered.mtx.gz
- GSE130973_matrix_raw.mtx.gz

https://data.humancellatlas.org/explore/projects/d3ac7c1b-5302-4804-b611-dad9f89c049d/project-matrices?catalog=dcp9

- GSE138266_RAW.tar
- GSE141797_AHLWHFBGX5_cuff_freatureCount.csv.gz
- GSE141797_AHM7F7BGX5_rsem_fpkmTable.csv.gz
- GSE141797_AHLWHFBGX5_rsem_fpkmTable.csv.gz
- GSE141797_AHM7F7BGX5_cuff_freatureCount.csv.gz
- GSE141797_AHM7F7BGX5_cuff_fpkmTable.csv.gz
- GSE141797_AHLWHFBGX5_cuff_fpkmTable.csv.gz

https://data.humancellatlas.org/explore/projects/df88f39f-01a8-4b5b-92f4-3177d6c0f242/project-matrices?catalog=dcp9

- GSE121267_RAW.tar

https://data.humancellatlas.org/explore/projects/c5f46615-68de-4cf4-bbc2-a0ae10f08243/project-matrices?catalog=dcp9

- E-MTAB-8142.processed_1.zip
