### ISSUE TITLE
Some ES requests aren't bracketed by log messages

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3312]
... so we don't know when the lambda times out while making a request.

Find all Elasticsearch requests in the codebase and make sure they are surrounded by a log statement before the request is made and after.

**Comment by melainalegaspi** [comment]
@jessebrennan : "Potential solution is to possibly modify the ES client to log automatically."

**Comment by baladithyab** [comment]
Initializing a logger using `logger.getLogger("elasticsearch.trace")` causes the pretty printed log to be read as individual lines even after editing the line ending of the logger from '\n' to ''.

`logger.getLogger("elasticsearch")` results in the log being one long Json string.

This is the following code that has been added:
```
es_trace_logger = logging.getLogger('elasticsearch.trace')
es_trace_logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler(stream=sys.stdout)
handler.terminator = ' '
es_trace_logger.addHandler(handler)
```

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/15759113/132405124-e6c7a33d-7246-4c32-be6b-3478ec7e2428.png">

**Comment by baladithyab** [comment]
`logger.getLogger("elasticsearch")` Results alongside custom formatted prefix. [ES] requests are logged by the newly implemented logger using the following lines:

```
es_trace_logger = logging.getLogger('elasticsearch')
            es_trace_logger.setLevel(logging.DEBUG)
            es_trace_formatter = logging.Formatter('[ES] %(asctime)s - %(message)s')
            handler = logging.StreamHandler(stream=sys.stdout)
            handler.setFormatter(es_trace_formatter)
            # handler.terminator = ' '
            es_trace_logger.addHandler(handler)
```

https://github.com/DataBiosphere/azul/pull/3411/commits/1e4af7b0cf52f01f67f964913aa0579cc2909b29

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/15759113/132572024-0b18d510-e37b-4870-bd53-3c23b3120da0.png">

**Comment by hannes-ucsc** [comment]
For demo, show the relevant ES log messages in CloudWatch for `dev`.
