### ISSUE TITLE
Limit PFB IDs to 254 or fewer characters

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3313]
Under some conditions, we concatenate multiple IDs together to make our PFB IDs. We need a smaller and consistent ID length. Perhaps we could store all previously concatenated IDs in a new metadata attribute. 

To reproduce:
- Download this manifest: `https://service.dev.singlecell.gi.ucsc.edu/fetch/manifest/files?catalog=dcp2&filters=%7B%0A%20%20%22cellCount%22%3A%20%7B%0A%20%20%20%20%22within%22%3A%20%5B%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%2010000%2C%0A%20%20%20%20%20%20%20%201000000000%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&format=terra.pfb`
- To prove that some IDs are too long run:
```python
import fastavro
with open('path/to/manifest.pfb', 'rb') as f:
    rs = fastavro.reader(f)
    rs = list(rs)
assert [x for x in rs[1:] if len(x['id']) > 254] == []  # Skip the first record since the metadata entity has no id field
Traceback (most recent call last):
  File "/home/jesse/gi/azul/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3435, in run_code
    await eval(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-036790dca497>", line 5, in <module>
    assert [x for x in rs[1:] if len(x['id']) > 254] == []
AssertionError
```
- To attempt import into Terra, URL encode the URL in the 302 response and pug it into `https://bvdp-saturn-dev.appspot.com/#import-data?format=PFB&url=`
- We expect the import to go successfully, but instead see an error like 
```Successfully updated 1000 entities; 13606 updates failed. First 100 failures are: samples samples_78d4aacb-337b-4167-82bc-4ae8b3df568b not found; cell_suspensions cell_suspensions_2cb7d888-09f4-4ad7-8bba-f60093a5f757 not found; sequencing_processes sequencing_processes_98deb697-fb25-4c0f-b039-c3b2111a29be not found; sequencing_processes sequencing_processes_ebff745d-507b-42ec-be47-905850207839 not found; sequencing_processes sequencing_processes_dc0a77bf-8fde-4e27-b9b9-f77882401208 not found; sequencing_inputs sequencing_inputs_2cb7d888-09f4-4ad7-8bba-f60093a5f757 not found; sequencing_processes sequencing_processes_8e09d15c-50b3-4381-8657-e63ef31d95f5 not found; donors donors_fa4495b0-2056-4978-a0bf-15a099e9caee not found; sequencing_processes sequencing_processes_41423821-1f96-4f5f-b27b-0e8940ebbb36 not found; sequencing_processes sequencing_processes_0e2a7d37-5a60-47e6-abfa-571fc1cf68e8 not found; sequencing_processes sequencing_processes_4fa6b304-2904-4239-9a8d-e19f830643fb not fou ...```

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Assignee to determine if hashing all IDs into one hash is a possible solution and whether we need to retain the IDs in a separate metadata attribute."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce in `prod`.
