### ISSUE TITLE
Prompt retry of notifications leads to persistent failures under load

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3315]
Project id: cc95ff89-2e68-4a08-a234-480eca21ce79

```
{
    "queue": "https://queue.amazonaws.com/542754589326/azul-notifications_fail-prod",
    "messages": [
        {
            "MessageId": "c7ef3949-002b-434e-b53d-0fcf67e6caab",
            "ReceiptHandle": "AQEBIw4ARY/UEi74WaIVBoTZHmFcvB05WUzV0F3WmxzfkrRtlIn+iO4zx+MNFxy+dPhLPVrV67YABHYdcBRsRDOY9MoKawJ3uK61EeVVN7PobLAHqWj+cyAAglZCe1fIajzYthE0HNE0EL9phVsHiOQq2aMp30BUHwoOe24Vb/lIPh1xLFmy9UkFz2/Y10kBACTvzPAboKYXf6V9uqdaF7doRIJzSgUtmVIoDvUX+UakA/UhQw5CXPi51rPC3xS82N4mIdfH8wSxuvJWUROqSy2907HAjrXtJcGi7HWsDPmzH+QwDP17bA61Sdjk4kK52ON0PrDQ+qKlvFrjE89cKyWxDfdAz9PWjOECyDtGXP8TaSEcsTuK7BaihY6byyDkuLhm1irfi1c48LKJUbbQu4SS+D3SGpAtZxeiNkkiBo9kcNg=",
            "MD5OfBody": "37a8bd42896bc05b39c6402e1d520681",
            "Body": {
                "action": "add",
                "notification": {
                    "source": {
                        "id": "a61115e1-ddf4-431a-8315-2cb4cb7cf87a",
                        "spec": "tdr:tdr-prd1-4265bbdb:snapshot/hca_prod_20201120_dcp2___20210730_dcp8:"
                    },
                    "query": {},
                    "subscription_id": "cafebabe-feed-4bad-dead-beaf8badf00d",
                    "transaction_id": "89788d7a-9d4f-400c-9a9d-b6743337e041",
                    "match": {
                        "bundle_uuid": "6a4dda81-d6c9-5be8-8608-c685eef62754",
                        "bundle_version": "2021-02-04T10:00:00.000000Z"
                    }
                },
                "catalog": "dcp8"
            },
            "Attributes": {
                "SenderId": "AROAX4XVRZKHHXD45CIX7:azul-indexer-prod-contribute",
                "ApproximateFirstReceiveTimestamp": "1628550028455",
                "ApproximateReceiveCount": "11",
                "SentTimestamp": "1628550028455"
            },
            "_Attributes": {
                "SentTimestamp": "2021-08-09T16:00:28.455000-07:00",
                "ApproximateFirstReceiveTimestamp": "2021-08-09T16:00:28.455000-07:00"
            }
        }
    ]
}
```

```
fields @timestamp, @message
# | filter @message like '6a4dda81-d6c9-5be8-8608-c685eef62754'
| filter @requestId = 'a340e15a-fceb-5e0c-a190-b8d12d876111'
| filter @logStream like 'a6d1fcbf9dcc4ac1a967ae8874f837d8'
| filter @timestamp > 1628557100308 and @timestamp < 1628557400415
| sort @timestamp desc
| limit 200
```

```
Field           Value
@ingestionTime  1628557400417
@log            542754589326:/aws/lambda/azul-indexer-prod-contribute
@logStream      2021/08/09/[$LATEST]a6d1fcbf9dcc4ac1a967ae8874f837d8
@message        2021-08-10T01:03:20.414Z a340e15a-fceb-5e0c-a190-b8d12d876111 Task timed out after 300.10 seconds
@requestId      a340e15a-fceb-5e0c-a190-b8d12d876111
@timestamp      1628557400414
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Assignee to provide complete log of a failed lambda execution, potentially can the affected bundle, and come up with final diagnosis."

**Comment by theathorn** [comment]
Missing file is DCP-generated "1M-immune-human-blood-10XV2.loom" from "Census of Immune Cells".

**Comment by danielsotirhos** [comment]
Attempt # 10 to index subgraph `6a4dda81-d6c9-5be8-8608-c685eef62754` :

`Exceeded BigQuery rate limit during attempt 1/5` occurred 14 times
`Exceeded BigQuery rate limit during attempt 2/5` occurred 3 times
`Exceeded BigQuery rate limit during attempt 3/5` occurred 0 times.

```
fields @timestamp, @message
| filter @requestId = 'ff8f2266-9268-50e7-929d-7bed7c967fda'
| filter @logStream like '1332b275f30046a0bd5affa10ff5314d'
| filter @timestamp >= 1628564692652 and @timestamp <= 1628565592766
| sort @timestamp asc
| limit 500
```

```
START RequestId: ff8f2266-9268-50e7-929d-7bed7c967fda Version: $LATEST
```
```
[INFO] 2021-08-10T03:04:52.653Z ff8f2266-9268-50e7-929d-7bed7c967fda Worker handling message {'action': 'add', 'notification': {'source': {'id': 'a61115e1-ddf4-431a-8315-2cb4cb7cf87a', 'spec': 'tdr:tdr-prd1-4265bbdb:snapshot/hca_prod_20201120_dcp2___20210730_dcp8:'}, 'query': {}, 'subscription_id': 'cafebabe-feed-4bad-dead-beaf8badf00d', 'transaction_id': '89788d7a-9d4f-400c-9a9d-b6743337e041', 'match': {'bundle_uuid': '6a4dda81-d6c9-5be8-8608-c685eef62754', 'bundle_version': '2021-02-04T10:00:00.000000Z'}}, 'catalog': 'dcp8'}, attempt #10 (approx).
```
...
```
[WARNING] 2021-08-10T03:19:32.808Z ff8f2266-9268-50e7-929d-7bed7c967fda Exceeded BigQuery rate limit during attempt 1/5. Retrying in 10s.
Traceback (most recent call last):
File "/var/task/azul/terra.py", line 437, in run_sql
result = job.result()
File "/opt/python/google/cloud/bigquery/job.py", line 3196, in result
super(QueryJob, self).result(retry=retry, timeout=timeout)
File "/opt/python/google/cloud/bigquery/job.py", line 818, in result
return super(_AsyncJob, self).result(timeout=timeout)
File "/opt/python/google/api_core/future/polling.py", line 135, in result
raise self._exception
google.api_core.exceptions.Forbidden: 403 Exceeded rate limits: too many concurrent queries for this project_and_region. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas

(job ID: 3d601894-b95e-4e4d-b570-4ca494095ebf)

-----Query Job SQL Follows-----

| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
1:
2: SELECT content, version, BYTE_LENGTH(content) AS content_size, project_id, JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type, links_id
3: FROM `tdr-prd1-4265bbdb.hca_prod_20201120_dcp2___20210730_dcp8.links`
4: WHERE links_id = '7e78a8ab-3d39-5b36-8df6-cac9aeaf29fa'
5: AND version = TIMESTAMP('2021-02-04T10:00:00.000000Z')
6:
| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
```
```
[WARNING] 2021-08-10T03:19:43.129Z ff8f2266-9268-50e7-929d-7bed7c967fda Exceeded BigQuery rate limit during attempt 2/5. Retrying in 20s.
Traceback (most recent call last):
File "/var/task/azul/terra.py", line 437, in run_sql
result = job.result()
File "/opt/python/google/cloud/bigquery/job.py", line 3196, in result
super(QueryJob, self).result(retry=retry, timeout=timeout)
File "/opt/python/google/cloud/bigquery/job.py", line 818, in result
return super(_AsyncJob, self).result(timeout=timeout)
File "/opt/python/google/api_core/future/polling.py", line 135, in result
raise self._exception
google.api_core.exceptions.Forbidden: 403 Exceeded rate limits: too many concurrent queries for this project_and_region. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas

(job ID: 8d9acd0b-6375-4f0b-95e3-caf5cc68a908)

-----Query Job SQL Follows-----

| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
1:
2: SELECT content, version, BYTE_LENGTH(content) AS content_size, project_id, JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type, links_id
3: FROM `tdr-prd1-4265bbdb.hca_prod_20201120_dcp2___20210730_dcp8.links`
4: WHERE links_id = '7e78a8ab-3d39-5b36-8df6-cac9aeaf29fa'
5: AND version = TIMESTAMP('2021-02-04T10:00:00.000000Z')
6:
| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
```
```
END RequestId: ff8f2266-9268-50e7-929d-7bed7c967fda
```
```
REPORT RequestId: ff8f2266-9268-50e7-929d-7bed7c967fda Duration: 900100.62 ms Billed Duration: 900000 ms Memory Size: 4096 MB Max Memory Used: 140 MB Init Duration: 1706.07 ms
```
```
2021-08-10T03:19:52.766Z ff8f2266-9268-50e7-929d-7bed7c967fda Task timed out after 900.10 seconds
```

**Comment by danielsotirhos** [comment]
The canned bundle file `6a4dda81-d6c9-5be8-8608-c685eef62754.metadata.json` is 2,219,719 bytes, 44,044 lines and took approx 13 minutes to can on developer's machine.

```
(.venv) daniel@Crispin ~/repo/azul3 $ python scripts/can_bundle.py -b 6a4dda81-d6c9-5be8-8608-c685eef62754 -v 2021-02-04T10:00:00Z -s 'tdr:tdr-prd1-4265bbdb:snapshot/hca_prod_20201120_dcp2___20210730_dcp8:'
2021-08-10 13:03:43,269 DEBUG   MainThread: _request('GET', 'https://jade-terra.datarepo-prod.broadinstitute.org/api/repository/v1/snapshots', fields={'filter': 'hca_prod_20201120_dcp2___20210730_dcp8', 'limit': '2'}, headers=None, body=None)
...
2021-08-10 13:16:13,262 DEBUG   ThreadPoolExecutor-0_0: Retrieved 129 entities of type 'analysis_file'
2021-08-10 13:16:19,351 DEBUG   ThreadPoolExecutor-0_0: Retrieved 2 entities of type 'analysis_protocol'
2021-08-10 13:16:21,258 DEBUG   ThreadPoolExecutor-0_0: Retrieved 1 entities of type 'project'
2021-08-10 13:16:23,634 DEBUG   ThreadPoolExecutor-0_0: Retrieved 65 entities of type 'analysis_process'
2021-08-10 13:16:29,355 DEBUG   ThreadPoolExecutor-0_0: Retrieved 384 entities of type 'sequence_file'
2021-08-10 13:16:31,326 DEBUG   ThreadPoolExecutor-0_0: Retrieved 2 entities of type 'sequencing_protocol'
2021-08-10 13:16:34,049 DEBUG   ThreadPoolExecutor-0_0: Retrieved 192 entities of type 'process'
2021-08-10 13:16:35,146 DEBUG   ThreadPoolExecutor-0_0: Retrieved 1 entities of type 'library_preparation_protocol'
2021-08-10 13:16:37,162 DEBUG   ThreadPoolExecutor-0_0: Retrieved 8 entities of type 'donor_organism'
2021-08-10 13:16:38,338 DEBUG   ThreadPoolExecutor-0_0: Retrieved 1 entities of type 'dissociation_protocol'
2021-08-10 13:16:41,149 DEBUG   ThreadPoolExecutor-0_0: Retrieved 64 entities of type 'specimen_from_organism'
2021-08-10 13:16:43,779 DEBUG   ThreadPoolExecutor-0_0: Retrieved 64 entities of type 'cell_suspension'
2021-08-10 13:16:43,783 INFO    MainThread: It took 779.071s to download bundle 6a4dda81-d6c9-5be8-8608-c685eef62754.2021-02-04T10:00:00Z
2021-08-10 13:16:43,783 INFO    MainThread: Fetched bundle '6a4dda81-d6c9-5be8-8608-c685eef62754' version '2021-02-04T10:00:00Z' from catalog 'dcp8'.
2021-08-10 13:16:43,812 INFO    MainThread: Successfully wrote /Users/daniel/repo/azul3/test/indexer/data/6a4dda81-d6c9-5be8-8608-c685eef62754.manifest.json
2021-08-10 13:16:43,881 INFO    MainThread: Successfully wrote /Users/daniel/repo/azul3/test/indexer/data/6a4dda81-d6c9-5be8-8608-c685eef62754.metadata.json
```

**Comment by danielsotirhos** [comment]
It is perhaps worth noting that despite a BigQuery slot reservation of 300, a peak of only 204 was reached during the reindex.

![Screen Shot 2021-08-10 at 1 29 38 PM](https://user-images.githubusercontent.com/46407464/128930747-81d35f9c-3009-4b47-a4d6-af39bc19e037.png)

**Comment by danielsotirhos** [comment]
The notification was fed into the notification queue and successfully indexed.
Attempt # 1 timed out in `azul-indexer-prod-contribute` after 300 seconds.
Attempt # 2 succeeded in `azul-indexer-prod-contribute_retry` after 785 seconds.

**Comment by melainalegaspi** [comment]
@hannes-ucsc spike to come up with a solution.

**Comment by hannes-ucsc** [comment]
The underlying issue is that problematically large subgraphs are retried when the system is busy. Some may exhaust all their retries before the indexing load tapers off. One solution would be an exponential back-off between retries via exponentially increasing message visibility timeouts but that has the downside of disregarding the queue lengths. A system with a small amount of work left in the queues enters an idle state sooner than a system with a lot of work left. We want to perform the retry as soon as the system is idle, not after a fixed amount of time.

We can solve the issue by taking full control of the message retry mechanism. We'll change the maximum receive count of all notification queues to 1 so that failed messages are immediately put into the corresponding dead-letter queue. We'll insert a `redrive` queue in between the `retry` and `fail` queues. We'll add a Lambda function for servicing that queue. The `redrive` Lambda simply puts messages back into the first (non-retry) queue. This will typically occur 5min + 10s + 15min + 10s (the sum of the retry and non-retry queues' visibility timeouts) after the message was first processed by the `contribute` Lambda so it is very likely that all `reindex` notifications will already have been processed and no first attempts are queued behind the redriven message. IOW, the redriven message will likely be processed after all other messages have been attempted at least once. The redriven message carries an `attempts` counter that signifies the number of times a Lambda has previously attempted to process the message. When the non-retry Lambda receives a message with an attempts counter > 0, it skips it by returning it to the queue (setting the visibility to 0), causing SQS to immediately feed it to the `retry` queue. This is necessary because it is very likely that the non-retry Lambda fails to process the message due to the limited resources we allocate to that Lambda. If the retry Lambda then also fails to process the redriven message, the message will be placed into the `redrive` queue and the process repeats until the `redrive` Lambda receives a message with an `attempts` counter of 9. At that time it will return the message so that SQS finally feeds it to the `fail` queue.

A redriven message is a modified copy of the original message. To prevent SQS's message deduplication from suppressing the redriven message, the dedupliction ID (a UUIDv5) must include the `attempts` counter.

Since this algorithm places all redriven messages at the end of the queue, they will likely be processed at the same time, or at least a batch of AZUL_CONTRIBUTION_CONCURRENCY messages will be. We will need to account for that by tweaking the retry Lambda function's concurrency, from 64 to, say, 8.

We'll first implement this for notifications. Tallies don't currently seem to suffer from this problem.

**Comment by jessebrennan** [comment]
This occurred for four bundles during the last reindex (yesterday)
```
('6a4dda81-d6c9-5be8-8608-c685eef62754', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
('6a4dda81-d6c9-5be8-8608-c685eef62754', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('93787442-244e-5d8a-a35e-f71646c26eab', 'tdr:tdr-prd1-87360b54:snapshot/hca_prod_20201120_dcp2___20210812_dcp8:')
('93787442-244e-5d8a-a35e-f71646c26eab', 'tdr:broad-datarepo-terra-prod-hca2:snapshot/hca_prod_20201120_dcp2___20210707_dcp7:')
```

**Comment by jessebrennan** [comment]
> We'll first implement this for notifications. Tallies don't currently seem to suffer from this problem.

This is not true. In the last reindex, we say 44 permanently failed tallies that indexed fine when I fed them back into the aggregate_retry lambda.

**Comment by hannes-ucsc** [comment]
Makes sense. We'll still implements this for notifications first and, soon after, fix it for tallies: #3359.

**Comment by theathorn** [comment]
Triage to discuss progress.

**Comment by achave11** [comment]
Note: If IT notifications are send to the retry mechanism, then we don't need a specific test targeting the `redrive` mechanism. Some runs cause the first attempt of processing the notification to fail, they should then be run by the retry lambda and if that is the case, then we can be certain that the `redrive` mechanism will be covered by IT runs occasionally.

TODO: Request WIP review from @hannes-ucsc.

**Comment by hannes-ucsc** [comment]
> Since this algorithm places all redriven messages at the end of the queue, they will likely be processed at the same time, or at least a batch of AZUL_CONTRIBUTION_CONCURRENCY messages will be. We will need to account for that by tweaking the retry Lambda function's concurrency, from 64 to, say, 8.

Let's hold off on this aspect of the design. In the experiment for #3629 we didn't observe any negative effects of 64.

**Comment by achave11** [comment]
sequence: `normal` -> `retry` -> `redrive` -> `fail`


None => 0
z = (1 if x > 1 else 0) + y
x, y -> z
1, None -> 1
2, None -> 2
3, None -> 2

1, 2 -> 2
2, 2 -> 3
3, 2 -> 3

1, 3 -> 3
2, 3 -> 4
3, 3 -> 4

1, 4 -> 4
2, 4 -> 5
3, 4 -> 5

1, 5 -> 5
2, 5 -> 6
3, 5 -> 6

1, 6 -> 6
2, 6 -> 7
3, 6 -> 7

1, 7 -> 7
2, 7 -> 8
3, 7 -> 8

1, 8 -> 8
2, 8 -> 9
3, 8 -> 9

1, 9 -> 9
2, 9 -> 10
3, 9 -> 10

**Comment by hannes-ucsc** [comment]
Recent changes improved processing of problematic notifications and tallies, so that recent reindexes didn't have any failed notifications or tallies. It is therefore hard to come up with a metric to measure the successof THIS improvement. Parking for now.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "The recent improvements eliminated any permanently failed notifications or tallies. This won't be needed anymore."
