### ISSUE TITLE
Lambda layer zip file exceeded deployment package size limit

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3329]
# Issue

The PR for #3192 failed the `deploy` job in sandbox https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26245 due to a need for requirements update.

After running `make requirements_update` and committing the update to `requirements.dev.trans.txt` and `requirements.trans.txt`, the PR was retried in sandbox https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26258 and the `deploy` job failed with the error:
```
Error: Error creating lambda layer: InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes
```

# Investigation

The dependencies layer package used by job 26258
```
62.8 - s3://edu-ucsc-gi-singlecell-azul-config-dev.us-east-1/azul/lambda_layer/b8b689c0f7e6b43adbe545ec6b27708d0bed2c39.f01861499c0b2edd2441de0c261e3eb3d5d4b658.zip.
```

was compared against the package zip used by the prior successful `deploy` job for `develop` https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26115

```
25.9 - s3://edu-ucsc-gi-singlecell-azul-config-dev.us-east-1/azul/lambda_layer/b8b689c0f7e6b43adbe545ec6b27708d0bed2c39.e8101e9d969d309cd86a358543964eac19fe445b.zip
```

The larger zip was found to contain most all of the files found in the smaller zip, along with a 2nd copy of the `fastavro` and `gprc` files.

These 2nd copies duplicate the filenames of their match but not the file size, with the largest difference occurring for `python/grpc/_cython/cygrpc.cpython-38-x86_64-linux-gnu.so` (1 instance with a size of 9mb in both zips, and 1 extra instance with a size of 128mb in the larger zip).

![Screen Shot 2021-08-13 at 3 36 39 PM](https://user-images.githubusercontent.com/46407464/129425780-bedcf35b-7523-48a3-ada2-40914ad97e62.png)

# Quick fix

The file `b8b689c0f7e6b43adbe545ec6b27708d0bed2c39.f01861499c0b2edd2441de0c261e3eb3d5d4b658.zip` was removed from s3, and a new dependencies layer package file `b8b689c0f7e6b43adbe545ec6b27708d0bed2c39.f01861499c0b2edd2441de0c261e3eb3d5d4b658.zip` (25.9mb) was generated by running `make deploy` on my Mac laptop.

**Comment by jessebrennan** [comment]
My proposed fixes to address this issue:

- Add steps to layer generation that copies requirements files, filtering out any requirements listed in wheels directory.
- Add sanity check that lists everything in zip and compares against requirements.

**Comment by hannes-ucsc** [comment]
For demo, make trivial change to affect layer hash, generate layer for personal deployment on Ubuntu and show absence of duplicates. Show that locally generated layer is of similar size as those used on `dev` and `prod`. Must wait for ticket to land in `prod` before demoing.
