### ISSUE TITLE
Add dbGAP, BioStudies and EGA accessions to project response

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3331]
Add `project.dbgap_accessions`, `project.ega_accessions` and `project.biostudies_accessions` to set of returned accessions.

~Solve #3331, #3332 and #3333 in the same PR.~

 Modify `hits.projects ` in the service response from

```json
{
    …
    "arrayExpressAccessions": [
        null
    ],
    "geoSeriesAccessions": [
        "GSE93421"
    ],
    "insdcProjectAccessions": [
        "SRP096558"
    ],
    "insdcStudyAccessions": [
        "PRJNA360949"
    ]
}
```

to 

```json
{
    …
    "arrayExpressAccessions": [
        null
    ],
    "geoSeriesAccessions": [
        "GSE93421"
    ],
    "insdcProjectAccessions": [
        "SRP096558"
    ],
    "insdcStudyAccessions": [
        "PRJNA360949"
    ],
    "accessions": [
        {
            "type": "geo_series",
            "value": "GSE93421"
        },
        {
            "type": "insdc_project",
            "value": "SRP096558"
        },
        {
            "type": "insdc_study",
            "value": "PRJNA360949"
        },
        {
            "type": "dbgap",
            "value": "…"
        },
        {
            "type": "ega",
            "value": "…"
        },
        {
            "type": "biostudies",
            "value": "…"
        }
    ]
}
```

The `type` value is the name of the corresponding schema property minus the `_accessions` suffix.

Note that there is no `null` entry for ArrayExpress in `accessions`.

The new `dbgap`, `ega` and `biostudies` type accessions are only exposed in the new `accessions` property. Any other type is exposed in the `accessions` property AND a separate backwards-compatible property.

**Comment by theathorn** [comment]
@hannes-ucsc "Make accession property support more generic (look for properties ending in _accessions)".

**Comment by amarjandu** [comment]
@theathorn 
In the description it says:
> The type value is the name of the corresponding schema property minus the _accessions suffix.

But then within the example it looks like there is a conversion within the `type` field from camelCase to snake_case.

Which should it be?
```
{
    …
    "arrayExpressAccessions": [
        null
    ],
    "geoSeriesAccessions": [
        "GSE93421"
    ],
    "insdcProjectAccessions": [
        "SRP096558"
    ],
    "insdcStudyAccessions": [
        "PRJNA360949"
    ],
    "accessions": [
        {
            "type": "geo_series",
            "value": "GSE93421"
        },
        {
            "type": "insdc_project",
            "value": "SRP096558"
        },
        {
            "type": "insdc_study",
            "value": "PRJNA360949"
        },
        {
            "type": "dbgap",
            "value": "…"
        },
        {
            "type": "ega",
            "value": "…"
        },
        {
            "type": "biostudies",
            "value": "…"
        }
    ]
}
```

**Comment by hannes-ucsc** [comment]
The *schema* property is snake case. The `type` value is snake case. Where do you see a change from snake to camel case?

**Comment by amarjandu** [comment]
Sorry, I was confusing the service response and the fields in the metadata. It's clear now.

**Comment by amarjandu** [comment]
Closing #3332 and #3333 as dups of this issue due to PR linking problem in hca-metadata-api#58

**Comment by hannes-ucsc** [comment]
For demo, show that the new `accessions` property shows up in the `/index/projects` response but not in the other endpoints. Show that the three newly supported namespaces from the ticket description are represented. Show that the previously supported namespaces are shown represented as distinct properties and in the new `accessions` property.

**Comment by amarjandu** [comment]
EGA - https://service.azul.data.humancellatlas.org/index/projects/c715cd2f-dc7c-44a6-9cd5-b6a6d9f075ae?catalog=dcp9
BioStudies - https://service.azul.data.humancellatlas.org/index/projects/ad98d3cd-26fb-4ee3-99c9-8a2ab085e737?catalog=dcp9
dbgap - ?
