### ISSUE TITLE
Add EGA accessions to project response

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3332]
Add `project.ega_accessions` to set of returned accessions.

See https://github.com/DataBiosphere/azul/issues/3331 for details.

**Comment by melainalegaspi** [comment]
Freebie of #3331

**Comment by melainalegaspi** [comment]
Freebie of #3331

**Comment by amarjandu** [comment]
Closing as dup of #3331

**Comment by hannes-ucsc** [comment]
@amarjandu, just closing isn't sufficient to enable you to connect DataBiosphere/hca-metadata-api#58 with PR #3369. You'd also have to disconnect this issue from that PR.
