### ISSUE TITLE
Possible Concurrent Write Ops Issue

### ISSUE THREAD

**Issue by shiroyuki** [DataBiosphere/azul#334]
(Related to #45)

## Abstract

With the first-write-win conflict resolution strategy, modifying the whole document, especially on an array field, could be overwritten by another concurrent call.

With the implementation for Azul/45 and the current data structure, we will run into this problem eventually. The solution analysis will be written later in this description.

## Scenario

Suppose we have documents in one of the indices with `n` bundles, namely `bundle_1`, `bundle_2`, ... and `bundle_n`.

## Base case: one connection at a time

Suppose that there exists **one request** to delete `bundle_1`.

As the code is to set `content` to `{deleted: true}`, the code will first load each document with `bundle_1`. At this point, the code will have the document in memory (i.e., *pre-update* state).

```javascript
{
  // ...
  bundles: [bundle_1_ok, bundle_2_ok, ..., bundle_n_ok]
}
```

Then, the code does the bundle list merge in memory and push the updated/merged list back (i.e., *post-update* state) to the document storage.

```javascript
{
  // ...
  bundles: [bundle_1_deleted, bundle_2_ok, ..., bundle_n_ok]
}
```

This case, what is stored in the document storage is what we want.

## Concurrent case: 3 concurrent requests

Now, suppose that there exists **3 simultaneous requests** where:
* `request_1` deletes `bundle_1`,
* `request_2` deletes `bundle_3`,
* `request_3` deletes `bundle_5`.

In this case, all requests may have the same *pre-update* state before merging. This means it is possible that one or two bundles are not *deleted*.

Suppose that the process that handles `request_2` has the last write operation. With ElasticSearch's Optimistic Concurrency Control, the final state of the effected document could end up like:

```javascript
{
  // ...
  bundles: [
    bundle_1_ok, // <-- still survived
    bundle_2_ok,
    bundle_3_deleted, // <-- DELETED for good
    bundle_4_ok,
    bundle_5_ok,  // <-- also survived
    // ...
    bundle_n_ok
  ]
}
```

## How could we mitigate the issue?

From the discussion Milan and I had earlier, we come up with two approaches (for now).

### Reduce concurrency factor

Reduce the number of concurrent execution on the lambda job.

* **Pros:** Mitigate the writing conflict or contention.
* **Cons:** Slow down the response time under high request load.

### Restructure the data structure

Restructure the data models to allow atomic CRUD operations.

* **Pros:** Faster update with minimal risk on data discrepancy.
* **Cons:** Much more work to do... High Code Impact!

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-218)
┆Project Name: azul
┆Issue Number: AZUL-218

**Comment by shiroyuki** [comment]
One more alternative solution is to implement a SQS FIFO queue for deleting bundles from indices, similar to @hannes-ucsc's proposal to fix #182.

**Comment by hannes-ucsc** [comment]
If the reproduction is merely "there are more than one concurrent delete", we have that covered by using ES versioning which is essentially optimistic locking. Yes, only one of the writers wins, but the losers read the document again and therefore witness the changes made by the winner. Then one of the losers wins and the last remaining writer reads the document a second time. It witnesses the changes made by both of the other writers.

1) writer 1 reads `doc.v12`
2) writer 2 reads `doc.v12`
3) writer 3 reads `doc.v12`
4) all writers modify the document and attempt to write it back as `doc.v13`
5) writer 2 succeeds in writing `doc.v13`, writers 1 and 3 get a 409
6) writer 1 reads `doc.v13`
7) writer 3 reads `doc.v13`
8) both writers modify the document and attempt to write it back as `doc.v14`
9) writer 3 succeeds in writing `doc.v14`, writer 1 gets a 409
10) writer 1 reads `doc.v14`, modifies it and writes it back as `doc.v15`

doc.v15 contains the changes of the three writers and nothing is lost.

Independently of that, if there actually were an issue with concurrency, merely reducing concurrency is not an effective means to preventing that issue, it would only reduce its probability.

I'll close this for now. In case I misunderstood the alleged reproduction of this issue, feel free to reopen with a description of the event sequence like the one I laid out above that reproduces the issue.

**Comment by shiroyuki** [comment]
@hannes-ucsc You are right. When the code reloads the document on the retry, the issue will become unlikely.

**Comment by hannes-ucsc** [comment]
When you say "unlikely", do you have a concrete scenario in mind that would reproduce this issue?
