### ISSUE TITLE
Consolidate requirements parsing between `scripts/manage_requirements.py` and `src/azul/lambda_layer.py`

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3342]
Both pieces of code parse requirements, but do it in their own way. `scripts/manage_requirements.py` uses the `requirements` library which is probably preferred to the home-spun technique used in `src/azul/lambda_layer.py`

**Comment by melainalegaspi** [comment]
Putting in triage because it needs a description.

**Comment by melainalegaspi** [comment]
@jessebrennan to provide description.

**Comment by hannes-ucsc** [comment]
Comes for free with #4364.

**Comment by hannes-ucsc** [comment]
I can't connect this to PR #4637 but the commit https://github.com/DataBiosphere/azul/commit/13842c28d570f4240dc014c35602869822dec55e makes this obsolete.
