### ISSUE TITLE
BigQuery rate limit exceeded during `prod` reindex

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3348]
```
[WARNING] 2021-08-19T21:32:03.641Z 0b1b68be-616c-57c1-bd10-3126ae98bb2d Exceeded BigQuery rate limit during attempt 1/5. Retrying in 10s.
Traceback (most recent call last):
File "/var/task/azul/terra.py", line 445, in run_sql
result = job.result()
File "/opt/python/google/cloud/bigquery/job.py", line 3196, in result
super(QueryJob, self).result(retry=retry, timeout=timeout)
File "/opt/python/google/cloud/bigquery/job.py", line 818, in result
return super(_AsyncJob, self).result(timeout=timeout)
File "/opt/python/google/api_core/future/polling.py", line 135, in result
raise self._exception
google.api_core.exceptions.Forbidden: 403 Exceeded rate limits: too many concurrent queries for this project_and_region. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas

(job ID: 742747a1-23f4-4053-8d2b-6aa577ffc041)

-----Query Job SQL Follows-----

| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
1:
2: SELECT JSON_EXTRACT_SCALAR(content, "$.schema_type") AS schema_type, cell_suspension_id, BYTE_LENGTH(content) AS content_size, version, content
3: FROM `broad-datarepo-terra-prod-hca2.hca_prod_20201120_dcp2___20210707_dcp7.cell_suspension`
4: WHERE cell_suspension_id = "26e2d8c7-3f68-4467-884d-098e4f283f9b"
5:
| . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |
```
---

#### This is happening very frequently during the reindex.

![rate-limit](https://user-images.githubusercontent.com/10734740/130147685-cf7fd629-1ff4-4bbe-84fd-975bd9cc3908.png)

#### Though most occurrences are warnings, we are seeing some errors:

![bq-errors](https://user-images.githubusercontent.com/10734740/130150514-d6b4b284-9653-4720-8a93-9621475e9dbc.png)

---

#### Google's status page indicates some issues with BigQuery which could explain why we're seeing the rate limit now when we never had before

>US Multi-region: DEADLINE_EXCEEDED Error while inserting a Google BigQuery job
>
>Only script jobs are affected. The workaround is to retry inserting failed jobs
>
>We believe the issue with Google BigQuery is partially resolved. Current data suggests that there is no active DEADLINE_EXCEEDED errors. If you are still impacted, please open a support case so we can work with you for resolution.
>
>Full resolution is expected to complete by Friday, 2021-08-20 12:15 US/Pacific and we will provide an update by then.

![bq-out](https://user-images.githubusercontent.com/10734740/130148377-96cf7740-c807-41a8-8786-172d3992fa28.png)

**Comment by jessebrennan** [comment]
[Google documentation recommends an exponential backoff](https://cloud.google.com/bigquery/docs/troubleshoot-quotas#overview).

> rateLimitExceeded. This value indicates a short-term limit. Usually you can resolve these limits by retrying the operation after a few seconds. Use exponential backoff between retry attempts. That is, exponentially increase the delay between each retry

**Comment by noah-aviel-dove** [comment]
[We already use exponential backoff for BigQuery](https://github.com/DataBiosphere/azul/blob/67875b713688db47adea257c817128cc0846be78/src/azul/terra.py#L437)

**Comment by jessebrennan** [comment]
This occurred during the last reindex as well. This indicates that this issue is most likely a duplicate of #3315.


![bq-last-reindex](https://user-images.githubusercontent.com/10734740/130153587-0daff8ad-d068-46d5-b754-96523276e953.png)

**Comment by danielsotirhos** [comment]
This can be found from the Google Cloud Platform menu -> BigQuery -> Monitoring.

![Screen Shot 2021-08-20 at 8 47 20 AM](https://user-images.githubusercontent.com/46407464/130259498-9ad40ebc-ed66-4164-beed-dddc26aa82bd.png)

**Comment by melainalegaspi** [comment]
@jessebrennan to update the CloudWatch screenshot.

**Comment by melainalegaspi** [comment]
@noah-aviel-dove spike to determine what the limit actually is.

**Comment by noah-aviel-dove** [comment]
The limit is 100 simultaneous interactive queries (https://cloud.google.com/bigquery/quotas#query_jobs). There is no limit on [batch queries](https://cloud.google.com/bigquery/docs/running-queries#batch).

**Comment by hannes-ucsc** [comment]
Sounds like we should be switching to batch queries. The PR for this should be labelled `reindex` so that we get to expose any negative  effects of batch queries on indexing performance or correctness in `sandbox` or `dev.

**Comment by noah-aviel-dove** [comment]
Changing to no-demo because the consequences of this change were already observed, analyzed, and reverted (https://github.com/DataBiosphere/azul/issues/3589)
