### ISSUE TITLE
`EventualConsistencyException`s during `prod` reindex

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3354]
### ~250 occurrences look like this:
```
[ERROR] EventualConsistencyException: ('Could not find all expected contributions.', {CataloguedEntityReference(entity_type='files', entity_id='d1697cd7-db19-4d3f-be05-939a3cc1a7f8', catalog='dcp8'): 1, CataloguedEntityReference(entity_type='cell_suspensions', entity_id='ff27c8a2-cc90-4c50-9662-035c55a811c0', catalog='dcp8'): 1, CataloguedEntityReference(entity_type='bundles', entity_id='c16c064a-b017-45bd-9680-c7e33a5665b0', catalog='dcp8'): 1, CataloguedEntityReference(entity_type='files', entity_id='48d34b7e-6688-40e2-b1a6-b4bf55abef31', catalog='dcp1'): 1, CataloguedEntityReference(entity_type='files', entity_id='66673b48-9ab5-4ee5-824a-296a55073161', catalog='dcp1'): 1, CataloguedEntityReference(entity_type='files', entity_id='c3d636e6-bad7-410d-a3c4-c666def96c63', catalog='dcp1'): 1}, Counter({CataloguedEntityReference(entity_type='cell_suspensions', entity_id='ff27c8a2-cc90-4c50-9662-035c55a811c0', catalog='dcp8'): 2, CataloguedEntityReference(entity_type='files', entity_id='48d34b7e-6688-40e2-b1a6-b4bf55abef31', catalog='dcp1'): 1, CataloguedEntityReference(entity_type='files', entity_id='66673b48-9ab5-4ee5-824a-296a55073161', catalog='dcp1'): 1, CataloguedEntityReference(entity_type='bundles', entity_id='c16c064a-b017-45bd-9680-c7e33a5665b0', catalog='dcp8'): 1, CataloguedEntityReference(entity_type='files', entity_id='d1697cd7-db19-4d3f-be05-939a3cc1a7f8', catalog='dcp8'): 1}))
Traceback (most recent call last):
  File "/var/task/app.py", line 119, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 1459, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 134, in aggregate
    app.index_controller.aggregate(event)
  File "/var/task/azul/indexer/index_controller.py", line 229, in aggregate
    self.index_service.aggregate(tallies)
  File "/var/task/azul/indexer/index_service.py", line 249, in aggregate
    raise EventualConsistencyException(message, *args)
```
### The rest look like this

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">@timestamp</th>
<th title="Field #2">@message</th>
</tr></thead>
<tbody><tr>
<td>2021-08-20 11:16:44.235</td>
<td>[ERROR] EventualConsistencyException: Search returned 3 hits but reports total to be 5<br/>Traceback (most recent call last):<br/>  File &quot;/var/task/app.py&quot;, line 119, in new_handler<br/>    return old_handler(self, event, context)<br/>  File &quot;/var/task/chalice/app.py&quot;, line 1459, in __call__<br/>    return self.func(event_obj)<br/>  File &quot;/var/task/app.py&quot;, line 134, in aggregate<br/>    app.index_controller.aggregate(event)<br/>  File &quot;/var/task/azul/indexer/index_controller.py&quot;, line 229, in aggregate<br/>    self.index_service.aggregate(tallies)<br/>  File &quot;/var/task/azul/indexer/index_service.py&quot;, line 243, in aggregate<br/>    contributions = self._read_contributions(total_tallies)<br/>  File &quot;/var/task/azul/indexer/index_service.py&quot;, line 358, in _read_contributions<br/>    raise EventualConsistencyException(message)</td>
</tr>
<tr>
<td>2021-08-20 10:13:43.126</td>
<td>[ERROR] EventualConsistencyException: Search returned 389 hits but reports total to be 524<br/>Traceback (most recent call last):<br/>  File &quot;/var/task/app.py&quot;, line 119, in new_handler<br/>    return old_handler(self, event, context)<br/>  File &quot;/var/task/chalice/app.py&quot;, line 1459, in __call__<br/>    return self.func(event_obj)<br/>  File &quot;/var/task/app.py&quot;, line 134, in aggregate<br/>    app.index_controller.aggregate(event)<br/>  File &quot;/var/task/azul/indexer/index_controller.py&quot;, line 229, in aggregate<br/>    self.index_service.aggregate(tallies)<br/>  File &quot;/var/task/azul/indexer/index_service.py&quot;, line 243, in aggregate<br/>    contributions = self._read_contributions(total_tallies)<br/>  File &quot;/var/task/azul/indexer/index_service.py&quot;, line 358, in _read_contributions<br/>    raise EventualConsistencyException(message)</td>
</tr>
<tr>
<td>2021-08-20 03:10:52.478</td>
<td>[ERROR] EventualConsistencyException: Search returned 719 hits but reports total to be 724<br/>Traceback (most recent call last):<br/>  File &quot;/var/task/app.py&quot;, line 119, in new_handler<br/>    return old_handler(self, event, context)<br/>  File &quot;/var/task/chalice/app.py&quot;, line 1459, in __call__<br/>    return self.func(event_obj)<br/>  File &quot;/var/task/app.py&quot;, line 134, in aggregate<br/>    app.index_controller.aggregate(event)<br/>  File &quot;/var/task/azul/indexer/index_controller.py&quot;, line 229, in aggregate<br/>    self.index_service.aggregate(tallies)<br/>  File &quot;/var/task/azul/indexer/index_service.py&quot;, line 243, in aggregate<br/>    contributions = self._read_contributions(total_tallies)<br/>  File &quot;/var/task/azul/indexer/index_service.py&quot;, line 358, in _read_contributions<br/>    raise EventualConsistencyException(message)</td>
</tr>
</tbody></table>

**Comment by hannes-ucsc** [comment]
These are expected. Only an increase in frequency would be concerning. Spike to compare frequency across multiple reindexes, taking number of notifications into account. We have reindexes that cover 1, 2 or 3 snapshots in prod.

**Comment by jessebrennan** [comment]
I searched for occurrences between 11 July and today.

reindex dates | # logs matched | catalogs reindexed | reindex notifications
--- | --- | --- | ---
27 May | 38 | ? | 768
3 Jun |  0 | ? | 256
12 Jun | 68 | ? | 768
2 Jul | 0 | ? | 256
9 Jul | 0 | ? | 256
13 Jul | 0 | ? | 256
22 Jun | 0 | ? | 768
8 Aug | 0 | ? | 256
19 Aug | 518 | 7, 8, 1, lungmap | 1024
23 Aug | 114 | 8 | 256
27 Aug | 1198 | 7, 8, 1, lungmap | 1024
3 Sep | 2450 | 9 | 256

**Comment by melainalegaspi** [comment]
@hannes-ucsc to evaluate findings.

**Comment by hannes-ucsc** [comment]
The trend has reversed. In particular the last two reindexes covered three HCA catalogs (the lungmap catalog is negligibly small) but had very low counts of this exception. The frequency with which this occurs depends on the load on ES and we have issues dealing with that, namely #3630, #3629, #3315 and #3359.

![image](https://user-images.githubusercontent.com/5143256/142474547-809d79ef-5de4-411f-8c0a-bf5e48d7dc96.png)

**Comment by hannes-ucsc** [comment]
To be closed in triage.
