### ISSUE TITLE
Prompt retry of tallies leads to persistent failures under load

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3359]
Re-queue failed tallies at the beginning of the tallies queue, just like for [notifications](https://github.com/DataBiosphere/azul/issues/3315#issuecomment-902928215).

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "After switching to paged retrieval of contributions instead of scan() , we do not have any persistent failures anymore."
