### ISSUE TITLE
Standardize process for back-porting `prod` to `develop` in operator manual

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3378]
This came up in the context of https://github.com/DataBiosphere/azul/pull/3365 so I decided to open this issue.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Titles of PRs and merge commits of hotfixes should be `Hotfix: `. PR title of backport should be `Backport: ` . Ask lead about what to do about backporting multiple hotfixes at once."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "For demo, show changes to operator manual."
