### ISSUE TITLE
Accelerate download of bulk data

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3381]
From Dr. Carlos Talavera-López <carlos.lopez@helmholtz-muenchen.de>:

I also did a couple of tests on what’s the best way to download this huge files from the DCP. In previous occasions I have recommended the DCP to include [axel](https://github.com/axel-download-accelerator/axel) alongside the curl option to download the link. For instance, downloading the reads for the heart data took me approx. 21 hrs, compared with approx. 6 hrs using 24 CPUs.

**Comment by hannes-ucsc** [comment]
It's trivial for any user to split a curl manifest into partitions and download those in parallel. There is no need to add support for non-standard tools at this time. I propose to close this.
