### ISSUE TITLE
Excessive number of failed tallies

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3386]
There were 100 initially during the last reindex, then 10 after refeeding multiple times. They succeeded only by aggregating individually.

**Comment by jessebrennan** [comment]
Possible solution:

One tally for a large aggregate can poison a whole batch of 10 tallies because of the batch size. Also if two large aggregates will compete for the compete for the resources of one lambda execution (running time and memory). 

To work around this, we can:

- Compute referrals and deferrals
- if only attempt 1s and 2s (receive count is approximate, some retries come in with receive count 1):
  * process all referrals
- else
  - pick one referral
  - return the remaining referrals to the queue
  - process the referral
- queue deferrals

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "We do not observe this anymore."
