### ISSUE TITLE
snykCon 2021

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3390]
Examine the [agenda](https://em.snyk.io/Njc3LVRIUC00MTUAAAF_O_4l-NRbPFb4d6SJLH08D7GREe7QupLntkEqABZNBxZBAMt2l6ucL0Yx6H3SO8x-5z5c32I=) and decide who (if anyone) should attend which sessions (Oct 5-7).

**Comment by melainalegaspi** [comment]
@theathorn : "No one to attend."
