### ISSUE TITLE
`requests` module raises RequestsDependencyWarning

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3402]
The `requests` module is raising a `RequestsDependencyWarning` during use of the `can_bundle.py` script
```
RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
```

In context:
```
(.venv) daniel@Crispin ~/repo/azul2 $ python scripts/can_bundle.py -b f9076299-5019-8ccc-ed6d-b1630d2743f2 -v "2021-05-24T16:47:59.709248Z" -s "tdr:broad-jade-dev-data:snapshot/hca_dev_20201203___20210524_lattice:"
/Users/daniel/repo/azul2/.venv/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2021-09-02 13:38:19,616 DEBUG   MainThread: _request('GET', 'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots', fields={'filter': 'hca_dev_20201203___20210524_lattice', 'limit': '2'}, headers=None, body=None)
2021-09-02 13:38:19,627 INFO    MainThread: Found credentials in environment variables.
...
```

... after which the script appears to complete without further warnings or error.

**Comment by melainalegaspi** [comment]
Spike to confirm whether this occurs in cloud watch logs.

**Comment by melainalegaspi** [comment]
@jessebrennan : "This probably started from #3347."

@noah-aviel-dove : "Can confirm this occurs in GitLab."

**Comment by noah-aviel-dove** [comment]
> Spike to confirm whether this occurs in cloud watch logs.

Yes it does.

```
Field | Value
-- | --
@ingestionTime | 1631064551077
@log | 122796619775:/aws/lambda/azul-indexer-dev-contribute
@logStream | 2021/09/08/[$LATEST]3de840e4efeb4634bd321c5b1fa0592b
@message | /opt/python/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
@timestamp | 1631064544242
```

**Comment by melainalegaspi** [comment]
Spike to come up with the implications of this warning. Why is `requests` warning is about the dependency?

**Comment by jessebrennan** [comment]
Requests likes to be strict with their dependencies. See https://github.com/psf/requests/pull/4144 for some internal discussion about this.

Our version of requests 2.22.0 doesn't support the latest version of urllib3. Versions of requests >=2.25.0 support urlib3. We could solve the warning by upgrading requests.

Ignoring the warning could also solve this. It looks like no fundamental changes were necessary for requests to support urllib3 versions 1.26+ (see: https://github.com/psf/requests/pull/5651/files)

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Resolution is to update requests."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce. Also show that the warning does occur in CW logs for `dev` before the fix lands, and stop occurring after.
