### ISSUE TITLE
PFB manifests include properties absent in aggregates

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3408]
For example, `publications` within a `project` PFB entity are always set to an empty list. This is because `_project_types` declares that property but the corresponding aggregator suppresses it. It would be better if `_project_types` declared whether a property is absent from aggregates. That way, the PFB generator wouldn't need to emit a dummy value for these types of properties.

**Comment by bvizzier-ucsc** [comment]
@hannes-ucsc: "Made obsolete by https://github.com/DataBiosphere/azul/issues/2693."
