### ISSUE TITLE
Destroy `jyo` deployment, create `dnastack` deployment

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#341]
@alex-hancock has made it so that all personal deployments share the ES domain with `dev`, to save money, as requested by CZI.

Please destroy the `jyo.local` deployment (`cd terraform && make destroy`) and create a `dnastack.local` deployment by copying `deployments/.example.local`.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-223)
┆Project Name: azul
┆Issue Number: AZUL-223

**Comment by Ben-Wu** [comment]
Jyo deployment destroyed and dnastack is up and running
