### ISSUE TITLE
Approximation errors for terms aggregation are unchecked

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3413]
From a [review comment](https://github.com/DataBiosphere/azul/pull/3352/files#r704884886) from related issue https://github.com/DataBiosphere/azul/issues/3318: 

> The terms aggregation is ... approximate. We should ... apply [a] sanity check to curb or eliminate approximation errors for the terms aggregation.

**Comment by hannes-ucsc** [comment]
This has been addressed:

https://github.com/DataBiosphere/azul/blob/95e4d86e4e472c98138f5ce29e34dd4c81b0289d/src/azul/plugins/metadata/hca/service/aggregation.py#L151
