### ISSUE TITLE
Relax conditions defining a CGM

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3420]
Instead of using the word "matrix: in `file.file_core.content_description` use any `analysis_file` with a `file_core.file_source` other than "DCP/2 analysis" or "DCP/1 matrix service".

**Comment by hannes-ucsc** [comment]
This should be implemented in an API-backwards-compatible way. Renaming response and index properties should be done in a follow-on PR. Before implementation commences, a spike should identify an example subgraph, as well as can and study it, either in TDR or in a staging area. I am particularly worried that the stratification of these "matrix-related" files may complicate things.

**Comment by danielsotirhos** [comment]
If conditions defining a CGM were relaxed to remove the requirement of "matrix" occurring in the file's `content_description`, 166 analysis files in 167 bundles for 8 unique projects from the `dcp9` catalog would be newly considered to be CGM.

166 analysis files
```
select * from `tdr-fp-546ade29.hca_prod_20201120_dcp2___20210910_dcp9.analysis_file` 
where content not like '%matrix%' and content like '%file_source%'
```

167 bundles from 8 distinct projects
```
# select * 
select distinct links.project_id
from `tdr-fp-546ade29.hca_prod_20201120_dcp2___20210910_dcp9.links` as links
inner join `tdr-fp-546ade29.hca_prod_20201120_dcp2___20210910_dcp9.analysis_file` as files
      on ( links.content like concat('%',files.analysis_file_id,'%') )
where files.content not like '%matrix%' and files.content like '%file_source%'
```

**Comment by danielsotirhos** [comment]
Attached CSV contains `file_core` details for the 166 analysis files.
Rows are sorted first by `project_id` and secondarily by `file_name`.
[dcp9_non_matrix_cgm.csv](https://github.com/DataBiosphere/azul/files/7262910/dcp9_non_matrix_cgm.csv)

**Comment by theathorn** [comment]
William Sullivan reviewed the spreadsheet and agreed all 166 files are CGM-related.

**Comment by hannes-ucsc** [comment]
For demo, in the DB for at least one project, show a contributor-generated analysis file whose content_description does not contain "matrix".
