### ISSUE TITLE
Index hca_prod_20201120_dcp2___20210910_dcp9 into dcp9 on prod

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3421]
Snapshot name: `hca_prod_20201120_dcp2___20210910_dcp9`
Google project ID: `tdr-fp-546ade29`

Assignee to create PR checklist item for operator to inform Broad on Slack in [this thread](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1631293597039600) once snapshot has been indexed.

**Comment by jessebrennan** [comment]
@hannes-ucsc notice that I changed the title. I assume the previous title was a mistake (s/dcp8/dcp9).

**Comment by hannes-ucsc** [comment]
It was. Thank you.
