### ISSUE TITLE
Portal registration IT overwrites concurrent updates made via API

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3427]

**Comment by achave11** [comment]
@hannes-ucsc: "Solution is to mock the object_key used for storing the DB during the IT. Also, ensure that only versions created by IT have the `expires` tag set to `true`."

**Comment by hannes-ucsc** [comment]
Portal registration API is [deprecated](https://github.com/DataBiosphere/azul/issues/6782).
