### ISSUE TITLE
register_sam.py does not inspect sources

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3443]
The format of the plugins within config.Catalog was changed, it causes this guard to not return any values within the comprehension.
https://github.com/DataBiosphere/azul/blob/2d2016c0fcf2b3408197e25505c246d9c68aa6ff/scripts/register_sam.py#L32

Regression from 8e9d8206

Before regression is introduced:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26410#L7443

Regression is introduced:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26422#L7798

**Comment by amarjandu** [comment]
```
Index: scripts/register_sam.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/register_sam.py b/scripts/register_sam.py
--- a/scripts/register_sam.py	(revision 109efb4afefbcb215198148a75e39d0c5e7d0842)
+++ b/scripts/register_sam.py	(date 1631912616062)
@@ -29,8 +29,9 @@
     tdr_catalogs = (
         catalog.name
         for catalog in config.catalogs.values()
-        if catalog.plugins['repository'] == 'tdr'
+        if catalog.plugins['repository'].name == 'tdr'
     )
+    assert tdr_catalogs
     for source in set(chain(*map(config.tdr_sources, tdr_catalogs))):
         source = TDRSourceSpec.parse(source)
         api_project = tdr.lookup_source_project(source)
```

**Comment by amarjandu** [comment]
Before regression is introduced:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26410#L7443

Regression is introduced:
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/26422#L7798

**Comment by hannes-ucsc** [comment]
For demo, show that output of `make sam` on GL for `develop` reverted to what was observed before the regression was introduced.
