### ISSUE TITLE
Slot management assumes all lower deployments use the same BQ location

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3454]
...which won't necessarily be true after https://github.com/databiosphere/azul/issues/3448 is addressed. There are two problems with this:

1. If slots are purchased in region 1 on deployment 1, and deployment 2 needs slots in region 2 for a reindex, no new slots will be purchased (because the slots in region 1 are assumed to be sufficient), and deployment 2 will not allocate the slots it needs for the reindex.
2. If `dev` is configured to purchase slots in region 1, and another deployment purchases slots in region 2, `dev` will not correctly determine the state of the slot commitment and may either fail to delete the slots, or, if it detects some resources but not all, attempt to delete some resources prematurely.

**Comment by melainalegaspi** [comment]
@noah-aviel-dove to update description with the potential negative outcomes (2 scenarios so far).

**Comment by noah-aviel-dove** [comment]
Moving to triage since this seems to have some overlap with https://github.com/DataBiosphere/azul/issues/3673

**Comment by noah-aviel-dove** [comment]
Description is inaccurate. https://github.com/DataBiosphere/azul/issues/3673 gives us a concrete problem to address that I think encompasses the intent behind this ticket.
