### ISSUE TITLE
Document emergency push to GitLab in operator manual

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3490]
When the operator needs to build a commit on GitLab that has not been pushed to GitHub, they should edit the `.gitlab-ci.yml` to prefix the `python scripts/github_status_check.py` invocations with `echo`. Explain an example scenario to motivate this procedure (Hannes isn't there to approve and operators cannot push directly to develop on GitHub).

**Comment by hannes-ucsc** [comment]
This seems to work around a situation that should not occur. There should always be a (deputy) system administrator, even when the main system admin is on vacation.
