### ISSUE TITLE
API Gateway log is missing important fields

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3497]
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference%3Fcmpid=docs_apigateway_console

**Comment by theathorn** [comment]
Spike to choose fields.

**Comment by hannes-ucsc** [comment]
```diff
Index: scripts/log_api_gateway.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/log_api_gateway.py b/scripts/log_api_gateway.py
--- a/scripts/log_api_gateway.py	(revision a0cebde04bb5715173f6261b92058fad180ed829)
+++ b/scripts/log_api_gateway.py	(date 1636485204500)
@@ -11,15 +11,27 @@
 # Do NOT run manually.
 
 JSON_LOG_FORMAT = {
+    "protocol": "$context.protocol",
+    "httpMethod": "$context.httpMethod",
+    "path": "$context.path",
     "requestId": "$context.requestId",
-    "ip": "$context.identity.sourceIp",
-    "caller": "$context.identity.caller",
-    "user": "$context.identity.user",
+    "awsEndpointRequestId": "$context.awsEndpointRequestId",
+    "awsEndpointRequestId2": "$context.awsEndpointRequestId2",
     "requestTime": "$context.requestTime",
-    "httpMethod": "$context.httpMethod",
-    "resourcePath": "$context.resourcePath",
     "status": "$context.status",
-    "protocol": "$context.protocol",
+    "dataProcessed": "$context.dataProcessed",
+    "error_message": "$context.error.message",
+    "error_messageString": "$context.error.messageString",
+    "error_responseType": "$context.error.responseType",
+    "integration_error": "$context.integration.error",
+    "integration_integrationStatus": "$context.integration.integrationStatus",
+    "integration_latency": "$context.integration.latency",
+    "integration_requestId": "$context.integration.requestId",
+    "integration_status": "$context.integration.status",
+    "integrationErrorMessage": "$context.integrationErrorMessage",
+    "integrationLatency": "$context.integrationLatency",
+    "integrationStatus": "$context.integrationStatus",
+    "responseLatency": "$context.responseLatency",
     "responseLength": "$context.responseLength"
 }
 
```

**Comment by hannes-ucsc** [comment]
Assignee to apply the above diff and then remove any fields that are evidently duplicates by looking at the resulting logs in a personal deployment before PR review, I don't trust the AWS documentation on the equivalencies between fields.

I hope that one of the request IDs logged here would allow us to correlate log entries from this log to those in the Lambda logs. Assignee to confirm and post findings here.

**Comment by achave11** [comment]
>I hope that one of the request IDs logged here would allow us to correlate log entries from this log to those in the Lambda logs. Assignee to confirm and post findings here.

Indeed, we can associate the API Gateway logs with the lambda via `awsEndpointRequestId` or `integration_requestId` which are apparent duplicates at the moment. (which one should go?)
![Screen Shot 2021-12-15 at 10 14 51 AM](https://user-images.githubusercontent.com/19215510/146248190-621b0f58-8d1d-4d62-b274-189f4a9ee85a.png)
![Screen Shot 2021-12-15 at 10 50 05 AM](https://user-images.githubusercontent.com/19215510/146248242-f7c7bab2-aba4-434e-b591-50c1af06c68d.png)

I recommend the removal of `awsEndpointRequestId2` & `dataProcessed`, since they don't seem to have an effect in the logs and complementary to that, they aren't in the [list of log variables](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference%3Fcmpid=docs_apigateway_console).
Also, it appears as that all of the integrationS(s)(_s)tatus variables are duplicates, not sure which ones should be removed.

**Comment by achave11** [comment]
Correction: The above to fields can be found on https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-logging-variables.html

**Comment by achave11** [comment]
Remove: 
$context.integrationStatus
$context.awsEndpointRequestId

**Comment by hannes-ucsc** [comment]
Estimate increase due to https://github.com/DataBiosphere/azul/pull/3700#pullrequestreview-861361549

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "We've recently updated Terraform and the AWS provider. @achave11 should take another look at this soon. Maybe the updates fixed the race @achave11 observed."

**Comment by hannes-ucsc** [comment]
For demo, show the additional fields in the log. Show how to correlate the request log with the application log.

**Comment by achave11** [comment]
`awsEndpointRequestId2` is `-` during demo.

**Comment by achave11** [comment]
To remove: 
`
integrationErrorMessage
integrationLatency
`
