### ISSUE TITLE
AttributeError when importing `azul.bigquery_reservation`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3508]
![image](https://user-images.githubusercontent.com/5143256/136419077-e95a9aa9-c6ce-4d1f-83e0-5b1f6ddb09e1.png)

The second import works if the first one is omitted. I would expect the second import to work in either case.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to fill in details.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
