### ISSUE TITLE
Index snapshots with updated analyses into `dcp2` on `dev`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3510]
[Slack link](https://humancellatlas.slack.com/archives/C01360XN04S/p1633618331208300?thread_ts=1631840213.076200&cid=C01360XN04S).

Dataset: hca_dev_f48e7c39cc6740559d79bc437892840c__20210830
Snapshot: hca_dev_f48e7c39cc6740559d79bc437892840c__20210830_20211007
Google Project ID: datarepo-dev-b51e6694

Dataset: hca_dev_83f5188e3bf749569544cea4f8997756__20210929
Snapshot: hca_dev_83f5188e3bf749569544cea4f8997756__20210929_20211007
Google Project ID: datarepo-dev-560ee3d1

**Comment by kbergin** [comment]
Hello! Just checking in if these datasets had been indexed in dev successfully? We'd love to be able to process 8 SS2 datasets in Prod in time for the Oct 25th deadline for release 11 so that DCP1 can be retired :D

**Comment by nikellepetrillo** [comment]
Hi @hannes-ucsc, the team took a look at f48e7c39-cc67-4055-9d79-bc437892840c in the browser and it looks good to us! Thank you

**Comment by hannes-ucsc** [comment]
Thank you, @nikellepetrillo. The scaling issue has been addressed and https://dev.singlecell.gi.ucsc.edu/explore/projects/83f5188e-3bf7-4956-9544-cea4f8997756 was indexed successfully. Could check that one as well?
