### ISSUE TITLE
Only one LungMAP project showing up in `prod`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3513]
Introduced in #3496.
The new snapshot should have been added to the LungMAP catalog, not replaced the previous snapshot.

Previous project details:
Dataset: hca_prod_20210616_lungmap2
Snapshot: hca_prod_20210616_lungmap___20210616_lm1
Google Project ID: ???

**Comment by achave11** [comment]
project ID: `broad-datarepo-terra-prod-hca2`
