### ISSUE TITLE
Promotions should involve PR and feature branch

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3516]
… so that we can track operator tasks in the PR checklist. Also, merge commit title should carry commit title tags from all merged commits. Modify operator manual to reflect these changes.

**Comment by jessebrennan** [comment]
What is the naming convention for the feature branch? What should the merge commit title be?

**Comment by jessebrennan** [comment]
@hannes-ucsc: "Commit title should be the same as before, but carry over tags (i.e. [r u]). Feature branch should be `promotions/yyyy-mm-dd`."
