### ISSUE TITLE
Add summary cell counts based on projects index

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3521]
We currently populate the cell count summaries (`totalCellCount` and `cellCountSummaries`) from the cell suspensions index. This makes sense because the underlying schema property (`cell_suspension.total_estimated_cells`) applies to cell suspensions. This means that the summary currently returns the sum of the `total_estimated_cells` property of each cell suspension that matches the current filter. If we were to use a different index, say projects, we would return the sum of the `total_estimated_cells` property of each cell suspension *in each project* that matches a filter, a subtle but significant difference. So in general, it is important that a summary property is backed by the index for the entity type that defines the property.

However, the project-level cell count in the project schema (`project.estimated_cell_count`) throws a wrench in the gears: If the Data Browser displays the project-level cell count in the *Cell Count Estimate* column (falling back to the sum of the cell suspension cell counts if no project level cell count is available), the sum of the column values may not match the cell count from the summary up top. That's the UI inconsistency we want to avoid. We need to extend the summary so that the Data Browser easily produce a summary that matches the table. If we don't, users would be able to filter down the project display to a single project row and get confused by the discrepancy. The project row may reflect a project-level cell count of 10000 because it reflects all cell suspensions in the project, while the summary displays a cell count of 5000 because only half of the project's cell suspension match the filter criteria.

The solution is to return to the Data Browser a sum of `cell_suspension.total_estimated_cells` of each cell suspension in each project matching the filter, in addition to the sum of `project.estimated_cell_count` of each project matching the filter. There is one more complication: we can't just add these two properties up and display them in the summary. if a project has both `project.estimated_cell_count` and `cell_suspension.total_estimated_cells` populated, we risk counting cells twice. For that reason we need to provide this pair of sums for each possible combination of `project.estimated_cell_count` and `cell_suspension.total_estimated_cells` being populated or not.

An example: The summary endpoint currently returns

```
{
    "projectCount": 103,
    "specimenCount": 7233,
    "speciesCount": 2,
    "fileCount": 112325,
    "totalFileSize": 25440020302158.0,
    "donorCount": 1027,
    "labCount": 194,
    "totalCellCount": 8371782.0,
    "projectEstimatedCellCount": 867820.0,
    "organTypes": [],
    "fileTypeSummaries": [],
    "cellCountSummaries": []
}
```

That should become

```
{
    "projectCount": 103,
    "specimenCount": 7233,
    "speciesCount": 2,
    "fileCount": 112325,
    "totalFileSize": 25440020302158.0,
    "donorCount": 1027,
    "labCount": 194,
    "totalCellCount": 21,
    "projects": [
        {
            "projects": {
                "estimatedCellCount": 10  # Display this …
            },
            "cellSuspensions": {
                "totalCells": 10
            }
        },
        {
            "projects": {
                "estimatedCellCount": 5  # … plus this …
            },
            "cellSuspensions": {
                "totalCells": null
            }
        },
        {
            "projects": {
                "estimatedCellCount": null
            },
            "cellSuspensions": {
                "totalCells": 11  # … plus this.
            }
        }
    ],
    "organTypes": [

    ],
    "fileTypeSummaries": [

    ],
    "cellCountSummaries": [

    ]
}
```

The Data Browse would then cherry pick the three indicated sums from the response and add them up for display in the summary section above the table.

The response might appear a bit more complicated than strictly necessary. My vision is for the summary response to more closely resemble the inner/outer entity dichotomy found on the other endpoints. That's why the response has the `"projects"` key nested inside another `"projects"` key. Using this format, we can in the future eliminate the cherry picking of individual properties based on the authoritative index and instead report results from all indices and have the Data Browser do the cherry picking based on their requirements.

**Comment by hannes-ucsc** [comment]
For demo, show the new structure in the summary endpoint. Add filters on the underlying facets to show how the summary changes. For example, if a filter selects all projects without a project-level estimate, the summary should reflect that with certain fields going to zero.
