### ISSUE TITLE
`make reindex` spends a lot of time resolving sources

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3525]
`AzulClient.remote_reindex` makes a round-trip to TDR to resolve every source to verify its ID. There are several issues with this:

1. This verification is 100% redundant since `resolve_source` and `verify_source` perform exactly the same lookup to check the source ID (both call `plugins.repository.tdr.Plugin.lookup_source_id` which calls `TDRClient.lookup_source`, which is _cached_).
2. Source resolution doesn't need to take place locally on the machine where the reindex is started from. It could be done in `AzulClient.remote_reindex_partition` after receiving only the spec from `message['source']`.
3. There appear to be several methods that pretend to require a `TDRSourceRef` when in reality a `TDRSourceSpec` instance would suffice, so it's unclear at what point the resolving the spec to a ref is actually necessary. This aspect might benefit from a spike, but it might not matter if the first two points are addressed.

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc : "We'll remove the `verify_source` method altogether to solve this issue. At a later time, we'll add it back but implement it by looking up the source by ID, synthesizing the name from that response, and compare the result against the spec. Furthermore, the current call to `verify_source` occurs way too early. Ideally we would do it when the bundle notification is about to be processed."

**Comment by hannes-ucsc** [comment]
This stale. The FIXME is gone. I don't think this applies anymore.
