### ISSUE TITLE
Remove deprecated response field hits[].projects[].contributorMatrices

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3526]
Remove deprecated field `hits[].projects[].contributorMatrices`.
The field has been superseded by `hits[].projects[].contributedAnalyses` in https://github.com/DataBiosphere/azul/issues/3420

**Comment by amarjandu** [comment]
This Issue appears to be resolved as part of PR #3526. 31bb637d

**Comment by hannes-ucsc** [comment]
For demo, show that response property is gone.
