### ISSUE TITLE
`terraform init` complains about outdated GPG key for Terraform

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3538]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/31267#L270
`Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512`

**Comment by hannes-ucsc** [comment]
I'll be solving this as part of #3605.

**Comment by hannes-ucsc** [comment]
For demo, compare the job logs for a build before the Terraform upgrade and one after.
