### ISSUE TITLE
`test_can_bundle_canned_repository` IT fails in `dev` deployment

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3544]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/31423#L1632
```
======================================================================
ERROR: test_can_bundle_canned_repository (integration_test.CanBundleScriptIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/.venv/lib/python3.8/site-packages/more_itertools/more.py", line 520, in one
    value = next(it)
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 1240, in test_can_bundle_canned_repository
    self._test_catalog(mock_catalog)
  File "/builds/ucsc/azul/test/integration_test.py", line 1179, in _test_catalog
    fqid = self.bundle_fqid(catalog.name)
  File "/builds/ucsc/azul/test/integration_test.py", line 1244, in bundle_fqid
    return one(bundle_fqids)
  File "/build/.venv/lib/python3.8/site-packages/more_itertools/more.py", line 522, in one
    raise too_short or ValueError('too few items in iterable (expected 1)')
ValueError: too few items in iterable (expected 1)
```

**Comment by amarjandu** [comment]
Regression added by #3476  https://github.com/DataBiosphere/azul/blob/f2a7e05fd6e1e9a07ac69c0a7c9c2511bc455c27/deployments/dev/environment.py#L178

Default prefix partition length was changed from `0` to `2`. 
This narrows the number of bundles that are returned turning IT: https://github.com/DataBiosphere/azul/blob/f2a7e05fd6e1e9a07ac69c0a7c9c2511bc455c27/test/integration_test.py#L188


Sandbox uses `0`: https://github.com/DataBiosphere/azul/blob/f2a7e05fd6e1e9a07ac69c0a7c9c2511bc455c27/deployments/sandbox/environment.py#L189

**Comment by amarjandu** [comment]
We should also pin the partition prefix length within the canned sourced specified in the IT test to avoid failures that can be deployment specific. Otherwise this failure will occur again when we do a promotion to `prod` due to its default partition prefix length being set to `2`.
