### ISSUE TITLE
`/repository/files/{UUID}` should yield 404 for non-existing files

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#355]
https://service.dev.explore.data.humancellatlas.org/repository/files/foo

Actual: 500 response with

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 726, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 150, in get_data
    response = response['hits'][0]
IndexError: list index out of range
```

Expected: 404 response saying 

```
File `foo` does not exist`
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-231)
┆Project Name: azul
┆Issue Number: AZUL-231

**Comment by hannes-ucsc** [comment]
Fell out of https://github.com/DataBiosphere/azul/issues/354

**Comment by mweiden** [comment]
Just encountered this on the `/repository/projects/{UUID}` endpoint as well:

https://service.explore.data.humancellatlas.org/repository/projects/2a0faf83-e342-4b1c-bb9b-cf1d1147f3bb

Also, you might consider returning a `Bad Request` or something else in the case of malformed input:

https://service.explore.data.humancellatlas.org/repository/projects/invalid

**Comment by hannes-ucsc** [comment]
Yup. A syntactically invalid UUID should yield a 400. A valid UUID that does not refer to an existing entity should yield a 404.

**Comment by GPelayo** [comment]
I demoed this on 4/1/2019
