### ISSUE TITLE
Test duplicate notifications during IT

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3558]
This is follow-up work for #2789 which causes an intentional regression here.

**Comment by noah-aviel-dove** [comment]
The solution for https://github.com/DataBiosphere/azul/issues/2789 no longer causes this regression. This should either be made a freebie or closed as invalid.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "This used to be a FIXME in a PR for #2789. It never was an issue on develop. @noah-aviel-dove's fix for #2789 will maintain testing of duplicate bundle notifications."
