### ISSUE TITLE
Listing bundles for a snapshot gives zero bundles

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#3561]
With `sandbox` selected run this in your interpreter

```python
from azul.azulclient import AzulClient
c = AzulClient()
plugin=c.repository_plugin('dcp2')
bundles_per_source = {}
for s in plugin.sources:
    source = plugin.resolve_source(str(s))
    bundles_per_source[str(s)] = c.list_bundles('dcp2', str(s), '')
    
{k:v for k, v in bundles_per_source.items() if len(v) == 0}
```

This will yield a single snapshot. It should yield none. 

The snapshot in question: `tdr:datarepo-dev-b839d6c7:snapshot/hca_dev_e526d91dcf3a44cb80c5fd7676b55a1d__20210902_20210907:e5/0`.

**Comment by hannes-ucsc** [comment]
Needs reproduction.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to review

**Comment by jessebrennan** [comment]
Listing bundles for every snapshot in `dev` took ~4:20 minutes.
Listing bundles for every snapshot in `sandbox` took ~4 minutes

This could potentially be sped up by using a BQ query which only gets the count instead of all of the bundles, since we only need the cardinality.

**Comment by noah-aviel-dove** [comment]
Making this a blocker of https://github.com/DataBiosphere/azul/issues/3095 because I had a bug in that PR that was erroneously causing zero bundles to be listed, and I'd like to have this verification in place before I move that ticket to review

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
