### ISSUE TITLE
Configure indexer lambda with information about public snapshots

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3572]

**Comment by noah-aviel-dove** [comment]
Create a hook in the Plugin class for injecting the variables into the lambda environment. Config can load plugins for all catalogs and call the hook. The accessor methods for those variables would be moved to the Plugin as well.

**Comment by noah-aviel-dove** [comment]
Note for parking lot: if we have 4 or more managed access sources in a single catalog, we will need to outsource the environment variable. We'll need to do some refactoring if want to be able to outsource lowercase vars.

**Comment by noah-aviel-dove** [comment]
Decided at parking lot to allow lowercase vars to be outsourced.

**Comment by hannes-ucsc** [comment]
This chain of tickets is blocked by HumanCellAtlas/dcp2#54 since I don't want us to infer the public status from making two listings. That's too complicated a workaround that I don't want to commit to maintaining long-term.

**Comment by hannes-ucsc** [comment]
Blocker is in `dev`

**Comment by hannes-ucsc** [comment]
I take that back. There is some uncertainty on the spelling of the added property and the deployment schedule for production.

**Comment by hannes-ucsc** [comment]
This has not been requested in a long time.

**Comment by hannes-ucsc** [comment]
Obsoleted by #5268
