### ISSUE TITLE
"Error importing data" for "large" PFB manifest

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3575]
![pfb-import-1.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/1b944cbe-088d-438d-bba5-73aa9f5f9867)

From David An ([Slack](https://humancellatlas.slack.com/archives/C018YPVKC73/p1634853371003300)): the error XXX not found usually means that the data contains "foreign keys," that is some data entity references another data entity, but the entity being referenced wasn't found. This could be simply because it's not in the PFB, or possibly the PFB is out of order … the entities being referenced need to be earlier in the file than the later ones.

**Comment by theathorn** [comment]
Close this?

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Ticket lacks concrete reproduction, therefore fix is hard to verify. Closing.
