### ISSUE TITLE
"Problem checking status of data import" for PFB manifest

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3576]
![pfb-import-2-network.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/01d07ad7-eae4-4449-9d4b-5847662821a8)

From David An: and this one is an ajax failure - this is a known problem in our polling system; we are too aggressive about showing errors during polling, but the import operation itself is not in error. This is tracked as [AS-487](https://broadworkbench.atlassian.net/browse/AS-487) if you ever want to refer to it. Sorry you hit this!

**Comment by danielsotirhos** [comment]
Verified I was able to successfully import a PFB manifest without issue.

![Screen Shot 2022-03-11 at 12 34 14 PM](https://user-images.githubusercontent.com/46407464/157960083-421714b1-be9e-4c0f-911e-7adc3e6e74c7.png)

![Screen Shot 2022-03-11 at 12 35 25 PM](https://user-images.githubusercontent.com/46407464/157960133-8db134cd-ecf8-41a9-a9a2-1b52988f1fe1.png)

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Currently still waiting for resolution from Terra team. No work for @danielsotirhos ATM."

**Comment by bvizzier-ucsc** [comment]
@hannes-ucsc: "Seems to be stale.  If it happens again, we will open a new ticket."
