### ISSUE TITLE
Sort by combination of cell suspension and project cell counts

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3581]
@NoopDog in https://github.com/HumanCellAtlas/data-browser/issues/1867#issuecomment-951242088

> We are looking at implementing this on the Data Browser. Currently, we have a "Cell Count Estimate" column that is backed by `hits[].cellSuspensions[].totalCells`. Note that `cellSuspensions[].totalCells` is aggregated in the browser by going over the list of `hits[x].cellSuspensions` in the Azul response.
> 
> This list is sortable on the UI by using `sort=cellCount` parameter in the /index/projects API call.
> 
> For the project list page, we can swap out the display of the Cell Count Estimate to use the `project.estimatedCellCount` when it is available. 
> However, it seems that using`sort=cellCount` still returns items in order of the `aggregate cellSuspension[].totalCells` and is not informed by the `project.estimatedCellCount`. 
> 
> Is there a different sort key we should be using? How do you recommend we sort the projects list by the count of cells in the project?

 @hannes-ucsc in https://github.com/humancellatlas/data-browser/issues/1867#issuecomment-952302708:

> The `cellCount` field is backed by the synthetic index field `estimated_cell_count` (not under `contents`) in aggregate documents. We can modify how that field is synthesized during aggregation to be `max(sum(contents.projects[*].estimated_cell_count), sum(contents.cell_suspensions[*].total_estimated_cells))` instead of just `sum(contents.cell_suspensions[*].total_estimated_cells)`. The `max` logic should NOT be applied to `cell_suspension` aggregates but I'm not sure if the synthetic `total_estimated_cells` field is even present on those aggregates.
> 
> This assumes that the DB also uses `max` to chose between `hits[i].cellSuspensions[*].totalCells` and `hits[i].project.estimatedCellCount` for the column display, obviously.

**Comment by danielsotirhos** [comment]
@hannes-ucsc : "Changed my mind. The max logic should only be applied to the projects endpoint, because in any other endpoint the sum of the cell counts of the cell suspensions associated with the outer entity returned by that endpoint is going to be less than the total cell count of the project the outer entity belongs to."

**Comment by danielsotirhos** [comment]
This ticket modifies the sort facet `cellCount` and adds a new sort facet `effectiveCellCount`.
- `cellCount`: The sum of cells from the cell suspensions
- `effectiveCellCount`: (on proects endpoint) the larger value between the sum of cells from the cell suspensions and the cell count from the project, or (on non-projects endpoints) the sum of cells from the cell suspsensions.

**Comment by hannes-ucsc** [comment]
For demo, sort all endpoints by `https://github.com/HumanCellAtlas/data-browser/issues/1867#issuecomment-951242088` and using `jq` print the associated project and cell suspension cell counts in the hits in the response. Illustrate that the max logic is only being applied on the projects endpoint.
