### ISSUE TITLE
Some calls to resolve_source are only done to parse the source spec

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3586]
The one in scripts/can_bundle.py for example. Split resolve source into two methods: one to parse a source spec, and another to convert a source spec to a source ref. Find all call sites that can be replaced with a call of the former.

**Comment by hannes-ucsc** [comment]
There is only one call to `resolve_bundle` in the canning script:

https://github.com/DataBiosphere/azul/blob/104a73bde6f7b469f19eae20f0969f5c348ab37c/scripts/can_bundle.py#L96

The returned source ref is used later to contruct an FQID so the prime example given is invalid. I surveyed the other call sites and they look fine.
