### ISSUE TITLE
Investigate unknown wildcard TLS certificates in our AWS account (hca-platform-dev)

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3587]
From 10/12/2021 Slack discussion: https://app.slack.com/client/T09P9H91S/C02B4S0V6GH/thread/C02B4S0V6GH-1634060259.000900

- `*.dev.lungmap.net`
- `*.dev.ucsc-cgp-redwood.org`
- `*.data.ucsc-cgp-redwood.org`
- `*.ucsc-cgp-redwood.org`
- `*.ucsc-redwood.com`

Investigate who created them and ask them to either delete or convert to a non-wildcard cert.

**Comment by melainalegaspi** [comment]
Assignee to find all wildcard certs in dev and prod.

**Comment by theathorn** [comment]
See @NoopDog's comment in HumanCellAtlas/data-browser#2004.

**Comment by amarjandu** [comment]
All wildcard certificates have been removed.

![image](https://user-images.githubusercontent.com/1947534/143095965-4ee66d12-5794-4836-909c-95871f3c4f60.png)

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "The wildcard certificates are gone."
