### ISSUE TITLE
Reindexing is considerably slower

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3589]
Current reindex

![image](https://user-images.githubusercontent.com/5143256/139337539-f83555db-0140-4a7b-8a74-58cf95351520.png)

Previous reindex (same time axis scale)

![image](https://user-images.githubusercontent.com/5143256/139337777-a8722bb7-a0c2-419e-bebb-17d2ed3eabef.png)

Note the bump in notifications retry queue at the end of the current reindex.

**Comment by hannes-ucsc** [comment]
I've updated the dashboard to account for invisible and delayed messages. The transition from notification queue to notifications_retry queue looks slightly different now, but still peculiar.

![image](https://user-images.githubusercontent.com/5143256/139482864-88af7ec9-1ad4-46cd-8f77-d39835da7551.png)

I have no idea why there isn't a steady spill-over rate from `notifications` to `notifications_retry`, and why all remaining messages in the notifications queue transition in a very short period of time instead.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Waiting for #3593 to complete before triaging again."

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/3593#issuecomment-960459775

Disable batch jobs by setting the corresponding configuration environment variable default to 0 as hotfix against `prod` branch with backport.

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc : "Contrary to what I wrote above, we should target develop initially, and might our change during PR review"

**Comment by hannes-ucsc** [comment]
For demo, post here with screenshot of CW dashboard first prod reindex with this change deployed in prod. Show post during demo.

**Comment by noah-aviel-dove** [comment]
![Screenshot from 2021-11-23 13-44-01](https://user-images.githubusercontent.com/48401926/143133955-29278064-3191-4231-b199-c9e9690d70f1.png)

**Comment by danielsotirhos** [comment]
@hannes-ucsc : "I will evaluate the findings. It looks like we don't have an apples to apples comparison because the reproduction appears to be one-catalog reindex whereas Noah's screenshot is of a three-catalog reindex."

**Comment by hannes-ucsc** [comment]
In order to compare the two experiments, @noah-aviel-dove to estimate slope of the quasi-linear portion of the queue length curve for the notifications queue during the reindex depicted in the first screenshot in the description of this ticket. Repeat for the reindex depicted in the screenshot he posted.

**Comment by noah-aviel-dove** [comment]
For the reindex corresponding to the first screenshot posted, the slope is approximately -13,770 from 00:00 UTC to 17:00 UTC and -14,330 from 01:00 UTC to 16:00 UTC (I consider the latter figure more reliable as the 1-hour granularity may cause distortions around the endpoints of the quasi-linear section of the graph).

**Comment by noah-aviel-dove** [comment]
For the reindex corresponding to my screenshot (11-19), the slope is approximately -30,580 from 01:00 UTC to 16:00 UTC and  -31,380 excluding the endpoints.

**Comment by noah-aviel-dove** [comment]
These numbers derived using a linear regression to fit the points (https://www.socscistatistics.com/tests/regression/default.aspx)

![image](https://user-images.githubusercontent.com/48401926/148146214-08ed5d56-fc5e-4a28-bec9-28da1ca8b55e.png)

![image](https://user-images.githubusercontent.com/48401926/148146297-a24ccd23-6ccc-4364-aa8e-d19e621e9b11.png)

**Comment by hannes-ucsc** [comment]
I'm too lazy to do the math. A slope is one number, *Δy/Δx*  which in our case has the unit 1/hour. Please produce this number for both reindexes and refer to the reindexes as "before" and "after" the change rather than "my screenshot" or "first screenshot" so that we conclude this issue with an easy to understand and definitive statement at the bottom.

**Comment by noah-aviel-dove** [comment]
Before: -14,330
After:-31,380

**Comment by hannes-ucsc** [comment]
OK, so it is twice a fast after the change.
