### ISSUE TITLE
Inverted condition on IT warning about too few bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3591]
https://github.com/DataBiosphere/azul/blob/a9d11b56220f4cf81527a95d05fbe68638a3b068/test/integration_test.py#L206

Should be `<`

**Comment by melainalegaspi** [comment]
@jessebrennan: "Obsoleted by #2789."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : " @noah-aviel-dove to confirm Jesse's claim."

**Comment by noah-aviel-dove** [comment]
Confirmed. The new bundle listing code in https://github.com/DataBiosphere/azul/pull/3583/files does not inherit this problem. \
https://github.com/DataBiosphere/azul/pull/3583/files#diff-4e904e078d9dedfc711df509920616607e93d4970e8a1115465fabc13bca0e00R218
