### ISSUE TITLE
Swagger UI shows obscure error for non-fetch file and manifest endpoints

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3599]
When using the (non-fetch) `/manifest/files` or `/repository/files` endpoints via the swagger UI, no response is displayed besides the message `TypeError: NetworkError when attempting to fetch resource.` The response HTTP code is shown as "Undocumented", despite both the 301 and 302 being documented right below where the error is shown. The accompanying cURL commands work as expected when executed in the console.

To reproduce, go to https://service.dev.singlecell.gi.ucsc.edu/#/Repository/get_repository_files__file_uuid_, enter `c3d6c0a2-29b9-4173-9d55-26ac48cc143c` for the `file_uuid`, and click `Execute`. Observed response:

![Screenshot from 2021-11-01 13-15-50](https://user-images.githubusercontent.com/48401926/139735822-43fa2728-c3e4-49b6-9b0b-e0e50c7a3efd.png)

(This may be invalid since the `/fetch/*` endpoints are intended to cover this use case. Still, the error is quite ugly and cryptic, and confused me enough to make me open a ticket, so at the very least maybe we should update the documentation).

**Comment by melainalegaspi** [comment]
@noah-aviel-dove to provide a better reproduction.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"The error message is indeed cryptic."

**Comment by melainalegaspi** [comment]
Spike for resolution.

**Comment by noah-aviel-dove** [comment]
I think this is caused by a missing CORS header in the redirect.

![Screenshot from 2022-02-26 17-53-18](https://user-images.githubusercontent.com/48401926/155865529-99c234a5-7705-4c0a-b3ea-acd677d3ad83.png)

![Screenshot from 2022-02-26 18-11-36](https://user-images.githubusercontent.com/48401926/155865555-743a0721-54ca-4340-b82b-54f17ae78fff.png)

![Screenshot from 2022-02-26 18-11-48](https://user-images.githubusercontent.com/48401926/155865558-d12a82a9-94ee-4974-bf54-4ca59cdbaa7f.png)

**Comment by melainalegaspi** [comment]
@hannes-ucsc to review.

**Comment by hannes-ucsc** [comment]
The CORS hypothesis sounds about right. The problem is that browsers don't respect `Retry-After` and will therefore quickly exhaust their maximum # of retries. So fixing CORS won't be enough to make these non-fetch endpoints work generally. I'm happy to have someone verify my hypothesis by running another experiment: add CORS for that Google endpoint and try a large uncached manifest.

Not sure this is worth it, though. Maybe we should just add a big disclaimer stating that these two endpoints don't work interactively in the Swagger UI. Maybe we could even disable them.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Decided in Triage that we would try to disable the button and provide a disclaimer."

**Comment by hannes-ucsc** [comment]
For demo, show the disabled *Try it out* button and that the links from the description to the anchors for the respective alternative endpoint works.
