### ISSUE TITLE
Create on- and off-boarding documentation

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3600]
Created from 10/29/2021. Include the following: 
SSH keys in Gitlab instance, Azul permissions, AWS keys, Google credentials, personal deployment

**Comment by jessebrennan** [comment]
I just unsubscribed from the Azul Google group (which is used for the Azul bot's Github account).

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"This is complete."
