### ISSUE TITLE
Place GitLab behind VPN

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3605]
Use AWS client VPN which is essentially a managed OpenVPN service.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_client_vpn_endpoint

Ultimately we need to remove the ALB and NLB, remove the two public subnets, and reduce the number of private subnets to one. We had to have two because AWS wanted load balancer targets in two availability zones. Without any LBs we won't need to satisfy that constraint. We will keep the VPC, keep the NAT Gateway (for egress from the Gitlab instance) and the internet gateway (to allow ingress to the VPN endpoints. The security group should allow inbound OpenVPN traffic 

This is a more complicated setup with a steep learning curve. Assigned would need to be familiar with OpenVPN and VOC networking. To simplify the task, we'll start with a spike that creates a private place VPC in a personal deployment, place a micro EC2 instance inside it, and put a VPN endpoint in the VPC that provides ingress to the instance. Install an OpenVPN client and demonstrate that the instance has no public IP and that one can only SSH into it through the VPN. Essentially, follow the procedure in

https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-getting-started.html

The second half of the spike is creating the same setup with Terraform.

The actual implementation will be integrating the resulting TF config into the current Gitlab TF config.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to provide description.
