### ISSUE TITLE
Update GitLab every week

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3608]
Important to mention that when performing updates across multiple versions, that one needs to follow the recommended [upgrade path](https://docs.gitlab.com/ee/update/index.html#upgrade-paths) and to wait for [background migrations](https://gitlab.dev.singlecell.gi.ucsc.edu/admin/background_migrations) to finish at each step. Luckily, multi-step upgrades are less likely to be required when the updates are done every week.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : " @melainalegaspi to create Slack notification on Mondays for operator to check for GitLab updates. Assignee to document procedure in operator manual. Procedure will likely involve an update to the GitLab tf config for the dev instance and deployment of that by the operator. The deployment of the prod instance will have to be done by @hannes-ucsc after being notified by the operator."

**Comment by melainalegaspi** [comment]
I've created a Slack workflow for a notification reminder; removing myself as assignee.

**Comment by amarjandu** [comment]
Useful links for checking version
https://gitlab.dev.singlecell.gi.ucsc.edu/help
https://gitlab.azul.data.humancellatlas.org/help
https://gitlab.com/gitlab-org/gitlab-foss/blob/master/CHANGELOG.md (edited)

**Comment by amarjandu** [comment]
@hannes-ucsc the link for [background migrations](https://gitlab.dev.singlecell.gi.ucsc.edu/admin/background_migrations) is not accessible (404), might be only accessible for admins.

**Comment by amarjandu** [comment]
@amarjandu use generic language to describe the setup process of the webhook url, we want to use it for #1751 as well.

**Comment by hannes-ucsc** [comment]
Skipping demo. We'll see if the snapshot script works when we next update GitLab.

@achave11 FYI
