### ISSUE TITLE
Contribute lambda times out fetching upstream subgraphs

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3613]
TODO: @danielsotirhos to fill in reproduction

**Comment by danielsotirhos** [comment]
@hannes-ucsc:
> Currently we perform 1 query per upstream bundle. We should fetch them in batches of N bundles per request using the [IN](https://cloud.google.com/bigquery/docs/reference/standard-sql/operators#in_operators) operator, using the tuple form: `(links_id, version) IN (('7681f23d-401e-5b77-bf1d-20a782f91965', TIMESTAMP('2021-10-12T18:33:36.000000Z'), ...)`.

> Additionally, the fetching of entities should also use the IN operator instead of OR.

**Comment by noah-aviel-dove** [comment]
I suspect this will run into issues with TinyQuery

**Comment by hannes-ucsc** [comment]
Write a method `def _in(lhs:Tuple[str], rhs:Iterable[Tuple[Any]) -> str` to return an efficient SQL expression using the `IN` operator for use in the WHERE clause. Patch that method during tests to return an expression that uses `OR` and `==`.

**Comment by hannes-ucsc** [comment]
Test the change in personal deployment by pointing it at the dcp11 snapshot from prod and canning the affected subgraphs, tracking the running time.

**Comment by danielsotirhos** [comment]
From https://github.com/DataBiosphere/azul/pull/3609#issuecomment-961211618

catalog: dcp11
bundle_uuid: 10260267-ca02-5b10-9df7-37697886f1de
bundle_version: 2021-10-12T18:47:27.000000Z
REPORT RequestId: 3fd952e0-d693-5399-abde-0b1d55d21af7 Duration: 900100.51 ms Billed Duration: 900000 ms Memory Size: 4096 MB Max Memory Used: 113 MB
Project: ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad

catalog: dcp11
bundle_uuid": 7681f23d-401e-5b77-bf1d-20a782f91965
bundle_version: 2021-10-12T18:33:36.000000Z
REPORT RequestId: b1fe75df-88d0-5f6e-85e3-2c220b916d8b Duration: 900100.49 ms Billed Duration: 900000 ms Memory Size: 4096 MB Max Memory Used: 143 MB Init Duration: 1608.94 ms
Project: 90bd6933-40c0-48d4-8d76-778c103bf545

catalog: dcp11
bundle_uuid: a7882d93-786a-5929-a083-c12635d39453
bundle_version: "2021-10-12T19:18:03.000000Z
REPORT RequestId: b9d7e643-745f-59fe-a8c2-bfbef71e1886 Duration: 900045.67 ms Billed Duration: 900000 ms Memory Size: 4096 MB Max Memory Used: 113 MB
Project: cddab57b-6868-4be4-806f-395ed9dd635a

catalog: dcp11
bundle_uuid: fe70d276-05be-5ad7-8d87-135c04cfaf54
bundle_version: 2021-10-07T18:17:35.000000Z
REPORT RequestId: a226fce8-a3f5-581a-980a-a51520b4173d Duration: 900100.45 ms Billed Duration: 900000 ms Memory Size: 4096 MB Max Memory Used: 185 MB Init Duration: 1589.04 ms
Project: f83165c5-e2ea-4d15-a5cf-33f3550bffde

catalog: dcp11
bundle_uuid: a059d535-19e5-5ba2-b794-434e0fe89195
bundle_version: 2021-10-06T17:32:00.000000Z
REPORT RequestId: a0d7b1c2-208a-5942-98b9-e83fa3cb36de Duration: 900100.66 ms Billed Duration: 900000 ms Memory Size: 4096 MB Max Memory Used: 105 MB
Project: f83165c5-e2ea-4d15-a5cf-33f3550bffde

**Comment by hannes-ucsc** [comment]
For demo, show the running time of the notification lambda for the five affected subgraphs during the first reindex with these changes deployed on prod.

**Comment by hannes-ucsc** [comment]
We either forgot to demo this or, if we did, forgot to label it correctly.
