### ISSUE TITLE
Scan GitLab instances with ClamAV every week

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3614]
This easy to do on RancherOS using the clamav Docker image:

https://docs.clamav.net/manual/Installing/Docker.html

Scan both the data and the root volume.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to improve solution based on comment by @amarjandu regarding automation via cron.

**Comment by hannes-ucsc** [comment]
Define a service in the cloud-init user data for the instance:

https://rancher.com/docs/os/v1.2/en/system-services/custom-system-services/

Specifically specify a "service cron":

https://rancher.com/docs/os/v1.2/en/system-services/custom-system-services/#service-cron

to achieve the same effect as running this command from the command line:

```
docker run -it --rm --mount type=bind,source=/,target=/scan,readonly  clamav/clamav:unstable clamscan -rz /scan
```

Use the clamscan exit status to trigger posting a Slack message using a Slack app's bot token.

**Comment by amarjandu** [comment]
Make sure to write the README addition for the webhook in a generic way.

**Comment by amarjandu** [comment]
@hannes-ucsc "In order to reduce coordination with operator work on this continues when @amarjandu is operator, starting Jan 17, 2022."

**Comment by danielsotirhos** [comment]
For demo: Show logs that confirm ClamAV scans are being run weekly, and briefly explain the results of the scan.
