### ISSUE TITLE
Setting AZUL_CONTRIBUTION_CONCURRENCY too low prevents timely completion of IT

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3628]
A configuration like `'AZUL_CONTRIBUTION_CONCURRENCY': '8/4'` in personal deployments (retry lambda concurrency set to 4) causes stalls and prevents a timely completion of the integration test.

**Comment by melainalegaspi** [comment]
@achave11 to provide more information: reproduce on develop and provide output of integration tests with above settings.

**Comment by achave11** [comment]
Full IT output with `AZUL_CONTRIBUTION_CONCURRENCY=8/4`  : [develop_IT_run_8-4.txt](https://github.com/DataBiosphere/azul/files/7542567/dev_it_repro.txt)

**Comment by melainalegaspi** [comment]
@hannes-ucsc to evaluate reproduction and determine the validity of this ticket.

**Comment by hannes-ucsc** [comment]
This is expected. Reduced concurrency leads to reduced throughput and extends the time to complete indexing of a fixed number of bundles. The occasional stall (https://github.com/DataBiosphere/azul/issues/1618, still unexplained) aggravates that. While it would be possible to derive the indexer timeout from the concurrency, I think that there are non-linear effects at small numbers would make this difficult. The potential cost benefit of supporting very low concurrency in personal deployments is not worth the effort of dealing with the complexity introduced by non-linear behavior at the low end.
