### ISSUE TITLE
Update Azul indexer (for Commons) to use dcp-cli v4.2.1

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#363]
Update Azul indexer (for Commons) to use `dcp-cli` v4.2.1, including a small change to how the DSSClient is initialized, as described here: https://hca.readthedocs.io/en/latest/
This is to help address issues that can occur with earlier versions of the dcp-cli when referencing a specific DSS deployment.

This is not a high priority, yet depending on how soon we move to the common/HCA implementation of Azul, it may be worth doing.

Done when:
 Azul indexer (for Commons) is updated to use dcp-cli v4.2.1 and deployed to Commons dev.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-234)
┆Project Name: azul
┆Issue Number: AZUL-234

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
