### ISSUE TITLE
Experiment with shard counts

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3630]
Pick a recent reindex on `prod` as a baseline. Repeat the reindex with the same settings except use

- one aggregate primary shard instead of `num_nodes` shards; leave # of replicas at `num_nodes - 1`
- `num_workers/8` primary contribution shards instead of `num_workers/4`;  leave # replicas at 0

For the baseline and the experimental reindex collect,

1) the max length of every queue over the entire indexing time, in 5min buckets
2) the average ES JVM memory pressure metric over the entire indexing time, in 5min buckets
3) the number of 429 errors per 5min over the entire indexing time

Modify the CW dashboard to add the above metrics as necessary. Have lead review the dashboard changes. The CW logs query for the 429 errors might be tricky.

We might want to do a repeat of this experiment with `num_workers/16` primary contribution shards. We'll decide after reviewing the data from the first experiment.

**Comment by achave11** [comment]
- [ ] Promote everything by EOD Dec 1
- [ ] Delete `dcp10` catalogs as part of PR #3669
- [ ] Reindex w/ just dcp1 and dcp11 catalogs in place (this will be the base line)
- [ ] Change shard settings as described above date TBD
- [ ] Reindex again date TBD

**Comment by hannes-ucsc** [comment]
For demo, show the collected data for the baseline reindex and the modified reindex.

**Comment by achave11** [comment]
@hannes-ucsc It seems like the [Prod Dashboard](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=azul-prod;start=PT168H) already contains the requested metrics. However it'd like to confirm that what is requested in the ticket is accounted for in the existing graphs.

General observations:
First reindex lasted 11:24 hours +  19 minutes for the failed queue re-feed index. Lasting a total of 11 hours with 43 minutes.
Exp. reindex lasted 10:40 hours + 10 minutes for the failed queue re-feed index. Lasting a total of 10 hours with 50 minutes.

The first reindex seem to have provoked a faster spike to a higher avg memory pressure during reindex, lasting the duration of the reindex.
Compared to the second reindex wich had a more gradual increase towards higher memory pressure, but still relatively similar averages in the high zone.

Seems like the second reindex had approx. three times less TransportErrors than the base reindex for the contributions.
<img width="901" alt="Screen Shot 2021-12-07 at 2 26 52 PM" src="https://user-images.githubusercontent.com/19215510/145115805-3f8ac8e2-637f-4488-a0e5-bd85824283c0.png">

Whereas the aggregations only saw a 35% reduction in TransportErrors.
<img width="1257" alt="Screen Shot 2021-12-07 at 2 28 30 PM" src="https://user-images.githubusercontent.com/19215510/145116028-28cb8965-ba79-448e-9124-f90b0f7fccd9.png">

It's worth noting that on the second reindex, queue length for tallies didn't spike up as drastically as it did for the first reindex.

**Comment by achave11** [comment]
The following are snap shots of the prod-dashboard for the base reindex and experimental reindex using the same time scale, which accounts for 15 hours and 10 minutes.
**BASE REINDEX:**
<img width="1680" alt="BaseReindx1" src="https://user-images.githubusercontent.com/19215510/145270339-a5e8c68b-5c64-48e3-a4e0-a94c65011eac.png">
<img width="1680" alt="BaseReindx2" src="https://user-images.githubusercontent.com/19215510/145270357-e2e24c53-f8ba-47ab-892f-649b7323791e.png">


**EXP. REINDEX:**
<img width="1680" alt="ExpReindx1" src="https://user-images.githubusercontent.com/19215510/145270184-8016ec4b-5606-471f-a5a0-3747f67d49c4.png">
<img width="1680" alt="ExpReindx2" src="https://user-images.githubusercontent.com/19215510/145270180-356b11a9-65ea-43fa-86a2-d7e41ab73ca2.png">
