### ISSUE TITLE
Can't read from or write to the portal DB after IT interruption

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3633]
On my personal deployment, the `PortalRegistrationIntegrationTest` was interrupted at some point, without the tear down running. The interruption occurred on November 8th at around 21:44 local time. I was experiencing network issues at the time. I can tell it was interrupted because the latest version of the DB is 9.4 KB (on a successful completed test, it grows to 16.8 KB and is reset to 2 B).

The object versions table entry for the portal DB now points to a version that does not exist in S3. I don't understand how this is possible because we don't update DynamoDB until after the new version is written to S3 (we use the version included in the response from the S3 write).

The result is that any attempt to read from or write to the DB loops forever while the portal service waits for the version to appear in S3. Manual intervention (setting the DynamoDB entry to the latest version in S3) was required to reset the DB to a functional state.

At the very least, we should probably develop a means to forcibly overwrite the DB without invoking the CRUD loop to escape from these situations. I would expect the `reset_portal_db` script to help under these circumstances but it hangs just like everything else.

**Comment by hannes-ucsc** [comment]
Portal registration is [deprecated](https://github.com/DataBiosphere/azul/issues/6782).
