### ISSUE TITLE
Sum cell_suspension.total_estimated_cells instead of tracking distinct values 

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#366]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-237)
┆Project Name: azul
┆Issue Number: AZUL-237

**Comment by achave11** [comment]
@hannes-ucsc to provide a description.

**Comment by hannes-ucsc** [comment]
Obsoleted by #433
