### ISSUE TITLE
Timeout aggregating batch of tallies for Tabula Muris

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3660]
Note that entity `e0009214-c0a0-4a7b-96e2-d6a83e966ce0` occurs with two tallies, one from dcp10 and another from dcp11. We know that a single tally can be aggregated separately, however when the batch has more than one tally for the same problematic entity it's likely to time out.
 

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-indexer-prod-aggregate_retry  
start-time: -3600s  
end-time: 0s  
query-string:
```
fields @timestamp, @message
#|filter @message like 'dcp11/projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0'
|filter @requestId like '69ccbed6-0cce-518d-8f91-e4c466f41607'
|filter @message not like 'GET'
#|filter @message like 'Deferring'
#| filter @message like 'Attempt'
#|filter @message like 'Aggregating'
#|filter @message like 'Successfully wrote'
| sort @timestamp desc

```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|       @timestamp        |                                                                                      @message                                                                                      |
|-------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 2021-11-20 03:24:21.139 | END RequestId: 69ccbed6-0cce-518d-8f91-e4c466f41607                                                                                                                                |
| 2021-11-20 03:24:21.139 | REPORT RequestId: 69ccbed6-0cce-518d-8f91-e4c466f41607 Duration: 600100.72 ms Billed Duration: 600000 ms Memory Size: 6500 MB Max Memory Used: 5434 MB Init Duration: 1582.75 ms   |
| 2021-11-20 03:24:21.139 | 2021-11-20T03:24:21.139Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Task timed out after 600.10 seconds                                                                                  |
| 2021-11-20 03:14:21.257 | [INFO] 2021-11-20T03:14:21.257Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Reading 250474 expected contribution(s) using scan().                                                         |
| 2021-11-20 03:14:21.102 | [INFO] 2021-11-20T03:14:21.102Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Found credentials in environment variables.                                                                   |
| 2021-11-20 03:14:21.063 | [INFO] 2021-11-20T03:14:21.063Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Found credentials in environment variables.                                                                   |
| 2021-11-20 03:14:21.050 | [DEBUG] 2021-11-20T03:14:21.050Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Creating ES client [search-azul-index-prod-mjluewlvxikvhillefxotw2tbm.us-east-1.es.amazonaws.com:443]        |
| 2021-11-20 03:14:21.041 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/bf81aeed-e549-4e6e-9581-ca9af9275014                       |
| 2021-11-20 03:14:21.041 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/c74bc166-98a9-46f9-806e-fca6f96a801e                       |
| 2021-11-20 03:14:21.041 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/c843b6de-caaa-4c13-828e-b6687acdab60                       |
| 2021-11-20 03:14:21.041 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/ee38fc45-bde7-4a0f-a7bd-401ea2776c77                       |
| 2021-11-20 03:14:21.041 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/f78c6cb2-257a-4556-8610-865998360a01                       |
| 2021-11-20 03:14:21.041 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 39 contribution(s) to entity dcp10/projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0                  |
| 2021-11-20 03:14:21.041 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 50745 contribution(s) to entity dcp11/projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0               |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.039Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/989c1ac3-63fc-470d-b7cf-c312198b3fbb            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.039Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/a657cb88-2847-483f-a1c0-1cc26e49937e            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/aa7f867b-f2b3-4ede-ac47-feafb6f4f55b            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/bf81aeed-e549-4e6e-9581-ca9af9275014            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/c74bc166-98a9-46f9-806e-fca6f96a801e            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/c843b6de-caaa-4c13-828e-b6687acdab60            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/ee38fc45-bde7-4a0f-a7bd-401ea2776c77            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 1 contribution(s) for entity dcp1/files/f78c6cb2-257a-4556-8610-865998360a01            |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 39 contribution(s) for entity dcp10/projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0       |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Attempt 1 of handling 50745 contribution(s) for entity dcp11/projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0    |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/989c1ac3-63fc-470d-b7cf-c312198b3fbb                       |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/a657cb88-2847-483f-a1c0-1cc26e49937e                       |
| 2021-11-20 03:14:21.040 | [INFO] 2021-11-20T03:14:21.040Z 69ccbed6-0cce-518d-8f91-e4c466f41607 Aggregating 1 contribution(s) to entity dcp1/files/aa7f867b-f2b3-4ede-ac47-feafb6f4f55b                       |
| 2021-11-20 03:14:21.037 | START RequestId: 69ccbed6-0cce-518d-8f91-e4c466f41607 Version: $LATEST                                                                                                             |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by amarjandu** [comment]
Potential solution would be to defer all but one tally for a single entity.

**Comment by melainalegaspi** [comment]
Moving out of Sprint due to assignee being overloaded.

**Comment by hannes-ucsc** [comment]
For demo, show logs for a problematic tally in prod. Show that reindex had fewer permanently failed tallies that needed to be refed.
