### ISSUE TITLE
Reindex can be started with non-empty queues

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3661]
It can be confusing if there are already failed notifications in the queues. During the reindex on 11/19/2021 we wasted time trying to triage duplicate messages in the retry notification queue.  These duplicate notifications were from a previous reindex where the queues were not purged after it was completed.

**Comment by amarjandu** [comment]
One option would be to include `python scripts/reindex.py list` within the GitLab `reindex` CI job, so that we have a record of queue length prior to the reindex being started.

**Comment by danielsotirhos** [comment]
@hannes-ucsc : "Default behavior should be for reindexing to fail right away when there are any messages in the queues.  The user should have to override the default (e.g. `make force_reindex`)"

**Comment by danielsotirhos** [comment]
@amarjandu to rephrase title & description so that it reflects the actual problem and doesn't assume a solution.

**Comment by hannes-ucsc** [comment]
Merging with #2433. See https://github.com/DataBiosphere/azul/issues/2433#issuecomment-2556102778 on why.
