### ISSUE TITLE
Index additional projects to `prod2`

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3667]
Ten additional projects snapshots have been cut for indexing into `prod2` see the `prod migration` sheet in https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1813930149 for list of snapshots.

Discussion Thread: https://humancellatlas.slack.com/archives/C01360XN04S/p1637690329147200

**Comment by danielsotirhos** [comment]
@hannes-ucsc : "Snapshot names will change to include the `dcp1` qualifier in the dataset name."

**Comment by amarjandu** [comment]
@aherbst-broad has updated the 10 snapshots in the spreadsheet.

**Comment by theathorn** [comment]
@hannes-ucsc : "Please file PR against prod branch - note that deployment is prod2 not prod, so all deployment actions are performed from the operator's personal machine. No backport necessary."

**Comment by hannes-ucsc** [comment]
For demo, show the ten projects in the dcp1 catalog using the `/index/projects` endpoint of prod2.
