### ISSUE TITLE
API Gateway request log does not include full resource path

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3668]
![image](https://user-images.githubusercontent.com/5143256/143310232-06e27747-1a4e-47e3-9895-b4be66b16cff.png)

Expected: a concrete file UUID should be listed in `resourcePath`

Actual: The `{file_uuid}` is listed.

**Comment by hannes-ucsc** [comment]
It's possible that #3497 takes care of this but we need to make sure. In the current form the logs are more or less useless.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Assignee to determine if #3497 addresses this. If not, we need to re-triage."

**Comment by achave11** [comment]
It appears as though applying the patch in #3497 solves this issue, and the full requested path (including the `file_uuid`) is logged.
![Screen Shot 2021-12-15 at 10 14 51 AM](https://user-images.githubusercontent.com/19215510/146242388-c7c6d0c2-8677-4ccf-a0c3-447658ed36e5.png)

**Comment by theathorn** [comment]
Dup of #3497.
