### ISSUE TITLE
Understand AnVIL CMG and CDDG data models

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3677]
..and how they relate to the HCA data model and metadata schema.
Documents: [CMG](https://docs.google.com/spreadsheets/d/1-cBRCHQfzDTlpJj5PMrIT_xJglsIupwMzWm97XFhouM) and [CDDG](https://docs.google.com/spreadsheets/d/1_hN_9hbPSF_gjmkQCvbobOP4G8oPVcJBbvRzMRk8fRA).

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "Decided to study the data model as we go while implementing the repository plugin for AnVIL workspaces."
