### ISSUE TITLE
Bundle contributions to specimens are not currently updatable

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#368]
When aggregating over `total_estimated_cells` in specimens in order to obtain the total number of cells in the azul `specimens` index and a given specimen contains multiple bundle contributions, the specimen will aggregate an incorrect number of cell counts. This is because the aggregates do not distinguish between the multiple bundles contributing to the specimen. Therefore adding the exact same field ('total_estimated_cells') however many times there is bundles contributing to that specimen.

The expected behavior is to have only one specimen contribution per bundle, and update the specimen based on how recent the contributing bundle is. Therefore, the bundles with a more recent version would have precedence over the others, and thereby allowing the specimen to update to the most recent properties.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-238)
┆Project Name: azul
┆Issue Number: AZUL-238

**Comment by achave11** [comment]
@hannes-ucsc if it requires further explaining or corrections please feel free to add them, or suggest them to me. Otherwise, assign the ticket back to me.

**Comment by theathorn** [comment]
Fixed by PR #433 for #391.
