### ISSUE TITLE
Unregistered users should have same access as anonymous ones

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3680]
An unregistered user is one with a Google account that has not been registered in SAM. A request with the token of an unregistered user should yield the same response as the same request without a token.

Currently, unregistered users see a 401 response:
![Screenshot from 2022-01-14 17-41-30](https://user-images.githubusercontent.com/48401926/149604120-55c148ad-77d4-4023-837c-82d08bfd58a5.png)
:

**Comment by hannes-ucsc** [comment]
Not sure if we can determine from the list snapshot response whether a user is registered or not.

**Comment by theathorn** [comment]
@noah-aviel-dove : "Currently unregistered users see a 401 response".
@hannes-ucsc : "Use this 401 response to fall back to the public service account".

**Comment by melainalegaspi** [comment]
Spike to determine impact on users (how likely are users to end up in this state and for how long).

**Comment by theathorn** [comment]
Per this [comment](https://github.com/HumanCellAtlas/data-browser/issues/1844#issuecomment-885277661) the Data Browser checks for logged-in-but-not-registered-with-Terra users and redirects them to a Terra registration process.

What response is acceptable for programmatic users?

**Comment by melainalegaspi** [comment]
Spike to reproduce with the swagger UI. Spike again for estimate.

**Comment by noah-aviel-dove** [comment]
After clicking "Authorize" and selecting an unregistered email address
![Screenshot from 2022-01-14 17-41-30](https://user-images.githubusercontent.com/48401926/149604120-55c148ad-77d4-4023-837c-82d08bfd58a5.png)
:

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Reproduction looks good. We should fix this by making sure that authenticated but unregistered (with Terra SAM) users have the same access as anonymous ones."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce via Swagger UI as in description above, and with Data Browser UI. If the Data Browser assumes registration we may need to file a follow-up ticket against it. If it somehow forces registration by redirecting to Terra after log in, that would be OK.
