### ISSUE TITLE
Cloudwatch `azul-prod` dashboard is missing data

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3699]
- `Shards` graph has no data for `Primary` or `Replica`
- `JVM Memory Pressure` graph is empty
- `JVM garbage collection time` is empty

![Screen Shot 2021-12-16 at 1 10 36 PM](https://user-images.githubusercontent.com/46407464/146449534-8dfc3ddc-93b7-49d0-9310-91d6a25edfc5.png)

**Comment by hannes-ucsc** [comment]
Fixed. The recent ES software update replaced all the nodes.

![image](https://user-images.githubusercontent.com/5143256/146472464-62334fcc-e1cf-4fea-9cb7-2842b1bfe827.png)
