### ISSUE TITLE
Check for S3 bucket existence and exception handling (persistent BDBag)

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#37]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-29)
┆Project Name: azul
┆Issue Number: AZUL-29
┆Epic: Epic 8: “Handoff” From Portal to Workspace

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

PR opened at [https://github.com/DataBiosphere/azul/pull/269](https://github.com/DataBiosphere/azul/pull/269).
