### ISSUE TITLE
Indexing dcp12 snapshot requires 900 instead of 300 slots

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3707]
Follow-up from https://github.com/DataBiosphere/azul/issues/3703#issuecomment-999196861

Indexing the dcp12 snapshot requires three times more slots to get the same throughput from BQ as the last reindex of the dcp11 snapshot. The first dcp12 reindex done by @danielsotirhos showed a 2.5 slowdown. A repeated attempt to reindex initially showed the same slowdown but throughput increased to expected levels after buying 600 more slots (900 in total).

![image](https://user-images.githubusercontent.com/5143256/147176437-f34af336-bfaf-4763-90c8-b6f0465e77d5.png)

The above dashboard screenshot shows three reindex operations. One for dcp11 and two for dcp12 (in that order). The first dcp12 reindex took at least twice as long as the dcp11 reindex. Both used 300 slots. When refeeding failed notifications after the first dcp12 reindex, no slots were active, hence the large number of presumed slot-hours. The second dcp12 reindex started with 300 slots, which was then bumped to 600 and 900 within a couple of hours into the reindex.

Only with 900 slots was query throughput in the same ballpark as the dcp11 reindex with 300 slots.

**Comment by hannes-ucsc** [comment]
I think we may actually need 1200 slots to be fully on par.

**Comment by hannes-ucsc** [comment]
I will initiate a dcp11 reindex with 300 slots now in order to determine if this issue is specific to a TDR snapshot.

**Comment by hannes-ucsc** [comment]
The dcp11 reindex has the same throughput as the previous dcp11 reindex, both using just 300 slot.

![image](https://user-images.githubusercontent.com/5143256/147280639-8cb80a0d-3db6-4dd4-aaeb-429cb9bf6d9c.png)
![image](https://user-images.githubusercontent.com/5143256/147280736-0146f02e-d99f-4eee-8d33-f4b917571e5c.png)

This seems to be specific to the dcp12 snapshot.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to discuss with the Broad.

**Comment by hannes-ucsc** [comment]
@noah-aviel-dove (operator) to determine BQ slot usage per query shape for the dcp12 (12/20/2021) and dcp11 (12/22/2021) reindex.

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=azul-prod;start=2021-12-20T08:00:00Z;end=2021-12-24T07:59:59Z

It might help to study the distinction between actual and presumed slot usage in the *BQ slot-hours (pro-rated)* graph on the prod dashboard. Essentially we need these two metrics, but for each query shape separately. It can be a CW metric graph like the one in the dashboard, but does not have to be.

**Comment by noah-aviel-dove** [comment]
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=azul-prod-3707-slot-usage-by-query-shape;start=2021-12-20T00:08:00Z;end=2021-12-24T07:59:59Z

**Comment by noah-aviel-dove** [comment]
@noah-aviel-dove to breakdown slot usage for finding the upstream bundles by project ID for the DCP12 and DCP11 reindex (12/20-12/24). Additionally, look at one actual instance of this query (for the same subgraph), from a project other than `5b328561-4a97-40ac-b7ad-6a90fc59d374` and compare job statistics between the two reindexes.

**Comment by noah-aviel-dove** [comment]
I could not find any subgraphs with dangling inputs that were indexed during both the DCP11 reindex and the DCP12 reindex.

**Comment by noah-aviel-dove** [comment]
Break down by project reveals that `5b328561-4a97-40ac-b7ad-6a90fc59d374` (https://github.com/DataBiosphere/azul/issues/3705) is the culprit. Queries from this project consumed >71,0000 actual slots (99.97% of total for finding upstream subgraphs) and >400 presumed slots (100% of total for finding upstream subgraphs) during this reindex. The project has 408 subgraphs, 403 of which made queries to find upstream bundles. However, a total of 3,110 notifications were received for subgraphs from this project over the course of the reindex, 3,099 of which ran queries to find upstream bundles.

**Comment by noah-aviel-dove** [comment]
Need to re-index DCP12 since Hannes's hotfix consolidating the queries to find the upstream bundles was only in place for the re-feeding of failed notifications, not the whole reindex.

**Comment by noah-aviel-dove** [comment]
> I could not find any subgraphs with dangling inputs that were indexed during both the DCP11 reindex and the DCP12 reindex.

Revisit this.

**Comment by noah-aviel-dove** [comment]
With the upstream bundle query consolidation in place, the DCP12 reindex completed in just over 8 hours with 300 slots. There were four transient failed notifications (all succeeded after the first re-feeding). There were no failed tallies.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Still waiting for @noah-aviel-dove to determine why he wasn't able to find subgraphs with dangling inputs, something Hannes was surprised by."

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc : "too much time has passed, we lost context. closing."
