### ISSUE TITLE
Instructions for upgrading GitLab in the operator manual are incomplete

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3709]
1. These instructions are specific to the `dev` instance and omit the `prod` instance:

> _select dev.gitlab
cd terraform/gitlab
make apply

> It may be necessary to set CI_COMMIT_REF_NAME=develop to work around check_branch.

2. I think there ought to be a first step telling the operator to checkout and update the `develop` or `prod` branch respectively before editing the terraform files.

3. There are no instructions for opening a PR.

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "We suspect that @amarjandu wrote the original section. He should also review @noah-aviel-dove 's improvements."

**Comment by noah-aviel-dove** [comment]
GitLab and GitLab runner are updated separately. Upgrade GitLab to the latest version and the update GitLab runner to the latest compatible version (i.e. the major and minor versions should be the same).

**Comment by noah-aviel-dove** [comment]
Decided at PL it would be better to address these changes as part of https://github.com/DataBiosphere/azul/pull/3627

**Comment by noah-aviel-dove** [comment]
I was mistaken about the `prod` branch. Since PR's are filed against dev there's no need to rebase on prof or set the commit ref var to reference it.
