### ISSUE TITLE
Obtain Google Cloud CRM package

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3711]
CRM = Customer Responsibility Matrix

**Comment by danielsotirhos** [comment]
- https://cloud.google.com/security/compliance/nist800-53/ contains a list of "Google Cloud services that are in scope for NIST 800-53".
- https://cloud.google.com/security/compliance/fedramp contains a `FedRAMP templates` download link. The zip file download contains the file `FedRAMP Moderate Security Controls Guide - Google Cloud Implementation Reference .xlsx`, and a CRM can be found on the `Moderate Baseline Controls` tab.

![Screen Shot 2022-01-04 at 2 15 37 PM](https://user-images.githubusercontent.com/46407464/148132124-42175572-e941-442b-b092-9cedbe09bce3.png)
