### ISSUE TITLE
Clean-up branches

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3716]
- [x] `github/issues/3542-consolidate-tdr-requests` Invalid name, @noah-aviel-dove
- [x] `github/issues/baladithyab/2170-maketesthang` Only draft PR, @baladithyab
- [ ] `github/issues/noah-aviel-3302-access-control-manifest` Invalid name, @noah-aviel-dove
- [x] `github/issues/noah-aviel-dove/2399-portal-crud-s3-overload` No PR, @noah-aviel-dove
- [x] `github/issues/noah-aviel-dove/2405-migrate-azul-dev` No PR, @noah-aviel-dove
- [x] `github/issues/noah-aviel-dove/2540-subgraph-stitching-fail-supp-files-2` No PR, @noah-aviel-dove

**Comment by noah-aviel-dove** [comment]
Deleting or renaming `github/issues/noah-aviel-3302-access-control-manifest ` would close https://github.com/DataBiosphere/azul/pull/3309

**Comment by baladithyab** [comment]
@hannes-ucsc Open PR for #2170

**Comment by hannes-ucsc** [comment]
Sorry, @baladithyab, I don't understand what you mean. Please use complete sentences in GitHub communication.

I see that you removed the draft status from PR #3624 so I assume that you intended to leave that PR open and don't want the branch deleted.
