### ISSUE TITLE
Operator manual is wrong for backports

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3718]
1. Merge instructions in operator manual are incorrect (merging should be done by clicking `merge` button in Github)
2. Some of the operator checklist items don't apply, e.g. rebasing the branch on `develop`

**Comment by noah-aviel-dove** [comment]
This might be addressed by the blocking ticket. Re-triage after it lands.

**Comment by hannes-ucsc** [comment]
Re-triaging.

**Comment by melainalegaspi** [comment]
@noah-aviel-dove to verify that this still is a valid issue.

**Comment by noah-aviel-dove** [comment]
Re-re-triaging based on PR feedback.

**Comment by noah-aviel-dove** [comment]
https://github.com/DataBiosphere/azul/pull/4020#pullrequestreview-928503323

Renders the first bullet in the description invalid. There's nothing else to do.
