### ISSUE TITLE
Remove code that supports the bagit-FC-lambda-based export to FC

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#372]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-242)
┆Project Name: azul
┆Issue Number: AZUL-242

**Comment by mjkrause** [comment]
done long time ago

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

This has been addressed by https://ucsc-cgl.atlassian.net/browse/TLP-560.
