### ISSUE TITLE
Update prod promotion doc to clarify vagueness

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3722]
From retro 12/17/2021.

**Comment by melainalegaspi** [comment]
@danielsotirhos to fill in details.

**Comment by danielsotirhos** [comment]
Not an issue. The "Promoting to prod" section of the [Operator document](https://github.com/DataBiosphere/azul/blob/develop/OPERATOR.rst#promoting-to-prod) is sufficient.
