### ISSUE TITLE
Index additional dcp1 projects to `prod2`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3724]
[Slack thread](https://humancellatlas.slack.com/archives/C01360XN04S/p1641581925002600?thread_ts=1641323990.260200&cid=C01360XN04S).

From @aherbst-broad : The [snapshots sheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1813930149) has been updated with the remainder of the dcp1 snapshots that are not blocked on the file ingestion issue referenced above. I added a divider to indicate the new batch.

**Comment by hannes-ucsc** [comment]
For demo, post comment with terminal transcript of running a `curl` command to request against projects endpoint of prod2 instance, counting the projects before and after deployment of the change. Show the two comments during demo.

**Comment by noah-aviel-dove** [comment]
```
$ curl -X GET 'https://service.azul2.data.humancellatlas.org/index/projects?catalog=dcp1' | jq .pagination.total
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  116k  100  116k    0     0  49178      0  0:00:02  0:00:02 --:--:-- 49157
10
```

**Comment by noah-aviel-dove** [comment]
```
$ curl -X GET 'https://service.azul2.data.humancellatlas.org/index/projects?catalog=dcp1' | jq .pagination.total
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  130k  100  130k    0     0  59037      0  0:00:02  0:00:02 --:--:-- 59063
22
```
