### ISSUE TITLE
Consolidate inner entity limits

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#3725]
Consolidate the inner entity limits (accumulator `max_size`) set by the aggregators, and refactor to replace the hard coded values with a config value (e.g. `config.max_num_inner_entities`)

**Comment by hannes-ucsc** [comment]
See also #3248 for where overly large limits cause an issue and #6648 where we're adding a warning when accumulators drop values.

**Comment by hannes-ucsc** [comment]
Accumulator overflows are now being addressed in #6793. The objective of avoiding overflow may conflict with the objective to keep project aggregates small (#3248). Not sure. We'll close this issue as superseded by #6793 and leave #3248 open as a separate, but potentially contradictory, issue.
