### ISSUE TITLE
Manifest fetches ES results in too many small pages

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3737]
I have the feeling that this 

https://github.com/DataBiosphere/azul/blob/f63d0cdd2f956b9fc051b12ec03b09e58dac2013/src/azul/service/manifest_service.py#L1005

and this

https://github.com/DataBiosphere/azul/blob/f63d0cdd2f956b9fc051b12ec03b09e58dac2013/src/azul/service/elasticsearch_service.py#L426

have the effect that no `size` request parameter is being applied at all, causing the default page size of 10 to be used, resulting in poor performance because two orders of magnitude more ES requests are made than would be optimal. 

Needs to be verified, though, and reproduction added.

**Comment by melainalegaspi** [comment]
Spike to verify.

**Comment by achave11** [comment]
@hannes-ucsc: "What @achave11  posted is clear evidence that we are in fact using an inefficient page size of ten."

**Comment by melainalegaspi** [comment]
@achave11 to spike again to confirm that we currently use page size of 10 for Avro PFB.

**Comment by achave11** [comment]
By looking at the number of ES request (116) and the number of files entries (115,168 round up to nearest thousand 116000), we can determine that each ES response results in 1,000 entries. Meaning that [this bug](https://github.com/DataBiosphere/azul/issues/3737) does not affect the `avro` manifest format.
<img width="1274" alt="Screen Shot 2022-01-24 at 3 08 18 PM" src="https://user-images.githubusercontent.com/19215510/150880225-784f3d31-dc57-4623-afac-f6c35bdbeb95.png">
<img width="1660" alt="Screen Shot 2022-01-24 at 3 08 37 PM" src="https://user-images.githubusercontent.com/19215510/150880918-2165a4de-b13e-422a-b10b-4e56a5f619c9.png">

**Comment by melainalegaspi** [comment]
@hannes-ucsc to evaluate @achave11's findings.

**Comment by hannes-ucsc** [comment]
Good work.

**Comment by hannes-ucsc** [comment]
For demo, attempt to [reproduce](https://github.com/DataBiosphere/azul/issues/3737#issuecomment-1011687969).
