### ISSUE TITLE
LungMAP Data Browser gets error handing-off BdBag manifest to Terra 

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3741]
Handing over fastq files for [this project](https://data-browser.lungmap.net/explore/projects/00f056f2-73ff-43ac-97ff-69ca10e38c89) results in the following error displayed by the Terra UI.

![image](https://user-images.githubusercontent.com/5143256/149219058-50c5d128-3897-42c5-98a7-6d3407444807.png)

To reproduce: In LungMAP Data Browser select project "Genomic, epigenomic, and biophysical cues controlling the emergence of the lung alveolus", "File Format = fastq.gz", "Export Selected Data", "Analyze in Terra", "Download Format = terra.bdbag".

Full error:

```
{
  "causes": [],
  "message": "java.lang.ArrayIndexOutOfBoundsException - Index 1024 out of bounds for length 1024\nParser Configuration: CsvParserSettings:\n\tAuto configuration enabled=true\n\tAuto-closing enabled=true\n\tAutodetect column delimiter=false\n\tAutodetect quotes=false\n\tColumn reordering enabled=true\n\tDelimiters for detection=null\n\tEmpty value=\n\tEscape unquoted values=false\n\tHeader extraction enabled=null\n\tHeaders=null\n\tIgnore leading whitespaces=true\n\tIgnore leading whitespaces in quotes=false\n\tIgnore trailing whitespaces=true\n\tIgnore trailing whitespaces in quotes=false\n\tInput buffer size=1048576\n\tInput reading on separate thread=true\n\tKeep escape sequences=false\n\tKeep quotes=false\n\tLength of content displayed on error=-1\n\tLine separator detection enabled=true\n\tMaximum number of characters per column=16384\n\tMaximum number of columns=1024\n\tNormalize escaped line separators=true\n\tNull value=\n\tNumber of records to read=all\n\tProcessor=none\n\tRestricting data in exceptions=false\n\tRowProcessor error handler=null\n\tSelected fields=none\n\tSkip bits as whitespace=true\n\tSkip empty lines=true\n\tUnescaped quote handling=nullFormat configuration:\n\tCsvFormat:\n\t\tComment character=#\n\t\tField delimiter=\\t\n\t\tLine separator (normalized)=\\n\n\t\tLine separator sequence=\\n\n\t\tQuote character=\"\n\t\tQuote escape character=\"\n\t\tQuote escape escape character=null\nInternal state when error was thrown: line=0, column=1025, record=0, charIndex=31370",
  "source": "FireCloud",
  "stackTrace": [],
  "statusCode": 400,
  "timestamp": 1642004829281
}
```

**Comment by theathorn** [comment]
Related to #2442?

**Comment by melainalegaspi** [comment]
Spike to identify if the cause is in the manifest. If so, identify what the cause is. Otherwise, we'll re-triage and reach out to the Terra team.

**Comment by hannes-ucsc** [comment]
The manifest being handed over:

[participants.tsv.txt](https://github.com/DataBiosphere/azul/files/7857788/participants.tsv.txt)

The same manifest transposed (columns are rows and vice versa):

[participants-transposed.tsv.txt](https://github.com/DataBiosphere/azul/files/7857789/participants-transposed.tsv.txt)

**Comment by hannes-ucsc** [comment]
The manifest has one row and 1838 columns. For historic reasons, the BDBag manifest has one row per subgraph (formerly known as bundle) and a group of columns per data file. There are 46 triplets (read1, read2 and index) of fastq files in the subgraph  leading to 138 files in total, and 13 columns per file. It seems that the large number of columns is tripping a limit in Terra.

Possible solutions (mixing long and short term, and in no particular order of preference):

1) Relax the column number limit in Terra
2) Reduce the number of files being handed over (roughly by half)
3) Rewrite the metadata to create one primary subgraph per fastq triplet
4) Use AvroPFB handover
5) Add a BDBag flavor that has one row per triplet

**Comment by davidangb** [comment]
>  It seems that the large number of columns is tripping a limit in Terra.

This is correct. Terra has a safety limit of 1024 columns when importing TSVs; as you noted, this import has 1838 columns in its participants table, so Terra is rejecting it (we could do a better job on providing a helpful error message!).

Because BDBag contains TSV(s), this limit is in effect; PFB works because PFB does not use the TSV code path at all.

If you have a way to restructure the incoming data to reduce the number of columns, that would work around the error, and be fully under your control. Otherwise, we can look to increase the column limit. As the data experts - are you aware of any other datasets/use cases that have large numbers of columns like this? Do you have a recommendation as to what a more appropriate column limit would be?

**Comment by theathorn** [comment]
Here is the current plan, courtesy of Tim Tickle:
1. Given PFB is already in progress and is also needed for other projects, we can delay the demo for the PFB work to happen.
2. I can evaluate the PFB hand-off at that point and if it passes review we could deprecate BDBag for LungMAP (they seem like duplicate functionality and PFB looks better at a quick glance).
3. If after seeing the PFB work, BDBag is still needed we can engage the CCHMC team on graph changes. From what I have heard, changes in the graph do not affect the PFB hand-off but if that is true please let me know.

The "PFB work" is #3689.
