### ISSUE TITLE
GitLab volume `/dev/sda1` is not tagged

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3747]
The volume `/dev/sda1` that is attached to the `gitlab-dev` instance is not tagged. It's at risk for deletion by the deletion daemon.

Redacted some info on the screen shot, was not sure how much was OK to expose.
![Screen Shot 2022-01-13 at 9.29.39 AM.png](https://images.zenhubusercontent.com/5bfc94ffa6759a229d994558/61ab72fa-5f82-4516-b651-4edc60c8f68e)

**Comment by theathorn** [comment]
@hannes-ucsc : "Assignee to ask Erich if automatically created root volumes of otherwise correctly tagged EC2 instances need to also be tagged"

**Comment by amarjandu** [comment]
Might be possible to add tags with https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#volume_tags

**Comment by amarjandu** [comment]
Erich requested that we tag the volumes to ensure its accounted for correctly in the Cost Reporting.

Forwarded the email to Hannes.

**Comment by hannes-ucsc** [comment]
The "deletion daemon" is not used on our accounts anymore. The FedRAMP inventory (#4003) takes its place.
