### ISSUE TITLE
Index more dcp2 projects to `prod2`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3752]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1813930149) rows 24-224

**Comment by melainalegaspi** [comment]
@hannes-ucsc to create blocker about giving prod2 a separate ES instance.

**Comment by hannes-ucsc** [comment]
Blocker was promoted last Friday (ZH column doesn't reflect that yet). We can start working on this now.

**Comment by amarjandu** [comment]
The issue mentions `dcp2`, the snapshot name has references to both `dcp2` and `dcp12` for rows 24-216.
However there is no `dcp2` catalog in in the `prod2` configuration, there is `dcp1` and `dcp10`. Which catalog in `prod2` should these snapshots be added to?

**Comment by hannes-ucsc** [comment]
The catalog name should be `dcp12`. The string `dcp2` in the snapshot name is the dataset qualifier. The `dcp10` catalog can be removed from `prod2`.

**Comment by theathorn** [comment]
From Jeff Korte: "The rest of the snapshots have been added to the sheet".

**Comment by hannes-ucsc** [comment]
For demo, show that dcp12 catalog in prod2 has 195 projects.

**Comment by amarjandu** [comment]
Removed the two dcp1 sources row 217 and row 218, added row 220

**Comment by amarjandu** [comment]
Added row 217 and 218 to the `dcp1` catalog. see https://github.com/DataBiosphere/azul/pull/3783#discussion_r798985447
