### ISSUE TITLE
Give `prod2` its own ES instance

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3757]
As snapshots are accumulating, we need to move `prod2` to its own ES instance. This should only be needed for a few weeks.

**Comment by theathorn** [comment]
@hannes-ucsc : "Don't forget to delete the prod2 indices from the prod ES instance afterwards"

**Comment by hannes-ucsc** [comment]
For demo, show instance. Make a request to the Azul service index endpoints on prod2 to show that instance is populated. Show that the old indices were removed from the prod instance.
