### ISSUE TITLE
ITS HIPAA Training

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3760]
[ITS HIPAA Training](https://its.ucsc.edu/security/training/hipaa.html)

It appears that the single Learning Center course [Health Care Privacy Training (previously HIPPA)](https://uc.sumtotal.host/rcore/c/search?context=activity&isDeepLink=1&isFromSuggestion=0&originalSearchText=hipaa&searchTerm=hipaa) has replaced the two previous courses.

**Comment by theathorn** [comment]
From UCSC ITS:

Thank you for contacting the ITS Support Center! Yes those courses were combined into a single course. You can access the single HIPAA course using the following link:

[HEALTH CARE PRIVACY TRAINING (PREVIOUSLY HIPPA)](https://uc.sumtotal.host/core/pillarRedirect?relyingParty=LM&url=app/management/LMS_ActDetails.aspx?ActivityId=135225&UserMode=0&domain=18)

**Comment by hannes-ucsc** [comment]
Took the training.

**Comment by hannes-ucsc** [comment]
There is no option to generate a certificate. I took a screenshot of the training site which proves I took the training.

**Comment by hannes-ucsc** [comment]
Uploaded screenshot to designated folder.
