### ISSUE TITLE
NIH Security Training

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3763]
[Security Training and Awareness Appendix 1](https://docs.google.com/document/d/18_UoOkT84AlbMrovhnV93aNjjlsv7SAkw3InZdmUeQc)

Per the [Data Access](https://ucsc-cgl.atlassian.net/wiki/spaces/DEV/pages/1774714882/Data+Access) requirements, Complete the [NIH INFORMATION SECURITY AND INFORMATION MANAGEMENT TRAINING COURSES](https://irtsectraining.nih.gov/publicUser.aspx) and then sign the [NIH Genomic Data Sharing Policy Agreement](https://giwiki.gi.ucsc.edu/images/1/1b/NIH_GDS_Policy.pdf).

  - [dbGaP APPROVED USER CODE OF CONDUCT](https://dbgap.ncbi.nlm.nih.gov/aa/GWAS_Code_of_Conduct.html)
  - [NIH Security Best Practices for Controlled-Access Data Subject to the NIH Genomic Data Sharing (GDS) Policy](https://osp.od.nih.gov/wp-content/uploads/NIH_Best_Practices_for_Controlled-Access_Data_Subject_to_the_NIH_GDS_Policy.pdf)
  - [National Institutes of Health Genomic Data Sharing Policy](https://giwiki.gi.ucsc.edu/images/1/1b/NIH_GDS_Policy.pdf)

Quizzes to complete:
  - [dbGaP Code of Conduct quiz](https://www.surveymonkey.com/r/HKXNYD7)
  - [NIH Security Best Practices for (CAD) Subject to NIH (GDS) Policy quiz](https://www.surveymonkey.com/r/FG3C63T)

**Comment by hannes-ucsc** [comment]
Took all the prescribed courses. I have certificates for three of the courses. The other courses didn't offer the option to create a certificate.

**Comment by hannes-ucsc** [comment]
Certificates and signed agreement uploaded to designated folder.

**Comment by theathorn** [comment]
In this folder:
  - [NIH_GDS_Policy_Sig_form_100918-signed.pdf](https://drive.google.com/file/d/1mkwlFrjZqkv7uSOxajfVyzYmH8dIFB24/view?usp=sharing)
  - [NIH INFORMATION MANAGEMENT AWARENESS TRAINING.pdf](https://drive.google.com/file/d/1dG3DYw6JaxauVM0snz4fjsRaepqPaQEn/view?usp=sharing)
  - [NIH INFORMATION MANAGEMENT AWARENESS TRAINING 2.pdf](https://drive.google.com/file/d/1Yn5WI73WSZ5B41UIfXAoiOwEplGP8uw4/view?usp=sharing)
  - [NIH Information Security and Management Awareness Refresher.pdf](https://drive.google.com/file/d/1bpBqQZhmCPrYhUNdqBND-rgGv4ZNFj5j/view?usp=sharing)
  - [NIH Secure Remote Computing.pdf](https://drive.google.com/file/d/1bkxyrP92mDZjmzfKyrZJSBVL2KBMguSC/view?usp=sharing)

**Comment by theathorn** [comment]
@hannes-ucsc to complete the 2 quizzes (at the foot of the description) and place the results [here](https://drive.google.com/drive/folders/1k6Kbx_exn190V_8uq9cpHh4i0cJQ2vNI).
