### ISSUE TITLE
`prod2` IT subgraph partitioning fails to locate bundles

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3767]
Cannot consistently get an IT to pass on `prod2`, see two test runs https://gitlab.dev.singlecell.gi.ucsc.edu/-/snippets/23#LC923 .

Note: The lack of indexed projects in the new ES instance caused a health check failure as well, this will go away once the reindex is complete.

**Comment by noah-aviel-dove** [comment]
Looks like we'll need to manually override the default common prefix for one or more snapshots. This saved query may be helpful in that regard: 
https://console.cloud.google.com/bigquery?sq=713613812354:b3c46f2c6ac94b9680da62fc7a9903e4
It lists the number of subgraphs per prefix for a given snapshot. The prefix length can be changed by commenting/uncommenting more lines like the ones that are commented out.

**Comment by hannes-ucsc** [comment]
For demo, show IT passing with `prod2` selected.
