### ISSUE TITLE
Switch to TDR new prod

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3782]

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"There will be more snapshots to index into prod2. Leaving this in Triage for now."

**Comment by hannes-ucsc** [comment]
1) Request a full dump of the projects endpoint response for `dcp12` on both deployments. Do textual comparison between the two using `diff`. The resulting patch should be empty. Do the same for the summary endpoint. Generate a compact manifest for all files in the `dcp12` catalog on both deployments. Compare the two manifests. The diff should be empty.

   If the patch between two artifacts is not empty but only contains insignificant differences, apply the necessary transformations (sorting, filtering) and repeat the comparison on the transformed artifacts. Document all steps taken in this ticket, including a shell transcript.

2) Wait until https://github.com/DataBiosphere/azul/issues/3843 lands in `prod2`

3) Repeat step 1 for `dcp13`

4) Port the relevant configuration from the `prod2` to `prod` (TDR and SAM urls, sources for all catalogs). This will replace the list of sources for the `dcp1`, `dcp12` and `dcp13` catalogs. File a PR for that.

5) Perform a promotion consisting only of the changes from that PR.

6) Manually destroy the `prod2` deployment.

7)  File another PR to remove the `prod2` deployment from the source.

**Comment by hannes-ucsc** [comment]
Note that we can and should perform step 1 while we wait for the blocker #3843.

**Comment by hannes-ucsc** [comment]
` for c in dcp{1,12,13}; do for d in '' 2; do curl https://service.azul$d.data.humancellatlas.org/repository/sources?catalog=$c | jq > sources-$c-prod$d.json; done ; done`

**Comment by hannes-ucsc** [comment]
`for c in dcp{1,12,13}; do for d in '' 2; do curl https://service.azul$d.data.humancellatlas.org/index/summary?catalog=$c | jq > summary-$c-prod$d.json; done ; done`
