### ISSUE TITLE
Unassigned shards during `prod` reindex

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3798]
The most recent reindex on `prod` (the first one using ES 7.0) had unassigned primary contribution shards.  

`GET /_cluster/allocation/explain?pretty` gave `failed to obtain in-memory shard lock` as the reason.

We should consider the possibility that automatic snapshots were the culprit. The ES domain was new, so naturally, snapshots would have been enabled again by default. I sent a support request to have them disabled. `GET _cat/snapshots/cs-automated`, however, returned no snapshots at all. It is possible that a snapshot was attempted, a shard lock was acquired for a long time during that attempt, but then the attempt ultimately failed. The held lock might have caused the five consecutive shard allocation attempts to fail as well.

Increasing the `index.allocation.max_retries` to 10 as described ob [this AWS support article](https://aws.amazon.com/premiumsupport/knowledge-center/opensearch-in-memory-shard-lock/) resolved the issue.

We should repeat the reindex with snapshots definitely disabled and if the problem occurs again, we should set a higher number of allocation retries on every index at creation time, I'm thinking, 10 and observe if this improves things for a few reindex operations.

**Comment by theathorn** [comment]
Spike to repeat re-index now that snapshots are disabled in prod.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Re-index did not produce unassigned shards. We will not increase the number of shard assignment attempts. @hannes-ucsc  to update this ticket with details on any documentation updates needed."

**Comment by amarjandu** [comment]
10 tallies fail to be indexed when refeed into the tallies-retry queue

See [here](https://gitlab.dev.singlecell.gi.ucsc.edu/-/snippets/25) for notifications that were sent to be refeed into the system.

Failures can be observed in cloudwatch insights linked [here](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E$25272022-01-31T20*3a20*3a39.389Z$257Estart$257E$25272022-01-31T18*3a46*3a56.793Z$257EtimeType$257E$2527ABSOLUTE$257Etz$257E$2527Local$257EeditorString$257E$2527fields*20*40timestamp*2c*20*40message*0a*7c*20sort*20*40timestamp*20desc*0a$257EisLiveTail$257Efalse$257EqueryId$257E$2527b4ba021b-f886-4e4d-9a5e-98072348318a$257Esource$257E$2528$257E$2527*2faws*2flambda*2fazul-indexer-prod-aggregate_retry$2529$2529)

Refeed for the 10 tallies occurred at ~10:50am pst on 2022-01-31.

**Comment by amarjandu** [comment]
All 10 tallies were able to be refeed into the system by refeeding them one at a time and having a 3-5 min delay between each refeed.

9 of them were indexed on the first retry, 1 [tally](https://gitlab.dev.singlecell.gi.ucsc.edu/-/snippets/26) emitted the ES error linked above, but was reindexed on its second retry.

**Comment by hannes-ucsc** [comment]
Document in operator manual that (from description)

> Increasing the index.allocation.max_retries to 10 as described ob this AWS support article resolved the issue.

This is the only method for kicking off shard allocation that works on AWS OpenSearch. The other methods are explicitly disallowed by Amazon.

Also document that the only scenario in which we've seen unassigned shards is when automatic snapshots were disabled.

Also document that after the creation of an ES domain, we need to manually request the disabling of snapshots.

**Comment by hannes-ucsc** [comment]
The easiest way to change that settings is in Cerebro.

**Comment by hannes-ucsc** [comment]
Docs are here https://github.com/DataBiosphere/azul/blob/develop/OPERATOR.rst#reindexing
