### ISSUE TITLE
Disable snapshots on all `platform-hca-dev` ES domains

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3799]
I filed a support request for `platform-hca-prod`, cc'ing `azul-group`. We need to do the same for all domains in `platform-hca-dev`.

**Comment by amarjandu** [comment]
Created support request for Azul ES instances in `platform-hca-dev`.
https://console.aws.amazon.com/support/home?#/case/?displayId=9547431521&language=en

**Comment by amarjandu** [comment]
AWS service rep turned off the snapshots for `dev` and `sandbox`. Confirmed date of last snapshot being on the 29th of Jan. See linked AWS support thread for more details.

**Comment by hannes-ucsc** [comment]
For demo, show -1 start hour in domains in AWS console.
