### ISSUE TITLE
Prototype repo plugin for AnVIL workspaces in Terra

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3804]
@hannes-ucsc:

> Write a plugin that extracts the workspace attributes and populates the project index.
>
> We've also established that we CAN actually access the workspaces from outside of Terra.

**Comment by hannes-ucsc** [comment]
The most minimal implementation would return the project title and the dbgap study accession.

I'm sure there will be a few hurdles along the path. The first one is to get the assignee's service account permission to access the AnVIL workspaces.

**Comment by theathorn** [comment]
@bethsheets suggests [here](https://docs.google.com/document/d/1U6_owoTdTOCe6ZCTMBk-hkUGZa_TIkTqN5UsMsQVSTA/edit#heading=h.w60wsch1u2qu) starting with 1000 Genomes.

**Comment by hannes-ucsc** [comment]
For this, we'll include information from all workspaces. The AnVIL Dataset Catalog already displays this information publicly, so evidently, the information we are indexing for this is not managed-access.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Unfortunately the Azul on AnVIL project has changed the requirements considerably: we won't be indexing Terra workspace tables anymore but index TDR snapshots that follow TIM."
