### ISSUE TITLE
Document feeding tallies individually

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3805]
This technique should be used to slowly feed problematic tallies into the indexer.

See Slack thread for more information https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1643737644045259?thread_ts=1643735864.856479&cid=C705Y6G9Z

**Comment by amarjandu** [comment]
Breaking down the list of tallies into smaller individual files (one message per file) can introduce a human error into the refeeding. It might be worth adding a `--delayed` flag that sends one message at a time, with an added delay, this allows and operator to use the file produced by the `dump_all` without modification. 

https://github.com/DataBiosphere/azul/blob/033849644d67f2554c37cc64d6f74cb1b6ead2ec/src/azul/queues.py#L278

**Comment by theathorn** [comment]
Obsoleted by #3660 - closing.
