### ISSUE TITLE
ES domains stuck at "Preparing to process updates"

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3809]
![image](https://user-images.githubusercontent.com/5143256/152079983-1a793885-2927-4cdd-ac27-a918a0d86170.png)

Why does it say `Preparing to process updates: 0%` if the service software version is already the latest?

**Comment by hannes-ucsc** [comment]
File support ticket with AWS.

**Comment by achave11** [comment]
A support ticket was [filed with AWS](https://console.aws.amazon.com/support/home#/case/?displayId=9590301681&language=en).

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Assignee to answer any questions AWS support might have and to follow-up with any fixes that might be needed on our end."

**Comment by achave11** [comment]
Paraphrasing AWS' response, the message had to do with a false positive and we were getting the false impression that the update was still in progress. The false positive message was manually intervened by the AWS team, and is no longer an issue.
![Screen Shot 2022-02-15 at 11 27 33 AM](https://user-images.githubusercontent.com/19215510/154134600-0bf325a9-b465-4151-a343-577a847d7252.png)

**Comment by achave11** [comment]
Support ticket submitted for `dev` account. https://console.aws.amazon.com/support/home#/case/?displayId=9650070881&language=en

**Comment by achave11** [comment]
AWS support replied with a solution to the problem "… please make a small change in Access policy for your domain and save and then revert back to old Access policy and it should solve the false 'Preparing to process updates' progress status.". After performing the suggested solution the false positive message disappeared. AWS is working on rolling out a bug-fix but is still in the makings.

**Comment by theathorn** [comment]
@hannes-ucsc : "Please provide screenshots for dev and sandbox".

**Comment by achave11** [comment]
Message has been removed after applying AWS' suggestion.
<img width="1017" alt="Screen Shot 2022-02-28 at 9 19 54 AM" src="https://user-images.githubusercontent.com/19215510/156028598-3e78ccc7-7f17-43d9-a0b5-8b80d9acc6a0.png">
