### ISSUE TITLE
Plugin-ify the service response population

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3817]
We've encapsulate the indexer machinery into the HCA metadata plugin but that only covers the indexer code paths. The service code paths hard-code assumption about the index document structure. The assumption will break on Anvil, because the Anvil data model is just too different from the HCA one.

Remove the JSONObject stuff and move the service response generation bits into the plugin.

This might need to be converted into an epic with smaller subtasks. We won't know until we start going down this road.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to fill in details.

**Comment by hannes-ucsc** [comment]
For demo, walk team through the refactoring (stages, chains) and the underlying design patterns.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :" @noah-aviel-dove is working on a PR that plugin-ifies the remaining hard coded HCA specifics."

**Comment by melainalegaspi** [comment]
@hannes-ucsc  "Remaining work covered by #4349."

**Comment by hannes-ucsc** [comment]
We either forgot to demo this, or, if we actually demoed it, to label it correctly as `demoed`. It's too late now.
