### ISSUE TITLE
EC2 instances for GitLab are incorrectly named

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3820]
The GitLab instances are missing the deployment stage within their tags and names.
Currently they are configured as `azul-gitlab` but they should be `azul-gitlab-dev` | `azul-gitlab-prod`

<img width="877" alt="Screen Shot 2022-02-03 at 3 45 46 PM" src="https://user-images.githubusercontent.com/1947534/152448127-09f91443-fef1-4dd3-950b-6b9ee8731df2.png">

see discussion:
https://github.com/DataBiosphere/azul/pull/3627#discussion_r785127251

**Comment by amarjandu** [comment]
Consider adding a method to `azul.config` that produces the correct EC2 instance `KeyName` for a deployment something like:

```
def gitlab_keyname():
   return 'gitlab-azul-prod' if self.deployment_stage is 'prod' else 'azul-gitlab-dev'
```

This will make it easier to create the correct filter in `scripts/create_gitlab_snapshots.create_snapshot`

**Comment by hannes-ucsc** [comment]
I changed my mind on this. There can only be one GitLab instance per AWS account. Including a deployment name in the account would falsely indicate the opposite. This applies to the snapshot and volume names, too.
