### ISSUE TITLE
Wranglers to provide study and cohort UUIDs as workspace attributes

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3826]
@hannes-ucsc:

> An Anvil *cohort* can be described by the following tuple:
> 
> 1) dbGap study accession
> 2) Consent code
> 3) Optional: tranche name
> 
> The tranche name is a string. It may refer to the name of the submitting lab or that of a sample collection site. Not all studies are split into tranches but all studies use at least one consent code. If a study has tranches, the tranche name must be present in all cohort tuples with the same study accession.
> 
> Common sense data modelling recommendations discourage the use of properties with real world meaning in a primary key. While such properties generally satisfy uniqueness constraints, they don't satisfy the stability constraint for private keys. Someone could have made a mistake entering the tranche name, used the wrong study, or the consent code may need to be changed over time.
> 
> IOW, we need to identify studies and cohorts using opaque, stable and globally unique identifiers i.e. UUIDs. Wranglers will populate all Anvil workspaces with these two UUIDs. The Azul team can help with tooling to get that started. The tooling would need to be able to extract the chort version and the elements of the cohort tuple from each workspace, either its name or its attributes. Wranglers need to ensure that future workspaces are tagged with study and chort UUIDs from the get go.
> 
> There can be multiple Terra workspaces per cohort. These workspaces represent different *versions* of the cohort. The workspace for version v2 of a cohort is a clone of the v1 workspace. Its workspace tables contain a complete, but updated copy of the tables in the corresponding v1 workspace (where updates could mean added or modified rows). The v2 workspace bucket contains only the data files added in v2. IOW, some of the table rows in the v2 workspace will refer to files in the v1 bucket. If a v3 workspace is created, a table row in that workspace could refer to a file in the v3 bucket or any of the buckets backing the preceding versions.
> 
> The Azul metadata plugin for Anvil will allocate exactly one project entity per study, and use the study UUID as the project UUID. The terms study and project are usually considered synonyms, anyways.
> 
> The Azul catalog for Anvil will allocate one source per cohort. If there are multiple versions of the cohort, the Azul catalog will reference only one of them. The source ID will be the Terra workspace ID, not the cohort UUID. 
> 
> Spike: TBD: When workspaces are cloned, will its attributes and tags be copied?
> 
> TBD: The exact name of the workspace tags to hold the study and cohort IDs. `study_id` and `chohort_id`?

**Comment by melainalegaspi** [comment]
@theathorn to add this to next AnVIL meeting agenda so @hannes-ucsc can discuss with Beth.

**Comment by theathorn** [comment]
@hannes-ucsc to fill in details.

**Comment by bethsheets** [comment]
I just tested that when cloning a workspace, dataset attributes (the readme), workspace tags, data tables, and inherited authorization domains are carried over. The workspace name with the cohort ID is suggested to be carried over (<workspace_name>_copy), but not required. The billing project can be but is likely not carried over. What other attributes do you rely on?

Can you clarify if you are suggesting:
cohort UUID
Represents data provided in a single Terra workspace. A workspace is broken down by dbGAP accession number, consent code, tranche (representing sequencing/submitting lab and any versioning). 

project UUID = study UUID
This UUID represents multiple cohort UUIDs that are connected via a dbGAP accession. For example: The dbGAP accession phs001766  (https://anvilproject.org/data/studies/phs001766) is represented by two workspaces in AnVIL/Terra listed at the bottom of the page.

Deliverable: Azul team to provide UUID generator tooling for both cohort and project/study UUIDs. Wranglers will generate each UUID. Wranglers will add cohort UUID to the workspace as a tag.

But where does the project/study UUID fit in?

**Comment by bethsheets** [comment]
Goal: Azul needs a definition of a "project" that can be represented as a UUID. This definition of project means a row in the data browser project's tab (which is the top-level).

**Comment by hannes-ucsc** [comment]
Given the A-TIM politics, I'm going to park this for now.

**Comment by hannes-ucsc** [comment]
BI will wrangle. This is obsolete.
