### ISSUE TITLE
Verify source spec at indexing time

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3827]
See https://github.com/DataBiosphere/azul/issues/3525#issuecomment-1031937534

@hannes-ucsc : "We'll remove the `verify_source` method altogether to solve this issue. At a later time, we'll add it back but implement it by looking up the source by ID, synthesizing the name from that response, and compare the result against the spec. Furthermore, the current call to `verify_source` occurs way too early. Ideally we would do it when the bundle notification is about to be processed."

**Comment by melainalegaspi** [comment]
@hannes-ucsc to fill in details.

**Comment by hannes-ucsc** [comment]
It turns out that https://github.com/DataBiosphere/azul/issues/3827 was a bad call on my part. It's quickly overloading TDR if we do this for every bundle.

**Comment by hannes-ucsc** [comment]
We'll back it out with https://github.com/DataBiosphere/azul/pull/4376
