### ISSUE TITLE
Obtain program name and project name from top-level metadata

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#383]
The `program` value is hardcoded to the value `TOPMed` and now we
are loading data from other programs, so the `program` value needs to be
obtained from the metadata.

Also, the `project` value is obtained from nested metadata values,
yet obtaining it from a top-level metadata value will make it more consistent with 
the `program` value and provide more convenient control of 
the `project` value going forward.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-247)
┆Project Name: azul
┆Issue Number: AZUL-247

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
