### ISSUE TITLE
Index `dcp13` in `prod2`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3843]
1) Copy the list of sources for the `dcp12` catalog in that deployment to a new `dcp13` catalog.

2) Add the snapshot reference for new projects. The project UUID minus dashes is in each snapshot name.

3) Update snapshots references for updated projects.

**Comment by theathorn** [comment]
Andrew Herbst confirms that all current projects are now in "new prod". 
i.e. "new prod" is up to date and in sync with the "old prod" dcp13 catalog.

**Comment by hannes-ucsc** [comment]
Starting at row 225 in https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1813930149

**Comment by hannes-ucsc** [comment]
@achave11, issues don't get the `reindex` label
