### ISSUE TITLE
GitLab `test` job ran abnormally long in prod

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#3844]
The `test` job in GitLab `prod` ran abnormally long. Initially after [35:22 min](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/16141) of running, the job was canceled and [restart](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/16149). The re-run ran equally as long, but succeeded without intervention. The canceled job would have potentially ran to completion since the logs of the cancelled job was making progress in its execution [according to the logs](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/16141/raw). In the former and the restart job logs …
```
Launching sibling container from image docker.elastic.co/elasticsearch/elasticsearch:7.10.1
2022-02-11 00:09:03,698 INFO    MainThread: Launched sibling container ~container_name~ from image docker.elastic.co/elasticsearch/elasticsearch:7.10.1, listening on 172.17.0.3:9200
2022-02-11 00:09:19,881 INFO    MainThread: It took *s for ES container to boot up
```
… the ES containers took upwards of 400 seconds to boot up.

**Comment by theathorn** [comment]
Spike to further determine the cause of the extended run time and to verify the hypothesis that the container startup is the cause.

**Comment by achave11** [comment]
The [last build](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/6567) for prod running the test job in 23 minutes is from Aug 9, 2021. The time that the ES container took to set up isn't logged.

The [following promotion](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/6699) and thereafter pipelines in GitLab run the test job in 30+ min. The time that the ES container took to set up isn't logged.

This increase in execution time for the test job is also visible in the `dev` GitLab instance. However there are more frequent outliers of test jobs that run in the low to mid 20s in dev.
The set of changes in https://github.com/DataBiosphere/azul/commit/667c3425cf8b45965cf6c12501cb4c403112141b (prod promotion) included several test additions and enhacements that can justify the test job's time increase.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Continue spike to useGitLab API to record the test job duration over the last 3 months."

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Cancelling the spike because this isn't currently affecting us too much."

**Comment by hannes-ucsc** [comment]
Didn't happen again. See #2653 and #6770 for unit tests being slow in general.
