### ISSUE TITLE
Script to copy bundles between deployments

### ISSUE THREAD

**Issue by alex-hancock** [DataBiosphere/azul#386]
Production, staging, and integration deployments have a paucity of diversity. It would be good to have the ability to download bundles on one deployment and upload them to another deployment. 

Ideally, this would take the form of a CLI that takes three parameters:
1. A source URL
2. A destination URL
3. An ES Query to run against the source to declare what should be copied

(See Mallory's message about specific Project UUID's for the pilot. copy from staging to integration as a test run)

Implementation note: Python script - bindings in the HCA CLI - POST search request for bundles from source, for-each bundle:
download bundle to local disk
PUT file for each bundle in file (or use upload bundle)

Possible optimization after demo: start uploading first bundle while downloading second bundle

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-250)
┆Project Name: azul
┆Issue Number: AZUL-250

**Comment by achave11** [comment]
@hannes-ucsc @jessebrennan @danielsotirhos this is the long term solution agreed on for addressing failures in Azul integration deployment.
