### ISSUE TITLE
Consolidate source definitions in `environment.py` for `prod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3870]
Once PR #3867 for #3843 lands, the list of sources for the `dcp12` and `dcp13` catalogs will be somewhat duplicative. It's also very easy to end up with two or sources for the same project since nothing currently enforces that constraint.

Track the sources for each catalog in a dictionary. Start with the dictionary for the `dcp12` catalog. Once that dictionary is populated, copy it for the `dcp13` catalog and add the `dcp13`-specfic sources. When adding an entry, parse the source to extract the project UUID and use that as the key. Use the source as the value. Add the entries in order of project ID. Add an assertion to ensure that key order in the final dictionary satisfies that ordering constraint.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to close, this is now obsolete.

**Comment by hannes-ucsc** [comment]
This was inadvertently fixed in 4e2037a1
