### ISSUE TITLE
Remove source hashing from portal database keys

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3874]
Currently the S3 object key of the portal database is calculated the MD5 hash of all sources in the [default](https://github.com/DataBiosphere/azul/issues/2716) catalog. This causes a new object to be created whenever the source configuration changes. We should just use the catalog name instead.

**Comment by hannes-ucsc** [comment]
Portal registration is [deprecated](https://github.com/DataBiosphere/azul/issues/6782).
