### ISSUE TITLE
GitLab IT job failed by exceeding the execution time allowed

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3877]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/39380
The job exceeded the maximum execution time set for the job when the index test produced upwards of 17784 notifications to index, this amount is unusually high. The last three IT test in GitLab `dev` logged a max of [484](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/39322/raw), [96](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/39260/raw), [96](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/39238/raw), notifications indexed by `test_index`.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "This is superseded by moving #2789 into In Progress and reverting the corresponding changes."
