### ISSUE TITLE
IT in GitLab prod fails due to AssertionError

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3880]
Multiple sub tests in [IT failed](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/16450) with same assertion error.
```
AssertionError: 513+ not less than or equal to 512 : Partition … of source tdr:broad-… is too large
```

**Comment by achave11** [comment]
It appears like https://github.com/DataBiosphere/azul/pull/3583 introduced the regression.
https://github.com/DataBiosphere/azul/blame/develop/test/integration_test.py#L276
We overlooked `prod` upper bound of sub-graphs per snapshot.

**Comment by theathorn** [comment]
Hot fix to target prod, then re-triage.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "This is superseded by moving #2789 into In Progress and reverting the corresponding changes.
