### ISSUE TITLE
Managed access IT subtest is too large

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3893]
@hannes-ucsc: "[_test_managed_access is getting too big. We should break it up into methods and sub tests where possible.](https://github.com/DataBiosphere/azul/pull/3694#discussion_r814154730)"

**Comment by hannes-ucsc** [comment]
For demo, insert `assert False` in one of the extracted methods. Run IT and show that another extracted method, one that is in a subsequent subtest, still passes.
