### ISSUE TITLE
Create pre-signed URL pointing to S3-bucket

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#39]
Part of persisting the BDBag so FireCloud can import it from a pre-signed URL.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-31)
┆Project Name: azul
┆Issue Number: AZUL-31
┆Epic: Epic 8: “Handoff” From Portal to Workspace

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

PR opened at [https://github.com/DataBiosphere/azul/pull/269](https://github.com/DataBiosphere/azul/pull/269).
