### ISSUE TITLE
Diagram for logging and monitoring

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3901]

**Comment by hannes-ucsc** [comment]
@danielsotirhos to post link to diagram

**Comment by danielsotirhos** [comment]
https://lucid.app/lucidchart/5a362477-88dc-418d-9fd5-ce2f7612a0c7/edit?page=3CPXQFUVPoyg

![Logging   Monitoring](https://user-images.githubusercontent.com/46407464/156635987-54aaa752-3024-4623-9bf5-91a4d10807bf.jpg)
