### ISSUE TITLE
Delete `prod2`

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3907]
@hannes-ucsc : "We cant go forward with this until we are sure we wont need to switch back to TDR-old-prod due to excessive timeouts from TDR (https://github.com/HumanCellAtlas/dcp2/issues/57)."

**Comment by amarjandu** [comment]
TF output for deletion https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/snippets/32

**Comment by hannes-ucsc** [comment]
All the manually provisioned resources need to be torn down as well.

https://github.com/DataBiosphere/azul#31-one-time-provisioning-of-shared-cloud-resources

**Comment by amarjandu** [comment]
Cleaned up layers/portal_db artifacts from `edu-ucsc-gi-azul-dcp2-prod-config.us-east-1`

**Comment by amarjandu** [comment]
No residual IAM Roles/Policies found

**Comment by amarjandu** [comment]
Route53 Hosted Zone `azul2.data.humancellatlas.org` deleted

**Comment by amarjandu** [comment]
No changes to `gitlab-prod` needed as `prod` is still in use.

**Comment by amarjandu** [comment]
No changes made to the `Google OAuth 2.0` infra;

no `azul-prod2` OAuth 2.0 client was found, no changes needed to redirect / origins for `azul-prod` OAuth 2.0 client.
