### ISSUE TITLE
Disallow `||` joiners in metadata

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3911]
Stray joiners in metadata caused #3888. We will work around those by only asserting the absence of joiners in fields when we actually need to join the fields into a TSV cell. To ensure that we don't keep accumulating stray joiners, we need to reject them at indexing time, in any property of any entity.

**Comment by achave11** [comment]
https://github.com/DataBiosphere/azul/issues/3888#issuecomment-1062182327

**Comment by achave11** [comment]
@hannes-ucsc: "Assignee to come up with sketch of solution."

**Comment by achave11** [comment]
@hannes-ucsc: "Continue spike to compare the performance of looking for the joiner in serialized JSON vs deserialized JSON"

**Comment by melainalegaspi** [comment]
Removing spike. @achave11 and @hannes-ucsc to discuss what the most simplest solution would be.

**Comment by achave11** [comment]
parking lot:
Benchmark the Bundle constructor with and without the call to the recursive method that disallows double pipe. Repeat with all applications open (as it is now) and from terminal with only that app open.

**Comment by hannes-ucsc** [comment]
That hints at two observations: that this benchmark is affected by system utilization and that the impact of the recursive approach to detecting a substring in JSON is > 10%, which is where I drew the line. To speed this up, we're just going to rely on my intuition (without evidence) that a string search *before* deserialization will be orders of magnitude faster. We'll implement that latter approach for all three repository plugins (`canned`, `tdr` and `dss`).

**Comment by achave11** [comment]
@hannes-ucsc: "It turns out that for DSS the HCA client library already deserializes metadata files to JSON. It would be hard to get in front of that so we will omit the requirement for DSS."

**Comment by achave11** [comment]
The requirement for `canned` will be addressed in https://github.com/databiosphere/azul/issues/4063.

**Comment by danielsotirhos** [comment]
For demo, show that a recent reindex on prod did not produce a `RequirementError` with the message `'||' is disallowed`

**Comment by theathorn** [comment]
As of `dcp20` there should be no remaining projects in `prod` with this issue.
For `dev` we either need to remove any affected projects from the Azul index or ask for new snapshots.

**Comment by hannes-ucsc** [comment]
@achave11 [confirms](https://github.com/HumanCellAtlas/dcp2/issues/63#issuecomment-1249824833) that the blocker has been resolved.

**Comment by hannes-ucsc** [comment]
… but we still need top copy updated snapshots from `prod` to `dev` for the projects listed in the the description under `dev`.

**Comment by dsotirho-ucsc** [comment]
Assignee to prepare a PR that :
- Adds code to each repository plugin that prevents indexing of metadata with `||` in them (should use `require` or `reject`).
- Addresses the FIXME's referring to this ticket
- Updates `dev` and `sandbox` with the seven snapshots mentioned on HumanCellAtlas/dcp2#63

@hannes-ucsc: "I think in earlier experiments @achave11 established that a simple lookup of the offending string in serialized JSON is faster than first deserializing it and performing a recursive search of all string values in it. The former is what we should use here."

**Comment by achave11-ucsc** [comment]
>…earlier experiments @achave11 established that a simple lookup…

This is all I found to that end, it will still need to be replicated in the other plugins.
```
Index: src/azul/plugins/repository/tdr_hca/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/repository/tdr_hca/__init__.py b/src/azul/plugins/repository/tdr_hca/__init__.py
--- a/src/azul/plugins/repository/tdr_hca/__init__.py	(revision aeef62ea475e11d62e7e446bd89f0247da5d552c)
+++ b/src/azul/plugins/repository/tdr_hca/__init__.py	(date 1676495896281)
@@ -35,6 +35,7 @@
     JSON,
     RequirementError,
     config,
+    reject,
     require,
 )
 from azul.bigquery import (
@@ -290,7 +291,9 @@
             for fqid in links_ids
         }
         for links_json in links.values():
-            links_json['content'] = json.loads(links_json['content'])
+            content = links_json['content']
+            reject("||" in content, "'||' is disallowed", content)
+            links_json['content'] = json.loads(content)
         return links
 
     def _retrieve_entities(self,

```
And the [closed PR](https://github.com/DataBiosphere/azul/pull/4264/files) reverting the changes that caused issues.

**Comment by hannes-ucsc** [comment]
No demo needed, a successful reindex will show the validity of this change and the metadata in the new snapshots.
