### ISSUE TITLE
PFB manifest contains invalid values for organism_age

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3913]
Reproduction steps:
  - Go to https://data-browser.lungmap.net/explore/projects
  - Click on the checkbox next to "Genomic, epigenomic, and biophysical cues controlling the emergence of the lung alveolus" (project_uuid=00f056f2-73ff-43ac-97ff-69ca10e38c89)
  - Click on "Export Selected Data"
  - Click on "Analyze in Terra"
  - Click on "Confirm Species"
  - Click on "Select All" and "terra.pfb"
  - Click on "Request Link"
  - Click on the generated link; Terra will open in a new browser window
  - Create a workspace in Terra (app.terra.bio) and wait for the import to finish
  - In "TABLES" click on "donors" and scroll to the "pfb:organism_age" column
  - Note the "[object Object]" entries

LungMAP "Terra Workspace" / "Analyze in Terra" for [this project](https://data-browser.lungmap.net/explore/projects/00f056f2-73ff-43ac-97ff-69ca10e38c89):

![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/be8a9dc9-70f4-4d14-b478-e4e40419b98b)

..results in "[object Object]" values for "pfb:organism_age" in "Donors" tab:

![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/ebb35f76-1031-4b0c-b911-43367c9dc544)

**Comment by theathorn** [comment]
Spike to ask on #terra-handoff channel if Avro/PFB supports arrays of nested objects.

**Comment by melainalegaspi** [comment]
@theathorn to file dcp2 blocker with reproduction.

**Comment by theathorn** [comment]
Asked David An for next steps in [this Slack thread](https://humancellatlas.slack.com/archives/CEYRYE9C1/p1646257420084599).

**Comment by davidangb** [comment]
fix is in progress at DataBiosphere/terra-ui#2872. The Broad Jira ticket number is AJ-341, if anyone needs that.

**Comment by theathorn** [comment]
Looks OK:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/ced3f109-c8f9-4800-b07e-539e2cf9c235)
