### ISSUE TITLE
Trailing comma in "pfb: organism_age_unit" of "donors" table

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3914]
There's a trailing comma after "day" in row 6 (same "Analyze in Terra" hand-off as in #3913):

![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/271d7fdc-8642-4ea3-9c3c-40072896dd56)

**Comment by bvizzier-ucsc** [comment]
@hannes-ucsc : "Made obsolete by: https://github.com/DataBiosphere/azul/issues/2693"
