### ISSUE TITLE
Final URL to managed access manifests is broken

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#3922]
We can include the header in the command line section of the response, but the clickable link in the browser needs a way to provide authentication. Currently users that click the link will see a 410 response if they requested the manifest while logged in with an account that has access to managed-access metadata.

To reproduce, log into [the dev instance of the data browser](https://dev.singlecell.gi.ucsc.edu/explore/projects?filter=%5B%7B%22facetName%22:%22genusSpecies%22,%22terms%22:%5B%22Homo%20sapiens%22%5D%7D%5D) with an account that has access to the managed access sources. Filter by file format and select `pdf`. As of 3/07/2022 there are 14 such files. Request a file manifest and click on the download link. 

![Screenshot from 2022-03-07 23-23-08](https://user-images.githubusercontent.com/48401926/157187143-34d58cf9-a5dc-4d0d-b815-0aa95de187b7.png)

The link leads to Azul's `/manifest/files` endpoint which responds with a 410 error.

![Screenshot from 2022-03-07 23-23-32](https://user-images.githubusercontent.com/48401926/157187157-985efbe3-c480-47a2-80cd-a1a41c90026b.png)

If the link is copied and used to make cURL request with OAuth access token included the header, the manifest is successfully downloaded.

**Comment by melainalegaspi** [comment]
@noah-aviel-dove to add reproduction to description.

**Comment by melainalegaspi** [comment]
Related to #2301.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Re-triage to determine current progress and decide if this can be postponed in favor of AnVIL/June 1st deliverables."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
