### ISSUE TITLE
Fill in role details in security architecture doc

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3935]
[Security and Privacy Controls for the UCSC Genomics Institute Data Browser](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0)

**Comment by hannes-ucsc** [comment]
I just did this as part of my work on #4429.

**Comment by hannes-ucsc** [comment]
All role details have been filled in and the corresponding TODO comments resolved.
