### ISSUE TITLE
Restructure the security architecture doc

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3936]
[Security and Privacy Controls for the UCSC Genomics Institute Data Browser](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0)

It was meant to be a part of compliance documentation but it can now be converted to a team internal policy.

**Comment by hannes-ucsc** [comment]
Repurposed the document as the security architecture.

**Comment by hannes-ucsc** [comment]
Repurposed the document as the security architecture.
