### ISSUE TITLE
Index LungMAP snapshots from TDR "new prod" into `prod`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3937]
Index the snapshots in the "lm1" column of this [Spreadsheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1910294292).

**Comment by hannes-ucsc** [comment]
For demo, show projects endpoint for lungmap catalog in prod.
