### ISSUE TITLE
Index LungMAP release 2 in `prod`

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#3939]
From https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1910294292

Index all projects in the "lm2" column into an "lm2" catalog.

**Comment by amarjandu** [comment]
For Triage: Should we create a `lm2` catalog?

**Comment by theathorn** [comment]
The above snapshot (lungmap_prod_00f056f273ff43ac97ff69ca10e38c89__20220308_20220314_lm2) has been provided.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "To answer @amarjandu's question: yes we need a new lm2 catalog. The existing `lungmap` catalog should not be renamed because doing so would break the data browser."
