### ISSUE TITLE
Can PyPI packages & Docker/AMI images be digitally signed?

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3948]
CM-5(3) ACCESS RESTRICTIONS FOR CHANGE | SIGNED COMPONENTS 
The information system prevents the installation of [Assignment: organization-defined software and firmware components] without verification that the component has been digitally signed using a certificate that is recognized and approved by the organization.

**Comment by hannes-ucsc** [comment]
For Docker images, there is https://docs.docker.com/engine/security/trust/ but most of the images we use aren't signed.

For PyPI there is [PEP 458](https://peps.python.org/pep-0458) and [480](https://peps.python.org/pep-0480/). The latter is a draft while the former is accepted but [has not been implemented yet](https://github.com/pypa/pip/issues/8585).
