### ISSUE TITLE
Index snapshots with phantom files into `lm2` on prod

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3957]
Essentially, undo afacb8b2 ~~but in lm3 not lm2~~.

[Snapshots Spreadsheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1910294292).

**Comment by hannes-ucsc** [comment]
Spike to verify that the files are indeed [phantom files](https://github.com/databiosphere/azul/issues/3956), what the the value of the `drs_uri` property is in all file descriptors in those two projects. If it is set to a non-null value, then we'll have to rethink the blocking relationship between these tickets.

**Comment by noah-aviel-dove** [comment]
For the projects `datarepo-73453de6.lungmap_prod_20037472ea1d4ddb9cd356a11a6f0f76__20220307_20220310_lm2` and `datarepo-df6004c2.lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220311_lm2`:

 - All sequence files are phantoms (111 total)
 - No analysis files are phantoms (70 total)
 - There are no reference files, supplementary files, or image files (0 total)

Query:
```
with all_files as (
    select * from `datarepo-73453de6.lungmap_prod_20037472ea1d4ddb9cd356a11a6f0f76__20220307_20220310_lm2.sequence_file`
    union all
    select * from `datarepo-df6004c2.lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220311_lm2.sequence_file`
)
select count(*) as count_
from all_files
where file_id is null
```

Result:

`{  "count_": "111"}`
