### ISSUE TITLE
Prevent automatic ES service software upgrades

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#3959]
Apparently, the `prod` domain was updated automatically right before the promotion yesterday. It caused all nodes to be replaced. It would be disastrous if such an update happened *during* a reindex.

**Comment by theathorn** [comment]
Spike to investigate why AWS starting doing this and if it can be prevented.

**Comment by achave11** [comment]
From https://docs.aws.amazon.com/opensearch-service/latest/developerguide/service-software.html

"If you take no action on required updates, OpenSearch Service still updates your domain service software automatically after a certain timeframe (typically two weeks)."
Additionally it seems like there is no info or options regarding the disabling of these updates. Rather they provide us with two weeks as buffer for managing the service software update at our own convenience.

**Comment by hannes-ucsc** [comment]
Hmm, OK. When we have the monitoring controls in place, we will need to hook up the update notification on the ES domain with our Slack channel. It looks like the route is going to be ES => EventBridge => SNS => AWS ChatBot => Slack.

In the short term, we need to update the operator manual to check daily for ES service updates in prod, and to create a ticket for each scheduled update. The ticket should contain the due date and time by the the update will be applied automatically. That we can have some control over when these updates are applied.

**Comment by amarjandu** [comment]
https://github.com/DataBiosphere/azul/issues/3978#issuecomment-1081042687

**Comment by achave11** [comment]
parking lot:

- [ ] Operator instructions to include:
        * Weekly checks for OS service instance updates.
        * Only high priority (update) notifications include the deadline (two weeks from date of notification) in the title.
        * High pri. notification updates get assigned as high priority in ZH board.
        * All domains to be checked; notifications are all included in a single ticket. (Deadline in title if notification is high pri.)
