### ISSUE TITLE
Keep GitLab instances updated

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3962]
Regularly update the OS by running `yum update` and update the AMI when we update the GitLab and ClamAV docker images.

**Comment by nolunwa** [comment]
@theathorn this should not be assigned to be.

Gap: how do we identify outdated OS patches with AWS

**Comment by melainalegaspi** [comment]
Triage during Thursday 10 a.m. compliance meeting.

**Comment by theathorn** [comment]
@hannes-ucsc :"Discussed in triage. I now understand the control. I need to specify our implementation for it (periodically run `yum update; yum upgrade` or equivalent).

**Comment by hannes-ucsc** [comment]
We will implement this as follows: 

1) We will have Slack reminders to run `yum update` as documented here:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-updates.html

2) We will have a monthly reminder to check for an updated AMI. This will also take care of updating the SSM Agent that comes preinstalled on Amazon Linux 2 AMIs. WIthout that we would need a separate reminder to [update the agent](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent-automatic-updates.html).

**Comment by achave11-ucsc** [comment]
Enhance Operator manual with instructions to update AMI, update to the monthly Slack reminder, and add a weekly reminder to run `yum update` on all instances.

**Comment by achave11-ucsc** [comment]
PL Items:
* Should the `…backup GitLab volumes` Slack reminder be enhanced to also include the `yum update` instructions, prior to backing up the volume.
    * Yes, first backup then yum.
* Similarly, should the Monthly `… GitLab and ClamAV updates` reminder be enhanced to include the AMI updates as well?
    * Yes, one commit and deployed together even.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Contrary to #4014, this work does not require any code changes that would have to be put in a PR. We therefore don't need to leave this ticket open as `do not close`. We did create the notification on Slack and the operator manual entry that documents the procedure. The Slack notification links to the operator manual entry."
