### ISSUE TITLE
Service should return 503 response when Terra client times out

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#3968]
https://github.com/DataBiosphere/azul/pull/3943#pullrequestreview-916449627

@hannes-ucsc : "… and ultimately a retry by the client (Data Browser). The precise mechanics of the client-side retries need to be discussed. It may be that we don't want to retry automatically but involve an action by the user. If an error is displayed to the user, it should be clear that it is transient, caused by high load and can be remedied by refreshing the page."

**Comment by danielsotirhos** [comment]
For demo: Modify personal deployment's `service` Lambda environment variables to set `AZUL_TERRA_TIMEOUT` to `01:01`. Demonstrate `503` response from endpoint and message logged in CloudWatch.

**Comment by nadove-ucsc** [comment]
There is an outstanding FIXME for this that we should review.

https://github.com/DataBiosphere/azul/blob/9b61454847ac296a56b5eb887507f9ed251a43c8/src/azul/terra.py#L357

**Comment by nadove-ucsc** [comment]
[These logs](https://github.com/DataBiosphere/azul/issues/5467#issuecomment-1692189510) indicate that the issue has indeed been resolved and that we just need to remove the FIXME comment.

**Comment by achave11-ucsc** [comment]
@nadove-ucsc: "Coincidentally, just as we unearthed this ticket we appear to have found a different code pathway where this is still an issue. Specifically, we still return a 500 response if the timeout occurs in the `/repository/files` endpoint instead of `/index/*`. Both should return 503"

https://groups.google.com/a/ucsc.edu/g/azul-group/c/-hsA5jn2Z_M/m/MLqauMxuFAAJ

```
    {
        "service_response_status": "Returning 500 response",
        "code": "DRSError",
        "msg": "
Traceback (most recent call last):
File "/var/task/chalice/app.py", line 1913, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 1470, in repository_files
result = _repository_files(file_uuid, fetch=False)
File "/var/task/app.py", line 1549, in _repository_files
return app.repository_controller.download_file(catalog=catalog,
File "/var/task/azul/service/repository_controller.py", line 232, in download_file
download.update(plugin, authentication)
File "/var/task/azul/plugins/repository/tdr.py", line 255, in update
access = drs_client.get_object(self.drs_uri, access_method=AccessMethod.gs)
File "/var/task/azul/drs.py", line 242, in get_object
return self._get_object(drs_uri, access_method)
File "/var/task/azul/drs.py", line 263, in _get_object
return self._get_object_access(drs_uri, access_id, AccessMethod.https)
File "/var/task/azul/drs.py", line 298, in _get_object_access
raise DRSError(response)
"
    },
    {
        "service_response_status": "Returning 503 response",
        "code": "ServiceUnavailableError",
        "msg": "No response from https://data.terra.bio/api/repository/v1/snapshots/roleMap within 5.0 seconds"
    },
```

**Comment by nadove-ucsc** [comment]
On 2nd thought, perhaps we should open a new ticket for the DRS Client timeout instead of re-using this one, because the DRS Client is not a Terra Client (as represented by our class hierarchy) even though it does make requests to Terra.

**Comment by dsotirho-ucsc** [comment]
Remaining work is tracked in https://github.com/DataBiosphere/azul/issues/5501
