### ISSUE TITLE
Remove 2 projects from dcp14

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3970]
From Enrique on this [Slack thread](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1647643314513959):
We have detected an error in 2 of our datasets, There's a missing value in the project_role field that makes the wrangler appear as a contributor.
Affected projects:
  - https://data.humancellatlas.org/explore/projects/40272c3b-4697-4bd4-ba3f-82fa96b9bf71?catalog=dcp14
  - https://data.humancellatlas.org/explore/projects/45c2c853-d06f-4879-957e-f1366fb5d423?catalog=dcp14

[DCP/2 Datasets and snapshots](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit#gid=1813930149) has been updated accordingly.

**Comment by hannes-ucsc** [comment]
If there is a dcp13 snapshot for either of these project (there may not be), we may need to ask for clarification on whether to delete the project or revert to the previous snapshot.

**Comment by theathorn** [comment]
These 2 projects were new to dcp14 and can simply be excluded.

**Comment by amarjandu** [comment]
These projects have been removed from `dcp14` catalog.

**Comment by amarjandu** [comment]
Proof of removal: 

https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/snippets/31

For https://data.humancellatlas.org/explore/projects/40272c3b-4697-4bd4-ba3f-82fa96b9bf71?catalog=dcp14

```
CBSEspecter:azul amar$ curl 'https://service.azul.data.humancellatlas.org/index/projects/40272c3b-4697-4bd4-ba3f-82fa96b9bf71?catalog=dcp14'
{"Code":"NotFoundError","Message":"NotFoundError: Can't find an entity in projects with an uuid, 40272c3b-4697-4bd4-ba3f-82fa96b9bf71."}
```

For https://data.humancellatlas.org/explore/projects/45c2c853-d06f-4879-957e-f1366fb5d423?catalog=dcp14

```
CBSEspecter:azul amar$ curl 'https://service.azul.data.humancellatlas.org/index/projects/45c2c853-d06f-4879-957e-f1366fb5d423?catalog=dcp14'
{"Code":"NotFoundError","Message":"NotFoundError: Can't find an entity in projects with an uuid, 45c2c853-d06f-4879-957e-f1366fb5d423."}
```
