### ISSUE TITLE
Apply OpenSearch (ES) Service Software

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#3978]
We have two weeks from 3/23/2022 to manually update the service software of the OpenSearch instances. 

- [x] Update `azul-index-dev`
- [x] Confirm with Azul devs that their personal deployments are inactive
- [x] Update `azul-index-sandbox`
- [x] Update `azul-index-prod`

**Comment by amarjandu** [comment]
@hannes-ucsc: "Turns out that the domain was updated by the deploy job on GitLab. At least according to the AWS support rep. Our assumption that informational notifications need to be handled with urgency was wrong, only high priority notifications represent mandatory service software updates. Abraham to adjust ticket accordingly."

**Comment by achave11** [comment]
Both `azul-service-dev` and `azul-index-sandbox` were updated to the latest service software version.
![Screen Shot 2022-04-15 at 2 53 23 PM](https://user-images.githubusercontent.com/19215510/163650002-8e54e60e-eee1-48ab-b24e-b7a12988e355.png)
![Screen Shot 2022-04-15 at 2 53 33 PM](https://user-images.githubusercontent.com/19215510/163650006-1ff5f7f2-466b-4850-bc71-4a51d42fac53.png)
![Screen Shot 2022-04-15 at 3 29 04 PM](https://user-images.githubusercontent.com/19215510/163650007-5cec2fd8-594b-4a27-a25d-badbb8e6179e.png)

**Comment by achave11** [comment]
`azul-index-prod` was updated to the latest service software version.
![Screen Shot 2022-04-15 at 4 02 11 PM](https://user-images.githubusercontent.com/19215510/163651145-b90136b1-748a-4ba9-bddd-c19d9ef1ed03.png)

**Comment by melainalegaspi** [comment]
@melainalegaspi to create Slack reminder to check for ES / software updates on Tuesdays 9 a.m.
