### ISSUE TITLE
Switch API Gateway from edge-optimized to regional

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#3989]
@hannes-ucsc : "AWS WAF requires that any API Gateway it fronts is regional. "

**Comment by melainalegaspi** [comment]
Spike to modify a personal deployment to use regional gateways and certificates and determine the fallout.

**Comment by danielsotirhos** [comment]
@hannes-ucsc : "Turns out the assumption that WAF requires a regional gateway is incorrect, it only requires a regional Web ACL. We prefer Edge optimized APIs because of the improved performance globally."
