### ISSUE TITLE
Give Carter Group Firewall ACLs for GitLab

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3994]
@hannes-ucsc : "For SC-7, the Carter group needs the specific firewall rules for ingress and egress traffic. Collect this information from the Terraform configuration for GitLab (security groups are Amazon's equivalent to firewall rules)."

**Comment by danielsotirhos** [comment]
https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.37m2jsg

![Screen Shot 2022-04-04 at 11 00 23 AM](https://user-images.githubusercontent.com/46407464/161603868-5c185f10-f2a9-4926-8857-e045bc279b43.png)
