### ISSUE TITLE
Sort by `Cell Count Estimate` does not correctly sort results

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#3996]
In the browser, sorting the `Projects` tab by `Cell Count Estimate` does not seem to correctly sort the results. 
![Screen Shot 2022-03-29 at 11 01 30 AM](https://user-images.githubusercontent.com/46407464/160677766-69fd73c4-7395-4de2-b5cf-842ee5098d08.png)

**Comment by danielsotirhos** [comment]
Sorting by `Cell Count Estimate` uses the sort field `effectiveCellCount` which sorts by the `max(project estimated cell count, sum(cell suspension cell counts))`, however the browser appears to only be displaying the project estimated cell count in the column.

```
$ http 'https://service.azul.data.humancellatlas.org/index/projects?filters=%7B%7D&size=25&sort=effectiveCellCount&order=desc&catalog=dcp13' | jq '.hits[] | {"id": .entryId, "pc": .projects[].estimatedCellCount, "cs": ([.cellSuspensions[].totalCells] | add)}'
{
  "id": "a9301beb-e9fa-42fe-b75c-84e8a460c733",
  "pc": 4062965,
  "cs": 4979593
}
{
  "id": "b51f49b4-0d2e-4cbd-bbd5-04cd171fc2fa",
  "pc": 4725000,
  "cs": 4725000
}
{
  "id": "091cf39b-01bc-42e5-9437-f419a66c8a45",
  "pc": 1500000,
  "cs": 1480000
}
{
  "id": "74b6d569-3b11-42ef-b6b1-a0454522b4a0",
  "pc": 1330000,
  "cs": 1330000
}
...
```

From a [comment](https://github.com/HumanCellAtlas/data-browser/issues/1867#issuecomment-952302708) on https://github.com/HumanCellAtlas/data-browser/issues/1867 :

> This assumes that the DB also uses max to chose between hits[i].cellSuspensions[*].totalCells and hits[i].project.estimatedCellCount for the column display, obviously.

**Comment by melainalegaspi** [comment]
@danielsotirhos to convert this to a data-browser ticket.

**Comment by danielsotirhos** [comment]
Created https://github.com/HumanCellAtlas/data-browser/issues/2372
