### ISSUE TITLE
Complete "Table 10-1 Ports, Protocols and Services" in SSP

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#3998]
Fill in the "10.2 Ports, Protocols and Services" table in the [Azul Data Browser FedRAMP SSP](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r).

**Comment by danielsotirhos** [comment]
https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#

![Screen Shot 2022-04-04 at 11 00 23 AM](https://user-images.githubusercontent.com/46407464/161604121-4a4b3a0a-6a8c-4ef9-8295-2f1e8850fcf2.png)

**Comment by theathorn** [comment]
@hannes-ucsc :"VPN is missing"

**Comment by danielsotirhos** [comment]
![Screen Shot 2022-04-05 at 10 09 20 AM](https://user-images.githubusercontent.com/46407464/161812229-ebccd99e-f020-401d-8f33-872493db5f85.png)

**Comment by theathorn** [comment]
UDP = User Datagram Protocol (not "Diagram").

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "It is like this in the template, not for us to fix."

**Comment by melainalegaspi** [comment]
@danielsotirhos to notify Carter Group on Slack.

**Comment by danielsotirhos** [comment]
Carter Group has been notified on Slack.
https://ucsc-gi.slack.com/archives/C02B4S0V6GH/p1649188738079809

**Comment by theathorn** [comment]
I fixed the UDP acronym in the SSP doc.
