### ISSUE TITLE
Make design design document for the Azul Indexer and Webservice

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#4]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-3)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-3
┆Epic: Azul Merge

**Comment by hannes-ucsc** [comment]
#31 (12cca0b3b9a934862877e6a181437aab4416f12d) at least partially addresses this.

@cricketsloan, could you decide if that change resolves this issue for you, and if not reopen and specify what else you would like to see here?
