### ISSUE TITLE
Add `donor_document_id` for superior accuracy on donor count

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#400]
We discover that `donor_biomatirial_id` which is the parameter that we use to display the number of different donors in our system is not unique across all the bundles in azul. Making queries on this value to obtain the different donors yields inaccurate responses.
The field `document_id` is distinct among each donor. Making it a field in the azul index as `donor_document_id` will allow us to distinguish distinct donors in our aggregations. Therefore, giving us an accurate result when requesting total donors count.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-261)
┆Project Name: azul
┆Issue Number: AZUL-261

**Comment by theathorn** [comment]
Fixed by #433.
