### ISSUE TITLE
Optionally put API Gateways in GitLab VPC

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4001]
..only for AnVIL deployment.

**Comment by danielsotirhos** [comment]
An upgrade of Chalice may be required. Currently we use Chalice v1.24.1

```
(.venv) daniel@Crispin ~/repo/azul1 $ grep chalice requirements.*
requirements.dev.txt:git+https://github.com/DataBiosphere/azul-chalice@1.24.1+7#egg=chalice
```

which suffers from a [bug](https://github.com/aws/chalice/issues/1449) associating VPC endpoints with private APIs.
A fix for this issue was merged on Dec 30, 2021 which puts it in Chalice v1.26.3

**Comment by danielsotirhos** [comment]
Confirmed the domain of my private API resolves in DNS after it is associated with the VPC endpoint.

![Screen Shot 2022-04-26 at 10 19 05 AM](https://user-images.githubusercontent.com/46407464/165357035-fe19a5bd-90fc-47fe-818f-02e6aafe9929.png)

```
$ nslookup a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
Name:	a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com
Address: 172.71.3.253
Name:	a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com
Address: 172.71.1.167

$ dig a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com

; <<>> DiG 9.10.6 <<>> a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33689
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com. IN A

;; ANSWER SECTION:
a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com. 60 IN A 172.71.3.253
a5493cgt14-vpce-06ae12eb9692543d3.execute-api.us-east-1.amazonaws.com. 60 IN A 172.71.1.167

;; Query time: 51 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Apr 26 10:22:13 PDT 2022
;; MSG SIZE  rcvd: 130
```

**Comment by theathorn** [comment]
@hannes-ucsc to outline demo instructions for the demo to the Broad.

**Comment by hannes-ucsc** [comment]
For demo, set up two personal deployments, one private, one public. Describe the architecture using the network diagram that we created for compliance. Show that the domain names for the private deployment resolve to private IPs in the VPC. Show that they can't be reached (ping and curl) unless the VPN is active. Show that the domain names for the public deployment resolve to public IPs. Describe briefly how we manage access to the VPN (PKI with certificate requests and without distributing private keys).

**Comment by hannes-ucsc** [comment]
This has been demo'ed to the AnVIL stakeholders on 6/28/2022 at 9:30am.

**Comment by hannes-ucsc** [comment]
The `anvil demo` label was combined with the `dcp demo` label to the `demo ext` label.
