### ISSUE TITLE
Create CloudWatch metric filter for number of 5xx errors

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4009]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Counting404Responses.html

Count the number of 5xx errors returned from from the Azul service and indexer REST APIs, using the API Gateway logs in CloudWatch.

![Data Browser System Overview - Logging   Monitoring(8)](https://user-images.githubusercontent.com/5143256/167752132-2d098e6b-5d3f-41d0-b377-c17bd506bfba.svg)

**Comment by noah-aviel-dove** [comment]
When `AZUL_DEBUG` was changed to an invalid value ("foo") in the lambda configuration for `azul-service-dev`, it resulted in a 502 error for every request to the service. However, none of these errors were observable via the metric filter `azul-service_5xx-dev`. Investigate why they weren't caught by the filter.

**Comment by hannes-ucsc** [comment]
We've determined that there is an issue with emitting JSON in API Gateway Logs. The [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html) suggests that one can use a JSON template to do so but that suggestion is naive because the approach quickly fails for fields whose values might contain quote or backslash. Something would need to escape those but there is currently no mechanism to do so.

We will whittle down the list of logged fields in #4073 and then split the log template into two blocks: one JSON and one custom, like so:

```
{
    "safeField", "$safeField"
}

unsafeField: $unsafeField
```

A safe field is one whose value is guaranteed (or extremely unlikely) to contain quotes or backslashes. The CloudWatch heuristic that detects and parses JSON in log messages will then be able to parse the JSON from the first block and ignore the second block.

**Comment by hannes-ucsc** [comment]
@achave11 points out that API Gateway already exposes a metric for the number of 5xx and 4xx errors. That means that we won't need to create a metric filter to parse the API Gateway logs. That means that #4073 isn't blocking this anymore.

**Comment by hannes-ucsc** [comment]
We can move on to #4010 and close this one.
