### ISSUE TITLE
Create CloudWatch alarm for number of 5xx errors

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4010]
… using a configurable threshold rate, say 10/h. ~Also create the SNS topic to which these and future alarms are posted. Subscribe azul-group@ucsc.edu to the topic.~ [edit: moved to #4190]
![Data Browser System Overview - Logging   Monitoring(25)](https://user-images.githubusercontent.com/5143256/168342634-d58f88b6-a805-435d-917a-4e7d4e7dba5a.svg)

**Comment by hannes-ucsc** [comment]
For demo, tweak the alarm parameters so that it can be triggered with just a dozen or so 500 responses. Force a 500 response by modifying the lambda environment or adding an `assert False` to the code. Show that the alarm fires.

**Comment by noah-aviel-dove** [comment]
The alarm is currently configured to trigger if the threshold is met for 6 evaluation periods of 1 minute each. It should instead be configured to trigger if the threshold is met for 1 evaluation of 60 minutes.
