### ISSUE TITLE
Integrate monitoring SNS topic with Slack

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4011]
![Data Browser System Overview - Logging   Monitoring (2)](https://user-images.githubusercontent.com/46407464/215891785-aff6fa1f-e824-4aab-b7b3-0cc7f5898584.png)

**Comment by achave11-ucsc** [comment]
This issue is blocked by #4807, when I set the blocking relationship it doesn't stick.

**Comment by hannes-ucsc** [comment]
For demo, show Slack notifications by the bot in each of the three new channels.

**Comment by nolunwa-ucsc** [comment]
Comment already in the SSP
