### ISSUE TITLE
Pen test PRs from external collaborators

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4012]
Use a personal GitHub account (unaffiliated with UCSC, not in any of the GitHub organizations in the screenshot below) to file a pull request against Azul.

![image](https://user-images.githubusercontent.com/5143256/160949895-94986920-b406-4535-b3e1-0f1978c1db80.png)

We expect no GitHub actions to be run.

**Comment by danielsotirhos** [comment]
[PR](https://github.com/DataBiosphere/azul/pull/4052) viewed from the (non-UCSC) submitter account:

<img width="927" alt="Screen Shot 2022-04-05 at 10 36 35 AM" src="https://user-images.githubusercontent.com/46407464/161816735-0415bad3-c451-4c0e-86ab-9ea6da5f0baa.png">

PR viewed from my UCSC account:

![Screen Shot 2022-04-05 at 10 39 41 AM](https://user-images.githubusercontent.com/46407464/161817007-7f83c4a9-40fb-428a-bc09-d679d4d4f3a0.png)

**Comment by hannes-ucsc** [comment]
It looks like we're only requiring approval for first-time outside contributors. That would mean that once a first PR was approved, subsequent PRs would not. I want to tighten that and require approval for every PR from an outside contributor.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-required-approval-for-workflows-from-public-forks
