### ISSUE TITLE
/index/{entity_type}/{uuid} does not enforce access controls

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4013]
… or at least apply filter on configured sources.

**Comment by noah-aviel-dove** [comment]
Suspicion seems to be refuted. I get a 404 response when requesting inaccessible entities.

```
$ curl https://service.dev.singlecell.gi.ucsc.edu/index/files/4e9f3b1b-01db-489f-ab54-3238022b3663 -H "Authorization: Bearer $(gcloud auth print-access-token)"
{"protocols":[],"entryId":"4e9f3b1b-01db-489f-ab54-3238022b3663","sources":[{"sourceId":"2c4ec571-f489-4277-b215-da8dedd86803", ...
```

```
$ curl https://service.dev.singlecell.gi.ucsc.edu/index/files/4e9f3b1b-01db-489f-ab54-3238022b3663
{"Code":"NotFoundError","Message":"NotFoundError: Can't find an entity in files with an uuid, 4e9f3b1b-01db-489f-ab54-3238022b3663."}
```

Looking at the source code, `/index/{entity_type}` and `/index/{entity_type}/{uuid}` are both handled by the same functions, the only difference between that the `item_id` parameter is `None` in the case of the former and is added to the filters in case of the latter. This does not affect the reification of the source filter.
