### ISSUE TITLE
Add API documentation for summary response field 'projects'

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4016]
The documentation for the `/index/summary` endpoint is missing an entry for the response field `projects` (from #3521, #3917)

![Screen Shot 2022-03-31 at 9 58 43 AM](https://user-images.githubusercontent.com/46407464/161110086-532e2832-9cca-4cf5-92fe-81213c8dbb5f.png)

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/pull/3984#discussion_r839845764

Please move screenshot to #3917.
