### ISSUE TITLE
Encrypt GitLab data and root volume and snapshots

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4022]
Part of "SC-28 PROTECTION OF INFORMATION AT REST".

**Comment by theathorn** [comment]
~@hannes-ucsc :"Blocker makes this a no-op."~

**Comment by hannes-ucsc** [comment]
I reversed the blocking relationship, making this represent the main work.

**Comment by hannes-ucsc** [comment]
Requires manual work to encrypt the existing backup snapshots. I think the process of encrypting the volume entails taking an encrypted snapshot, and restoring a new volume from it with encryption enabled.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Work to commence on Monday 05/08, when assignee becomes operator."

**Comment by dsotirho-ucsc** [comment]
Encryption of snapshots and GitLab volumes completed on `platform-hca-dev`

![azul-gitlab-dev](https://github.com/DataBiosphere/azul/assets/46407464/d338c891-81e5-478c-970a-0226885945a2)

**Comment by dsotirho-ucsc** [comment]
Encryption of snapshots and GitLab volumes completed on `platform-hca-prod`

![azul-gitlab-prod](https://github.com/DataBiosphere/azul/assets/46407464/66f8c999-5c75-4018-9002-bd8fd4f85852)

**Comment by dsotirho-ucsc** [comment]
Encryption of snapshots and GitLab volumes completed on `platform-anvil-dev`

![azul-gitlab-anvildev](https://github.com/DataBiosphere/azul/assets/46407464/58bfd948-9dd6-4bfe-87aa-f50055be750d)

**Comment by dsotirho-ucsc** [comment]
Encryption of snapshots and GitLab volumes completed on `platform-anvil-prod`

![azul-gitlab-anvillprod](https://github.com/DataBiosphere/azul/assets/46407464/8a1c9d63-0336-462a-950c-cce04cd03e12)

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Decided to increase the scope to include encryption of root volume which would have to be defined in Terraform config."

**Comment by hannes-ucsc** [comment]
For demo, show that all EBS volumes and snapshots are encrypted in all deployment zones.
