### ISSUE TITLE
AC-2 (1) Automated mechanisms to support the management of information system accounts

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4025]
[FedRAMP SSP AC-2 (1) Control Enhancement](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.kgcv8k):
Per Mariano Serquina: "The HCA system is looking to configure their GitHub ticketing system to be able to track every system-related task, including account creation/removal and role assignment/reassignment, as this helps create a more formalized and automated approval process."

**Comment by hannes-ucsc** [comment]
Onboarding is described in this document:

https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.u3tjz35wp6ln

**Comment by nolunwa** [comment]
@hannes-ucsc In addition to on and off-boarding, all user account actions are reported through AWS CloudWatch/Cloud Trail as defined in AU-02 and reviewed, analyzed, and reported in accordance with AU-6 (continuously monitored automatically)

**Comment by theathorn** [comment]
@hannes-ucsc "How does a monthly meeting cover a control that requires automation?"

**Comment by nolunwa** [comment]
@theathorn 

ACCOUNT MANAGEMENT | AUTOMATED SYSTEM ACCOUNT MANAGEMENT
Support the management of system accounts using [Assignment: organization-defined
automated mechanisms].
Discussion: Automated system account management includes using automated mechanisms
to create, enable, modify, disable, and remove accounts; notify account managers when an
account is created, enabled, modified, disabled, or removed, or when users are terminated
or transferred; monitor system account usage; and report atypical system account usage.
Automated mechanisms can include internal system functions and email, telephonic, and
text messaging notifications.
Related Controls: None.

**Comment by nolunwa** [comment]
NIST SP 800 53 rev 5 https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf

**Comment by theathorn** [comment]
@hannes-ucsc : "Given the control discussion cited above, it turns out that a ticketing system in conjunction with making sure all account management actions are logged in CloudWatch are sufficient to cover this control."

**Comment by nolunwa** [comment]
@hannes-ucsc i confirm logging is not required for this control. The goal of this control is employs automated mechanisms to support the management of accounts.

**Comment by hannes-ucsc** [comment]
>  confirm logging is not required for this control.

In that case, the on- and off boarding tickets (#4205 and #4206) cover this control sufficiently. No additional tickets are needed.
