### ISSUE TITLE
SA-2 ALLOCATION OF RESOURCES

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4026]
[FedRAMP SSP SA-2 Allocation of Resources](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.4j8vrz3).

**Comment by nolunwa** [comment]
@theathorn This is WIP need to work with Greta and someone from the finance team for this

**Comment by nolunwa-ucsc** [comment]
implemented and SSP updated
