### ISSUE TITLE
Put Python dependencies under version control

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4033]
Use `pip download` and commit the result. Use `pip install --find-links` to install them.

https://pip.pypa.io/en/stable/cli/pip_download/

**Comment by theathorn** [comment]
Spike to determine feasibility.

**Comment by hannes-ucsc** [comment]
For demo, delete one of the pre-downloaded dependencies and re-deploy to a personal deployment. Show that the service fails with a 500 `ImportError`. Delete all (or all but one if chalice complains) pre-downloaded dependencies and examine the layer's `deployment.zip`. It should be empty (or only contain one package). Undo all deletions, re-deploy and show that app is functional again.

**Comment by hannes-ucsc** [comment]
Failed to demo step 1. Deletion of wheel did not result in ImportError on the service side.

**Comment by hannes-ucsc** [comment]
During the demo I deleted the `botocore` wheel. Apparently the AWS Lambda runtime includes `botocore:

> Your code runs in an environment that includes the SDK for Python (Boto3), with credentials from an AWS Identity and Access Management (IAM) role that you manage.

(https://docs.aws.amazon.com/lambda/latest/dg/lambda-python.html)

So deleting the wheel un-shadowed the built-in copy of botocore. After deleting the `elasticsearch` I was able to produce an ImportModuleError. Going for demo again next week.
