### ISSUE TITLE
Conduct annual review of the rule set for audited events

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4035]
For [SSP AU-2 (3) Control Enhancement](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.338fx5o): The team should review the rules for what is captured in CloudWatch and CloudTrail logs.

The organization reviews and updates the audited events [FedRAMP Assignment: annually or whenever there is a change in the threat environment].

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Is this a one-time task or periodic one?"

**Comment by theathorn** [comment]
From Mariano Sequina: "Planned: The HCA system does not currently have a defined frequency for review of CloudTrail audit logs, it is done on an ad-hoc basis. It is planned to change this to align with the FedRAMP requirement of weekly audit log reviews."

**Comment by theathorn** [comment]
@hannes-ucsc : "There are 3 distinct concepts: 1) The set of types of events that get logged,  2) the set of rules that govern the automated auditing of log events, and 3) the periodic review of both sets. Questions: Are both sets to be reviewed periodically? Do we need to go into details about the specific review process?"

@nolunwa : "Both audited events (the rule set) and auditable event (type of event) will need to be reviewed on a periodic basis. That is: how this control will be tested based on the test case workbook. No specific details on how the review should be done. What the auditors will want to see (is that) there was a meeting held by the team to perform the review or an admin reviewing screenshotting with timestamp which can be added to the (meeting) minutes (and) that the logs were reviewed and (the rules) modified if needed.  This can be part of your monthly security meeting or quarterly meeting as we have a bunch of controls that require review at a defined frequency."

**Comment by theathorn** [comment]
@nolunwa to follow up with Carter Group to document the review process.

**Comment by nolunwa** [comment]
@hannes-ucsc For the audited events (the rule set) the review frequency is annually or whenever there is a change in the threat environment

**Comment by nolunwa** [comment]
@theathorn for the review process we should open a ticket for the annual review of the audited events (the rule set), we can assign the ticket or have a meeting to perform the review of the rule set

**Comment by hannes-ucsc** [comment]
We will implement this control by having a yearly reminder on Slack to conduct a review of the rule set that governs what ends up in the audit log. In response to the reminder, the project manager will create a ticket and assign it to the operator. The operator will then review the rule set and make a comment on the ticket to record the outcome of the review. If the review results in changes to the rule set to be required, the operator will create tickets to track that work.

**Comment by theathorn** [comment]
See [AU-02 (03) comment](https://docs.google.com/document/d/1Lo4YMxXA8k4Wiyl08tYMecfKlgl82lT3kysGI3aXKEg/edit?disco=AAAAfglQICM).

**Comment by nolunwa** [comment]
updated SSP and SOP will approved process

**Comment by theathorn** [comment]
@melainalegaspi to create Slack reminder for annual review of rule set - @theathorn to observe this process.

**Comment by theathorn** [comment]
Mel guided me through the process:
  - on Slack, select the dropdown next to "UCSC GI"
  - select Tools -> Workflow Builder
  - select Create (or edit an existing workflow)

I created "[Annual review of the rule set for audited events](https://app.slack.com/workflow-builder/T09P9H91S/workflow/425704114060540024)" starting on December 12 and "repeats annually".

We can choose a different start date in consultation with @nolunwa and @hannes-ucsc.

**Comment by hannes-ucsc** [comment]
This should use the mechanism @melainalegaspi picked to solve #4494.

**Comment by melainalegaspi** [comment]
@theathorn to come up with exact wording of notification so that @melainalegaspi can implement it.

**Comment by theathorn** [comment]
The team should review all the types of events that can generate a CloudWatch log entry for completeness.
The audited event types are documented in #2519.
The Slack notification should state "Conduct a review of the rule set for audited events".

**Comment by hannes-ucsc** [comment]
We need to decide what to do with this since assignee has left the team.

**Comment by melainalegaspi** [comment]
cannot add this to a Task Reminder notification in Slack because it doesn't allow annual reminders to be set up. This is still an annual reminder in the Slack workflow builder.

**Comment by theathorn** [comment]
@theathorn to set up a calendar invite.

**Comment by theathorn** [comment]
Slack workflow configured:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/d86e7574-5a3c-4029-afe5-0aceccd496d8)

**Comment by theathorn** [comment]
Add reminder for the PM to schedule a meeting.

**Comment by theathorn** [comment]
![image](https://user-images.githubusercontent.com/38867406/208774557-64438ca6-4830-430f-af28-972b3becd581.png)
