### ISSUE TITLE
Deploy automated tools to analyze audit records

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4040]
From [SSP AU-6 (3) Control Enhancement](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.2uxtw84):
The organization analyzes and correlates audit records across different repositories to gain organization-wide situational awareness. 
Th team is looking to add automated tools to analyze audit records.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "How does Dockstore implement this?"

**Comment by theathorn** [comment]
Nneka: CloudWatch/CloudTrail/GuardDuty -> dashboard in SecurityHub.
Hannes to look at Amazon Detective.

**Comment by melainalegaspi** [comment]
@theathorn to discuss this during this Thursdays compliance meeting.

**Comment by theathorn** [comment]
Azul uses real time monitoring with Slack notifications.

**Comment by nolunwa-ucsc** [comment]
Current implementation and documentation in the SSP is CloudWatch/CloudTrail/GuardDuty
