### ISSUE TITLE
Provide an audit reduction and report generation capability

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4041]
From [SSP AU-7 Audit Reduction and Report Generation](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.1a346fx):
The team plans to use CloudWatch Logs Insights to assist in the reduction of audit logs.
CloudWatch Logs Insights will be able to reduce audit logs to more specific events in search for unusual activity.
It can also generate reports for analysis.

**Comment by theathorn** [comment]
Nneka: Agree. Logs cannot be altered.
Hannes: Nothing further to do for Azul team. Preventing log tampering is sufficiently implemented by our policy.

**Comment by nolunwa-ucsc** [comment]
SSP updated
