### ISSUE TITLE
Select static code analysis tool

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4058]
From [SA-11(01): DEVELOPER SECURITY TESTING AND EVALUATION | STATIC CODE ANALYSIS](https://docs.google.com/document/d/1vCrthQdtDmg50gWmWEGBLIWS__c6Wsn6re9IE9mUIiA/edit#bookmark=id.t9gs8ma21exj):
The organization requires the developer of the information system, system component, or information system service to employ static code analysis tools to identify common flaws and document the results of the analysis.

Investigate [LGTM](https://lgtm.com/) and [SonarCloud](https://sonarcloud.io/) and make a decision as to which static application security testing (SAST ) tool we will deploy.

**Comment by hannes-ucsc** [comment]
Currently trying out LGTM.

**Comment by melainalegaspi** [comment]
@hannes-ucsc: "LGTM looks pretty good, I like that it only flags violations in added code. The only thing left to do is make the LGTM status check mandatory for PRs."

**Comment by hannes-ucsc** [comment]
Made LGTM a mandatory status check for the `develop` branch.
