### ISSUE TITLE
Error downloading DCP-generated loom files

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4059]
Steps:
  - On `prod`, filter on "File Source = DCP/2 Analysis"
  - Click on one of the "Matrices" download icons on the Projects tab
  - Click on the download icon for a DCP-generated loom file
  - After 10-20 seconds an error is generated:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/13582f03-6f91-4d5f-bc85-6fa88ad25e12)

**Comment by theathorn** [comment]
Customer example: https://data.humancellatlas.org/explore/projects/cc95ff89-2e68-4a08-a234-480eca21ce79/project-matrices

**Comment by theathorn** [comment]
Spike to diagnose.

**Comment by danielsotirhos** [comment]
TDR requests were returning 500 errors between 6am and noon Wed Apr 6th.

![Screen Shot 2022-04-07 at 8 52 17 AM](https://user-images.githubusercontent.com/46407464/162245745-a314681d-c3c5-467f-90e1-dfde18b79c58.png)

**Comment by melainalegaspi** [comment]
@hannes-ucsc to create dcp2 ticket about false 401s from TDR.

**Comment by melainalegaspi** [comment]
@danielsotirhos in this ticket link to Andrew's statement from Slack about SAM outage.

**Comment by danielsotirhos** [comment]
The statement from Andrew was quoted above in https://github.com/DataBiosphere/azul/issues/4059#issuecomment-1091907020 .

The direct link to the statement is https://humancellatlas.slack.com/archives/C9XD6L0AD/p1649337140233539?thread_ts=1649263990.730139&cid=C9XD6L0AD
