### ISSUE TITLE
Promotion checklist conflicts with operator manual

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#4062]
From [Operator manual](https://github.com/DataBiosphere/azul/blob/develop/OPERATOR.rst#promoting-to-prod):
`Create a new GitHub issue with the title Promotion yyyy-mm-dd`

From [promotion checklist](https://github.com/DataBiosphere/azul/blob/develop/.github/PULL_REQUEST_TEMPLATE/promotion.md): 
`Title of connected issue matches Promotions/yyyy-mm-dd`

Which is it? 🤔

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "The manual is correct in this case. The checklist needs to be updated."
