### ISSUE TITLE
5xx errors from Azul should point to the root cause

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4065]
... if TDR is the root cause. 

The return value from `ServiceAccountCredentialsProvider.insufficient_access` should include a string pointing at TDR.

Furthermore, the 500 caused by time-boxing TDR requests should point at TDR as the root cause.

**Comment by hannes-ucsc** [comment]
I have the feeling this is too technical to demo to the entire DCP.

For demo, temporarily shorten the TDR timeout in `dev` and show that the resulting error message displayed by the Data Browser indicates that TDR is the root cause.
