### ISSUE TITLE
Transient failure during IT due to `GaiaMint invalid`

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#4071]
Omitted logs output for security concerns, see https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/19066#L1695

This failure did not occur again when the IT job was retried.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Parking in order to get a better idea about prevalence."

**Comment by achave11** [comment]
https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/22926.

**Comment by hannes-ucsc** [comment]
No recurrences since then.
