### ISSUE TITLE
Project summary donor count is always -1 in project hits

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#408]
This happens in data portal dev, which points to Azul Dev and DSS Integration. 

https://service.dev.explore.data.humancellatlas.org/repository/projects?size=15&filters=%7B%7D

![Screen Shot 2018-10-12 at 9.17.15 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/6e9a5dd3-d79f-4a51-bf71-b8813316aa15)

https://dev.data.humancellatlas.org/explore/projects

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-265)
┆Project Name: azul
┆Issue Number: AZUL-265

**Comment by hannes-ucsc** [comment]
For your entertainment:

https://github.com/DataBiosphere/azul/blob/develop/src/azul/service/responseobjects/hca_response_v5.py#L285
