### ISSUE TITLE
Residual Lambda context in IT caused by AzulChaliceLocalIntegrationTest

### ISSUE THREAD

**Issue by amarjandu** [DataBiosphere/azul#4085]
During `IntegrationTest._test_managed_access` we expect there to be no lambda context so that the long timeout is used when making TDR requests. Because `AzulChaliceLocalIntegrationTest` is the first test that is ran, a residual Lambda Context exists during the test execution which causes causes the short time to be used.

The test run https://gitlab.dev.singlecell.gi.ucsc.edu/-/snippets/34 shows that when `AzulChaliceLocalIntegrationTest` is skipped, the long time is used.

```
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision fe1d2842e42040c36c69a0e88e5a1ab1702cf8dd)
+++ b/test/integration_test.py	(date 1649874078486)
@@ -1412,6 +1412,7 @@
                 mini_dss.get_native_file_url(uuid, version, 'aws')
 
 
+@unittest.skip('Skip to see if Lambda Context is present')
 class AzulChaliceLocalIntegrationTest(AzulTestCase):
     url = furl(scheme='http', host='127.0.0.1', port=8000)
     server = None
```

Observed as part of https://github.com/DataBiosphere/azul/issues/4083

**Comment by melainalegaspi** [comment]
@hannes-ucsc to triage.

**Comment by hannes-ucsc** [comment]
Duplicates #4087.
