### ISSUE TITLE
Project title is always the same in `dev`

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#409]
Is this correct?
Are all projects really Q4_DEMO-Single cell RNA-seq of primary human glioblastomas.

https://dev.data.humancellatlas.org/explore/projects
https://service.dev.explore.data.humancellatlas.org/repository/projects?size=15&filters=%7B%7D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-266)
┆Project Name: azul
┆Issue Number: AZUL-266

**Comment by hannes-ucsc** [comment]
@NoopDog to verify against staging. I'm pretty sure this is because integration has only scale and integration test data.

Also consider displaying the short name in table and display long name on hover.

**Comment by NoopDog** [comment]
Staging times out when hitting

https://service.staging.explore.data.humancellatlas.org/repository/projects?size=15&filters=%7B%7D

**Comment by theathorn** [comment]
Short names are different and long names are sometimes different.
