### ISSUE TITLE
IT fails with `BadGzipFile`

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#4093]
```
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='dcp2-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nadove/PycharmProjects/azul-sc/test/integration_test.py", line 359, in subTest
    yield
  File "/home/nadove/PycharmProjects/azul-sc/test/integration_test.py", line 738, in _test_repository_files
    self._validate_fastq_response(response)
  File "/home/nadove/PycharmProjects/azul-sc/test/integration_test.py", line 745, in _validate_fastq_response
    self._validate_fastq_content(response)
  File "/home/nadove/PycharmProjects/azul-sc/test/integration_test.py", line 803, in _validate_fastq_content
    fastq = buf.read(self.num_fastq_bytes)
  File "/home/nadove/.pyenv/versions/3.8.12/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/home/nadove/.pyenv/versions/3.8.12/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/nadove/.pyenv/versions/3.8.12/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/home/nadove/.pyenv/versions/3.8.12/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'@N')

----------------------------------------------------------------------
Ran 16 tests in 1029.367s

FAILED (errors=1, skipped=3)
make: *** [Makefile:160: integration_test] Error 1
```

The seed for `integration_test.IndexingIntegrationTest.test_indexing` was 7002460651899548689.

**Comment by melainalegaspi** [comment]
Spike to determine if GZipFile is invalid in the snapshot.

**Comment by noah-aviel-dove** [comment]
I have a hypothesis that the file is an ordinary (non-compressed) fastq file, not a gzip file at all. The stacktrace shows that it starts with an `@` character, which is always the first character in a (non-compressed) fastq. Furthermore, the function that chooses a fastq file to validate (`_get_one_file_uuid`) includes both "fastq.gz" and "fastq" in the file format filter, so we may be attempting to unzip a file that doesn't even have a `.gz` extension.

**Comment by achave11** [comment]
This happened during IT for GitLab dev https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43559.

**Comment by noah-aviel-dove** [comment]
The offending file in that prompted the creation of this ticket is https://service.dev.singlecell.gi.ucsc.edu/index/files/1697aa82-0910-44e6-ac07-2020248e1977 ("mouse_cortex_I1.fastq"). It is a valid non-compressed fastq file with no `.gz` extension.

```
$ head mouse_cortex_I1.fastq 
@NB501337:483:H5NTJBGX7:1:11101:16780:1041 1:N:0:TCCGGAGA
TCCGGAGA
+
AAAAAEEE
@NB501337:483:H5NTJBGX7:1:11101:12493:1044 1:N:0:TCCGGAGA
TCCGGAGA
+
66/AA6E6
@NB501337:483:H5NTJBGX7:1:11101:10988:1044 1:N:0:TCCGGAGA
TCCGGAGA
```

Ergo, I think this is a `test` `bug` rather than a `data` `bug`. We should either drop `fastq` from the list of filtered file formats (the .gz variant is more common on both dev (dcp2, 99.3%) and prod (dcp14, 94%)), or make the decompression conditional on the file format.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "We should make the decompression conditional on the file extension in the file name. Since the solution for #4074 includes returning the entire inner file entity we will be basing this solution on that one."

**Comment by hannes-ucsc** [comment]
For demo, run IT with the seed mentioned in the description. If possible, also run the IT from that seed against the commit on develop that immediately precedes the merge commit, just so we can see that the reproduction is valid. Maybe do the latter, prior to the demo and just show the IT failure and the commit you're on.
