### ISSUE TITLE
genusSpecies and libraryConstructionApproach are always empty on /projects

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#410]
genusSpecies	[]
libraryConstructionApproach	[]
disease	[]

https://dev.data.humancellatlas.org/explore/projects
https://service.dev.explore.data.humancellatlas.org/repository/projects?size=15&filters=%7B%7D

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-267)
┆Project Name: azul
┆Issue Number: AZUL-267

**Comment by hannes-ucsc** [comment]
I fixed it for `libraryConstructionApproach`. I can't reproduce this for `genusSpecies`. I can reproduce this for `disease`.
