### ISSUE TITLE
Open TIM in TopBraid Composer

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4103]
https://docs.google.com/document/d/1Hc8lPOKC27c-EFNl8AWHo2xPVhgOTiNOO5aw2k11GmQ/edit?usp=sharing

**Comment by hannes-ucsc** [comment]
I asked BI to share above document with Daniel.

**Comment by danielsotirhos** [comment]
Was successfully able able to follow the `TopBraid Composer Getting Started Guide` document and open the `Terra-Interoperability-Model` using `TopBraid Composer Free Edition v6.0.1` on MacOS.

<img width="1122" alt="Screen Shot 2022-04-15 at 1 30 42 PM" src="https://user-images.githubusercontent.com/46407464/163631158-23de0e5c-7cb7-46c1-8b38-6b411a79f579.png">

**Comment by theathorn** [comment]
@hannes-ucsc : "I am able to open TIM in Composer on my personal Mac. Requested UCSC provided Mac from Tim Harris."
