### ISSUE TITLE
/index/{entity_type}/{uuid} has no test coverage

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4131]
We need unit and integration test coverage for these endpoints. That's how #4130 slipped through.

**Comment by nadove-ucsc** [comment]
We may still need IT coverage, but it appears that this is now covered by unit tests: https://app.codecov.io/gh/DataBiosphere/azul/commit/e06862b240ea32297880e4668ca975521b05263f/blob/src/azul/service/repository_service.py#L118

**Comment by nadove-ucsc** [comment]
I was correct. This endpoint was not covered by IT but it was already covered for unit tests.
https://github.com/DataBiosphere/azul/actions/runs/4932472891/jobs/8815526840
