### ISSUE TITLE
Update ClamAV every week

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4139]
Per [Information Integrity Procedure](https://docs.google.com/document/d/1KWBwFyWCbLVDKqUYmY05oh8XZRdI0ZSVhn64XytrjKw), SI-03(2):
The information system automatically updates malicious code protection mechanisms. Supplemental Guidance: Malicious code protection mechanisms include, for example, signature definitions. Due to information system integrity and availability concerns, organizations give careful consideration to the methodology used to carry out automatic updates.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "PR #3672  for #3614 already includes keeping the database up to date using FreshClam."
