### ISSUE TITLE
Terra timeouts should lead to a 503 from Azul

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4152]
… and ultimately a retry by the client (Data Browser). The precise mechanics of the client-side retries need to be discussed. It may be that we don't want to retry automatically but involve an action by the user. If an error is displayed to the user, it should be clear that it is transient, caused by high load and can be remedied by refreshing the page.

**Comment by hannes-ucsc** [comment]
In triage, discuss any blocking relationship with other tickets.

**Comment by noah-aviel-dove** [comment]
https://github.com/DataBiosphere/azul/issues/3968

https://github.com/DataBiosphere/azul/blob/0cd72559ef793f79bd71f90e27643c0b757002b8/src/azul/terra.py#L303

**Comment by theathorn** [comment]
Dup of #3968.
