### ISSUE TITLE
Off-board Amar

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#4159]

**Comment by amarjandu** [comment]
Deleted personal deployment, cleaned up applicable manually provisioned resources

**Comment by hannes-ucsc** [comment]
Completed https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.t4ugroiv40fz except for step 3 which involves Erich who has been contacted.

**Comment by hannes-ucsc** [comment]
Erich just confirmed.
