### ISSUE TITLE
Summarize `libraryConstructionApproach` in specimens and projects responses

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#416]
For projects and specimens the "processes" element in the response can be quite large and and we do not need most of the data.

https://service.staging.explore.data.humancellatlas.org/repository/specimens?size=15&filters=%7B%22file%22:%7B%22preservationMethod%22:%7B%22is%22:%5B%22frozen,%20liquid%20nitrogen%22%5D%7D%7D%7D

Instead of a list of processes we need an aggregation similar to the fileTypeSummaries over `libraryConstructionApproach`.

So like:
```
libraryConstructionApproachSummary : [
    {
        libraryConstructionApproach: "SS2"
        count: 25
   },
   {
        libraryConstructionApproach: "10x"
        count: 50
   }
]

```

instead of:

![Screen Shot 2018-10-13 at 6.32.20 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/1a62b62a-460c-4286-a85f-51ef1027d3df)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-272)
┆Project Name: azul
┆Issue Number: AZUL-272

**Comment by theathorn** [comment]
@NoopDog Reevaluate in dev.

**Comment by theathorn** [comment]
Azul OK in dev but not deployed to staging yet.
