### ISSUE TITLE
Prefer project estimated cell count for sort order

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4173]
If a project contains both project.estimated_cell_count and cell_suspension.estimated_cell_count values then the project cell count should take precedence and be used when sorting is applied (remove the current logic of using the maximum).

**Comment by melainalegaspi** [comment]
@danielsotirhos  : "On production, in DCP15 catalog there are 237 projects, 35 with cell suspension cell counts and no project cell count."

**Comment by hannes-ucsc** [comment]
For demo, show that the sorting is based on the new logic, as opposed to max.

**Comment by hannes-ucsc** [comment]
The blocker should be demo'ed to the DCP. This one should be demo'ed internally only.
