### ISSUE TITLE
Enable GuardDuty and SecurityHub

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4174]
![Data Browser System Overview - Logging   Monitoring(9)](https://user-images.githubusercontent.com/5143256/167753073-5365c3d0-27fd-4393-b722-14cabd605f39.svg)

**Comment by theathorn** [comment]
Rachel requesting this as a high priority task requested by David Bernick.

**Comment by theathorn** [comment]
Spike to determine if this requires a change to the Terraform configuration and read introductory documentation on both.

**Comment by theathorn** [comment]
[CIS AWS Foundations Benchmark standard](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-cis.html) states "AWS Security Hub has satisfied the requirements of CIS Security Software Certification".

**Comment by danielsotirhos** [comment]
Amazon GuardDuty Features
https://aws.amazon.com/guardduty/features/

Use Terraform to automatically enable Amazon GuardDuty for an organization
https://github.com/aws-samples/amazon-guardduty-for-aws-organizations-with-terraform

Terraform resource: GuardDuty
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_detector

AWS Security Hub features
https://aws.amazon.com/security-hub/features/

Setup AWS SecurityHub with Terraform
https://towardsaws.com/setup-aws-securityhub-with-terraform-in-less-than-a-minute-bf27d742602c

Terraform resource: SecurityHub
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_account

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Reviewed spike results together with @danielsotirhos, moving straight to implementation stage."

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Demoed this on Tuesday to the Anvil folks. More demos scheduled for Friday with David Bernick."
