### ISSUE TITLE
Enable VPC flow logs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4176]
![Data Browser System Overview - Logging   Monitoring (15)](https://user-images.githubusercontent.com/46407464/215921687-8123e853-c0f0-4873-8102-59af6cb59ce0.png)

https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-cwl.html#flow-logs-cwl-create-flow-log

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/flow_log

Enable for all traffic, watch log volume, adjust settings if needed.

**Comment by theathorn** [comment]
@hannes-ucsc :'Once the finding from #4694 is addressed, this becomes a no-op."

**Comment by hannes-ucsc** [comment]
Inverted the blocking relation.

**Comment by hannes-ucsc** [comment]
For demo, show that SecurityHub finding from blocked ticket is fixed in all our AWS accounts. Close blocked ticket.
