### ISSUE TITLE
Set up Amazon Inspector for scanning Docker images

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4177]
Fortreum identifier: 2023-V113-RA-5 - Container Image Scans Not Provided

https://docs.aws.amazon.com/inspector/latest/user/scanning-ecr.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_registry_scanning_configuration

![Data Browser System Overview - Logging   Monitoring (14)](https://user-images.githubusercontent.com/46407464/215921409-4f2af59a-a8d4-4d1c-afa7-0356427c8411.png)

**Comment by hannes-ucsc** [comment]
Spike to update diagram.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to reprioritize.

**Comment by nolunwa-ucsc** [comment]
Finding from Initial VAR v1.3
V113-RA-5: CONTAINER IMAGE SCANS NOT PROVIDED

**Comment by nolunwa-ucsc** [comment]
@hannes-ucsc going further what will the cadence for managing containers and redeploying them to keep them up to date be? Has this been decided or documented

**Comment by hannes-ucsc** [comment]
We have no plans to periodically update Docker images. We will update an image as needed when Amazon Inspector detects vulnerabilities in it or when we need a feature that is only provided by a newer version of an image.

**Comment by hannes-ucsc** [comment]
For demo, show Amazon Inspector2 findings for ECR images.
