### ISSUE TITLE
Forward ALB logs from S3 to CloudWatch

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4178]
Use this for inspiration:

https://github.com/rupertbg/aws-load-balancer-logs-to-cloudwatch

![Data Browser System Overview - Logging   Monitoring (1)](https://user-images.githubusercontent.com/46407464/215891330-1a1e6aa4-2c4e-4dd4-887d-01119a487a4d.png)

**Comment by nadove-ucsc** [comment]
@hannes-ucsc: "We should stuff this functionality into the indexer Lambda of the main deployment that is colocated with the shared deployment. I would not invoke the CloudWatch client as illustrated in the example. I would just print the logs to standard out and rely on CloudWatch logging to forward that to the default log group associated with the Lambda."

**Comment by hannes-ucsc** [comment]
For demo, show forwarded ALB logs for both GitLab and the private `anvildev` Azul service API. Show how one would discriminate them (GitLab and Azul) in a CloudWatch Logs Insights query. Perform a request against `anvildev` and find the corresponding log entry.
