### ISSUE TITLE
Scan GitLab EC2 instance with Amazon Inspector

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4189]
![Data Browser System Overview - Logging   Monitoring(2)](https://user-images.githubusercontent.com/5143256/222214253-ac4789d6-1d70-491a-9bbb-2b6b0226cd3b.png)

Install SSM agent on the instance (via user data in TF config) and [integrate](https://docs.aws.amazon.com/inspector/latest/user/enable-disable-scanning-ec2.html) with Amazon Inspector.

~Revert #3614~

**Comment by dsotirho-ucsc** [comment]
Assignee to check blocking relationships for wrong direction.

**Comment by hannes-ucsc** [comment]
Inverted blocking relationship for #4177. This will enable Amazon Inspector and add scanning of the GitLab EC2 instances. #4177 will add scanning of Docker images.

Removed blocking relationship with #4401. There is no direct dependency between this and that ticket.

**Comment by hannes-ucsc** [comment]
Turns out SSM Agent is already running on Amazon Linux 2 AMI which we use. This reduces the complexity, and therefore the estimate.

**Comment by hannes-ucsc** [comment]
For demo, show Amazon Inspector dashboard with evidence that GitLab instance is being scanned in all AWS accounts.
