### ISSUE TITLE
Create SNS topic for monitoring and security notifications

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#4190]
Split from https://github.com/DataBiosphere/azul/issues/4010

![Data Browser System Overview - Logging   Monitoring(27)](https://user-images.githubusercontent.com/5143256/168342879-7bb9311d-c855-409f-b101-9597effe5334.svg)

Ensure that any existing CloudWatch alarms are posting to the topic. Subscribe [azul-group@ucsc.edu](mailto:azul-group@ucsc.edu) to the topic.

**Comment by hannes-ucsc** [comment]
For demo, show that tripping the 5xx metric alarm in `dev` generates an email notification
