### ISSUE TITLE
Enable sending of CloudTrail events to CloudWatch logs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4196]
```
{
    "GeneratorIds": [
        "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0/rule/2.4"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-2.4
https://docs.aws.amazon.com/awscloudtrail/latest/userguide/send-cloudtrail-events-to-cloudwatch-logs.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail

![Data Browser System Overview - Logging   Monitoring(29)](https://user-images.githubusercontent.com/5143256/168405047-9fbdbed0-ecdd-47ec-9e87-57e02212ec25.svg)

**Comment by dsotirho-ucsc** [comment]
Spike to add JSON to ticket description

**Comment by hannes-ucsc** [comment]
For demo, show the new log group in `anvildev`. Perform a Cloudwatch Logs Insights query against it.
