### ISSUE TITLE
Manage CloudTrail trail in 'shared' TF component

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4197]
Import the default trail (using [terraform import](https://www.terraform.io/cli/commands/import)) into ~the GitLab~ a new `shared` component (dev.shared or prod.shared) so it can be managed by TF.

![Data Browser System Overview - Logging   Monitoring(28)](https://user-images.githubusercontent.com/5143256/168405008-8ecf1356-ad00-4395-bee8-beaa6c46cd3f.svg)

**Comment by hannes-ucsc** [comment]
For demo, show new trails in `dev` and `prod`. Show the old trails were deleted. Show that the new trails use the pre-existing buckets and that those buckets contain log files predating this ticket. Show that the buckets also contain log files for the new trails.

**Comment by danielsotirhos** [comment]
Demoed in `dev`. Still to demo in `prod`
