### ISSUE TITLE
Revoke VPN cert for Amar

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4199]
https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/cvpn-working-certificates.html

**Comment by theathorn** [comment]
@hannes-ucsc to check if this is covered in offboarding documentation.

**Comment by hannes-ucsc** [comment]
Can't do this until #3929 is done.

**Comment by hannes-ucsc** [comment]
![image](https://user-images.githubusercontent.com/5143256/178082368-22e5a3b3-7da4-4bc6-a7c7-d8c9e6bf3fb1.png)

**Comment by hannes-ucsc** [comment]
![image](https://user-images.githubusercontent.com/5143256/178082549-931057d8-6926-44f8-8bce-106bfecb17e3.png)
