### ISSUE TITLE
Add troubleshooting to resolve KMSAccessDeniedException errors from AWS lambda

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4200]
Symptom: Logs for the `/aws/apigateway/...` log group report "Internal Server Error" / HTTP 500 errors, and no logs for the `/aws/lambda/...` log group are being recorded.

Confirmation: Running a `Test` of the related lambda from the AWS Console fails with the error
> Calling the invoke API action failed with this message: Lambda was unable to decrypt the environment variables because KMS access was denied. Please check the function's KMS key settings. KMS Exception: AccessDeniedExceptionKMS Message: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

![Screen Shot 2022-05-17 at 4 38 20 PM](https://user-images.githubusercontent.com/46407464/168929690-1f434585-55ad-4095-aaaf-fa69caf56c83.png)

Solution: Reset the AWS KMS grant for the lambda function's execution role. Steps can be found on the AWS help page: [How do I resolve KMSAccessDeniedException errors from AWS Lambda?](https://aws.amazon.com/premiumsupport/knowledge-center/lambda-kmsaccessdeniedexception-errors/)

**Comment by theathorn** [comment]
@hannes-ucsc : "This error is not reproducible so we can't demonstrate the scripts efficacy."
