### ISSUE TITLE
Track VPN as a separate component in the security documentation

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4204]
https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.u3tjz35wp6ln

Only two component-specific roles: admin and user.

That way the removal of the developer, project manager and operator roles during off-boarding will implicitly cover the creation and revocation of the certificate.

**Comment by theathorn** [comment]
Dup of #4557.
