### ISSUE TITLE
Create issue template for off-boarding

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4206]
The [documentation](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.u3tjz35wp6ln) of the off-boarding process relies heavily on the removal of roles. This is good in that it avoids duplicating text that could become inconsistent, stale or wrong if only one copy is updated. OTOH, it may be difficult to extract the concrete off-boarding steps from the documentation in that form. Because it would be bad if we were to forget an off-boarding step, I think we should compile a specific checklist in an issue template and add a reminder to the doc about updating the templates (on- and off-boarding).

**Comment by hannes-ucsc** [comment]
For demo, create a test ticket from the template.

**Comment by danielsotirhos** [comment]
Needs heading before very last checkbox.

**Comment by hannes-ucsc** [comment]
The checklist in its current form still mentions the removal of component roles, for example:

> Removed the `Azul modify` role (a component of the `operator` role) from the offboarded employee/contractor for all deployments and all zones.

We want to expand that to the concrete steps that need to be taken.

**Comment by hannes-ucsc** [comment]
For demo, create an issue from the template. Review checklist with team. Close issue.

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "During the demo it was found that some of the actions are in the wrong order. Specifically nomination of replacement systems administrator should precede the changing of GitLab root account credentials. Also, I'm not sure the `or` structure is particularly conducive to our needs."

**Comment by danielsotirhos** [comment]
Bugs encountered during demo:
- In `Organization administrator actions`` section, removing from `Azul Developers` team should be `Azul Admins`.
- replace `for the deployment` with `all deployments`
