### ISSUE TITLE
Health check for private API accepts 403

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4212]

**Comment by theathorn** [comment]
Spike to diagnose, potentially file a ticket with Amazon support.

**Comment by danielsotirhos** [comment]
A `403` response from the health check is expected and appears to be unavoidable when using a custom domain for a private API. The [original article](https://medium.com/codex/aws-private-api-gateway-with-custom-domain-names-350fee48b406#74db) detailing the setup also includes this as part of the configuration.
