### ISSUE TITLE
Configure WAF with rules

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4218]
@hannes-ucsc: "Review managed rules and select the appropriate set of managed rules. Specify custom rules to limit request rates, potentially specific to status code and endpoint."

**Comment by hannes-ucsc** [comment]
We want rate limiting at N (TBD during review) requests per minute and source IP.

We need an IP set where we can quickly add IPs to be blocked.

With respect to other managed rules I want to enable 

- Amazon IP reputation list
- Core rule set
- POSIX operating system

**Comment by hannes-ucsc** [comment]
For demo, show rule set in `dev`. Make request to `dev`. Add own IP to `blocked` IP set. Repeat request. Remove IP again. Repeat request.

**Comment by nolunwa-ucsc** [comment]
@hannes-ucsc what rate limit was configured? The ticket states "We want rate limiting at N (TBD during review) requests per minute and source IP"

**Comment by dsotirho-ucsc** [comment]
> what rate limit was configured?

We currently have a rate limit of 1000 requests allowed in a five-minute period.

https://github.com/DataBiosphere/azul/blob/8b5e9eb128921f86ade07fb8fbcc687d36fd1d1d/terraform/api_gateway.tf.json.template.py#L230

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc thanks
