### ISSUE TITLE
Index updated project into `lm2` on `prod`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4225]
There is an [updated snapshot](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=1910294292) lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220524_lm2 for project https://data-browser.lungmap.net/explore/projects/f899709c-ae2c-4bb9-88f0-131142e6c7ec, which corrects the empty strings for file_core.format for 34 files.

Edit by @danielsotirhos :

> The snapshot mentioned above did not contain the updated entries.
> A new snapshot has been made which has been confirmed to contain the updated 34 analysis files entries.
> Project: `datarepo-360d3b54`, Name: `lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220608_lm2`

**Comment by melainalegaspi** [comment]
@theathorn to contact Eric from CCHMC and Nate from the Broad.

**Comment by danielsotirhos** [comment]
A replacement snapshot has been created.
Project: `datarepo-360d3b54`, Name: `lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220608_lm2`
