### ISSUE TITLE
AC-2 (3) Disable inactive accounts

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4227]
From the [UCSC Azul Data Browser Access Control Procedure](https://docs.google.com/document/d/1_2J_cOFX-Mdn23s_jhmA9eubiDgL0dAYjTbS-AUdWzs):

Planned: The HCA team plans to automatically disable inactive accounts after 90 days. This can be fulfilled by having password expiration for the account in the different environments such as GitHub, GitLab and AWS IAM.

Disable accounts when the accounts:
(a) Have expired;
(b) Are no longer associated with a user or individual;
(c) Are in violation of organizational policy; or
(d) Have been inactive for 90 days

Document disabling inactive accounts in the security architecture doc.
Automatically disable IAM accounts and inactive VPN certifications.

**Comment by theathorn** [comment]
Discuss with Nneka developer vs external user accounts.
@nolunwa Would it be OK to only implement this for external user accounts and rely on manual procedures (off-boarding, account review) for internal ones?

**Comment by theathorn** [comment]
See also #4025.

**Comment by theathorn** [comment]
Team will manually review internal accounts every 90 days.
@danielsotirhos  will document the internal account inactivation procedure for each account type.
There is no need to disable external accounts as the system retains no user information for these.
External accounts are administered by Google, Terra, etc.

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Add section titled `Account Review` to [document](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit) . That section will list the steps required 1) to enumerate accounts for each of the types defined in this document and 2) to determine whether any roles can be removed from an account and 3) to determine whether an account can be disabled."

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "After going through a few example account types I think only I currently have the knowledge to add that section."

**Comment by hannes-ucsc** [comment]
Should include reviewing accounts AND their privileges.
