### ISSUE TITLE
Excessive AWS cost on May 28, 2022

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4228]

**Comment by theathorn** [comment]
Spike to breakdown the cost for that day by service using the Billing Explorer.

**Comment by hannes-ucsc** [comment]
The log volume produced by a reindex has increased significantly in both prod and dev. The blue line is the daily volume, the orange line is the cumulative volume.

![image](https://user-images.githubusercontent.com/5143256/171311563-c6bffd12-8a1c-477a-8c33-25784ff2cf61.png)

![image](https://user-images.githubusercontent.com/5143256/171311756-9b66da28-8865-4f13-be06-dd619a55e221.png)

The first anomalous increase occurred 4/13 in `dev` and 4/7 in `prod`. PR #3411 for #3312 landed in `dev` with 2a7e253d on 3/31 and in `prod` with 098ac71d on 4/7. The anomalous increases coincide with the respective first reindex after the PR lands in either deployment ([dev](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/43521) and [prod](https://github.com/DataBiosphere/azul/pull/4061#issuecomment-1092373158). The latter reindex was partial for one catalog which explains that the bump wasn't as big as the one from 5/27 which was complete and for three catalogs.

**Comment by hannes-ucsc** [comment]
The immediate fix is to ensure that the [`elasticsearch` logger](https://github.com/DataBiosphere/azul/commit/2a7e253d62eb559743797abbc97799194d36a779#diff-11d8abf3f1da9a5204e60e15f069bec0c282699722e60ad7751044d23ff9170aR105) is only active when `AZUL_DEBUG` is 2, along these lines:

```diff
Index: src/azul/logging.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/logging.py b/src/azul/logging.py
--- a/src/azul/logging.py	(revision a593e166fae97a9ec65915dc9df0e016dfb59996)
+++ b/src/azul/logging.py	(date 1654049272090)
@@ -103,7 +103,8 @@
     root_level = root_log_level()
     logging.getLogger().setLevel(root_level)
     es_logger = logging.getLogger('elasticsearch')
-    for logger in {*loggers, azul.log, es_logger}:
+    es_logger.setLevel(es_log_level())
+    for logger in {*loggers, azul.log}:
         logger.setLevel(azul_level_)
 
 
@@ -113,3 +114,6 @@
 
 def azul_log_level():
     return [logging.INFO, logging.DEBUG, logging.DEBUG][azul.config.debug]
+
+def es_log_level():
+    return root_log_level()
```

Not sure yet what the longer term fix is. The first PR should be partial or a follow-up ticket must be filed and a FIXME added.

We should also delete the log streams from the pathological days in `dev` and `prod`, otherwise we'd be paying $80 per month until they are evicted at the end of the retention period.

**Comment by hannes-ucsc** [comment]
The diff above is a sketch, not a specification. The specified goal is to reduce the CloudWatch log charges. The effectiveness of the fix must be verified by an operator in `dev` as part of the PR checklist.

**Comment by danielsotirhos** [comment]
For demo: After deployed to `dev` and a reindex has been run, recreate the CloudWatch metrics graph shown in [Hannes's comment](https://github.com/DataBiosphere/azul/issues/4228#issuecomment-1143035180) and show the difference in log volume produced.
