### ISSUE TITLE
Remove log streams from the pathological days in `dev` and `prod`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4243]
Followup to https://github.com/DataBiosphere/azul/issues/4228.

**Comment by achave11** [comment]
The following log streams were removed from `dev` and `prod` as [requested by lead](https://github.com/DataBiosphere/azul/issues/4228#issuecomment-1143045553).
[azul-indexer-dev.zip](https://github.com/DataBiosphere/azul/files/8922245/azul-indexer-dev.zip)
[azul-indexer-prod.zip](https://github.com/DataBiosphere/azul/files/8922246/azul-indexer-prod.zip)

**Comment by melainalegaspi** [comment]
@hannes-ucsc to specify demo instructions.

**Comment by hannes-ucsc** [comment]
For demo, show days with excessive CloudWatch cost in `prod` and `dev` billing. Show that no log entries exist for those days.

**Comment by achave11** [comment]
Remove all logs for `dev` for the days of 04/14/22 UTC, 05/24/22 UTC and 05/25/22 UTC.

**Comment by achave11** [comment]
ApiGateway log allocation can encompass events ranging widely in the dates. Making it difficult to surgically remove streams of a specific period. Given this info @hannes-ucsc suggested to skip deletion of ApiGateway logs.
