### ISSUE TITLE
ENCODE dataset-level metadata is missing

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4275]
The `AnVIL_ENCODE_default_v1` snapshot in the `datarepo-e8d615a1` project. snapshot has no `study` or `dataset` table from which we could index what we've been referring to on the HCA side as "project-level" information. For #4224, we currently mock this metadata in the indexer plugin with foo. This will look bad during the demo.

Either we need an updated snapshot that ONLY adds the missing tables (has no other changes), or we need to be given instructions on what to place into the mocked metadata.

**Comment by theathorn** [comment]
Email from Kathy: "[Copy of AnVIL ENCODE Dataset Profile.](https://docs.google.com/spreadsheets/d/10ZPGTcKqUufSmMre1JYUvL1zdOyaM9E61x8_yYNsqGk)  No project data for ENCODE."

The above spreadsheet has a "Dataset" tab which specifies "Recommended Column_label" fields for `dataset_id`, `title`, `description` and many additional fields.

**Comment by noah-aviel-dove** [comment]
Info from the spreadsheet visible here: https://service.nadove3.dev.singlecell.gi.ucsc.edu/index/datasets

**Comment by theathorn** [comment]
@hannes-ucsc :"looks good, ideally there should be a commit on the PR branch referring to this issue so that we have a record about how we worked around this. Once the commit exists, the ticket can be unassigned from Noah. a permanent fix will have to come in the form of an updated snapshot".
