### ISSUE TITLE
Index updated LungMAP project on `dev`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4279]
[Snapshot](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=690494292) `lungmap_dev_f899709cae2c4bb988f0131142e6c7ec__20220401_20220629_lm2` with Google Project ID `datarepo-dev-d57fd0c5` fixes the empty file_core.format issue.

Reproduction steps: Go to https://data-browser.dev.lungmap.net/explore/projects?filter=%5B%7B%22facetName%22:%22fileFormat%22,%22terms%22:%5B%22%22%5D%7D%5D, switch to the Files tab and observe that one project has files with a blank file format.

![Screen Shot 2022-06-30 at 2 14 07 PM](https://user-images.githubusercontent.com/46407464/176779597-6d0ce5ae-a4eb-44cb-a448-25ee7aeb2957.jpg)

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
