### ISSUE TITLE
Examine two AnVIL CMG snapshots and updated ENCODE snapshot

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4280]
ANVIL_CMG_UWASH_DS_BAV_IRB_PUB_RD
datarepo-250a2fdd

AnVIL_CMG_UWash_GRU
datarepo-51059aff

**Comment by hannes-ucsc** [comment]
Updated snapshots expected before 8/5/2022 but will look at the aforementioned ones anyways.

**Comment by theathorn** [comment]
Obsoleted by #4355.
