### ISSUE TITLE
`BigQueryReservation` ignores slot deficit in existing commitments

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#4290]
If slots are purchased, and subsequently changes are deployed that would increase the number of purchased slots (e.g. increasing the lambda concurrency), the existing slot commitment is left unmodified. Manual intervention is required to raise the slot capacity of the existing commitment to match the configuration. Ideally, the code that detects the existing commitment would inspect its capacity and make the appropriate modification automatically. We may also want to issue a warning if the existing commitment is *larger* than the updated configuration requires, since automatically shrinking it may not be a good idea.

**Comment by hannes-ucsc** [comment]
For demo, show the desired behavior in the three cases: `actual == required`, `actual < required` and `actual > required`.
