### ISSUE TITLE
IT on prod timeout waiting for queues

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4299]
Prod promotion #4291 failed IT due to a timeout waiting for the queues to empty:

IT Log (failure): https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/23696/raw
Start: 2022-07-08 00:58:15 UTC
End: 2022-07-08 01:57:54 UTC

The promotion (which adds catalog `dcp18`) was reverted and IT completed successfully:

IT Log (success): https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/23738/raw
Start: 2022-07-08 19:03:22
End: 2022-07-08 19:25:52

To test if the new catalog `dcp18` was at cause, `dcp18` was configured to have the same snapshots as `dcp17`. IT completed successfully.

IT Log (success): https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/23751/raw
Start: 2022-07-08 20:49:58 UTC
End: 2022-07-08 21:12:55 UTC

Keeping the `dcp18` catalog equal to `dcp17`, IT was then pinned with the seed value used during job 23696 and IT once again was on track to time out (job was canceled after 55 min). 

IT Log (failure): https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/23773/raw
Seed: 6256089001268341090
Start: 2022-07-08 23:20:03 UTC
End: 2022-07-09 00:15:38 UTC

**Comment by danielsotirhos** [comment]
![Screen Shot 2022-07-08 at 6 56 36 PM](https://user-images.githubusercontent.com/46407464/178089451-ed9dc6f6-3c3c-4798-a6e1-d02115e33106.png)

**Comment by melainalegaspi** [comment]
Assignee to spike for diagnosis.

**Comment by danielsotirhos** [comment]
Spike completed. IT timeout was due to an unfortunate selection of test bundles which meant (1) many bundles had to be partitioned, and (2) there were many duplicated notifications for those bundles.

The fix will be an update to the Operator guide with how to identify this issue in CloudWatch when it occurs, and what steps such as purging the queues for the IT catalogs before IT is tried again.
