### ISSUE TITLE
Maintain a single set of blocked IPs for WAF

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4304]
@hannes-ucsc: "All WAFs in a particular AWS account should share a list of blocked IPs, *IP set* in WAF lingo. The corresponding resource should reside in the `dev.shared` and `prod.shared` components. The WAFs for all deployments should have a rule blocking the IPs in the shared list."

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "This is invalid. We currently do not have any IP sets and #4218 will set them up as resources in the shared component to begin with."
