### ISSUE TITLE
Manage CloudWatch dashboard with TerraForm

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#4307]
Take JSON source of the [production dashboard](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=azul-prod) and use it in a https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_dashboard so that each deployment gets its own dashboard.

The AWS account number, the region and the IDs of the ES cluster nodes are hard-coded in the dashboard JSON and need to be made dynamic. The first two should be easy but the cluster node IDs are tricky. See my comments on https://stackoverflow.com/questions/53837021/aws-elasticsearch-service-get-nodeid-instance-id for inspiration.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to provide description.

**Comment by hannes-ucsc** [comment]
For demo, show the dashboard for `prod` and compare it with the existing one that I created manually. Make a manual, interactive change to the dashboard of a personal deployment in `dev` and integrate that change into the code base.
