### ISSUE TITLE
Rename organCount to organTypeCount

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#431]
What is called `organCount` is de-facto a count of the number of types of organs, not a count of individual organs. If we have specimens from three hearts and three brains, the value of that field is 2, not 6. It should be renamed to reflect the current implementation.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-285)
┆Project Name: azul
┆Issue Number: AZUL-285

**Comment by danielsotirhos** [comment]
This ticket has been made obsolete by completed ticket #885 which removed the summary field `organCount` and added a new field `organTypes` that contains a set of unique organ values instead of just a count
