### ISSUE TITLE
Add AvroPFB manifest format backed by contributions index

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#4311]
The current PFB implementation is plagued by lossyness. Because it is backed by the aggregate index, it conflates (ahem aggregates) entities of all types except `file` type into single rows. For example, all donors contributing to a file are represented by one row in the donors table. The aggregation combines all column values using an aggregate function, typically a sum. Numeric values are added together, string values (like IDs) are placed in a set. The size of the set is capped, depending on the field. The lossyness is expressed in various ways: the size cap of the string sets, the irreversibility of integer sums, and, most importantly, the lack of correlation between the values in the string sets. For two columns A and B that are string sets, it is impossible to determine which set item in A belongs to which set item in B, where "belongs to" stands for "came from the same entity as".

If it weren't for filtering, we could relatively easily switch to using the contributions index in which no aggregation has taken place. Filters are translated to ES queries and those ES queries only work on the aggregate index. I can think of two solutions: 1) introduce a second translation mode that translates the filters into an ES query of a form that works against the contributions index, or 2) join the aggregate index against the contribution index. The latter solution would fetch a batch of IDs of aggregate documents that match the filter, fetch the corresponding batch of contributions and generate the PFB from that.

**Comment by theathorn** [comment]
Is this needed for the stakeholder demo?

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "We should ask the Broad if they think they can implement the workspace population notebook in time for the stakeholder demo."

**Comment by melainalegaspi** [comment]
@hannes-ucsc spike to motivate the need for this work.

**Comment by hannes-ucsc** [comment]
Duplicates #4943 which defines a different implementation strategy.
