### ISSUE TITLE
Test private API with Data Browser team

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4325]
Daniel to standup personal deployment behind a VPN and Data Browser team to switch anvil.dev... to that deployment so we can test what happens when the Data Browser is visited by a user that's a) not connected to the VPN and b) connected to the VPN.

**Comment by danielsotirhos** [comment]
Personal deployment behind `azul-gitlab-dev` VPN: https://service.daniel2.dev.singlecell.gi.ucsc.edu/

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "This is now redundant since we will get this for free when we do databiosphere/data-browser#4756"
