### ISSUE TITLE
Delete old trail bucket in prod

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4326]
Copy contents of `platform-hca-cloudtrail` to `edu-ucsc-gi-platform-hca-prod-cloudtrail` and then delete `platform-hca-cloudtrail`.

**Comment by hannes-ucsc** [comment]
Triage when blocker lands in prod.

**Comment by achave11** [comment]
Contents of `platform-hca-cloudtrail` have been copied to `edu-ucsc-gi-platform-hca-prod-cloudtrail` and deleted from original bucket. 
```
$ aws s3 ls --recursive s3://platform-hca-cloudtrail --human-readable --summarize

Total Objects: 0
   Total Size: 0 Bytes
```
ATM the bucket is being emptied through the console, it wasn't being removed via the CLI, perhaps due to versioning.

**Comment by hannes-ucsc** [comment]
Looks good.
