### ISSUE TITLE
Talk to Trevor about assigning technical admin for JIRA

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#4333]
Action item from 7/22/2022 retrospective.

**Comment by melainalegaspi** [comment]
@theathorn to talk to Charles Overbeck about this.

**Comment by theathorn** [comment]
Response from Charles: "I’m not a JIRA admin and can’t really envision what useful info I might have."

**Comment by melainalegaspi** [comment]
@melainalegaspi to provide list of current JIRA admins.

**Comment by melainalegaspi** [comment]
![Screen Shot 2022-07-26 at 12.03.16 PM.png](https://images.zenhubusercontent.com/5cb8d2ec67d6eb305bc6fd58/ab4dc6d0-dda3-403c-bcac-0af28aa79a41)

"Site admins can perform these site operations:
Access the site's Admin at https://admin.atlassian.com.
Make other users site or product admins.
Site settings so that it displays your company's branding and image.
Administer users for your site, meaning you can invite, remove, and export users, among other things.
Groups and product access, meaning you can update settings for how users get access and adding users to groups.
 
Organization admins can perform these organization operations:
Access your organization at admin.atlassian.com.
Make other users organization admins.
Verify or remove domains for your organization.
Subscribe to Atlassian Access and apply security policies on managed accounts.
Managed accounts, meaning you can edit details and deactivate or delete accounts, among other things." (https://community.atlassian.com/t5/Jira-questions/What-is-different-between-org-admin-site-admin-and-product-admin/qaq-p/1707926)

**Comment by theathorn** [comment]
@theathorn to confirm that Erich will be the technical contact for issues for Jira.

**Comment by theathorn** [comment]
Erich: "I can be that person."
