### ISSUE TITLE
Conduct annual review of the rule set for audited events

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4346]
Per @nolunwa's comment in #4035: "We should open a ticket for the annual review of the audited events (the rule set), we can assign the ticket or have a meeting to perform the review of the rule set."

**Comment by melainalegaspi** [comment]
Triage during Thursday 10 a.m. compliance meeting.

**Comment by hannes-ucsc** [comment]
Duplicates #4035.
