### ISSUE TITLE
Create JIRA tickets for ENCODE snapshot issues

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4354]
[Broad JIRA Instructions](https://docs.google.com/document/d/1BFpHfXjU2WFR6ap6TYru0COW86krailZdROqCfTNyr8).
[AnVIL Data Explorer Epic](https://broadworkbench.atlassian.net/jira/software/projects/DI/boards/145?issueParent=51220).
[AnVIL ENCODE snapshot issues](https://docs.google.com/document/d/1WMI8_cuYIzKEZa-pEENsC1r5Zrf4JBY6Br6AL6iJjFc).

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Finished triaging the tickets with Nate and Mike."
