### ISSUE TITLE
CA-8 PENETRATION TESTING

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4363]
The organization conducts penetration testing [FedRAMP Assignment: at least annually] on [Assignment: organization-defined information systems or system components].

**Comment by nolunwa** [comment]
This will be performed with the external security control assessment

**Comment by nolunwa** [comment]
Pen testing Overview

- The pen Testing will include the 6 Attack vector provided by FedRAMP
- Network and web application penetration test against UCSC Azul Data Browser
- Pen Testing will be done on an environment that is a mirrored version of Prod
-  IAM Role will be created for the Audit Team

-

**Comment by nolunwa** [comment]
https://docs.google.com/document/d/10-wTDzmSdJVbY7bjMkINF6h1nUH7WFciO_Bduzvngfk/edit#heading=h.33c6uzxsgd2g

**Comment by nolunwa-ucsc** [comment]
Pen Test was done with the Assessment in March 2023
