### ISSUE TITLE
Replace snapshot `AnVIL_ENCODE_default_v1` with TBD in personal AnVIL deployment

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4367]
https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274

Supposedly it's a drop-in replacement but if columns were removed or renamed, record this here and make the necessary changes to the BQ queries. The replacement snapshot is also supposedly fixing the bad foreign keys. The workaround for dangling FKs is removed as part of #4355. If there are still danlging FKs, pause work. We'll request a new snapshot. The `dataset` table was added. The workaround for the missing `dataset` table was removed as part of #4355, too.

Edit:

We're abandoning the effort to integrate encode_in_anvil_all_data because it still has dangling foreign keys. Waiting for an updated encode snapshot to replace it.

**Comment by theathorn** [comment]
May want to switch to "encode_in_anvil_v5_full_view".

**Comment by theathorn** [comment]
Kathy states we should always be indexing the findability snapshot which in this case is [row 11](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274):
Snapshot name: `Encode_in_anvil_findability_v1`
Google Project ID: `datarepo-506e6200`

**Comment by theathorn** [comment]
`encode_in_anvil_all_data` is the latest candidate.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"we're abandoning the effort to integrate `encode_in_anvil_all_data` because it still has dangling foreign keys. Waiting for an updated encode snapshot to replace it."

**Comment by theathorn** [comment]
@hannes-ucsc :"No need for ENCODE in AnVIL in the foreseeable future. The Broad employee advocating for this has since left".

**Comment by hannes-ucsc** [comment]
Closed connected PR https://github.com/DataBiosphere/azul/pull/4397

**Comment by hannes-ucsc** [comment]
No ENCODE snapshot in the [spreadsheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274) in either TDR dev or prod. We'll deal with ENCODE again when we have a snapshot for it.
