### ISSUE TITLE
Create one personal AnVIL deployment to be colocated with `anvildev`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4369]
Create a personal deployment (e.g. `nadove4`) in AWS account (and GCP project) `platform-anvil-dev`. The `anvilbox` deployment can be used as a template, except for the catalog configuration (`anvilbox` and `anvildev` refer to HCA snapshots still). The `nadove4` deployment should point at the same EnCODE snapshot (with a prefix) as the `nadove2` and `nadove3` deployments. The `nadove4` deployment should be private i.e. only accessible through the VPN.

Change the existing personal AnVIL deployments to share a ES domain with the `sandbox` deployment. Make sure the personal ES domains are gone.

**Comment by hannes-ucsc** [comment]
Erich supposedly already gave @noah-aviel-dove access, so the first order of business is configuring the above AWS account and GCP project for interactive and programmatic access. VPN and GitLab access is next.

https://github.com/DataBiosphere/azul#232-aws-credentials
https://github.com/DataBiosphere/azul#233-google-cloud-credentials
https://github.com/DataBiosphere/azul#911-requesting-access

The AnVIL GitLab instance is https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/pipelines
The `anvilbox` Azul instance (the equivalent of sandbox for AnVIL) is at https://service.anvilbox.anvil.gi.ucsc.edu/

`anvilbox` is still public. See https://github.com/DataBiosphere/azul/issues/4373. 

`anvildev` hasn't been deployed yet. We'll sit on that for a bit.

Let's aim for finishing this before EOD Wed 10

For demo, show the personal deployment's Swagger UI, show that the deployment is private. Show that access to GitLab `anvildev` is working.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "Made a mistake regarding the original deployments nadove2 and 3. One of them should be kept alive and share an ES domain with sandbox but index the encode snapshot with a 2 digit prefix or whatever prefix indexes in about 1 hour."

**Comment by hannes-ucsc** [comment]
![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/149c0813-fa20-4ced-a1aa-bfbb11f66bab)

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/dec58cae-bfac-4731-ba82-94202c656b77
)

**Comment by hannes-ucsc** [comment]
![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/8807d1d9-0980-420e-aef4-d05447f92730)
