### ISSUE TITLE
Provide ITS with a service account access token to use for authenticated scans

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4374]
@hannes-ucsc:

> Looks like the captcha check can't be prevented for Google user accounts: https://issuetracker.google.com/issues/67954589
> 
> We should try using a service account instead. In this scenario we would provide ITS with a fixed bearer JWT that goes into the `Authorization: Bearer ...` request header. I just learned about the possibility of this:
> 
> https://developers.google.com/identity/protocols/oauth2/service-account
> 
> It would side-step the need for the scanner to implement any authentication flows. It would just require pinning the `Authorization` header sent by the scanner to a fixed value. The question is how long we can make the expiration of that fixed bearer JWT and if TDR accepts it. If TDR doesn't accept it, this is a no go. If the expiration is short we would need to provide ITS with the ability to generate a new one before every scan.
> 
> We can test this by having someone on the Azul team sign a JWT as described in the above link, using a service account that is already registered with TDR, and then hand that JWT to Jevan to configure the Authorization header.
> 
> The signing procedure is documented here: https://developers.google.com/identity/protocols/oauth2/service-account#jwt-auth

**Comment by danielsotirhos** [comment]
We've decided to use an access token instead of JWT due to:
- Unsure what value to specify as the audience claim ('aud')
- JWT has an expiration of 1 hour (same as an access token)
- We already have code to generate access tokens via `ServiceAccountCredentialsProvider`

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "I documented my position to not perform authenticated scans in an email thread titled 'UCSC Azul Monthly Web Application Scan - Invicti'. Somehow this decision needs to be captured in the SSP. Trevor to coordinate with Nneka about that."

**Comment by theathorn** [comment]
[Slack thread](https://ucsc-gi.slack.com/archives/C02B4S0V6GH/p1661804255981549):
@theathorn : Are you OK with @hannes  approach to not use authenticated scans and where should this decision be documented in the SSP and by whom?
@nolunwa : Yes I am and i will document that in the SSP - no further action from the team.
