### ISSUE TITLE
Establish a feature/commons2

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#438]
1) Review Hannes' plan
2) Choosing from where to branch
3) Coming up with a baseline plan for how to do a plugin for the Commons Indexer

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-289)
┆Project Name: azul
┆Issue Number: AZUL-289
┆Epic: Re-implement the Azul and Dash

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
