### ISSUE TITLE
Fill in types of users in security architecture doc

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4388]
[Security and Privacy Controls for the UCSC Genomics Institute Data Browser](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0)

**Comment by hannes-ucsc** [comment]
https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.g8xhw0txacqe

**Comment by hannes-ucsc** [comment]
@nolunwa could you please review the section I added?

**Comment by hannes-ucsc** [comment]
I'm unassigned myself as this is clogging up my board.
