### ISSUE TITLE
Break out SSP into one document per control family

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4389]
The [[Initial Draft] UCSC Azul Data Browser SSP v1](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r) is too unwieldy to edit/review.

**Comment by nolunwa** [comment]
This is WIP and all the SOP has been added to the compliance drive

**Comment by nolunwa-ucsc** [comment]
was done before the assessmnet in March 2023
