### ISSUE TITLE
Recreate Auth for Azul to Datastore

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#439]
It is undelare as to how this will work as a plug-in or as configuration.  But we would like to see the new Azul indexer working with Commons Blue Box

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-291)
┆Project Name: azul
┆Issue Number: AZUL-291
┆Epic: Re-implement the Azul and Dash

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
