### ISSUE TITLE
Delete DSS related SNS subscriptions in dev account

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4394]
Delete the SNS subscriptions in the `platform-hca-dev` account that point to DSS related SNS topics that no longer exist.

ID | Endpoint | Status | Protocol | Topic
-- | -- | -- | -- | --
11ec2409-488e-463f-b1ca-005f02d610cf | arn:aws:lambda:us-east-1:122796619775:function:dss-scalability-test-dev | Confirmed | LAMBDA | dss-scalability-test-run-dev
023692e1-8422-4697-aa29-61508aaf4a2a | arn:aws:lambda:us-east-1:122796619775:function:dss-sfn-launcher-dev | Confirmed | LAMBDA | dss-sfn-dev
f3487720-9aa8-400d-89c9-0d607eaa1480 | arn:aws:lambda:us-east-1:122796619775:function:dss-scalability-test-dev | Confirmed | LAMBDA | dss-scalability-test-dev
60b213e4-0781-42bf-951d-6c945ef49773 | arn:aws:sqs:us-east-1:122796619775:domovoi-s3-events-ucsc-cgp-dss-dev-dss-sync-sfn-dev | Confirmed | SQS | domovoi-s3-events-ucsc-cgp-dss-dev
4d1ddf28-57d8-4335-b922-c593a2b2ff4c | arn:aws:sqs:us-east-1:122796619775:domovoi-s3-events-ucsc-cgp-dss-dev-dss-index-dev | Confirmed | SQS | domovoi-s3-events-ucsc-cgp-dss-dev
cfbaa764-ff5b-4d4a-b329-ad68618b068a | arn:aws:sqs:us-east-1:122796619775:dss-sync-dev | Confirmed | SQS | dss-gs-events-ucsc-cgp-dss-dev
ff2f597b-83ac-4322-9a32-c4874fd6bcf6 | arn:aws:sqs:us-east-1:122796619775:domovoi-s3-events-ucsc-cgp-dss-dev-dss-notify-v2-dev | Confirmed | SQS | domovoi-s3-events-ucsc-cgp-dss-dev
5ee86d17-40fb-4415-9f8f-9667466d08ca | arn:aws:sqs:us-east-1:122796619775:dss-index-dev | Confirmed | SQS | dss-gs-events-ucsc-cgp-dss-dev
ac9c2793-e347-4a0a-97ee-f9e18f3b3223 | arn:aws:sqs:us-east-1:122796619775:dss-notify-v2-event-relay-dev | Confirmed | SQS | dss-gs-events-ucsc-cgp-dss-dev

**Comment by hannes-ucsc** [comment]
LGTM. Thank you for this, @danielsotirhos.

**Comment by danielsotirhos** [comment]
The DSS related SNS subscriptions on the dev account have been deleted.

![Screen Shot 2022-08-22 at 1 02 12 PM](https://user-images.githubusercontent.com/46407464/186008937-ad81ea17-5eba-4f21-953a-36cf8a44d2f7.png)

**Comment by achave11** [comment]
Confirmed that no DSS related SNS subscriptions remain on the `dev` account. 
![Screen Shot 2022-08-24 at 10 11 42 AM](https://user-images.githubusercontent.com/19215510/186480932-6d94549a-8145-4a4b-864b-f57aef01f9c1.png)

**Comment by hannes-ucsc** [comment]
Looks good.
