### ISSUE TITLE
AnVIL deployments conflate indexer and public SAs

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4398]

**Comment by melainalegaspi** [comment]
@hannes-ucsc to create blocking data-browser ticket.

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/4616#issuecomment-1622190952

**Comment by hannes-ucsc** [comment]
For demo, show that sign-in works in the Data Browser in anvilprod. Before signing in, only donors, biosamples, activities and files from public snapshots (currently 1000G) should be visible. After signing-in as a member of the Terra group `azul-anvil-prod`, all entities from all snapshots should be visible.
