### ISSUE TITLE
Process=>protocol field change to metadata

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#44]
Metadata v6: fields in type/process schemas will be moving to type/protocol schemas on Monday 4 June.

https://humancellatlas.slack.com/files/U6CB89VLJ/FAX897Y8P/HCA_Metadata_Standard_Proposed_Major_Update____process_schema_fields_to___protocol_schemas

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-73)
┆Project Name: azul
┆Issue Number: AZUL-73
┆Epic: Insulate Indexer from metadata

**Comment by hannes-ucsc** [comment]
This was handled as part of #187
