### ISSUE TITLE
Build a plug-in for GEN3 indexer

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#440]
1) Create tests for the GEN3 indexer
2) Create the plugin
3) demonstarte the working of the plugin with the test harness

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-290)
┆Project Name: azul
┆Issue Number: AZUL-290
┆Epic: Re-implement the Azul and Dash

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
