### ISSUE TITLE
Hard to prevent default VPN route using Viscosity

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4408]
Just following the README instructions for split tunnels for Viscosity don't work, at least not on Windows. Viscosity still creates those pseudo default routes 0.0.0.0/1 and 128.0.0.0/1, at least on Windows. To fix that, one has to additionally insert `pull-filter ignore redirect-gateway` on the *Advanced* tab of Viscosity's profile editor window. The question remains as to why the README instructions are sufficient on macOS. 

`pull-filter ignore redirect-gateway` should be mentioned in the `.ovpn` file that `make -C terraform/gitlab/vpn config` generates or document how to add that using the *Advanced* tab of Viscosity's profile editor window. Including it in the `.ovpn` might make redundant the manual steps for `Network Manager` on Linux.

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "I think I addressed this in 4e0d90e4d83b12b0f115740558875d6cbf9891c2 but need to confirm."

**Comment by hannes-ucsc** [comment]
This was partially addressed in commit 4e0d90e4 of PR #4431 for #3930, specifically [this hunk](https://github.com/DataBiosphere/azul/commit/4e0d90e4d83b12b0f115740558875d6cbf9891c2#diff-aa56a1bd64e37b658e523f5b98ec63846cacd06a91c472325ccd546ef5bb1537R54).

Those changes prevent Viscosity on macOS from adding the default route (or the split pseudo-default route), even if the server pushes a `redirect-gateway` configuration (the pull filter takes care of that). The generated .ovpn file should work out of the box. I left the README section on split tunnels in place, though, just in case Viscosity changes its behavior in the future.

The same applies to Tunnelblick,

The above changes do not eliminate the manual Network Manager steps on Linux. NM ignores the `redirect-gateway` config and has a separate, independent toggle for enabling/disabling the default route, a toggle that's not influenced by what's in the .ovpn or what the server pushes.

I'd prefer it if @theathorn could test an updated .ovpn file with Viscosity on Windows.

**Comment by melainalegaspi** [comment]
@theathorn will ping @hannes-ucsc for updated .ovpn file

**Comment by theathorn** [comment]
New profile installed and confirmed working.
