### ISSUE TITLE
Deployment of Commons Azul indexer with an Existing ES

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#441]
1) This would involve updating the deployment instructions
2) This would involve separating out the deploymnet from TerraForm or setting up terra form for Commons

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-292)
┆Project Name: azul
┆Issue Number: AZUL-292
┆Epic: Re-implement the Azul and Dash

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
