### ISSUE TITLE
Formalize our stance on authenticated scans

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4416]

**Comment by hannes-ucsc** [comment]
Responded to email thread as follows:

> To close the loop: Daniel and Jevan tried a scan with a hard-coded access token. For the Data Browser, passing an access token has no effect since the Data Browser UI ignores it. The UI expects a session cookie and those are not documented by Google. Passing a token to the Azul API did work initially but the token expired mid-scan, as expected. This actually reduced the depth of the scan because an invalid token causes an empty 403 response, while passing no token generates a fully populated 200 response. In other words, an unauthenticated scan covers more of the site than an authenticated scan with a token that expires mid-scan.
>
> I've come to the concussion that we aren't gaining any insights with an authenticated scan. The way access controls are implemented in Azul and the Data Browser, authenticated requests don't actual return more pages, or unlock areas of the site that are not accessible via unauthenticated requests. The only difference between authenticated and unauthenticated requests to the API is that the former potentially contain more hits (metadata items), otherwise they are functionally identical. In particular, authenticated requests don't provide access to modifications simply because the API is read-only, regardless of authentication.
> 
> To summarize: 1) Authenticated scans of the API with a 1h access token reduce scan coverage. 2) The UI ignores access tokens. 3) Based on Jevan's assessment, Invicti's OAuth 2.0 implementation triggers a captcha which the Invicti can't automatically solve.
> 
> For these reasons, we are going to de-prioritize authenticated scans until the API offers long-lived API tokens (as opposed to short-lived access tokens) or we switch to a scanner that somehow avoids the captcha, by interactively pre-authenticating the scan, for example.

**Comment by hannes-ucsc** [comment]
@nolunwa, is the above rationale sufficient for inclusion in the SSP?

**Comment by theathorn** [comment]
See [Slack thread](https://ucsc-gi.slack.com/archives/C02B4S0V6GH/p1661804255981549) where @nolunwa states that it is OK to not use authenticated scans and that she will document this in the SSP.

**Comment by nolunwa** [comment]
SSP and SOp updated
