### ISSUE TITLE
Non-route lambda handlers in service log hardcoded `requestId`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4418]
Interestingly only the service is affected even though both app.py modules initialize logging in the same way:

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-indexer-dev, /aws/lambda/azul-indexer-dev-aggregate, /aws/lambda/azul-indexer-dev-aggregate_retry, /aws/lambda/azul-indexer-dev-contribute, /aws/lambda/azul-indexer-dev-contribute_retry, /aws/lambda/azul-indexer-dev-indexercachehealth, /aws/lambda/azul-service-dev, /aws/lambda/azul-service-dev-manifest, /aws/lambda/azul-service-dev-servicecachehealth  
start-time: -2419200s  
end-time: 0s  
query-string:
```
fields @log
| filter @message like "00010ca1-b0ba-466f-8c58-dabbad000000"
| stats count(*) by @log
```
---------------------------------------------------------------------------
|                             @log                             | count(*) |
|--------------------------------------------------------------|----------|
| 122796619775:/aws/lambda/azul-service-dev-servicecachehealth | 41803    |
| 122796619775:/aws/lambda/azul-service-dev-manifest           | 3673     |
---------------------------------------------------------------------------

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Assignee to reproduce in personal deployment and to use Jesse's remote debugging instructions to further diagnose the cause."

**Comment by hannes-ucsc** [comment]
For demo, one week after the fix lands in `dev`, show that no log entries containing that hard-coded UUID occur in any of the Lambda logs for that deployment. Show that such entries do exist prior to the fix landing.
