### ISSUE TITLE
Terra group membership is not covered in on- and off-boarding procedures

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4419]

**Comment by hannes-ucsc** [comment]
This is covered in #4206. I just changed [the ](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.9mn956snpwbu) to give internal users `Terra private`.

**Comment by hannes-ucsc** [comment]
Reassigning to @danielsotirhos. After expansion of roles is addressed by a third PR for #4206, there should be a PR for this issue in which 1) the removal of the Terra private role is expanded to the removal of the offboarded user from any Terra groups they are mentioned in and 2) the removal of the Terra admin role is expanded to unticking the "Can administer group" checkbox for the group member.

**Comment by dsotirho-ucsc** [comment]
> 2) the removal of the Terra admin role is expanded to unticking the "Can administer group" checkbox for the group member

@hannes-ucsc: "This is obviously not correct for offboarding since offboarding does not demote someone from Terra Admin to Terra Private, it only completely removes their access so unticking the checkbox is nonsensical if the member is completely removed from the group."

**Comment by theathorn** [comment]
@hannes-ucsc :"I think this was addressed recently".

**Comment by hannes-ucsc** [comment]
Turns out it still needs to be addressed for on-boarding.

**Comment by dsotirho-ucsc** [comment]
This will be solved by the solution for #4205.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
