### ISSUE TITLE
Restructure Dashboard service to the same structure as Azul webservice

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#442]
This is the pre-step to a plug-in for the webservice.  We would restructure the Dashboard Service to be in the same structure as Azul Webservice so that we could see where the differences are.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-293)
┆Project Name: azul
┆Issue Number: AZUL-293
┆Epic: Re-implement the Azul and Dash

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
