### ISSUE TITLE
Complete "Table 13-3. CA-3 Authorized Connections" in SSP

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4423]
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/e0a248b6-c3d5-426c-aa59-2c5549f7ce1b)

**Comment by hannes-ucsc** [comment]
Add link to the respective section in SSP, please.

**Comment by theathorn** [comment]
Section [CA-3 System Interconnections](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.3dhjn8m).

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "the table for CA-3 must have the same rows as the table for SI-4. The CA-3 table only adds information about connection agreements and when they were signed. This is not a technical implementation. @theathorn to discuss with @nolunwa ."

**Comment by theathorn** [comment]
@nolunwa [Table 11-1 System Interconnections](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.37m2jsg) lists the Broad Institute, GitHub, Docker and the Python Software Foundation. We don't have a "Signed Connection Agreement" with any of these, and it seems likely we only would have a signed agreement with the Broad. How should we proceed?

**Comment by theathorn** [comment]
Update table 13-3 with links to "Terms of Service" or "Interconnections Service Contract (ISC)" for each row.

**Comment by theathorn** [comment]
Updated [Table 13-3](https://docs.google.com/document/d/1fEuSP7l5_7mdBevI3ji_6SFvOnf28nUJQmSYbQ2krsk/edit#heading=h.1smtxgf) in  UCSC Azul Data Browser Assessment and Authorization Procedure.

**Comment by nolunwa** [comment]
Looks good, added System Owner (Benedict Paten) as the role and name of person to sign

**Comment by nolunwa** [comment]
@theathorn ok to close ticket

**Comment by nolunwa-ucsc** [comment]
SSP updated
