### ISSUE TITLE
Eliminate personal service accounts

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4424]
#2528 requires 2FA for organizational users. Our developers currently use a personal service account. The credentials (a private key) for that account are stored in a file on the developer's machine. Service accounts do not support 2FA. We should replace them with `gcloud login` which would enable the 2FA authentication enforced by ITS.

Clever Canary would have to certify in writing (in a contract, for example) that they have 2FA enabled on their Google Workspace for `clevercanary.com`.

**Comment by hannes-ucsc** [comment]
Spike to test this by removing (or hiding) the personal service account credentials from a developer machine and running `make deploy` on a new deployment. Address any easy to fix issue (references to GOOGLE_APPLICATION_CREDENTIALS, for example) but abort spike on more protracted issues. The outcome of the spike should enable us to estimate the issue.

**Comment by danielsotirhos** [comment]
Using the patch below (after removing `GOOGLE_APPLICATION_CREDENTIALS` running `gcloud auth login`) I was able to deploy a new deployment, complete a reindex, and get successful responses from the deployment's endpoints.

```
Index: scripts/provision_credentials.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/provision_credentials.py b/scripts/provision_credentials.py
--- a/scripts/provision_credentials.py	(revision dfb5ff17b4b3a11a58456974cbe1f5b4ad36cced)
+++ b/scripts/provision_credentials.py	(date 1662147683304)
@@ -6,9 +6,8 @@
 import time
 import uuid
 
-from google.oauth2 import (
-    service_account,
-)
+
+import google.auth
 import googleapiclient.discovery
 from googleapiclient.errors import (
     HttpError,
@@ -32,9 +31,9 @@
 
 
 def get_google_service():
-    credentials = service_account.Credentials.from_service_account_file(
-        filename=os.environ['GOOGLE_APPLICATION_CREDENTIALS'],
-        scopes=['https://www.googleapis.com/auth/cloud-platform'])
+    credentials, project_id = google.auth.default(
+        scopes=['https://www.googleapis.com/auth/cloud-platform']
+    )
     return googleapiclient.discovery.build('iam', 'v1', credentials=credentials)
 
 
```


```
$ http 'https://service.daniel3.dev.singlecell.gi.ucsc.edu/index/summary?catalog=dcp2' | jq
{
  "projectCount": 105,
  "specimenCount": 889,
  "speciesCount": 2,
  "fileCount": 3440,
  "totalFileSize": 10967869203586,
  "donorCount": 653,
  "labCount": 204,
  "organTypes": [
    "blood",
    "brain",
    "skin of body",
    "kidney",
...
```

```
$ http 'https://service.daniel3.dev.singlecell.gi.ucsc.edu/index/projects?catalog=dcp2' | jq
{
  "pagination": {
    "count": 10,
    "total": 105,
    "size": 10,
    "next": "https://service.daniel3.dev.singlecell.gi.ucsc.edu/index/projects?catalog=dcp2&filters=%7B%7D&search_after=%5B%22A+survey+of+human+brain+transcriptome+diversity+at+the+single+cell+level%22%2C+%2252b29aa4-c8d6-42b4-807a-b35be94469ca%22%5D&sort=projectTitle&order=asc&size=10",
    "previous": null,
    "pages": 11,
    "sort": "projectTitle",
    "order": "asc"
  },
  "termFacets": {
    "organ": {
      "terms": [
        {
          "term": "blood",
          "count": 19
        },
        {
          "term": null,
          "count": 15
        },
...
```

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "we still need to solve the problem of re-authentication when switching deployments so that the developer is prompted to re-authenticate with GCS when switching to a deployment that uses a different google account or when the authentication session has expired. Ideally, wouldn't need to re-authenticate when the session is valid and uses the same google account as the previously selected deployment."

**Comment by hannes-ucsc** [comment]
Since we all need to upgrade our deployments with this change, it will be immediatly evident if this doesn't work. No demo.

**Comment by hannes-ucsc** [comment]
For demo, show that all personal service accounts are gone from all Google projects.
