### ISSUE TITLE
Our use of ucsc.edu accounts violates AC-6 (2)

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4429]
[SSP Section AC-6(2)](https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit#heading=h.1opuj5n).

> We should define non-security functions as all those that make use of the application as an end user would, and security functions to be all remaining functions. The latter would include operating the system, contributing code to it, managing permissions and accounts. With that definition we pretty much implement this control. There is one exception: our ucsc.edu Google Workspace accounts can be used to log into the application AND to log into the Google Cloud console to manage it. We'd have to find a solution to that. That's the only issue I can think of.

From https://docs.google.com/document/d/1lA5KF1ARfUX_T5UXLMv8tj-1aKNazT9r/edit?disco=AAAAXyKmcYA

**Comment by theathorn** [comment]
Isn't it OK to use the same account to log into the application and into the Google Cloud console as long as the privileges for the account are set appropriately in each system?

**Comment by melainalegaspi** [comment]
@theathorn to discuss roles with @nolunwa

**Comment by hannes-ucsc** [comment]
The control enhancement actually reads

> The organization requires that users of information system accounts, or roles, with access to [Assignment: organization-defined security functions or security-relevant information], use non- privileged accounts or roles, when accessing nonsecurity functions. 

I missed the "or roles" part. We (the team) do access the Data Browser UI in a non-security function using our `@ucsc.edu` account, but we do in-fact use a separate role for that, except that my doc (https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#) doesn't currently capture that correctly. This is something for me to fix.

**Comment by hannes-ucsc** [comment]
Roles have been separated. There is now the [Backend modify](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.uiag3uhvnbh0) role and the [Frontend private](https://docs.google.com/document/d/1Kg0dMZmCw6gtkvabD2jYWPZO2Mx_wsC8BJPKdeKTfg0/edit#heading=h.qwtn42rktb8w) role. The same person can perform a function that includes these two roles, and use the same account, but they'd be acting in a different roles depending on whether they access the frontend or modify a backend.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"Ticket is not valid as described. The security architecture document now adequately describes the role separation."
