### ISSUE TITLE
Figure a Full deploy of feature/commons2

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#443]
Work out a complete deploy with terraform of the azul GEN3 indexer and the dashboard serivces redo.  This will involve setting up a new deployment mechanism for Commons.  After this, I would like to say that we would be ready to deprecate feature/commons 1 and redeploy dev and staging.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-294)
┆Project Name: azul
┆Issue Number: AZUL-294
┆Epic: Re-implement the Azul and Dash

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
