### ISSUE TITLE
Add support for Ingest spreadsheets to the DCP/2 System Design

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4436]
[Slack thread](https://humancellatlas.slack.com/archives/C03VB103H63/p1661993695564459) with @hannes-ucsc design proposal.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to spike for filing PR against spec.

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Need follow up ticket for implementation work."

**Comment by theathorn** [comment]
See #4488.
