### ISSUE TITLE
Enable CORS on the /projects/:id endpoint

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#444]
We are seeing a CORS error trying to request the projects/id endpoint from localhost.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-295)
┆Project Name: azul
┆Issue Number: AZUL-295

**Comment by hannes-ucsc** [comment]
CORS should be enabled. Can you provide the stack trace or error message?

https://github.com/DataBiosphere/azul/blob/5bdc9fc708e273b5f870837d5aa2d700b368ed14/lambdas/service/app.py#L243

**Comment by NoopDog** [comment]
This was a problem with the URL on our end. closing.
