### ISSUE TITLE
CA-9 Internal System Connections

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4447]
Write the SSP entry for this control. Use the Dockstore version below for inspiration.

**Comment by nolunwa** [comment]
The Dockstore system is designed and configured to authorize internal connections of the components that are part of the Dockstore system with an exception to when necessary to provide access to public traffic.

All internal system connections are configured using security groups to deny all traffic and only allow authorized connections using IAM or by specifically identifying a resource as allowed by the security group. AWS security groups are configured similar to host-based firewalls with the additional capability of restricting traffic to specific Amazon resources by their unique identifier. For more information see SC-7.

In addition to restricting access between components using firewalls, secondary authorization is needed for accessing the database. This is performed using a username and password combination.

The Grafana instance is available to the public internet at port 3000, however, accounts are only available for organizational users. They must authenticate using their GitHub account and use MFA.

Interconnections between Amazon resources that don’t have a security group are authorized using IAM policies. These configurations are described in code when possible and only allow authorized connections between devices.

Remote sessions on instances are authorized using IAM groups as described in AC-2. The connection between a developer and the instance is managed by the AWS console. Developers must authorize and authenticate using AWS IAM and their connection uses TLS.

**Comment by nolunwa** [comment]
Important to note as we document this control.

- defines system components to be considered and authorized as internal connections to the system"


- How do we authorize internal connections

- documents, for each internal connection: the interface characteristics, the security requirements, the nature of the information communicated.

**Comment by theathorn** [comment]
[CA-9 description](https://www.stigviewer.com/controls/800-53/CA-9).

**Comment by hannes-ucsc** [comment]
Essentially this means documenting the edges in the networking diagram. Just like #4571 requires documenting the edges in the data flow diagram.

**Comment by hannes-ucsc** [comment]
Offloading some of my Sprint column.

**Comment by theathorn** [comment]
Update [this section](https://docs.google.com/document/d/1fEuSP7l5_7mdBevI3ji_6SFvOnf28nUJQmSYbQ2krsk/edit?disco=AAAAfvHZgxo) of the UCSC Azul Data Browser Assessment and Authorization Procedure.

**Comment by hannes-ucsc** [comment]
https://docs.google.com/document/d/1bjBnBusauDEiRNHOAM7vwGrL-GPlE-YcLQIBrE6SOdI/edit
