### ISSUE TITLE
Network diagram is missing WAF for private API

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4448]

**Comment by danielsotirhos** [comment]
Confirmed functionality of the WAF when applied to a private API. Tested with a simple rate-based rule blocking requests when a source IP has made 100 or more requests within 5 minutes.

![Screen Shot 2022-09-14 at 5 34 11 PM](https://user-images.githubusercontent.com/46407464/190286653-75aebe35-849e-4cb4-afe3-9281a73579e0.png)

Also it is worth noting the `Source IP` reported in the sampled requests reflects the availability zones of the load balancer, specifically `us-east-1b` (172.71.3.0/24) and `us-east-1a` (172.71.1.0/24)

![Screen Shot 2022-09-14 at 5 35 55 PM](https://user-images.githubusercontent.com/46407464/190287253-bd4b06b5-8916-4580-bb2a-e86bc3c20b93.png)

For comparison, here is the same table from the WAF on my public deployment after repeating similar requests to `/summary` endpoint.

![Screen Shot 2022-09-14 at 5 35 26 PM](https://user-images.githubusercontent.com/46407464/190287773-062ec40f-5316-4b28-8c09-ca8686c65819.png)

**Comment by danielsotirhos** [comment]
I can confirm the `Source IP` listed in the WAF's "Sampled requests" section are the IP addresses of the load balancer.

The `Source IP` column has two unique IP addresses, `172.71.1.97 (UZ)` and `172.71.3.116 (BF)`. Following the steps provided in this [AWS knowledge center article](https://aws.amazon.com/premiumsupport/knowledge-center/elb-find-load-balancer-IP/), I found the load balancer private IP to be the same two addresses.

![Screen Shot 2022-09-15 at 2 59 21 PM](https://user-images.githubusercontent.com/46407464/190517978-2267cd2d-394d-4060-8348-df868523da9a.png)

**Comment by hannes-ucsc** [comment]
This means that the original source IP is lost. Please read 

https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-forwarded-ip-address.html

to see if that helps. You might need to verify in an experiment. Bumped the spike.

**Comment by danielsotirhos** [comment]
Experimented on my private API deployment with a rate-based rule using the `X-Forwarded-For` header, however in the WAF logs it was discovered that the request header did not contain the original source IP, and instead had the private IP of the `azul-gitlab-vpn` ClientVPN Endpoint.

Here are the IPs contained in one such log:
```
httpRequest.clientIp    172.71.3.116    (ALB)
X-Forwarded-For         172.71.3.217    (ClientVPN Endpoint)
X-Forwarded-For         172.71.3.116    (ALB)
```
and another log entry which connected to the 2nd load balancer:
```
httpRequest.clientIp    172.71.1.97     (ALB)
X-Forwarded-For         172.71.3.217    (ClientVPN Endpoint)
X-Forwarded-For         172.71.1.97     (ALB)
```

Crucially, not listed in the log is the IP of my system nor my VPN connection.

Another experiment was performed connecting the WAF to the load balancer instead of the API gateway. Logged requests with this setup only contained the private IP of the ClientVPN endpoint and no `X-Forwarded-For` header.
```
httpRequest.clientIp    172.71.3.217    (ClientVPN Endpoint)
```

Also investigated into if the public IP of the ClientVPN Endpoints could be removed. From https://repost.aws/questions/QUXQ8aH5RQTr-JRSXK2s9N7w/vpn-client-endpoint-interfaces-have-public-ip-how-to-remove :

> You are correct that this public IP is not the one you will use to connect to the Client VPN. Instead, this IP is used as the source IP for traffic coming from Client VPN destined to Internet via IGW as described in https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/scenario-internet.html .

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "I added the WAF to the network diagram in front of the private API gateway. I also included the currently unused public IPs for VPN egress. @danielsotirhos to create follow-up ticket for the fact that the IP of the VPN clients is not logged by WAF, API gateway, or Lambda."

**Comment by hannes-ucsc** [comment]
Follow-on ticket is #4467. WAF is now present in Network Diagram for private APIs.
