### ISSUE TITLE
Create private GitHub repository for tracking security tickets

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4455]

**Comment by melainalegaspi** [comment]
@theathorn to create corresponding Epic.

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul-private

Next assignee to sync labels.

**Comment by achave11** [comment]
Labels have been synced https://github.com/DataBiosphere/azul-private/labels.

**Comment by achave11** [comment]
@hannes-ucsc: "Looks good."
