### ISSUE TITLE
Prepare incident response scenario

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4456]
Run through the scenario before the initial compliance audit.
The scenario will include an attacker role and operator role, and will result in an incident response playbook.

**Comment by melainalegaspi** [comment]
@theathorn to create corresponding Epic

**Comment by hannes-ucsc** [comment]
https://docs.google.com/document/d/1I5u56c4F7qACYl0E9KjQcvBRgHd6_k7JUIOSuIuXsUE/edit?usp=sharing

**Comment by theathorn** [comment]
Reviewed and suggestions made.

**Comment by nolunwa-ucsc** [comment]
this was done and updated in the SSP
