### ISSUE TITLE
Update canned bundles to resemble pilot bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#446]
Replace the canned bundles with ones from one of the the pilot datasets and update the UUID and assertions accordingly.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-298)
┆Project Name: azul
┆Issue Number: AZUL-298

**Comment by theathorn** [comment]
No longer needed.
