### ISSUE TITLE
Add support for treatment protocols

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4465]
Test data is here: https://github.com/HumanCellAtlas/schema-test-data/pull/23

Schema: https://schema.staging.data.humancellatlas.org/type/protocol/biomaterial_collection/1.0.0/treatment_protocol

**Comment by danielsotirhos** [comment]
Not indexing any fields from `treatment_protocol` at this time.
https://humancellatlas.slack.com/archives/C01360XN04S/p1664398056336049

**Comment by hannes-ucsc** [comment]
Other than the new entity type not breaking the indexer (which we would learn about during reindexing) there is nothing to demo here.
