### ISSUE TITLE
GitLab volume fills up with logs and docker cruft

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4466]

**Comment by hannes-ucsc** [comment]
6G for docker images and 2G for logs. The default volume size for the RancherOS AMI was 10G, for the new Amazon Linux AMI it is only 8G. The biggest contributor to the logs in /var/log was the `gitlab` container. On RancherOS those logs went to the `gitlab` volume and were logrotated out, and never caused issues. Now that container's logs go syslog and then /var/log on the root volume. On `prod` log rotation did kick in but didn't delete any files.

I have the feeling we'll have to live with the 6G for Docker. `docker image prune` didn't delete anything. The `gitlab-ce` image is huge, 2.6 G uncompressed.

I think growing the root volume to 16G and more frequent log rotation will fix this. Ultimately, syslogs will be sent to CloudWatch, so local log retention will be less important.

**Comment by theathorn** [comment]
@hannes-ucsc : "I confirmed that increasing the volume size to 20G fixes the issue on prod and dev - closing".
