### ISSUE TITLE
IP of VPN clients not logged by WAF, API Gateway, or Lambda

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4467]
Follow-up to #4448

For requests to GitLab and Azul deployments with private APIs, we need to be able to determine (or deduce by log correlation) the internal and public IP of clients making those requests.

**Comment by hannes-ucsc** [comment]
ALB logs should have that.

**Comment by hannes-ucsc** [comment]
The blocker may solve this. Spike to confirm when blocker lands.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "The blocker didn't solve this issue. Assignee to file ticket with AWS support."

**Comment by hannes-ucsc** [comment]
Issue moved to [DataBiosphere/azul-private #86](https://github.com/DataBiosphere/azul-private/issues/86) via [**Zenhub**](https://www.zenhub.com/)
