### ISSUE TITLE
AnVIL: Index `source_datarepo_row_ids` and include in PFB export

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/azul#4482]
AnVIL TDR snapshots now include a field named `source_datarepo_row_ids`, which was added primarily to support user workspace population with the complete set of study data. This field is included in all rows of AnVIL Findability Subset tables.
It needs to be indexed and passed through to the PFB export.
We don't currently have use cases requiring this information to be displayed in the Browser UI.

The value of this field is of the form:
_source table name_`:`_TDR row id_

For example:  
`ws_subject:40019057-b92e-4423-b890-c2fc78d310c3`

Showing exported data in Terra user workspaces that closely matches (e.g., same shape/structure) was recently identified as important/necessary for the first demo to the AnVIL sponsors. An estimate is requested for when this could be available.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to review.

**Comment by hannes-ucsc** [comment]
I'll be closing #4483 and #4482 as duplicates of #4121 which predates them. The former two tickets provided helpful information for the description of the latter. So thank you for filing them. I'm consolidating two tickets into one because it would take more time to implement them separately than together which is our main criterion for ticket granularity.

**Comment by mbaumann-broad** [comment]
@hannes-ucsc Okay with managing the tickets as you like, as long as the functionality matches the more recent, specific and detailed descriptions of https://github.com/DataBiosphere/azul/issues/4483 and https://github.com/DataBiosphere/azul/issues/4482.

**Comment by hannes-ucsc** [comment]
The specification is a matter of negotiation between all parties. We obviously can't give you a carte blanche to dictate specs on a UCSC product.
