### ISSUE TITLE
Include reference to source snapshot in PFB manifest

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/azul#4483]
To enable populating user workspaces with the full set of selected study data, TDR snapshot information is needed to complement the `source_datarepo_row_ids` field (see #4482).  The required snapshot identifier is not available until after the snapshot is written and cannot be included in the snapshot itself. This information is, however, available at indexing time.

The request is to insert a new field named `source_datarepo_snapshot` in all rows of AnVIL Findability Subset data at the time of indexing and to include it in the PFB export.  We don't currently have use cases requiring this information to be displayed in the Browser UI.

The format of the values is:  
_snapshot_version_`:`_snapshot_name_`:`_snapshot_uuid_

For example:
`v1:ANVIL_CMG_UWASH_DS_BDIS_20220922_202209221415:f5db3b98-a633-4677-b8b2-ca5b629eae7a`

The _snapshot_version_ (`v1`) is currently a constant value, introduced by the TDR team for future proofing. Sushma is going to check if there is currently a TDR API for obtaining this value.

Showing exported data in Terra user workspaces that closely matches (e.g., same shape/structure) was recently identified as important/necessary for the first demo to the AnVIL sponsors. An estimate is requested for when this could be available.

**Comment by hannes-ucsc** [comment]
What's `snapshot_version`? Where would we get it from? Why do we need to send the name of the snapshot when the UUID is sufficient?

**Comment by mbaumann-broad** [comment]
The snapshot_version (v1) is currently a constant value, introduced by the TDR team for future-proofing. Sushma is going to check if there is currently a TDR API for obtaining this value.

**Comment by mbaumann-broad** [comment]
Including a human meaningful name is thought to be useful as provenance information for researchers and easier-to-use diagnostic information for developers. This is especially true for Terra user workspaces containing data from multiple snapshots

**Comment by melainalegaspi** [comment]
@hannes-ucsc to review

**Comment by hannes-ucsc** [comment]
It's always possible to obtain the name of the snapshot given its ID so I don't quite buy the provenance argument. The main purpose of the row reference is to facilitate the population of the workspace using a script running in the workspace. IOW, the main consumer is a program, not a human. It's simpler and sufficient to send just the UUID. That eliminates the need for some proprietary syntax, which makes joining easier.

**Comment by hannes-ucsc** [comment]
I'll be closing #4483 and #4482 as duplicates of #4121 which predates them. The former two tickets provided helpful information for the description of the latter. So thank you for filing them. I'm consolidating two tickets into one because it would take more time to implement them separately than together which is our main criterion for ticket granularity.
