### ISSUE TITLE
Identify Ingest spreadsheets to the Data Browser

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4488]
Enable the Data Browser to discover Ingest spreadsheets and handle them as desired.
For such files the `.file_source` is set to `"DCP/2 Ingest"` and the `.content_description` property is set to `"Database entry metadata"`.

**Comment by theathorn** [comment]
@theathorn to un-park this when example snapshot is available.

**Comment by theathorn** [comment]
The dcp23 snapshots will contain metadata ingest spreadsheets.

**Comment by hannes-ucsc** [comment]
@theathorn asked for example file metadata from EBI. Waiting for response.

**Comment by hannes-ucsc** [comment]
Example not needed anymore. PR was filed

https://github.com/HumanCellAtlas/dcp2/pull/67

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to merge PR.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "This is done."

https://github.com/DataBiosphere/azul/pull/4821#issuecomment-1352387911
