### ISSUE TITLE
Details endpoints use awkward query condition

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#449]
The details endpoint (/repository/$entity_type/$uuid) use a query clause on `contents.$entity_type/document_id`. They should use `entity_id`. One of the invariants guarantees that both fields have the same value but filtering on `entity_id` at the document root is more direct and intuitive. We could also use `_id` as that is also the same value and may be more efficient.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-299)
┆Project Name: azul
┆Issue Number: AZUL-299

**Comment by GPelayo** [comment]
Resolved in PR https://github.com/DataBiosphere/azul/pull/874.
Specifically at this line, https://github.com/DataBiosphere/azul/pull/874/files#diff-01f073890fc4c72bb641f6a570a02db0L43

**Comment by hannes-ucsc** [comment]
Fix confirmed.
