### ISSUE TITLE
Slack notifications are easily missed

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4494]
Consider a way to repeatedly send notifications until they are acknowledged.

**Comment by melainalegaspi** [comment]
Couldn't find a way to repeatedly send notifications, but can instead create a button someone presses to acknowledge the reminder and then send a message to the channel confirming the reminder was seen and that the action is in process. ![Screen Shot 2022-09-30 at 11.40.35 AM.png](https://images.zenhubusercontent.com/5cb8d2ec67d6eb305bc6fd58/ea5c5aea-f7f9-430f-8e7c-6b12ed1cd766)

**Comment by melainalegaspi** [comment]
I'll investigate further on apps that can further add steps to workflows.

**Comment by melainalegaspi** [comment]
still spiking, testing out RosterBird and Task Reminder

**Comment by melainalegaspi** [comment]
I will create task for Hannes (the most frequent reminder) as a test.

**Comment by theathorn** [comment]
@hannes-ucsc :"I successfully participated in the test. @melainalegaspi, do you know if it is possible to post the reminders in a thread rather than directly in the channel?"

**Comment by hannes-ucsc** [comment]
We need to decide what to do with this since assignee has left the team.

**Comment by melainalegaspi** [comment]
Created notifications for daily/weekly reminders (Promotion, OpenSearch updates, Clam AV, Backup GitLab volume, Review PR notifications) View list of all created tasks by entering `@Task Reminder tasks` in #team-boardwalk

**Comment by theathorn** [comment]
@theathorn to review current setup and request changes if needed.

**Comment by theathorn** [comment]
Task reminder's are sent to the #team-boardwalk channel and repeated on the following schedule until acknowledged:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/f67bc428-2b6d-4253-95ad-cbdba9aab134)

**Comment by theathorn** [comment]
Workflows are configured by clicking in Slack on the "UCSC GI" dropdown -> Tools -> Workflow Builder.
Here is the list of current workflows:![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/37c78d4e-71e1-4ea1-b81e-8289902fbd40)
