### ISSUE TITLE
Index four updated CMG snapshots with additional facets

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4495]
Snapshot names (rows 9-12 of [spreadsheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274)):
  - ANVIL_CMG_UWASH_GRU_20220919_202209211317
  - ANVIL_CMG_UWASH_DS_BAV_IRB_PUB_RD_20220921_202209211310
  - ANVIL_CMG_UWASH_DS_EP_20220921_202209211403
  - ANVIL_CMG_UWASH_HMB_IRB_20220921_202209211635

Index / add search facets for:
  - dataset.title
  - dataset.registered_identifier
  - dataset.consent_group
  - dataset.data_use_permission

**Comment by hannes-ucsc** [comment]
For demo, show new/changed facets in `anvildev`.

**Comment by nadove-ucsc** [comment]
New fields are missing from `termFacets`
