### ISSUE TITLE
Implement Handlers for Delete Events on the Indexer

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#45]
As a user I would like to see data removed from the DSS also be removed from our indexers (and therefore, disappear from the portal. 

DOD: We have a way to retrieve a list of ES ids that match the bundle id from the event. Update the documents in ES. Make the logic of retrieving ES IDs as configurable at deploy time.  Unit tests included.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-75)
┆Project Name: azul
┆Issue Number: AZUL-75

**Comment by hannes-ucsc** [comment]
Deletions should not show up in a response or cause exceptions there. See https://github.com/DataBiosphere/azul/issues/170#issuecomment-414748808.
