### ISSUE TITLE
Describe change management and deployment

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4501]

**Comment by theathorn** [comment]
@hannes-ucsc to provide details and then assign to @danielsotirhos.

**Comment by dsotirho-ucsc** [comment]
Document: [Change Management and Deployment](https://docs.google.com/document/d/1pT-3QVY1_NARfIHVLQHFlc3x42QCy92CIJJM1uvuy4U/edit)

**Comment by dsotirho-ucsc** [comment]
@noah-aviel-dove to review first.

**Comment by nadove-ucsc** [comment]
Approved.

**Comment by hannes-ucsc** [comment]
Pretty good document so far, @danielsotirhos & @noah-aviel-dove. I left comments and requested changes.

**Comment by dsotirho-ucsc** [comment]
[Document](https://docs.google.com/document/d/1pT-3QVY1_NARfIHVLQHFlc3x42QCy92CIJJM1uvuy4U/edit) was updated for the requested changes.

**Comment by hannes-ucsc** [comment]
Looks good. Please convert to reStructuredText and file a PR that adds the result to this repository under `docs/compliance/change_management.rst`.
