### ISSUE TITLE
Find out why Snyk isn't used anymore on PRs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4504]

**Comment by hannes-ucsc** [comment]
SNYK is working now, using the synthetic `requirements.all.txt` which contains specific versions of all dependencies, build-time and runtime, direct and transitive. The status check is enabled on PRs and passing:

![Screen Shot 2022-10-11 at 10.31.35 AM.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/8dd00a8c-3891-4053-91c3-17e08ecf7b6c)![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/ff0923ba-0b40-4205-a769-55b0f5825cca)

Screenshots are from https://github.com/DataBiosphere/azul/pull/4562 which updated almost all [direct](https://github.com/DataBiosphere/azul/pull/4562/files#diff-66bb0bc92455abe70f26f42197a234d72e21308eaeb3a5fc17f669dc17707870L2-L26) and [runtime](https://github.com/DataBiosphere/azul/pull/4562/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L1-R37) dependencies.
