### ISSUE TITLE
Configure daily reminder for operators to review dependabot PR notifications

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4505]
@nolunwa to provide expected turnaround times.

**Comment by nolunwa** [comment]
@hannes-ucsc high-risk vulnerabilities mitigated within thirty (30) days from date of discovery; moderate risk vulnerabilities mitigated within ninety (90) days from date of discovery; low risk vulnerabilities mitigated within one hundred and eighty (180) days from date of discovery

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "notification should read : @here operator this is your daily reminder to check for and deal with any open dependabot PRs."

**Comment by hannes-ucsc** [comment]
Ticket closure typically requires review or demo, or at least re-triaging.

**Comment by melainalegaspi** [comment]
I'll fix the @here link in the reminder notification.

**Comment by melainalegaspi** [comment]
Fixed.
