### ISSUE TITLE
Update and review the Incident response plan

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4520]
[UCSC Azul Data Browser Incident Response Plan](https://docs.google.com/document/d/1O38TaVox_A9YNhgar4ZFLkXlGBsGwH8jugb3W4Kam6M).

**Comment by theathorn** [comment]
@nolunwa to update this doc and then re-assign to me for review.

**Comment by nolunwa-ucsc** [comment]
was submitted during the audit
