### ISSUE TITLE
CP-2 CONTINGENCY PLAN

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4524]
[HCA Data Browser Contingency Plan (ISCP](https://docs.google.com/document/d/1LatxhU0h-iKGaKPy9iD0yhTz6gY45Ick)).
[HCA CP:BIA Questions](https://docs.google.com/document/d/1Tb7N-NZqruS0MYpRyBXqW6QXfD77_mY9).

**Comment by theathorn** [comment]
@nolunwa to update these docs and then re-assign to me for review.

**Comment by nolunwa-ucsc** [comment]
Completed and submitted before the audit
