### ISSUE TITLE
Periodically backup GitLab volume

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4525]
Notification on Slack and manual creation of snapshot.

**Comment by melainalegaspi** [comment]
I'll Thursday weekly notification 9 a.m.: "@here this is a reminder to backup GitLab volumes in `dev`, `anvildev` and `prod`."

**Comment by melainalegaspi** [comment]
Created notification and will close once the notification is sent to Slack channel on Thursday.

**Comment by hannes-ucsc** [comment]
We need to decide what to do with this since assignee has left the team.

**Comment by melainalegaspi** [comment]
created slack notification via Task Reminder. View list of all created tasks by entering `@Task Reminder tasks` in #team-boardwalk

**Comment by theathorn** [comment]
@theathorn to review current setup and request changes if needed.

**Comment by theathorn** [comment]
I see task reminders for this sent to Slack channel #team-boardwalk everyday starting at 9:00am and repeated at 12:00pm and 3:00pm unless acknowledged.

**Comment by theathorn** [comment]
Slack workflow configuration:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/7fb678f8-4089-42e4-9809-71f26d498194)
