### ISSUE TITLE
LGTM is going down December 2022 

### ISSUE THREAD

**Issue by melainalegaspi** [DataBiosphere/azul#4529]
> LGTM.com will be shut down in December 2022 — we recommend that you use GitHub code scanning instead. Read more in [our blog post on the GitHub blog](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/).

**Comment by hannes-ucsc** [comment]
We will transition to [GitHub Code Scanning](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository#setting-up-code-scanning-manually)

**Comment by hannes-ucsc** [comment]
For demo, show code scanning results on GitHub.
