### ISSUE TITLE
Include DSS URL in `contents.files`

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#453]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-304)
┆Project Name: azul
┆Issue Number: AZUL-304

**Comment by hannes-ucsc** [comment]
<img width="1156" alt="screen shot 2018-10-24 at 3 44 56 pm" src="https://user-images.githubusercontent.com/5143256/47465940-d4861c00-d7a3-11e8-8f9c-d50390fe9821.png">
