### ISSUE TITLE
SNYK raises false positives in requirements files

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4531]
… due to the limited scope (per file) scan, the comprehensive set of requirements (where other transitive dependencies get pinned) for the project are omitted and potential fixes to transitive (vulnerable) dependencies disregarded.

**Comment by hannes-ucsc** [comment]
For example, 

![image.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/a3e3e942-9d91-4c15-b1d4-4377c63d5e10)

claims that `requirements.dev.txt` uses a vulnerable version of `rsa` and suggests to upgrade to version 4.7 in which that vulnerability is fixed. We are, in fact, using that version and it is pinned in the runtime requirements file

https://github.com/DataBiosphere/azul/blob/79cc35ebed77ab04c083c9188a4fbd1832d4bbfc/requirements.txt#L40

but SNYK doesn't see that pin when analyzing requirements.dev.txt
