### ISSUE TITLE
Identify authoritative CRM (customer responsibility matrix) agreement for GCP

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4551]
For AC-2(12).a.1 defines atypical usage for information system accounts.

**Comment by theathorn** [comment]
Google Cloud Platform: [Shared Responsibility Matrix](https://services.google.com/fh/files/misc/gcp_pci_srm__apr_2019.pdf).

**Comment by theathorn** [comment]
[GCP CRM](https://drive.google.com/drive/folders/1uJOMfyMHRP8UOMkhjgoUSjJkT0zv5HjB).

**Comment by theathorn** [comment]
@nolunwa can we close this ticket now?

**Comment by nolunwa** [comment]
@theathorn Yes please thanks
