### ISSUE TITLE
Field mapping assumes field names are unique

### ISSUE THREAD

**Issue by noah-aviel-dove** [DataBiosphere/azul#4553]
Activities, donors, and libraries all define a field called `date_created` in `azul.plugins.metadata.anvil.Plugin._field_mapping`. When `Plugin._field_mapping` is inverted to yield `Plugin.field_mapping`, these field names are switched from being values to being keys, allowing only one of their definitions to be expressed. The others are lost.

```
>>> plugin.field_mapping['date_created']
('contents', 'libraries', 'date_created')
```

When the `library` entity type was removed as part of PR #4530, it revealed that an erroneous mapping for `date_created` was present for donor entities, despite that field being replaced with `birth_date` in [75803eb9](https://github.com/DataBiosphere/azul/commit/75803eb9802793f9aa9e6719a61c63799b769856). This was not detected because the mapping for libraries was used in place of the missing definition for donors.

This probably also affects fields such as `data_modality` that are defined for multiple entity types.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to devise solution.

**Comment by hannes-ucsc** [comment]
The assumption that field names (and therefore facets) are unique across all inner entities dates back quite a while. I think there's an easy way out: We should switch to using a dotted path notation for the field names in the AnVIL plugin, as in `donors.birth_date`. We should also enforce that the inversion creates no conflicts exist.

We need to coordinate this change with the DB team but I think we can avoid a transitional period where we support both forms and instead just do a hard switch.

**Comment by melainalegaspi** [comment]
@hannes-ucsc :"We should start working on this but it can't be merged before the next internal AnVIL demo on 10/18/2022."

**Comment by hannes-ucsc** [comment]
For demo, show the new field name notation in service requests and responses.

**Comment by theathorn** [comment]
@noah-aviel-dove to hold this warm and re-request review on Tuesday.
