### ISSUE TITLE
Can't install greenlet 1.1.3.post0

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4561]
Currently only reproducible on a PR branch for #4559.

With `greenlet==1.1.3.post0` in `requirements.dev.trans.txt` I get

`make requirements`

```
ERROR: Ignored the following versions that require a different python version: 0.10.6 Requires-Python >=2.7, <3.6; 0.10.7 Requires-Python >=2.7, <3.6
ERROR: Could not find a version that satisfies the requirement greenlet==1.1.3.post0 (from versions: 0.1, 0.2, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 1.0a1, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 2.0.0a1, 2.0.0a2)
ERROR: No matching distribution found for greenlet==1.1.3.post0
make: *** [requirements] Error 1
```

on an M1 MacBook Pro running macOS. That entry in `requirements.dev.trans.txt` was the result of running `make requirements_update` so I guess this does not occur on Linux.

As a workaround, I will pin predecessor version 1.1.3 (without `.post0`) in `requirements.dev.txt`.

Don't really understand the cause. Whatever, the permanent fix is, it should remove the pin again.

**Comment by melainalegaspi** [comment]
@hannes-ucsc to try upgrading again in a few weeks.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
