### ISSUE TITLE
Describe AC-4 Information flow control enforcement

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4571]
[AC-4 control description](https://www.stigviewer.com/controls/800-53/AC-4).
Provide text based description for the data flow diagram.
Related to CA-9 (#4447).

**Comment by hannes-ucsc** [comment]
Offloading some of my Sprint column.

**Comment by dsotirho-ucsc** [comment]
~Document: [Data Browser System Overview (Description)](https://docs.google.com/document/d/1sJ-QP3PQnSAPc0Oau8ZA_Dy2bYa6KzzG81ANSDGd4yc/edit#)~

Superseded: https://github.com/DataBiosphere/azul/issues/4571#issuecomment-1466653365

**Comment by hannes-ucsc** [comment]
The product is not adequate for inclusion in official documentation. I'll have to write it myself. On the bright side, I'm two thirds done and found a few bugs in the diagram itself.

**Comment by hannes-ucsc** [comment]
Final draft is here: https://docs.google.com/document/d/1bjBnBusauDEiRNHOAM7vwGrL-GPlE-YcLQIBrE6SOdI/edit

**Comment by nolunwa-ucsc** [comment]
received and will review, thanks

**Comment by nolunwa-ucsc** [comment]
this has been done and updated on the ssp
