### ISSUE TITLE
Delete ad-hoc CloudWatch dashboards

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4575]
Wait until #4307 was demoed. Then delete any manually created dashboards. I'm aware of `azul-prod` in `prod`, `azul-nadove2` and `azul-nadove3` in `dev`. Check `anvilddev`.

**Comment by danielsotirhos** [comment]
Deleted dashboards

platform-hca-prod:
- azul-prod
- azul-prod-3707-slot-usage-by-query-shape

platform-hca-dev:
- azul-nadove2
- azul-nadove3

platform-hca-anvil
- (none)
