### ISSUE TITLE
Update ClamAV engine version together with GitLab

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4582]
- [x] Add operator manual item to update ClamAV if and when we update GitLab @achave11 
- [x] Modify wording of Slack reminder @melainalegaspi

**Comment by hannes-ucsc** [comment]
For demo, show updated operator manual and Slack notification text.

**Comment by hannes-ucsc** [comment]
We need to decide what to do with this since assignee has left the team.

**Comment by melainalegaspi** [comment]
Created notification via Task Reminder. View list of all created tasks by entering @Task Reminder tasks in #team-boardwalk

**Comment by theathorn** [comment]
@theathorn to review current setup and request changes if needed.

**Comment by theathorn** [comment]
Current reminder text is "This is a reminder for this week's operator to check for GitLab and ClamAV updates.".
Last message was sent on Nov. 10th at 3:00pm and marked as "Done" by @achave11.

**Comment by theathorn** [comment]
Slack workflow configuration:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/e057e4bb-d43d-4bc2-81de-1f0508c4fc51)

**Comment by theathorn** [comment]
Change to monthly reminder.

**Comment by theathorn** [comment]
Changed schedule to "Starts January 3rd at 8:00am and repeats monthly on the first Tuesday".
