### ISSUE TITLE
Index AnVIL schema v3 CMG and GTEX snapshots

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4599]
From this [Slack thread](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1665606666155309):

These are schema version “3”, which is now indicated in the snapshot name by an “ANV3" between the dataset date stamp and the snapshot datetime stamp. The only change is the addition of the used_biosample_id field in the activity table, which should now be populated for the GTEx snapshot to provide linkage from biosamples to activities (and subsequently to files).

@hannes-ucsc :"This includes adding support for indexing the generic `activities` table and using its foreign keys to discover other entities."

**Comment by theathorn** [comment]
@hannes-ucsc :"Going by the book, we would first have to index the remaining 5 CMG snapshots with schema v2 before switching to the schema v3 snapshots, but I don't foresee any issues adding the 5 CMG datasets so we are going to skip that and simply index all 10 snapshots with schema v3 in a single PR. There is 1 important [change](https://github.com/broadinstitute/anvil_tdr_ingest/pull/1/files
) in the v3 schema: the activity entity now has a foreign key to biosample

**Comment by melainalegaspi** [comment]
@hannes-ucsc to include file count match in demo requirements.

**Comment by noah-aviel-dove** [comment]
There is a conflict between the synthetic "activity_type" column that we create from the table name and the actual "activity_type` column that is present in the updated schema. We should rename our synthetic field name to "activity_table" and index the column of the same name verbatim.

**Comment by hannes-ucsc** [comment]
For the internal demo, show that the file count reported by Azul matches the expected number for 1) the GTEX snapshot and 2) either one of the CMG snapshots or all of them if that's easier.

**Comment by noah-aviel-dove** [comment]
@hannes-ucsc: "Can't satisfy demo instruction due to #4654. Revoking demo label."
