### ISSUE TITLE
Rotate operator role again

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4604]
We need some sort of notification procedure to rotate the role between Daniel and Abraham starting Monday 10/24/22.

**Comment by hannes-ucsc** [comment]
We need to decide what to do with this since assignee has left the team.

**Comment by melainalegaspi** [comment]
Created notification in Slack via Rotation App

**Comment by theathorn** [comment]
@theathorn to review current setup and request changes if needed.

**Comment by theathorn** [comment]
The reminder text from Rotation App is "Hey team :wave: It's @Abraham's turn to be team boardwalk operator".
Last reminder was sent on Nov. 8th at 9:35am.

**Comment by theathorn** [comment]
Rotation App is configured in Slack to alternate every 2 weeks between Abraham and Daniel.
From today:
![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/3f9c6e5f-7cab-461b-aa5b-37c50306ebb3)
