### ISSUE TITLE
Unit tests do not cover PFB manifest with AnVIL plugins

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4606]

**Comment by achave11-ucsc** [comment]
Assignee to determine next steps.

**Comment by hannes-ucsc** [comment]
Solve #5046, first, which switches from TinyQuery to BQE and adds basic coverage of AnVIL `fetch_bundle` and `list_bundles`.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "#4943 will add a completely new PFB-based manifest format including tests, so I don't think it makes a lot of sense to cover the code of the legacy PFB-based manifest just as it's being replaced."
