### ISSUE TITLE
Allow-list platform-anvil-prod OAuth clients in Terra prod

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4616]

**Comment by danielsotirhos** [comment]
@theathorn to continue engaging with BI in this matter.

**Comment by theathorn** [comment]
Requires compliance 3PAO report from Fortreum followed by ATO from David Bernick.

**Comment by hannes-ucsc** [comment]
… and will be done to clients in anvilprod, not anvildev. Changing title accordingly.

**Comment by hannes-ucsc** [comment]
Broad reports that this is done: https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1688570596264529?thread_ts=1686684082.808079&cid=C03TPJS54DC

We can't confirm the fix until we remove the workaround, blocked issue #4398. We're going to schedule that now.

**Comment by dsotirho-ucsc** [comment]
#4398 was addressed
