### ISSUE TITLE
Update to AnVIL schema v4

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4617]
https://github.com/broadinstitute/anvil_tdr_ingest/pull/2/files

- [x] Switch the v3 snapshots in the corpus to their updated v4 counterparts
- [x] Absorb renaming of fields
- [x] Absorb renaming of tables
- [ ] Ensure that we index all tables
- [ ] Ensure that we follow all foreign keys in the schema
- [x] Ensure that we index all columns in the schema

I don't think we currently follow the FK `from_biosample.diagnosis_id_to_diagnosis.diagnosis_id` that's being removed in v4. So nothing to do on that front. But see #4618.

Absorbing the renamed tables doesn't affect our internal naming of entity types i.e. `biosample` stays `biosample` even though the table is called `anvil_biosample`.

**Comment by melainalegaspi** [comment]
@noah-aviel-dove received review request, waiting for review to complete before triaging.

**Comment by melainalegaspi** [comment]
@theathorn to monitor spreadsheet for updated snapshots.

**Comment by hannes-ucsc** [comment]
Current v4 snapshots will be retracted and replacements with more file connections will be released.

https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1667564548110159

**Comment by theathorn** [comment]
[Slack thread](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1667932321086009) re. updated snapshots.

**Comment by theathorn** [comment]
[Rows 29-38](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274) contain the 10 updated snapshots.

**Comment by hannes-ucsc** [comment]
For demo, show that each snapshot is represented on the `/index/files` endpoint. Name the tables and foreign keys that are not indexed/followed and discuss if we need additional tickets for them.

**Comment by nadove-ucsc** [comment]
Follow-ups from demo: 
https://github.com/DataBiosphere/azul/issues/4827
https://github.com/DataBiosphere/azul/issues/4828
