### ISSUE TITLE
Index AnVIL `diagnoses` entity

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4618]

**Comment by melainalegaspi** [comment]
@noah-aviel-dove received review request, waiting for review to complete before triaging.

**Comment by melainalegaspi** [comment]
@theathorn to monitor spreadsheet for updated snapshots.

**Comment by theathorn** [comment]
Not strictly required for stakeholder demo but would be NTH.

**Comment by nadove-ucsc** [comment]
@hannes-ucsc: "For now, index as inner entity only. And index all non-ID columns as fields and facets. Add disease, phenotype, and phenopacket to summary."

**Comment by nadove-ucsc** [comment]
For summary:
 - donorDiagnosisDiseases
 - donorDiagnosisPhenotypes
 - no top-level counts

**Comment by hannes-ucsc** [comment]
~For demo, show the effects of this change on hits, facets, sorting, filtering, summary and manifests.~

To be demo-ed as part of #4922.
