### ISSUE TITLE
Run Prowler security scanning tool for AWS

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4622]
From [this Slack thread](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1666278905545459) - Bernick: ask them to run "[prowler](https://prowler.pro/)" and give me the results. That'll tell me if they're clean. https://github.com/prowler-cloud/prowler with cislevel1 setting.

**Comment by theathorn** [comment]
Spike to try it out locally.

**Comment by hannes-ucsc** [comment]
https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1667451422652499?thread_ts=1667391423.927699&cid=C03TPJS54DC

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Need to find out from David Bernick if we need to do this on a continuous basis."

**Comment by theathorn** [comment]
@nolunwa : "All scanning tools should be run monthly just like Invicti. David Bernick is not particular if the scan is run via AWS Security Hub or Prowler, he just wants the Data Browser system cloud infrastructure scanned regularly against the CIS Level 1."

**Comment by theathorn** [comment]
Re-run Prowler with cislevel1.
Correlate Prowler findings with SecurityHub findings with the goal of determining which SecurityHub findings after cislevel1 and which are cislevel2.
Since Dave Bernick's requirement is only to address cislevel1 findings, this could result in a lower number of medium findings that we need to address within 90 days.

**Comment by theathorn** [comment]
@hannes-ucsc to post exact command line for Prowler.

**Comment by hannes-ucsc** [comment]
I ran it with `cislevel2` but for the purpose stated by Trevor above, the `cislevel1` group might be better suited.


`mkdir -p prowler && docker run -ti --rm -v $PWD/prowler:/prowler/output --name prowler --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN toniblyx/prowler:latest -g cislevel2 -M csv,json,html`

**Comment by dsotirho-ucsc** [comment]
Prowler findings: https://docs.google.com/spreadsheets/d/1rmPOmPfiNRYiproD61glGw0R1D3HMmDcvHGmy1r2swk/edit?usp=sharing

Using the results of the Prowler scan I've categorized the issues created from DataBiosphere/azul#4666 and added the `severity:cis1` or `severity:cis2` label to the appropriate issues.

CIS LEVEL 1
-----------
- https://github.com/DataBiosphere/azul/issues/4692

CIS LEVEL 2
-----------
- https://github.com/DataBiosphere/azul/issues/4686
- https://github.com/DataBiosphere/azul/issues/4689
- https://github.com/DataBiosphere/azul/issues/4693
- https://github.com/DataBiosphere/azul/issues/4694

AWS Foundational Security Best Practices
----------------------------------------
- https://github.com/DataBiosphere/azul/issues/4687
- https://github.com/DataBiosphere/azul/issues/4688
- https://github.com/DataBiosphere/azul/issues/4690
- https://github.com/DataBiosphere/azul/issues/4691
- https://github.com/DataBiosphere/azul/issues/4695
- https://github.com/DataBiosphere/data-browser/issues/3140
- https://github.com/DataBiosphere/data-browser/issues/3141
- https://github.com/DataBiosphere/azul/issues/4698
- https://github.com/DataBiosphere/azul/issues/4699
- https://github.com/DataBiosphere/azul/issues/4700
- https://github.com/DataBiosphere/azul/issues/4701
- https://github.com/DataBiosphere/azul/issues/4702
- https://github.com/DataBiosphere/azul/issues/4703
- https://github.com/DataBiosphere/azul/issues/4704
- https://github.com/DataBiosphere/azul/issues/4705
- https://github.com/DataBiosphere/azul/issues/4706
- https://github.com/DataBiosphere/azul/issues/4707
- https://github.com/DataBiosphere/azul/issues/4708
- https://github.com/DataBiosphere/azul/issues/4709
- https://github.com/DataBiosphere/azul/issues/4710
- https://github.com/DataBiosphere/azul/issues/4711
- https://github.com/DataBiosphere/azul/issues/4712
- https://github.com/DataBiosphere/azul/issues/4713
- https://github.com/DataBiosphere/azul/issues/4714
- https://github.com/DataBiosphere/azul/issues/4715
- https://github.com/DataBiosphere/azul/issues/4716
- https://github.com/DataBiosphere/azul/issues/4717
- https://github.com/DataBiosphere/azul/issues/4718
- https://github.com/DataBiosphere/azul/issues/4719
- https://github.com/DataBiosphere/azul/issues/4720
- https://github.com/DataBiosphere/azul/issues/4721
- https://github.com/DataBiosphere/azul/issues/4722

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "This is done."
