### ISSUE TITLE
Rename Azul storage buckets

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4646]
Current storage bucket names are wildly inconsistent:

- `edu-ucsc-gi-singlecell-azul-storage-dev`
- `edu-ucsc-gi-singlecell-azul-storage-sandbox`
- `edu-ucsc-gi-azul-dcp2-prod-storage-prod`
- `edu-ucsc-gi-platform-anvil-dev-anvilbox`
- `edu-ucsc-gi-platform-anvil-dev-anvildev`
- `edu-ucsc-gi-platform-anvil-prod-anvilprod`

We want them to be consistent so that we can switch to using the `qualified_bucket_name()` config method to generated them, in #4655. 

Change the values of the AZUL_S3_BUCKET variable for all deployments so that it match the template `edu-ucsc-gi-{aws.accountname}-storage-{deployment_stage}.{aws.region}`. The storage buckets contain cached manifests, lambda layers and cached health statuses. None of that information must be retained and is recreated automatically when needed, albeit at a slight performance cost. 

During deployment, a new bucket should be created under the new name. The old bucket should be left in place by Terraform and deleted later as a manual upgrade step. By removing the bucket resource from Terraform state, Terraform can be tricked into believing that the bucket does not exist, so that it creates a new one, using the new name. Resources can be removed from TF state with `rename_resources.py`.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to provide description.

**Comment by hannes-ucsc** [comment]
For demo, after this lands in `prod`, show absence of any old storage buckets in any of our three AWS accounts.
