### ISSUE TITLE
All bucket names should default to `qualified_bucket_name()`

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4655]
Add the ability to pass a deployment name to the `qualified_bucket_name` method. Assuming that all invocations proved the deployment, the argument should be mandatory.

The template for bucket names is `edu-ucsc-gi-{aws.accountname}-{name}-{deployment_stage}.{aws.region}` or `edu-ucsc-gi-{aws.accountname}-{name}.{aws.region}` if no deployment was passed.

Use that method wherever a bucket name is specified in TF configuration, environment configuration or code. Delete the `AZUL_VERSIONED_BUCKET` and `AZUL_S3_BUCKET` variables. This change should result in an empty TF plan at deployment time because the blocking tickets already took care of changing the existing bucket names to match the return value of the method.

**Comment by hannes-ucsc** [comment]
Despite being debt, it's important that this gets done ASAP to prevent future deviations, incurring even more debt.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by dsotirho-ucsc** [comment]
Assignee to resolve issue.
