### ISSUE TITLE
Some route53 hosted zones might be unused

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#4662]
… such as `url.singlecell.gi.ucsc.edu` and `dev.azul.data.humancellatlas.org` but confirmation that they can safely be deleted is required.

I was unable to find which deployment or when `url.singlecell.gi.ucsc.edu` hosted zone was created. The one reference to that string I found was it's removal in https://github.com/DataBiosphere/azul/commit/c5cb4f484c1ed126eac6553784aab622652673af. And as per my understanding, it's been some time since we've stop using the `*humancellatlas.org` domain in `dev`.

**Comment by theathorn** [comment]
@achave11 and @hannes-ucsc to work through this in PL on Monday.

**Comment by hannes-ucsc** [comment]
As discussed in PL, this can and should be solved as part of #4625.
