### ISSUE TITLE
Consolidate SecurityHub/GuardDuty findings into individual tickets

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4666]

**Comment by danielsotirhos** [comment]
@hannes-ucsc: "Explore the possibility of tagging findings with the corresponding issue in GitHub."

**Comment by dsotirho-ucsc** [comment]
Created tickets for all findings on the [Anvildev SecurityHub Findings](https://docs.google.com/spreadsheets/d/1Z1lCbYnl1T4n-SjVFINzwj_NCKEtH8xWHgKY0JWDAAE/edit#gid=1573959227) Nov 2 sheet except the two `AWS Health - AWS_EVENTS_OPERATIONAL_ISSUE` findings (these only apply to AWS customers that have configured rules with CloudWatch Log targets).

Tickets:
- https://github.com/DataBiosphere/azul/issues/4686
- https://github.com/DataBiosphere/azul/issues/4687
- https://github.com/DataBiosphere/azul/issues/4688
- https://github.com/DataBiosphere/azul/issues/4689
- https://github.com/DataBiosphere/azul/issues/4690
- https://github.com/DataBiosphere/azul/issues/4691
- https://github.com/DataBiosphere/azul/issues/4692
- https://github.com/DataBiosphere/azul/issues/4693
- https://github.com/DataBiosphere/azul/issues/4694
- https://github.com/DataBiosphere/azul/issues/4695
- https://github.com/DataBiosphere/data-browser/issues/3140
- https://github.com/DataBiosphere/data-browser/issues/3141
- https://github.com/DataBiosphere/azul/issues/4698
- https://github.com/DataBiosphere/azul/issues/4699
- https://github.com/DataBiosphere/azul/issues/4700
- https://github.com/DataBiosphere/azul/issues/4701
- https://github.com/DataBiosphere/azul/issues/4702
- https://github.com/DataBiosphere/azul/issues/4703
- https://github.com/DataBiosphere/azul/issues/4704
- https://github.com/DataBiosphere/azul/issues/4705
- https://github.com/DataBiosphere/azul/issues/4706
- https://github.com/DataBiosphere/azul/issues/4707
- https://github.com/DataBiosphere/azul/issues/4708
- https://github.com/DataBiosphere/azul/issues/4709
- https://github.com/DataBiosphere/azul/issues/4710
- https://github.com/DataBiosphere/azul/issues/4711
- https://github.com/DataBiosphere/azul/issues/4712
- https://github.com/DataBiosphere/azul/issues/4713
- https://github.com/DataBiosphere/azul/issues/4714
- https://github.com/DataBiosphere/azul/issues/4715
- https://github.com/DataBiosphere/azul/issues/4716
- https://github.com/DataBiosphere/azul/issues/4717
- https://github.com/DataBiosphere/azul/issues/4718
- https://github.com/DataBiosphere/azul/issues/4719
- https://github.com/DataBiosphere/azul/issues/4720
- https://github.com/DataBiosphere/azul/issues/4721
- https://github.com/DataBiosphere/azul/issues/4722

**Comment by hannes-ucsc** [comment]
Would be really helpful to have a link to the finding below the JSON, above the security checklist.

Example link

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-2

**Comment by hannes-ucsc** [comment]
I'll put the medium tickets in the Parked column for now to avoid filling up the Triage column.

**Comment by hannes-ucsc** [comment]
Please put those medium tickets back into Triage when done.

**Comment by hannes-ucsc** [comment]
Links should point at the top entry, not the remediation:

![Screen Shot 2022-11-14 at 12.54.54 PM.png](https://images.zenhubusercontent.com/5a5fdc8c4b5806bc2bc32e01/6b682676-8899-4729-8a2a-e39aa57b069c)

**Comment by hannes-ucsc** [comment]
Looks good. Thank you.
