### ISSUE TITLE
Bugs in off-boarding template

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4669]
> Removed the offboarded employee/contractor's GitHub account from the Azul Developers team in the DataBiosphere organization on GitHub

is duplicated.

The `-viewer` groups are missing in the section where system admin removes person from groups in gi-gateway account.

Same section is missing entry for AnVIL prod.

**Comment by theathorn** [comment]
Address in PR for #4206.

**Comment by danielsotirhos** [comment]
PR https://github.com/DataBiosphere/azul/pull/4742 for this issue is attached to the original issue #4206

**Comment by theathorn** [comment]
For demo, attempt to reproduce.
