### ISSUE TITLE
Eliminate burner accounts

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4673]
Remove mentions of burner accounts from the documentation. Ensure any burner accounts are removed from all Google Cloud projects used by the system, and are replaced with the corresponding UCSC or Google Workspace account for the owner of the burner account. Ensure that burner accounts are removed from any Terra groups used by the system, and are replaced with the corresponding UCSC or Google Workspace account for the owner of the burner account.. Ensure that internal users owning burner accounts close those accounts.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by danielsotirhos** [comment]
@hannes-ucsc to add description.

**Comment by hannes-ucsc** [comment]
Security review: This change increases the overall security of the system by reducing the number of Google accounts involved. It consolidates the permissions of internal users to just one type of Google user account. When any internal user previously used a burner and their main UCSC account (Google Workspace account for Clever Canary), the main account will be used consistently in all places. The Broad Institute discouraged the use of main accounts for their development instances of Terra services but it was never made clear as to why. We found out by accident that main accounts are perfectly fine. 

Burner accounts are regular gmail accounts that are not subject to any organizational oversight. Eliminating them is a requirement for compliance.

**Comment by hannes-ucsc** [comment]
It is likely that the lead will have to perform the account replacement in Terra groups and GCP projects. So no demo needed.
