### ISSUE TITLE
Ensure hardware MFA is enabled for the root user

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4686]
```
{
    "GeneratorIds": [
        "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0/rule/1.14",
        "aws-foundational-security-best-practices/v/1.0.0/IAM.6"
    ]
}
```

For compliance, we need to enable hardware MFA for the root user on `platform-{hca,anvil}-{dev,prod}`. This must be addressed by 11/18/2022.

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-1.14
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#iam-6-remediation

---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11** [comment]
@hannes-ucsc to provide solution and additional labels.

**Comment by hannes-ucsc** [comment]
Done. Email sent to Erich.

**Comment by hannes-ucsc** [comment]
Security review: this does modify the authentication protocol used for the root user of every AWS account used by the system. It increases security by following [best practices recommended by AWS](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-iam-6) to enable a hardware multi-factor authentication device. It does not modify anyone's permissions. It can only be performed by an organization administrator because only they have the permissions to modify the authentication settings for root users in AWS accounts used by the system.

**Comment by hannes-ucsc** [comment]
Erich reports this is done. We'll have to wait 24 hours to see if the finding shows as fixed.
