### ISSUE TITLE
CloudFront distributions should have a default root object configured

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4687]
```
{
    "GeneratorIds": [
        "aws-foundational-security-best-practices/v/1.0.0/CloudFront.1"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-cloudfront-1

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11** [comment]
@hannes-ucsc to provide solution and additional labels.

**Comment by hannes-ucsc** [comment]
Existing description suffices. @theathorn to coordinate with Clever Canary. This needs to be done by 11/18/2022.

**Comment by NoopDog** [comment]
Hi @danielsotirhos, can you tell me which CloudFront distribution this was run against and needs to be updated? I know we need to update all, but I want to be sure we get the one that is being tested updated and verified first. Cheers, D

**Comment by NoopDog** [comment]
Hi @danielsotirhos, I added an "index.html" default root object to this distribution here:

https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-east-1#/distributions/E2DEJ1QLYBYKJ4

I also deployed the anvil site to the default origin bucket. 
https://anvil.gi.ucsc.edu/

Let me know if this fixes the security issue.

Cheers,
D
CC @theathorn

**Comment by hannes-ucsc** [comment]
> I added an "index.html" default root object to this distribution here

That resolved the finding in the platform-anvil-dev account.

However, this must be done for every CF distribution in every account Clever Canary was given access to. If Clever Canary programmatically creates CF distributions, the corresponding code needs to be updated to configure a default root object for every CF distribution created in the future.

**Comment by NoopDog** [comment]
Thanks, will verify we did them all. The setup is not currently automated.

**Comment by theathorn** [comment]
Confirmed with @NoopDog that all CF distributions have been manually configured to have a default root object.
Follow on ticket DataBiosphere/data-browser#3006 is for automation of this process.

**Comment by hannes-ucsc** [comment]
This must be demoed. For demo, show that finding is fixed in `platform-anvil-dev`.

**Comment by achave11-ucsc** [comment]
@achave11 to verify that finding is fixed with screen shot in `anvildev`.

**Comment by achave11-ucsc** [comment]
Finding is resolved in `anvildev`:

<img width="1712" alt="Screen Shot 2022-12-14 at 4 51 13 PM" src="https://user-images.githubusercontent.com/19215510/207746816-0d5279df-6724-4c20-b97e-b6095332c4f8.png">
