### ISSUE TITLE
Ensure the default security group of every VPC restricts all traffic

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4689]
```
{
    "GeneratorIds": [
        "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0/rule/4.3",
        "aws-foundational-security-best-practices/v/1.0.0/EC2.2"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-4.3
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-2

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11** [comment]
@hannes-ucsc to provide solution and additional labels.

**Comment by hannes-ucsc** [comment]
I updated my comment accordingly.

**Comment by achave11** [comment]
Removed inbound and outbound rules from default SGs on every VPC in `anvildev`.

**Comment by hannes-ucsc** [comment]
Confirmed that both findings are fixed in `anvildev`.

**Comment by hannes-ucsc** [comment]
Assignee to file PR for the code changes. PR checklist should include items for remaining manual actions so that they are executed in deployment when the PR lands in that deployment.

**Comment by achave11-ucsc** [comment]
Assigning this issue to Operator @danielsotirhos. A branch with some changes towards solving this issue is available at https://github.com/DataBiosphere/azul/compare/issues/achave11/4689-inhibit-default-sg.
