### ISSUE TITLE
EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4690]
```
{
    "GeneratorIds": [
        "aws-foundational-security-best-practices/v/1.0.0/EC2.8"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-8

---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11** [comment]
@hannes-ucsc to provide solution and additional labels.

**Comment by hannes-ucsc** [comment]
This should do it: 

```diff
Index: terraform/gitlab/gitlab.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/gitlab/gitlab.tf.json.template.py b/terraform/gitlab/gitlab.tf.json.template.py
--- a/terraform/gitlab/gitlab.tf.json.template.py	(revision 5c968d728eca610296eb6ff0098f425c7f8ebd68)
+++ b/terraform/gitlab/gitlab.tf.json.template.py	(date 1667862885099)
@@ -1201,6 +1201,9 @@
                 'iam_instance_profile': '${aws_iam_instance_profile.gitlab.name}',
                 'ami': ami_id[config.region],
                 'instance_type': 't3a.xlarge',
+                'metadata_options': {
+                    'http_tokens': 'required'
+                },
                 'root_block_device': {
                     'volume_size': 20
                 },
```

Apply this patch, deploy to `dev.gitlab` and wait for the next full complete build to succeed on that GitLab instance. If it fails, revert and put ticket back to Triage. Otherwise, file PR.

**Comment by hannes-ucsc** [comment]
Security review: This does increase the security of the exchange between code running on the instance and the instance metadata service exposed on the instance. We are following the [recommend best practices](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-8) here.

**Comment by hannes-ucsc** [comment]
For demo, show that the `MetadataNoToken` CW metric is continually zero since this landed in `anvildev`. Show that 

https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/aws-foundational-security-best-practices-1.0.0/EC2.8

is fixed.

**Comment by achave11** [comment]
Note on https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html:
> * For IMDSv2, you must use /latest/api/token when retrieving the token.

Changes caused failures during `deploy` step while running in GitLab. Additionally, while the changes were active the security finding showed a `Record State: Archived` for EC2.8 finding for the GitLab instance. After reverting the change, a new finding with `Record State: Active` for the same instance and finding was available.

**Comment by hannes-ucsc** [comment]
Please try again with 

```diff
Index: terraform/gitlab/gitlab.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/gitlab/gitlab.tf.json.template.py b/terraform/gitlab/gitlab.tf.json.template.py
--- a/terraform/gitlab/gitlab.tf.json.template.py	(revision ab9c226c5b1d4b718696db2c5bbc30816fe8b2cf)
+++ b/terraform/gitlab/gitlab.tf.json.template.py	(date 1668035616234)
@@ -1201,6 +1201,10 @@
                 'iam_instance_profile': '${aws_iam_instance_profile.gitlab.name}',
                 'ami': ami_id[config.region],
                 'instance_type': 't3a.xlarge',
+                'metadata_options': {
+                    'http_tokens': 'required',
+                    'http_put_response_hop_limit': 10
+                },
                 'root_block_device': {
                     'volume_size': 20
                 },
```

If that works, find the minimum value for `http_put_response_hop_limit` that works.
