### ISSUE TITLE
S3 Block Public Access setting should be enabled at the bucket-level

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#4691]
```
{
    "GeneratorIds": [
        "aws-foundational-security-best-practices/v/1.0.0/S3.8"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-8

---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11** [comment]
@hannes-ucsc to provide solution and additional labels.

**Comment by hannes-ucsc** [comment]
Add this: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block

**Comment by hannes-ucsc** [comment]
For demo, show that the https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/aws-foundational-security-best-practices-1.0.0/S3.8 finding in `anvildev` is fixed.

**Comment by hannes-ucsc** [comment]
Security review: This follows best practices recommended by AWS to completely disable even the possibility to have publicly accessible object in any bucket in the system.

**Comment by achave11** [comment]
No buckets outstanding in the `.gitlab` components.

**Comment by hannes-ucsc** [comment]
For demo, show that findings are resolved in `platform-anvil-dev`.

**Comment by hannes-ucsc** [comment]
There are two instances of this finding that relate to buckets managed by Clever Canary. I tried to fix them by manually blocking all public access but had to revert that since it broke the Data Browser. Now, buckets backing CloudFront distros don't need to be public:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

so there is more work for Clever Canary. They need to implement the configuration described in the CF developer guide linked to above and then enabale the "block all public access" setting on these buckets.

**Comment by hannes-ucsc** [comment]
Can't demo this until blocker DataBiosphere/data-browser#2964 is addressed. @theathorn to watch that issue.

**Comment by theathorn** [comment]
Per the blocker, "this should be done in anvildev".
