### ISSUE TITLE
Web service API to support per-organ cell counts on Home Page

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#47]
Portal Home page provides hover-over cell counts for each type of organ represented:

Blood
Bone Marrow
Brain
Esophagus
Heart
Immune
Kidney
Liver
Pancreas
Spleen

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-56)
┆Project Name: azul
┆Issue Number: AZUL-56
┆Epic: Data Portal Home Page integration with Browser

**Comment by kozbo** [comment]
We will need another ticket for regularly updating the data on the main page, perhaps hourly.
