### ISSUE TITLE
Elasticsearch domains should encrypt data at-rest and when sent between nodes

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4708]
```
{
    "GeneratorIds": [
        "aws-foundational-security-best-practices/v/1.0.0/ES.1",
        "aws-foundational-security-best-practices/v/1.0.0/ES.3"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/es-controls.html#es-1
https://docs.aws.amazon.com/securityhub/latest/userguide/es-controls.html#es-3

---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … [affect](https://github.com/DataBiosphere/azul/issues/4708#issuecomment-1515726838) the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Not super-easy since we would need to manage keys in KMS and encrypt TF state at rest.

**Comment by hannes-ucsc** [comment]
For demo, show that finding is fixed in all accounts.

**Comment by hannes-ucsc** [comment]
This change improves our security posture by enabling encryption at rest on a resource that currently not encrypted at rest. It uses AWS-managed keys so no secrets need to be managed, either.
