### ISSUE TITLE
S3 bucket server access logging should be enabled

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4717]
```
{
    "GeneratorIds": [
        "aws-foundational-security-best-practices/v/1.0.0/S3.9"
    ]
}
```

Buckets:
- edu-ucsc-gi-platform-anvil-dev-cloudtrail
- anvil.explorer.gi.ucsc.edu
- edu-ucsc-gi-platform-anvil-dev-awsconfig.us-east-1
- anvil.gi.ucsc.edu
- edu-ucsc-gi-platform-anvil-dev.us-east-1
- edu-ucsc-gi-platform-anvil-dev-logs.us-east-1

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-9

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
This should be fixed. Assignee to check finding again in all accounts and list any buckets here for which that finding has not been addressed yet.

**Comment by dsotirho-ucsc** [comment]
## `platform-hca-dev` 14 buckets without logging
- cc-dev.explore.singlecell.gi.ucsc.edu
- cc-dev.singlecell.gi.ucsc.edu
- data-browser.dev.lungmap.net
- dev.archive-preview.singlecell.gi.ucsc.edu
- dev.explore.lungmap.net
- dev.explore.singlecell.gi.ucsc.edu
- dev.singlecell.gi.ucsc.edu
- edu-ucsc-gi-orange-backup-dev
- edu-ucsc-gi-platform-hca-dev-awsconfig.us-east-1
- edu-ucsc-gi-platform-hca-dev-cloudtrail
- edu-ucsc-gi-platform-hca-dev-logs.us-east-1
- edu-ucsc-gi-singlecell-azul-config-dev.us-east-1
- ux-dev.explore.singlecell.gi.ucsc.edu
- ux-dev.singlecell.gi.ucsc.edu

<details>
<summary>Terminal Log</summary>

```
(.venv) daniel@Crispin ~/repo/azul2 $ _select
lrwxr-xr-x  1 daniel  staff  3 Feb 17 15:34 .active -> dev
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ aws s3api list-buckets | jq '.Buckets[].Name' | xargs -I % sh -c 'echo %; aws s3api get-bucket-logging --bucket %'
cc-dev.explore.singlecell.gi.ucsc.edu
cc-dev.singlecell.gi.ucsc.edu
data-browser.dev.lungmap.net
dev.archive-preview.singlecell.gi.ucsc.edu
dev.explore.lungmap.net
dev.explore.singlecell.gi.ucsc.edu
dev.singlecell.gi.ucsc.edu
edu-ucsc-gi-orange-backup-dev
edu-ucsc-gi-platform-hca-dev-awsconfig.us-east-1
edu-ucsc-gi-platform-hca-dev-cloudtrail
edu-ucsc-gi-platform-hca-dev-logs.us-east-1
edu-ucsc-gi-platform-hca-dev-storage-abrahamsc.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/abrahamsc/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-daniel.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/daniel/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-daniel2.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/daniel2/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-dev.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/dev/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-hannes.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/hannes/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-nadove.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/nadove/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-nadove2.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/nadove2/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-nadove3.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/nadove3/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/sandbox/storage/"
    }
}
edu-ucsc-gi-platform-hca-dev-trail.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/dev/cloudtrail/"
    }
}
edu-ucsc-gi-singlecell-azul-config-dev.us-east-1
ux-dev.explore.singlecell.gi.ucsc.edu
ux-dev.singlecell.gi.ucsc.edu
(.venv) daniel@Crispin ~/repo/azul2 $
```
</details>

**Comment by dsotirho-ucsc** [comment]
## `platform-anvil-dev` 6 buckets without logging
- anvil.explorer.gi.ucsc.edu
- anvil.gi.ucsc.edu
- edu-ucsc-gi-platform-anvil-dev-awsconfig.us-east-1
- edu-ucsc-gi-platform-anvil-dev-cloudtrail
- edu-ucsc-gi-platform-anvil-dev-logs.us-east-1
- edu-ucsc-gi-platform-anvil-dev.us-east-1

<details>
<summary>Terminal Log</summary>

```
(.venv) daniel@Crispin ~/repo/azul2 $ _select
lrwxr-xr-x  1 daniel  staff  8 Feb 17 16:05 .active -> anvildev
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ aws s3api list-buckets | jq '.Buckets[].Name' | xargs -I % sh -c 'echo %; aws s3api get-bucket-logging --bucket %'
anvil.explorer.gi.ucsc.edu
anvil.gi.ucsc.edu
edu-ucsc-gi-platform-anvil-dev-awsconfig.us-east-1
edu-ucsc-gi-platform-anvil-dev-cloudtrail
edu-ucsc-gi-platform-anvil-dev-logs.us-east-1
edu-ucsc-gi-platform-anvil-dev-storage-anvilbox.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-anvil-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/anvilbox/storage/"
    }
}
edu-ucsc-gi-platform-anvil-dev-storage-anvildev.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-anvil-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/anvildev/storage/"
    }
}
edu-ucsc-gi-platform-anvil-dev-storage-nadove4.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-anvil-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/nadove4/storage/"
    }
}
edu-ucsc-gi-platform-anvil-dev-storage-nadove5.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-anvil-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/nadove5/storage/"
    }
}
edu-ucsc-gi-platform-anvil-dev-trail.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-anvil-dev-logs.us-east-1",
        "TargetPrefix": "s3/access/anvildev/cloudtrail/"
    }
}
edu-ucsc-gi-platform-anvil-dev.us-east-1
(.venv) daniel@Crispin ~/repo/azul2 $
```

</details>

**Comment by dsotirho-ucsc** [comment]
## `platform-hca-prod` 9 buckets without logging
- archive-preview.humancellatlas.org
- data-browser.explore.lungmap.net
- data-browser.lungmap.net
- edu-ucsc-gi-azul-dcp2-prod-config.us-east-1
- edu-ucsc-gi-platform-hca-prod-awsconfig.us-east-1
- edu-ucsc-gi-platform-hca-prod-cloudtrail
- edu-ucsc-gi-platform-hca-prod-logs.us-east-1
- org-humancellatlas-data-browser-dcp2-prod
- org-humancellatlas-data-portal-dcp2-prod

<details>
<summary>Terminal log</summary>

```
(.venv) daniel@Crispin ~/repo/azul2 $ _select
lrwxr-xr-x  1 daniel  staff  4 Feb 17 16:09 .active -> prod
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ aws s3api list-buckets | jq '.Buckets[].Name' | xargs -I % sh -c 'echo %; aws s3api get-bucket-logging --bucket %'
archive-preview.humancellatlas.org
data-browser.explore.lungmap.net
data-browser.lungmap.net
edu-ucsc-gi-azul-dcp2-prod-config.us-east-1
edu-ucsc-gi-platform-hca-prod-awsconfig.us-east-1
edu-ucsc-gi-platform-hca-prod-cloudtrail
edu-ucsc-gi-platform-hca-prod-logs.us-east-1
edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-prod-logs.us-east-1",
        "TargetPrefix": "s3/access/prod/storage/"
    }
}
edu-ucsc-gi-platform-hca-prod-trail.us-east-1
{
    "LoggingEnabled": {
        "TargetBucket": "edu-ucsc-gi-platform-hca-prod-logs.us-east-1",
        "TargetPrefix": "s3/access/prod/cloudtrail/"
    }
}
org-humancellatlas-data-browser-dcp2-prod
org-humancellatlas-data-portal-dcp2-prod
(.venv) daniel@Crispin ~/repo/azul2 $
```

</details>

**Comment by hannes-ucsc** [comment]
This is a bit verbose. Could you please consolidate this into a single post with all three deployments? Ideally, it would be a table with three columns: account name, bucket name, and purpose. You can leave the third column blank for now.

**Comment by dsotirho-ucsc** [comment]
| Account            | Bucket                                             | Purpose | Next steps |
|--------------------|----------------------------------------------------|---------|------------|
| platform-hca-dev   | cc-dev.explore.singlecell.gi.ucsc.edu              | DB, E25SUK9P6E5T4Q | Enable (#5005) |
|                    | cc-dev.singlecell.gi.ucsc.edu                      | DB, E25SUK9P6E5T4Q | Enable (#5005) |
|                    | data-browser.dev.lungmap.net                       | DB, E21CJFOUWO9Q7X | Enable (#5005) |
|                    | dev.explore.lungmap.net                            | DB, E21CJFOUWO9Q7X | Enable (#5005) |
|                    | dev.archive-preview.singlecell.gi.ucsc.edu         | DB, E3562WJBOLN8W8 | Enable (#5005) |
|                    | dev.explore.singlecell.gi.ucsc.edu                 | DB, E3562WJBOLN8W8 | Enable (#5005) |
|                    | dev.singlecell.gi.ucsc.edu                         | DB, E3562WJBOLN8W8 | Enable (#5005) |
|                    | ux-dev.explore.singlecell.gi.ucsc.edu              | DB, E3FFK49Z7TQ60R | Enable (#5005) |
|                    | ux-dev.singlecell.gi.ucsc.edu                      | DB, E3FFK49Z7TQ60R | Enable (#5005) |
|                    | ~edu-ucsc-gi-orange-backup-dev~                    | ~old backup~ | ~Delete~ |
|                    | edu-ucsc-gi-platform-hca-dev-awsconfig.us-east-1   | AWS Config bucket | Enable (#5004) |
|                    | edu-ucsc-gi-platform-hca-dev-cloudtrail            | Old CloudTrail bucket | Delete (#4885) |
|                    | edu-ucsc-gi-platform-hca-dev-logs.us-east-1        | Contains S3 access logs. AWS recommends not to Enable access logs on buckets containg access logs. | None |
|                    | edu-ucsc-gi-singlecell-azul-config-dev.us-east-1   | Shared config bucket | Rename (#4918), Enable (#4960) |
| platform-anvil-dev | anvil.explorer.gi.ucsc.edu                         | DB, E3JAUIVOC72EMP | Enable (#5005) | 
|                    | anvil.gi.ucsc.edu                                  | DB, E3JAUIVOC72EMP | Enable (#5005) | 
|                    | edu-ucsc-gi-platform-anvil-dev-awsconfig.us-east-1 | AWS Config bucket | Enable (#5004) |
|                    | edu-ucsc-gi-platform-anvil-dev-cloudtrail          | Old CloudTrail bucket | Delete (#4885) |
|                    | edu-ucsc-gi-platform-anvil-dev-logs.us-east-1      | Contains S3 access logs. AWS recommends not to Enable access logs on buckets containg access logs. | None |
|                    | edu-ucsc-gi-platform-anvil-dev.us-east-1           | Shared config bucket | Rename (#4918), Enable (#4960) |
| platform-hca-prod  | archive-preview.humancellatlas.org                 | DB, E1LYQC3LZXO7M3 | Enable (#5005) |
|                    | org-humancellatlas-data-browser-dcp2-prod          | DB, E1LYQC3LZXO7M3 | Enable (#5005) |
|                    | org-humancellatlas-data-portal-dcp2-prod           | DB, E1LYQC3LZXO7M3 | Enable (#5005) |
|                    | data-browser.explore.lungmap.net                   | DB, E22L661MUAMMTD | Enable (#5005) |
|                    | data-browser.lungmap.net                           | DB, E22L661MUAMMTD | Enable (#5005) |
|                    | edu-ucsc-gi-azul-dcp2-prod-config.us-east-1        | Shared config bucket | Rename (#4918), Enable (#4960) |
|                    | edu-ucsc-gi-platform-hca-prod-awsconfig.us-east-1  | AWS Config bucket | Enable (#5004) |
|                    | edu-ucsc-gi-platform-hca-prod-cloudtrail           | Old CloudTrail bucket | Delete (#4885) |
|                    | edu-ucsc-gi-platform-hca-prod-logs.us-east-1       | Contains S3 access logs. AWS recommends not to Enable access logs on buckets containg access logs. | None |

**Comment by dsotirho-ucsc** [comment]
Assignee to continue spike by filling in "Purpose" column in above table.

**Comment by hannes-ucsc** [comment]
All sub-tickets are closed. Assignee to double check that and the finding again, then close ticket or identify outstanding work.

**Comment by dsotirho-ucsc** [comment]
Confirmed in `dev`, `prod`, `anvildev`, and `anvilprod` that all buckets, except the logs bucket, have access logging enabled.

Also confirmed AWS best practices rule S3.9 has "Passed" status* on all 4 accounts.

## dev
![Screen Shot 2023-08-10 at 9 58 29 AM](https://github.com/DataBiosphere/azul/assets/46407464/d8845dca-3712-4f2c-a68a-78f0b1fa8cb6)

## anvildev
![Screen Shot 2023-08-10 at 9 58 42 AM](https://github.com/DataBiosphere/azul/assets/46407464/dcf22b01-e652-4710-a7bf-29d43cf49002)

## anvilprod
![Screen Shot 2023-08-10 at 9 58 48 AM](https://github.com/DataBiosphere/azul/assets/46407464/7b42a416-4fca-42d3-a27e-d0b156ab847c)

## prod
![Screen Shot 2023-08-10 at 9 58 59 AM](https://github.com/DataBiosphere/azul/assets/46407464/b3862bb0-fe11-4438-8a3d-bdf6695837bc)

*Note: The logs bucket are given a failed status in control S3.9 as logging is not enabled on these buckets, however since this is intended, these individual findings on the logs buckets have manually been marked "suppressed" so they don't cause the whole control to fail.

![Screen Shot 2023-08-10 at 10 05 59 AM](https://github.com/DataBiosphere/azul/assets/46407464/d83d9b34-7d85-427e-94ac-f91855936fc2)
