### ISSUE TITLE
Missing `treatment_protocol` in `prod` snapshot

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4736]
… `hca_prod_a1375150dda440818318c1593622da55__20221101_dcp2_20221101_dcp22`.
Causing 40 notifications to fail while the `dcp22` catalog was being indexed.
[Slack discussion.](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1668188529729779?thread_ts=1668187759.918709&cid=C9XD6L0AD)

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by theathorn** [comment]
Assignee to remove the affected project from the environment file for prod in a branch targeting develop. During the promotion this week, de-index the affected project (don't re-index unless a re-index is required organically for the promotion).

**Comment by theathorn** [comment]
[Slack thread](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1668187759918709).

**Comment by NoopDog** [comment]
Hi @achave11 is this deployed? Can we go live with dcp22? Thanks! D

**Comment by achave11-ucsc** [comment]
Hi @NoopDog, yes, this changes has been deployed to prod (https://github.com/DataBiosphere/azul/commits/prod). It should be safe to go live with dcp22.

**Comment by hannes-ucsc** [comment]
@theathorn to watch for updated snapshot for project with UUID=a1375150-dda4-4081-8318-c1593622da55

**Comment by hannes-ucsc** [comment]
We stopped waiting/parking for updated snapshots. The removal of the offending snapshot via hotfix addresses the issue.
