### ISSUE TITLE
AC-22 PUBLICLY ACCESSIBLE CONTENT

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4737]
Create a Revocation Policy across partners.
- The Terra team has complete controls and needs to inform UCSC of the best method to contact in the event of information spillage
- Since UCSC does not have any managed access data we do not have any procedure in place
- contact and confirm from Terra security what the current procedure is on communication so UCSC can adopt it, what is the preferred method of communication when we have a revocation of the right issue

Updated based on 2023 Audit:

There is no formal training for users to ensure that all issues and push/pull requests on the public facing GitHub page contain only publicly accessible content.

**Comment by nolunwa-ucsc** [comment]
created a procedure to leverage going forward, i will with share with Hannes, Ben and Dave on Thursday to provide input https://docs.google.com/document/d/1nS4e8EkpVW0tp5Lfc0Y36ONdPmXzhIYi5NzLhcwre8o/edit

**Comment by nolunwa-ucsc** [comment]
closing this as the implementation is https://github.com/DataBiosphere/azul/issues/6051
