### ISSUE TITLE
Remove need for feature branch hacks in dcp repo

### ISSUE THREAD

**Issue by alex-hancock** [DataBiosphere/azul#474]
This issue already exists in [dcp/#106](https://github.com/HumanCellAtlas/dcp/issues/106)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-315)
┆Project Name: azul
┆Issue Number: AZUL-315

**Comment by hannes-ucsc** [comment]
Too much work for us. Won't fix.
