### ISSUE TITLE
Test GitHub's credential filtering facility

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4745]

**Comment by hannes-ucsc** [comment]
I was able to push a fake secret key and a fake access key ID so if there are any measures against pushing AWS credentials, they're not very effective. This means that we need to mandate the use of `git-secrets` on every developer machine.

It should be said that AWS secret keys are 30 base64-encoded random bytes and the naïve regex `[a-zA-Z0-9+/]{40}` produces a ton of false positives. I tried anchoring that pattern with its inverse on either end and it still produced many false hits.

**Comment by hannes-ucsc** [comment]
@theathorn this is in the wrong epic.

**Comment by theathorn** [comment]
Follow on work tracked in #4858.

**Comment by carlaarchuleta308-source** [comment]
https://github.com/DataBiosphere/azul/issues/4745
