### ISSUE TITLE
elasticsearch_nodes.py fails too soon

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4755]
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/5383

This build recreated the ES domain, which leads to new set of node IDs. The script that infers them from CW metrics gave up too soon.

```
│ Error: External Program Execution Failed
│ 
│   with data.external.elasticsearch_nodes,
│   on cloudwatch.tf.json line 6, in data[0].external.elasticsearch_nodes:
│    6:                     "program": [
│    7:                         "python",
│    8:                         "/builds/ucsc/azul/scripts/elasticsearch_nodes.py"
│    9:                     ],
│ 
│ The data source received an unexpected error while attempting to execute
│ the program.
│ 
│ Program: /build/.venv/bin/python
│ Error Message: 2022-11-22 01:06:33,543 DEBUG   MainThread: Attempt 1/10
│ 2022-11-22 01:06:33,576 INFO    MainThread: Found credentials from IAM
│ Role: azul-gitlab
│ 2022-11-22 01:06:33,696 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:06:38,700 DEBUG   MainThread: Attempt 2/10
│ 2022-11-22 01:06:38,706 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:06:43,708 DEBUG   MainThread: Attempt 3/10
│ 2022-11-22 01:06:43,714 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:06:48,715 DEBUG   MainThread: Attempt 4/10
│ 2022-11-22 01:06:48,720 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:06:53,724 DEBUG   MainThread: Attempt 5/10
│ 2022-11-22 01:06:53,730 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:06:58,733 DEBUG   MainThread: Attempt 6/10
│ 2022-11-22 01:06:58,839 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:07:03,844 DEBUG   MainThread: Attempt 7/10
│ 2022-11-22 01:07:03,850 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:07:08,855 DEBUG   MainThread: Attempt 8/10
│ 2022-11-22 01:07:08,861 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:07:13,866 DEBUG   MainThread: Attempt 9/10
│ 2022-11-22 01:07:13,873 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ 2022-11-22 01:07:18,879 DEBUG   MainThread: Attempt 10/10
│ 2022-11-22 01:07:18,886 WARNING MainThread: No node IDs found in response.
│ Retrying …
│ Traceback (most recent call last):
│   File "/builds/ucsc/azul/scripts/elasticsearch_nodes.py", line 132, in <module>
│     main()
│   File "/builds/ucsc/azul/scripts/elasticsearch_nodes.py", line 46, in main
│     node_ids = get_node_ids()
│   File "/builds/ucsc/azul/scripts/elasticsearch_nodes.py", line 85, in get_node_ids
│     raise RuntimeError('Failed to obtain node IDs')
│ RuntimeError: Failed to obtain node IDs
│ 
│ State: exit status 1
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Also https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/57326

**Comment by hannes-ucsc** [comment]
And https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/5404

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Given that Cloudwatch metric granularity is 5 minutes by default, we should retry for 10 minutes"

**Comment by hannes-ucsc** [comment]
The solution for #4778 would fix this one, too.

**Comment by hannes-ucsc** [comment]
To demoed with #4778.
