### ISSUE TITLE
Ensure security contact information is registered

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4764]
```
{
    "GeneratorIds": [
      "aws-foundational-security-best-practices/v/1.0.0/Account.1"
    ]
}
```

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-account-1

Note: This finding relates to CIS-1.18 however it is one of the CIS checks that AWS Security Hub [does not support](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-cis-checks-not-supported.html#securityhub-standards-cis1.2-checks-not-supported) so there is no generator ID for it. 

> Security Hub doesn't support the following requirements of CIS AWS Foundations Benchmark v1.2.0 because they require manual checks of your resources:
> - 1.18 – Ensure security contact information is registered

---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by theathorn** [comment]
Spike to determine how Prowler flags this - the fix will follow from that.

**Comment by hannes-ucsc** [comment]
https://github.com/prowler-cloud/prowler/blob/master/checks/check118

They are calling ` aws account get-alternate-contact --alternate-contact-type SECURITY`.

It looks like we can use https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/account_alternate_contact to provide that contact.

**Comment by hannes-ucsc** [comment]
For demo, show that finding is fixed in `platform-anvil-dev`.
