### ISSUE TITLE
Move promotion notification to before stand up

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4774]

**Comment by achave11-ucsc** [comment]
Promotion reminder notification will be send weekly on Tuesdays at 11:15.
<img width="1076" alt="Screen Shot 2022-11-30 at 3 21 18 PM" src="https://user-images.githubusercontent.com/19215510/204929108-17f7425e-3785-44c4-bc56-9f1baf25ea22.png">

**Comment by dsotirho-ucsc** [comment]
Waiting until next Tuesday.

**Comment by theathorn** [comment]
Confirmed fixed.
