### ISSUE TITLE
No Slack notification for standup meeting

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4782]
There was no slack post for standup on 12/02/2022

**Comment by achave11-ucsc** [comment]
When attempting to update the integration settings in https://ucsc-gi.slack.com/services/1699128812950?updated=1, a warning reads … `Oops! Something isn’t right, we were unable to tell Google Calendar to work with Slack.`
while still allowing me to modify schedule details. I might need enhanced permissions in the Team Boardwalk google calendar or a calendar admin might need to reconfigure this integration.

**Comment by achave11-ucsc** [comment]
Modifying the time of the [reminder succeeded](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1670351402117499) and was sufficient to rehabilitate the calendar notifications, despite warning mentioned above.
