### ISSUE TITLE
Fix offboarding template

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4798]
Expand both these items:
> Removed the system administrator role from the offboarded employee/contractor's accounts or the offboarded employee/contractor did not perform the system administrator role
> Assigned the system administrator role to the replacement nominated by the project manager or the offboarded employee/contractor was not the sole system administrator

Remove the TODO:
> Removed the GitLab maintainer role from the offboarded employee/contractor (TODO: Fill in details of steps required to do this)

Remove from `Organization administrator actions`:
> Removed the offboarded employee/contractor's Google workspace account and the Google service account deleted above from the azul-dev group in Terra

**Comment by hannes-ucsc** [comment]
Walk through the off-boarding instructions and eliminate any redundancies. Replace high-level, general steps with concrete ones. Minimize work for the Org Admin.

**Comment by hannes-ucsc** [comment]
We'll do another dry run when we demo #4419.
