### ISSUE TITLE
Set up Development Deployment

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#48]
We need to set up the Dev Deployment for Orange (index, web service, UI)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-55)
┆Project Name: azul
┆Issue Number: AZUL-55
┆Epic: Setup HCA environments

**Comment by hannes-ucsc** [comment]
https://service.integration.explore.data.humancellatlas.org/

Note the absence of `/api` in the path.
