### ISSUE TITLE
ZenHub trial runs out 01/04/23

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4814]
https://files.slack.com/files-pri/T09P9H91S-F04EGP3BC0M/screen_shot_2022-12-09_at_10.10.49_am.png

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
I asked about limiting the set of paid-for users: https://community.zenhub.com/t/number-of-users/1010

**Comment by theathorn** [comment]
I don't seem able to buy a license for less than all the members (100) of the DataBiosphere organization:![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/7bb7f4f6-e7af-4104-a77b-d17b01b8b4fa)

**Comment by hannes-ucsc** [comment]
I asked on community thread linked to above.

**Comment by hannes-ucsc** [comment]
With help of ZenHub support I was able to remove users from the ZenHub organisation. We should be able to purchase a paid plan for a limited number of users now. We should discuss purchasing licenses for Clever Canary.

**Comment by theathorn** [comment]
A 10-user annual license was purchased using Kimberley Czupil's corporate credit card.
This will automatically renew annually on Jan 3rd.
