### ISSUE TITLE
Pooled specimens inflate estimated cell count

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#482]
Certain lab experiments pool cells from multiple specimens in a single cell suspension. This bundle from the 1M Neurons project in staging is an example: `b7fc737e-9b7b-4800-8977-fe7c94e131df`. It has one cell suspension and three specimens all of which are linked to the cell suspension via a dissociation process.

Azul extracts the cell count from the cell suspension and associates it with each specimen. This will inflate the aggregated cell count in the summary over all specimens or all specimens in a particular project.

We should detect pooled specimens and attribute the cell count equally. For example, if the cell suspension has 3000 cells, each specimen should be given 1000 (one third of 3000). This may not reflect the actual contribution from that specimen but it is a good enough estimation in my opinion. It was proposed to display "unknown" but then the project-wide aggregate would be too low.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-320)
┆Project Name: azul
┆Issue Number: AZUL-320

**Comment by theathorn** [comment]
Hannes to reevaluate validity of this in relation to #499.

**Comment by hannes-ucsc** [comment]
It turns out that https://github.com/DataBiosphere/azul/commit/82fd784d29c366fd5be32202abb9ed616ee5636c also fixed this issue. For proof, see #482.
