### ISSUE TITLE
Remove import of the gitlab security group from the TF 'shared' component

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4824]
Once the import of the `gitlab` default security group has been completed, remove the import from the `import_resources` Makefile target in the Terraform `shared` component.

**Comment by hannes-ucsc** [comment]
Fixed by https://github.com/DataBiosphere/azul/commit/36fc5d4f5b07de4bdf2e290cfddcf057dffb575a
