### ISSUE TITLE
Manifest download occasionally times out on staging

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#483]
Requesting a manifest on staging without any filters, takes close to 30s, sometimes over 30s and the request times out.

I think there are a few low-hanging fruit that have the potential to get us down to 15s or so. I would like to try the following optimizations.

1) Add logging statements so we see how long each phase of the request processing takes in a real lambda environment.

2) Eliminate the aggregates from the ES request.

3) Use [source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-source-filtering.html) to request only the fields from ES that are needed for preparing the manifest. I would propose to use store fields but I don't think our mapping specifies any stored fields. But keep that in mind as an possible alternative to source filtering.

5) "Stream" the TSV to S3. The point of this would be to overlap the ES I/O with the S3 I/O such that while we are waiting for a chunk to be written to S3, we're already fetching the next result from ES. This obviously involves threads. I can see two possible approaches: 1) a single PUT where boto3's `upload_fileobj()` method is given a custom implementation of `RawIOBase`. 2) a multipart PUT where each chunk is a part of the multipart upload. Each approach has caveats. 1) is tricky because the RawIOBase instance needs to be seekable which contradicts the streaming nature of this thing. 2) requires a finalizing CompleteMultipartUpload request and I don't know if that adds considerable latency. I doubt it and that's why I'd try 2) first.

4) Use `search_after` instead of the scroll API (or the `scan()` helper in elasticsearch_dsl)

I would like to try them in the order listed, as soon as we're down to 15s, let's file a PR and reconvene. Always measure the impact of each improvement.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-321)
┆Project Name: azul
┆Issue Number: AZUL-321

**Comment by shiroyuki** [comment]
So far, I'm up to the third step. I have tried a few approaches and the combination of them.

Let's start with what we currently have.

<img width="1113" alt="screen shot 2018-10-26 at 11 43 18 am" src="https://user-images.githubusercontent.com/226612/47577837-da9c0a00-d915-11e8-88d1-4072915e1a3e.png">

I have done some analysis and the part that the API stores a downloadable object in S3 generally takes up to 2.5 seconds.

First, I tried to limit the aggregation in `es_search` by only aggregating what is essential for facet search and TSV data construction. (`["cellCount", "donorDocumentId", "donorId", "entryId", "fileId", "fileName", "fileSize", "lab", "processId", "projectId", "specimenDocumentId", "specimenId", fileId", 
"fileName", "fileSize]`). The improvement is statistically insignificant.

<img width="1115" alt="screen shot 2018-10-26 at 11 43 36 am" src="https://user-images.githubusercontent.com/226612/47578025-51d19e00-d916-11e8-8060-2415c142f29c.png">

Then, with the combination of step 2 (using post_filter), the improvement is statistically insignificant.

<img width="1114" alt="screen shot 2018-10-26 at 11 43 54 am" src="https://user-images.githubusercontent.com/226612/47578066-70d03000-d916-11e8-9417-a121fdd1c163.png">

Then, I moved to use source filtering only.

<img width="1114" alt="screen shot 2018-10-26 at 11 44 12 am" src="https://user-images.githubusercontent.com/226612/47578187-bb51ac80-d916-11e8-940e-5bbbd2ad1935.png">

As you can see, the response time becomes much better even in the maximum query time.

Now, with the combination of post filtering and source filtering,

<img width="1114" alt="screen shot 2018-10-26 at 11 52 14 am" src="https://user-images.githubusercontent.com/226612/47578660-ebe61600-d917-11e8-9c0a-f715bc72c8ca.png">

The change in this case isn't significant.

For a short term fix, while at minimum source filtering seems to be fixing the issue, we can implement both source filtering and post filtering to mitigate the issue.

After that, I'll look into S3 multipart upload and `search_after`.

**Comment by shiroyuki** [comment]
Here is the result from PR #501 .

Without any filter, the API responds between 8 and 13 seconds on average (with 4 and 10 concurrently requests perspectively).

> 10 concurrent requests

<img width="1113" alt="screen shot 2018-10-29 at 1 46 49 pm" src="https://user-images.githubusercontent.com/226612/47669532-7a110500-db81-11e8-9cbb-3d9c0a200615.png">

> 4 concurrent requests

<img width="1112" alt="screen shot 2018-10-29 at 1 47 04 pm" src="https://user-images.githubusercontent.com/226612/47669724-e8ee5e00-db81-11e8-8242-b9fedaad330e.png">

In this example, any request to get manifests with `brain` is responded under a second.

<img width="1114" alt="screen shot 2018-10-29 at 1 47 24 pm" src="https://user-images.githubusercontent.com/226612/47669784-091e1d00-db82-11e8-96e0-ecd14419788a.png">

**Comment by shiroyuki** [comment]
@hannes-ucsc I tried to disable the aggregation. While the result after disabling aggregation with four concurrent requests seems to be similar to the previous result, the result with ten concurrent requests shows that the API provide more consistent.

<img width="811" alt="screen shot 2018-10-29 at 3 39 21 pm" src="https://user-images.githubusercontent.com/226612/47676020-d8de7a80-db91-11e8-8a13-ec7e3c5cb6f9.png">

After #501 is merged, I'll created the second PR for removing the aggregation from Manifest API.

**Comment by shiroyuki** [comment]
@hannes-ucsc The current implementation is querying the data and then pushing the data. The timeline looks like this.

```
|<---( ElasticSearch Query Time )--->|<---( S3 Put )--->|
```

> As mentioned in https://github.com/DataBiosphere/azul/issues/356#issuecomment-426049171, uploading to S3 with `s3_client.put_object` is pretty fast for the current data size that we are putting on S3. However, in the worst case scenario, the query time (after source filtering) still can take as long as 9-11 seconds.

One of the proposals to optimize the API is using S3 multipart upload to push the data as we receive the data from ElasticSearch. This means that the code doesn't have to spend time to push the data to S3 in one big batch at the end.

```
|<---( ElasticSearch Query Time )--->|
     |<-----( S3 Multipart Upload )----->|
```

I have tried to implement the multipart support in PR #520 but the code with multipart upload somehow slower than the original code (single put).

↓ Here is the benchmark on the overall response time before using multipart upload.

<img width="1086" alt="screen shot 2018-10-31 at 12 55 59 pm" src="https://user-images.githubusercontent.com/226612/47807147-bf643c80-dd11-11e8-82bd-de221947e3e1.png">

↓ Here is the benchmark on the overall response time after using multipart upload.

<img width="815" alt="screen shot 2018-10-31 at 1 17 31 pm" src="https://user-images.githubusercontent.com/226612/47807213-ecb0ea80-dd11-11e8-907f-b1efc2572e1f.png">

As the current datasets on the dev ES can only be translated to up to 26 MB of TSV content, it seems that we won't get the full benefit of the multipart upload at the moment.

What do you think?
