### ISSUE TITLE
Move CloudTrail trail to default region

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4831]
We're constantly running into issues with our choice to place the trail into the US-west-2 region (which we did to maintain continuity with the preexisting trail). Other than continuity, we gain nothing from that choice. 

- [x] Create a new trail called `azul-cloudtrail-{deployment_stage}`<sup>1</sup>. Leave the original trail in place.
- [x] Change all references to the original trail to point to the new trail.
- [x] Disable logging on the original trail
- [x] Create a new trail bucket with the same name<sup>1</sup> as the current bucket with the suffix `.{region}` appended. 
- [x] Associate the new trail with the new bucket. 

<sup>1 Name changed from `cloudtrail` to `trail` to ensure consistency and avoid conflict with existing log group</sup>

-----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, show trail, log group and bucket in `anvildev`. Show original trail, log group and bucket. Show that new and original trail are searchable via CloudTrail directly and in Cloudwatch Insights. Show that the original trail is not being logged to and that the original bucket is not being written to.
