### ISSUE TITLE
Disable original CloudTrail trail

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4832]
Care must be taken to remove the trail, log group, and trail bucket from underneath Terraform's management without actually deleting them. 

Leave the original bucket, log group, and trail in place so that we can run queries against them.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by nadove-ucsc** [comment]
The PR for this issue should also be linked to https://github.com/DataBiosphere/azul/issues/4829

**Comment by nadove-ucsc** [comment]
Add support to `rename_resources` script for removing resources from the state by using `None` as the new resource name.

**Comment by hannes-ucsc** [comment]
This change does not remove any resources. It just takes them away from Terraform for management. #4885 will delete the legacy trail, but not the legacy trail bucket or the CloudWatch log groups that the legacy trail was forwarded to.

**Comment by hannes-ucsc** [comment]
Not much to demo here since the cloud resources remain.
