### ISSUE TITLE
CM-9: Configuration Management Plan

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4850]
[CM-9 Control Description](https://www.stigviewer.com/controls/800-53/CM-9).

**Comment by nolunwa-ucsc** [comment]
this is the plan https://docs.google.com/document/d/1KdVX2ppBo-cRk0AQsdD90py4BUfFQnKqVrUVjCtxWwM/edit

**Comment by theathorn** [comment]
@nolunwa commented to me: "We have the plan, needs to be updated and reviewed by you afterward. Assign to me for now."

**Comment by nolunwa-ucsc** [comment]
CM Plan https://docs.google.com/document/d/1KdVX2ppBo-cRk0AQsdD90py4BUfFQnKqVrUVjCtxWwM/edit
