### ISSUE TITLE
Disable creation of automatic tasks in Slack

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4855]
https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1671648246452619

It appears that the automatic task creation by the Task Reminder app can't be disabled. I checked the app's configuration and documentation. This won't work for us. We've previously used an app that automatically **offered** to create a task whenever you typed a matching phrase. That app was useful. Can we switch back to using it? 

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by theathorn** [comment]
Spike to diagnose.

**Comment by achave11-ucsc** [comment]
I was unable to find the app that **offered** to create a task. That App might have been Task Reminder confirming a task when it wasn't sure.
Non of the task/reminder apps I looked at are as concise and effective as Task Reminder.
I suggest to keep Task Reminder, and be aware that @ mentioning someone and including a URL link will automatically create a task ([reference](https://www.labfortysix.com/link-reminder/quickstart?utm_source=slack_bot-dm-open&utm_medium=organic#automatic-reminders)). The prompt to create a task under said scenario is only raised when Task Reminder isn't sure, the criteria used by the algorithm isn't described only mentions that [non-essential links](https://www.labfortysix.com/link-reminder?utm_source=slack_app-listing&utm_medium=referral) are dismissed. Furthermore, we could contact the support team and ask if it's possible to disable the automatic feature and leave the prompt feature as default.

Other apps like [Follow Up Bot](https://ucsc-gi.slack.com/apps/A03JYBLAUKX-follow-up-bot?tab=more_info) work differently than task reminder. This app will look for unanswered Slack question/s after a configurable amount of time (minimum 10 min), and will make a post to the configured channel regarding the unanswered question. It is unknown how frequently this post are made.

Also, apps like [Todo](https://ucsc-gi.slack.com/apps/AU5C4QPQS-todo?tab=more_info), [Poppins](https://ucsc-gi.slack.com/apps/A01TH66ME7K-poppins?tab=more_info), [Workast](https://ucsc-gi.slack.com/apps/A0HBTUUPK-workast?tab=more_info), [Donezo](https://ucsc-gi.slack.com/apps/APTE3DX7D-donezo?tab=more_info) and [Kyber](https://ucsc-gi.slack.com/apps/A0EP69E58-kyber?tab=more_info) require to manually set the task, the users involved, a deadline and frequency of notifications.

**Comment by achave11-ucsc** [comment]
Assignee to determine next steps.
