### ISSUE TITLE
Mandate use of git-secrets

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4858]
For due diligence preventing us from committing secrets, we need to mandate the use of [git-secrets](https://github.com/awslabs/git-secrets) by every developer. 

Install `git-secrets` and write up a short paragraph under *Prerequisites* in the README. Add an entry to the issue template for onboarding.

**Comment by theathorn** [comment]
@hannes-ucsc to provide details.

**Comment by hannes-ucsc** [comment]
I'm sure there is a NIST control for this. @nolunwa, do you know?

**Comment by nolunwa-ucsc** [comment]
@hannes-ucsc this 3 controls requires Secrets should not be in code, [Git-secrets](https://github.com/awslabs/git-secrets), trufflehog or other similar tools should use to prevent/detect.

The controls are SA-03 (system development lifecycle) , SA-08 (security engineering principle) and SA-11 (Developer Testing and Evaluation)

**Comment by hannes-ucsc** [comment]
On Slack, we'll collect every team member's confirmation that they installed, and verified the proper function of, git-secrets.
