### ISSUE TITLE
Combine logged request query and headers into one JSON literal

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4868]
Currently requests are logged with two separate JSON literals, one for the query parameters, and one for the request headers. Combine these two JSON literals into one nested JSON structure, such that:

> [INFO] 2022-12-31T23:36:50.891Z c9300ddf-07c3-4b21-abe5-5c02297b5997 azul.chalice Received HEAD request for '/index/projects', with query {"size": "1"} and headers {"accept": "*/*", "accept-encoding": "gzip, deflate", "cloudfront-forwarded-proto": "https", "cloudfront-is-desktop-viewer": "true", "cloudfront-is-mobile-viewer": "false", "cloudfront-is-smarttv-viewer": "false", "cloudfront-is-tablet-viewer": "false", "cloudfront-viewer-asn": "14618", "cloudfront-viewer-country": "US", "host": "service.dev.singlecell.gi.ucsc.edu", "user-agent": "python-requests/2.28.1", "via": "1.1 3042bd56e0ca0a7910df89f6b5e95e9e.cloudfront.net (CloudFront)", "x-amz-cf-id": "lcIU9wetF_-YknujlxxQUIZd-w1jrZ2l7NptE4QcYmXZU6LRrOmkmA==", "x-amzn-trace-id": "Root=1-63b0c792-601592823a75396a6e5f4371", "x-forwarded-for": "52.20.215.168, 15.158.50.144", "x-forwarded-port": "443", "x-forwarded-proto": "https"}.

would become:

> [INFO] 2022-12-31T23:36:50.891Z c9300ddf-07c3-4b21-abe5-5c02297b5997 azul.chalice Received HEAD request for '/index/projects', with {"query": {"size": "1"}, "headers": {"accept": "*/*", "accept-encoding": "gzip, deflate", "cloudfront-forwarded-proto": "https", "cloudfront-is-desktop-viewer": "true", "cloudfront-is-mobile-viewer": "false", "cloudfront-is-smarttv-viewer": "false", "cloudfront-is-tablet-viewer": "false", "cloudfront-viewer-asn": "14618", "cloudfront-viewer-country": "US", "host": "service.dev.singlecell.gi.ucsc.edu", "user-agent": "python-requests/2.28.1", "via": "1.1 3042bd56e0ca0a7910df89f6b5e95e9e.cloudfront.net (CloudFront)", "x-amz-cf-id": "lcIU9wetF_-YknujlxxQUIZd-w1jrZ2l7NptE4QcYmXZU6LRrOmkmA==", "x-amzn-trace-id": "Root=1-63b0c792-601592823a75396a6e5f4371", "x-forwarded-for": "52.20.215.168, 15.158.50.144", "x-forwarded-port": "443", "x-forwarded-proto": "https"}}.

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, show new log message. Show that Cloudwatch parses all headers and query parameters into separate fields that can be filtered on.
