### ISSUE TITLE
Invalid value for URL param `order` should cause 4xx error

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4877]
Currently an invalid value given to the `order` URL param will produce a 500 response along with a stack trace.
Instead, a 4xx response should be returned with no stack trace.

Example:
```
$ curl --fail-with-body 'https://service.dev.singlecell.gi.ucsc.edu/index/bundles?catalog=dcp2&filters=%7B%7D&order=%2527&search_after=%5B1644398658267%2C%20%22494295a9-d6da-42a6-bda2-40b51ffeb84d%22%5D&size=10&sort=bundleVersion'
Traceback (most recent call last):
…
  File "/var/task/azul/service/elasticsearch_service.py", line 132, in prepare_request
    request = self.outer.prepare_request(request)
  File "/var/task/azul/service/elasticsearch_service.py", line 515, in prepare_request
    request = request.sort(*sort(sort_order))
  File "/var/task/azul/service/elasticsearch_service.py", line 485, in sort
    assert order in ('asc', 'desc'), order
AssertionError: %27
curl: (22) The requested URL returned error: 500
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce and show that next vulnerability scan by Invicti reflects the fix.

**Comment by dsotirho-ucsc** [comment]
Demoed reproduction, awaiting a new Invicti scan to complete demo.
