### ISSUE TITLE
Invalid mix of `search_after` and `search_before` should cause 4xx error

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4879]
An invalid mixture of the `search_after` and `search_before` URL params will produce a 500 response.
Instead, a 4xx response should be returned.

Example:
```
$ curl --fail-with-body 'https://service.dev.singlecell.gi.ucsc.edu/index/samples?catalog=lm2-it&filters=%7B%0A%20%20%22cellCount%22%3A%20%7B%0A%20%20%20%20%22within%22%3A%20%5B%0A%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%2010000%2C%0A%20%20%20%20%20%20%20%201000000000%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&order=desc&search_after=3&search_after_uid=3&search_before=3&search_before_uid=3&size=10&sort=cellCount'
curl: (22) The requested URL returned error: 500
{"Code":"ChaliceViewError","Message":"Only one of search_after or search_before may be set"}
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce and show that next vulnerability scan by Invicti reflects the fix.

**Comment by dsotirho-ucsc** [comment]
Demoed reproduction, awaiting a new Invicti scan to complete demo.
