### ISSUE TITLE
Alarms for CIS recommendations should treat missing data as OK

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4880]
… alarm filters will only produce hits when the filter matches entries in the log, so the absence of matches should indicate an OK state.
```
Index: terraform/shared/shared.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/shared/shared.tf.json.template.py b/terraform/shared/shared.tf.json.template.py
--- a/terraform/shared/shared.tf.json.template.py	(revision 50f68819fe855f200f378a2ad494565b43286668)
+++ b/terraform/shared/shared.tf.json.template.py	(date 1673388998163)
@@ -357,6 +357,7 @@
                 'metric_name': a.metric_name,
                 'namespace': 'LogMetrics',
                 'statistic': a.statistic,
+                'treat_missing_data': 'notBreaching',
                 'threshold': 1,
                 # The CIS documentation does not specify a period. 5 minutes is
                 # the default value when creating the alarm via the console UI.

```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, pick an alarm, say, the one for "unauthorized access", and show that the absence of matching log events for one hour—after the ALARM notification was sent—results in an OK notification.
