### ISSUE TITLE
Legacy `azul-shared` trail fails SecurityHub checks

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4885]
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/5143256/211882766-5653ff5a-66f2-4635-a44f-5fb1fdda494e.png">

<img width="1202" alt="Screen Shot 2023-01-11 at 10 00 34 AM" src="https://user-images.githubusercontent.com/5143256/211882817-b79957f8-b737-4f1f-a09e-cf2853616227.png">

<img width="1207" alt="Screen Shot 2023-01-11 at 10 00 47 AM" src="https://user-images.githubusercontent.com/5143256/211882864-c5261172-ae4e-4a2b-b760-e91910373241.png">

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
We will delete the legacy trail. We can always [search the backing bucket using Athena](https://docs.aws.amazon.com/athena/latest/ug/cloudtrail-logs.html) if we need to.

**Comment by nadove-ucsc** [comment]
@hannes-ucsc: "This needs to wait until https://github.com/databiosphere/azul/issues/4832 is solved."

**Comment by hannes-ucsc** [comment]
- [x] Delete legacy trail in `anvildev`, leave bucket and log group
- [x] Delete legacy trail in `dev`, leave bucket and log group
- [x] Wait for blocker #4832 to arrive in `prod`
- [x] Delete legacy trail in `prod`, leave bucket and log group

**Comment by hannes-ucsc** [comment]
In 90 days, delete legacy bucket and log group in all AWS accounts.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce in all deployments.

Then put ticket into Parked, do not close b/c previous comment.

**Comment by hannes-ucsc** [comment]
Deleted bucket edu-ucsc-gi-platform-anvil-dev-cloudtrail and log group azul-cloudtrail-anvildev.

**Comment by hannes-ucsc** [comment]
Deleted log group `azul-cloudtrail-anvildev`. There was no log group for the old trail in prod.

**Comment by hannes-ucsc** [comment]
Deleted log group `azul-cloudtrail-dev`. That leaves two remaining resources to be deleted: the trail buckets in `dev` and `prod`: `edu-ucsc-gi-platform-hca-prod-cloudtrail` and `edu-ucsc-gi-platform-hca-dev-cloudtrail`.

I'm having difficulties emptying the prod bucket `edu-ucsc-gi-platform-hca-prod-cloudtrail`. Initially, interactively emptying the bucket seemed to work until about 1 million objects were deleted and then the process stalled. I tried restarting it but it stalled at 0 deleted objects, even though there are still objects in the bucket. I suspect the same thing would happen for the `dev` bucket.

Amazon suggests using a lifecycle policy to evict objects from a bucket with many objects. This needs a little bit more research and I would like to enlist the operator's help with it (research and execution).

*It is important that this is done on the correct buckets, so please be extra careful.*

**Comment by achave11-ucsc** [comment]
To accomplish this by introducing a deletion policy for old objects, go to the bucket's 'Management' tab and create the following lifecycle policy.

![Screen Shot 2023-05-31 at 3 09 40 PM](https://github.com/DataBiosphere/azul/assets/19215510/81743201-b059-462c-a2ab-a2d606e6ee6a)
![Screen Shot 2023-05-31 at 3 09 47 PM](https://github.com/DataBiosphere/azul/assets/19215510/a3f848a1-48ee-4ce7-bb56-af85d16bcb2e)

This is done for the `edu-ucsc-gi-platform-hca-dev-cloudtrail` bucket.

**Comment by achave11-ucsc** [comment]
This is also done for `edu-ucsc-gi-platform-hca-prod-cloudtrail`.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Let's monitor the buckets, and delete them when they're empty."

**Comment by achave11-ucsc** [comment]
Both buckets have been deleted from S3.
<img width="1408" alt="Screen Shot 2023-06-02 at 2 52 17 PM" src="https://github.com/DataBiosphere/azul/assets/19215510/d15d881f-0201-45a9-9507-1320fcbf8743">
<img width="1415" alt="Screen Shot 2023-06-02 at 2 53 24 PM" src="https://github.com/DataBiosphere/azul/assets/19215510/af594257-5200-45bc-acbf-53d5b043fff5">

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "For demo, show that findings CIS 2.2, 2.4, and 2.6 are fixed in all accounts."
