### ISSUE TITLE
Many false positives for `azul-api_unauthorized-*` alarms

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4886]
To reproduce, in a web browser, log into the `gi-gateway` account using the AWS Console, switch to the `developer` role in one of our own AWS accounts (`platform-{hca,anvil}-{dev,prod}` ), and open a resource page, say, that of the GitLab EC2 instance. Let the session expire, 8 to 12 hours. Reload the page. You are redirected to the login page. Log in again. Before you have a chance to switch back to the previous role, the console redirects back to the resource page. The resulting API requests are rejected with an "Unauthorized" response because the resource resides in our own AWS account, while the current credentials belong to your IAM user in the `gi-gateway` account. The error is resolved by switching roles again. The rejected request, however, was already logged in CloudTrail where it will trigger the CloudWatch log metric alarm for unauthorized requests, as mandated by CIS.

I consider this a bug in the AWS Console: when redirecting back to the original resource page, the console should also switch to the role that was active when the page was last loaded successfully.

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to fill in details.

**Comment by hannes-ucsc** [comment]
Ideas to resolve are 

- using

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to see if a particular console setting prevents the original page from being reloaded after sign in.

**Comment by hannes-ucsc** [comment]
It doesn't, unfortunately.

**Comment by hannes-ucsc** [comment]
The workaround is to never sign into the console from an expired browser tab, but to instead use a plain sign-in URL, one that doesn't have the "redirect back to where you were" parameters appended to it. This can be achieved by dragging a bookmark to the plain sign-in URL of the into the expired tab, or by closing the expired tab and opening a new one, from the bookmark, or the browser's location bar auto-complete/history.

Developer awareness of this workaround has increased and we now have very low rate of false positives stemming from to this issue.
