### ISSUE TITLE
AWS `developer` policy inconsistent between `dev` and `prod`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4895]
`dev` on left, `prod` on right

![Screen Shot 2023-01-11 at 3 54 58 PM](https://user-images.githubusercontent.com/19215510/211943351-b187157f-d607-47e1-a519-ebecabaa1c72.png)

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to come up with design.

**Comment by hannes-ucsc** [comment]
We can't allow developers to change the permissions of the GitLab instance in `prod`, neither the boundary policy nor the regular policy, so the statement with the `Sid` of `DeployGitlab` must not be present in `prod`. The additional IAM actions in `prod` on the right should be present in `dev` and `anvildev`.

**Comment by hannes-ucsc** [comment]
> The additional IAM actions in prod on the right should be present in dev and anvildev.

Fixed in both.
