### ISSUE TITLE
Deliver "clean" Prowler report to the Broad security team

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4898]
Now that all cis level 1 findings have been addressed we need to generate a new Prowler report proving this and send it to David Bernick and Sarah Tahiri.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to link to respective Slack posting.

**Comment by hannes-ucsc** [comment]
Report delivered on Slack: https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1673981422305319

**Comment by dsotirho-ucsc** [comment]
Response from Broad: "`@Trevor Heathorn: Thank you for sending! We've sent the report to @David Bernick (he/him) and now have sign-off for the demo. cc: @rliao @Michael Baumann`"
