### ISSUE TITLE
Update diagram screenshots in all monitoring issues

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4917]
Most of the issues in Epic SI-4 have a screenshot of the diagram in which the affected component is highlighted in green. The diagram has evolved since the issues were created. We should update the screenshots.

**Comment by dsotirho-ucsc** [comment]
Screenshots updated in the description of the following SI-4 tickets:
- https://github.com/DataBiosphere/azul/issues/3702
- https://github.com/DataBiosphere/azul/issues/3894
- https://github.com/DataBiosphere/azul/issues/4008
- https://github.com/DataBiosphere/azul/issues/4011
- https://github.com/DataBiosphere/azul/issues/4175
- https://github.com/DataBiosphere/azul/issues/4176
- https://github.com/DataBiosphere/azul/issues/4177
- https://github.com/DataBiosphere/azul/issues/4178
- https://github.com/DataBiosphere/azul/issues/4189
- https://github.com/DataBiosphere/azul/issues/4198
- https://github.com/DataBiosphere/azul/issues/4586
- https://github.com/DataBiosphere/azul/issues/4641
- https://github.com/DataBiosphere/azul/issues/4653
- https://github.com/DataBiosphere/azul/issues/4667
- https://github.com/DataBiosphere/azul/issues/4668
