### ISSUE TITLE
Rename `shared` (aka `versioned` aka `config`) bucket

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4918]
The new bucket name should be 

`edu-ucsc-gi-{aws.accountname}-shared.{aws.region}`

so for example

`edu-ucsc-gi-platform-anvil-dev-shared.us-east-1`

instead of 

`edu-ucsc-gi-platform-anvil-dev.us-east-1`

This is a complicated migration considering that the bucket is shared by all deployments in an AWS account. I have a pretty good idea how this should work but I struggle to write it down precisely without being very verbose, which would consume an excessive amount of time. I should just do this, and soon, while my memory is fresh.

Notes to self:

- [replication](https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html)
- [batch replication](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-batch-replication-batch.html)
- [delete marker replication](https://docs.aws.amazon.com/AmazonS3/latest/userguide/delete-marker-replication.html)
- delete from state on `develop` and then re-import from feature branch
- quite period between deploys
- temporarily disable life-cycle rules

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to provide description.

**Comment by hannes-ucsc** [comment]
This is blocking compliance tickets so we'll need to treat it as a compliance ticket.

**Comment by hannes-ucsc** [comment]
For demo, in all AWS accounts, show presence of new bucket with correct name and absence of old bucket.

**Comment by hannes-ucsc** [comment]
Doing this in two PRs. The first PR creates the new bucket with the correct name, sets up replication
between the old and the new bucket so that future object versions are copied, and runs a batch migration of prior and current objects versions. The second PR will actually switch all deployments to using the new bucket.
