### ISSUE TITLE
Viewing AWS support tickets with `developer` role raises api_unauthorized alarm

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4919]
In the AWS console, navigating to the Support service and viewing an existing ticket with the `developer` role (specifically `developer @ platform-hca-prod` in this case) causes an `AccessDenied` error to be logged in Cloudwatch and raises the `api_unauthorized` alarm.

Ideally performing this action would not cause the error or alarm.

An instance of this alarm and the related Cloudwatch log can be found in this [Google groups thread](https://groups.google.com/a/ucsc.edu/g/azul-group/c/qbXe2w-3ZIE/m/_fMTUSqXAQAJ). 

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Tried the obvious by modifying the `developer` role to allow ListDelegatedAdministrators, to no avail. Emailed Erich for help.

**Comment by hannes-ucsc** [comment]
After Erich worked with AWS support to address this in the administrator account for our organisation, we are unable to reproduce this issue and consider it fixed.
