### ISSUE TITLE
Assign role-based training courses to individual team members

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4932]
https://docs.google.com/document/d/11JZlwNppGfjAkYVHnD_bgQIzk7_Rn5sLY_lWpuw_gzo

Each team member needs to have completed 1h of training by March 20.

I propose the following courses for each team member:

- Daniel: [#403 - Amazon Detective](https://learn.acloud.guru/series/aws-service-spotlight/view/403) 
- Noah: [Cross Site Scripting (XSS) 101](https://safecode.org/lessons/cross-site-scripting-xss-101/)
- Abraham: [Threat Modelling 101](https://safecode.org/courses/threat-modeling-101/)
- Hannes: [AWS for Architects - Advanced Security](https://www.linkedin.com/learning/aws-for-architects-advanced-security/welcome?u=65318132)

I also propose that each team member prepares a short 5min presentation post-standup (no more than three slides) with key takeaways.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to provide details.

**Comment by hannes-ucsc** [comment]
8 = 4 * (1 + 1)

Four assignees, each take 1 hour of training, 1h for preparing presentation.

**Comment by nadove-ucsc** [comment]
Finished.

**Comment by dsotirho-ucsc** [comment]
Demoed.
Slides: [Amazon Detective overview ](https://docs.google.com/presentation/d/1ZPgz8B75RzbftQmqCLp7SCdqFaUi42opg9BtdGqXOiY/edit?usp=sharing)

**Comment by nadove-ucsc** [comment]
[Slides](https://docs.google.com/presentation/d/1wGJOIWH7qTpk1tLiUoiPN7CsM3jTfGvXsdjUPFVsArw/)

**Comment by achave11-ucsc** [comment]
Demoed, [presentation](https://docs.google.com/presentation/d/1eRR8-3MWwCYorsocUOHhrGGqXlO7LX1ztoCHuZjG1Rc).

**Comment by hannes-ucsc** [comment]
[Advanced security architecture.pdf](https://github.com/DataBiosphere/azul/files/11006068/Advanced.security.architecture.pdf)

**Comment by nolunwa-ucsc** [comment]
SSP updated
