### ISSUE TITLE
Use TDR roleMap endpoint for list of accessible snapshots

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4937]
From https://humancellatlas.slack.com/archives/C01360XN04S/p1674856528424779?thread_ts=1668020229.262939&cid=C01360XN04S

> Hello :wave: circling back to update that that we've added a new TDR snapshots endpoint [getSnapshotIdsAndRoles](https://jade.datarepo-dev.broadinstitute.org/swagger-ui.html#/snapshots/getSnapshotIdsAndRoles) as part of https://broadworkbench.atlassian.net/browse/DR-2852.  It is available in TDR dev and will be available in prod after our next monolith release, currently scheduled for Wednesday 2/1.
This endpoint returns the caller's accessible snapshot IDs mapped to the roles which confer access.
Example invocation and response:
>
> ```
> curl -X 'GET' \
>   'https://jade.datarepo-dev.broadinstitute.org/api/repository/v1/snapshots/roleMap' \
>   -H 'accept: application/json' \
>   -H 'Authorization: Bearer <token>'> 
>
> {
>   "roleMap": {
>     "ac1ea569-f70d-4189-affd-61a3dc06422a": [
>       "steward",
>       "admin",
>       "discoverer"
>     ],
>     "1b3b475f-8b70-4972-97f9-61047d26aa30": [
>       "steward",
>       "admin"
>     ]
>   },
>   "errors": []
> }
> ```
>
> As a reference, in TDR dev I am seeing sub-second response times (in Swagger you can see this as "Request duration" within the server response). (edited)

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Two-part demo. Demo in `dev` as soon as possible.

For demo in `dev`, show that signing into the `dev` instance of the Data Browser reveals the files from the two mock managed-access snapshots in TDR `dev`. 

For demo in `prod`, using CloudWatch Logs , compare the average latency of  requests to the new endpoint with those of the old one.

**Comment by nadove-ucsc** [comment]
Demoed in `dev`.

**Comment by nadove-ucsc** [comment]
Demoed in `prod`.

**Comment by nadove-ucsc** [comment]
Between 2 and 3 -fold improvement in latency (~1.25s -> ~0.48s)
