### ISSUE TITLE
GitHub jobs are run twice

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4939]
![image](https://user-images.githubusercontent.com/48401926/215597829-41bc42d7-959c-45fb-b800-76bcb29f3b8e.png)

https://github.com/DataBiosphere/azul/pull/4905 changed our CI config to run all jobs for both the `push` trigger and `pull_request` trigger. This is now causing all jobs be run twice for each commit where the CI is run. I can't prove causation, but it's felt like CI is a lot slower since this change was made. I often observe jobs sitting queued for longer than it takes to actually run them, meaning it can take over an hour to get a green build.

We should consider reverting this change or devising a different way to limit when the CI is run.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
It is caused by #4905. Not only do the jobs wait in the queue for longer, I've also observed them to fail completely due to tripping the GH API rate limit. I'd rather accept codeql false positives on chained PRs rather than everyone having to deal with this all the time. We should roll back the fix for #4905.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
