### ISSUE TITLE
Push down HCA specifics to a `Bundle` subclass

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4940]
https://github.com/DataBiosphere/azul/issues/2693#user-content-4940

**Comment by nadove-ucsc** [comment]
Spike to explore and estimate a solution.

**Comment by hannes-ucsc** [comment]
Unpinning because relative to other ongoing work this is lower.

**Comment by achave11-ucsc** [comment]
@noah-aviel-dove: "Explored solution and estimated this to be 13 or 21."

**Comment by hannes-ucsc** [comment]
Refactoring, nothing to demo here.
