### ISSUE TITLE
Ensure that each `Bundle` instance is a complete subgraph

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4941]
https://github.com/DataBiosphere/azul/issues/2693#user-content-4941

**Comment by nadove-ucsc** [comment]
We do not index [project](https://github.com/DataBiosphere/azul/issues/4827) or [antibody](https://github.com/DataBiosphere/azul/issues/4440) entities. Consequently, we do not index the FK relationships `assayactivity.antibody_id -> antibody.antibody_id` and `project.generated_dataset_id -> dataset.datset_id`.

**Comment by nadove-ucsc** [comment]
I presume that all foreign keys are insignificant columns. `source_datarepo_row_ids` is the only non-FK column in the schema that I believe is insignificant.

**Comment by nadove-ucsc** [comment]
Summary of FK relations that we currently follow for primary bundles:

| Foreign key                               | Primary key               | Followed...                           |
| ----- | ----- | ----- | 
| activity.used_file_id                     | file.file_id              | Up from files, down from files        |
| activity.generated_file_id                | file.file_id              | Up from files, down from biosamples, down from files |
| activity.used_biosample_id                | biosample.biosample_id    | Up from files, down from biosamples   |
| alignmentactivity.used_file_id            | file.file_id              | Up from files, down from files        |
| alignmentactivity.generated_file_id       | file.file_id              | Up from files, down from files        |
| assayactivity.antibody_id                 | antibody.antibody_id      |                                       |
| assayactivity.generated_file_id           | file.file_id              | Up from files, down from biosamples   |
| assayactivity.used_biosample_id           | biosample.biosample_id    | Up from files, down from biosamples   |
| biosample.donor_id                        | donor.donor_id            | Up from biosamples                    |
| biosample.part_of_dataset_id              | dataset.dataset_id        | Up from biosamples                    |
| donor.part_of_dataset_id                  | dataset.dataset_id        |                                       |
| diagnosis.donor_id                        | donor.donor_id            | Up from donors                        |
| project.generated_dataset_id              | dataset.dataset_id        |                                       |
| sequencingactivity.generated_file_id      | file.file_id              | Up from files, down from biosamples   |
| sequencingactivity.used_biosample_id      | biosample.biosample_id    | Up from files, down from biosamples   |
| variantcallingactivity.used_file_id       | file.file_id              | Up from files, down from files        |
| variantcallingactivity.generated_file_id  | file.file_id              | Up from files, down from files        |

**Comment by nadove-ucsc** [comment]
Whether this set of FK relations represents a "complete" subgraph (barring the aforementioned entity types) depends on the definition of "complete." Because every entity in the snapshot is linked directly or indirectly to the singleton `dataset` entity, the entire snapshot forms a single connected graph. Currently, our traversal algorithm includes:

- The bundle entity
- Every (transitive) descendant of the bundle entity
- Every (transitive) ancestor of all aforementioned entities

Notably, we do _not_ include descendants of entities that are not the bundle entity.

I think our current set of indexed FKs satisfies those bullet points.

**Comment by nadove-ucsc** [comment]
> I think our current set of indexed FKs satisfies those bullet points.

@hannes-ucsc: "I agree."

**Comment by nadove-ucsc** [comment]
Extend spike 1 hour to ask about projects:

1. Confirm project is higher in hierarchy than dataset, i.e., one project can have multiple datasets but not vice versa
2. Are snapshots generated per dataset or per project?
3. Last time we checked, projects table had no meaningful information; has this changed?

**Comment by nadove-ucsc** [comment]
Assert that `biosample.part_of_dataset_id` and `donor.part_of_dataset_id` are redundant by including the latter in the indexed columns and verifying that it matches the retrieved dateset in the plugin following the retrieval of the entities.

**Comment by nadove-ucsc** [comment]
> Confirm project is higher in hierarchy than dataset, i.e., one project can have multiple datasets but not vice versa

Confirmed.

> Are snapshots generated per dataset or per project?

Per dataset.   

> Last time we checked, projects table had no meaningful information; has this changed?

"Most snapshots should have some meaningful data in this table now."

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/4941#issuecomment-1548479331 looks unaddressed.

Support for antibodies will be added in #4440.

Support for projects will be added in #4827.

I'll put those in the epic but leave them out of the [AnVIL Public Release](https://github.com/DataBiosphere/azul/milestone/33) milestone. Pending the open comment above, we should be able to make this a zero estimate.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We determined during stand-up that Noa's comment above is meant to specify what needs to be done as part of this ticket. This means that this ticket was not a zero estimate, there is still a small amount of work left."
