### ISSUE TITLE
Represent verbatim metadata as `Document` subtype `Replica`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4942]
https://github.com/DataBiosphere/azul/issues/2693#user-content-4942

**Comment by nadove-ucsc** [comment]
@hannes-ucsc : "Assignee to break this up into smaller tickets."

**Comment by nadove-ucsc** [comment]
1. Refactor abstraction of indices to accommodate a `replica` index type in addition to `contribution` and `aggregate` (estimate 40)
2. Emit replica instances and populate the replica index, omitting the `hub_ids` field (estimate 40)
3. Incorporate `hub_ids` (estimate 40)

**Comment by nadove-ucsc** [comment]
Assignee to create tickets for each bullet point.

**Comment by hannes-ucsc** [comment]
Epic is complete.
