### ISSUE TITLE
SI-10 INFORMATION INPUT VALIDATION

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#4953]
Update [this section](https://docs.google.com/document/d/1_-QRKKkSgi_yq5dyDNCQ__IrVLDFc74t57Z2_UiOktc/edit?disco=AAAAgrjsGmc) in the UCSC Azul Data Browser Incident Response Procedure.

**Comment by nolunwa-ucsc** [comment]
@theathorn related control is SI-10, need to document react inbuilt capability and security protection here

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to determine where we would document our implementation of this control.

**Comment by hannes-ucsc** [comment]
I'll add a section to the security architecture document.
