### ISSUE TITLE
Service `app.repository_controller` should be cached

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4957]
https://github.com/DataBiosphere/azul/blob/350fe6400a7ad82f05375ae004134349a16dcb66/lambdas/service/app.py#L294

Other controller attributes should be checked as well.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to describe solution.

**Comment by hannes-ucsc** [comment]
Spike to change `@property` to `@cached_property` and see what happens. This is mostly need to facilitate more control on caching during tests in #4956.

**Comment by hannes-ucsc** [comment]
Unit and integration tests pass with 

```diff
Subject: [PATCH] [u 2/2] Do not remove storage bucket from TF state (#4959)
---
Index: lambdas/service/app.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lambdas/service/app.py b/lambdas/service/app.py
--- a/lambdas/service/app.py	(revision f7eb1653ee492d41a1196dae74023a974e534820)
+++ b/lambdas/service/app.py	(date 1675883689320)
@@ -291,9 +291,7 @@
     def catalog_controller(self) -> CatalogController:
         return self._service_controller(CatalogController)
 
-    # FIXME: Service `app.repository_controller` should be cached
-    #        https://github.com/DataBiosphere/azul/issues/4957
-    @property
+    @cached_property
     def repository_controller(self) -> RepositoryController:
         return self._service_controller(RepositoryController)
 
```

so I'm just going to take this on and have the spike cover the estimate.
