### ISSUE TITLE
Storage bucket is still being removed from TF state

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4958]
PR https://github.com/DataBiosphere/azul/pull/4926 for #4646 removed the old storage bucket from the Terraform state using the `rename_resource` script. The line in that script to remove the bucket from the state was left in place, causing the new, renamed buckets to again be removed from the state. This causes deployment failures when Terraform tries to create the bucket when it already exists. Running `make deploy` fails with

```
╷
│ Error: creating Amazon S3 (Simple Storage) Bucket (edu-ucsc-gi-platform-hca-dev-storage-hannes.us-east-1): bucket already exists
│ 
│   with aws_s3_bucket.storage,
│   on s3.tf.json line 24, in resource[0].aws_s3_bucket[0].storage:
│   24:                     }
│ 
╵
```

Resolution to this ticket involves

- [ ] Removing the reference to the storage bucket from `rename_resources.py`
- [ ] Either importing the existing bucket back into the state, or deleting it so that Terraform can create a new bucket that will not be removed from the state

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by nadove-ucsc** [comment]
A deployment where the bucket has been removed from the state can be repaired by removing the offending line from `rename_resources.py` and running:

```
cd terraform
make plan
terraform import aws_s3_bucket.storage $AZUL_S3_BUCKET
make apply
```

**Comment by hannes-ucsc** [comment]
Demoed as part of #4646.
