### ISSUE TITLE
Onboard Ben Vizzier to Azul

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4962]
# Onboarding

This ticket should be created by the hiring supervisor to initiate the process
of onboarding an employee to team Boardwalk. The action items in this ticket
will be completed by the supervisor, other team members, and the onboarded
employee. The ticket should first be assigned to the hiring supervisor.

If you are assigned this ticket, perform the checklist items in order. Remove
your assignment only after assigning this ticket to the next in line or the
ticket checklist is completed. At that time, put the ticket back in triage.

## Hiring Supervisor 

- [x] Onboarded employee's name: [Ben Vizzier]
- [x] Approved the HR request for ITS to create a UCSC account for the onboarded employee
- [x] Instructed the onboarded employee to create a new GitHub account using the username `{ucsc_account_name}-ucsc` connected to their UCSC account email address. The new account will be used exclusively for work on the team and should be created even if they already have another account.
- [x] Assigned this ticket to the onboarded employee

## Onboarded employee actions

- [x] Onboarded employee's UCSC account email: [bvizzier@ucsc.edu]
- [x] Onboarded employee's GitHub account username: [bvizzier-ucsc]
- [x] Read [Azul README.md](..)
- [x] Read [Contributing Guidelines](../blob/develop/CONTRIBUTING.rst)
- [x] Read [AWS Credential Configuration](https://giwiki.gi.ucsc.edu/index.php/Overview_of_Getting_and_Using_an_AWS_IAM_Account)
- [x] Completed the NIH [Information Security and Management Refresher](https://irtsectraining.nih.gov/publicUser.aspx) training courses
- [x] Completed the NIH [Information Security Awareness for New Hires](https://irtsectraining.nih.gov/publicUser.aspx) training courses
- [x] Completed the NIH [Information Management for New Hires](https://irtsectraining.nih.gov/publicUser.aspx) training courses
- [x] Completed the [dbGaP Code of Conduct](https://www.surveymonkey.com/r/HKXNYD7) quiz
- [x] Completed the [NIH Security Best Practices for (CAD) Subject to NIH (GDS) Policy](https://www.surveymonkey.com/r/FG3C63T) quiz
- [x] Digitally signed the [NIH GDS Policy](https://giwiki.gi.ucsc.edu/images/1/1b/NIH_GDS_Policy.pdf) document and gave it to the hiring supervisor
- [x] Installed [git-secrets](..#211-git-secrets)
- [ ] ~Completed steps for [setting up a VPN client](..#911-setting-up-a-vpn-client) for `dev.gitlab` and `anvildev.gitlab`~ Employee is not a developer and opted out of VPN access
- [ ] ~Sent a request email to the organization administrator (cc: hiring supervisor & system administrator) asking them to:~ Employee is not a developer
    - Create an AWS IAM user account
    - Assign the `developer` role in the dev accounts (`platform-{hca,anvil}-dev`) to the AWS IAM user account
    - Assign the `developer` role to the onboarded employee's GitHub user account
    - Add the onboarded employee's UCSC account to the `firecloud-cgl` group in Terra
    - Send confirmation to all email recipients when the request has been completed
- [x] Assigned this ticket to the hiring supervisor

## Hiring supervisor actions

- [x] Approved (by replying to) the request email sent by the onboarded employee to the organization administrator
- [x] Received confirmation from the organization administrator that the request has been completed
- [x] Assigned this ticket to the onboarded employee

## Onboarded employee actions

- [ ] ~Sent a request email to the system administrator (cc: hiring supervisor) asking them to:~ Employee is not a developer and opted out of GitLab access
    - Create a GitLab user account on the dev instances of GitLab
    - Assign the `developer` role to the account
- [x] Assigned this ticket to the hiring supervisor

## Hiring supervisor actions

- [ ] ~Approved (by replying to) the request email sent by the onboarded employee to the system administrator~ Not applicable, see above.
- [x] Assigned this ticket to the system administrator

## System administrator actions

- [ ] ~Verified the authenticity of the approval~ Not applicable, see above.
- [ ] ~Verified the GitHub user account is associated with the onboarded employee's UCSC account email~ Not applicable, see above.
- [ ] ~Created a GitLab user account for the onboarded employee on the `dev` instance of GitLab~ Not applicable, see above.
- [ ] ~Created a GitLab user account for the onboarded employee on the `anvildev` instance of GitLab~ Not applicable, see above.
- [ ] ~Added the onboarded employee to exactly one of the groups on the `dev` instance of GitLab and set the `Max Role` to `Developer`~ Not applicable, see above.
- [ ] ~Added the onboarded employee to exactly one of the groups on the `anvildev` instance of GitLab and set the `Max Role` to `developer`~ Not applicable, see above.
- [ ] ~Associated the new GitLab user accounts with the onboarded employee's GitHub user account~ Not applicable, see above.
- [ ] ~Added the onboarded employee to the `Azul Developers` GitHub team~ Not applicable, see above.
- [ ] ~Added the onboarded employee's UCSC account to the `platform-hca-dev` Google project and assigned the `developer` role~ Not applicable, see above.
- [ ] ~Added the onboarded employee's UCSC account to the `platform-anvil-dev` Google project and assigned the `developer` role~ Not applicable, see above.
- [ ] ~Added the onboarded employee's Google Workspace account to the `platform-hca-dev` Google project and assigned `Project Editor` permissions~ Not applicable, see above.
- [ ] ~Added the onboarded employee's Google Workspace account to the `platform-anvil-dev` Google project and assigned `Project Editor` permissions~ Not applicable, see above.
- [ ] ~Assigned this ticket to the hiring supervisor~ Not applicable, see above.

## Hiring supervisor actions

- [x] Added the onboarded employee to the [UCSC-CGL Slack](https://ucsc-cgl.slack.com)
- [x] Assigned this ticket to the system administrator

## System administrator actions

- [ ] ~Gave the onboarded employee push access to the Azul Repository on [#team-boardwalk](https://ucsc-cgl.slack.com/archives/C705Y6G9Z)~ Employee is not a developer and opted out.
- [ ] ~Gave the onboarded developer access to development CI/CD systems on [#team-boardwalk](https://ucsc-cgl.slack.com/archives/C705Y6G9Z)~ Employee is not a developer and opted out.
- [ ] ~Gave the onboarded employee [GCP Credentials](https://console.cloud.google.com/)~ Employee is not a developer and opted out.
- [ ] ~Added the onboarded employee's Google Workspace account to the `azul-dev` group in Terra~ Employee is not a developer and opted out.
- [ ] ~Added the onboarded employee's Google Workspace account to the `azul-anvil-dev` group in Terra~ Employee is not a developer and opted out.
- [ ] ~Added the onboarded employee's Google Workspace account to the `azul-anvil-prod` group in Terra~ Employee is not a developer and opted out.
- [ ] ~Assigned this ticket to the hiring supervisor~ Employee is not a developer and opted out.

## Hiring supervisor actions (after probationary period)

- [ ] ~Sent a request email to the organization administrator (cc: onboarded employee, hiring supervisor & system administrator) asking them to:~ Employee is not a developer and opted out
    - Assign the `viewer` role in the prod accounts (`platform-{hca,anvil}-prod`) to the AWS IAM user account
    - Send confirmation to all email recipients when the request has been completed
- [ ] ~Sent a request email to the system administrator (cc: onboarded employee & hiring supervisor) asking them to:~ Employee is not a developer and opted out
    - Create a GitLab user account on the production instances of GitLab
    - Associate the GitLab user account with the employee's GitHub user account
    - Assign the `developer` role to the GitLab user account
    - Add the employee's UCSC account to the Google Cloud project in the prod deployment zone
    - Send confirmation to all email recipients when the request has been completed
- [ ] ~Received confirmation from the organization administrator that the request has been completed~ Not applicable, see above.
- [ ] ~Received confirmation from the system administrator that the request has been completed~ Not applicable, see above.
 
## Conclusion

- [ ] Closed & unassigned this ticket

**Comment by achave11-ucsc** [comment]
@danielsotirhos to update template as soon as #4205 lands.

**Comment by theathorn** [comment]
Ben will also need access to the azul-private repo.

**Comment by bvizzier-ucsc** [comment]
I have read the documents referenced.  Since I don't expect to do development, I have yet to actually work through the steps.

**Comment by bvizzier-ucsc** [comment]
The onboarding template should be updated before March 31, 2023, to point to me instead of Trevor.

**Comment by dsotirho-ucsc** [comment]
Update ticket description with the [onboarding template](https://github.com/DataBiosphere/azul/blob/e7f0cbaf410d618e7e9ea6f9fba7f47f6828b0bd/.github/ISSUE_TEMPLATE/onboarding.md) updated by [PR 4968](https://github.com/DataBiosphere/azul/pull/4968).

**Comment by hannes-ucsc** [comment]
@bvizzier-ucsc, what's the ETA for this?

**Comment by bvizzier-ucsc** [comment]
I reviewed the list and marked all of the tasks that I completed.  Since I'm not a developer and keeping with the principle of least privilege, I have not requested access to resources that I don't need.  If a need arises, we can revisit the specific privileges at that time.
