### ISSUE TITLE
Add custom buttons to Chatbot's Slack post

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4963]
- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike to research feasibility.

**Comment by achave11-ucsc** [comment]
A [troubleshooting guide for AWS Chatbot](https://docs.aws.amazon.com/chatbot/latest/adminguide/chatbot-troubleshooting.html) on how to solve issues with messages not being delivered to Slack, hints at raw messages from SNS and modified EventBridge event messages not being deliverable by Chatbot. Which was a suggested, potential workaround for customizing the message in AWS before being delivered to Slack.

Additionally, in another related [stackoverflow](https://stackoverflow.com/questions/72573004/is-there-a-way-to-customise-slack-message-by-aws-chatbot/72602737#72602737) question, someone confirm that "AWS Chatbot doesn't allow you to specify your own templates for the messages", and concluded by suggesting "If you want custom Slack messages, you'll need to write your own Slack integration without using AWS Chatbot.".

If a button must be included in the notification from `@aws` bot, it might be achievable through a [custom bot](https://www.youtube.com/watch?v=DyzNPAuGtcU), that has admin level permissions in Slack (required to edit the other bot messages in Slack) and attach the [buttons as actions in the JSON](https://api.slack.com/legacy/message-buttons) transmitted by `@aws`. Alternatively, Zapier might help with adding reactions to the message or by replying in specified threads but it hasn't been explored extensively.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Create a prototype solution that uses a Slack workflow triggered by a webhook and subscribes the webhook to the SNS topic. If needed include Zapier actions in the workflow so that messages can be filtered, transformed, etc."

**Comment by achave11** [comment]
* Adding a button (done/acknowledge) to the chatbot (`@aws`) post.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Extract some of the prototype into the solution for #5246. When that is done, we will resume work on this ticket."

**Comment by achave11-ucsc** [comment]
Assignee to determine next steps.

**Comment by hannes-ucsc** [comment]
Obsoleted by #5703.
