### ISSUE TITLE
Chatbot role policy is too restrictive and causes persistent alarms

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#4966]
… the azul-chatbot policy [is more restrictive](https://github.com/DataBiosphere/azul/blob/develop/terraform/shared/shared.tf.json.template.py#L497-#L508) than the recommended [CloudwatchReadOnlyAccess policy](https://docs.aws.amazon.com/chatbot/latest/adminguide/chatbot-iam-policies.html#CloudwatchReadOnlyAccess-policy-for-chatbot). Because of this limitation, Chatbot has been reporting and setting off the ` azul-api_unauthorized-dev` and  `azul-api_unauthorized-anvildev` alarms in Slack throughout the day.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Spike to post report of all trail events that 1) triggered the alarm and 2) can be attributed to the bot.

**Comment by achave11-ucsc** [comment]
The trail event that caused the `azul-api_unauthorized-dev` alarm…
```
- CW Query

fields @timestamp, userIdentity.principalId, errorCode, eventSource, eventName
| filter @message not like /hannes/
| filter @message not like /achave11/
| filter (
    errorCode like /UnauthorizedOperation/ 
    or errorCode like /AccessDenied/
)
| sort @timestamp desc
| limit 180

-

[
    {
        "@timestamp": "2023-02-07 04:46:30.045",
        "userIdentity.principalId": "AROARZFZ7W775TV2NGE7W:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeLogGroups"
    },
    {
        "@timestamp": "2023-02-07 04:46:30.045",
        "userIdentity.principalId": "AROARZFZ7W775TV2NGE7W:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeQueryDefinitions"
    },
    … + 176 occurrences …
    {
        "@timestamp": "2023-02-07 19:01:32.570",
        "userIdentity.principalId": "AROARZFZ7W775TV2NGE7W:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeLogGroups"
    },    
    {
        "@timestamp": "2023-02-07 19:01:32.572",
        "userIdentity.principalId": "AROARZFZ7W775TV2NGE7W:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeQueryDefinitions"
    },
]
```
… and started after [I invited](https://ucsc-gi.slack.com/archives/C04K81HUALD/p1675728511672719) the `@aws` bot to the `dev` monitoring Slack channel.

The trail events that caused the `azul-api_unauthorized-anvildev` alarms…
```
- CW Query
fields @timestamp, userIdentity.principalId, errorCode, eventSource, eventName
| filter @message not like /hannes/
| filter (
    errorCode like /UnauthorizedOperation/ 
    or errorCode like /AccessDenied/
)
| sort @timestamp desc
| limit 26

-

[
    {
        "@timestamp": "2023-02-08 02:13:17.055",
        "userIdentity.principalId": "AROAUHATKQ7OSS7DDKYKM:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeLogGroups"
    },
    {
        "@timestamp": "2023-02-08 02:13:17.055",
        "userIdentity.principalId": "AROAUHATKQ7OSS7DDKYKM:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeQueryDefinitions"
    },
    … + 22 occurrences …
    {
        "@timestamp": "2023-02-08 04:12:13.316",
        "userIdentity.principalId": "AROAUHATKQ7OSS7DDKYKM:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeQueryDefinitions"
    },
    {
        "@timestamp": "2023-02-08 04:12:57.625",
        "userIdentity.principalId": "AROAUHATKQ7OSS7DDKYKM:chatbot-session",
        "errorCode": "AccessDenied",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeLogGroups"
    }
]
```
… also started after `@aws` bot [was removed](https://ucsc-gi.slack.com/archives/C04K81HUALD/p1675804244300159) from the `dev` monitoring Slack channel, it's unclear if it's related since the Slack channels receiving notifications in both deployments is distinct.

**Comment by hannes-ucsc** [comment]
I asked for all events but the reports above omit many. The point of this is that we learn which actions we need to allow in the policy. I suggest using `filter` on the principal, and `stats` to group by event source and name.

**Comment by achave11-ucsc** [comment]
For `dev` account:
```
[
    {
        "userIdentity.principalId": "AROARZFZ7W775TV2NGE7W:chatbot-session",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeQueryDefinitions",
        "errorCode": "AccessDenied",
        "count()": "89"
    },
    {
        "userIdentity.principalId": "AROARZFZ7W775TV2NGE7W:chatbot-session",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeLogGroups",
        "errorCode": "AccessDenied",
        "count()": "89"
    }
]
```

Similarly for `anvildev` account:
```
[
    {
        "userIdentity.principalId": "AROAUHATKQ7OSS7DDKYKM:chatbot-session",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeLogGroups",
        "errorCode": "AccessDenied",
        "count()": "13"
    },
    {
        "userIdentity.principalId": "AROAUHATKQ7OSS7DDKYKM:chatbot-session",
        "eventSource": "logs.amazonaws.com",
        "eventName": "DescribeQueryDefinitions",
        "errorCode": "AccessDenied",
        "count()": "13"
    }
]
```

**Comment by achave11-ucsc** [comment]
The following patch…
```
diff --git a/terraform/shared/shared.tf.json.template.py b/terraform/shared/shared.tf.json.template.py
index 48090078..837ffc9f 100644
--- a/terraform/shared/shared.tf.json.template.py
+++ b/terraform/shared/shared.tf.json.template.py
@@ -504,6 +504,7 @@ emit_tf(block_public_s3_bucket_access({
                                         'cloudwatch:Describe*',
                                         'cloudwatch:Get*',
                                         'cloudwatch:List*',
+                                        'logs:Describe*',
                                         'sns:Get*',
                                         'sns:List*'
                                     ]
```
… would prevent the Chatbot integration from setting off the false alarms in Slack.

**Comment by achave11-ucsc** [comment]
Consider the following found on [Troubleshooting AWS Chatbot.](https://docs.aws.amazon.com/chatbot/latest/adminguide/chatbot-troubleshooting.html) 
> - The bot is not invited to the channel.
>Ensure that the AWS Chatbot app (`@aws`) is added to the Slack channel. If it hasn't, in Slack, add the AWS Chatbot app by choosing Add apps from the channel's Details screen.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "To strike a balance between least privileges and practicality we will include all recommended privileges that @achave11 links to in the AWS docs, but we'll exclude `autoscaling` since we're unlikely to ever use it."

**Comment by hannes-ucsc** [comment]
For demo, show absence of matching trail events in `dev` for a duration of one week after this lands there.
