### ISSUE TITLE
Update to Python 3.11.x

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4982]
3.10 and 3.11 have many desirable improvements. The additions of 

- https://docs.python.org/3/library/unittest.html#unittest.TestCase.enterContext
- https://docs.python.org/3/library/unittest.html#unittest.TestCase.enterClassContext

would be very useful for us. We have various places where we do `cls.x = mock.patch(…); x.start()` in `setUpClass` and `cls.x.stop(); cls.x = None` in `tearDownClass`. This can be greatly simplified by doing just `cls.enterContext(mock.patch(…))` without any explicit state, or having to remember to do the inverse in `tearDownClass`.

We should also replace `AlwaysTearDownTestCase` with use of 

- https://docs.python.org/3/library/unittest.html#unittest.TestCase.addCleanup
- https://docs.python.org/3/library/unittest.html#unittest.TestCase.addClassCleanup

because

> If [setUpClass()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass) fails, meaning that [tearDownClass()](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDownClass) is not called, then any cleanup functions added will still be called.

Currently we can't do this because AWS Lambda doesn't support 3.11, yet, or 3.10 for that matter:

- https://github.com/aws/aws-lambda-base-images/issues/31
- https://github.com/aws/aws-lambda-base-images/issues/62

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [ ] ~… introduce a new software dependency like~ https://github.com/DataBiosphere/azul/issues/4982#issuecomment-1780477264
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Assignee to periodically check on AWS blocker.

**Comment by hannes-ucsc** [comment]
Support for Python 3.10 is now available in AWS Lambda but 3.11 is not, and with no ETA.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "AWS Lambda released support for Python 3.11 runtimes. We'll use that runtime and docker image [3.11.5-bullseye](https://hub.docker.com/layers/library/python/3.11.5-bullseye/images/sha256-01d798ba865dcb6f157b9a5cc1be7127dde929c614ac33d099c05588cf2f3709?context=explore)"

**Comment by dsotirho-ucsc** [comment]
Chalice has an open ticket to support Python 3.11 https://www.github.com/aws/chalice/issues/2053

**Comment by hannes-ucsc** [comment]
Security review: This change updates Python to a version officially supported by AWS for Lambda. It upgrades the AWS Terraform provider.
