### ISSUE TITLE
Apply Amazon OpenSearch (ES) Software Update (before 2023-03-29)

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4983]
```
Date: February 14, 2023, 10:14 am
Domains: azul-index-dev, azul-index-sandbox
Severity: High
Message: Service software update R20221114 available. Update will be automatically installed after 2023-03-29T10:14:05Z if no action is taken.
```

```
Date: Feb 14, 2023, 02:15 am
Domains: azul-index-anvilbox, azul-index-anvildev
Severity: High
Message: Service software update R20221114 available. Update will be automatically installed after 2023-03-29T10:15:34Z if no action is taken.
```

```
Date: Feb 14, 2023, 02:15 am
Domains: azul-index-prod
Severity: High
Message: Service software update R20221114 available. Update will be automatically installed after 2023-03-29T10:15:40Z if no action is taken.
```

- [x] Update `azul-index-dev` with service software update `R20221114`
- [x] Confirm with Azul devs that their personal deployments sharing `azul-index-sandbox` are idle
- [x] Update `azul-index-sandbox` with service software update `R20221114`
- [x] Update `azul-index-anvildev` with service software update `R20221114`
- [x] Confirm with Azul devs that their personal deployments sharing `azul-index-anvilbox` are idle
- [x] Update `azul-index-anvilbox` with service software update `R20221114`
- [x] Update `azul-index-prod` with service software update `R20221114`

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
All ES domains have been upgraded to `R20221114`.

![Screen Shot 2023-02-23 at 8 17 55 PM](https://user-images.githubusercontent.com/46407464/221090766-b44b2ce8-a352-4cf5-a0b5-593574efa6a1.png)
![Screen Shot 2023-02-23 at 8 17 43 PM](https://user-images.githubusercontent.com/46407464/221090795-421f936a-c1d1-4b20-857f-e41bd9b9a508.png)
![Screen Shot 2023-02-23 at 8 18 27 PM](https://user-images.githubusercontent.com/46407464/221090777-f235ed30-8228-4f4d-9123-66c52f083e36.png)
![Screen Shot 2023-02-23 at 8 18 38 PM](https://user-images.githubusercontent.com/46407464/221090804-0f55f067-0db4-4e43-8638-9eaf8784d8d3.png)
![Screen Shot 2023-02-23 at 8 18 54 PM](https://user-images.githubusercontent.com/46407464/221090785-a02efe7f-9d26-467b-aaa3-ee520213433f.png)

**Comment by hannes-ucsc** [comment]
Looks good. Thank you!
