### ISSUE TITLE
Count # of entities in dcp23

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4992]
I need that to size the ES cluster for AnVIL. I'd like a count per entity type, including bundles and cell suspensions. Probably best to query ES directly, instead of our API, since we don't expose cell suspensions. For extra credit, counts per type *and* snapshot (or project) would be good.

**Comment by dsotirho-ucsc** [comment]
```
GET /_cat/indices/*dcp23*?v&s=index&h=index,docs.count,docs.deleted,store.size,pri.store.size

index                                            docs.count docs.deleted store.size pri.store.size
azul_v2_prod_dcp23_bundles_aggregate                 193577          305      4.1gb            1gb
azul_v2_prod_dcp23_cell_suspensions_aggregate        130762        56857      1.5gb        403.7mb
azul_v2_prod_dcp23_files_aggregate                   490015          403      4.6gb          1.1gb
azul_v2_prod_dcp23_projects_aggregate                  1196          564    115.5mb         28.8mb
azul_v2_prod_dcp23_samples_aggregate                  15615        14768      1.5gb        383.4mb
```

Aggregated totals: [dcp23 row counts grouped by project](https://docs.google.com/spreadsheets/d/1sQB0HVJiO72Z8Ub6OTmhAUdJhofs5zag_hL5rdjyLm0/edit?usp=sharing)

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Numbers from `_cat` don't add up, for example we don't have 1196 project entities, we have 313. Even subtracting the deleted docs doesn't get us to that number."

**Comment by dsotirho-ucsc** [comment]
`_cat/indices` was the wrong choice for a summary count of entities.

https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html
> These metrics are retrieved directly from Lucene, which Elasticsearch uses internally to power indexing and search. As a result, all document counts include hidden nested documents.

Using a cardinality aggregation I was able to get a count of the unique entity IDs in each index:
 
| Index | Unique entity_id count |
| -- | -- |
| azul_v2_prod_dcp23_bundles_aggregate | 194351 |
| azul_v2_prod_dcp23_cell_suspensions_aggregate | 131482 |
| azul_v2_prod_dcp23_files_aggregate | 484789 |
| azul_v2_prod_dcp23_projects_aggregate | 313 |
| azul_v2_prod_dcp23_samples_aggregate | 15647 |

Example ES Query:
```
GET /azul_v2_prod_dcp23_projects_aggregate/_search?size=0
{
  "query": {
    "match_all": {}
  },
  "aggregations": {
    "unique_entity_ids": {
      "cardinality": {
        "field": "entity_id.keyword"
      }
    }
  }
}
```

**Comment by hannes-ucsc** [comment]
Total of 826582 entities.

**Comment by hannes-ucsc** [comment]
Discussion continues here: https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1677537879738299?thread_ts=1676646220.783009&cid=C03TPJS54DC
