### ISSUE TITLE
Invalid JSON for search_after or …before should cause 4xx

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4996]
The 2/2/2023 Invicti scan repored both a `Stack Trace Disclosure (Python)` and `Internal Server Error` (HTTP status 500) finding as a result of requesting a URL with incomplete JSON specified as the `search_after` parameter.

Request:
```
GET /index/bundles?catalog=dcp2&filters=%7B%7D&order=desc&search_after=%2527&size=10&sort=bundleVersion HTTP/1.1
Host: service.dev.singlecell.gi.ucsc.edu
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Cache-Control: no-cache
Referer: https://service.dev.singlecell.gi.ucsc.edu/index/bundles
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.0 Safari/537.36
```

Response:
```
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
X-Amz-Cf-Id: yljUg4uYRSb6npAuq4HeXGYYmCDOI2gNSKkSzWv0yIbFUf3-HRmPFA==
Connection: keep-alive
X-Amzn-Trace-Id: Root=1-63dc8df6-04db7de25839062032153ee5;Sampled=0
x-amz-apigw-id: fvseiHaKIAMFg7g=
Content-Length: 798
X-Cache: Error from cloudfront
Access-Control-Allow-Origin: *
Content-Type: text/plain
X-Amz-Cf-Pop: SFO20-C1
Date: Fri, 03 Feb 2023 04:30:46 GMT
Via: 1.1 1b76276e9fd9c7bd637ed463cc0a5976.cloudfront.net (CloudFront)
x-amzn-RequestId: b15a73ac-60c0-4d34-a657-8d2dd7079d83

Traceback (most recent call last):
File "/var/task/chalice/app.py", line 1913, in _get_view_function_response
response = view_function(**function_args)
File "/var/task/app.py", line 1219, in repository_search
pagination=app.get_pagination(entity_type),
File "/var/task/app.py", line 351, in get_pagination
sa = tuple(json.loads(sa))
File "/var/lang/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/var/lang/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/var/lang/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
