### ISSUE TITLE
Create alarm for log forwarding failures

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#4997]
- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] ~… affect monitoring of the system~ https://github.com/DataBiosphere/azul/issues/4997#issuecomment-1635032541
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by nadove-ucsc** [comment]
- Regular python exceptions (`ERROR`)
- Task time out (`Task timed out`)
- Out of memory (`Error: Runtime exited with error: signal: killed Runtime.ExitError`)

**Comment by nadove-ucsc** [comment]
Should be covered by the built in "Lambda Errors" metric (this was confirmed via experiment)

**Comment by dsotirho-ucsc** [comment]
> Should be covered by the built in "Lambda Errors" metric (this was confirmed via experiment)

@hannes-ucsc: "Agreed. In that case this ticket is a duplicate of #5060. However the FIXME comment needs to be removed from the source by #5060."

**Comment by hannes-ucsc** [comment]
For demo, in a lower deployment, temporarily break the ALB access log forwarder. Show, that the corresponding CW log group stops receiving events. Show that the error threshold metric alarm goes off. Repair the breakage.

**Comment by hannes-ucsc** [comment]
Security review: See https://github.com/DataBiosphere/azul/issues/5060#issuecomment-1635031718

**Comment by hannes-ucsc** [comment]
Merge commit was reverted. Replacement PR will need to be filed.

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc this ticket is due 09/01/2023

**Comment by dsotirho-ucsc** [comment]
During demos it was discovered the new alarms are misconfigured and are not reading errors & throttles from the desired Lambda functions.
Putting ticket back in progress for a new PR to fix the broken alarms.
