### ISSUE TITLE
Failed notifications for `dcp24` due to empty donor age

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#4999]
Azul has a requirement that if a donor does not have an organism age, it must also not have an age unit.

transform.py (line 812):
```
        if donor.organism_age is None:
            require(donor.organism_age_unit is None)
```

A snapshot in the `dcp24` catalog fails this check, having one donor organism (0aecdb08-b489-4346-bf14-d3db0958b0ce) that has no age, but does have an age unit. Note: this is the only donor in this snapshot with this issue, all other donors have both an age and age unit.

```
SELECT donor_organism_id, JSON_EXTRACT(content, '$.organism_age') AS organism_age, JSON_EXTRACT(content, '$.organism_age_unit') AS organism_age_unit
FROM `datarepo-adc4e130.hca_prod_5f607e50ba224598b1e9f3d9d7a35dcc__20230201_dcp2_20230210_dcp24.donor_organism`
```

| donor_organism_id | organism_age | organism_age_unit |
| -- | -- | -- |
| … | … | … |
| 30c11f43-2823-4360-9474-fb88da28688d | "87" | {"text":"year","ontology":"UO:0000036","ontology_label":"year"} |
| 0aecdb08-b489-4346-bf14-d3db0958b0ce | null | {""text"":""year"",""ontology"":""UO:0000036"",""ontology_label"":""year""} |
| e5cdd8e4-b909-44e8-9219-0291d1b225bc | "42" | {"text":"year","ontology":"UO:0000036","ontology_label":"year"} |
| … | … | … |

The seven subgraphs that mention this donor organism are also the exact seven `bundle_uuid` in the failed notification messages.

```
SELECT links_id from `datarepo-adc4e130.hca_prod_5f607e50ba224598b1e9f3d9d7a35dcc__20230201_dcp2_20230210_dcp24.links`
WHERE content like '%0aecdb08-b489-4346-bf14-d3db0958b0ce%'
```

| links_id |
| -- |
| 3bbe4ccc-72a6-45cd-b1fa-2e585aa2785f |
| d5396b9d-49db-4691-8d89-7fe5d1cc9a5f |
| 9b9810ee-5a91-40ba-8311-8cdad7a39d97 |
| bc705f88-2f0f-41c6-ae00-590214f4e027 |
| 5dda3f3d-915a-4702-ba31-5ca787272cbf |
| fcc59670-9c8e-45c1-a726-165c77dab1e6 |
| 4bf62a86-14ce-4aef-aac7-2a4e16bf3ef7 |

```
(.venv) daniel@Crispin ~/repo/azul3 $ grep bundle_uuid azul-notifications_fail-prod.json | sort | uniq
                        "bundle_uuid": "3bbe4ccc-72a6-45cd-b1fa-2e585aa2785f",
                        "bundle_uuid": "4bf62a86-14ce-4aef-aac7-2a4e16bf3ef7",
                        "bundle_uuid": "5dda3f3d-915a-4702-ba31-5ca787272cbf",
                        "bundle_uuid": "9b9810ee-5a91-40ba-8311-8cdad7a39d97",
                        "bundle_uuid": "bc705f88-2f0f-41c6-ae00-590214f4e027",
                        "bundle_uuid": "d5396b9d-49db-4691-8d89-7fe5d1cc9a5f",
                        "bundle_uuid": "fcc59670-9c8e-45c1-a726-165c77dab1e6",
```

The failed notification messages were re-fed into the notifications_retry queue, however there same RequirementError was raised from this attempt.

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Assignee to respond in Slack posting about this snapshot, mention the affected project, number of donors, and short summary of the issue (can't have an age unit without an age).

**Comment by dsotirho-ucsc** [comment]
Waiting for a response to my [posted question](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1677024541961049?thread_ts=1676061428.478939&cid=C9XD6L0AD)

**Comment by hannes-ucsc** [comment]
For demo, show evidence that reindex in prod passed without errors. Show that affected project is missing from catalog.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "There won't be a reindex any time soon, and while the offending snapshot was manually removed, we can not easily demonstrate the first aspect of the demo instructions. However, we will reindex at some point in the future and if we made a mistake (removed the wrong snapshot) the issue would manifest itself again in the form of failed notifications."
