### ISSUE TITLE
Manually enable access logs on DB buckets

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5005]
See https://github.com/databiosphere/azul/issues/4717#issuecomment-1435475704 for list.

Create checklist here.

Logs should go into the existing Azul logs bucket under `/s3/access/.data-browser/{full-bucket-name}`

## platform-hca-dev

- [x] cc-dev.explore.singlecell.gi.ucsc.edu	
- [x] cc-dev.singlecell.gi.ucsc.edu	
- [x] data-browser.dev.lungmap.net	
- [x] dev.explore.lungmap.net	
- [x] dev.archive-preview.singlecell.gi.ucsc.edu	
- [x] dev.explore.singlecell.gi.ucsc.edu	
- [x] dev.singlecell.gi.ucsc.edu	
- [x] ~ux-dev.explore.singlecell.gi.ucsc.edu~ (bucket deleted)
- [x] ~ux-dev.singlecell.gi.ucsc.edu~ (bucket deleted)

## platform-anvil-dev

- [x] anvil.explorer.gi.ucsc.edu	
- [x] anvil.gi.ucsc.edu	

## platform-hca-prod

- [x] archive-preview.humancellatlas.org	
- [x] org-humancellatlas-data-browser-dcp2-prod	
- [x] org-humancellatlas-data-portal-dcp2-prod	
- [x] data-browser.explore.lungmap.net	
- [x] data-browser.lungmap.net	

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by danielsotirhos** [comment]
Enabling server logging on a bucket requires a target bucket & path.
The path we've used for our deployment buckets conforms to: `/s3/access/{DEPLOYMENT}/{SLUG}/` (e.g. `/s3/access/daniel2/storage/`)

@hannes-ucsc please provide the desired slugs for the following buckets.

| Account | Bucket | Slug |
| -- | -- | -- |
| platform-hca-dev | cc-dev.explore.singlecell.gi.ucsc.edu |  |
|  | cc-dev.singlecell.gi.ucsc.edu |  |
|  | data-browser.dev.lungmap.net |  |
|  | dev.explore.lungmap.net |  |
|  | dev.archive-preview.singlecell.gi.ucsc.edu |  |
|  | dev.explore.singlecell.gi.ucsc.edu |  |
|  | dev.singlecell.gi.ucsc.edu |  |
|  | ux-dev.explore.singlecell.gi.ucsc.edu |  |
|  | ux-dev.singlecell.gi.ucsc.edu |  |
| platform-anvil-dev | anvil.explorer.gi.ucsc.edu |  |
|  | anvil.gi.ucsc.edu |  |
| platform-hca-prod | archive-preview.humancellatlas.org |  |
|  | org-humancellatlas-data-browser-dcp2-prod |  |
|  | org-humancellatlas-data-portal-dcp2-prod |  |
|  | data-browser.explore.lungmap.net |  |
|  | data-browser.lungmap.net |  |
--


<br class="Apple-interchange-newline">

**Comment by dsotirho-ucsc** [comment]
Done, access logging enabled for buckets listed in the ticket description.

The remaining buckets without access logging enabled are:

## platform-hca-dev

- edu-ucsc-gi-platform-hca-dev-awsconfig.us-east-1
- edu-ucsc-gi-platform-hca-dev-cloudtrail
- edu-ucsc-gi-platform-hca-dev-logs.us-east-1
- edu-ucsc-gi-singlecell-azul-config-dev.us-east-1

## platform-anvil-dev

- edu-ucsc-gi-platform-anvil-dev-awsconfig.us-east-1
- edu-ucsc-gi-platform-anvil-dev-cloudtrail
- edu-ucsc-gi-platform-anvil-dev-logs.us-east-1
- edu-ucsc-gi-platform-anvil-dev.us-east-1

## platform-hca-prod

- edu-ucsc-gi-azul-dcp2-prod-config.us-east-1
- edu-ucsc-gi-platform-hca-prod-awsconfig.us-east-1
- edu-ucsc-gi-platform-hca-prod-cloudtrail
- edu-ucsc-gi-platform-hca-prod-logs.us-east-1

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "For demo, show findings in `dev`, `anvildev`, and `prod` for [S3.9](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/aws-foundational-security-best-practices-1.0.0/S3.9)"

[edit: See [updated](https://github.com/DataBiosphere/azul/issues/5005#issuecomment-1478413179) demo instructions below, @hannes-ucsc ]

**Comment by hannes-ucsc** [comment]
This wasn't done correctly. Slash missing in key between source bucket name and date:

<img width="985" alt="image" src="https://user-images.githubusercontent.com/5143256/225718296-e4f20a52-d17f-4739-b522-84b21042c43b.png">

**Comment by dsotirho-ucsc** [comment]
> This wasn't done correctly. Slash missing in key between source bucket name and date:

Fixed. Bucket logging paths were updated, and all the logs created with the incorrect path have been moved & renamed on `dev`, `anvildev`, and `prod`.

[logging-status-dev.txt](https://github.com/DataBiosphere/azul/files/11023528/logging-status-dev.txt)
[logging-status-anvildev.txt](https://github.com/DataBiosphere/azul/files/11023530/logging-status-anvildev.txt)
[logging-status-prod.txt](https://github.com/DataBiosphere/azul/files/11023531/logging-status-prod.txt)

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "For demo (2nd), show that none of the log buckets contain log objects with the wrong key, in all three AWS accounts. Repeat [previous](https://github.com/DataBiosphere/azul/issues/5005#issuecomment-1446994266) demo."
