### ISSUE TITLE
Prepare `platform-anvil-prod` for compliance assessment

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#5015]
- [ ] ~Revoke VPN certs for BI employees~ Moved to #5283 
- [ ] ~Delete all traces of managed access data in `platform-anvil-dev` (ES & S3, anything else?)~ Moved to #5283
- [ ] ~Allocate `dev.anvil.gi.ucsc.edu`~ Used prod.anvil.gi.ucsc.edu instead for anvilprod
- [ ] Switch `anvildev` and `anvilbox` to the snapshots listed in the *AnVIL Dev* tab of the 
[tracking sheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=1208943485) tab (see [Slack thread](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1677684233457079)) Moved to #5283 
- [x] Prepare upgrade instructions for personal deployments
- [x] Reconfigure and deploy DB & Portal

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to come up with strategy for third party assessment.

**Comment by hannes-ucsc** [comment]
> @hannes-ucsc to come up with strategy for third party assessment.

Created #5019. Assessors will use `platform-anvil-prod`. During the assessment we can deploy urgent hotfixes to `anvilprod` (created by #5019) and otherwise focus on general compliance and other non-AnVIL-related work, like verbatim metadata.

**Comment by hannes-ucsc** [comment]
For demo, show how browser and portal are deployed.
