### ISSUE TITLE
Index public & mock-MA snapshots in `anvilprod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5019]
The compliance assessors won't have authorization to access any managed-access (MA) data. Since they'll need temporary IAM credentials that would expose them to any MA data in a deployment zone, we cannot given them access to a deployment zone that contains MA data. @theathorn suggested that we use a dedicated deployment zone, like `platform-anvil-staging` but I'd rather avoid that additional work.

Instead, we will reinstate the `platform-anvil-prod` deployment zone, make `anvilprod` a replica of `anvildev` and point `anvil.gi.ucsc.edu` at it. I will need to reissue VPN certs so that we and the select CC and BI folks can continue to access that private `anvilprod` deployment. We'll revoke the `platform-anvil-dev` certificates for the CC & BI folks. Data Browser & Portal will need to be deployed in the `platform-anvil-prod`  zone, too, and point at `anvilprod`. Hopefully we can deploy them ourselves and won't need to give CC access, as will ultimately be required for compliance.

The rest of the work of prepping for the assessment is tracked in #5015.

Update: https://github.com/DataBiosphere/azul/issues/5019#issuecomment-1461131978

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "It's ok to prepare as much as possible but the actual deployment should wait until CC is back and able to do their part."

**Comment by hannes-ucsc** [comment]
Slight change in plans. We'll have the assessors use `anvilprod`. It creates a more confusing combination of configurations in that `anvilprod` indexes TDR dev and `anvildev` indexes TDR prod, but it has the advantage of not breaking `anvildev` or interfering with work happening there.

**Comment by hannes-ucsc** [comment]
I deployed `anvilprod.shared`, `anvilprod.gitlab` and `anvilprod`. Before I can proceed, I need approval to expose the mock managed access snapshots and the 1000G snapshot to the public, in an Azul service instance that is not behind a VPN. I asked on Slack but haven't received a response yet so I will create blocking ticket. If we don't get approval soon, we will get not be able to have the deployment ready for the assessment.

**Comment by hannes-ucsc** [comment]
The `platform-anvil-prod` account is also missing Data Portal and Data Browser instances. To deploy them I need minimal documentation and assistance from Clever Canary. I will follow-up with CC on Slack.

**Comment by hannes-ucsc** [comment]
For demo, show service response in `anvilprod`.
