### ISSUE TITLE
Temporarily destroy `nadove4` and `nadove5` for assessment

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5021]
… in preparation for the assessment in the `platform-anvil-dev` deployment zone.

**Comment by nadove-ucsc** [comment]
`nadove5` destruction ~~in progress~~ complete

**Comment by hannes-ucsc** [comment]
I changed my mind. We'll have the assessors use `anvilprod`. There is no need to destroy `nadove4` anymore and `nadove5` can be recreated at your discretion, @noah-aviel-dove.
