### ISSUE TITLE
Prod fails test_indexing IT for newly added lm3 project

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5023]
… the [failure was due to a stalled queue.](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/35598#L6425) This problem seems to only be affecting one bundle in that project.
```
Traceback (most recent call last):
  File "/var/task/azul/indexer/index_controller.py", line 175, in contribute
    contributions = self.transform(catalog, notification, delete)
  File "/var/task/azul/indexer/index_controller.py", line 209, in transform
    results = service.transform(catalog, bundle, partition, delete=delete)
  File "/var/task/azul/indexer/index_service.py", line 283, in transform
    contributions.extend(transformer.transform(partition))
  File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 1599, in transform
    yield self._transform()
  File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 1633, in _transform
    contributed_analyses = [
  File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 1634, in <listcomp>
    self._matrix(file)
  File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 1153, in _matrix
    strata_string = self._build_strata_string(file)
  File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 1194, in _build_strata_string
    assert self.dimension_value_re.fullmatch(value), value
AssertionError

```
<span>

@requestId | d04a33e5-4dcc-5f3f-b0cf-6f99771c0f2e
-- | --
@timestamp | 1677867185528
action | add
catalog | lm3-it
notification.match.bundle_uuid | 1d96f4d7-1013-3ef7-a491-aae9b145837f
notification.match.bundle_version | 2023-01-25T18:30:09.464965Z
notification.partition.prefix | 0
notification.partition.prefix_length | 1
notification.source.id | 6f6d46d1-5cc2-4137-b614-4de7e76e9f3b
notification.source.spec | tdr:datarepo-1634bdcc:snapshot/lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20230228_lm3:/0
notification.transaction_id | 1f76a89e-5bf7-45cc-9188-3aedbf158367

</span>

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
2 rows found in `specimen_from_organism` with empty string ("") `organ` value.

```
SELECT JSON_VALUE(content, '$.organ.ontology_label') AS ontology_label,
JSON_VALUE(content, '$.organ.text') AS text,
JSON_VALUE(content, '$.organ.ontology') AS ontology
FROM `datarepo-1634bdcc.lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20230228_lm3.specimen_from_organism`
```

![Screen Shot 2023-03-03 at 11 39 19 AM](https://user-images.githubusercontent.com/46407464/222811436-30d2f8a5-2cfe-40e9-9656-1d0d902a7c3e.png)

**Comment by achave11-ucsc** [comment]
Assignee to follow up with LungMAP on Slack.

**Comment by hannes-ucsc** [comment]
https://humancellatlas.slack.com/archives/C01DQFA5F5Y/p1677999432199879?thread_ts=1675442256.366649&cid=C01DQFA5F5Y

**Comment by hannes-ucsc** [comment]
I would like the operator to file PR against `develop` that removes the offending snapshot so that the next promo can be green.

**Comment by hannes-ucsc** [comment]
Passing IT will prove the fix.

**Comment by achave11-ucsc** [comment]
[IT succeeded in](https://gitlab.azul.data.humancellatlas.org/ucsc/azul/-/jobs/35951) GL `prod`.
