### ISSUE TITLE
Enabling access logging on any bucket trashes bucket policy on logs bucket

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5024]
- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to provide details.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Assignee to spike for reproduction by creating a new bucket and enabling logging on it. The key question is whether the policy change obliterates our own changes or if it is purely additive."

**Comment by dsotirho-ucsc** [comment]
`make plan` for `dev.shared` :

Before enabling access logging on test bucket:
```
No changes. Your infrastructure matches the configuration.
```

and after:
```
Terraform will perform the following actions:

  # aws_s3_bucket_policy.logs will be updated in-place
  ~ resource "aws_s3_bucket_policy" "logs" {
        id     = "edu-ucsc-gi-platform-hca-dev-logs.us-east-1"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                    {
                        Action    = "s3:PutObject"
                        Effect    = "Allow"
                        Principal = {
                            AWS = "arn:aws:iam::127311923021:root"
                        }
                        Resource  = "arn:aws:s3:::edu-ucsc-gi-platform-hca-dev-logs.us-east-1/alb/access/*/AWSLogs/122796619775/*"
                    },
                  ~ {
                      ~ Action    = "s3:PutObject" -> [
                          + "s3:PutObject",
                        ]
                        # (4 unchanged elements hidden)
                    },
                  - {
                      - Action    = "s3:PutObject"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "logging.s3.amazonaws.com"
                        }
                      - Resource  = "arn:aws:s3:::edu-ucsc-gi-platform-hca-dev-logs.us-east-1/*"
                      - Sid       = "S3PolicyStmt-DO-NOT-MODIFY-1679099805827"
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Spike results indicate that the console doesn't really trash the policy, but instead just adds a statement and makes an insignificant change to an existing statement. Based on that I don't think we need to do anything. #5015 will put the data browser buckets under TF control, meaning that we won't have to resort to manual changes to those buckets."
