### ISSUE TITLE
Approval to publicly expose AnVIL snapshots from TDR dev

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5039]
I deployed `anvilprod.shared`, `anvilprod.gitlab` and `anvilprod`. Before I can proceed, I need approval to expose the mock managed access snapshots and the 1000G snapshot to the public, in an Azul service instance that is not behind a VPN. I asked on Slack but haven't received a response yet so I will create blocking ticket. If we don't get approval soon, we will get not be able to have the deployment ready for the assessment.

_Originally posted by @hannes-ucsc in https://github.com/DataBiosphere/azul/issues/5019#issuecomment-1462523655_

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Approval was given: https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1678467725601819?thread_ts=1678459128.977859&cid=C03TPJS54DC"
