### ISSUE TITLE
Color code current/future state in monitoring diagram

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5054]
@hannes-ucsc Color code what is the current state versus future state in the [logging and monitoring diagram](https://lucid.app/lucidchart/5a362477-88dc-418d-9fd5-ce2f7612a0c7/edit?invitationId=inv_1f2553c1-cc7a-46f7-8c13-e3316939e1f7&page=3CPXQFUVPoyg#?folder_id=shared).

**Comment by dsotirho-ucsc** [comment]
For demo show how shapes can be marked as complete by setting a data field.
