### ISSUE TITLE
Apply Amazon OpenSearch (ES) Software Update (before 2023-04-04)

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5067]
```
Date: Mar 17, 2023, 05:20 am
Domains: azul-index-dev, azul-index-sandbox
Severity: High
Service software update R20221114-P2 available. Update will be automatically installed after 2023-04-04T05:20:25Z if no action is taken.
```

```
Mar 17, 2023, 05:21 am
Domains: azul-index-anvilbox, azul-index-anvildev
Severity: High
Service software update R20221114-P2 available. Update will be automatically installed after 2023-04-04T05:21:59Z if no action is taken.
```

```
Mar 17, 2023, 05:22 am
Domains: azul-index-prod
Severity: High
Service software update R20221114-P2 available. Update will be automatically installed after 2023-04-04T05:22:06Z if no action is taken.
```

- [x] Update `azul-index-dev` with service software update `R20221114-P2`
- [x] Confirm with Azul devs that their personal deployments sharing `azul-index-sandbox` are idle
- [x] Update `azul-index-sandbox` with service software update `R20221114-P2`
- [x] Update `azul-index-anvildev` with service software update `R20221114-P2`
- [x] Confirm with Azul devs that their personal deployments sharing `azul-index-anvilbox` are idle
- [x] Update `azul-index-anvilbox` with service software update `R20221114-P2`
- [x] Update `azul-index-prod` with service software update `R20221114-P2`
- [x] Update `azul-index-anvilprod` with service software update `R20221114-P2`

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
<img width="985" alt="Screen Shot 2023-03-29 at 5 56 56 PM" src="https://user-images.githubusercontent.com/5143256/228700647-e2275d31-7ba1-495a-9833-d1f783671072.png">
