### ISSUE TITLE
Device lock required for AC-2(5) and AC-12: 

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#5076]
Device lock required for AC-2(5) and AC-12: 

The UCSC Data Browser team should enable the screen saver on the ITS-managed laptop/personal device

- Required for all devices used to have access to Prod/managed access data 
- If you are using a personal Laptop please enable by convention.
- Everyone should share a screen shot showing this has been enabled
- Due date Monday 3/27

**Comment by nadove-ucsc** [comment]
![image](https://user-images.githubusercontent.com/48401926/227317643-c64797bd-c2aa-47e2-bdf4-1bb1c18197a6.png)

**Comment by dsotirho-ucsc** [comment]
<img width="702" alt="Screen Shot 2023-03-23 at 2 07 39 PM" src="https://user-images.githubusercontent.com/46407464/227362224-0c8498d4-5d28-46af-9746-29311d90b648.png">

<img width="702" alt="Screen Shot 2023-03-23 at 2 08 31 PM" src="https://user-images.githubusercontent.com/46407464/227362179-5e4fd001-0d00-4f05-81b1-a7b9ad0a9722.png">

<img width="702" alt="Screen Shot 2023-03-23 at 2 09 09 PM" src="https://user-images.githubusercontent.com/46407464/227362262-a5ed1a73-9348-45a1-af2f-54985f8e7b77.png">

**Comment by achave11-ucsc** [comment]
<img width="659" alt="Screen Shot 2023-03-24 at 10 21 44 PM" src="https://user-images.githubusercontent.com/19215510/227698103-474b82c9-16d9-45f6-b001-02240639b13b.png">

<img width="645" alt="Screen Shot 2023-03-24 at 10 23 19 PM" src="https://user-images.githubusercontent.com/19215510/227698106-6b0b7ec7-a017-4b7e-9ea0-e5a5488bbe68.png">

<img width="660" alt="Screen Shot 2023-03-24 at 10 23 53 PM" src="https://user-images.githubusercontent.com/19215510/227698113-c0bc6ee1-252d-42f1-a290-0e6667e96667.png">

**Comment by hannes-ucsc** [comment]
<img width="780" alt="Screen Shot 2023-03-24 at 10 53 36 PM" src="https://user-images.githubusercontent.com/5143256/227699370-d35e80cd-55b5-4741-b2b9-11b15d6a808a.png">

<img width="780" alt="Screen Shot 2023-03-24 at 10 54 26 PM" src="https://user-images.githubusercontent.com/5143256/227699419-5ece44c1-4de2-4e36-a8ce-1417e36d4c19.png">

<img width="780" alt="Screen Shot 2023-03-24 at 10 55 23 PM" src="https://user-images.githubusercontent.com/5143256/227699500-cfad4349-5cd8-4eee-b389-1f2731d9dcd1.png">

<img width="780" alt="Screen Shot 2023-03-24 at 10 55 42 PM" src="https://user-images.githubusercontent.com/5143256/227699514-3b852019-8a39-49df-af48-6d998eac669e.png">

**Comment by nolunwa-ucsc** [comment]
already in the ssp
