### ISSUE TITLE
Remove redundant fields from projects response

### ISSUE THREAD

**Issue by Ben-Wu** [DataBiosphere/azul#508]
We should remove the list of laboratories for each project from the response and let the client get those from the list of contributors so that there's a single source of truth.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-331)
┆Project Name: azul
┆Issue Number: AZUL-331

**Comment by Ben-Wu** [comment]
@NoopDog The array of laboratories is also returned in the files and specimens endpoints which don't have the list of contributors.  Can you check if you use that field at all anywhere?

**Comment by hannes-ucsc** [comment]
@theathorn reports @NoopDog saying that this wasn't needed anymore.
