### ISSUE TITLE
Offboard Trevor

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5088]
# Offboarding

By creating this ticket, you are requesting an employee to be offboarded from
team Boardwalk. The action items in this ticket will be completed by the
project manager, other team members, and the offboarded employee. The ticket
should first be assigned to the offboarded employee.

If you are assigned this ticket, perform the checklist items in order. Remove
your assignment only after assigning this ticket to the next in line or the
ticket checklist is completed. At that time, put the ticket back in triage.

## Offboarded employee actions

- [X] Offboarded employee's name: Trevor Heathorn
- [X] Offboarded employee's UCSC account: theathor@ucsc.edu
- [X] Offboarded employee's GitHub handle: theathorn
- [x] Offboarded employee's AWS IAM username: [N/A]
- [X] Employee is leaving UCSC? YES
- [x] Destroyed all personal deployments that had been created or attempted. This includes all cloud resources created for use during the offboarded employee's work on the system, **except** for log resources, specifically CloudWatch logs, CloudTrail audit logs and S3 access logs
- [x] Assigned ticket to the project manager

## Project manager actions

- [x] Nominated [N/A] as a replacement system administrator <sub>or the system administrator is not being replaced</sub>
- [ ] ~Assigned ticket to the offboarded employee~

## Offboarded employee actions

- [x] Handed over credentials of the GitHub machine account to the replacement system administrator <sub>or the system administrator is not being replaced</sub>
- [x] Assigned the replacement system administrator's account as a maintainer of the `Azul Triagers` team on GitHub <sub>or the system administrator is not being replaced</sub>
- [x] Assigned the replacement system administrator's account as a maintainer of the `Azul Developers` team on GitHub <sub>or the system administrator is not being replaced</sub>
- [x] Assigned the replacement system administrator's account as a maintainer of the `Azul Operators` team on GitHub <sub>or the system administrator is not being replaced</sub>
- [x] Handed over credentials of all GitLab root accounts to the replacement system administrator <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `platform-hca-dev` Google project <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `platform-hca-prod` Google project <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `platform-anvil-dev` Google project <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `platform-anvil-prod` Google project <sub>or the system administrator is not being replaced</sub>
- [x] Added `Project Owner` permissions to the replacement system administrator's Google workspace account <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `azul-dev` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `azul-prod` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `azul-anvil-dev` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's Google workspace account to the `azul-anvil-prod` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Set the `Can manage users (admin)` checkbox for the replacement system administrator in the `azul-dev` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Set the `Can manage users (admin)` checkbox for the replacement system administrator in the `azul-prod` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Set the `Can manage users (admin)` checkbox for the replacement system administrator in the `azul-anvil-dev` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Set the `Can manage users (admin)` checkbox for the replacement system administrator in the `azul-anvil-prod` group in Terra <sub>or the system administrator is not being replaced</sub>
- [x] Sent a request email to the organization administrator (cc: project manager & system administrator) asking them to:
    - Remove the offboarded employee's AWS IAM user account from the `platform-{hca,anvil}-{dev,prod}-{viewer,developer,administrator}` groups in the `gi-gateway` AWS account
    - If the system administrator is being replaced, add the replacement system administrator's AWS IAM user account to the `platform-hca-{dev,prod,anvildev,anvilprod}-administrator` IAM groups in the `gi-gateway` AWS account
    - Send confirmation to all email recipients when the request has been completed
- [x] Assigned this ticket to the project manager

## Project manager actions

- [x] Approved (by replying to) the request email sent by the offboarded employee to the organization administrator
- [x] Received confirmation from the organization administrator that the request has been completed
- [x] Assigned ticket to the system administrator

## Organization administrator actions

- [x] Added the replacement system administrator's AWS IAM user account to the `platform-hca-dev-administrator` IAM group in the `gi-gateway` AWS account <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's AWS IAM user account to the `platform-hca-prod-administrator` IAM group in the `gi-gateway` AWS account <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's AWS IAM user account to the `platform-hca-anvildev-administrator` IAM group in the `gi-gateway` AWS account <sub>or the system administrator is not being replaced</sub>
- [x] Added the replacement system administrator's AWS IAM user account to the `platform-hca-anvilprod-administrator` IAM group in the `gi-gateway` AWS account <sub>or the system administrator is not being replaced</sub>
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-hca-dev-viewer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-hca-dev-developer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-hca-dev-administrator` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-hca-prod-viewer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-hca-prod-developer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-hca-prod-administrator` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-anvil-dev-viewer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-anvil-dev-developer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-anvil-dev-administrator` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-anvil-prod-viewer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-anvil-prod-developer` group in the `gi-gateway` AWS account
- [x] Removed the offboarded employee/contractor's AWS IAM user account from the `platform-anvil-prod-administrator` group in the `gi-gateway` AWS account
- [x] Assigned ticket to the system administrator

## System administrator actions

- [x] Reset the GitHub machine account credentials <sub>or the system administrator is not being replaced</sub>
- [x] Removed the offboarded employee from the `HumanCellAtlas` GitHub organization <sub>or the offboarded employee is not leaving UCSC</sub>
- [x] Removed the offboarded employee from the `DataBiosphere` GitHub organization <sub>or the offboarded employee is not leaving UCSC</sub>
- [x] Removed the offboarded employee from the `ucsc-cgp` GitHub organization <sub>or the offboarded employee is not leaving UCSC</sub>
- [x] Removed the offboarded employee from the `Azul Admins` GitHub team
- [x] Removed the offboarded employee from the `Azul Developers` GitHub team
- [x] Removed the offboarded employee from the `Azul Operators` GitHub team
- [x] Removed the offboarded employee from the `Azul Triagers` GitHub team
- [x] Created a new `dev` GitLab EC2 instance using a private key from the replacement system administrator <sub>or the system administrator is not being replaced</sub>
- [x] Created a new `prod` GitLab EC2 instance using a private key from the replacement system administrator <sub>or the system administrator is not being replaced</sub>
- [x] Created a new `anvildev` GitLab EC2 instance using a private key from the replacement system administrator <sub>or the system administrator is not being replaced</sub>
- [x] Created a new `anvilprod` GitLab EC2 instance using a private key from the replacement system administrator <sub>or the system administrator is not being replaced</sub>
- [x] Assigned themselves the `GitLab own` role on the `dev` instance of GitLab <sub>or the system administrator is not being replaced</sub>
- [x] Assigned themselves the `GitLab own` role on the `prod` instance of GitLab <sub>or the system administrator is not being replaced</sub>
- [x] Assigned themselves the `GitLab own` role on the `anvildev` instance of GitLab <sub>or the system administrator is not being replaced</sub>
- [x] Assigned themselves the `GitLab own` role on the `anvilprod` instance of GitLab <sub>or the system administrator is not being replaced</sub>
- [x] Removed the offboarded employee from the list of members on the Group members page in the `dev` instance of GitLab
- [x] Removed the offboarded employee from the list of members on the Group members page in the `prod` instance of GitLab
- [x] Removed the offboarded employee from the list of members on the Group members page in the `anvildev` instance of GitLab
- [x] Removed the offboarded employee from the list of members on the Group members page in the `anvilprod` instance of GitLab
- [x] Set the offboarded employee's account status to `Blocked` on the Users page in the Admin Area of the `dev` instance of GitLab
- [x] Set the offboarded employee's account status to `Blocked` on the Users page in the Admin Area of the `prod` instance of GitLab
- [x] Set the offboarded employee's account status to `Blocked` on the Users page in the Admin Area of the `anvildev` instance of GitLab
- [x] Set the offboarded employee's account status to `Blocked` on the Users page in the Admin Area of the `anvilprod` instance of GitLab
- [x] Removed all role assignments from the offboarded employee in the `dev` instance of GitLab
- [x] Removed all role assignments from the offboarded employee in the `prod` instance of GitLab
- [x] Removed all role assignments from the offboarded employee in the `anvildev` instance of GitLab
- [x] Removed all role assignments from the offboarded employee in the `anvilprod` instance of GitLab
- [x] Removed the offboarded employee from the `Azul bot account for Gitlab (UCSC Genomics Institute)` group in the `ucsc.edu` Google organization
- [x] Removed the offboarded employee's Google Workspace account from the `platform-hca-dev` Google project
- [x] Removed the offboarded employee's Google Workspace account from the `platform-hca-prod` Google project
- [x] Removed the offboarded employee's Google Workspace account from the `platform-anvil-dev` Google project
- [x] Removed the offboarded employee's Google Workspace account from the `platform-anvil-prod` Google project
- [x] Removed the offboarded employee's Google service account from the `platform-hca-dev` Google project
- [x] Removed the offboarded employee's Google service account from the `platform-hca-prod` Google project
- [x] Removed the offboarded employee's Google service account from the `platform-anvil-dev` Google project
- [x] Removed the offboarded employee's Google service account from the `platform-anvil-prod` Google project
- [x] Removed the offboarded employee from the `azul-dev` group in Terra
- [x] Removed the offboarded employee from the `azul-prod` group in Terra
- [x] Removed the offboarded employee from the `azul-anvil-dev` group in Terra
- [x] Removed the offboarded employee from the `azul-anvil-prod` group in Terra
- [x] Revoked the offboarded employee's VPN certificate for `dev` and submitted the updated certificate revocation list to AWS Client VPN
- [x] Revoked the offboarded employee's VPN certificate for `prod` and submitted the updated certificate revocation list to AWS Client VPN
- [x] Revoked the offboarded employee's VPN certificate for `anvildev` and submitted the updated certificate revocation list to AWS Client VPN
- [x] Revoked the offboarded employee's VPN certificate for `anvilprod` and submitted the updated certificate revocation list to AWS Client VPN
- [x] Assigned ticket to the project manager

## Project manager

- [x] If the offboarded employee is leaving UCSC, sent a request email to ITS (cc: system administrator) asking them to:
    - Disable the offboarded employee's UCSC account
    - Rotate and redistribute all shared credentials to all remaining eligible employees
- [x] Received confirmation from ITS that the request has been completed <sub>or the offboarded employee is not leaving UCSC</sub>
- [x] Assigned ticket to the system administrator

## System administrator actions
 
- [x] Performed an account review and disabled any accounts owned by the offboarded employee 
- [ ] ~Performed a [resource inventory](https://github.com/DataBiosphere/azul/issues/3634) and deleted any resources owned by the offboarded employee~ As a PM, Trevor did not own any cloud resources

## Conclusion

- [x] Closed & unassigned ticket

**Comment by achave11-ucsc** [comment]
@bvizzier to complete filling in the place holders in the description.

**Comment by nolunwa-ucsc** [comment]
@bvizzier @hannes-ucsc 

 for Trevor's offboarding, we are required to disable IAM credentials to AWS console, GitHub, and Prod Instance within 24 hrs from his official last day

**Comment by bvizzier-ucsc** [comment]
![Screenshot of ITS conformation.](https://github.com/DataBiosphere/azul/assets/15311001/89d0b619-3b81-4f63-8737-99fa2eb8a4d8)
