### ISSUE TITLE
FedRAMP inventory should be kept for one year

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5093]
![image](https://user-images.githubusercontent.com/48401926/228376070-b7db9613-dcd2-447e-a5a6-d70530aa4b8f.png)

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike to find relevant documentation about artifact retention in GitLab.

**Comment by achave11-ucsc** [comment]
[Here's a link](https://docs.gitlab.com/15.9/ee/user/admin_area/settings/continuous_integration.html#default-artifacts-expiration) to the relevant information on default artifact expiration/retention.

Additionally, the following changes can be made to .gitlab-ci.yml to configure the default artifact [retention](https://docs.gitlab.com/ee/ci/yaml/index.html#artifactsexpire_in).
```
Index: .gitlab-ci.yml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml	(revision 64b678e5597f86dec5229f2950c6e6d8338d967b)
+++ b/.gitlab-ci.yml	(date 1680123363727)
@@ -144,3 +144,5 @@
   artifacts:
     paths:
       - fedramp_inventory.xlsx
+    expire_in:
+      never

```

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
