### ISSUE TITLE
Confirm team members have Virtru encryption configured

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5094]
Instructions can be found as a [link in this document](https://docs.google.com/document/d/1cpRbu__nrYmB-DjGeaITKXCx9d4zpBzOZSKgPn5QvAo/edit#heading=h.x646n270hixz). 

Please note there are three potential ways to use Virtru:
* Virtru for Gmail <- Encrypted email.
* Virtru for Drive
* Virtru Secure File Share

**Comment by hannes-ucsc** [comment]
There are no instruction on how to install Virtru that document. There is only a link on how to read an encrypted email without having any software from Virtru installed.

There is no support for Firefox or Firefox-based browsers. The only way to send encrypted emails is to use a Chrome-based browser and install the Virtu Chrome extension in that browser. If you don't use Chrome for privacy concerns, you can install Chromium or Brave and either switch to that browser permanently or only use it when you need to send an encrypted email.

Details on the extension are here https://support.virtru.com/hc/en-us/articles/115012442108

EDIT: From our ITS on how to use Virtru https://its.ucsc.edu/virtru/encrypted-email.html

**Comment by hannes-ucsc** [comment]
I've installed the extension and sent this encrypted email to the group:

<img width="1390" alt="Screen Shot 2023-03-28 at 11 03 49 PM" src="https://user-images.githubusercontent.com/5143256/228440871-f1d28dad-9438-42d6-b69e-c12f019542c8.png">

**Comment by danielsotirhos** [comment]
I have installed the Virtru extension in Chrome and sent this encrypted email to the group.

![Screen Shot 2023-03-29 at 9 22 53 AM](https://user-images.githubusercontent.com/46407464/228604868-6118ac88-ca55-493b-b01a-90b99aa1117a.png)

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Based on Abraham's edit above, it is sufficient to use the subject line method to encrypt emails. No special plugin is needed. Assignees to post screenshots of encrypted message send to the group"

**Comment by achave11-ucsc** [comment]
I've uses the #secure# keyword in the subject of the email to encrypt it.
![Screen Shot 2023-03-29 at 11 57 49 AM](https://user-images.githubusercontent.com/19215510/228645355-1e5d8d41-7646-499a-a410-63853e6fcc87.png)

**Comment by dsotirho-ucsc** [comment]
Encyrpted and sent using the Virtru Chrome extension.

![Screen Shot 2023-03-29 at 11 59 24 AM](https://user-images.githubusercontent.com/46407464/228653995-ae2f1bc9-136a-4aee-9de8-c1a6696d9644.png)

**Comment by nadove-ucsc** [comment]
Sent using the `#secure#` keyword.

![image](https://user-images.githubusercontent.com/48401926/232920555-02bc6b08-a466-43d6-a80b-f721335d7b11.png)

**Comment by hannes-ucsc** [comment]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5143256/232924113-36c9dec0-1584-432d-9729-5b84156fe83b.png">
