### ISSUE TITLE
AnVIL: Change browser UI to not display curl download button

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/azul#5106]
https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1680296678149869

For AnVIL, the browser UI should be changed to not display the curl download button, at least until downloading from the UI is properly addressed in the future. The button is not currently operational.

Currently, the curl button is visible in both the AnVIL "dev" and "production" deployments.

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/84099036/229232247-94140048-1768-487c-b06c-b77ac903f75f.png">

**Comment by achave11-ucsc** [comment]
Assignee to diagnose the fact that button intermittently appears/disappears.

**Comment by NoopDog** [comment]
I was not able to reproduce the intermittent behavior. However, I did see that the site was configured to show the "curl" option, and I have made a change to remove the curl option for this site in this [PR](https://github.com/DataBiosphere/data-browser/pull/3191). 

I have also created a [ticket](https://github.com/clevercanary/data-browser/issues/816) to review and add cache control headers to the responses from Cloud Front, depending on the file type. 

@mbaumann-broad, once this is deployed, can you verify that the curl command is no longer showing? Thanks! D

**Comment by dsotirho-ucsc** [comment]
@NoopDog The ticket link in your last comment yields a 404. Can you provide a working link for this?

**Comment by NoopDog** [comment]
Hi, @danielsotirhos Apologies, I put in the wrong link. It's updated now. Cheers, D

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "The fix was pushed to `anvilprod` and `anvildev`."
