### ISSUE TITLE
Failing PFB handover from `anvilprod`

### ISSUE THREAD

**Issue by mbaumann-broad** [DataBiosphere/azul#5107]
AnVIL Data Explorer export to Terra from the Azul "dev" deployment (https://anvil.gi.ucsc.edu/explore/datasets) works successfully.
However, AnVIL Data Explorer export to Terra from the Azul "production" deployment https://prod.anvil.gi.ucsc.edu/explore/datasets) fails to import to Terra.
There is a substantial difference between the two in the form of the URL passed, which may be relevant.

See the Slack thread here for details: https://broadinstitute.slack.com/archives/C03TPJS54DC/p1680296217670029
I am not posting the details here, as they include many internal details.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
The Azul behaviour is by design, as motivated here:

https://github.com/DataBiosphere/azul/blob/6b920e99c78cc09f670ba0b2bf8d0d475eabfc34/src/azul/service/manifest_controller.py#L180

So what you observe in `anvilprod` is the normal behavior. It can also be observed in HCA deployments, namely `dev` and `prod`. What you observe in `anvildev` is the exception. To address this, the Terra team needs to allow the manifest URL that the Data Browser submits to Terra for import.

**Comment by hannes-ucsc** [comment]
Assignee to follow-up with Broad so that `anvilprod` is allowed as a source for Terra imports.

**Comment by hannes-ucsc** [comment]
This is fixed. 

https://humancellatlas.slack.com/archives/C018YPVKC73/p1680542629275629
