### ISSUE TITLE
Various FedRAMP inventory issues

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5108]
- [x] EC2 instance is not represented correctly. It only has one row under a generic type `'AWS::Config::ResourceCompliance'`, and lacks specifics.
- [ ] ~Route 53 hosted zones are not represented (not sure why, considering https://aws.amazon.com/about-aws/whats-new/2022/08/aws-config-supports-20-new-resource-types/)~ [moved to new issue](https://github.com/DataBiosphere/azul/issues/5108#issuecomment-1495402918)
- [x] Some values are unnecessarily surrounded by single quotes
- [x]  All rows except for synthesized ones (see below) should specify "AWS" for software vendor
- [x] Application endpoints (like `service.anvil.gi.ucsc.edu) aren't represented (see below)
- [x] GitLab endpoints aren't represented (see below)
- [x] There are some uninformative`'AWS::Config::ResourceCompliance'` records that seem to duplicate existing records. These should not be listed in the inventory.
- [x] Add mapper for AWS::ACM::Certificate to generate the endpoint for the Client VPN (one of the ACM certs refers to the client VPN, example below)
- [x] ~~Add mapper for NetworkInterface~~ Fix NetworkInterfaceMapper to include public IP addresses

Regarding endpoints: Since many resources are involved in providing any given endpoint, we should include synthesized inventory rows for the service and indexer of the main deployment, and for ports 22, 22222 and 443 of the GitLab instance. These synthesized rows should just be derived from the current Azul configuration (`azul.config`), regardless of whether the underlying resources that provide that endpoint are actually present.

Specifically,

- https://prod.anvil.gi.ucsc.edu/
- https://service.prod.anvil.gi.ucsc.edu/
- https://indexer.prod.anvil.gi.ucsc.edu/
- cvpn-endpoint-024ba9048fd69288f.prod.clientvpn.us-east-1.amazonaws.com:443
- https://gitlab.prod.anvil.gi.ucsc.edu/
- ssh://ssh.gitlab.prod.anvil.gi.ucsc.edu:2222/
- git+ssh://ssh.gitlab.prod.anvil.gi.ucsc.edu:22/

Example ACM resource JSON (abbreviated). Note the inUseBy entry referring to the cvpn endpoint from which the string in the fourth bullet can be generated.

```json
{
    "resourceType": "AWS::ACM::Certificate",
    "resourceId": "arn:aws:acm:us-east-1:289950828509:certificate/c6905429-c743-4169-8b28-e7fd9b13e6e6",
    "awsRegion": "us-east-1",
    "configuration": {
        "inUseBy": [
            "aws:clientvpn:us-east-1:prod/cvpn-endpoint-04c5afd23df5863d9"
        ]
    }
}
```

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Sadly, according to AWS support, the set of resource types supported for queries is a subset of the types supported in general. It looks like that if we want to generically support any resource types, we can't rely on queries, but need to switch to the [ListDiscoverdResources](https://docs.aws.amazon.com/config/latest/APIReference/API_ListDiscoveredResources.html) API and follow that up with calls to [BatchGetResourceConfig](https://docs.aws.amazon.com/config/latest/APIReference/API_BatchGetResourceConfig.html) to get the individual resources. The mappers must then parse those results instead of the query response. I've opened #5110 to cover that.

**Comment by nadove-ucsc** [comment]
@hannes-ucsc Questions for WIP review:
 - How should the rows in the synthetic inventory be ordered, both relative to each other and relative to the rest of the inventory? Currently, the row derived from the VPN certificate is ordered based on the  positioning of the `ACMCertificateMapper`, and the other synthetic rows are at the bottom.
 - Currently, URLs for GitLab and Data Browser are hard-coded for `anvil-prod`. Should we fix this to use the correct URL for other deployments? If so, how can these URLs be derived for the current deployment? Note that the Azul endpoints use the current deployment.

All the changes pertinent to these questions are in the most recent commit.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.

**Comment by nolunwa-ucsc** [comment]
ssp updated
