### ISSUE TITLE
Switch to ListDiscoveredResources for inventory

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5110]
> Sadly, according to AWS support, the set of resource types supported for queries is a subset of the types supported in general. It looks like that if we want to generically support any resource types, we can't rely on queries, but need to switch to the [ListDiscoverdResources](https://docs.aws.amazon.com/config/latest/APIReference/API_ListDiscoveredResources.html) API and follow that up with calls to [BatchGetResourceConfig](https://docs.aws.amazon.com/config/latest/APIReference/API_BatchGetResourceConfig.html) to get the individual resources. The mappers must then parse those results instead of the query response.

_Originally posted by @hannes-ucsc in https://github.com/DataBiosphere/azul/issues/5108#issuecomment-1495402918_

~~Then add support for Rout53 hosted zones.~~

@nadove-ucsc: "@hannes-ucsc and I agreed to postpone the addition of Route53-specific mappers to [a follow-up ticket](https://github.com/DataBiosphere/azul/issues/5148)."

**Comment by hannes-ucsc** [comment]
For demo, show most recent inventory for `anvildev` and highlight the new Route53 entries.

**Comment by achave11-ucsc** [comment]
Changes lack the pertinent enhancements to the GL role policy.
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/66657
https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/14566

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Noa to update the GL IAM policy with the required permissions in `anvildev`. If that requires elevated permissions, Noa should request them from Erich CCing Hannes and Ben."

**Comment by nadove-ucsc** [comment]
Tested on `anvildev.gitlab` and determined the necessary permissions.

https://gitlab.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/14600
