### ISSUE TITLE
Obtain and ship loaner laptop for FedRAMP Assessment

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5117]
Obtain a loaner laptop configured with a standard IT image for the FedRAMP assessor to use for testing.

Once the laptop is obtained, hand it off to Daniel for configuration as a development laptop (see blocker).

When the blocker is resolved, have the laptop sent to the assessor.

**Comment by bvizzier-ucsc** [comment]
Kelly told me to work with Jesus (jortizri@ucsc.edu) to identify the laptop.

**Comment by bvizzier-ucsc** [comment]
The laptop is ready and Daniel is scheduled to pick it up from Jesus on Monday, April 10, 2023.

**Comment by dsotirho-ucsc** [comment]
I will pickup the loaner laptop from WRP on Monday and do the work for #5118. When I'm done work on this ticket can resume.

**Comment by dsotirho-ucsc** [comment]
The laptop has been [set up](https://github.com/DataBiosphere/azul/issues/5118#issuecomment-1506244742). I will reach out to @bvizzier-ucsc tomorrow to coordinate a drop-off of the laptop for shipping.

**Comment by bvizzier-ucsc** [comment]
Per Benedict's instructions, Kim Czupil will work with Daniel & Nneka to ship the laptop.

@dsotirho-ucsc, Please work with Kim to schedule a handoff date and time.

Nneka will need to provide the address.

**Comment by dsotirho-ucsc** [comment]
Laptop has been given to Kimberley Czupil for shipping to Fortreum.

**Comment by bvizzier-ucsc** [comment]
The laptop has been shipped.  FedEx Tracking Number [635963864920](https://www.fedex.com/fedextrack/?trknbr=635963864920&trkqual=2460049000~635963864920~FX).

The return tracking number is [635963864930](https://www.fedex.com/fedextrack/?trknbr=635963864930&trkqual=2460049000~635963864930~FX).

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Tracking numbers have been created for both shipping and return. Leave ticket in progress and assigned until laptop is back in our custody."

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Laptop has arrived back at WRP. Daniel to retrieve it and remove the user account containing the VPN credentials, and return laptop to Kimberley C."

**Comment by achave11-ucsc** [comment]
https://support.apple.com/guide/mac-help/erase-and-reinstall-macos-mh27903/mac

**Comment by dsotirho-ucsc** [comment]
Laptop was wiped and returned to Jesus Ortiz-Rivas at WRP.
