### ISSUE TITLE
Configure development environment on loaner laptop for FedRAMP Assessment

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5118]
Configure the loaner laptop as a developer system per @hannes-ucsc specifications. 

Once done, resolve this ticked and let @bvizzier know so it can be shipped.

**Comment by dsotirho-ucsc** [comment]
done.


## Installed 

- Homebrew
- Git
- Git repo (Azul clone at ~/repo/azul)
- Pyenv
- Python 3.9.12
- Tfenv
- Terraform 1.3.4
- Pycharm Community Edition
- Docker
- git-secrets
- Vicosity VPN client
- aws CLI
- google-cloud-sdk

## Configured

- FileVault: Encrypted HD
- Find My Mac: Enabled
- Power: Turn off display after 15min
- Screen saver: Start after 5min
- Security: Require password 5 seconds after sleep/screen saver
- Pycharm: Project for ~/repo/azul
- VPN Connection: azul-gitlab-dev-dsotirho@ucsc.edu
