### ISSUE TITLE
Update Commons index mappings for: project, study, program

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#513]
Update Commons Azul index mappings for the ETL output format as of 10/16/18 for: `project`, `study`, `program`

The mappings are as follows:

Metadata Field | Azul Index Field
---------------|-----------------
project.code | project
study.submitter_id | study
study.submitter_id | program*

* Note: The mapping to program must be updated when the `program` object becomes available in the ETL output. The current, specific mapping to `program` is an interim solution until the `program` JSON object is available.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-333)
┆Project Name: azul
┆Issue Number: AZUL-333

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
