### ISSUE TITLE
Change GitHub user name to match compliance requirements

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5131]
FedRAMP requires that identifiers aren't reused for different people. ITS ensures that for @ucsc.edu accounts for a period of three years. To address the requirement for AWS IAM accounts, we established the convention to the name IAM account of a user the same as their `@ucsc.edu` account. Similarly, we need to have a fixed mapping between the `@ucsc.edu` account and a user's GitHub user name. The GitHub user name must be `{localpart}-ucsc` where `localpart` is the part before `@ucsc.edu` in a team member's UCSC account.

Please [rename](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/changing-your-github-username) your GitHub account or create a new account under the required name. Renaming an account is less invasive. For example, your GitLab accounts will remain active since the numeric account ID doesn't change. If you rename the existing account, please create a new account under the old name so that no one can claim it and intercept @-mentions of the old name. The new account will not be used for work, it's just there to prevent name squatting.

Please discuss with me if you strongly prefer to create a new account under the new name.

When done, notify the system administrator on Slack. We have never attempted this before so we may encounter issues with this.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
This change does affect authentication for GitHub and therefore GitHub. Renamed accounts should continue to work in GitLab because GitLab maps GitLab accounts to GitHub accounts using the numeric ID of the GitHub account, not the symbolic name. This does not affect OAuth with Google, or AWS. You may have to sign-in again to GitLab after renaming the account.

**Comment by dsotirho-ucsc** [comment]
Done. Old: `danielsotirhos`, new: `dsotirho-ucsc`

**Comment by nadove-ucsc** [comment]
https://github.com/nadove-ucsc
https://github.com/noah-aviel-dove

**Comment by nadove-ucsc** [comment]
Note that that if you have bookmarks referencing the old username, e.g. `?assignee=...` for ZenHub, you'll need to update them.

**Comment by bvizzier-ucsc** [comment]
Done: bvizzier-ucsc

**Comment by achave11-ucsc** [comment]
Done: [achave11-ucsc](https://github.com/achave11-ucsc)

**Comment by nolunwa** [comment]
done: nolunwa-ucsc

**Comment by nolunwa-ucsc** [comment]
Done: nolunwa-ucsc

Did this with Hannes 04/19
