### ISSUE TITLE
Trigger an alarm on absence of logs

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5133]
The health cache update mechanism generates log entries every minute (or every 5 minutes) in the CloudWatch log groups for the service and indexer lambdas. Add a metric filter &  alarm that triggers a notification when the frequency of those log messages drops below the expected rate. Add a similar metric filter * alarm that triggers when the rate of log messages in the `trail` group drops below the expected rate.

**Comment by hannes-ucsc** [comment]
For demo, throttle the health lambda and show alarm going off.
