### ISSUE TITLE
Remove custodian cloudwatch event rules

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5136]
To see existing event rules, in AWS cloudshell run: `aws events list-rules`

----

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
All the following CloudWatch event rules have been deleted from `dev`…
```
azul-indexer-geryl-failuremessages-event
azul-indexer-geryl-indexercachehealth-event
azul-indexer-geryl-nudge-event
azul-service-geryl-servicecachehealth-event
cloud-custodian-mailer
```
and the following from `dev`, `anvildev` and `prod`.

```
custodian-mandatory_tag_enforcer_aws-ebs
custodian-mandatory_tag_enforcer_aws-ebs-snapshot
custodian-mandatory_tag_enforcer_aws-ec2
custodian-mandatory_tag_enforcer_deleter_aws-ebs
custodian-mandatory_tag_enforcer_deleter_aws-ebs-snapshot
custodian-mandatory_tag_enforcer_deleter_aws-ec2
custodian-mandatory_tag_enforcer_deleter_s3
custodian-mandatory_tag_enforcer_lifecycle_s3
custodian-mandatory_tag_enforcer_s3
custodian-mandatory_tag_enforcer_untagger_aws-ebs
custodian-mandatory_tag_enforcer_untagger_aws-ebs-snapshot
custodian-mandatory_tag_enforcer_untagger_aws-ec2
custodian-mandatory_tag_enforcer_untagger_s3
```

**Comment by achave11-ucsc** [comment]
Needs to be done for all accounts (missing `anvildev`, `prod`, and `anvilprod`).

**Comment by achave11-ucsc** [comment]
Cloud custodian event rules remain to be deleted for `anvilprod` account, assigning issue to @hannes-ucsc to complete the removal of custodian event rules in that account.

**Comment by hannes-ucsc** [comment]
Deleted rules in anvilprod.
