### ISSUE TITLE
CloudWatch metrics and alarms for GitLab EC2 instance

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5139]
…such as CPU usage is high & available disk space. Add alarms for free disk (on root and data volume) below 25% and average CPU usage >= 90% for an hour.

**Comment by achave11-ucsc** [comment]
Spike to investigate if EBS volume usage metric involves SSM agent or cwagent.

**Comment by achave11-ucsc** [comment]
Metrics like `disk_free` free space on the disks in bytes, `disk_used` used space on the disks in bytes, and `cpu_usage_active` the percentage of time that the CPU is active in any capacity in percent are [metrics that can be collected using the cwagent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/metrics-collected-by-CloudWatch-agent.html#linux-metrics-enabled-by-CloudWatch-agent).

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Please continue spike to confirm/deny the hypothesis that CPU usage is also available as an EC2 metric. If so, determine how it relates to the one collected by the cwagent."

**Comment by achave11-ucsc** [comment]
There is such metric in the `AWS/EC2` namespace, see ['Instance metrics'](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html#ec2-cloudwatch-metrics). There seems to be no correlation to the metrics collected by the cwagent. However, the following speculation can be made. cwagent collected metrics will be available under a specific namespace, call it a metric name. Having alarms configured to this metric data will be persistent, recreating and destroying the EC2 instance will not require modifying this type of monitoring infra. On the other hand, if we use the `AWS/EC2` provided metric it will have to be recreated each time the instance ID changes.

**Comment by hannes-ucsc** [comment]
Makes sense. We should collect `disk_used_percent`, `mem_used_percent` and `cpu_usage_active`. We should create alarms on `disk_used_percent >= 75%` and `avg(cpu_usage_active, 1h) > 90%`. We'll decide on a alarm threshold for `mem_used_percent` at a later time when we have a couple of weeks worth of data for that metric.

**Comment by hannes-ucsc** [comment]
For demo, show all new metrics in the AWS console for a lower deployment. Manually lower the threshold for the disk alarm so that the alarm is raised. Revert the manual change.
