### ISSUE TITLE
`source environment` causes a ModuleNotFoundError

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5143]
`ModuleNotFoundError: No module named 'azul'` occurs the first time `source environment` is run in a shell.

```
daniel@Crispin ~/repo/azul1 $ source .venv/bin/activate
(.venv) daniel@Crispin ~/repo/azul1 $ source environment
Error in sitecustomize; set PYTHONVERBOSE for traceback:
ModuleNotFoundError: No module named 'azul'
export_environment.py: Loading environment from deployments/daniel.local/environment.local.py
…
```

The error does not occur for any following runs of `source environment` in the same shell.

```
(.venv) daniel@Crispin ~/repo/azul1 $ deactivate
daniel@Crispin ~/repo/azul1 $
daniel@Crispin ~/repo/azul1 $ . .venv/bin/activate
(.venv) daniel@Crispin ~/repo/azul1 $ source environment
envhook.py: Currently disabled because the ENVHOOK environment variable is set to 0.
export_environment.py: Loading environment from deployments/daniel.local/environment.local.py…
```

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
spike to propose solution.

**Comment by dsotirho-ucsc** [comment]
The ModuleNotFoundError is being raised due to a global import of `azul.args.AzulArgumentHelpFormatter` in `sitecustomize.py`. Since this file is run before `export_environment.py`, `PYTHONPATH` is not yet set and there is no path to the "azul" module.

An easy solution is to make the import of the module local to the one method `_main` where it is used.

```
Subject: [PATCH] Make avro_pfb _add_missing_fields() more dynamic
---
Index: scripts/envhook.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/envhook.py b/scripts/envhook.py
--- a/scripts/envhook.py	(revision fd3608b70c1d570e96c24b399e62e09c03a320c0)
+++ b/scripts/envhook.py	(date 1684458909494)
@@ -29,10 +29,6 @@
     TypeVar,
 )
 
-from azul.args import (
-    AzulArgumentHelpFormatter,
-)
-
 
 class EnvHook:
 
@@ -57,6 +53,9 @@
 
     def _main(self, argv):
         import argparse
+        from azul.args import (
+            AzulArgumentHelpFormatter,
+        )
         parser = argparse.ArgumentParser(description=__doc__,
                                          formatter_class=AzulArgumentHelpFormatter)
         parser.add_argument('action', choices=['install', 'remove'])
```

**Comment by dsotirho-ucsc** [comment]
Investigate if issue exists for `make envhook`

**Comment by dsotirho-ucsc** [comment]
Issue does not exist for `make envhook` due to the Makefile prerequisites for the `envhook` target that require the virtual environment is loaded and `source environment` has been run.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
