### ISSUE TITLE
Remove reliance on `versions` table in DynamoDB for portal database

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5145]
Amazon is strongly consistent so we may not need the versions table anymore. IIRC, it is also used to coordinate access via a row lock or optimistic locking. If we can't remove the table, we need to modify this ticket to instead enable backup of the table so that we can recover from accidental deletions.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Spike to determine if we need the table now that S3 is strongly consistent.

**Comment by nadove-ucsc** [comment]
I think we still need the table. Strong consistency does not solve the problem of multiple users simultaneously trying to write to the object, e.g.:

- User 1 reads S3 object (gets `["spam"]`)
- User 2 reads S3 object (gets `["spam"]`)
- User 1 writes S3 object (new value: `["spam", "eggs"]`)
- User 2 writes S3 object (new value: `["spam", "beans"]`; user 1's changes are lost/overridden)

Our current implementation depends on DynamoDB's [conditional update feature](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ConditionExpression) to ensure that write operations only succeed if the current object version matches the version that was read. I can't find any support for this type of logic in the S3 API.

**Comment by achave11-ucsc** [comment]
Back up of table is handled in #5174.
