### ISSUE TITLE
IT subtest managed_access_indices fails on AnVIL

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5167]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/2695

```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_indices]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 378, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1059, in _test_managed_access
    bundles = self._test_managed_access_indices(catalog, managed_access_source_ids)
  File "/builds/ucsc/azul/test/integration_test.py", line 1114, in _test_managed_access_indices
    hits = self._get_entities(catalog, 'projects')
  File "/builds/ucsc/azul/test/integration_test.py", line 1003, in _get_entities
    body = self._get_url_json(url)
  File "/builds/ucsc/azul/test/integration_test.py", line 633, in _get_url_json
    return json.loads(self._get_url_content(url))
  File "/builds/ucsc/azul/test/integration_test.py", line 636, in _get_url_content
    return self._get_url(url).data
  File "/builds/ucsc/azul/test/integration_test.py", line 648, in _get_url
    self._assertResponseStatus(response, expected_statuses)
  File "/builds/ucsc/azul/test/integration_test.py", line 673, in _assertResponseStatus
    assert response.status in expected_statuses, (
AssertionError: (400, 'Bad Request', b'{"Code":"BadRequestError","Message":"Entity type \'projects\' is invalid for catalog \'anvil-it\'. Must be one of {\'datasets\', \'files\', \'biosamples\', \'activities\', \'donors\'}."}')
```

AnVIL doesn't have projects, or many of the other HCA-specific entity types. Conceptually it should still work, since `dataset` could be used instead of `project`. This can only be observed on `anvilprod`. `anvildev` and `anvilbox` have a [hack](https://github.com/databiosphere/azul/issues/4398) in place that makes all MA-snapshots look like publicly accessible ones. The hack defeats the IT logic for finding MA-sources, causing the `managed_access_indices` subtest to be skipped there. `anvilprod` has mock-MA snapshots and so the aforementioned logic kicks in, enabling the subtest which then fails like this.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "This should be reproducible by indexing the snapshots from `anvilprod` in a personal deployment in the `anvildev` deployment zones."

**Comment by hannes-ucsc** [comment]
No demo, passing IT is sufficient.

**Comment by nadove-ucsc** [comment]
PR #5273 includes a bug caused by files occurring in multiple HCA bundles. A follow-up PR is needed to correct this.
