### ISSUE TITLE
PyCharm formatter hangs on Apple Silicon

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5193]
… or works occasionally but not reliably. This is for `rycus86/pycharm:2019.3.5` docker image.

The behavior can be replicated by running `make format` in a M1 chipset Mac.

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Furthermore, the results of the `make format` command seems to be creating conflicts with the `make pep8` commands. This is evident in [Send GitLab host logs to CloudWatch (#3894) PR #5187](https://github.com/DataBiosphere/azul/pull/5187).

**Comment by dsotirho-ucsc** [comment]
Also update docker image to latest available.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce. The reproduction is non-deterministic so failing to reproduce the issue is no prove of having fixed it. However, show that `make format` runs faster on Apple Silicon.
