### ISSUE TITLE
Snapshots from dcp25 & dcp27 contain `||` in metadata

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5203]
Errors experienced during reindex of `dcp27` catalog

```
[ERROR] RequirementError: ("'||' is disallowed in metadata", TDRBundleFQID(uuid='99abef08-9516-4831-a5c0-685ec357323b', version='2022-08-10T09:53:22.830000Z', source=SourceRef(id='bab5eaa4-c480-49b4-a6dc-4abd02f2f7ec', spec=TDRSourceSpec(prefix=Prefix(common='', partition=1), project='datarepo-96f28c63', name='hca_prod_615158205bb845d08d12f0850222ecf0__20221007_dcp2_20230314_dcp25', is_snapshot=True))))
Traceback (most recent call last):
  File "/var/task/azul/chalice.py", line 142, in patched_event_source_handler
    return old_handler(self_, event, context)
  File "/var/task/chalice/app.py", line 1752, in __call__
    return self.handler(event_obj)
  File "/var/task/chalice/app.py", line 1708, in __call__
    return self.handler(request, self.next_handler)
  File "/var/task/azul/chalice.py", line 193, in _lambda_context_middleware
    return get_response(event)
  File "/var/task/app.py", line 188, in contribute_retry
    app.index_controller.contribute(event, retry=True)
  File "/var/task/azul/indexer/index_controller.py", line 179, in contribute
    contributions = self.transform(catalog, notification, delete)
  File "/var/task/azul/indexer/index_controller.py", line 214, in transform
    results = service.transform(catalog, bundle, partition, delete=delete)
  File "/var/task/azul/indexer/index_service.py", line 263, in transform
    bundle.reject_joiner()
  File "/var/task/azul/indexer/__init__.py", line 457, in reject_joiner
    self._reject_joiner(self.metadata_files)
  File "/var/task/azul/indexer/__init__.py", line 443, in _reject_joiner
    self._reject_joiner(v)
  File "/var/task/azul/indexer/__init__.py", line 443, in _reject_joiner
    self._reject_joiner(v)
  File "/var/task/azul/indexer/__init__.py", line 443, in _reject_joiner
    self._reject_joiner(v)
  File "/var/task/azul/indexer/__init__.py", line 450, in _reject_joiner
    raise RequirementError(msg, self.fqid)
```

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: /aws/lambda/azul-indexer-prod, /aws/lambda/azul-indexer-prod-aggregate, /aws/lambda/azul-indexer-prod-aggregate_retry, /aws/lambda/azul-indexer-prod-contribute, /aws/lambda/azul-indexer-prod-contribute_retry  
start-time: -86400s  
end-time: 0s  
query-string:
```
fields @timestamp, @message
| filter @message like 'disallowed in metadata'
| parse "name='*'" as snapshot
| stats count(*) by snapshot

```
---
| snapshot | count(*) |
| --- | --- |
| hca_prod_615158205bb845d08d12f0850222ecf0__20221007_dcp2_20230314_dcp25 | 66998 |
| hca_prod_5f607e50ba224598b1e9f3d9d7a35dcc__20230201_dcp2_20230501_dcp27 | 44 |
| hca_prod_e6773550c1a6494986431a3154cf2670__20221208_dcp2_20230314_dcp25 | 40 |
---

Timeline:
```
05/10/2023  dcp27 added: 5f607e50ba224598b1e9f3d9d7a35dcc added
05/04/2023  require no ||, no reindex done
04/20/2023  dcp26 added
03/24/2023  dcp25 added: 615158205bb845d08d12f0850222ecf0 updated, e6773550c1a6494986431a3154cf2670 updated
12/12/2022  dcp23 added: e6773550c1a6494986431a3154cf2670 added
10/12/2022  dcp21 added: 615158205bb845d08d12f0850222ecf0 added
```

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Operator to check upcoming DCP releases for updated snapshots to these three projects and confirm that they do not include `||` in metadata. Next release will be `dcp28` which we will likely get to next week, during which time @dsotirho-ucsc will be operator."

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "HCA leadership requested that we prioritize dcp28. We will therefore do it today which means that the current operator (@achave11-ucsc) should be assigned."

**Comment by achave11-ucsc** [comment]
The following, 
```
datarepo-d7690867.hca_prod_615158205bb845d08d12f0850222ecf0__20221007_dcp2_20230530_dcp28.analysis_protocol
```
… still presents metadata with `||` .
```
{"publication_doi":"10.1016/j.cell.2020.04.011||https://doi.org/10.1101/791699"}
```

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Awaiting updated snapshot for project that is still affected in dcp28 (615158205bb845d08d12f0850222ecf0). Hopefully they will be available for release dcp29. Ticket should remain assigned to operator for tracking this."

**Comment by achave11-ucsc** [comment]
The malformed project (65cbfea55c544255a1d014549a86a5c1) has been updated in the `dcp29` catalog, and no longer contains the joiner in its the metadata.

**Comment by achave11-ucsc** [comment]
Project has been fixed, and was [indexed successfully](https://service.azul.data.humancellatlas.org/index/projects/65cbfea5-5c54-4255-a1d0-14549a86a5c1?catalog=dcp29) by Azul.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Finally."
