### ISSUE TITLE
Review inventory once and create monthly reminder

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5218]

**Comment by hannes-ucsc** [comment]
I think we did this ad-hoc last week.

**Comment by achave11-ucsc** [comment]
We did create a reminder: https://ucsc-gi.slack.com/archives/C02B4S0V6GH/p1684459719135989.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "The initial review was done when the inventory PR was first demoed."
