### ISSUE TITLE
Request to service for "Unspecified" terms

### ISSUE THREAD

**Issue by frano-m** [DataBiosphere/azul#523]
At the moment, when an "Unspecified" term has been selected, no data is returned.

1. under filter "Method", "Storage Method", click "Unspecified"
2. Table should show all results where "preservationMethod" = `[]`
3. Currently table returns no results

What sort of request would we need to call to return corresponding data?
for example:
`https://service.dev.explore.data.humancellatlas.org/repository/projects?from=1&size=1&filters=%7B%22file%22:%7B%22preservationMethod%22:%7B%22is%22:%5B%22none%22%5D%7D%7D%7D`
OR
`https://service.dev.explore.data.humancellatlas.org/repository/projects?from=1&size=1&filters=%7B%22file%22:%7B%22preservationMethod%22:%7B%22is%22:%5B%22null%22%5D%7D%7D%7D`
OR ???

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-339)
┆Project Name: azul
┆Issue Number: AZUL-339

**Comment by hannes-ucsc** [comment]
The filters string is a Python literal (don't ask) and not JSON. The Python literals for JSON `true`, `false` and `null` are `True`, `False` and `None`. This should work

```
https://service.dev.explore.data.humancellatlas.org/repository/projects?from=1&size=1&filters={"file":{"preservationMethod":{"is":None}}}
```
