### ISSUE TITLE
Transient IT failure due to AssertionError in GitLab `dev`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5251]
…  for `managed_access_manifest` [sub-test](https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/68894#L1713).
```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_manifest]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 378, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1105, in _test_managed_access
    self._test_managed_access_manifest(catalog,
  File "/builds/ucsc/azul/test/integration_test.py", line 1258, in _test_managed_access_manifest
    assert_manifest({public_bundle, *managed_access_bundles})
  File "/builds/ucsc/azul/test/integration_test.py", line 1251, in assert_manifest
    self.assertNotEqual(set(), found_bundles)
AssertionError: set() == set()
----------------------------------------------------------------------
Ran 14 tests in 556.237s
FAILED (failures=1, skipped=3)
make: *** [Makefile:240: integration_test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
1mERROR: Job failed: exit code 1
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike to attempt to reproduce and diagnose.

**Comment by nadove-ucsc** [comment]
This subtest splits the `bundle_uuid` manifest column using the manifest joiner (`'||'`). PR #5041 changed the format of the compact manifest to include spaces around the joiner (`' || '`), but the test was not updated accordingly, causing spaces to occur at the beginning and end of the split bundle UUIDs and leading to mismatches between the expected and observed values. 

Presumably, the failure is transient because not every manifest includes files that occur in multiple indexed bundles.

The fix is simple:

```diff
Subject: [PATCH] fix
---
Index: test/integration_test.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/integration_test.py b/test/integration_test.py
--- a/test/integration_test.py	(revision 0357f2950d860dab7ef82130b02981067655187d)
+++ b/test/integration_test.py	(date 1685585468057)
@@ -1241,7 +1241,7 @@
             ))
             all_found_bundles = set()
             for row in manifest_rows:
-                row_bundles = set(row['bundle_uuid'].split(ManifestGenerator.column_joiner))
+                row_bundles = set(row['bundle_uuid'].split(ManifestGenerator.padded_joiner))
                 # It's possible for one file to be present in multiple
                 # bundles (e.g. due to stitching), so each row may include
                 # additional bundles besides those included in the filters.
```
