### ISSUE TITLE
Restore best-practices log metric alarms

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5255]
… but filter out any notifications resulting from them. This will fix the SecurityHub rule checks that we already passed last year but failed again due to changes to the pattern to [silence overly noisy notifications](https://github.com/DataBiosphere/azul/issues/5043#issuecomment-1571408164) resulting from bad actors looking for vulnerable web application in the DB's CloudFront distributions and other causes and alarms.

For a complete list of alarms that need to be restored, please review all failing SecurityHub findings in all accounts.

The filtering of notifications should occur in the [Lambda function](https://github.com/DataBiosphere/azul/issues/5246) that is subscribed to the monitoring SNS topic.

**Comment by bvizzier-ucsc** [comment]
https://github.com/DataBiosphere/azul/issues/5246#issuecomment-2540110718

**Comment by hannes-ucsc** [comment]
In fact, the NIST 800.53 security standard in SecurityHub does not even include CloudWatch.1 to CloudWatch.14, the controls that mandate certain log metric filters, so this can be closed as invalid.
