### ISSUE TITLE
Unit without value for donor age in project 5f607e50

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5264]
… which causes indexing failures in a recently updated snapshot,
```
datarepo-75a8bdf9.hca_prod_5f607e50ba224598b1e9f3d9d7a35dcc__20230201_dcp2_20230531_dcp28.donor_organism
```
with documentId `0aecdb08-b489-4346-bf14-d3db0958b0ce`.

This causes an assertion error to be raised in Azul.
```
Traceback (most recent call last):
  File "/var/task/azul/indexer/index_controller.py", line 179, in contribute
    contributions = self.transform(catalog, notification, delete)
  File "/var/task/azul/indexer/index_controller.py", line 214, in transform
    results = service.transform(catalog, bundle, partition, delete=delete)
  File "/var/task/azul/indexer/index_service.py", line 279, in transform
    contributions.extend(transformer.transform(partition))
  File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 1404, in _transform
    donors=list(map(self._donor, visitor.donors.values())),
  File "/var/task/azul/plugins/metadata/hca/indexer/transform.py", line 813, in _donor
    require(donor.organism_age_unit is None)
  File "/var/task/azul/__init__.py", line 1667, in require
    reject(not condition, *args, exception=exception)
  File "/var/task/azul/__init__.py", line 1686, in reject
    raise exception(*args)
azul.RequirementError
```

This is the offending metadata:
```
{
    "describedBy": "https://schema.humancellatlas.org/type/biomaterial/15.6.1/donor_organism",
    "schema_type": "biomaterial",
    "biomaterial_core": {
        "biomaterial_id": "P-M032",
        "biomaterial_name": "Human Donor",
        "biomaterial_description": "human with COVID-19",
        "ncbi_taxon_id": [
            9606
        ]
    },
    "genus_species": [
        {
            "text": "Homo sapiens",
            "ontology": "NCBITaxon:9606",
            "ontology_label": "Homo sapiens"
        }
    ],
    "sex": "male",
    "is_living": "yes",
    "organism_age_unit": {
        "text": "year",
        "ontology": "UO:0000036",
        "ontology_label": "year"
    },
    "development_stage": {
        "text": "human adult stage",
        "ontology": "HsapDv:0000087",
        "ontology_label": "human adult stage"
    },
    "diseases": [
        {
            "text": "mild/moderate COVID-19",
            "ontology": "MONDO:0100096",
            "ontology_label": "COVID-19"
        }
    ],
    "medical_history": {
        "medication": "unknown"
    },
    "provenance": {
        "document_id": "0aecdb08-b489-4346-bf14-d3db0958b0ce",
        "submission_date": "2023-01-12T15:43:46.042Z",
        "update_date": "2023-05-17T09:28:18.886Z",
        "schema_major_version": 15,
        "schema_minor_version": 6
    }
}
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Supposedly the affected project was updated in dcp29 (snapshot `hca_prod_5f607e50ba224598b1e9f3d9d7a35dcc__20230201_dcp2_20230616_dcp29`)

The reindex as part of the promotion #5334 which includes the dcp29 release will show if the issue is fixed.

**Comment by achave11-ucsc** [comment]
Project was indexed successfully without issues. 
https://service.azul.data.humancellatlas.org/index/projects/5f607e50-ba22-4598-b1e9-f3d9d7a35dcc?catalog=dcp29
