### ISSUE TITLE
Update operator manual for removal of previous operator's permissions

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5277]
Update the operator manual instruction:

> Ask Erich Weiler ([weiler@soe.ucsc.edu](mailto:weiler@soe.ucsc.edu)) via email (cc Trevor and Hannes) to give you developer access to the platform-hca-prod AWS account

with the following changes:

- [ ] Request also that developer access to platform-hca-prod is removed from the previous operator.
- [ ] Replace reference to Trevor with Ben.
- [ ] Include mention of anvilprod where necessary 

---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
These changes have already been implemented by Hannes in PR https://github.com/DataBiosphere/azul/pull/5322 (for issue #5302)

**Comment by achave11-ucsc** [comment]
https://github.com/DataBiosphere/azul/blob/03bad7959b7b6a744d9cd287f43a2947e5fbb2c2/OPERATOR.rst?plain=1#L22
