### ISSUE TITLE
IT failure with `anvilprod` snapshots

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5279]
Found while running IT on my `nadove5` deployment which indexes the `anvilprod` snapshots. On latest develop (commit bd1bd60a), seed 8049852765673357024. 

```
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [catalog_complete] (catalog='anvilprodtest-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nadove/PycharmProjects/azul-sc/test/integration_test.py", line 383, in subTest
    yield
  File "/home/nadove/PycharmProjects/azul-sc/test/integration_test.py", line 1010, in _assert_catalog_complete
    self.assertSetEqual(indexed_fqids, expected_fqids)
AssertionError: Items in the first set but not the second:
AnvilBundleFQID(uuid='c6a1b8c7-7ad4-a39a-ad61-6575ce8f5dad', version='2022-06-01T00:00:00.000000Z', source=SourceRef(id='cc1c98a4-bfc4-45f2-b8dc-e920e5ca634d', spec=TDRSourceSpec(prefix=Prefix(common='', partition=2), project='datarepo-dev-43738c90', name='ANVIL_1000G_2019_Dev_20230302_ANV5_202303032342', is_snapshot=True)), entity_type=<BundleEntityType.primary: 'biosample'>)
Items in the second set but not the first:
AnvilBundleFQID(uuid='c6a1b8c7-7ad4-a39a-ad61-6575ce8f5dad', version='2022-06-01T00:00:00.000000Z', source=SourceRef(id='cc1c98a4-bfc4-45f2-b8dc-e920e5ca634d', spec=TDRSourceSpec(prefix=Prefix(common='', partition=2), project='datarepo-dev-43738c90', name='ANVIL_1000G_2019_Dev_20230302_ANV5_202303032342', is_snapshot=True)), entity_type=<BundleEntityType.supplementary: 'file'>)

----------------------------------------------------------------------
Ran 14 tests in 707.137s

FAILED (failures=1, skipped=2)
make: *** [Makefile:237: integration_test] Error 1
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by nadove-ucsc** [comment]
Appears connected to [the false positive supplementary files in the current snapshots](https://github.com/DataBiosphere/azul/issues/5229#issuecomment-1556040066)

**Comment by dsotirho-ucsc** [comment]
Spike to diagnose and propose a solution.

**Comment by nadove-ucsc** [comment]
File `c6a1b8c7-7ad4-439a-ad61-6575ce8f5dad` is marked as supplementary but is also linked to a biosample. This results in the indexer producing both a primary bundle (based on the upstream biosample) and a supplementary bundle (based on itself).

This error occurs when both of these bundles are indexed during the same IT run. This results in a hit from `/index/files` that looks like this:

```
{
    entryId": "c6a1b8c7-7ad4-439a-ad61-6575ce8f5dad",
    "sources": [
        {
              "sourceSpec": "tdr:datarepo-dev-43738c90:snapshot/ANVIL_1000G_2019_Dev_20230302_ANV5_202303032342:/2",
              "sourceId": "cc1c98a4-bfc4-45f2-b8dc-e920e5ca634d"
        }
    ],
    "bundles": [
        {
              "bundleUuid": "c6413299-8a1f-a5b1-bd77-7a0ed9901685",
              "bundleVersion": "2022-06-01T00:00:00.000000Z"
        },
        {
              "bundleUuid": "c6a1b8c7-7ad4-a39a-ad61-6575ce8f5dad",
              "bundleVersion": "2022-06-01T00:00:00.000000Z"
        }
    ],
    ....
    files": [
        {
              ...
              "is_supplementary": true,
              ...
        }
    ]
```

PR #5231 attempted to handle this problem, but the solution is not sufficient. 
Because the file is linked to a biosample, the supplementary bundle is incorrectly counted as a primary bundle. This causes a mismatch between the expected and observed bundles.

**Comment by nadove-ucsc** [comment]
What is needed is a foolproof way to determine which bundles are supplementary and which are primary from the hit shown above. I think the best way to do this is to compare each bundle UUID to the file entity ID. If they match, the bundle must be supplementary.

**Comment by dsotirho-ucsc** [comment]
Hannes to review Noa's findings.

**Comment by hannes-ucsc** [comment]
I hesitate to sink more time into a fix. I'm in touch with Nate from the BI to see if they can expedite the fix.

**Comment by hannes-ucsc** [comment]
If @nadove-ucsc runs out of work they can take this on.

I assume that "match" means taking into account the UUID version difference (4 vs a).

**Comment by hannes-ucsc** [comment]
ETA for the fixed snapshot is ["early next week"](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1686271327431249?thread_ts=1684805634.413329&cid=C03TPJS54DC).

**Comment by nadove-ucsc** [comment]
> I assume that "match" means taking into account the UUID version difference (4 vs a).

Correct.

**Comment by dsotirho-ucsc** [comment]
Spike to confirm that the [updated snapshot](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1686592132224359?thread_ts=1684805634.413329&cid=C03TPJS54DC) for 1000G indeed fixes the [issue](https://github.com/DataBiosphere/azul/issues/5229) of false supplementary files.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Assuming that are no more false supplementary files, we should be able to revert the workaround for #5229 as part of a PR connected to that issue and close this one."

**Comment by nadove-ucsc** [comment]
I found no occurrences of supplementary files derived from non-supplementary files or from biosamples. So I believe the issue with false supplementary files has indeed been solved.
```
WITH supp_files AS (
  SELECT file_id
  FROM `datarepo-dev-e53e74aa.ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732.anvil_file`
  WHERE is_supplementary
), 
prim_files AS (
  SELECT file_id
  FROM `datarepo-dev-e53e74aa.ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732.anvil_file`
  WHERE NOT is_supplementary
),
linked_files AS (
  SELECT generated_file_id, used_file_id, used_biosample_id
  FROM `datarepo-dev-e53e74aa.ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732.anvil_activity`
  UNION ALL
  SELECT generated_file_id, used_file_id, [] AS used_biosample_id
  FROM `datarepo-dev-e53e74aa.ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732.anvil_alignmentactivity`
  UNION ALL
  SELECT generated_file_id, [] AS used_file_id, used_biosample_id
  FROM `datarepo-dev-e53e74aa.ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732.anvil_assayactivity`
  UNION ALL
  SELECT generated_file_id, [] AS used_file_id, used_biosample_id
  FROM `datarepo-dev-e53e74aa.ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732.anvil_sequencingactivity`
  UNION ALL
  SELECT generated_file_id, used_file_id, [] AS used_biosample_id
  FROM `datarepo-dev-e53e74aa.ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732.anvil_variantcallingactivity`
 )
SELECT *
FROM linked_files AS lf, supp_files AS sf, prim_files AS pf
WHERE 
  sf.file_id IN UNNEST(lf.generated_file_id) 
  AND 
  (
    ARRAY_LENGTH(lf.used_biosample_id) > 0 
    OR
    pf.file_id IN UNNEST(lf.used_file_id)
  )
```

**Comment by hannes-ucsc** [comment]
Thank you. As quoted above, there is no need to address this anymore. We will instead revert the changes for #5229 and switch to the updated snapshot in a second PR connected to that same issue.
