### ISSUE TITLE
_select doesn't validate its argument

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5289]
`_select` exits with a successful status after selecting an invalid deployment. After revoking the existing credentials, it prints a hard-to-spot error message before loading the environment from the previously selected deployment.
```
$ _select foo
Removing login credentials for 465330168186.dkr.ecr.us-east-1.amazonaws.com

Revoked temporary AWS credentials.
....
Revoked temporary Google credentials.

error: foo
export_environment.py: Loading environment from deployments/anvilprod/environment.local.py
...
Temporary session credentials are in effect for AWS, Google, Amazon ECR and the GitLab docker registry. Use '_deauth' to revert the effect of this command.

lrwxrwxrwx 1 nadove nadove 9 Jun  6 17:22 .active -> anvilprod
$ echo $?
0
```

Additionally, tab completion is no longer working. When typing `_select dev[TAB]`:

```
 _select devbasename: extra operand ‘/home/nadove/PycharmProjects/azul-sc/deployments/nadove5.local’
Try 'basename --help' for more information.
```

Note that I had `anvilprod` selected when I collected this transcript, not `nadove5`.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Can't reproduce the tab completion issue.

**Comment by nadove-ucsc** [comment]
> Can't reproduce the tab completion issue.

Still affects me. I traced the error to [this line](https://github.com/DataBiosphere/azul/blob/3518091b9a99f95b84643d24e4a121602dcdad3c/environment#L178). Here's what happens when I try to run it outside of the `_select` function:

```
$ find "${project_root}/deployments" -maxdepth 1 -type d -print0 | xargs -0 basename
basename: extra operand ‘/home/nadove/PycharmProjects/azul-sc/deployments/nadove5.local’
Try 'basename --help' for more information.
```

If I substitute `echo` for `basename`, all directories in `deployments` are printed on the same line, so I think `basename` is seeing every directory at once instead of them being split at `\x00` as expected.

`find` version 4.9.0
`xargs` version 4.9.0
`basename` version 9.1

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
