### ISSUE TITLE
Whitelist more staging projects

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#529]
Columns V to AA of the [staging CBeta sheet](https://docs.google.com/spreadsheets/d/155ACGfrgobXy9DI_GduYyHCpkCyFDIa6FvgH8keBdug/edit?ts=5bdb5cf7#gid=622734345) have not yet been whitelisted yet.

1f9a699a-262c-40a0-8b2c-7ba960ca388c 
62aa3211-bf52-4873-9029-0bcc1d09e553
a71dee10-9a4d-4ea2-a6f3-ae7314112cf1
adb384b2-cd5e-4cf5-9205-5f066474005f
46c58e08-4518-4e45-acfe-bdab2434975d
3eaad325-3666-4b65-a4ed-e23ff71222c1

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-341)
┆Project Name: azul
┆Issue Number: AZUL-341

**Comment by malloryfreeberg** [comment]
Noting here that, if possible, it would be great the get the rest of these datasets/projects whitelisted soon. We need to let the contributors of these datasets see them in the Browser before Adrienne and Gabby start the closed beta testing.

**Comment by malloryfreeberg** [comment]
@hannes-ucsc is this ticket closed because it is done? I don't see these projects in the staging Browser :(

**Comment by malloryfreeberg** [comment]
Thanks for the clarification!
