### ISSUE TITLE
Suppress unauthorized alarms for visiting Inspector console

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5291]
Similar to the changes in PR #5278 for #5043, we would like to eliminate the false alarms that are caused by simply visiting the Amazon Inspector console. Here's one redacted example:

```
{
        "@timestamp": "2023-06-09 17:35:28.723",
        "@message": {
            "eventVersion": "1.08",
            "userIdentity": {
                "type": "AssumedRole",
                "principalId": "[REDACTED:hannes@ucsc.edu](mailto:REDACTED%3Ahannes@ucsc.edu)",
                "arn": "arn:aws:sts::465330168186:assumed-role/administrator/[hannes@ucsc.edu](mailto:hannes@ucsc.edu)",
                "accountId": "465330168186",
                "accessKeyId": "REDACTED",
                "sessionContext": {
                    "sessionIssuer": {
                        "type": "Role",
                        "principalId": "REDACTED",
                        "arn": "arn:aws:iam::465330168186:role/administrator",
                        "accountId": "465330168186",
                        "userName": "administrator"
                    },
                    "webIdFederationData": {},
                    "attributes": {
                        "creationDate": "2023-06-09T17:33:06Z",
                        "mfaAuthenticated": "true"
                    }
                }
            },
            "eventTime": "2023-06-09T17:35:01Z",
            "eventSource": "[inspector2.amazonaws.com](http://inspector2.amazonaws.com/)",
            "eventName": "DescribeOrganizationConfiguration",
            "awsRegion": "us-east-1",
            "sourceIPAddress": "REDACTED",
            "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0",
            "errorCode": "AccessDenied",
            "requestParameters": null,
            "responseElements": null,
            "requestID": "4c799d82-a44e-42f2-aabe-aebee90ed704",
            "eventID": "52bd99ce-7ff9-4038-80ee-76894a30b846",
            "readOnly": true,
            "eventType": "AwsApiCall",
            "managementEvent": true,
            "recipientAccountId": "465330168186",
            "eventCategory": "Management"
        }
    }
```

Also update canned Cloudwatch Insight queries.

---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] ~… affect audit logging in the system, like~
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] ~… affect monitoring of the system~
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Security review: This change increases our security posture by increasing the specificity of the alarms (reducing false positives).

**Comment by hannes-ucsc** [comment]
For demo, visit the Inspector console and show that no alarms are raised.
