### ISSUE TITLE
Update/harden docker.elastic.co/elasticsearch/elasticsearch

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5292]
We currently use

https://www.docker.elastic.co/r/elasticsearch/elasticsearch:7.10.1-amd64

from Elastic's registry which turns out to be the same as the one on docker.io:

https://hub.docker.com/layers/library/elasticsearch/7.10.1/images/sha256-e9a1fe65f68b2d2b9583287d1190f67f23af08582eac4d2a8dc342e4219c7306

Elastic offers an image for the next patch level, 7.10.2, and docker.io does not, but that version is only two months younger and so will be equally riddled with CVEs.

Worse, the images from that time period (2020/21) are based on CentOS 8 which is EOL, so without updates.

More recent 7.x images are based on Ubuntu LTS 20 which is not yet EOL. This means we need to update to the most recent 7.x image (currently [7.17.10](https://www.docker.elastic.co/r/elasticsearch/elasticsearch:7.17.10-amd64) *and* harden that image.

This means that the version of ES that we test against will be different from the version running on the cluster.

Spike to see if the tests even pass on 7.17.10. The easiest way to do that is to bump the image references (there are two) on a branch and push that branch to GitHub. GitHub pulls the upstream images, not the ones we mirror in ECR. Alternatively, one could set azul_docker_registry to `''` and run `make test`.

If that works, we need to create a new `Dockerfile` with, in essence 

```
FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.10
RUN sudo apt-get update && sudo apt-get upgrade
```

and a Makefile that can build and push that image to Dockerhub (remember that that image needs to be multiarch).

- [ ] ~Security design review completed; the Resolution of this issue does **not**~ …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [ ] ~… introduce a new software dependency like~ (https://github.com/DataBiosphere/azul/issues/5292#issuecomment-1581656893)
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Security review: this change does introduce a newer version of a Docker images. That image will have significantly fewer vulnerabilities.

**Comment by dsotirho-ucsc** [comment]
To test I set `azul_docker_registry` to an empty string in my `environment.local.py`, and changed the elasticsearch version used in `es_test_case.py`:
```
es_endpoint = cls._create_container('docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
```

Running `azul_docker_registry="" make test` resulted in 33 errors

```
======================================================================
ERROR: test_well_bundles (indexer.test_indexer.TestHCAIndexer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/daniel/repo/azul1/test/indexer/test_indexer.py", line 1290, in test_well_bundles
    hits = self._get_all_hits()
  File "/Users/daniel/repo/azul1/test/indexer/__init__.py", line 139, in _get_all_hits
    self._verify_sorted_lists(hit)
  File "/Users/daniel/repo/azul1/test/indexer/__init__.py", line 224, in _verify_sorted_lists
    num_lists_counted = verify_sorted_lists(data)
  File "/Users/daniel/repo/azul1/test/indexer/__init__.py", line 189, in verify_sorted_lists
    return sum(verify_sorted_lists(val, (*path, key))
  File "/Users/daniel/repo/azul1/test/indexer/__init__.py", line 189, in <genexpr>
    return sum(verify_sorted_lists(val, (*path, key))
  File "/Users/daniel/repo/azul1/test/indexer/__init__.py", line 206, in verify_sorted_lists
    if path[-2] == 'projects' and path[-1] in ordered_fields:
IndexError: tuple index out of range

----------------------------------------------------------------------
Ran 400 tests in 1319.089s

FAILED (errors=33, skipped=4)
```

Most of these errors had the same cause, line 206 in verify_sorted_lists. Upon further investigation it was revealed there is now an unexpected `path` value of `('_ignored',)` that is being passed in.

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-ignored-field.html

With the hack patch below, running `azul_docker_registry="" make test` completed without error:

```
Subject: [PATCH] Add hash `null` provider
---
Index: test/es_test_case.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/es_test_case.py b/test/es_test_case.py
--- a/test/es_test_case.py	(revision 94231bbd7aca326bb71d6af394e6507499520308)
+++ b/test/es_test_case.py	(date 1686761225386)
@@ -36,7 +36,7 @@
     @classmethod
     def setUpClass(cls):
         super().setUpClass()
-        es_endpoint = cls._create_container('docker.elastic.co/elasticsearch/elasticsearch:7.10.1',
+        es_endpoint = cls._create_container('docker.elastic.co/elasticsearch/elasticsearch:7.17.10',
                                             container_port=9200,
                                             environment=['xpack.security.enabled=false',
                                                          'discovery.type=single-node',
Index: test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json b/test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json
--- a/test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json	(revision 94231bbd7aca326bb71d6af394e6507499520308)
+++ b/test/indexer/data/aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.results.json	(date 1686761148662)
@@ -3,6 +3,7 @@
         "_index": "azul_bundles_dev",
         "_type": "_doc",
         "_id": "aaa96233-bf27-44c7-82df-b4dc15ad4d9d_aaa96233-bf27-44c7-82df-b4dc15ad4d9d_2018-11-02T11:33:44.698028Z_exists",
+        "_ignored": ["contents.projects.project_description.keyword"],
         "_score": 1.0,
         "_source": {
             "entity_id": "aaa96233-bf27-44c7-82df-b4dc15ad4d9d",
@@ -269,6 +270,7 @@
         "_index": "azul_files_dev",
         "_type": "_doc",
         "_id": "0c5ac7c0-817e-40d4-b1b1-34c3d5cfecdb_aaa96233-bf27-44c7-82df-b4dc15ad4d9d_2018-11-02T11:33:44.698028Z_exists",
+        "_ignored": ["contents.projects.project_description.keyword"],
         "_score": 1.0,
         "_source": {
             "entity_id": "0c5ac7c0-817e-40d4-b1b1-34c3d5cfecdb",
@@ -508,6 +510,7 @@
         "_index": "azul_files_dev",
         "_type": "_doc",
         "_id": "70d1af4a-82c8-478a-8960-e9028b3616ca_aaa96233-bf27-44c7-82df-b4dc15ad4d9d_2018-11-02T11:33:44.698028Z_exists",
+        "_ignored": ["contents.projects.project_description.keyword"],
         "_score": 1.0,
         "_source": {
             "entity_id": "70d1af4a-82c8-478a-8960-e9028b3616ca",
@@ -747,6 +750,7 @@
         "_index": "azul_samples_dev",
         "_type": "_doc",
         "_id": "a21dc760-a500-4236-bcff-da34a0e873d2_aaa96233-bf27-44c7-82df-b4dc15ad4d9d_2018-11-02T11:33:44.698028Z_exists",
+        "_ignored": ["contents.projects.project_description.keyword"],
         "_score": 1.0,
         "_source": {
             "entity_id": "a21dc760-a500-4236-bcff-da34a0e873d2",
@@ -1011,6 +1015,7 @@
         "_index": "azul_projects_dev",
         "_type": "_doc",
         "_id": "e8642221-4c2c-4fd7-b926-a68bce363c88_aaa96233-bf27-44c7-82df-b4dc15ad4d9d_2018-11-02T11:33:44.698028Z_exists",
+        "_ignored": ["contents.projects.project_description.keyword"],
         "_score": 1.0,
         "_source": {
             "entity_id": "e8642221-4c2c-4fd7-b926-a68bce363c88",
@@ -2456,6 +2461,7 @@
         "_index": "azul_projects_aggregate_dev",
         "_type": "_doc",
         "_id": "e8642221-4c2c-4fd7-b926-a68bce363c88",
+        "_ignored": ["contents.projects.project_description.keyword"],
         "_score": 1.0,
         "_source": {
             "entity_id": "e8642221-4c2c-4fd7-b926-a68bce363c88",
@@ -2779,6 +2785,7 @@
         "_index": "azul_cell_suspensions_dev",
         "_type": "_doc",
         "_id": "412898c5-5b9b-4907-b07c-e9b89666e204_aaa96233-bf27-44c7-82df-b4dc15ad4d9d_2018-11-02T11:33:44.698028Z_exists",
+        "_ignored": ["contents.projects.project_description.keyword"],
         "_score": 1.0,
         "_source": {
             "entity_id": "412898c5-5b9b-4907-b07c-e9b89666e204",
Index: test/indexer/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/indexer/__init__.py b/test/indexer/__init__.py
--- a/test/indexer/__init__.py	(revision 94231bbd7aca326bb71d6af394e6507499520308)
+++ b/test/indexer/__init__.py	(date 1686761225382)
@@ -203,7 +203,9 @@
                             'contact_names',
                             'publication_titles'
                         }
-                        if path[-2] == 'projects' and path[-1] in ordered_fields:
+                        if path[0] == '_ignored':
+                            return 0
+                        elif path[-2] == 'projects' and path[-1] in ordered_fields:
                             return 0
                         else:
                             self.assertEqual(data, sorted(data, key=lambda x: (x is None, x)))
```

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Continue spike to confirm that we do not supply a value in the mapping for either `ignore_above` or any other property that would cause the `project_description` to be ignored during indexing. Furthermore, try to determine what the default value for `ignore_above` is, or, if we do specify `ignore_above`, what we specify. Thirdly, specify value for `ignore_above` in the mapping for that field so that we do not trip the limit during unit tests."

**Comment by dsotirho-ucsc** [comment]
> confirm that we do not supply a value in the mapping for either ingore_above or any other property that would cause the project_description to be ignored during indexing

We do specify a value in `src/azul/plugins/__init__.py`

```
    string_mapping = {
        'type': 'text',
        'fields': {
            'keyword': {
                'type': 'keyword',
                'ignore_above': 256
            }
        }
    }
```

> try to determine what the default value for ignore_above is, or, if we do specify ignore_above, what we specify

According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-params), the default for keyword fields in 256. We also specify the value of `256`.

> specify a value for ignore_above in the mapping for that field so that we do not trip the limit during unit tests

The largest project_description found in a canned bundle has a len() of 2715. With the `ignore_above` set to 2715 (and using elasticsearch:7.17.10) all tests were able to pass without any other modification. The absolute maximum recommended by Elasticsearch is 8191.

https://www.elastic.co/guide/en/elasticsearch/reference/7.17/ignore-above.html

> This option is also useful for protecting against Lucene’s term byte-length limit of 32766.
> 
> The value for ignore_above is the character count, but Lucene counts bytes. If you use UTF-8 text with many non-ASCII characters, you may want to set the limit to 32766 / 4 = 8191 since UTF-8 characters may occupy at most 4 bytes.

Note: the latest schema recommends that `project_description` "should be fewer than 300 words", however there is no length limit enforced.

https://schema.humancellatlas.org/core/project/7.0.5/project_core

> "project_description": {
>       "description": "A longer description of the project which includes research goals and experimental approach.",
>       "type": "string",
>       "user_friendly": "Project description",
>       "guidelines": "Project description should be fewer than 300 words, such as an abstract from a grant application or publication."
> }

`project_description` lengths from all canned bundles (test/indexer/data/):

```
len    bundle
-----|------------------------------------------------------------------------------
2715   587d74b4-1075-4bbf-b96a-4d1ede0481b2.dss.hca.json
2715   3db604da-940e-49b1-9bcc-25699a55b295.dss.hca.json
2040   d7b8cbff-aee9-5a05-a4a1-d8f4e720aee7.dss.hca.json
2040   8c1773c3-1885-545f-9381-0dab1edf6074.dss.hca.json
2040   7a330531-ec7f-5aee-84d4-2ba24d66e93b.dss.hca.json
2040   4da04038-adab-59a9-b6c4-3a61242cc972.dss.hca.json
2040   3ac62c33-93e1-56b4-b857-59497f5d942d.dss.hca.json
2040   1f6afb64-fa14-5c6f-a474-a742540108a3.dss.hca.json
2040   1ed68210-eaba-531d-ba9e-db80164d65ef.dss.hca.json
1780   2c7d06b8-658e-4c51-9de4-a768322f84c5.dss.hca.json
1721   e2c3054e-9fba-4d7a-b85b-a2220d16da73.dss.hca.json
1721   aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-04T11:33:44.698028Z.dss.hca.json
1721   aaa96233-bf27-44c7-82df-b4dc15ad4d9d.2018-11-02T11:33:44.698028Z.dss.hca.json
1721   3f8176ff-61a7-4504-a57c-fc70f38d5b13.dss.hca.json
1583   e0ae8cfa-2b51-4419-9cde-34df44c6458a.dss.hca.json
1366   04836733-0449-4e57-be2e-6f3b8fbdfb12.dss.hca.json
1328   8338b891-f3fa-5e7b-885f-e4ee5689ee15.dss.hca.json
1328   7eb74d9f-8346-5420-b7e4-b486f99451a8.dss.hca.json
1328   4b03c1ce-9df1-5cd5-a8e4-48a2fe095081.dss.hca.json
1328   00f48893-5e9d-52cd-b32d-af88edccabfa.dss.hca.json
1179   97f0cc83-f0ac-417a-8a29-221c77debde8.dss.hca.json
1179   8c90d4fe-9a5d-4e3d-ada2-0414b666b880.dss.hca.json
1143   fce68057-b0f0-5d11-b9a7-30e8fa3259a8.dss.hca.json
1055   02e69c25-71e2-48ca-a87b-e256938c6a98.dss.hca.json
 970   ffac201f-4b1c-4455-bd58-19c1a9e863b4.dss.hca.json
 951   f0731ab4-6b80-4eed-97c9-4984de81a47c.dss.hca.json
 951   cfab8304-dc9f-439e-af29-f8eb75b0729d.dss.hca.json
 940   1fd499c5-f397-4bff-9af0-eb42c37d5fbe.dss.hca.json
 940   0722b70c-6778-423d-8fe9-869e2a515d35.dss.hca.json
 768   79fa91b4-f1fc-534b-a935-b57342804a70.2020-12-10T10:30:00.000000Z.dss.hca.json
 741   dcccb551-4766-4210-966c-f9ee25d19190.dss.hca.json
 741   412cd8d5-5990-43cd-84cc-6c7796b8a76d.dss.hca.json
 741   411cd8d5-5990-43cd-84cc-6c7796b8a76d.dss.hca.json
 715   f79257a7-dfc6-46d6-ae00-ba4b25313c10.dss.hca.json
 715   4426adc5-b3c5-5aab-ab86-51d8ce44dfbe.tdr.hca.json
 685   1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.tdr.hca.json
 685   1b6d8348-d6e9-406a-aa6a-7ee886e52bf9.dss.hca.json
 667   b7fc737e-9b7b-4800-8977-fe7c94e131df.dss.hca.json
 633   fa5be5eb-2d64-49f5-8ed8-bd627ac9bc7a.dss.hca.json
 207   d0e17014-9a58-4763-9e66-59894efbdaa8.dss.hca.json
 204   d5e01f9d-615f-4153-8a56-f2317d7d9ce8.dss.hca.json
 169   80baee6e-00a5-4fdc-bfe3-d339ff8a7178.dss.hca.json
  38   94f2ba52-30c8-4de0-a78e-f95a3f8deb9c.dss.hca.json
```

**Comment by hannes-ucsc** [comment]
Looks like the field is ignored in 7.10, too, it just wasn't reported as such in the document source.

https://github.com/elastic/elasticsearch/issues/74228

Fix as in patch above but make the change to `_verify_sorted_lists` smarter. It already is brittle and the patch makes even more so. There is a way to code the existing condition for ordered project fields more defensively.  _verify_sorted_lists shouldn't even look at other top level fields. It should start the recursion at `_source`.

Also: Need a FIXME (comment, commit and issue) to not include fields in contributions that are then ignored. Note how the project_description is present in file and other contribution documents, but not the corresponding aggregates.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Because we need this image for unit tests in GitHub Actions, this image needs to be pushed to DockerHub. Model your approach on https://github.com/DataBiosphere/azul-docker-pycharm except that the repository you will be creating is not a fork. It should be called `azul-docker-elasticsearch`."

**Comment by hannes-ucsc** [comment]
For demo, show absence of old repository in ECR in a lower deployment. Show presence of new repository. Show Inspector findings for new repository.

Edit: @hannes-ucsc: "Show evidence that the new image is being used for the unit tests on GitLab."
