### ISSUE TITLE
Keep `docker` Docker images updated

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5298]
Every six months or when critical or high CVE findings make it necessary, the operator will file a PR that updates Azul to the latest version of `docker.io/library/docker:${version}` and `docker.io/library/docker:${version}-dind`.

**Comment by hannes-ucsc** [comment]
Need to create reminder, first.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Reminder should link back to this ticket."

**Comment by achave11-ucsc** [comment]
Done.
Notification repeats every six months.
<img width="1141" alt="Screen Shot 2023-06-14 at 11 14 01 AM" src="https://github.com/DataBiosphere/azul/assets/19215510/11e338d3-b109-4ec2-8f77-51ee31e296d2">

**Comment by hannes-ucsc** [comment]
For demo, in any main deployment, show the updated base images in ECR  and their vulnerabilities in Inspector. Show the executor image in the GitLab registry. Run `docker version` inside a container for the executor image. Show that the GitLab instance is running the updated dind image.

**Comment by hannes-ucsc** [comment]
Made obsolete by DataBiosphere/azul#5703.
