### ISSUE TITLE
Keep Python updated

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5299]
Every three months, or when critical/high CVEs make it necessary, the operator creates a PR that 

1) updates the Python docker image (docker.io/library/python) and 
2) keeps other non-docker references to Python consistent

These PR will always have upgrade instructions and will always requiring redeploying shared.

We always specify the Python version to the patch level.

Here's an [example commit](https://github.com/DataBiosphere/azul/commit/acfc8fd5cac9d27885a82e7119fa235f071580af#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557) for updating Python, the most recent one.

**Comment by hannes-ucsc** [comment]
Need to create reminder, first.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Reminder should link back to this ticket."

**Comment by achave11-ucsc** [comment]
Done.
Repeats every three months, on the first Monday.
<img width="1170" alt="Screen Shot 2023-06-14 at 11 06 14 AM" src="https://github.com/DataBiosphere/azul/assets/19215510/46f8f1b7-c52a-41b5-af5a-5bd43b69f0b2">

**Comment by hannes-ucsc** [comment]
Made obsolete by #5703.
