### ISSUE TITLE
Set up Staging Deployment

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#53]
We need to set up Staging Deployment for Orange (index, web service, UI)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-51)
┆Project Name: azul
┆Issue Number: AZUL-51
┆Epic: Setup HCA environments

**Comment by hannes-ucsc** [comment]
https://service.staging.explore.data.humancellatlas.org/

Note the absence of `/api` in the path.
