### ISSUE TITLE
Bundles without specimens fail to be indexed

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#530]
```
'organ': KeyError
Traceback (most recent call last):
  File "/var/task/app.py", line 105, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 209, in write
    indexer.write(documents_by_id, conflict_retry_limit=0, error_retry_limit=0)
  File "/var/task/azul/indexer.py", line 99, in write
    aggregates = self._aggregate_docs(originals)
  File "/var/task/azul/indexer.py", line 110, in _aggregate_docs
    aggregate_doc = transformer.aggregate_document(doc)
  File "/var/task/azul/transformer.py", line 554, in aggregate_document
    contents[entity_type] = aggregator.aggregate(contents[entity_type])
  File "/var/task/azul/transformer.py", line 511, in aggregate
    group_keys = self._group_keys(entity)
  File "/var/task/azul/project/hca/transformers.py", line 252, in _group_keys
    return entity['organ']
KeyError: 'organ'
```
preceded in the logs by

```
Attempt 10 of writing document files/48c28556-9fc9-490b-bc97-062e66d01be7 from bundle da4df007-d468-4a2b-b7e2-943499f4fd5e, version 2018-10-11T221017.544395Z
```

and 

```
Attempt 10 of writing document files/58c3d06e-8795-4639-a7c4-8e191973a45b from bundle da4df007-d468-4a2b-b7e2-943499f4fd5e
```

Bundle has no specimen. Currently being discussed on Slack. Could be buggy metadata but I feel like we should handle this case more gracefully.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-342)
┆Project Name: azul
┆Issue Number: AZUL-342

**Comment by hannes-ucsc** [comment]
@daniwelter and @malloryfreeberg confirmed that this case is a metadata bug but @tburdett says that theoretically it is possible to go from `donor_organism` straight to `cell_suspension`. We should be able to handle this case.

**Comment by amarjandu** [comment]
unable to locate files or bundles, attempted to search for `KeyError` in latest reindex unable to locate errors / warnings.

**Comment by theathorn** [comment]
@hannes-ucsc : "Current re-index of prod yields no failures. implying that either issue is fixed or there are no bundles of this type in DSS prod. Latter corroborated by Amar.  Move to Icebox due to lack of repro.

**Comment by hannes-ucsc** [comment]
Not able to reproduce.
