### ISSUE TITLE
Alarm on detection of new vulnerabilities by Inspector

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5301]
When Amazon Inspector finds new critical or high vulnerabilities in any of the images in our private ECR registries, a message should be sent to the group email, and a post to the Slack notification channel should be made. 

It's difficult to be more specific here until we get our feet wet with EventBridge (blocker #4175). I have the feeling that there is not much to the blocker by itself without a concrete use case, so it may be best to tackle this and the blocker in the same PR.

**Comment by achave11-ucsc** [comment]
Implementation isn't functional: https://github.com/DataBiosphere/azul/issues/5534#issue-1897500206

**Comment by achave11-ucsc** [comment]
@dsotirho-ucsc to propose demo instructions.

**Comment by dsotirho-ucsc** [comment]
Proposed testing:
- deploy to `dev.shared`
- deploy `dev.gitlab` without running `yum update`
- Wait for AWS Inspector to detect vulnerabilities
- Confirm new findings are sent as email to the Google group

Proposed demo:
- Show an email sent to the Google group for a new AWS Inspector finding on `prod`.

**Comment by hannes-ucsc** [comment]
For demo, show that we received such a notification. If two weeks have passed since this landed in the lower deployments, something must still be off. I expect to get a constant trickle of vulnerabilities.

**Comment by dsotirho-ucsc** [comment]
Demoed. See https://github.com/DataBiosphere/azul/issues/5612 and https://github.com/DataBiosphere/azul/issues/5625 for follow-up work.
