### ISSUE TITLE
Exclude noisy events from api_unauthorized alarm

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5325]
In comment https://github.com/DataBiosphere/azul/issues/5043#issuecomment-1571408164 Hannes detailed an example of a noisy event log that should be excluded from the `api_unauathorized` alarm.

This was addressed by PR https://github.com/DataBiosphere/azul/issues/5278 , however not all noisy events were excluded from the alarm. Further modify the alarm to exclude `HeadObject` events from `cloudfront.amazonaws.com` such as the example below.

Also update the canned CloudWatch Logs Insight query in all deployments.

```
[
    {
        "@timestamp": "2023-06-15 21:43:37.732",
        "@message": {
            "eventVersion": "1.08",
            "userIdentity": {
                "type": "AWSService",
                "invokedBy": "cloudfront.amazonaws.com"
            },
            "eventTime": "2023-06-15T21:40:50Z",
            "eventSource": "s3.amazonaws.com",
            "eventName": "HeadObject",
            "awsRegion": "us-east-1",
            "sourceIPAddress": "cloudfront.amazonaws.com",
            "userAgent": "cloudfront.amazonaws.com",
            "errorCode": "AccessDenied",
            "errorMessage": "Access Denied",
            "requestParameters": {
                "bucketName": "cc-dev.singlecell.gi.ucsc.edu",
                "Host": "cc-dev.singlecell.gi.ucsc.edu.s3.us-east-1.amazonaws.com",
                "key": "wp-content/"
            },
            "responseElements": null,
            "additionalEventData": {
                "SignatureVersion": "SigV4",
                "CipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
                "bytesTransferredIn": 0,
                "AuthenticationMethod": "AuthHeader",
                "x-amz-id-2": "Cmk6FWPkq6Cd1uElDFgKfWCavOFOK+2sDyJ48+1zRabI79EhTdbMSytVf8sHYh74uy2fGHfnnB0=",
                "bytesTransferredOut": 243
            },
            "requestID": "SV1RQKXY17NVZ6SS",
            "eventID": "66491450-89d3-4932-a33e-cf9ac1936aea",
            "readOnly": true,
            "resources": [
                {
                    "type": "AWS::S3::Object",
                    "ARN": "arn:aws:s3:::[cc-dev.singlecell.gi.ucsc.edu/wp-content/](http://cc-dev.singlecell.gi.ucsc.edu/wp-content/)"
                },
                {
                    "accountId": "122796619775",
                    "type": "AWS::S3::Bucket",
                    "ARN": "arn:aws:s3:::[cc-dev.singlecell.gi.ucsc.edu](http://cc-dev.singlecell.gi.ucsc.edu/)"
                }
            ],
            "eventType": "AwsApiCall",
            "managementEvent": false,
            "recipientAccountId": "122796619775",
            "sharedEventID": "f70f993f-e073-4c27-bf89-0d40b5bafda4",
            "eventCategory": "Data"
        }
    }
]
```

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … ~affect monitoring of the system~ https://github.com/DataBiosphere/azul/issues/5325#issuecomment-1610643463
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Security review: This change suppresses alarms for expected and unavoidable unauthorized error that are caused by third-parties scanning the application's UI for signatures of commonly known vulnerable web applications. We have to reject these requests in this way and we don't control these third parties. Our only recourse is to suppress alarms triggered by this specific pattern of abuse by 3rd parties. This increases our security posture by eliminating noise, strengthening the signal/noise ratio and increasing the team's sensitivity to **unexpected** unauthorized errors.

**Comment by hannes-ucsc** [comment]
For demo, show that no noisy alarms were triggered in the week prior to the demo.
