### ISSUE TITLE
Assign monthly milestones to vulnerability findings

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5339]
Retroactively apply [mitigation milestones](https://github.com/DataBiosphere/azul-private/issues/87) to any issues that reflect Invicti, SNYK, dependabot or AWS Inspector findings. Create milestones for the next 12 months in advance.

**Comment by dsotirho-ucsc** [comment]
Created monthly [milestones](https://app.zenhub.com/workspaces/team-boardwalk-5d680d7e3eeb5f1bbdf5668f/milestones) for July 2023 (`Compliance mitigation 23/07`) through June 2024 (`Compliance mitigation 24/06`)

Milestones were assigned to these existing GitHub issues:
- https://github.com/DataBiosphere/azul-private/issues/15
- https://github.com/DataBiosphere/azul-private/issues/17
- https://github.com/DataBiosphere/azul-private/issues/18

Milestones were not assigned to these GitHub issues:
- https://github.com/DataBiosphere/azul-private/issues/14
    - Issue was resolved with the completion of the blocking tickets
- https://github.com/DataBiosphere/azul-private/issues/16
    - Issue was resolved with the completion of the blocking tickets
- https://github.com/DataBiosphere/azul-private/issues/33
    - Issue is marked `wontfix`
- https://github.com/DataBiosphere/azul-private/issues/35
    - Issue is marked `wontfix`
- https://github.com/DataBiosphere/azul-private/issues/34
    - Issue already in `AnVIL Public Release` milestone
- https://github.com/DataBiosphere/azul-private/issues/36
    - Issue already in `AnVIL Public Release` milestone

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We also need to include other POAM findings of high and medium severity."

**Comment by dsotirho-ucsc** [comment]
Assigned milestones to `poam 2023` labeled tickets.

### Compliance mitigation 23/07

- https://github.com/DataBiosphere/azul/issues/4997
- https://github.com/DataBiosphere/azul/issues/5292
- https://github.com/DataBiosphere/azul/issues/5282
- https://github.com/DataBiosphere/azul/issues/5280

### Compliance mitigation 23/09

- https://github.com/DataBiosphere/azul-private/issues/84
- https://github.com/DataBiosphere/azul/issues/5297
- https://github.com/DataBiosphere/azul/issues/5296
- https://github.com/DataBiosphere/azul/issues/5299
- https://github.com/DataBiosphere/azul/issues/5298
- https://github.com/DataBiosphere/azul-private/issues/133
- https://github.com/DataBiosphere/azul/issues/5301
- https://github.com/DataBiosphere/azul/issues/5294
- https://github.com/DataBiosphere/azul/issues/5293
