### ISSUE TITLE
PR checklist item isn't congruent when deleting PR branches

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5342]
https://github.com/DataBiosphere/azul/blame/32e2102e208af00ed04a39893a7b3ee03ee4e907/.github/pull_request_template.md#L151C15-L151C48

Requests that the branch be deleted from the `anvilprod` deployment, but the PR branch is never pushed to that deployment to run as sanbox build.

https://github.com/DataBiosphere/azul/blame/32e2102e208af00ed04a39893a7b3ee03ee4e907/.github/pull_request_template.md#L100C8-L112C8

**Comment by hannes-ucsc** [comment]
This will be made obsolete by #5370.
