### ISSUE TITLE
Make dcp29 the default catalog on production

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5351]

**Comment by bvizzier-ucsc** [comment]
Please hold work on this until further notice.  

It appears there is some confusion on the dataset review side.

**Comment by achave11-ucsc** [comment]
https://humancellatlas.slack.com/archives/C9XD6L0AD/p1686954473848839

**Comment by bvizzier-ucsc** [comment]
dcp29 has been approved for release:  https://humancellatlas.slack.com/archives/C9XD6L0AD/p1687981010768359?thread_ts=1687965154.556919&cid=C9XD6L0AD
