### ISSUE TITLE
Improve caching of DRS and TDR clients

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5357]
```diff
Subject: [PATCH] [r u] Index AnVIL snapshots from TDR dev in `anvildev` and `anvilbox` (#5283)
---
Index: src/azul/plugins/repository/tdr.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/repository/tdr.py b/src/azul/plugins/repository/tdr.py
--- a/src/azul/plugins/repository/tdr.py	(revision 4da2f05716818ddbd42b8d85329f9932a5358486)
+++ b/src/azul/plugins/repository/tdr.py	(date 1687974216095)
@@ -29,6 +29,7 @@
     cache_per_thread,
     config,
     require,
+    cache,
 )
 from azul.auth import (
     Authentication,
@@ -101,6 +102,7 @@
     def sources(self) -> Set[TDRSourceSpec]:
         return self._sources
 
+    @cache
     def _user_authenticated_tdr(self,
                                 authentication: Optional[Authentication]
                                 ) -> TDRClient:
@@ -219,6 +221,7 @@
     def _emulate_bundle(self, bundle_fqid: TDRBundleFQID) -> TDRBundle:
         raise NotImplementedError
 
+    @cache
     def drs_client(self,
                    authentication: Optional[Authentication] = None
                    ) -> DRSClient:
Index: src/azul/drs.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/drs.py b/src/azul/drs.py
--- a/src/azul/drs.py	(revision 4da2f05716818ddbd42b8d85329f9932a5358486)
+++ b/src/azul/drs.py	(date 1687974943791)
@@ -119,11 +119,6 @@
 
 class IdentifiersDotOrgClient:
 
-    @classmethod
-    @cache
-    def instance(cls) -> 'IdentifiersDotOrgClient':
-        return cls()
-
     def prefix_to_host(self, prefix: str) -> mutable_furl:
         namespace_id = self._prefix_to_namespace(prefix)
         log.info('Resolved prefix %r to namespace ID %r', prefix, namespace_id)
@@ -169,9 +164,9 @@
 class DRSClient:
     http_client: urllib3.PoolManager
 
-    @property
+    @cached_property
     def id_client(self) -> IdentifiersDotOrgClient:
-        return IdentifiersDotOrgClient.instance()
+        return IdentifiersDotOrgClient()
 
     def get_object(self,
                    drs_uri: str,
Index: src/azul/plugins/__init__.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/plugins/__init__.py b/src/azul/plugins/__init__.py
--- a/src/azul/plugins/__init__.py	(revision 4da2f05716818ddbd42b8d85329f9932a5358486)
+++ b/src/azul/plugins/__init__.py	(date 1687973732377)
@@ -1,3 +1,4 @@
+import importlib
 from abc import (
     ABCMeta,
     abstractmethod,
@@ -11,7 +12,6 @@
 from enum import (
     Enum,
 )
-import importlib
 from inspect import (
     isabstract,
 )
@@ -586,7 +586,11 @@
     def drs_client(self,
                    authentication: Optional[Authentication] = None
                    ) -> DRSClient:
-        return DRSClient(http_client=http_client())
+        return DRSClient(http_client=self._http_client)
+
+    @cached_property
+    def _http_client(self):
+        return http_client()
 
     @abstractmethod
     def file_download_class(self) -> Type['RepositoryFileDownload']:
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Waiting for #5155 to land before cleaning up the patch and adding description.

**Comment by hannes-ucsc** [comment]
Patch doesn't apply cleanly anymore. We're not experiencing performance issues related to DRS or TDR client at the moment so this can wait.

**Comment by nadove-ucsc** [comment]
> We're not experiencing performance issues related to DRS or TDR client at the moment

[Current findings](https://github.com/DataBiosphere/azul/issues/5459#issuecomment-1672746693) indicate otherwise.

**Comment by nadove-ucsc** [comment]
For demo, compare the average latency of the `/repository/files` endpoint on `anvildev` from before and after this PR is merged. It should be faster now. It may be appropriate to wait a week or two after merging to accumulate sufficient data.

[edit @hannes-ucsc] There may be no measurable difference. Also discuss whether it makes sense to cache [_drs_client](https://github.com/DataBiosphere/azul/commit/ebe8d4fb90a522226a78512ba4400e4e65268425#diff-d06c277d463ade91d3f16bb7571c09b7ebb04a00d52e9f0264de2a3ca5da00bfR189) if the method it calls is already cached.
