### ISSUE TITLE
Track replica hub IDs

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5360]
[3/3] https://github.com/DataBiosphere/azul/issues/4942#issuecomment-1612106651

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by nadove-ucsc** [comment]
Seems potentially useful? https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-update.html#upserts

**Comment by hannes-ucsc** [comment]
For demo, use Kibana to show the `hub_ids` property in replica documents in `anvilprod` and, at a later demo, in `prod`. Show that the hubs are files. Make a query for replicas by `hub_id`. Pick a file and show that the list of hubs is complete, pick a hub and show that the set of files referring to it as their hub is complete. This may require some thinking and preparation and will probably involve running some queries in the BQ console.

**Comment by hannes-ucsc** [comment]
PR was reverted.

https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1708675442093639

**Comment by nadove-ucsc** [comment]
This part was demoed: 

> Show that the hubs are files. Make a query for replicas by hub_id.

**Comment by nadove-ucsc** [comment]
Assignee to make remaining demo instructions more concrete.

**Comment by hannes-ucsc** [comment]
We will drop the remaining demo instructions. We can satisfy them more easily when we have the JSONL manifest (#6028).  We are currently refining the demo criteria on the PR for that issue:

https://github.com/DataBiosphere/azul/pull/6029#issuecomment-2023829741

**Comment by hannes-ucsc** [comment]
I decided not to complicate the demo instructions for #6028

The [results](https://github.com/DataBiosphere/azul/pull/6029#issuecomment-2029111257) of the experiments on PR #6029 for that issue are sufficient.
