### ISSUE TITLE
AWS alleges recursive Lambda invocations

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5368]
We got this message with the subject line 

> [Action Required] Recursive loops are detected in your AWS Account [AWS Account: 289950828509] [US-EAST-1]

from AWS this on Fri, Jun 30, 12:53 AM (3 days ago).

> Hello,
> 
> You are receiving this notification because you have one or more Lambda functions in the US-EAST-1 Region that are being invoked in a recursive loop with other AWS resources.
> 
> Starting June 26, 2023, AWS Lambda is launching recursive loop detection. With this launch, Lambda will stop recursive invocations between Amazon SQS, AWS Lambda, and Amazon SNS after 16 recursive calls. If a function is invoked by the same triggering event more than 16 times, Lambda will stop the next invocation and send the event to a Dead-Letter Queue or on-failure destination, if configured.
> 
> The following are your affected Lambda function ARN(s);
> arn:aws:lambda:us-east-1:289950828509:function:azul-indexer-nadove5-aggregate
> arn:aws:lambda:us-east-1:289950828509:function:azul-indexer-anvildev-aggregate
> 
> 
> What do I need to do?
> To prevent potential disruptions to your account, we have turned off recursive loop detection for your AWS account so that you can investigate these recursive functions. Please review your functions and their trigger configurations to identify any unintentional recursive patterns.
> 
> If your account has functions that intentionally use recursive patterns, no further action on your part is required. To learn more about recursive loop detection, please refer to Lambda documentation[1].
> 
> If your recursive patterns are unintentional, you can press the “Throttle” button in the Lambda console to scale the funtion concurrency down to zero and break the recursive cycle. Please contact AWS Support [2] in order to turn on recursive loop detection for your AWS Account.
> 
> [1] https://docs.aws.amazon.com/lambda/latest/dg/invocation-recursion.html
> [2] https://aws.amazon.com/support
> 
> Sincerely,
> Amazon Web Services
> 
> Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210
> 
> ---
> Reference: https://phd.aws.amazon.com/phd/home?region=us-east-1#/event-log?eventID=arn:aws:health:us-east-1::event/LAMBDA/AWS_LAMBDA_OPERATIONAL_NOTIFICATION/AWS_LAMBDA_OPERATIONAL_NOTIFICATION_39a878245b94a5af112a38f53bf41656bfe65c2b1c33b5eed43ede179081db7c&amp;eventTab=details
> 
> -- 
> You received this message because you are subscribed to the Google Groups "platform-anvil-dev" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to [platform-anvil-dev-group+unsubscribe@ucsc.edu](mailto:platform-anvil-dev-group%2Bunsubscribe@ucsc.edu).
> To view this discussion on the web visit https://groups.google.com/a/ucsc.edu/d/msgid/platform-anvil-dev-group/010001890b4aa620-ab11dfe7-8f9c-4614-816f-f63c6dc11ced-000000%40email.amazonses.com.
> For more options, visit https://groups.google.com/a/ucsc.edu/d/optout.

We also received a similar message for `platform-anvil-prod` with the subject line 

> [Action Required] Recursive loops are detected in your AWS Account [AWS Account: 465330168186] [US-EAST-1]

at the same time.

> Hello,
> 
> You are receiving this notification because you have one or more Lambda functions in the US-EAST-1 Region that are being invoked in a recursive loop with other AWS resources.
> 
> Starting June 26, 2023, AWS Lambda is launching recursive loop detection. With this launch, Lambda will stop recursive invocations between Amazon SQS, AWS Lambda, and Amazon SNS after 16 recursive calls. If a function is invoked by the same triggering event more than 16 times, Lambda will stop the next invocation and send the event to a Dead-Letter Queue or on-failure destination, if configured.
> 
> The following are your affected Lambda function ARN(s);
> arn:aws:lambda:us-east-1:465330168186:function:azul-indexer-anvilprod-aggregate
> 
> 
> What do I need to do?
> To prevent potential disruptions to your account, we have turned off recursive loop detection for your AWS account so that you can investigate these recursive functions. Please review your functions and their trigger configurations to identify any unintentional recursive patterns.
> 
> If your account has functions that intentionally use recursive patterns, no further action on your part is required. To learn more about recursive loop detection, please refer to Lambda documentation[1].
> 
> If your recursive patterns are unintentional, you can press the “Throttle” button in the Lambda console to scale the funtion concurrency down to zero and break the recursive cycle. Please contact AWS Support [2] in order to turn on recursive loop detection for your AWS Account.
> 
> [1] https://docs.aws.amazon.com/lambda/latest/dg/invocation-recursion.html
> [2] https://aws.amazon.com/support
> 
> Sincerely,
> Amazon Web Services
> 
> Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210
 
---

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Spike to investigate. Is this a valid concern? If so, what needs to change? Otherwise, how do we prevent these messages in the future.

**Comment by nadove-ucsc** [comment]
> Spike to investigate. Is this a valid concern?

From the docs linked from the original message:

> Recursive loop detection in Lambda works by tracking events ... If your function is invoked more than 16 times in the same chain of requests, then Lambda automatically stops the next function invocation in that request chain and notifies you. 

This implies that recursion is only detected when the Lambda is invoked.

From the message itself:

> Starting June 26, 2023, AWS Lambda is launching recursive loop detection. 

`nadove5-aggregate` has not been invoked since June 22nd ([metric](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2?graph=~(period~60~metrics~(~(~'AWS*2fLambda~'Invocations~'FunctionName~'azul-indexer-nadove5-aggregate~(stat~'Sum~region~'us-east-1)))~region~'us-east-1~title~'Invocations~start~'-PT336H~end~'P0D))). Therefore, this cannot be a valid concern because there have been no events to track.

**Comment by nadove-ucsc** [comment]
> how do we prevent these messages in the future.

From the message:

> To prevent potential disruptions to your account, we have turned off recursive loop detection for your AWS account so that you can investigate these recursive functions.

I think this means no action is needed, unless it becomes important for us to re-enable recursion detection.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "I'd like to gather more evidence that this is indeed unproblematic. I would also like to ask AWS Support about the [contradiction](https://github.com/DataBiosphere/azul/issues/5368#issuecomment-1619542234) Noa points out."

**Comment by hannes-ucsc** [comment]
> Hello,
> 
> You are receiving this notification because you have one or more Lambda functions in the US-EAST-1 Region that are being invoked in a recursive loop with other AWS resources.
> 
> Starting June 26, 2023, AWS Lambda is launching recursive loop detection. With this launch, Lambda will stop recursive invocations between Amazon SQS, AWS Lambda, and Amazon SNS after 16 recursive calls. If a function is invoked by the same triggering event more than 16 times, Lambda will stop the next invocation and send the event to a Dead-Letter Queue or on-failure destination, if configured.
> 
> The following are your affected Lambda function ARN(s);
> arn:aws:lambda:us-east-1:465330168186:function:azul-indexer-anvilprod-aggregate
> 
> 
> What do I need to do?
> To prevent potential disruptions to your account, we have turned off recursive loop detection for your AWS account so that you can investigate these recursive functions. Please review your functions and their trigger configurations to identify any unintentional recursive patterns.
> 
> If your account has functions that intentionally use recursive patterns, no further action on your part is required. To learn more about recursive loop detection, please refer to Lambda documentation[1].
> 
> If your recursive patterns are unintentional, you can press the “Throttle” button in the Lambda console to scale the funtion concurrency down to zero and break the recursive cycle. Please contact AWS Support [2] in order to turn on recursive loop detection for your AWS Account.
> 
> [1] https://docs.aws.amazon.com/lambda/latest/dg/invocation-recursion.html
> [2] https://aws.amazon.com/support
> 
> Sincerely,
> Amazon Web Services
> 
> Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210
> 
> ---
> Reference: https://phd.aws.amazon.com/phd/home?region=us-east-1#/event-log?eventID=arn:aws:health:us-east-1::event/LAMBDA/AWS_LAMBDA_OPERATIONAL_NOTIFICATION/AWS_LAMBDA_OPERATIONAL_NOTIFICATION_39a878245b94a5af112a38f53bf41656bfe65c2b1c33b5eed43ede179081db7c&amp;eventTab=details
>

**Comment by hannes-ucsc** [comment]
After some back and forth with Amazon, I determined that this is mostly Amazon crying wolf. There is not enough tooling to investigate the alleged loops and the metric that tracks invocations dropped for this reason is useless since it only covers two weeks worth of time.

AWS support did turn loop detection off in `platform-anvil-prod` in response to my support ticket. Operator to request the same in the three other accounts.

**Comment by dsotirho-ucsc** [comment]
Support cases opened:
- platform-hca-dev: Case ID 13287408551
- platform-hca-prod: Case ID 13287435511
- platform-anvil-dev: Case ID 13287450171

**Comment by dsotirho-ucsc** [comment]
Assignee to ask Erich if there is a difference in support level between `platform-hca-prod` and `platform-hca-dev`.

**Comment by dsotirho-ucsc** [comment]
The three support cases have now been closed.
Positive feedback was left for the `platform-hca-prod` support ticket for being promptly handled, and after confirming with Erich that we have the same `Enterprise` level support on all four AWS accounts, constructive feedback was given for the `…hca-dev` and `…anvil-dev` support tickets for the slow response time they received.
