### ISSUE TITLE
IT fails when only supplementary bundles are indexed from a source

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5381]
This was observed while running IT for https://github.com/DataBiosphere/azul/pull/5378 using the `anvilprod` snapshots.
I didn't record the seed; the cause of the error was inferred by analyzed the state of the `anvil-it` catalog after running the IT with `delete = False`. 

During this IT run, no primary bundles were indexed for 2 sources. This caused those sources not to occur anywhere in the response from the `/index/biosamples` endpoint, which the `_test_managed_access_indices` method uses to determine the set of expected indexed bundles. The fix is to replace the calls to `_get_entities` in this method with `_get_indexed_bundles`, which correctly returns both primary supplementary bundles.

**Comment by dsotirho-ucsc** [comment]
To be solved together with #4398 in PR #5378.
