### ISSUE TITLE
Harden Azul build image

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5388]
Currently the docker file does not run `apt update` or `apt upgrade`.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We also need to investigate the discrepancy between Inspector and SNYK:"
<img width="975" alt="Screen Shot 2023-07-12 at 11 52 10 AM" src="https://github.com/DataBiosphere/azul/assets/46407464/ba42b9b0-fe3e-4f7f-8879-25f6905f20cd">
<img width="620" alt="Screen Shot 2023-07-12 at 11 53 26 AM" src="https://github.com/DataBiosphere/azul/assets/46407464/501ac1ee-5f68-4cfc-a138-bb31e6996604">

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Turns out that SNYK has not caught up with our latest changes to the Dockerfile, yet. We are on 3.9.17 of the base image whereas SNYK thinks we are on 3.9.12. We will disable SNYK scanning of our Dockerfile once #5301 (Alarm on detection of new vulnerabilities by Inspector) lands."

<img width="1423" alt="Screen Shot 2023-07-13 at 11 56 28 AM" src="https://github.com/DataBiosphere/azul/assets/46407464/67e35358-f000-470a-a1a4-e2c5836e7a1a">

**Comment by hannes-ucsc** [comment]
For demo, show how to upgrade OS packages in the image. Make sure that we have a ticket reminding us to do so periodically.
