### ISSUE TITLE
Index new AnVIL CMG snapshots

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5392]
In `anvilprod`, index all snapshots whose name starts with `ANVIL_CMG` or `ANVIL_cmg` in the [spreadsheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274). A *new* snapshot is one that we currently don't index. Note that at least one of those snapshots supersedes another one that we may already index.

Do this in a new catalog called `anvil1` and make that catalog the default but leave the current `anvil` catalog in place.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Incorporation these new snapshots may require changes to the indexer code. We have not been informed of any significant structural changes compared to previous CMG snapshots but we won't know for sure until we attempt to index. There have been unannounced structural changes in snapshots in the past.

I think we should do this spike as a PR that we take as far as merging into develop and deploying to `anvilprod`. Structural changes will likely be exposed as indexing failures in the author's personal deployment. If there aren't any, then the resulting estimate for this issue will be 0. Otherwise, we'll revert the merge (if we did merge the PR) and the estimate will reflect the implementation effort need to absorb the structure changes.

**Comment by hannes-ucsc** [comment]
For demo, show new datasets and files in the browser UI (https://prod.anvil.gi.ucsc.edu/explore/datasets). Download a file from a new dataset.

**Comment by nadove-ucsc** [comment]
![image](https://github.com/DataBiosphere/azul/assets/48401926/19ae2a03-f962-4d19-9e9c-9ff0a1f8a723)

**Comment by nadove-ucsc** [comment]
We thought that the demo failed due to errors in the Data Browser. But now I think the error may have been expected as the [demo instructions for the previous snapshots update](https://github.com/DataBiosphere/azul/issues/5155#issuecomment-1649194817) explicitly said that the Data Browser was broken and could not be used to test the file download.

**Comment by achave11-ucsc** [comment]
Waiting for an answer to https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1691606153171859.

**Comment by achave11-ucsc** [comment]
@nadove-ucsc: "The file download button isn't intended to be working, so the error we observed during the demo does not indicate a problem. At the next demo, use `curl` and the swagger UI to download the file as [was done for the previous ticket](https://github.com/DataBiosphere/azul/issues/5155#issuecomment-1649194817)."

**Comment by bvizzier-ucsc** [comment]
Concerning the demo... The system will require support for requester-pays to support data egress file download. 

There is a suggestion that we support the download of files below a "To Be Determined" file size that would be billed to AnVIL.  [Slack discussion link.](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1691630228958769)

For the short term, the Data Browser will disable the file download option.
