### ISSUE TITLE
Index new AnVIL GTEx snapshots

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5393]
In `anvilprod`, index all *new* snapshots whose name starts with `ANVIL_GTEx` in the [spreadsheet](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?pli=1#gid=187179274). A *new* snapshot is one that we currently don't index. Note that at least one of those snapshots supersedes another one that we may already index.

Do this in catalog `anvil1`.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Incorporation these new snapshots may require changes to the indexer code. We have not been informed of any significant structural changes compared to previous CMG snapshots but we won't know for sure until we attempt to index. There have been unannounced structural changes in snapshots in the past.

**Comment by hannes-ucsc** [comment]
Incorporation these new snapshots may require changes to the indexer code. We have not been informed of any significant structural changes compared to previous CMG snapshots but we won't know for sure until we attempt to index. There have been unannounced structural changes in snapshots in the past.

**Comment by hannes-ucsc** [comment]
Incorporation these new snapshots may require changes to the indexer code. We have not been informed of any significant structural changes compared to previous CMG snapshots but we won't know for sure until we attempt to index. There have been unannounced structural changes in snapshots in the past.

I think we should do this spike as a PR that we take as far as merging into develop and deploying to `anvilprod`. Structural changes will likely be exposed as indexing failures in the author's personal deployment. If there aren't any, then the resulting estimate for this issue will be 0. Otherwise, we'll revert the merge (if we did merge the PR) and the estimate will reflect the implementation effort need to absorb the structure changes.

**Comment by nadove-ucsc** [comment]
For demo, show the updated GTEx snapshots in the anvilprod Data Browser.
