### ISSUE TITLE
Retain 'anvil_' prefixes for the Findability Subset table names

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5417]
Request from the Broad:

Retain 'anvil_' prefixes for the Findability Subset table names.

- Expected table name prefixes would flow through from TDR to Explorer to user workspace. 
- It would be useful from the user perspective and notebook usability to make this change on the Explorer side.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "@mikebaumann, we weren't planning on removing the table name prefix during verbatim handover. If you are under the impression that we would, could you chime in here, please. Otherwise, we would be closing this ticket."

**Comment by mbaumann-broad** [comment]
@dsotirho-ucsc @hannes-ucsc 
> we weren't planning on removing the table name prefix during verbatim handover.

By "verbatim handover" are you referring to current handover behavior or the full PFB handover still to be implemented?

Clearly the current handover behavior results in the `anvil_` prefix on the Findability Subset table names being removed when those tables are exported as PFB and imported to a Terra user workspace, as shown in the images below:

Terra Data Repo:    
<img width="550" alt="terraDataRepoTableNames" src="https://github.com/DataBiosphere/azul/assets/84099036/49545650-3224-492e-82d4-8db75435eb31">

Terra Workspace After Handoff/Import:  
<img width="554" alt="terraWorkspaceTableNames" src="https://github.com/DataBiosphere/azul/assets/84099036/66b0e0cd-804b-473c-b398-d4a6cebc11dd">

This undesirable difference was discussed in a Broad/UCSC Weekly Standup meetings months ago, soon after the `anvil_` prefix was added to the FS table names in the TDR schema.

**Comment by hannes-ucsc** [comment]
> By "verbatim handover" are you referring to current handover behavior or the full PFB handover still to be implemented?

The current handover is not verbatim. *Verbatim handover* is referring to the one we are currently working on, which will replace the current hand-over. We treat terms *full* and *verbatim* as synonyms.

For the verbatim hand-over we're planning on retaining the table names as they are in the snapshot. I don't think we'll spend time in addressing this in the current hand-over. Feel free to reopen if you disagree, @mikebaumann.

> This undesirable difference was discussed in a Broad/UCSC Weekly Standup meetings months ago, soon after the anvil_ prefix was added to the FS table names in the TDR schema.

I remember this vaguely. Apologies, the PM at the time should have created an issue.

**Comment by mbaumann-broad** [comment]
Thank you for the clarification, @hannes-ucsc.
That sounds right to me. I would rather see time/effort go into developing the full/verbatim handover than make changes to the current interim handover.
Much appreciated!
