### ISSUE TITLE
Azul rejects OAuth tokens from `gcloud`

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5420]
# Expected behavior

OAuth 2.0 access tokens generated using `gcloud auth print-access-token` can be used to authenticate with the Azul REST API. This is a pattern I've been using for years:

```
$ gcloud auth login
...
$ curl -X 'GET'   'https://service.dev.singlecell.gi.ucsc.edu/index/summary'   -H 'accept: application/json'   -H "Authorization: Bearer $(gcloud auth print-access-token)"
{"projectCount": ...
```

# Observed behavior

Azul now rejects credentials generated in this manner.

```
$ gcloud auth login
...
$ curl -X 'GET'   'https://service.dev.singlecell.gi.ucsc.edu/index/summary'   -H 'accept: application/json'   -H "Authorization: Bearer $(gcloud auth print-access-token)"
{"Code":"UnauthorizedError","Message":"Invalid credentials"}
```

# Analysis

When I tried to use the token locally, I observed this exception:

```
>>> from azul.terra import TDRClient
>>> from azul.auth import OAuth2
>>> TDRClient.for_registered_user(OAuth2('<TOKEN-REDACTED>'))
Invalid credentials
Traceback (most recent call last):
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/terra.py", line 658, in for_registered_user
    self.validate()
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/oauth2.py", line 142, in validate
    require(project_id == authorized_project_id,
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/__init__.py", line 1724, in require
    reject(not condition, *args, exception=exception)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/__init__.py", line 1743, in reject
    raise exception(*args)
azul.RequirementError: OAuth 2.0 client project does not match
Traceback (most recent call last):
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/terra.py", line 658, in for_registered_user
    self.validate()
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/oauth2.py", line 142, in validate
    require(project_id == authorized_project_id,
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/__init__.py", line 1724, in require
    reject(not condition, *args, exception=exception)
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/__init__.py", line 1743, in reject
    raise exception(*args)
azul.RequirementError: OAuth 2.0 client project does not match

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nadove/PycharmProjects/azul-sc/src/azul/terra.py", line 661, in for_registered_user
    raise UnauthorizedError('Invalid credentials')
chalice.app.UnauthorizedError: Invalid credentials
```

The failed requirement is [here](https://github.com/DataBiosphere/azul/blob/599937e2ad609941c56119781d91be420d51cb2a/src/azul/oauth2.py#L142). 

With this patch:

```
Subject: [PATCH] changes
---
Index: src/azul/oauth2.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/azul/oauth2.py b/src/azul/oauth2.py
--- a/src/azul/oauth2.py	(revision 032c401523b9f489906fd41f7423a5296c95a266)
+++ b/src/azul/oauth2.py	(date 1690343594202)
@@ -140,7 +140,8 @@
                 project_id = self._project_id_from_client_id(config.google_oauth2_client_id)
                 authorized_project_id = self._project_id_from_client_id(authorized_party)
                 require(project_id == authorized_project_id,
-                        'OAuth 2.0 client project does not match')
+                        'OAuth 2.0 client project does not match',
+                        project_id, authorized_project_id)
             elif email is not None and email.endswith('.iam.gserviceaccount.com'):
                 # A service account's bare access token
                 require(token_info['email_verified'] == 'true',

```

The `RequirementError` becomes:

```
azul.RequirementError: ('OAuth 2.0 client project does not match', '1055427471534', '32555940559.apps.googleusercontent.com')
```

The `project_id` of 1055427471534 corresponds to `platform-anvil-prod`. The `authorized_project_id` of '32555940559.apps.googleusercontent.com' corresponds to [the Google Cloud SDK](https://github.com/twistedpair/google-cloud-sdk/blob/7f4b8da8645e84f0fe4c6eb68758cda74570dd56/google-cloud-sdk/lib/googlecloudsdk/core/config.py#L183) and presumably, by extension, the `gcloud` app.

[This stackoverflow post](https://stackoverflow.com/questions/64532135/cloud-run-authentication-with-user-account) may be relevant.

**Comment by hannes-ucsc** [comment]
I don't use this approach and I don't think it's documented to be supported. I usually just steal a token from the Swagger UI. However, I see the value in it. I'd be happy to entertain the idea of supporting this use case if the solution is easy and secure. If we accept tokens minted by `gcloud auth print-access-token`, we need to make sure they are tied to the same project as the OAuth client(s) we accept tokens from.

For demo, show that `_select dev && gcloud auth print-access-token` is accepted by the Azul service in `dev`, but not in `anvildev`.

**Comment by hannes-ucsc** [comment]
> If we accept tokens minted by gcloud auth print-access-token, we need to make sure they are tied to the same project as the OAuth client(s) we accept tokens from.

Reading through this again I don't think that's possible. The token from `gcloud auth print-access-token` is not tied to the GCS project of the currently selected deployment.

I think it is acceptable to grab a token from the Swagger UI, if an when needed.
