### ISSUE TITLE
Disable SNYK

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5431]
We used SNYK to scan our Dockerfiles and, for scanning Python requirements, as a fall-back for GitHub's dependabot. In our experience, the latter detects the same vulnerabilities and is more reliable. It also automatically closes its PRs when a resolution lands by some other means, in a different PR, for example. SNYK only scans the base image of our Dockerfiles and we now use ECR for that #4177. Additionally, SNYK is slow to incorporate updates to a Dockerfile, including updates to the FROM references. The current findings for that are two months old, while the FROM reference was updated three weeks ago.

For that reason we should disable SNYK scanning completely.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [ ] ~… affect authentication; for example:~ https://github.com/DataBiosphere/azul/issues/5431#issuecomment-1666244210
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] ~… affect monitoring of the system~ https://github.com/DataBiosphere/azul/issues/5431#issuecomment-1666244210
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Security review: this disables access of a 3rd party tool to our infrastructure. The scope and detail of all monitoring and scanning functionality remains the same (see description). It does involve removing a GitHub personal access token from the GitHub bot user (azul-group). Overall this change retains current level of scrutiny while disabling access by a 3rd party. It therefore does not decrease our security posture.

**Comment by hannes-ucsc** [comment]
I deleted the "SNYK project" for Azul at snyk.io and deleted the personal access token used by SNYK from the settings of the bot user (azul-group) on GH.

I don't think it is necessary that people remove SNYK from their list of authorized OAuth apps on GH.

**Comment by hannes-ucsc** [comment]
This can be closed during triage.
