### ISSUE TITLE
IT in `anvilprod` transiently fails `repository_files` subtest

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5459]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/9543#L329

```
…
2023-08-09 00:19:00,093 INFO    MainThread: Beginning sub-test [repository_files] {'catalog': 'anvil-it'}
2023-08-09 00:19:00,094 INFO    MainThread: GET https://service.prod.anvil.gi.ucsc.edu/fetch/repository/files/0210bf07-90ab-46ee-bbe5-25aff773362d?catalog=anvil-it&version=2022-06-01T00%3A00%3A00.000000Z ...
2023-08-09 00:19:29,112 INFO    MainThread: ... -> 504
2023-08-09 00:19:29,112 INFO    MainThread: Failed sub-test [repository_files] {'catalog': 'anvil-it'}
…
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='anvil-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 397, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 835, in _test_repository_files
    while response['Status'] != 302:
KeyError: 'Status'
----------------------------------------------------------------------
Ran 14 tests in 1465.376s
FAILED (errors=1, skipped=1)
make: *** [Makefile:231: integration_test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike to further diagnose the root cause of this issue.

**Comment by achave11-ucsc** [comment]
This seems to be becoming more pervasive in the `hammerbox` and `anvilprod` deployments.

https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/9618#L894
```
======================================================================
ERROR: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='anvil1-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 397, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 835, in _test_repository_files
    while response['Status'] != 302:
KeyError: 'Status'
----------------------------------------------------------------------
```

https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/9608#L419
```
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [managed_access_repository_files]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 397, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1116, in _test_managed_access
    files = self._test_managed_access_repository_files(catalog, managed_access_source_ids)
  File "/builds/ucsc/azul/test/integration_test.py", line 1226, in _test_managed_access_repository_files
    self.assertIn(response.status, (301, 302))
AssertionError: 504 not found in (301, 302)
----------------------------------------------------------------------
```

… note in `anvilprod` it seems to have also affected the `managed_access_repository_files`.

**Comment by nadove-ucsc** [comment]
This appears to be due to the latency involved in resolving the compact DRS identifiers. For example, on [one occasion](https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/9618#L894) it took 26 seconds to receive a response from identifiers.org:

```
[INFO]	2023-08-09T21:42:40.986Z	936acffb-0975-416c-80ab-d06e2de173f2	azul.drs	GET https://registry.api.identifiers.org/restApi/resources/search/findAllByNamespaceId?id=3571 …
[INFO]	2023-08-09T21:43:06.016Z	936acffb-0975-416c-80ab-d06e2de173f2	azul.drs	Obtained URL pattern 'https://data.terra.bio/ga4gh/drs/v1/objects/{$id}' from resource 'National Human Genome Research Institute'
```

**Comment by nadove-ucsc** [comment]
May be related to https://github.com/DataBiosphere/azul/issues/5357

**Comment by nadove-ucsc** [comment]
We'll start by addressing https://github.com/DataBiosphere/azul/issues/5357. Once that issue is resolved, we'll re-evaluate the frequency of these errors and decide whether additional work is needed.

**Comment by achave11-ucsc** [comment]
This happened again https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/10016.

**Comment by achave11-ucsc** [comment]
Waiting for the blocker to mature on `dev` and then collect some data on how it has affected performance.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc to review the partial caching improvements and decide on next steps.

**Comment by hannes-ucsc** [comment]
Reviewed the changes from #5357 and added a discussion item to the demo instructions by editing [this comment](https://github.com/DataBiosphere/azul/issues/5357#issuecomment-1679676429) on that issue.

**Comment by dsotirho-ucsc** [comment]
> We'll start by addressing #5357. Once that issue is resolved, we'll re-evaluate the frequency of these errors and decide whether additional work is needed.

Assignee to do that.

**Comment by achave11-ucsc** [comment]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/14158#L1236

**Comment by hannes-ucsc** [comment]
No recurrences since Oct
