### ISSUE TITLE
`test_accessions_fields` does not assert anything

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5485]
https://github.com/DataBiosphere/azul/blob/7fb38a696a70b3ce5b76287786c0feb13ede1423/test/indexer/test_indexer.py#L1416

Because the index name is actually "projects" (plural), this block never executes and no assertions are ever performed. If the pluralization issue is fixed, and the assertions execute as intended, the test fails because the orderings of the lists are different.

```
AssertionError: Lists differ: [{'namespace': 'array_express', 'accession': 'E-AAAA-00'}[224 chars]00'}] != [{'namespace': 'insdc_project', 'accession': 'SRP000000'}[224 chars]00'}]

First differing element 0:
{'namespace': 'array_express', 'accession': 'E-AAAA-00'}
{'namespace': 'insdc_project', 'accession': 'SRP000000'}

- [{'accession': 'E-AAAA-00', 'namespace': 'array_express'},
+ [{'accession': 'SRP000000', 'namespace': 'insdc_project'},
+  {'accession': 'SRP000001', 'namespace': 'insdc_project'},
   {'accession': 'GSE00000', 'namespace': 'geo_series'},
+  {'accession': 'E-AAAA-00', 'namespace': 'array_express'},
-  {'accession': 'SRP000000', 'namespace': 'insdc_project'},
-  {'accession': 'SRP000001', 'namespace': 'insdc_project'},
   {'accession': 'PRJNA000000', 'namespace': 'insdc_study'}]
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by nadove-ucsc** [comment]
`indexer` `bug` if order matters for this field and `test` `bug` if (as I suspect) it doesn't.

**Comment by nadove-ucsc** [comment]
https://github.com/DataBiosphere/azul/blob/7fb38a696a70b3ce5b76287786c0feb13ede1423/test/indexer/__init__.py#L200

Looks like we don't care about order for this field. `test` `bug`.

**Comment by dsotirho-ucsc** [comment]
> If the pluralization issue is fixed, and the assertions execute as intended, the test fails because the orderings of the lists are different.

Since the accessions values are gathered into an [OrderedSet of Accession objects](https://github.com/DataBiosphere/azul/blob/7fb38a696a70b3ce5b76287786c0feb13ede1423/src/humancellatlas/data/metadata/api.py#L336) prior to being [transformed into a list of dictionaries](https://github.com/DataBiosphere/azul/blob/7fb38a696a70b3ce5b76287786c0feb13ede1423/src/azul/plugins/metadata/hca/indexer/transform.py#L709) for indexing, an easy fix for the test failure would be to modify the test's expected values so that they occur in the same order as they do in the canned bundle source.
