### ISSUE TITLE
Optimize  Facet and Table API's - Too Much Data is coming down.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#55]
For example we are getting all files in a sample.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-48)
┆Project Name: azul
┆Issue Number: AZUL-48

**Comment by NoopDog** [comment]
I have made one request here to remove the files from the /samples response (per sample)  and replace with a summary

https://app.zenhub.com/workspace/o/databiosphere/azul/issues/170
