### ISSUE TITLE
GitLab updates cause false positive `insufficient_data` alarms

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5518]
<img width="1412" alt="Screen Shot 2023-09-11 at 12 13 24 PM" src="https://github.com/DataBiosphere/azul/assets/19215510/c6ed3a67-5e16-458a-a7ee-9db4024418df">

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … ~affect monitoring of the system~ https://github.com/DataBiosphere/azul/issues/5518#issuecomment-1741615995
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We think that relaxing the number of breaching data points from 1 to 6 will help prevent these false alarms at the cost of delaying true positives, but that's okay because the threshold is low enough to give us some cushion before we have to respond."

**Comment by hannes-ucsc** [comment]
Security review: This change reduces the chance of false positives, increasing the specificity of the alarms, thereby improving our security posture, and eliminating time spent unnecessarily on triaging false positives.

**Comment by hannes-ucsc** [comment]
For demo, terminate the GitLab instances in `dev` and `anvildev`. Turn one on 50 minutes after it was turned off, and the other 70 after. There should be one alarm for the  2nd instance and no alarm for the first.

**Comment by achave11-ucsc** [comment]
Please also include a change equivalent to the sketch below, in the PR for this issue:
```diff
Index: terraform/gitlab/gitlab.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/gitlab/gitlab.tf.json.template.py b/terraform/gitlab/gitlab.tf.json.template.py
--- a/terraform/gitlab/gitlab.tf.json.template.py	(revision e2853b0fb27fc57c5bf7ca5f32289d09a679839d)
+++ b/terraform/gitlab/gitlab.tf.json.template.py	(date 1697055803976)
@@ -1811,7 +1811,7 @@
         'aws_cloudwatch_metric_alarm': {
             **{
                 'gitlab_' + resource: {
-                    'alarm_name': 'azul-gitlab_' + resource,
+                    'alarm_name': 'azul-gitlab_' + resource + '-' + config.deployment_stage,
                     'comparison_operator': 'GreaterThanOrEqualToThreshold',
                     'datapoints_to_alarm': 6,
                     'evaluation_periods': 6,

```

**Comment by dsotirho-ucsc** [comment]
Demo results:

# GitLab `dev`

- Instance terminated @ 2:37p, confirmed @ 2:38p
- Instance recreated @ 3:28p (51 minutes after termination)
- During test the instance state did not change from `OK`
- No notifications posted to SNS

![dev-1](https://github.com/DataBiosphere/azul/assets/46407464/275f915f-b156-473e-bb82-45eb67ec5e92)

![dev-2](https://github.com/DataBiosphere/azul/assets/46407464/627d8fcb-fb16-4a86-a5ff-a90e0d329e31)

# GitLab `anvildev`

- Instance terminated @ 2:37p, confirmed @ 2:38p
- Instance state changed from `OK` to `insufficient data` @ 3:57p (79 minutes after termination)
- INSUFFICIENT_DATA notifications posted to SNS @ 3:57p
- Instance recreated @ 4:17p
- OK notifications posted to SNS @ 4:21p

![anvildev-1](https://github.com/DataBiosphere/azul/assets/46407464/54b655ea-03ed-48f0-b739-0a8f0a8db4fc)

![anvildev-2](https://github.com/DataBiosphere/azul/assets/46407464/1381c318-511d-4ba6-9f39-7440f1af432d)

![anvildev-3](https://github.com/DataBiosphere/azul/assets/46407464/d831f7c5-7a81-4b12-9b75-7adc7ea9ce4c)

![anvildev-4](https://github.com/DataBiosphere/azul/assets/46407464/567fb4e4-15d7-402f-907f-c5129d7b2e7a)
