### ISSUE TITLE
Import error for Terra handover

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5526]
Introduced by https://github.com/DataBiosphere/azul-private/issues/96 (PR https://github.com/DataBiosphere/azul/pull/5508)

![image](https://github.com/DataBiosphere/azul/assets/48401926/f3e5785a-05f0-47b8-a0af-fa9d0c44cd10)

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc discussion with Terra team: https://humancellatlas.slack.com/archives/C018YPVKC73/p1694555600685269

**Comment by hannes-ucsc** [comment]
Should get ETA on Tuesday.

**Comment by hannes-ucsc** [comment]
This was addressed by BI in Terra prod. I requested similar change for Terra `dev`.

**Comment by hannes-ucsc** [comment]
I recently confirmed (for PR #5669) that hand-overs are working against Terra `dev` so the change must have been deployed even though we didn't get confirmation from BI.
