### ISSUE TITLE
Project entorhinalCortexAlzheimers is missing genus_species

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5530]
Project UUID is `dcc28fb3-7bab-48ce-bc4b-684c00e133ce`, snapshot is `hca_prod_dcc28fb37bab48cebc4b684c00e133ce__20230905_dcp2_20230905_dcp31`.

<img width="839" alt="Screen Shot 2023-09-13 at 1 51 50 PM" src="https://github.com/DataBiosphere/azul/assets/19215510/09a9407d-3174-4270-9c10-6a0c75f242a6">

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to contact wranglers.

**Comment by hannes-ucsc** [comment]
Done: https://humancellatlas.slack.com/archives/C9XD6L0AD/p1695081842862329?thread_ts=1693233512.051389&cid=C9XD6L0AD

**Comment by achave11-ucsc** [comment]
Assignee to check project again in DCP32 release.

**Comment by hannes-ucsc** [comment]
Project was updated in dcp32 and is showing fixed now: <img width="1273" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/cf3ce4ff-afdf-4844-ab13-1d2f48bb9d1c">
