### ISSUE TITLE
Prevent unintentional generation of expensive manifests

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5533]
- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc to come up with design.

**Comment by hannes-ucsc** [comment]
Modify all manifest endpoints and their documentation to require the `filters` parameter. This will prevent search engines from inadvertently triggering these expensive requests. 

We could also prevent a `filters` value of `{}`, and while that constraint could be easily circumvented by enumerating all possible values in a particular field or by using an all-encompassing  `within` filter on a numeric field, I feel that requirement would be punitive. The DataBrowser for AnVIL currently uses `{}` for unconstrained manifests, the Data Browser for HCA specifies all file formats explicitly.

**Comment by dsotirho-ucsc** [comment]
Spike to refine design

**Comment by hannes-ucsc** [comment]
We should use POST for the creation of server-side resources.

Current request flow:

![Blank diagram - Page 1](https://github.com/DataBiosphere/azul/assets/5143256/a7e257eb-37e7-452c-9247-68e8700c8976)

New request flow implemented in a partial PR (changes marked in red):

![Blank diagram - Page 2](https://github.com/DataBiosphere/azul/assets/5143256/d86750d4-c42e-4157-8817-43ea92a95414)

The `filters` query parameter should be made mandatory. Note that in the new flow there is a single path parameter for either a token (representing an ongoing manifest generation) or an object key (representing the generation's result). A heuristic should be used to distinguish them.   

In a final PR, after the Data Browser has been updated to use POST instead of GET for the initial request, the GET form should be removed. Note that we don't need to worry about this type of backwards compatibility for the URLs we redirect to, those further down in the flow. Clients should blindly follow the redirects without inspecting the target URL.

**Comment by hannes-ucsc** [comment]
There is a complication. The URLs that contain objectKey also drag around all other parameters, like `filters`, `catalog` and `format`. This is a weird redundancy that will need to be removed before we can turn the `objectKey` query parameter into a `path` parameter.

**Comment by hannes-ucsc** [comment]
For demo, download a manifest using the `PUT /fetch/manifest/files endpoint`. Show the backwards-compatible `GET /fetch/manifest/files endpoint`.

**Comment by hannes-ucsc** [comment]
I don't understand why this was moved back to the Debt column. It was in prod and demoed. Closing.

**Comment by hannes-ucsc** [comment]
I understand now. PR was partial. Final PR can be filed when DB blocker is resolved.

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/data-browser/issues/3694#issuecomment-1954900664

> Lungmap appears to have been updated to `main`. I am assuming we can now close this and move forward with a PR that completes the resolution for DataBiosphere/azul#5533, by removing the support for `GET /fetch/manifest/files` and GET `/manifest/files`.

**Comment by dsotirho-ucsc** [comment]
Disconnecting this issue from PR #5594 to connect my PR #5981

**Comment by hannes-ucsc** [comment]
For demo, attempt to use GET with all of the manifest endpoints in a stable deployment.
