### ISSUE TITLE
Create FedRAMP related Diagram to include HCA Prod

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#5541]
The team needs to provide a new Authorization Boundary Diagram with HCA prod included. System diagrams showing before and after state of the system

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "This issue will not be addressed by creating a new diagram or by significantly modifying existing diagrams. We'll just need to mention HCA domain names in the legend to the network diagram."

**Comment by nolunwa-ucsc** [comment]
During storytime Hannes confirmed that there's an instance of the security boundary in every deployment zone. We have an instance of this for anvil production and development, HCA development and HCA production. And so, there is nothing to do in this diagram to cover HCA because it applies to both anvil and HCA.

**Comment by hannes-ucsc** [comment]
> During storytime Hannes confirmed

This was during stand-up

> And so, there is nothing to do in this diagram to cover HCA because it

Not quite. See my previous comment.

**Comment by hannes-ucsc** [comment]
Domain names in legend to network diagram have been updated.

**Comment by hannes-ucsc** [comment]
<img width="984" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/9eaf9538-65ba-4f72-a6d8-58742ac53a0a">
