### ISSUE TITLE
GitLab IT failure in `anvilprod` for catalog_complete subtest

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5546]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/11893
```
…
2023-09-18 22:10:04,424 INFO    MainThread: ... -> 200
2023-09-18 22:10:04,519 INFO    MainThread: Detected 195 of 194 bundles on try #0.
2023-09-18 22:10:04,520 ERROR   MainThread: Found 195 bundles, more than the expected 194.
2023-09-18 22:10:04,521 INFO    MainThread: Failed sub-test [catalog_complete] {'catalog': 'anvil2-it'}
…
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest) [catalog_complete] (catalog='anvil2-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 397, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 1040, in _assert_catalog_complete
    self.assertSetEqual(indexed_fqids, expected_fqids)
AssertionError: Items in the first set but not the second:
AnvilBundleFQID(uuid='a19cdf91-2f13-aadb-b43a-7536e73cb008', version='2022-06-01T00:00:00.000000Z', source=SourceRef(id='b735d811-a7ed-4d82-8b9d-5f23a9f33936', spec=TDRSourceSpec(prefix=Prefix(common='', partition=1), project='datarepo-a0cddf4b', name='ANVIL_PAGE_SoL_HMB_WGS_20221220_ANV5_202304271353', is_snapshot=True)), entity_type=<BundleEntityType.supplementary: 'file'>)
----------------------------------------------------------------------
Ran 14 tests in 1704.129s
FAILED (failures=1, skipped=1)
make: *** [Makefile:231: integration_test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
ERROR: Job failed: exit code 1
```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Happened again, https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/11924.

**Comment by achave11-ucsc** [comment]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/11979#L1573

**Comment by achave11-ucsc** [comment]
Spike to diagnose.

**Comment by nadove-ucsc** [comment]
This is caused by supplementary files being counted twice during indexing. The IT failures recorded above show two affected snapshots: 

- `datarepo-a0cddf4b.ANVIL_PAGE_SoL_HMB_WGS_20221220_ANV5_202304271353`
 - `datarepo-72d751e6.ANVIL_CMG_Broad_Muscle_Kang_WES_20230525_ANV5_202305251745`

Here is an example of an affected file: 

```
{
      "entryId": "83c81e75-32ee-49fc-a1a0-84b2291ea9b5",
      "sources": [
        {
          "sourceSpec": "tdr:datarepo-a0cddf4b:snapshot/ANVIL_PAGE_SoL_HMB_WGS_20221220_ANV5_202304271353:/1",
          "sourceId": "b735d811-a7ed-4d82-8b9d-5f23a9f33936"
        }
      ],
      "bundles": [
        {
          "bundleUuid": "83c81e75-32ee-a9fc-a1a0-84b2291ea9b5",
          "bundleVersion": "2022-06-01T00:00:00.000000Z"
        },
        {
          "bundleUuid": "a19cdf91-2f13-aadb-b43a-7536e73cb008",
          "bundleVersion": "2022-06-01T00:00:00.000000Z"
        }
      ],
      "activities": [
        {
          "activity_type": [
            "Checksum"
          ],
          "assay_type": [
            null
          ],
          "data_modality": [
            null
          ]
        }
      ],
      "biosamples": [],
      "datasets": [
        {
          "dataset_id": [
            "747d2563-6d3f-c38b-11cd-0b849bdc226a"
          ],
          "title": [
            "ANVIL_PAGE_SoL_HMB_WGS"
          ]
        }
      ],
      "diagnoses": [],
      "donors": [],
      "files": [
        {
          "document_id": "83c81e75-32ee-49fc-a1a0-84b2291ea9b5",
          "source_datarepo_row_ids": [
            "file_inventory:0338931d-5957-4a42-aef4-3aa8047f8764"
          ],
          "file_id": "e7f84b4f-9893-44e9-9fce-a56688185fa7",
          "data_modality": [
            null
          ],
          "file_format": ".cram",
          "file_size": 19898809658,
          "file_md5sum": "Iwq0NV7XSYHhIkZyY1A7Og==",
          "reference_assembly": [
            null
          ],
          "file_name": "H_TK-G0038746-G0038746.cram",
          "is_supplementary": true,
          "version": "2022-06-01T00:00:00.000000Z",
          "uuid": "83c81e75-32ee-49fc-a1a0-84b2291ea9b5",
          "size": 19898809658,
          "name": "H_TK-G0038746-G0038746.cram",
          "crc32": "",
          "sha256": "",
          "drs_uri": "drs://drs.anv0:v2_ecd26de7-08e6-3d12-b46c-a9b71ff9b6f6",
          "accessible": true,
          "url": "https://service.prod.anvil.gi.ucsc.edu/repository/files/83c81e75-32ee-49fc-a1a0-84b2291ea9b5?catalog=anvil2&version=2022-06-01T00%3A00%3A00.000000Z"
        }
      ]
    }
```

This is a supplementary file that received contributions from two bundles: a supplementary bundle, centered on the file itself, and a primary bundle centered on Biosample `a19cdf91-2f13-4adb-b43a-7536e73cb008`. I infer from the service response that the structure of the primary bundle looks like this:

![image](https://github.com/DataBiosphere/azul/assets/48401926/24e3d21f-8e18-49c1-90eb-b8356d1253d1)

I believe this constitutes a bug in the snapshot, since supplementary files should not be linked to non-supplementary files. I suspect the correct structure would be:

![image](https://github.com/DataBiosphere/azul/assets/48401926/7ac8ae3a-7345-43f4-93b9-cd0bd5674eff)

-----

That said, there may be room for improvement on our end as well. [The current logic for obtaining the set of indexed bundles](https://github.com/DataBiosphere/azul/blob/a151b4586fb8b0895079bbe05f03b5283102e39e/test/integration_test.py#L996) interprets the bundles shown above as _two_ supplementary bundles, based on the assumption on that supplementary files will never be linked to a primary bundle. This causes the test to expect to find two different versions of the linked primary bundle: one where it's been correctly identified as a primary bundle, and one where it's been incorrectly identified as a supplementary bundle. I think it would result in a clearer error message if we asserted that each supplementary file only occurs in a single bundle, as long as I'm correct in my assumption that this is the expected behavior.

**Comment by achave11-ucsc** [comment]
Happened again for `hammerbox` https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/12056#L597.

https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/12078#L1727

https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/12114#L421

**Comment by nadove-ucsc** [comment]
Using BigQuery, I detected activities linking between supplementary and non-supplementary files in the following snapshots in `anvil2`. The number in parentheses is the number of such activities.

1. `datarepo-a0cddf4b.ANVIL_PAGE_SoL_HMB_WGS_20221220_ANV5_202304271353` (206)
2. `datarepo-72d751e6.ANVIL_CMG_Broad_Muscle_Kang_WES_20230525_ANV5_202305251745` (9)
3. `datarepo-3c031cc3.ANVIL_CMG_Broad_Brain_Walsh_WES_20230605_ANV5_202306131445` (3)
4. `datarepo-84b68087.ANVIL_T2T_20230714_ANV5_202307181429` (140)
5. `datarepo-bf58b120.ANVIL_HPRC_20230721_ANV5_202307241534` (628)

**Comment by nadove-ucsc** [comment]
I confirmed the structure of the bundle shown above using BigQuery. Here is a diagram showing the foreign keys that determine the shape of the subgraph. The black dots indicate queries that yielded no results. The activity and file in the bottom right are not elements of the affected subgraph, but I thought their connection was interesting.

![image](https://github.com/DataBiosphere/azul/assets/48401926/9ea996d6-2103-41be-a037-713753fb642a)

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "I will contact Nate. Assignee to file a PR that removed the five snapshots listed by @nadove-ucsc above."

**Comment by achave11-ucsc** [comment]
Note that two of the [projects mentioned](https://github.com/DataBiosphere/azul/issues/5546#issuecomment-1728503499) were first introduced by the `anvil1` catalog.
```
ANVIL_CMG_Broad_Muscle_Kang_WES_20230525_ANV5_202305251745
ANVIL_CMG_Broad_Brain_Walsh_WES_20230605_ANV5_202306131445
```

**Comment by hannes-ucsc** [comment]
Contacted Nate: https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1695336751871409?thread_ts=1693341779.811629&cid=C03TPJS54DC
