### ISSUE TITLE
Increase retention of Elasticsearch domain error logs

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5557]
Increase retention of Elasticsearch domain `ES_APPLICATION_LOGS` type logs to 180 days.

This ticket was prompted from the review of audit log retention #5078

----

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] ~… affect audit logging in the system, like~ https://github.com/DataBiosphere/azul/issues/5557#issuecomment-1739762819
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [ ] ~… require persistence of sensitive or confidential data that might require encryption at rest~ https://github.com/DataBiosphere/azul/issues/5557#issuecomment-1739762819
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, show retention in AWS console.

**Comment by hannes-ucsc** [comment]
Security review: This change increases the retention of Elasticsearch error logs to longer than what FedRAMP requires. We've [determined](https://github.com/DataBiosphere/azul/issues/5078#issuecomment-1728184702) that the resulting increase in storage volume is negligible. The logs are stored in CloudWatch will are encrypted server-side by default. 

This change therefore increases our security posture.
