### ISSUE TITLE
Indexer throttled during IT in `anvilprod`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5567]
<img width="1236" alt="Screen Shot 2023-09-26 at 1 15 12 PM" src="https://github.com/DataBiosphere/azul/assets/19215510/5e19f006-0f36-4b9c-8f2f-4a9e77f7eed5">

<img width="1288" alt="Screen Shot 2023-09-26 at 1 15 02 PM" src="https://github.com/DataBiosphere/azul/assets/19215510/a9e4fc26-cc9e-4c37-b2b4-d1e39678d133">

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Resolution is to request an increase in total concurrency from 1k to 2k just like we did in `dev`. This request needs to be made for `anvildev` and `anvilprod`."

**Comment by dsotirho-ucsc** [comment]
> Resolution is to request an increase in total concurrency from 1k to 2k just like we did in `dev`

- Request in `platform-anvil-dev`: [Case ID 14034104271](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=14034104271&language=en)
- Request in `platform-anvil-prod`: [Case ID 14034049781 ](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=14034049781&language=en)

**Comment by dsotirho-ucsc** [comment]
Account limits have been increased.
I closed the AWS Support tickets with positive feedback ratings.

```
(.venv) daniel@Crispin ~/repo/azul2 $ _select
lrwxr-xr-x  1 daniel  staff  8 Oct 11 08:48 .active -> anvildev
(.venv) daniel@Crispin ~/repo/azul2 $
(.venv) daniel@Crispin ~/repo/azul2 $ aws lambda get-account-settings
{
    "AccountLimit": {
        "TotalCodeSize": 80530636800,
        "CodeSizeUnzipped": 262144000,
        "CodeSizeZipped": 52428800,
        "ConcurrentExecutions": 2000,
        "UnreservedConcurrentExecutions": 1392
    },
    "AccountUsage": {
        "TotalCodeSize": 198293174,
        "FunctionCount": 47
    }
}
```

```
(.venv) daniel@Crispin ~/repo/azul3 $ _select
lrwxr-xr-x  1 daniel  staff  9 Oct 11 08:48 .active -> anvilprod
(.venv) daniel@Crispin ~/repo/azul3 $
(.venv) daniel@Crispin ~/repo/azul3 $ aws lambda get-account-settings
{
    "AccountLimit": {
        "TotalCodeSize": 80530636800,
        "CodeSizeUnzipped": 262144000,
        "CodeSizeZipped": 52428800,
        "ConcurrentExecutions": 2000,
        "UnreservedConcurrentExecutions": 1456
    },
    "AccountUsage": {
        "TotalCodeSize": 146947562,
        "FunctionCount": 29
    }
}
```
