### ISSUE TITLE
Deploy Data Browser rewrite for HCA (dev & prod)

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5568]
Clever Canary is ready to deploy the React version of the Data Browser and needs a dev deploy for this purpose.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We would need a reference to the config files in the data-browser repository."

**Comment by NoopDog** [comment]
Hi @dsotirho-ucsc  yes to prepare the config we need to know the deployment URL and the Azul endpoint for each environment. Would you be able to provide these please? Thanks! D

**Comment by hannes-ucsc** [comment]
- `dev`: 
   - Azul: `https://service.dev.singlecell.gi.ucsc.edu`
   - Data Browser: `https://explore.dev.singlecell.gi.ucsc.edu`
- `prod`: 
   - Azul: `https://service.azul.data.humancellatlas.org`
   - Data Browser: `https://explore.data.humancellatlas.org`

**Comment by NoopDog** [comment]
Super , thanks.

D

**Comment by dsotirho-ucsc** [comment]
@bvizzier-ucsc: "Clever Canary is actively working on the configuration."

**Comment by bvizzier-ucsc** [comment]
@NoopDog Where do we stand on this?  Please update.

**Comment by NoopDog** [comment]
Hi @bvizzier-ucsc this ticket is complete.

#### Prod
The non-managed access version of the Prod HCA Data Explorer is hosted in `platform-hca-portal` at https://explore.data.humancellatlas.org/

#### Dev
The non-managed access version of the Dev HCA Data Explorer is hosted on a Clever Canary AWS account at `platform-hca-portal` at https://explore.data.humancellatlas.dev.clevercanary.com/

Cheers,
D
