### ISSUE TITLE
PR template for GitLab updates contradicts OPERATOR.rst

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5590]
Update the [GitLab update PR template](https://github.com/DataBiosphere/azul/blob/develop/.github/PULL_REQUEST_TEMPLATE/gitlab.md) to match the operator guide section [Upgrading GitLab & ClamAV](https://github.com/DataBiosphere/azul/blob/develop/OPERATOR.rst#upgrading-gitlab-clamav), specifically by removing the steps to update `prod.gitlab` along with the other deployments, and instead add a checklist item to add a checklist item to the `prod` promotion PR to deploy `prod.gitlab` during the promotion.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, show how the checklists in the `upgrade` and `promotion` templates now handle deploying the `gitlab` component on GitLab updates.

**Comment by hannes-ucsc** [comment]
This was moved out of `prod` because it was thought to not be demoable because another ticket resolved by the same PR failed to be demoed. This issue is actually demoable. Moving back to `prod`.
