### ISSUE TITLE
ES client causes urllib3 DeprecationWarning

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5592]
Our current version of `elasticsearch` client v7.10.1 causes a DepricationWarning in `urllib3` v1.26.17

```
AssertionError: ["{message : DeprecationWarning('HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.'), category : 'DeprecationWarning', filename : '/home/runner/work/azul/azul/.venv/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py', lineno : 275, line : None}"]
```

After upgrading to `elasticsearch` v7.15.0 or higher, remove the permitted warning in `azul_test_case.py`

Source of DeprecationWarning in `elasticsearch` v7.10.1: https://www.github.com/elastic/elasticsearch-py/blob/e275834941ea053c300e2c4bc494fccd5265f127/elasticsearch/connection/http_urllib3.py#L275

First `elasticsearch` version to resolve this issue (v7.15.0): https://www.github.com/elastic/elasticsearch-py/blob/v7.15.0/elasticsearch/connection/http_urllib3.py

----

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Spike for design

**Comment by hannes-ucsc** [comment]
Spike to upgrade client, verify that it still breaks at runtime when it refuses to work with an Opensearch domain. 

If it doesn't, we only need to file a PR with the dependency upgrade.

If it does, we need to monkey patch the client to disable that check. If that doesn't work or is crazy complicated, fork the client repository and remove the check in the source. File a PR with these changes.

**Comment by nadove-ucsc** [comment]
> Spike to upgrade client, verify that it still breaks at runtime when it refuses to work with an Opensearch domain.

Deployment fails with

```
Plan: 0 to add, 9 to change, 0 to destroy.
╷
│ Error: External Program Execution Failed
│ 
│   with data.external.elasticsearch_nodes,
│   on cloudwatch.tf.json line 7, in data[0].external[0].elasticsearch_nodes:
│    7:                         "program": [
│    8:                             "python",
│    9:                             "/home/nadove/PycharmProjects/azul-sc/scripts/elasticsearch_nodes.py"
│   10:                         ],
│ 
│ The data source received an unexpected error while attempting to execute the program.
│ 
│ Program: /home/nadove/PycharmProjects/azul-sc/.venv/bin/python
...
│ elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch
```
