### ISSUE TITLE
Review mitigation milestones for vulnerability tickets

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5597]
Adjust/set the mitigation milestone for all tickets that represent vulnerability findings. Clock starts at ATO (7/1/2023) or date of when finding was first detected, whichever is later.

Also ensure that iceboxed tickets are labeled `invalid` or `won't fix`.

Low: 180 days
Medium: 90 days
High: 30 days
Critical: 15 days

**Comment by dsotirho-ucsc** [comment]
Milestones added to all* vulnerability tickets without a milestone.

*Exceptions:
- https://github.com/DataBiosphere/azul-private/issues/35 (severity: Informational)
- https://github.com/DataBiosphere/azul/issues/4177 (severity: unknown)

Labels used to find vulnerability tickets: `invicti`, `fortreum`, `severity:cis1`, `severity:cis2`, `severity:critical`, `severity:high`, `severity:low`, `severity:medium`, `securityhub`
