### ISSUE TITLE
Re-triage data portal and browser findings

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5598]
Check all tickets labeled `invicti` and `canary` and determine if they are still being detected in the most recent Invicti scans. Provide additional information on each ticket if necessary.

**Comment by dsotirho-ucsc** [comment]
Still a finding as of the 9/20/2023 scan:
- https://github.com/DataBiosphere/azul-private/issues/36
- https://github.com/DataBiosphere/azul-private/issues/6
- https://github.com/DataBiosphere/azul-private/issues/7
- https://github.com/DataBiosphere/azul-private/issues/10

No longer a finding:
- https://github.com/DataBiosphere/azul-private/issues/5
- https://github.com/DataBiosphere/azul-private/issues/8
- https://github.com/DataBiosphere/azul-private/issues/9
- https://github.com/DataBiosphere/azul-private/issues/11
