### ISSUE TITLE
Document the Data Portal/Browser restful APIs for end users

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#56]
Documentation of the Data Portal/Data Browser restful APIs for end users (tertiary analysis portal developers and researchers).

Use Swagger Web Services.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-47)
┆Project Name: azul
┆Issue Number: AZUL-47

**Comment by theathorn** [comment]
Proposal is to use Sphinx tool (www.sphinx-doc.org/).

**Comment by theathorn** [comment]
Dup of #541.
