### ISSUE TITLE
Timestamp should be part of the filename when downloading the manifest

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#561]
When downloading the manifest, name it something like manifest_{timestamp}.tsv

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-357)
┆Project Name: azul
┆Issue Number: AZUL-357

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
