### ISSUE TITLE
AWS Inspector fails to post findings to SNS topic

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5612]
Issue #5301 (PR #5539) added an AWS EventBridge rule to to post AWS Inspector findings to the `monitoring` SNS topic, howwever this is only currently working on `platform-hca-dev`.

it needs to be figured out why this is not working on `platform-anvil-dev` and `platform-anvil-prod`.

----

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@dsotirho-ucsc to mention symptom in title and description.

**Comment by dsotirho-ucsc** [comment]
The `monitoring` SNS topic on `platform-hca-dev` has an additional access policy statement that the other deployments do not have that allows EventBridge to publish to the SNS topic. The same policy statement will need to be added to the other deployments.

Note:
- The new statement should be appended to the to the policy's existing statements.
- The statement on `platform-hca-dev` should be manually removed just prior to the merge & deploy of a PR for this issue (assuming we add the new statement via Terraform)
- Specifics about the required statement can be found on the following AWS documentation pages:
    - [Amazon SQS permissions](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-use-resource-based.html#eb-sqs-permissions)
    - [My rule runs, but I don't see any messages published into my Amazon SNS topic](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-troubleshooting.html#eb-no-messages-published-sns)

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "It's some what puzzling that the topic policy already includes a certain number of statements, even though we don't specify any policy in Terraform config for the topic. This suggests that the policy was updated automatically. We need to put the policy under Terraform control. Assignee to ensure that the policy contains statements for all required entities posting to the topic not just EventBridge, the lack of which is the immediate cause of this issue."

**Comment by dsotirho-ucsc** [comment]
Statement found on all deployments (dev's copy shown here)

```
    {
      "Sid": "__default_statement_ID",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "SNS:GetTopicAttributes",
        "SNS:SetTopicAttributes",
        "SNS:AddPermission",
        "SNS:RemovePermission",
        "SNS:DeleteTopic",
        "SNS:Subscribe",
        "SNS:ListSubscriptionsByTopic",
        "SNS:Publish"
      ],
      "Resource": "arn:aws:sns:us-east-1:122796619775:azul-monitoring-dev",
      "Condition": {
        "StringEquals": {
          "AWS:SourceOwner": "122796619775"
        }
      }
    },
```

The extra statement on dev that's allowing EventBridge to post to the topic:
```
    {
      "Sid": "AWSEvents_inspector_to_slack_terraform-20230728162845718600000001",
      "Effect": "Allow",
      "Principal": {
        "Service": "events.amazonaws.com"
      },
      "Action": "sns:Publish",
      "Resource": "arn:aws:sns:us-east-1:122796619775:azul-monitoring-dev"
    }
```

**Comment by hannes-ucsc** [comment]
For demo, repeat demo of #5301 for every deployment.

**Comment by dsotirho-ucsc** [comment]
PR #5623 failed to deploy to `dev.shared` after it was merged. A revert commit has been added to `develop`.

**Comment by dsotirho-ucsc** [comment]
From @hannes-ucsc on [Slack](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1698257253812009?thread_ts=1698252233.348869&cid=C705Y6G9Z) :
> I think the first statement in the topic policy is redundant. With only one statement left, I believe we don't need a Sid. Be sure to test my hypothesis before the next review.
