### ISSUE TITLE
False positive AWS Inspector findings after GitLab deploy

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5617]
Destroying and recreating the GitLab EC2 instance causes false positive AWS Inspector findings to be reported.

These findings are false positives because some of the findings are resolved right after they are found when `yum update` is run as part of the initial startup of the instance.

----

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Assignee to modify title and description to capture the symptom and propose the remedy in a comment.

**Comment by dsotirho-ucsc** [comment]
Possible remedies include:
- Moving the `yum` action to be earlier in the cloud-init processes
- Tweaking the SSM Agent on EC2 instance to delay the Inspector scan performed at launch of the instance

**Comment by dsotirho-ucsc** [comment]
> * Moving the `yum` action to be earlier in the cloud-init processes

This was tested on `dev` and it did not resolve the symptom, the findings were still found and reported to the SNS topic.

**Comment by achave11-ucsc** [comment]
Spike for design.

**Comment by hannes-ucsc** [comment]
Firstly, craft a CW Logs Insights query that we can use to determine the sequence of relevant events. Look for signs of SSM agent starting and stopping. Systemd logs when each unit starts and stops. Cloud-init logs when `runcmd` finishes. Look for `config-runcmd ran successfully`.

As for the actual fix, try

```diff
Subject: [PATCH] WIP
---
Index: terraform/gitlab/gitlab.tf.json.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/gitlab/gitlab.tf.json.template.py b/terraform/gitlab/gitlab.tf.json.template.py
--- a/terraform/gitlab/gitlab.tf.json.template.py	(revision 3febfa75e31a0bafdc8f58159fc980ff35c54c69)
+++ b/terraform/gitlab/gitlab.tf.json.template.py	(date 1697648275794)
@@ -1344,6 +1344,9 @@
                         'dracut-fips'
                     ],
                     'ssh_authorized_keys': other_public_keys.get(config.deployment_stage, []),
+                    'bootcmd': [
+                        ['cloud-init-per', 'once', 'systemctl', 'disable', 'amazon-ssm-agent.service']
+                    ],
                     'write_files': [
                         {
                             'path': '/root/.docker/config.json',
@@ -1796,7 +1799,8 @@
                             '-c', 'file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json',
                             '-s'  # restart agent afterwards
                         ],
-                        ['yum', '-y', 'update']
+                        ['yum', '-y', 'update'],
+                        ['systemctl', 'enable', 'amazon-ssm-agent.service']
                     ],
                     # Reboot to realize the added kernel parameter the changed sshd configuration
                     'power_state': {
```

The above assumes that `systemctl` disable is functional during `bootcmd` and that the `amazon-ssm-agent.service` unit hasn't started yet. If the former turns out to be false, fall back to `rm /etc/systemd/system/multi-user.target.wants/amazon-ssm-agent.service` (split into array, obviously). If the former is true but the latter is false, use a `bootcmd` of `systemctl stop …` and a `runcmd` of `systemctl start` instead. Be sure to understand what `cloud-init-per` does.

The above also assumes that `systemctl enable` also starts the unit. If that turns out not to be the case, use a `bootcmd of `systemctl start`.

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We were able to demo according to the instructions above, but @achave11-ucsc proposed looking for closed findings and we found one medium vulnerability that was opened and then closed shortly thereafter. That indicates that there still might be a race (we don't send notifications for medium severity vulnerabilities). I'm fine with that for now."
