### ISSUE TITLE
S3 log forwarder lambda times out

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5622]
… and raised an alarm. Comparatively, with other logs (which aren't associated via requestId) an s3 type of log appears to not have been emitted. Also, no error log was observed, as was the case for #5582.

[CW Insights](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2023-10-12T23*3a23*3a48.429Z~start~'2023-10-12T23*3a23*3a14.475Z~timeType~'ABSOLUTE~tz~'Local~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40log*0a*23*20*7c*20filter*20*40logStream*20like*20*272023*2f10*2f12*2f*5b$21LATEST*5daafe9faeb886454aa301aa2fc77a6f5c*27*0a*23*20*7c*20filter*20*40message*20like*20*2faa5a1d97*2f*0a*23*20*7c*20filter*20*40message*20like*20*2f*2f*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*2060~queryId~'4c1a3ac4f5a25d-fd1cd67a-4723d18-aeff6d56-791164ce5fbe11e2fc948deb~source~(~'*2faws*2flambda*2fazul-indexer-dev-forward_s3_logs))).

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike to investigate.

**Comment by nadove-ucsc** [comment]
I believe it's impossible to determine which log object triggered the lambda invocation that timed out. However, I can make an educated guess that the offending trigger was `s3/access/nadove/storage/2023-10-12-23-23-15-F82EE6A46C24A4D1`, based on the following evidence:

 - Its timestamp precedes the lambda invocation by just a few milliseconds. The object's `LastModified` field is `2023-10-12T23:23:16.000Z`, while the Lambda's START message was logged at `2023-10-12T23:23:16.909Z`. This is consistent with other (successful) invocations that occurred at around the same time, e.g. `s3/access/abrahamsc/storage/2023-10-12-23-23-00-F4D9795B43BAA862` (object modified at `2023-10-12T23:23:01.000Z`, Lambda invoked at `2023-10-12T23:23:01.729Z`, trigger confirmed via `_source_key` log field).
 - It is the only object in `s3/access/` created between 23:23 and 23:34 that does _NOT_ have a corresponding forwarded log message within that same time range.

The object itself appears unremarkable. It's 791 bytes and records a single PUT operation performed by the health service for one of my personal deployments. There are thousands of such log messages, so I doubt the object's contents is the issue. Perhaps we could experiment by downloading, deleting, and re-uploading it to try and reproduce the timeout.

I think a more likely explanation is that a transient network error caused the object to fail to download. But I'm at a loss as to how to investigate further.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We seem to have explicitly disabled retries for the forwarder lambda, I agree with @nadove-ucsc's explanation of the transient nature of this issue. I'd like to address this by either enabling retries or configuring a DLQ, splitting up the forwarder into two handlers just like we do during indexing."

**Comment by achave11-ucsc** [comment]
Spike for design.

**Comment by hannes-ucsc** [comment]
In a first, partial PR, enable one retry (two attempts) and a DLQ on this function so that we capture each event that failed to be processed two times. This will enable us to more quickly diagnose repeatedly failed executions and reduce the impact of transient errors.

**Comment by achave11-ucsc** [comment]
This happened again recently in `anvilprod`. 

```
[
    {
        "@timestamp": "2023-10-20 16:27:46.827",
        "@message": "START RequestId: 4299ee26-8d1d-4ea9-bd43-77b85ed96cfe Version: $LATEST\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    },
    {
        "@timestamp": "2023-10-20 16:28:17.840",
        "@message": "2023-10-20T16:28:17.840Z 4299ee26-8d1d-4ea9-bd43-77b85ed96cfe Task timed out after 31.01 seconds\n\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    },
    {
        "@timestamp": "2023-10-20 16:28:17.840",
        "@message": "END RequestId: 4299ee26-8d1d-4ea9-bd43-77b85ed96cfe\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    },
    {
        "@timestamp": "2023-10-20 16:28:17.840",
        "@message": "REPORT RequestId: 4299ee26-8d1d-4ea9-bd43-77b85ed96cfe\tDuration: 31012.52 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 109 MB\t\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    }
]
```

**Comment by achave11-ucsc** [comment]
Once more for `anvilprod`:
```
This happened again
[
    {
        "@timestamp": "2023-10-23 05:29:28.562",
        "@message": "START RequestId: 2e35fc11-8244-444a-bade-11afb4aedf2f Version: $LATEST\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    },
    {
        "@timestamp": "2023-10-23 05:29:59.624",
        "@message": "2023-10-23T05:29:59.624Z 2e35fc11-8244-444a-bade-11afb4aedf2f Task timed out after 31.06 seconds\n\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    },
    {
        "@timestamp": "2023-10-23 05:29:59.624",
        "@message": "END RequestId: 2e35fc11-8244-444a-bade-11afb4aedf2f\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    },
    {
        "@timestamp": "2023-10-23 05:29:59.624",
        "@message": "REPORT RequestId: 2e35fc11-8244-444a-bade-11afb4aedf2f\tDuration: 31061.76 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 112 MB\t\n",
        "lambda": "azul-indexer-anvilprod-forward_s3_logs"
    }
]
```

**Comment by dsotirho-ucsc** [comment]
Closing issue as dup of #5499

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "This ticket has more meat so we inverted the duplicate relationship."

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Now that we have Boto3 request logging we can tell that the lambda times out during a GetObject request to S3: "

```
[
    {
        "@timestamp": "2024-01-16 07:37:44.002",
        "@message": "START RequestId: 068bbd6b-f3a8-43a6-8a58-6fbc2a1e7eef Version: $LATEST\n"
    },
    {
        "@timestamp": "2024-01-16 07:37:44.004",
        "@message": "[INFO]\t2024-01-16T07:37:44.004Z\t068bbd6b-f3a8-43a6-8a58-6fbc2a1e7eef\tazul.boto3\ts3.GetObject:\tMaking GET request to https://s3.amazonaws.com/edu-ucsc-gi-platform-anvil-prod-logs.us-east-1/s3/access/anvilprod/storage/2024-01-16-07-37-42-E7634FBBB18F83ED"
    },
    {
        "@timestamp": "2024-01-16 07:37:44.004",
        "@message": "[INFO]\t2024-01-16T07:37:44.004Z\t068bbd6b-f3a8-43a6-8a58-6fbc2a1e7eef\tazul.boto3\ts3.GetObject:\t… without request body"
    },
    {
        "@timestamp": "2024-01-16 07:38:15.044",
        "@message": "2024-01-16T07:38:15.044Z 068bbd6b-f3a8-43a6-8a58-6fbc2a1e7eef Task timed out after 31.04 seconds\n\n"
    },
    {
        "@timestamp": "2024-01-16 07:38:15.044",
        "@message": "END RequestId: 068bbd6b-f3a8-43a6-8a58-6fbc2a1e7eef\n"
    },
    {
        "@timestamp": "2024-01-16 07:38:15.044",
        "@message": "REPORT RequestId: 068bbd6b-f3a8-43a6-8a58-6fbc2a1e7eef\tDuration: 31041.31 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 121 MB\t\n"
    },
    {
        "@timestamp": "2024-01-16 22:25:55.827",
        "@message": "START RequestId: 036df23b-6ae0-49cc-ac1b-104330dcd5ee Version: $LATEST\n"
    },
    {
        "@timestamp": "2024-01-16 22:25:55.829",
        "@message": "[INFO]\t2024-01-16T22:25:55.828Z\t036df23b-6ae0-49cc-ac1b-104330dcd5ee\tazul.boto3\ts3.GetObject:\tMaking GET request to https://s3.amazonaws.com/edu-ucsc-gi-platform-anvil-prod-logs.us-east-1/s3/access/anvilprod/browser/2024-01-16-22-25-54-B4B022131BCEE79A"
    },
    {
        "@timestamp": "2024-01-16 22:25:55.829",
        "@message": "[INFO]\t2024-01-16T22:25:55.829Z\t036df23b-6ae0-49cc-ac1b-104330dcd5ee\tazul.boto3\ts3.GetObject:\t… without request body"
    },
    {
        "@timestamp": "2024-01-16 22:26:26.893",
        "@message": "2024-01-16T22:26:26.893Z 036df23b-6ae0-49cc-ac1b-104330dcd5ee Task timed out after 31.07 seconds\n\n"
    },
    {
        "@timestamp": "2024-01-16 22:26:26.893",
        "@message": "END RequestId: 036df23b-6ae0-49cc-ac1b-104330dcd5ee\n"
    },
    {
        "@timestamp": "2024-01-16 22:26:26.893",
        "@message": "REPORT RequestId: 036df23b-6ae0-49cc-ac1b-104330dcd5ee\tDuration: 31065.56 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 123 MB\t\n"
    },
    {
        "@timestamp": "2024-01-17 07:40:31.247",
        "@message": "START RequestId: d45838cc-be16-4c7f-9ee0-6026818b48b6 Version: $LATEST\n"
    },
    {
        "@timestamp": "2024-01-17 07:40:31.248",
        "@message": "[INFO]\t2024-01-17T07:40:31.248Z\td45838cc-be16-4c7f-9ee0-6026818b48b6\tazul.boto3\ts3.GetObject:\tMaking GET request to https://s3.amazonaws.com/edu-ucsc-gi-platform-anvil-prod-logs.us-east-1/s3/access/hammerbox/storage/2024-01-17-07-40-29-24D082E69AFD6A9D"
    },
    {
        "@timestamp": "2024-01-17 07:40:31.248",
        "@message": "[INFO]\t2024-01-17T07:40:31.248Z\td45838cc-be16-4c7f-9ee0-6026818b48b6\tazul.boto3\ts3.GetObject:\t… without request body"
    },
    {
        "@timestamp": "2024-01-17 07:41:02.321",
        "@message": "2024-01-17T07:41:02.321Z d45838cc-be16-4c7f-9ee0-6026818b48b6 Task timed out after 31.07 seconds\n\n"
    },
    {
        "@timestamp": "2024-01-17 07:41:02.321",
        "@message": "END RequestId: d45838cc-be16-4c7f-9ee0-6026818b48b6\n"
    },
    {
        "@timestamp": "2024-01-17 07:41:02.321",
        "@message": "REPORT RequestId: d45838cc-be16-4c7f-9ee0-6026818b48b6\tDuration: 31074.01 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 122 MB\t\n"
    }
]
```

**Comment by achave11-ucsc** [comment]
Could be related to https://github.com/DataBiosphere/azul/issues/5467#issuecomment-1897057973

**Comment by dsotirho-ucsc** [comment]
Freebie of PR #5915 for #5467

**Comment by hannes-ucsc** [comment]
For demo, two weeks after this lands in anvilprod or prod, show the reduction in the incident rate of the corresponding alarm.

**Comment by achave11-ucsc** [comment]
![Screenshot 2024-02-20 at 2 52 13 PM](https://github.com/DataBiosphere/azul/assets/19215510/fd0824b9-c804-4f44-8051-53e23ec5cfb2)

@hannes-ucsc: "Incident rate prior to the fix is too low to drawn any conclusions regarding the fix' effectiveness in the two weeks after it landed on prod, we would have to wait several months to observe a change in frequency."

**Comment by dsotirho-ucsc** [comment]
https://groups.google.com/a/ucsc.edu/g/azul-group/c/bE5INoa1FnQ/m/boQKPs9oAgAJ

**Comment by dsotirho-ucsc** [comment]
This issue has reemerged, see logs from `dev` below.

```

    {
        "@timestamp": "2024-02-23 23:41:11.909",
        "@message": "START RequestId: 6cb9195c-f54b-4bf0-9392-ffc1d1be284f Version: $LATEST\n"
    },
    {
        "@timestamp": "2024-02-23 23:41:11.910",
        "@message": "[INFO]\t2024-02-23T23:41:11.910Z\t6cb9195c-f54b-4bf0-9392-ffc1d1be284f\tazul.boto3\ts3.GetObject:\tMaking GET request to https://s3.amazonaws.com/edu-ucsc-gi-platform-hca-dev-logs.us-east-1/s3/access/sandbox/storage/2024-02-23-23-41-10-255BB732A7D5CEF0"
    },
    {
        "@timestamp": "2024-02-23 23:41:11.910",
        "@message": "[INFO]\t2024-02-23T23:41:11.910Z\t6cb9195c-f54b-4bf0-9392-ffc1d1be284f\tazul.boto3\ts3.GetObject:\t… without request body"
    },
    {
        "@timestamp": "2024-02-23 23:41:43.003",
        "@message": "2024-02-23T23:41:43.003Z 6cb9195c-f54b-4bf0-9392-ffc1d1be284f Task timed out after 31.09 seconds\n\n"
    },
    {
        "@timestamp": "2024-02-23 23:41:43.003",
        "@message": "END RequestId: 6cb9195c-f54b-4bf0-9392-ffc1d1be284f\n"
    },
    {
        "@timestamp": "2024-02-23 23:41:43.003",
        "@message": "REPORT RequestId: 6cb9195c-f54b-4bf0-9392-ffc1d1be284f\tDuration: 31094.58 ms\tBilled Duration: 31000 ms\tMemory Size: 128 MB\tMax Memory Used: 122 MB\t\n"
    }
]
```

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Assignee to file AWS support issue:

> We occasionally observe the … lambda function timing out when reading S3 access logs from an S3 bucket. The function is triggered by a S3 object creation event. The function is in a VPC. Since enabling a VPC Gateway Endpoint for S3, the frequency of these timeout has decreased but they still occur. At this point we are at a loss as to why this is occurring and how to deal with it.

**Comment by dsotirho-ucsc** [comment]
Assignee to file AWS Support ticket on `anvilprod`

**Comment by achave11-ucsc** [comment]
[Issue](https://support.console.aws.amazon.com/support/home#/case/?displayId=171026705601879) has been submitted AWS `dev` support.

**Comment by achave11-ucsc** [comment]
AWS Support has replied, https://support.console.aws.amazon.com/support/home#/case/?displayId=171026705601879

**Comment by dsotirho-ucsc** [comment]
Spike to determine what the maximum evaluation period for a metric alarm is, and to confirm that retries are currently disabled on the log forwarding Lambdas.
@hannes-ucsc: "We may be able to allow one failed request per day / week without sacrificing robustness, especially if we enable retries. I confirmed that the S3 objects that the forwarder failed to read were never read again."

**Comment by achave11-ucsc** [comment]
From the [CloudWatch service quota page,](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html) on _Alarm evaluation period_:
> The maximum value, calculated by multiplying the alarm period by the number of evaluation periods used, is one day (86,400 seconds). This quota cannot be changed.


For the forwarding Lambdas, the following [retry configuration](https://github.com/DataBiosphere/azul/blob/develop/terraform/api_gateway.tf.json.template.py#L373-L380) is in effect:
```
'aws_lambda_function_event_invoke_config': {
                function_name: {
                    'function_name': '${aws_lambda_function.%s.function_name}' % function_name,
                    'maximum_retry_attempts': 0
                }
                for function_name in
                [
                    f'indexer_{lm}'
                    for lm in ['forward_alb_logs', 'forward_s3_logs']
```

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Assignee to increase the alarm threshold to 1 alarm per day. Assignee to also mark the support ticket as closed and thank the support person."

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Assignee to also increase the retry to two, so three attempts in total."

**Comment by dsotirho-ucsc** [comment]
~@hannes-ucsc: "We will move the retry increase to #6097."~

https://github.com/DataBiosphere/azul/issues/6097#issuecomment-2037921669

**Comment by hannes-ucsc** [comment]
For demo, show absence of alarms in all lower deployments, two weeks after this landed in those deployments.
