### ISSUE TITLE
`KeyError` in `repository_files` IT subtest

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5652]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/14457#L610

```
2023-10-25 22:57:33,120    INFO MainThread test.integration_test: GET https://service.hammerbox.prod.anvil.gi.ucsc.edu/fetch/repository/files/140e0c28-0795-4faf-81b4-3989d62ec2b9?catalog=anvil1-it&version=2022-06-01T00%3A00%3A00.000000Z using contextual client...
2023-10-25 22:58:02,135    INFO MainThread test.integration_test: ... -> 504
2023-10-25 22:58:02,135    INFO MainThread test.integration_test: Failed sub-test [repository_files] {'catalog': 'anvil1-it'}

...

ERROR: test_indexing (integration_test.IndexingIntegrationTest) [repository_files] (catalog='anvil1-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 407, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 868, in _test_repository_files
    while response['Status'] != 302:
KeyError: 'Status'
```

Looks like a gateway timeout resulted in a response with an unexpected structure. 

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "The easy fix is to check the native status code before diving into the body. This would avoid the key error but it would still fail the test in case the API gateway returns a 504. Assignee to consider retrying on 504s and to include the fix in the PR for DataBiosphere/azul-private#110 "

**Comment by hannes-ucsc** [comment]
The fix was incorporated in a different PR, but the [commit](https://github.com/DataBiosphere/azul/commit/70054b6a3058e43081ce2690d543733820af222a) does not refer to this issue.

The IT does not retry on 504s, only on [429, 500, 502, 503](https://github.com/DataBiosphere/azul/commit/8554b040619e3b5ecc4079be0858f24326d79b53) but it is likely that the 504 was caused by a slow DRS request, and those are now [timeboxed](https://github.com/DataBiosphere/azul/issues/5536) and cause a 503 which *is* being retried.
