### ISSUE TITLE
IA-5(1) Password-based Authentication 

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#5654]
For password-based authentication:

> (a)	Maintain a list of commonly-used, expected, or compromised passwords and update the list [Assignment: organization-defined frequency] and when organizational passwords are suspected to have been compromised directly or indirectly;
> (b)Verify, when users create or update passwords, that the passwords are not found on the list of commonly-used, expected, or compromised passwords in IA-5(1)(a);
> (c)Transmit passwords only over cryptographically-protected channels;
> (d)Store passwords using an approved salted key derivation function, preferably using a keyed hash;
> (e)Require immediate selection of a new password upon account recovery;
> (f)Allow user selection of long passwords and passphrases, including spaces and all printable characters;
> (g)Employ automated tools to assist the user in selecting strong password authenticators; and
> (h)Enforce the following composition and complexity rules: [Assignment: organization-defined composition and complexity rules].
> 
> **IA-5 (1) Additional FedRAMP Requirements and Guidance:**
> **Guidance:** Note that (c) and (d) require the use of cryptography which must be compliant with Federal requirements and utilize FIPS validated or NSA approved cryptography (see SC-13).
> **Requirement:** Password policies must be compliant with NIST SP 800-63B for all memorized, lookup, out-of-band, or One-Time-Passwords (OTP). Password policies shall not enforce special character or minimum password rotation requirements for memorized secrets of users.
> **(h) Requirement:** For cases where technology doesn’t allow multi-factor authentication, these rules should be enforced: must have a minimum length of 14 characters and must support all printable ASCII characters.
> For emergency use accounts, these rules should be enforced: must have a minimum length of 14 characters, must support all printable ASCII characters, and passwords must be changed if used.
>

**Comment by hannes-ucsc** [comment]
We assign during triage.

**Comment by dsotirho-ucsc** [comment]
Assignee to describe differences between R4 and R5 with respect to IA-5.

**Comment by nolunwa-ucsc** [comment]
The following controls were added in Rev 5 for IA-5(1) and was not covered in Rev 4

a) Maintain a list of commonly-used, expected, or compromised passwords and update the list [Assignment: organization-defined frequency] and when organizational passwords are suspected to have been compromised directly or indirectly;
(b)Verify, when users create or update passwords, that the passwords are not found on the list of commonly-used, expected, or compromised passwords in IA-5(1)(a);
(e)Require immediate selection of a new password upon account recovery;
(f)Allow user selection of long passwords and passphrases, including spaces and all printable characters;
(g)Employ automated tools to assist the user in selecting strong password authenticators; and

**Comment by dsotirho-ucsc** [comment]
Assignee to update security architecture document with a description of how we implement this control or inherit its implementation from one of the CSPs.

**Comment by hannes-ucsc** [comment]
> Assignee to update security architecture document with a description of how we implement this control or inherit its implementation from one of the CSPs.

Done, see my suggested edits and comments. Assignee to review any edits and comments and to accepts suggested edits.

@nolunwa-ucsc, regarding g)

> (g)Employ automated tools to assist the user in selecting strong password authenticators; and

We should capture the requirement for a password manager in the policy. I recently went through this with every team member: https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1694710448346759

**Comment by nolunwa-ucsc** [comment]
SSP updated
