### ISSUE TITLE
"Unsupported attribute" error when deploying private API

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5656]
```
$ make deploy
...
Success! The configuration is valid.
...
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Failed to decode resource from state
│ 
│ Error decoding "aws_wafv2_web_acl.api_gateway" from previous state: unsupported attribute "excluded_rule"
╵
make[1]: *** [Makefile:52: apply] Error 1
make[1]: Leaving directory '/home/nadove/PycharmProjects/azul-sc/terraform'
make: *** [Makefile:93: terraform] Error 2
```

I think this is due to the recent [update to the TF AWS provider](https://github.com/DataBiosphere/azul/pull/5629/commits). The [old version](https://registry.terraform.io/providers/hashicorp/aws/4.58.0/docs/resources/wafv2_web_acl.html) mentioned the 
"excluded_rule" attribute, but the [new version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl.html) doesn't.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
Looks like we're running into https://github.com/hashicorp/terraform/issues/31052

**Comment by hannes-ucsc** [comment]
The obvious fix is to upgrade Terraform to the latest version or the latest 1.4.x version but that may turn into a rabbit whole. 

Based on https://github.com/hashicorp/terraform/issues/31052#issuecomment-1470056703

running `terraform apply -target aws_wafv2_web_acl.api_gateway` might be a workaround.

**Comment by nadove-ucsc** [comment]
Workaround appears to work.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Blocker makes this a freebie."

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Despite this being a freebie, we increased the estimate because even confirming the fix is significant work."

**Comment by hannes-ucsc** [comment]
This was verified as part of the PR: https://github.com/DataBiosphere/azul/pull/5780#issuecomment-1889700039
