### ISSUE TITLE
SC-12 Cryptographic Key Establishment and Management

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#5663]
- [ ] Cryptographic keys are not managed under a defined plan or set of procedures, the team needs to provide a cryptographic key management plan/procedures

- [ ] The team needs to provide documentation on how the SSH keypairs are being managed as the Asymmetric keys are not managed by AWS KMS

From NIST SP 800 rev 5

> Control: Establish and manage cryptographic keys when cryptography is employed within the
> system in accordance with the following key management requirements: [Assignment:
> organization-defined requirements for key generation, distribution, storage, access, and
> destruction].
> 
> CRYPTOGRAPHIC KEY ESTABLISHMENT AND MANAGEMENT | ASYMMETRIC KEYS
> Produce, control, and distribute asymmetric cryptographic keys using [Selection: NSAapproved key management technology and processes; prepositioned keying material;
> DoD-approved or DoD-issued Medium Assurance PKI certificates; DoD-approved or DoDissued Medium Hardware Assurance PKI certificates and hardware security tokens that
> protect the user’s private key; certificates issued in accordance with organization-defined
> requirements].

**Comment by dsotirho-ucsc** [comment]
Assignee to add a section to the security architecture document and describe how we handle cryptographic keys in the system.

**Comment by hannes-ucsc** [comment]
> Assignee to add a section to the security architecture document and describe how we handle cryptographic keys in the system.

Done. See suggested edits. Assignee to review and accept edits.

**Comment by nolunwa-ucsc** [comment]
SSP updated
