### ISSUE TITLE
Throttle alarms still go off during reindex in `prod`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5688]
Throttle thresholds might require re-tuning. An ongoing index of `dc33` catalog, for Promotion 2023-11-08 (#5685, PR #5686) caused alarms in both `indexer_contribute_throttles` and `indexer_aggregate_throttles`.

**azul-indexer_contribute_throttles-prod**:  SetT:150, MaxT:274
![Screen Shot 2023-11-09 at 10 48 02 AM](https://github.com/DataBiosphere/azul/assets/19215510/e04bee54-09bc-4bab-a066-8f0dca0c8fe3)

**azul-indexer_aggregate_throttles-prod**:  SetT:140, MaxT:175
![Screen Shot 2023-11-09 at 10 48 31 AM](https://github.com/DataBiosphere/azul/assets/19215510/656f9b85-c1cc-4a56-a08a-227c9c963a4a)

@hannes-ucsc: "We tried to addressed this in #5462 but something changed on the Lambda side, potentially the Python version upgrade. The reindex wasn't slower, neither were there any other signs of issues with the reindex so we think this is benign and we'll just adjust the thresholds again."
 

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
No demo. If this didn't work, we'd learn about it during alarm triage.
