### ISSUE TITLE
Building docker image fails due to Java and GPG key export

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#569]
Running `sudo docker build -t dcc-dashboard-service .` results in the following message:
`Step 31/32 : RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 && apt-get update && apt-get install -y curl dnsutils oracle-java8-installer ca-certificates
 ---> Running in b136c8ee42dd
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.qaysBfInjh/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys EEA14886
gpg: key 8F9293A1EEA14886: public key "Totally Legit Signing Key <mallory@example.org>" imported
gpg: cannot open '/dev/tty': No such device or address
The command '/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 && apt-get update && apt-get install -y curl dnsutils oracle-java8-installer ca-certificates' returned a non-zero code: 2
`

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-361)
┆Project Name: azul
┆Issue Number: AZUL-361

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

I put this in review as creation of the image and spinning it up seems to work. However, as this is part of the docker compose pool of containers and as I noticed another problem (BOARD-84) with the boardwalk docker, we might want to wait and test whether cgp-deployment passes the integration test and everything works as expected before merging it (both stories) into feature/commons.
