### ISSUE TITLE
ANVIL_1000G_2019_Dev fails to index w/ DUOS

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5695]
In `anvildev`, when attempting to index …
```JSON
[
    {
        "notification.bundle_fqid.entity_type": "dataset",
        "notification.bundle_fqid.source.id": "790795c4-49b1-4ac8-a060-207b92ea08c5",
        "notification.bundle_fqid.source.spec": "tdr:datarepo-dev-e53e74aa:snapshot/ANVIL_1000G_2019_Dev_20230609_ANV5_202306121732:/1",
        "notification.bundle_fqid.uuid": "677dd55c-3fa3-ab07-8c98-985d94d7577e"
    }
]
```
… the following error occurs:
```
Traceback (most recent call last):
  File "/var/task/azul/indexer/index_controller.py", line 179, in contribute
    contributions = self.transform(catalog, notification, delete)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/indexer/index_controller.py", line 217, in transform
    bundle = service.fetch_bundle(catalog, bundle_fqid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/indexer/index_service.py", line 183, in fetch_bundle
    return plugin.fetch_bundle(bundle_fqid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/plugins/repository/tdr.py", line 211, in fetch_bundle
    bundle = self._emulate_bundle(bundle_fqid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/plugins/repository/tdr_anvil/__init__.py", line 291, in _emulate_bundle
    return self._dataset_description(bundle_fqid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/plugins/repository/tdr_anvil/__init__.py", line 377, in _dataset_description
    description = self.tdr.get_duos(bundle_fqid.source)['studyDescription']
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/azul/terra.py", line 667, in get_duos
    duos_id = response['duosFirecloudGroup']['duosId']
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

[CW Insights.](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*2ffailed*2f*0a*7c*20display*20notification.bundle_fqid.entity_type*2c*20notification.bundle_fqid.source.id*2c*20notification.bundle_fqid.source.spec*2c*20notification.bundle_fqid.uuid*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*2020~queryId~'919ed87211427a7-d5e4d153-47a8337-258b208f-ff6d7fffe497ecbf7d8a36a~source~(~'*2faws*2flambda*2fazul-indexer-anvildev-contribute_retry)))

_Originally posted by @achave11-ucsc in https://github.com/DataBiosphere/azul/issues/5649#issuecomment-1813259271_

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "In this case we should use `.get` instead of `[]` so that we won't have to triage indexing failures resulting from this type of defect in TDR's database in the future. Similarly, any other permanent type of data issue with TDR or DUOS should result in description being null. For example a 404 response from DUOS falls into that category. Lastly, we should make sure that `hits[].datasets[].description` is absent from all index endpoints except `/index/datasets` and always present in the latter, but with a null value if the description could not be indexed due to a permanent data issue."

**Comment by hannes-ucsc** [comment]
For demo, show that reindex in `anvildev` ended with empty fail queues.
