### ISSUE TITLE
Webservice support for Projects Tab

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#57]
As a developer I want to see which projects my facet search contains.

DOD: The indexer creates a project oriented ElasticSearch document that includes all bundles in a project. Unit tests included.

### Implementation
| Reviewed? |
| --- |
| Not yet |

Add a request handler with routes:

```python
@app.route('/repository/projects', methods=['GET'], cors=True)
@app.route('/repository/projects/{project_id}', methods=['GET'], cors=True)
def get_project_data(project_id=None):
    # ...
```

The code in this method should be identical to `get_specimen_data`.

> We have done an impact assessment on `ElasticTransformDump.transform_request` into `azul.service.responseobjects.elastic_request_builder` but these is no update required in order to support the update on the webservice.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-46)
┆Project Name: azul
┆Issue Number: AZUL-46

**Comment by kozbo** [comment]
Needs to depend on UI specification

**Comment by theathorn** [comment]
@Hannes Use aggregations over specimen index?

**Comment by shiroyuki** [comment]
On the side now, decoding JSON strings with `ast.literal_eval` has come into my attention. This is potentially security issue and I have notified @mikebaumann for further discussion.
