### ISSUE TITLE
HCA dcp33 duplicate file 

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5701]
In reviewing dcp33, one issue has been found so far.  Quote from the [Slack message:](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1700149533675379?thread_ts=1698068019.262469&cid=C9XD6L0AD)

> The only issue is with project `95f07e6e-6a73-4e1b-a880-c83996b3aa5c` : `GSE149689_matrix.mtx.gz` appears twice. I think this is happening because the matrix was initially added to the portal when we didn't have analysis file. I've added the matrix to the project as an analysis file now, is it possible to drop the earlier version so that there is just one copy left?

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
I believe this is a defect in the [snapshot](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1700159576300329?thread_ts=1698068019.262469&cid=C9XD6L0AD) or the staging area. It should be addressed there.

<img width="1280" alt="Screen Shot 2023-11-16 at 10 29 09 AM" src="https://github.com/DataBiosphere/azul/assets/5143256/3cd4d4da-1be7-401a-a44c-f8ba0a6ce0c4">

**Comment by achave11-ucsc** [comment]
Assignee to continue conversation with wranglers about this.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Release 33 was approved despite the duplicate file. It is still uncertain as to what caused it. Assignee to ask Nate from the Broad."

**Comment by hannes-ucsc** [comment]
Conversation leads nowhere. I made clear that it's not Azul.

https://humancellatlas.slack.com/archives/C9XD6L0AD/p1701198272990449?thread_ts=1698068019.262469&cid=C9XD6L0AD
