### ISSUE TITLE
Consolidate dependency updates into single bi-weekly issue

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5703]
Use GitHub actions to create a new _upgrade_ issue every other Sunday. The interval is two weeks because that is also the maximum mitigation timeline required by FedRAMP for critical vulnerabilities (we get new critical CVEs all the time), and because that's the duration of an operator stint. The issue description should have checklist items for each dependency. Multiple PRs might be required, one per affected repository, but they will all connect to that issue. The issue will have a checklist in the description that summarizes the actions to be taken, typically one per dependency (or group of related dependencies).

Dependabot PRs will not be merged individually, instead their proposed changes will be consolidated and combined into the PRs mentioned above. When those PRs land, Dependabot will realize that the vulnerability is fixed and automatically close the PR it opened. The goal is to have no Dependabot PRs open for longer than two weeks.

Independently, we will track each applicable critical and high severity vulnerability in a separate _vulnerability_ issue. That issue will be opened by the operator when we are notified about the vulnerability, either by AWS Inspector, via a Dependabot PR or by other means like the GitLab security bulletins, if applicable.

The biweekly upgrade issue will have a checklist item to triage any open vulnerability issue that can be closed because the source reports it as fixed. If the reporting source is AWS Inspector, we consider the vulnerability as fixed if AWS Inspector shows the vulnerability as fixed in all stable deployments (currently `prod` and soon `anvilprod`). If the reporting source is Dependabot, we consider the vulnerability fixed if the Dependabot PR was closed (the vulnerable version of the dependency is absent from the `develop` branch) and the respective commit that updates it was promoted from `develop` to `prod`.

---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Assignee to decide on next steps.

**Comment by dsotirho-ucsc** [comment]
<img width="833" alt="Screen Shot 2023-11-20 at 12 24 09 PM" src="https://github.com/DataBiosphere/azul/assets/46407464/c210f4c5-e6da-4431-bccc-a1321ab11114">

**Comment by hannes-ucsc** [comment]
For demo, show ticket created by scheduled job. Show how to customize the schedule.
