### ISSUE TITLE
test_pfb_manifest should assert AVRO schema

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5704]
… as outlined in sketch below. However, this then fails in the assertion added to `test_manifest.py` due to ambiguity (yay!) with respect to naming fields. The following are all equivalent `{'name': 'fubar', namespace: 'foo.bar'}`, `{'name': 'bar.fubar', namespace: 'foo'}` and `{'name': 'foo.bar.fubar'}` and it seems that when the reader reads the schema (or when the writer writes it), it normalizes this ambiguity to some degree. We would need to normalize the schema we generate (before it goes into the writer) and make sure that Terra can still import it like that. One might also want to play with newer versions of `fastavro` for Python or writer/reader settings, if any, I don't know.

```diff
Index: test/service/test_pfb.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/service/test_pfb.py b/test/service/test_pfb.py
--- a/test/service/test_pfb.py  (revision 13382a94b35d6d8e7f54f08da3fef0c5ceabfff0)
+++ b/test/service/test_pfb.py  (date 1701151402381)
@@ -1,7 +1,3 @@
-import json
-from pathlib import (
-    Path,
-)
 from typing import (
     cast,
 )
@@ -15,33 +11,18 @@
 from azul.service import (
     avro_pfb,
 )
-from azul_test_case import (
-    AzulUnitTestCase,
+from pfb_test_case import (
+    PFBTestCase,
 )
 
 
-class TestPFB(AzulUnitTestCase):
+class TestPFB(PFBTestCase):
 
     def test_pfb_schema(self):
         self.maxDiff = None
         field_types = FileTransformer.field_types()
         schema = avro_pfb.pfb_schema_from_field_types(field_types)
-        fastavro.parse_schema(schema)
-        # Parsing successfully proves our schema is valid
-        with self.assertRaises(KeyError):
-            fastavro.parse_schema({'this': 'is not', 'an': 'avro schema'})
-
-        def to_json(records):
-            return json.dumps(records, indent=4, sort_keys=True)
-
-        results_file = Path(__file__).parent / 'data' / 'pfb_manifest.schema.json'
-        if results_file.exists():
-            with open(results_file, 'r') as f:
-                expected_records = json.load(f)
-            self.assertEqual(expected_records, json.loads(to_json(schema)))
-        else:
-            with open(results_file, 'w') as f:
-                f.write(to_json(schema))
+        self._assert_pfb_schema(schema)
 
     def test_pfb_metadata_object(self):
         metadata_entity = avro_pfb.pfb_metadata_entity(FileTransformer.field_types())
Index: test/service/test_manifest.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/service/test_manifest.py b/test/service/test_manifest.py
--- a/test/service/test_manifest.py (revision 13382a94b35d6d8e7f54f08da3fef0c5ceabfff0)
+++ b/test/service/test_manifest.py (date 1701151607465)
@@ -104,6 +104,9 @@
     AzulUnitTestCase,
     DCP1TestCase,
 )
+from pfb_test_case import (
+    PFBTestCase,
+)
 from service import (
     DocumentCloningTestCase,
     StorageServiceTestMixin,
@@ -194,7 +197,7 @@
     return wrapper
 
 
-class TestManifestEndpoints(ManifestTestCase):
+class TestManifestEndpoints(ManifestTestCase, PFBTestCase):
 
     def run(self,
             result: Optional[unittest.result.TestResult] = None
@@ -239,6 +242,8 @@
                     self.assertEqual(200, response.status_code)
                     pfb_file = BytesIO(response.content)
                     reader = fastavro.reader(pfb_file)
+                    schema = reader.writer_schema
+                    self._assert_pfb_schema(schema)
                     records = list(reader)
                     results_file = Path(__file__).parent / 'data' / 'pfb_manifest.results.json'
                     if results_file.exists():
Index: test/pfb_test_case.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/pfb_test_case.py b/test/pfb_test_case.py
new file mode 100644
--- /dev/null (date 1701151603417)
+++ b/test/pfb_test_case.py (date 1701151603417)
@@ -0,0 +1,34 @@
+import json
+from pathlib import (
+    Path,
+)
+import sys
+
+import fastavro
+
+from azul_test_case import (
+    AzulUnitTestCase,
+)
+
+
+class PFBTestCase(AzulUnitTestCase):
+    def _assert_pfb_schema(self, schema):
+        fastavro.parse_schema(schema)
+        # Parsing successfully proves our schema is valid
+        with self.assertRaises(KeyError):
+            fastavro.parse_schema({'this': 'is not', 'an': 'avro schema'})
+
+        def to_json(records):
+            return json.dumps(records, indent=4, sort_keys=True)
+
+        cls = type(self)
+        module = sys.modules[cls.__module__]
+        results_file = Path(
+            module.__file__).parent / 'data' / 'pfb_manifest.schema.json'
+        if results_file.exists():
+            with open(results_file, 'r') as f:
+                expected_records = json.load(f)
+            self.assertEqual(expected_records, json.loads(to_json(schema)))
+        else:
+            with open(results_file, 'w') as f:
+                f.write(to_json(schema))

```

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Assignee to provide description.

**Comment by hannes-ucsc** [comment]
Spike to apply patch and reproduce assertion failure mentioned in description. Normalize `name` vs `namespace` until test passes. If that doesn't work, see if there are any settings that can be adjusted to prevent the implicit normalization in the reader or the writer. See if newer versions of fastavro are available that affect the normalization or add settings to disable/control it. Any solution that makes the assertion pass, should also be tested again the Terra import endpoint to make sure that the generated AvroPFB files is still accepted by Terra.

**Comment by nadove-ucsc** [comment]
> Spike to apply patch and reproduce assertion failure mentioned in description.

Reproduction successful.

**Comment by nadove-ucsc** [comment]
I've [gotten the unit tests to pass](https://github.com/DataBiosphere/azul/pull/5778/commits/0c47d750b06025459602f24480e701039ce4171b).

**Comment by nadove-ucsc** [comment]
[Handover was successful](https://bvdp-saturn-dev.appspot.com/#workspaces/general-dev-billing-account/nadove-temp-handover-test/data) with the newly normalized schema.

**Comment by hannes-ucsc** [comment]
Passing unit tests will sufficiently demonstrate the efficacy of the resolution.
