### ISSUE TITLE
Aggregate throttle threshold exceeded during reindex

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5727]
The current indexer aggregate throttle threshold was exceeded during a reindex on anvilprod.

![Screen Shot 2023-11-27 at 2 25 04 PM](https://github.com/DataBiosphere/azul/assets/46407464/b7da9341-0ba1-4407-8c07-a12e6472f225)

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Throttle threshold should be increased to 300.

**Comment by dsotirho-ucsc** [comment]
Spike to produce a diagram for the aggregate non-retry throttles during the last reindex on `prod`.

**Comment by dsotirho-ucsc** [comment]
From 11/8 index of the `dcp33` catalog as part of the [prod promotion](https://github.com/DataBiosphere/azul/pull/5686).

[Cloudwatch metrics](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2?graph=~(metrics~(~(~'AWS*2fLambda~'Throttles~'FunctionName~'azul-indexer-prod-aggregate~(stat~'Sum)))~view~'timeSeries~stacked~false~start~'-PT2160H~end~'P0D~period~300~region~'us-east-1~title~'azul-indexer_aggregate_throttles-prod.alarm~annotations~(horizontal~(~(label~'Throttles*20*3e*20200*20for*201*20datapoints*20within*205*20minutes~value~200))))):

![Screen Shot 2023-11-28 at 1 35 44 PM](https://github.com/DataBiosphere/azul/assets/46407464/0a43a464-e32a-4299-ae50-6aa20141823c)

**Comment by hannes-ucsc** [comment]
OK, 300 seems to be a suitable threshold for both, `anvilprod` and `prod`.

**Comment by hannes-ucsc** [comment]
For demo, show that most recent reindex after this lands in `prod` did not trigger the alarm.

**Comment by dsotirho-ucsc** [comment]
> For demo, show that most recent after this lands in `prod` did not trigger the alarm.

The aggregate throttle threshold (300) set by this PR was exceeded during a reindex. A follow-up issue https://github.com/DataBiosphere/azul/issues/5837 (PR https://github.com/DataBiosphere/azul/pull/5852) will set the aggregate throttle threshold to 450.

![Screenshot 2024-01-23 at 1 35 10 PM](https://github.com/DataBiosphere/azul/assets/46407464/04d8e1b8-6746-44a0-91cc-1040ec41bd93)
