### ISSUE TITLE
Migrate reminders to GitHub schedule

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5733]

**Comment by dsotirho-ucsc** [comment]
Spike to enumerate all existing Slack reminders and their cadence.

**Comment by achave11-ucsc** [comment]
Two reminders were omitted. One was inactive (Sprint Retro) and the second was not associated with Azul or Team Boardwalk (Dockstore related).

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">Reminder</th>
<th title="Field #2">Cadence</th>
<th title="Field #3">Scheduled at (PT)</th>
</tr></thead>
<tbody><tr>
<td>Annual review of the rule set for audited events</td>
<td>Anually April 3rd</td>
<td>10:00</td>
</tr>
<tr>
<td>Keep docker Docker images updated</td>
<td>Biannually fist Monday</td>
<td>9:00</td>
</tr>
<tr>
<td>Keep Python updated</td>
<td>Quaterly first Monday</td>
<td>9:30</td>
</tr>
<tr>
<td>Update GitLab AMI and Docker images</td>
<td>Monthly first Monday</td>
<td>9:00</td>
</tr>
<tr>
<td>Review FedRAMP inventory</td>
<td>Monthly first Friday</td>
<td>9:00</td>
</tr>
<tr>
<td>Backup GitLab and update packages 2</td>
<td>Monthly second Monday</td>
<td>9:00</td>
</tr>
<tr>
<td>Backup GitLab and update packages 3</td>
<td>Monthly third Monday</td>
<td>9:00</td>
</tr>
<tr>
<td>Backup GitLab and update packages 4</td>
<td>Monthly fourth Monday</td>
<td>9:00</td>
</tr>
<tr>
<td>Backup GitLab and update packages 5</td>
<td>Monthly last Monday</td>
<td>9:00</td>
</tr>
<tr>
<td>Boardwalk Demo Reminder</td>
<td>Weekly on Mondays</td>
<td>15:00</td>
</tr>
<tr>
<td>OpenSearch updates reminder</td>
<td>Weekly on Mondays</td>
<td>9:00</td>
</tr>
<tr>
<td>Scan Amazon Inspector findings</td>
<td>Weekly on Mondays</td>
<td>9:00</td>
</tr>
<tr>
<td>Promotion Reminder</td>
<td>Weekly on Tuesdays</td>
<td>11:15</td>
</tr>
<tr>
<td>Review Snyk and DependaBot PRs reminder</td>
<td>Every weekday</td>
<td>9:00</td>
</tr>
</tbody></table>

**Comment by hannes-ucsc** [comment]
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">Reminder</th>
    <th class="tg-0pky">Cadence</th>
    <th class="tg-0pky">Time</th>
    <th class="tg-0pky">Action</th>
    <th class="tg-0pky">New cadence</th>
    <th class="tg-0pky">New time</th>
    <th class="tg-0pky">Remarks</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">Annual review of the rule set for audited events</td>
    <td class="tg-0pky">Anually April 3rd</td>
    <td class="tg-0pky">10:00</td>
    <td class="tg-0pky">Move to GitHub</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Keep docker Docker images updated</td>
    <td class="tg-0pky">Biannually fist Monday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by upgrade (#5703)</td>
  </tr>
  <tr>
    <td class="tg-0pky">Keep Python updated</td>
    <td class="tg-0pky">Quaterly first Monday</td>
    <td class="tg-0pky">9:30</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by upgrade (#5703)</td>
  </tr>
  <tr>
    <td class="tg-0pky">Update GitLab AMI and Docker images</td>
    <td class="tg-0pky">Monthly first Monday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by upgrade (#5703)</td>
  </tr>
  <tr>
    <td class="tg-0pky">Review FedRAMP inventory</td>
    <td class="tg-0pky">Monthly first Friday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Move to GitHub</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Backup GitLab and update packages 2</td>
    <td class="tg-0pky">Monthly second Monday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Move to GitHub</td>
    <td class="tg-0pky">Bi-weekly, alternate with upgrade</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Backup GitLab and update packages 3</td>
    <td class="tg-0pky">Monthly third Monday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by above</td>
  </tr>
  <tr>
    <td class="tg-0pky">Backup GitLab and update packages 4</td>
    <td class="tg-0pky">Monthly fourth Monday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by above</td>
  </tr>
  <tr>
    <td class="tg-0pky">Backup GitLab and update packages 5</td>
    <td class="tg-0pky">Monthly last Monday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by above</td>
  </tr>
  <tr>
    <td class="tg-0pky">Boardwalk Demo Reminder</td>
    <td class="tg-0pky">Weekly on Mondays</td>
    <td class="tg-0pky">15:00</td>
    <td class="tg-0pky">Keep on Slack</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">OpenSearch updates reminder</td>
    <td class="tg-0pky">Weekly on Mondays</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Move to GitHub</td>
    <td class="tg-0pky">Bi-weekly, same as backup</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Scan Amazon Inspector findings</td>
    <td class="tg-0pky">Weekly on Mondays</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by upgrade (#5703)</td>
  </tr>
  <tr>
    <td class="tg-0pky">Promotion Reminder</td>
    <td class="tg-0pky">Weekly on Tuesdays</td>
    <td class="tg-0pky">11:15</td>
    <td class="tg-0pky">Move to GitHub</td>
    <td class="tg-0pky">Same</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky"></td>
  </tr>
  <tr>
    <td class="tg-0pky">Review Snyk and DependaBot PRs reminder</td>
    <td class="tg-0pky">Every weekday</td>
    <td class="tg-0pky">9:00</td>
    <td class="tg-0pky">Retire</td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">Handled by upgrade (#5703)</td>
  </tr>
</tbody>
</table>

**Comment by hannes-ucsc** [comment]
For demo, show automatically scheduled promotion ticket.
