### ISSUE TITLE
Suppress Inspector findings for images not used within boundary

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5738]
Create an AWS Inspector [suppression](https://docs.aws.amazon.com/inspector/latest/user/findings-managing-supression-rules.html) rule for the Kibana, Cerebro and aws-siging-proxy images.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] ~… affect monitoring of the system~ https://github.com/DataBiosphere/azul/issues/5738#issuecomment-1839378168
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Assignee to provide description.

**Comment by hannes-ucsc** [comment]
Security review: this change will suppress AWS Inspector findings for three images that are exclusively used outside the security boundary. This will prevent alarms for any vulnerabilities detected in them. We still want to keep these images on ECR so that 1) they can't be updated without our knowledge and 2) we can review the vulnerabilities, but we don't need to address every vulnerability with the same urgency as we do for images used within the boundary.

**Comment by hannes-ucsc** [comment]
For demo, show that the AWS Inspector console displays no findings for the `_kibana`, `_cerebro` and `_signing_proxy` images, or that the findings can be easily filtered out by their suppression status.
