### ISSUE TITLE
Merging upgrade PR temporarily breaks personal deployments

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5743]
…by replacing images in ECR with newer versions, removing the images currently in use by personal deployments.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Assignee to provide description.

**Comment by dsotirho-ucsc** [comment]
The proposed fix is to make the deploy of the `shared` component a two-step process, with a `make -C terraform/shared deploy` step to be run before the upgrade PR is merged, and a `make -C terraform/shared post_merge` to be run after. 
The `deploy` target should cause the `copy_images_to_ecr.py` script to be run without the `--delete-unused` option, while the `post_merge` target should run the script with the option.

**Comment by dsotirho-ucsc** [comment]
Assignee to review proposed solution.

**Comment by hannes-ucsc** [comment]
`make -C terraform/shared apply_no_delete` for the first step, and `make -C terraform/shared apply` or `make -C terraform/shared` for the second. The second step can't just run the script directly. The script must be called by Terraform from a null_resource. During the first step, the actual script invocation should be short-circuited via an environment variable that's set temporarily by the Makefile before it invokes Terraform (`foo=… terraform …`).

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "I'll be taking this on together with #5746"

**Comment by hannes-ucsc** [comment]
Will be exercised when merging next upgrade PR.
