### ISSUE TITLE
Triage Airbrake errors

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#575]
See "asking Hannes" rows in https://docs.google.com/spreadsheets/d/18n4HJkmfJG2K6loHf31jcNVwPmaZ745t0fYZUFxT7Ug/edit#gid=0

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-366)
┆Project Name: azul
┆Issue Number: AZUL-366

**Comment by hannes-ucsc** [comment]
There is no point in investigating Airbrake warnings against `dev`, `integration` and personal deployments. They will break all the time and usually people will be aware of these problems already.

The above spreadsheet needs to be filtered for error messages originating from the `staging` and `prod` deployments.

**Comment by theathorn** [comment]
Spreadsheet is stale and is not the correct procedure for monitoring warnings.
