### ISSUE TITLE
Enable DNSSEC for anvil. and singlecell.gi.ucsc.edu

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5755]
https://github.com/DataBiosphere/azul/issues/5142#issue-1665389166

**Comment by hannes-ucsc** [comment]
Deferring for now.

**Comment by hannes-ucsc** [comment]
Changed my mind.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "No progress with ITS since November. Assignee to escalate this."

**Comment by hannes-ucsc** [comment]
Looks like UCSC ITS is not going to be able to help with this. Giving up.
