### ISSUE TITLE
Transient `repository_files` failure during IT

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5765]
GitLab `anvilprod` job [17208](https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17208):

```
2023-12-06 23:51:45,818    INFO MainThread test.integration_test: Beginning sub-test [repository_files] {'catalog': 'anvil3-it'}
2023-12-06 23:51:45,819    INFO MainThread test.integration_test: Making GET request to 'https://service.prod.anvil.gi.ucsc.edu/fetch/repository/files/0697899d-b3fb-4e05-80eb-eed84f1f9890?catalog=anvil3-it&version=2022-06-01T00%3A00%3A00.000000Z'
2023-12-06 23:51:45,819   DEBUG MainThread test.integration_test: … without request body
2023-12-06 23:51:56,469    INFO MainThread test.integration_test: Got 503 response after 10.650s from GET to https://service.prod.anvil.gi.ucsc.edu/fetch/repository/files/0697899d-b3fb-4e05-80eb-eed84f1f9890?catalog=anvil3-it&version=2022-06-01T00%3A00%3A00.000000Z
2023-12-06 23:51:56,469   DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '164', 'Connection': 'keep-alive', 'Date': 'Wed, 06 Dec 2023 23:51:56 GMT', 'x-amzn-RequestId': '3790759d-de94-4ebb-b69a-4ab95b0942e6', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Headers': 'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key', 'x-amz-apigw-id': 'Pi5a1HxAIAMEWJw=', 'X-Amzn-Trace-Id': 'Root=1-65710911-7cecdbaa2ceb348c03a90e99;Sampled=0;lineage=45061563:0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 db72f6ab1d9d27534c6158ca17e3af1c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD89-C3', 'X-Amz-Cf-Id': 'm8qkmNPqTIKWpGbTJZpAQ0aoq1V--r66oM6VDBwPud5zYcM3xgBtrA=='})
2023-12-06 23:51:56,469   DEBUG MainThread test.integration_test: … with response body b'{"Code":"ServiceUnavailableError","Message":"No response from https://data.terra.bio/ga4gh/drs/v1/objects/v2_6e7ddace-6276-37...'
2023-12-06 23:51:56,469    INFO MainThread test.integration_test: Failed sub-test [repository_files] {'catalog': 'anvil3-it'}
  test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [repository_files] (catalog='anvil3-it') ... FAIL  
```

[CloudWatch Logs](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2023-12-06T23*3a55*3a17.801Z~start~'2023-12-06T23*3a47*3a52.459Z~timeType~'ABSOLUTE~tz~'LOCAL~editorString~'fields*20*40timestamp*2c*20*40message*0a*7c*20filter*20*40requestId*20*3d*20*2783453835-1fe3-4458-a0d2-5e0880aa8c1d*27*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*20200~queryId~'1ac075cf647df1a-61fd9055-41a182-e8343c27-f1fe3619648561771c4b395~source~(~'*2faws*2flambda*2fazul-service-anvilprod))) on `anvilprod`:

```
[
    {
        "@timestamp": "2023-12-06 23:51:45.819",
        "@message": "START RequestId: 83453835-1fe3-4458-a0d2-5e0880aa8c1d Version: $LATEST\n"
    },
    {
        "@timestamp": "2023-12-06 23:51:45.820",
        "@message": "[INFO]\t2023-12-06T23:51:45.820Z\t83453835-1fe3-4458-a0d2-5e0880aa8c1d\tazul.chalice\tReceived GET request for '/fetch/repository/files/0697899d-b3fb-4e05-80eb-eed84f1f9890', with {\"query\": {\"catalog\": \"anvil3-it\", \"version\": \"2022-06-01T00:00:00.000000Z\"}, \"headers\": {\"accept-encoding\": \"identity\", \"cloudfront-forwarded-proto\": \"https\", \"cloudfront-is-desktop-viewer\": \"true\", \"cloudfront-is-mobile-viewer\": \"false\", \"cloudfront-is-smarttv-viewer\": \"false\", \"cloudfront-is-tablet-viewer\": \"false\", \"cloudfront-viewer-asn\": \"14618\", \"cloudfront-viewer-country\": \"US\", \"host\": \"service.prod.anvil.gi.ucsc.edu\", \"user-agent\": \"python-urllib3/1.26.18\", \"via\": \"1.1 db72f6ab1d9d27534c6158ca17e3af1c.cloudfront.net (CloudFront)\", \"x-amz-cf-id\": \"m8qkmNPqTIKWpGbTJZpAQ0aoq1V--r66oM6VDBwPud5zYcM3xgBtrA==\", \"x-amzn-trace-id\": \"Root=1-65710911-7cecdbaa2ceb348c03a90e99\", \"x-forwarded-for\": \"35.168.152.160, 130.176.98.88\", \"x-forwarded-port\": \"443\", \"x-forwarded-proto\": \"https\"}}."
    },
    …
    {
        "@timestamp": "2023-12-06 23:51:46.325",
        "@message": "[INFO]\t2023-12-06T23:51:46.325Z\t83453835-1fe3-4458-a0d2-5e0880aa8c1d\tazul.drs\tObtained URL pattern 'https://data.terra.bio/ga4gh/drs/v1/objects/{$id}' from resource 'National Human Genome Research Institute'"
    },
    {
        "@timestamp": "2023-12-06 23:51:46.325",
        "@message": "[INFO]\t2023-12-06T23:51:46.325Z\t83453835-1fe3-4458-a0d2-5e0880aa8c1d\tazul.terra\tMaking GET request to 'https://data.terra.bio/ga4gh/drs/v1/objects/v2_6e7ddace-6276-37c9-a0c2-40609933d433'"
    },
    {
        "@timestamp": "2023-12-06 23:51:46.325",
        "@message": "[DEBUG]\t2023-12-06T23:51:46.325Z\t83453835-1fe3-4458-a0d2-5e0880aa8c1d\tazul.terra\t… without request body"
    },
    {
        "@timestamp": "2023-12-06 23:51:51.438",
        "@message": "[WARNING]\t2023-12-06T23:51:51.437Z\t83453835-1fe3-4458-a0d2-5e0880aa8c1d\turllib3.connectionpool\tRetrying (LimitedRetry(total=None, connect=0, read=0, redirect=0, status=0)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='data.terra.bio', port=443): Read timed out. (read timeout=5)\")': /ga4gh/drs/v1/objects/v2_6e7ddace-6276-37c9-a0c2-40609933d433"
    },
    {
        "@timestamp": "2023-12-06 23:51:56.464",
        "@message": "[DEBUG]\t2023-12-06T23:51:56.463Z\t83453835-1fe3-4458-a0d2-5e0880aa8c1d\tazul.chalice\tReturning 503 response with headers {\"Access-Control-Allow-Origin\": \"*\", \"Access-Control-Allow-Headers\": \"Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key\", \"Strict-Transport-Security\": \"max-age=31536000; includeSubDomains\"}. See next line for the first 1024 characters of the body.\n{\"Code\": \"ServiceUnavailableError\", \"Message\": \"No response from https://data.terra.bio/ga4gh/drs/v1/objects/v2_6e7ddace-6276-37c9-a0c2-40609933d433 within 5 seconds\"}"
    }
]
```

-----

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Now that we properly timebox DRS requests, we should retry the Azul request during IT. Assignee to consider the implications."

**Comment by achave11-ucsc** [comment]
This happened again in IT for `hammerbox`. https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17508

**Comment by achave11-ucsc** [comment]
Multiple occurrence for `anvilprod`,

`Dec 12, 2023 1:47pm PST`: https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17569#L18.

`Dec 12, 2023 3:27pm PST`: https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17589,

`Dec 12, 2023 4:08pm PST`: https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17592.

`Dec 12, 2023 8:13pm PST`: https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17615

`Dec 12, 2023 10:59pm PST`: https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17632#L15

`Dec 13, 2023 8:21am PST`: https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17673#L13 [[reference below](https://github.com/DataBiosphere/azul/issues/5765#issuecomment-1854400294)]

**Comment by hannes-ucsc** [comment]
The picture might be clouded a bit by the fact that my original attempt at fixing #5536 and #5720 was broken and actually made things worse for `/repository/files` by including the DRS requests in a broken implementation of restricted timings. I had to chase it with another PR #5777. We'll wait until that lands in `prod` (hopefully tomorrow), establish how many 503s Azul returns for `/repository/files` with restricted timings fixed and re-evaluate the validity and urgency of this issue.

**Comment by hannes-ucsc** [comment]
There is already [one recurrence](https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17615#L14) with PR #5777 merged, so we're going ahead with a fix.

**Comment by hannes-ucsc** [comment]
As is standard procedure, every IT failure must be tracked either as a new issue or as a comment to an existing issue. The absence of any such comments on this issue for two weeks after this lands in production will be sufficient evidence for the efficacy of the fix.

**Comment by hannes-ucsc** [comment]
For demo, show absence of comments linking to IT failures.
