### ISSUE TITLE
Add secondary analysis community pipeline attribute to the indexed facets list

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#577]
Make the Community/Blessed pipeline attribute a searchable facet.
See humancellatlas/secondary-analysis#406

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-368)
┆Project Name: azul
┆Issue Number: AZUL-368

**Comment by kbergin** [comment]
This will be blocked by us adding this metadata in this ticket [secondary-analysis/406](https://app.zenhub.com/workspaces/dcp-backlogs-5ac7bcf9465cb172b77760d9/issues/humancellatlas/secondary-analysis/406)

**Comment by melainalegaspi** [comment]
This was relevant for DCP1, not DCP2.
