### ISSUE TITLE
AWS event GetMacieSession results in AccessDenied error

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5779]
… causing alarms to go off. This issue has been observe in `anvildev`, `anvilprod` as well as HCA `prod`.

<details><summary>AnVIL dev</summary>
<p>

```JSON
[
    {
        "@timestamp": "2023-12-09 21:15:24.273",
        "errorCode": "AccessDenied",
        "eventSource": "macie2.amazonaws.com",
        "eventName": "GetMacieSession",
        "eventCategory": "Management",
        "userIdentity.invokedBy": "config.amazonaws.com",
        "userIdentity.arn": "arn:aws:sts::289950828509:assumed-role/azul-aws_config/configLambdaExecution"
    },
    {
        "@timestamp": "2023-12-10 21:21:10.148",
        "errorCode": "AccessDenied",
        "eventSource": "macie2.amazonaws.com",
        "eventName": "GetMacieSession",
        "eventCategory": "Management",
        "userIdentity.invokedBy": "config.amazonaws.com",
        "userIdentity.arn": "arn:aws:sts::289950828509:assumed-role/azul-aws_config/configLambdaExecution"
    },
    {
        "@timestamp": "2023-12-11 21:21:20.298",
        "errorCode": "AccessDenied",
        "eventSource": "macie2.amazonaws.com",
        "eventName": "GetMacieSession",
        "eventCategory": "Management",
        "userIdentity.invokedBy": "config.amazonaws.com",
        "userIdentity.arn": "arn:aws:sts::289950828509:assumed-role/azul-aws_config/configLambdaExecution"
    }
]
```
<img width="1297" alt="Screen Shot 2023-12-12 at 9 00 21 AM" src="https://github.com/DataBiosphere/azul/assets/19215510/b2706126-051c-4a05-b1d1-0646c69f6c25">

</p>
</details> 

<details><summary>AnVIL prod</summary>
<p>

```JSON
[
    {
        "@timestamp": "2023-12-10 16:04:15.177",
        "errorCode": "AccessDenied",
        "eventSource": "macie2.amazonaws.com",
        "eventName": "GetMacieSession",
        "eventCategory": "Management",
        "userIdentity.invokedBy": "config.amazonaws.com",
        "userIdentity.arn": "arn:aws:sts::465330168186:assumed-role/azul-aws_config/configLambdaExecution"
    },
    {
        "@timestamp": "2023-12-11 16:47:08.902",
        "errorCode": "AccessDenied",
        "eventSource": "macie2.amazonaws.com",
        "eventName": "GetMacieSession",
        "eventCategory": "Management",
        "userIdentity.invokedBy": "config.amazonaws.com",
        "userIdentity.arn": "arn:aws:sts::465330168186:assumed-role/azul-aws_config/configLambdaExecution"
    },
    {
        "@timestamp": "2023-12-12 16:47:52.817",
        "errorCode": "AccessDenied",
        "eventSource": "macie2.amazonaws.com",
        "eventName": "GetMacieSession",
        "eventCategory": "Management",
        "userIdentity.invokedBy": "config.amazonaws.com",
        "userIdentity.arn": "arn:aws:sts::465330168186:assumed-role/azul-aws_config/configLambdaExecution"
    }
]
```
<img width="1293" alt="Screen Shot 2023-12-12 at 9 00 29 AM" src="https://github.com/DataBiosphere/azul/assets/19215510/13dc62a7-1206-4b55-b117-30e73f2f2aca">

</p>
</details> 

<details><summary>HCA prod</summary>
<p>

```JSON
[
    {
        "@timestamp": "2023-12-12 13:51:57.502",
        "errorCode": "AccessDenied",
        "eventSource": "macie2.amazonaws.com",
        "eventName": "GetMacieSession",
        "eventCategory": "Management",
        "userIdentity.invokedBy": "config.amazonaws.com",
        "userIdentity.arn": "arn:aws:sts::542754589326:assumed-role/azul-aws_config/configLambdaExecution"
    }
]
```

<img width="1295" alt="Screen Shot 2023-12-12 at 10 24 16 AM" src="https://github.com/DataBiosphere/azul/assets/19215510/6ec033d9-74bd-47da-920b-a6bea1b857c1">

</p>
</details> 

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We provably just need to add this action to whatever IAM policy we use to grant permissions to Amazon Inspector. I don't remember if we track the policy in code or if this is just a policy we maintain manually."

**Comment by achave11-ucsc** [comment]
The AWS Managed role policy we use for services like inspector [AWS_ConfigRole](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWS_ConfigRole.html) was recently updated (December 04, 2023, 15:44) to add permission for this service. However, our role `azul-aws_config` which uses that managed policy has not been updated since [October 26, 2022, 19:13](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/roles/details/azul-aws_config?section=revoke_sessions). It's likely that tainting and recreating the policy might fix this problem.

**Comment by achave11-ucsc** [comment]
AWS Support ticket in `prod` account has been opened.

**Comment by achave11-ucsc** [comment]
AWS support has replied, and the ticket is now in pending Amazon action state.

>…
Upon further checking internally , I could see that this is a reported issue as per the Config team and they have mentioned "AWS config launched support for new resource type AWS::Macie::Session. AWS config calls GetMacieSession to describe the AWS::Macie::Session. If the account has disabled AWS::Macie::Session, the API raises AccessDeniedException instead of RecordNotFoundException, though AWS Config handles it correctly but AWS::Macie::Session service records this exception in CloudTrail logs. To mitigate the exception in CloudTrail logs issue, AWS Config reverted the changes to record AWS::Macie::Session resource type. AWS Config is working with AWS::Macie::Session team to correct the behaviour of this API."
Thus I have reached out to the internal team for further confirmation if there has been any fix deployed for the same. 
Rest assured, I will let you know as soon as I get an update from them. Until then, I am flipping the case status to ‘Pending Amazon Action’.
…

**Comment by achave11-ucsc** [comment]
Assignee to monitor support ticket.

**Comment by achave11-ucsc** [comment]
AWS support has replied,

> They have informed that Security Hub Control [Macie.1] ( https://docs.aws.amazon.com/securityhub/latest/userguide/macie-controls.html#macie-1 ) checks whether Amazon Macie is enabled for an account. The control is backed by macie-status-check ( https://docs.aws.amazon.com/config/latest/developerguide/macie-status-check.html ) config rule.
> 
> As per the rule-logic, the control produces a FAILED finding if Macie is not enabled in an account. Config use the get_macie_session() API and if the response of the call is "AccessDeniedException" - the rule results in a NON_COMPLIANT. CloudTrail logs the events independently and alerts customers when there is an AccessDenied error. This is something Macie team is checking with the CloudTrail team however there is no ETA on the fix unfortunately.
> 
> This a periodic control that runs every 24 hours, the customers would continue to get a FAILED finding if they have the control enabled and have Macie disabled.
> 
> Internal team has additionally mentioned that if customers are looking to avoid these errors as of now, please request the customer to disable Macie.1 control.
> For detailed instructions on how to disable a control, please see Disabling controls in the AWS Security Hub documentation [1].
>

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Considering that Macie.1 is part of Amazon's NIST 800.53 r5 standard, we should enable Macie. This will hopefully prevent the access denied error and eliminate the noisy alarm."

**Comment by achave11-ucsc** [comment]
Permission enhancements to AWS Roles:

- [ ] `developer:  AmazonMacieFullAccess`
- [ ] `viewer:  AmazonMacieReadOnlyAccess`

**Comment by achave11-ucsc** [comment]
Although the `developer` role has been provisioned with the `AmazonMacieFullAccess` AWS managed policy, navigating the Macie console still causes many AccessDenied type of alarms for the deployment. This service seems to be targeted specifically to account owners and/or administrators like the Billing service, where an administrator (role selected) was generating alarms by navigating the Billing console. Additionally, it isn't evident from the console UI that these errors are being generated.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Let's not enable Macie just yet. I have the feeling that it will not prevent the warning. For now let's just follow recommendation by AWS Support in production and see what happens. Eventually we still will enable Macie, but as a separate issue."

**Comment by achave11-ucsc** [comment]
@dsotirho-ucsc  and I, have disabled the `Macie.1` control check from the Security Hub console. With this check disabled the AccesDenied alarms should desist, will confirm tomorrow after 06:30 when this check usually happens for the `prod` account.

**Comment by achave11-ucsc** [comment]
Confirming the the `Macie.1` check has been disabled in `prod`. As it may be apparent from the previous occurrence cadence, `prod` did not register this alarm for today.

![Screenshot 2024-01-24 at 9 20 50 AM](https://github.com/DataBiosphere/azul/assets/19215510/73f8b166-720c-4f05-af87-7ee6abf9ee14)

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Until we enable Macie, we should disable the control as outlined in the above experiment, but using Terraform config ([aws_securityhub_standards_control](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_standards_control)). We should also revert the effects of that experiment in case they interfere with the Terraform changes. An earlier experiment enabled Macie in `dev`. That must also be reverted. We also need an issue to enable Macie. The author of the issue should record in it that enabling Macie and applying the recommended permission changes still resulted in access denied alarms when anyone visits the Macie console."

**Comment by dsotirho-ucsc** [comment]
Assignee to revert yesterday's experiment, and then assign @achave11-ucsc for the remaining work.

**Comment by dsotirho-ucsc** [comment]
> Assignee to revert yesterday's experiment, and then assign @achave11-ucsc for the remaining work.

Re-enabled `Macie.1` control.

![Screenshot 2024-01-24 at 1 03 11 PM](https://github.com/DataBiosphere/azul/assets/46407464/e653b02a-4b4b-423f-b4f2-186d311e6be5)

**Comment by achave11-ucsc** [comment]
Disabling the control via terraform seems unlikely, www:://github.com/hashicorp/terraform-provider-aws/issues/27686

**Comment by hannes-ucsc** [comment]
Cessation of alarm suffices as demo.
