### ISSUE TITLE
Create blacklist of projects NOT to be indexed in prod

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#578]
Currently we have an Azul whitelist but a blacklist if better for the (more usual) case that only a few projects will cause problems and need to be black-listed.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-369)
┆Project Name: azul
┆Issue Number: AZUL-369

**Comment by hannes-ucsc** [comment]
This is only for PROD.
