### ISSUE TITLE
Create Google client ids for HCA managed access environments

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#5782]
We are working on setting up the HCA managed-access pilot environments, and I need some Google client IDs for the new environments. We need client IDs configured for the following:

**Dev**
localhost:3000
CC-Dev: https://ma-pilot.explore.data.humancellatlas.dev.clevercanary.com/
Dev: https://ma-pilot.explore.data.dev.singlecell.gi.ucsc.edu/

**Prod**
Prod: https://ma-pilot.explore.data.humancellatlas.org/

**Comment by hannes-ucsc** [comment]
Client IDs:

prod: 473200283737-4pt6e9lraf5jbb650f9kp7ethelv4a8l.apps.googleusercontent.com
dev: 713613812354-ckf448r07ahvh8o1hjfj38tp91j9gpq8.apps.googleusercontent.com

**Comment by NoopDog** [comment]
Thanks!
