### ISSUE TITLE
Get project `platform-hca-prod` allow-listed in Terra production

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5783]
Without this, logging into the pilot site will produce a 401 or 403 from TDR due to access tokens being rejected. Azul will propagate the error to DB. The person at the Broad doing this will likely send the request up the chain where it will likely have to be approved by AO. We need to ensure that this is on their radar and that they are at least tentatively in agreement.

**Comment by hannes-ucsc** [comment]
In fact, I'm not sure who to ask. For AnVIL, Jack Warren ultimately did the hands-on work but they are not on the HCA Slack.

**Comment by hannes-ucsc** [comment]
During the compliance meeting, it was suggested that I ask Nicolas from the Broad. I just did:

https://humancellatlas.slack.com/archives/C01360XN04S/p1702578969208689

**Comment by bvizzier-ucsc** [comment]
Okay, I just updated the thread that the ISA has been signed and that, to our knowledge, there is nothing else blocking the HCA Data Explorer from being allow listed.  

https://humancellatlas.slack.com/archives/C01360XN04S/p1703192876472989?thread_ts=1702578969.208689&cid=C01360XN04S

**Comment by hannes-ucsc** [comment]
This was [completed](https://humancellatlas.slack.com/archives/C01360XN04S/p1704473718303859?thread_ts=1702578969.208689&cid=C01360XN04S) on Jan 5.
