### ISSUE TITLE
Add missing prod datasets to indexing whitelist

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#579]
Currently Completely Missing Datasets:
| Accountable | Dataset     | Project UUID                           |
|-------------|-------------|--------------------------------------|
| 12          | peer        | fd1d163d-d6a7-41cd-b3bc-9d77ba9a36fe |
| 8           | neuron_diff | f8880be0-210c-4aa3-9348-f5a423e07421 |
| 10          | ido_amit    | 0c7bbbce-3c70-4d6b-a443-1b92c1f205c8 |
| 11          | humphreys   | 1630e3dc-5501-4faf-9726-2e2c0b4da6d7 |

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-370)
┆Project Name: azul
┆Issue Number: AZUL-370

**Comment by hannes-ucsc** [comment]
@theathorn we use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case) for issue titles. Title case is too noisy visually, tedious to type and harder to get right.

**Comment by hannes-ucsc** [comment]
@GPelay, please cherry pick the commit and file PR against `dev` as well. Use `Add more projects to whitelist for prod (fixes #579)` as the title.

**Comment by hannes-ucsc** [comment]
@GPelayo ^
