### ISSUE TITLE
Subtest `repository_files` in IT fails with an assertion error

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5794]
https://gitlab.prod.anvil.gi.ucsc.edu/ucsc/azul/-/jobs/17859/raw

```
…
2023-12-14 17:27:00,726    INFO MainThread test.integration_test: Beginning sub-test [repository_files] {'catalog': 'anvil3-it'}
2023-12-14 17:27:00,727    INFO MainThread test.integration_test: Making GET request to 'https://service.prod.anvil.gi.ucsc.edu/fetch/repository/files/f6c7670c-2fa2-48eb-aa74-31b7ec94b148?catalog=anvil3-it&version=2022-06-01T00%3A00%3A00.000000Z'
2023-12-14 17:27:00,727   DEBUG MainThread test.integration_test: … without request body
2023-12-14 17:27:13,203    INFO MainThread test.integration_test: Got 200 response after 12.476s from GET to https://service.prod.anvil.gi.ucsc.edu/fetch/repository/files/f6c7670c-2fa2-48eb-aa74-31b7ec94b148?catalog=anvil3-it&version=2022-06-01T00%3A00%3A00.000000Z
2023-12-14 17:27:13,204   DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'Content-Type': 'application/json', 'Content-Length': '1035', 'Connection': 'keep-alive', 'Date': 'Thu, 14 Dec 2023 17:27:13 GMT', 'x-amzn-RequestId': '78106650-10f0-4a15-8922-dde51ff0efed', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Access-Control-Allow-Headers': 'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key', 'x-amz-apigw-id': 'P8YlcGtKoAMEopw=', 'X-Amzn-Trace-Id': 'Root=1-657b3aef-178257e03a3343e74146d6dd;Sampled=0;lineage=45061563:0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 51391527dd8c879c45b44b119905c872.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD89-C3', 'X-Amz-Cf-Id': 'Ul50UYg5UQISCs_BcDu-t2Apu8WBuBU0_T4qN12bINo-SrSNKWIEqg=='})
2023-12-14 17:27:13,204   DEBUG MainThread test.integration_test: … with response body b'{"Status": 302, "Location": "https://storage.googleapis.com/fc-47de7dae-e8e6-429c-b760-b4ba49136eee/summary_stats/variant_cou...'
2023-12-14 17:27:13,205    INFO MainThread test.integration_test: Making GET request to 'https://storage.googleapis.com/fc-47de7dae-e8e6-429c-b760-b4ba49136eee/summary_stats/variant_counts_windows/dchr20.GIH.counts.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=tdr-ingest-sa%40datarepo-9e80499e.iam.gserviceaccount.com%2F20231214%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20231214T172713Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&requestedBy=azul-ucsc-1-public-anvilprod%40platform-anvil-prod.iam.gserviceaccount.com&userProject=datarepo-02ad84ea&X-Goog-Signature=592e011867cdc11a940295919de1c105f6bc43230b1b43bac70d84572642603479a24dde23fc41497261d12527b4c371533334279dbba6c31b3a7a0ff865e3f9ec352f0156c12cb592eb72058991d0e02d7997a9119eb3acd937711f9cda6b5f9beb6638fd25741e677572bcb3a08822e1889ccf2329a4d4ac94e7cdae0f1f234d9caf72f35817e952b277484c05e05d39462a207631f1d90fe7b283758785136c671a2c7aedcb50563a2cc0c6c608cb461ae60dd7e40a5cda690326496f5b42dea5d24d815ee495ccaf8a0281ee3feda43a0846d8173196f86a8063a8a0e7a67068c689dbb09859f4fd7bdb8f2859e08d43342c8128b1d4d003208c0fffa0d7'
2023-12-14 17:27:13,205   DEBUG MainThread test.integration_test: … without request body
2023-12-14 17:27:13,395    INFO MainThread test.integration_test: Got 200 response after 0.189s from GET to https://storage.googleapis.com/fc-47de7dae-e8e6-429c-b760-b4ba49136eee/summary_stats/variant_counts_windows/dchr20.GIH.counts.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=tdr-ingest-sa%40datarepo-9e80499e.iam.gserviceaccount.com%2F20231214%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20231214T172713Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&requestedBy=azul-ucsc-1-public-anvilprod%40platform-anvil-prod.iam.gserviceaccount.com&userProject=datarepo-02ad84ea&X-Goog-Signature=592e011867cdc11a940295919de1c105f6bc43230b1b43bac70d84572642603479a24dde23fc41497261d12527b4c371533334279dbba6c31b3a7a0ff865e3f9ec352f0156c12cb592eb72058991d0e02d7997a9119eb3acd937711f9cda6b5f9beb6638fd25741e677572bcb3a08822e1889ccf2329a4d4ac94e7cdae0f1f234d9caf72f35817e952b277484c05e05d39462a207631f1d90fe7b283758785136c671a2c7aedcb50563a2cc0c6c608cb461ae60dd7e40a5cda690326496f5b42dea5d24d815ee495ccaf8a0281ee3feda43a0846d8173196f86a8063a8a0e7a67068c689dbb09859f4fd7bdb8f2859e08d43342c8128b1d4d003208c0fffa0d7
2023-12-14 17:27:13,395   DEBUG MainThread test.integration_test: … with response headers HTTPHeaderDict({'X-GUploader-UploadID': 'ABPtcPr97tilFR4kHP9QPnt9W-chNXbW_NWLgyBwMEtumNFUcd91ymzYlh4OWWuApF3ZYlOSO34vA8w2Pw', 'Last-Modified': 'Fri, 26 Aug 2022 16:31:18 GMT', 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'x-goog-generation': '1661531478218204', 'x-goog-metageneration': '1', 'x-goog-stored-content-encoding': 'identity', 'x-goog-stored-content-length': '0', 'x-goog-meta-x-goog-reserved-source-generation': '1661530046474186', 'Content-Type': 'text/plain', 'x-goog-hash': 'crc32c=AAAAAA==, md5=1B2M2Y8AsgTpgAmY7PhCfg==', 'x-goog-storage-class': 'STANDARD', 'Accept-Ranges': 'bytes', 'Content-Length': '0', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'Date': 'Thu, 14 Dec 2023 17:27:13 GMT', 'Server': 'UploadServer', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
2023-12-14 17:27:13,395   DEBUG MainThread test.integration_test: … with a streamed response body
2023-12-14 17:27:13,395    INFO MainThread test.integration_test: Failed sub-test [repository_files] {'catalog': 'anvil3-it'}

  test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [repository_files] (catalog='anvil3-it') ... FAIL
…
======================================================================
FAIL: test_indexing (integration_test.IndexingIntegrationTest.test_indexing) [repository_files] (catalog='anvil3-it')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builds/ucsc/azul/test/integration_test.py", line 411, in subTest
    yield
  File "/builds/ucsc/azul/test/integration_test.py", line 988, in _test_repository_files
    self._validate_file_response(response, self._file_ext(file))
  File "/builds/ucsc/azul/test/integration_test.py", line 1014, in _validate_file_response
    self._validate_file_content(response, file_ext)
  File "/builds/ucsc/azul/test/integration_test.py", line 1005, in _validate_file_content
    self.assertEqual(1, len(content.read(1)))
AssertionError: 1 != 0
----------------------------------------------------------------------
Ran 15 tests in 1346.798s
FAILED (failures=1, skipped=1)
make: *** [Makefile:241: integration_test] Error 1
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
The file might have been empty. An attempt to download the contents from the Google signed URL was unsuccessful, it seems like there's nothing to download from the provided URL.

<table class="table table-bordered table-hover table-condensed">
<thead><tr><th title="Field #1">@timestamp</th>
<th title="Field #2">@message</th>
<th title="Field #3">@log</th>
</tr></thead>
<tbody><tr>
<td>2023-12-14 17:27:00.752</td>
<td>START RequestId: d52d8472-9a3d-4847-a94b-dd495996227e Version: $LATEST<br/></td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:00.752</td>
<td>[INFO]	2023-12-14T17:27:00.752Z	d52d8472-9a3d-4847-a94b-dd495996227e	azul.chalice	Received GET request for &#39;/fetch/repository/files/f6c7670c-2fa2-48eb-aa74-31b7ec94b148&#39;, with {&quot;query&quot;: {&quot;catalog&quot;: &quot;anvil3-it&quot;, &quot;version&quot;: &quot;2022-06-01T00:00:00.000000Z&quot;}, &quot;headers&quot;: {&quot;accept-encoding&quot;: &quot;identity&quot;, &quot;cloudfront-forwarded-proto&quot;: &quot;https&quot;, &quot;cloudfront-is-desktop-viewer&quot;: &quot;true&quot;, &quot;cloudfront-is-mobile-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-smarttv-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-tablet-viewer&quot;: &quot;false&quot;, &quot;cloudfront-viewer-asn&quot;: &quot;14618&quot;, &quot;cloudfront-viewer-country&quot;: &quot;US&quot;, &quot;host&quot;: &quot;service.prod.anvil.gi.ucsc.edu&quot;, &quot;user-agent&quot;: &quot;python-urllib3/1.26.18&quot;, &quot;via&quot;: &quot;1.1 51391527dd8c879c45b44b119905c872.cloudfront.net (CloudFront)&quot;, &quot;x-amz-cf-id&quot;: &quot;OhuKMdeDonyPQiN2DP15opjHOIiqHZBvLWaq4TybRT8h54ZaZTT-6A==&quot;, &quot;x-amzn-trace-id&quot;: &quot;Root=1-657b3ae4-5f7e54562a47e5287ec1d28e&quot;, &quot;x-forwarded-for&quot;: &quot;35.168.152.160, 130.176.98.94&quot;, &quot;x-forwarded-port&quot;: &quot;443&quot;, &quot;x-forwarded-proto&quot;: &quot;https&quot;}}.</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:01.229</td>
<td>[INFO]	2023-12-14T17:27:01.229Z	d52d8472-9a3d-4847-a94b-dd495996227e	azul.terra	Making GET request to &#39;https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef&#39;</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:01.229</td>
<td>[DEBUG]	2023-12-14T17:27:01.229Z	d52d8472-9a3d-4847-a94b-dd495996227e	azul.terra	… without request body</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:06.296</td>
<td>[DEBUG]	2023-12-14T17:27:06.296Z	d52d8472-9a3d-4847-a94b-dd495996227e	azul.chalice	Returning 503 response with headers {&quot;Access-Control-Allow-Origin&quot;: &quot;*&quot;, &quot;Access-Control-Allow-Headers&quot;: &quot;Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key&quot;, &quot;Strict-Transport-Security&quot;: &quot;max-age=31536000; includeSubDomains&quot;}. See next line for the first 1024 characters of the body.<br/>{&quot;Code&quot;: &quot;ServiceUnavailableError&quot;, &quot;Message&quot;: &quot;No response from https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef within 5 seconds&quot;}</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:06.298</td>
<td>REPORT RequestId: d52d8472-9a3d-4847-a94b-dd495996227e	Duration: 5545.76 ms	Billed Duration: 5546 ms	Memory Size: 2048 MB	Max Memory Used: 167 MB	<br/></td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:06.339</td>
<td>START RequestId: 86528675-501e-4785-aa89-b165f653bec3 Version: $LATEST<br/></td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:06.340</td>
<td>[INFO]	2023-12-14T17:27:06.340Z	86528675-501e-4785-aa89-b165f653bec3	azul.chalice	Received GET request for &#39;/fetch/repository/files/f6c7670c-2fa2-48eb-aa74-31b7ec94b148&#39;, with {&quot;query&quot;: {&quot;catalog&quot;: &quot;anvil3-it&quot;, &quot;version&quot;: &quot;2022-06-01T00:00:00.000000Z&quot;}, &quot;headers&quot;: {&quot;accept-encoding&quot;: &quot;identity&quot;, &quot;cloudfront-forwarded-proto&quot;: &quot;https&quot;, &quot;cloudfront-is-desktop-viewer&quot;: &quot;true&quot;, &quot;cloudfront-is-mobile-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-smarttv-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-tablet-viewer&quot;: &quot;false&quot;, &quot;cloudfront-viewer-asn&quot;: &quot;14618&quot;, &quot;cloudfront-viewer-country&quot;: &quot;US&quot;, &quot;host&quot;: &quot;service.prod.anvil.gi.ucsc.edu&quot;, &quot;user-agent&quot;: &quot;python-urllib3/1.26.18&quot;, &quot;via&quot;: &quot;1.1 51391527dd8c879c45b44b119905c872.cloudfront.net (CloudFront)&quot;, &quot;x-amz-cf-id&quot;: &quot;f3EZ2MA9kkyCHQ-gCN_YnXTDnPAz_VMfrR1zu_yqx-p6JBNPrJP9Dw==&quot;, &quot;x-amzn-trace-id&quot;: &quot;Root=1-657b3aea-69672e44613ae1807382f5d5&quot;, &quot;x-forwarded-for&quot;: &quot;35.168.152.160, 130.176.98.94&quot;, &quot;x-forwarded-port&quot;: &quot;443&quot;, &quot;x-forwarded-proto&quot;: &quot;https&quot;}}.</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:06.363</td>
<td>[INFO]	2023-12-14T17:27:06.363Z	86528675-501e-4785-aa89-b165f653bec3	azul.terra	Making GET request to &#39;https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef&#39;</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:06.363</td>
<td>[DEBUG]	2023-12-14T17:27:06.363Z	86528675-501e-4785-aa89-b165f653bec3	azul.terra	… without request body</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:11.390</td>
<td>[DEBUG]	2023-12-14T17:27:11.390Z	86528675-501e-4785-aa89-b165f653bec3	azul.chalice	Returning 503 response with headers {&quot;Access-Control-Allow-Origin&quot;: &quot;*&quot;, &quot;Access-Control-Allow-Headers&quot;: &quot;Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key&quot;, &quot;Strict-Transport-Security&quot;: &quot;max-age=31536000; includeSubDomains&quot;}. See next line for the first 1024 characters of the body.<br/>{&quot;Code&quot;: &quot;ServiceUnavailableError&quot;, &quot;Message&quot;: &quot;No response from https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef within 5 seconds&quot;}</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:11.392</td>
<td>REPORT RequestId: 86528675-501e-4785-aa89-b165f653bec3	Duration: 5052.50 ms	Billed Duration: 5053 ms	Memory Size: 2048 MB	Max Memory Used: 167 MB	<br/></td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:11.424</td>
<td>START RequestId: 9152a383-0212-4222-9869-5b9e5676edc0 Version: $LATEST<br/></td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:11.424</td>
<td>[INFO]	2023-12-14T17:27:11.424Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.chalice	Received GET request for &#39;/fetch/repository/files/f6c7670c-2fa2-48eb-aa74-31b7ec94b148&#39;, with {&quot;query&quot;: {&quot;catalog&quot;: &quot;anvil3-it&quot;, &quot;version&quot;: &quot;2022-06-01T00:00:00.000000Z&quot;}, &quot;headers&quot;: {&quot;accept-encoding&quot;: &quot;identity&quot;, &quot;cloudfront-forwarded-proto&quot;: &quot;https&quot;, &quot;cloudfront-is-desktop-viewer&quot;: &quot;true&quot;, &quot;cloudfront-is-mobile-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-smarttv-viewer&quot;: &quot;false&quot;, &quot;cloudfront-is-tablet-viewer&quot;: &quot;false&quot;, &quot;cloudfront-viewer-asn&quot;: &quot;14618&quot;, &quot;cloudfront-viewer-country&quot;: &quot;US&quot;, &quot;host&quot;: &quot;service.prod.anvil.gi.ucsc.edu&quot;, &quot;user-agent&quot;: &quot;python-urllib3/1.26.18&quot;, &quot;via&quot;: &quot;1.1 51391527dd8c879c45b44b119905c872.cloudfront.net (CloudFront)&quot;, &quot;x-amz-cf-id&quot;: &quot;Ul50UYg5UQISCs_BcDu-t2Apu8WBuBU0_T4qN12bINo-SrSNKWIEqg==&quot;, &quot;x-amzn-trace-id&quot;: &quot;Root=1-657b3aef-178257e03a3343e74146d6dd&quot;, &quot;x-forwarded-for&quot;: &quot;35.168.152.160, 130.176.98.71&quot;, &quot;x-forwarded-port&quot;: &quot;443&quot;, &quot;x-forwarded-proto&quot;: &quot;https&quot;}}.</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:11.445</td>
<td>[INFO]	2023-12-14T17:27:11.445Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	Making GET request to &#39;https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef&#39;</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:11.445</td>
<td>[DEBUG]	2023-12-14T17:27:11.445Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	… without request body</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:12.141</td>
<td>[INFO]	2023-12-14T17:27:12.140Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	Got 200 response after 0.695s from GET to https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:12.141</td>
<td>[DEBUG]	2023-12-14T17:27:12.141Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	… with response headers HTTPHeaderDict({&#39;Date&#39;: &#39;Thu, 14 Dec 2023 17:27:11 GMT&#39;, &#39;Server&#39;: &#39;Apache&#39;, &#39;X-Frame-Options&#39;: &#39;SAMEORIGIN&#39;, &#39;Access-Control-Allow-Headers&#39;: &#39;DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Referer,X-App-Id,Origin&#39;, &#39;Access-Control-Allow-Methods&#39;: &#39;GET,POST,DELETE,PUT,PATCH,OPTIONS,HEAD&#39;, &#39;X-Content-Type-Options&#39;: &#39;nosniff&#39;, &#39;Strict-Transport-Security&#39;: &#39;max-age=31536000;includeSubDomains&#39;, &#39;Cache-Control&#39;: &#39;no-cache,no-store,must-revalidate&#39;, &#39;X-Request-ID&#39;: &#39;a0kK84Qj&#39;, &#39;Content-Type&#39;: &#39;application/json&#39;, &#39;Content-Length&#39;: &#39;3862&#39;, &#39;Vary&#39;: &#39;Origin&#39;, &#39;Via&#39;: &#39;1.1 google&#39;, &#39;Alt-Svc&#39;: &#39;h3=&quot;:443&quot;; ma=2592000,h3-29=&quot;:443&quot;; ma=2592000&#39;})</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:12.141</td>
<td>[DEBUG]	2023-12-14T17:27:12.141Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	… with response body b&#39;{&quot;id&quot;:&quot;v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef&quot;,&quot;name&quot;:&quot;summary_stats_variant_counts_windows_dchr20.GIH.counts.txt&quot;,&quot;self_uri...&#39;</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:12.142</td>
<td>[INFO]	2023-12-14T17:27:12.142Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	Making GET request to &#39;https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef/access/gcp-us*c3746ca1-61ec-431e-9c9c-1d14e9dcbafd&#39;</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:12.142</td>
<td>[DEBUG]	2023-12-14T17:27:12.142Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	… without request body</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:13.197</td>
<td>[INFO]	2023-12-14T17:27:13.197Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	Got 200 response after 1.055s from GET to https://data.terra.bio/ga4gh/drs/v1/objects/v2_9c0c5f14-c714-3c5e-b96f-e4545ba098ef/access/gcp-us*c3746ca1-61ec-431e-9c9c-1d14e9dcbafd</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:13.197</td>
<td>[DEBUG]	2023-12-14T17:27:13.197Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	… with response headers HTTPHeaderDict({&#39;Date&#39;: &#39;Thu, 14 Dec 2023 17:27:12 GMT&#39;, &#39;Server&#39;: &#39;Apache&#39;, &#39;X-Frame-Options&#39;: &#39;SAMEORIGIN&#39;, &#39;Access-Control-Allow-Headers&#39;: &#39;DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept,Referer,X-App-Id,Origin&#39;, &#39;Access-Control-Allow-Methods&#39;: &#39;GET,POST,DELETE,PUT,PATCH,OPTIONS,HEAD&#39;, &#39;X-Content-Type-Options&#39;: &#39;nosniff&#39;, &#39;Strict-Transport-Security&#39;: &#39;max-age=31536000;includeSubDomains&#39;, &#39;Cache-Control&#39;: &#39;no-cache,no-store,must-revalidate&#39;, &#39;X-Request-ID&#39;: &#39;pYnyJ5dP&#39;, &#39;Content-Type&#39;: &#39;application/json&#39;, &#39;Content-Length&#39;: &#39;1029&#39;, &#39;Vary&#39;: &#39;Origin&#39;, &#39;Via&#39;: &#39;1.1 google&#39;, &#39;Alt-Svc&#39;: &#39;h3=&quot;:443&quot;; ma=2592000,h3-29=&quot;:443&quot;; ma=2592000&#39;})</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:13.197</td>
<td>[DEBUG]	2023-12-14T17:27:13.197Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.terra	… with response body b&#39;{&quot;url&quot;:&quot;https://storage.googleapis.com/fc-47de7dae-e8e6-429c-b760-b4ba49136eee/summary_stats/variant_counts_windows/dchr20.GI...&#39;</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:13.198</td>
<td>[DEBUG]	2023-12-14T17:27:13.198Z	9152a383-0212-4222-9869-5b9e5676edc0	azul.chalice	Returning 200 response with headers {&quot;Access-Control-Allow-Origin&quot;: &quot;*&quot;, &quot;Access-Control-Allow-Headers&quot;: &quot;Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key&quot;, &quot;Strict-Transport-Security&quot;: &quot;max-age=31536000; includeSubDomains&quot;}. See next line for the first 1024 characters of the body.<br/>{&quot;Status&quot;: 302, &quot;Location&quot;: &quot;https://storage.googleapis.com/fc-47de7dae-e8e6-429c-b760-b4ba49136eee/summary_stats/variant_counts_windows/dchr20.GIH.counts.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=tdr-ingest-sa%40datarepo-9e80499e.iam.gserviceaccount.com%2F20231214%2Fauto%2Fstorage%2Fgoog4_request&amp;X-Goog-Date=20231214T172713Z&amp;X-Goog-Expires=900&amp;X-Goog-SignedHeaders=host&amp;requestedBy=azul-ucsc-1-public-anvilprod%40platform-anvil-prod.iam.gserviceaccount.com&amp;userProject=datarepo-02ad84ea&amp;X-Goog-Signature=592e011867cdc11a940295919de1c105f6bc43230b1b43bac70d84572642603479a24dde23fc41497261d12527b4c371533334279dbba6c31b3a7a0ff865e3f9ec352f0156c12cb592eb72058991d0e02d7997a9119eb3acd937711f9cda6b5f9beb6638fd25741e677572bcb3a08822e1889ccf2329a4d4ac94e7cdae0f1f234d9caf72f35817e952b277484c05e05d39462a207631f1d90fe7b283758785136c671a2c7aedcb50563a2cc0c6c608cb461ae60dd7e40a5cda690326496f5b42dea5d24d815ee495ccaf8a0281ee3feda43a0846d8173196f86a8063a8a0e7a67068c689dbb09859f4fd7bdb8f2859e08d43342c8128b1d4d003208</td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
<tr>
<td>2023-12-14 17:27:13.199</td>
<td>REPORT RequestId: 9152a383-0212-4222-9869-5b9e5676edc0	Duration: 1775.67 ms	Billed Duration: 1776 ms	Memory Size: 2048 MB	Max Memory Used: 168 MB	<br/></td>
<td>465330168186:/aws/lambda/azul-service-anvilprod</td>
</tr>
</tbody></table>

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
We do fetch the file metadata earlier during the test. We should only assert a non-empty body for files that have a size of zero. We are currently already extracting the file extension from the file metadata, and instead of adding a second parameter to pass down the call chain we should either pass the entire inner file dictionary or derive an instance of a new, IT-specific, attrs-decorated `File` class from the file metadata and pass that down.

**Comment by hannes-ucsc** [comment]
Passing test suffices for demo.
