### ISSUE TITLE
Developers can't delete unused DockerHub images during upgrade

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5798]
The issue template for biweekly upgrades includes items about deleting unused images from DockerHub. However, this action requires the cooperation of the system administrator. Instead of tracking this actions as CL items in the issue, we should track them as CL in the PR template that we'll create as part of #5774.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Solve together with #5774.

**Comment by hannes-ucsc** [comment]
For demo, show CL items for two phases of deploying the `shared` component.

**Comment by hannes-ucsc** [comment]
This was moved out of `prod` because it was thought to not be demoable because another ticket resolved by the same PR failed to be demoed. This issue is actually demoable. Moving back to `prod`.
