### ISSUE TITLE
requirements.all.txt does not reflect pins from requirements.pip.txt

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5799]
A recently filed PR by Dependabot attempted to bump the dependency listed in [requirements.all.txt](https://github.com/DataBiosphere/azul/blob/develop/requirements.all.txt#L91C1-L91C1), which is use as a comprehensive reference of all project dependencies and isn't explicitly managed.

Azul's pip dependency is already pinned to the appropriate version, see [requirements.pip.txt](https://github.com/DataBiosphere/azul/blob/develop/requirements.pip.txt#L1). However, the version listed in `requirements.all.txt` is incongruent.

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Assignee to provide description.

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Turns out that Chalice has a [upper version limit](https://github.com/DataBiosphere/azul-chalice/blob/e3a62b1cd249ccdb3ed137b2295a8b7c8dfa8795/setup.py#L28) on `pip` that prevents the installation of the version we pin in `requirements.pip.txt`.

This patch exposes the version conflict:

```diff
Index: scripts/manage_requirements.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/scripts/manage_requirements.py b/scripts/manage_requirements.py
--- a/scripts/manage_requirements.py	(revision 52a8568278b293c019f2b6a19b02d768c95ca0df)
+++ b/scripts/manage_requirements.py	(date 1702937914845)
@@ -193,10 +193,8 @@
         dupes = direct_build_reqs & direct_runtime_reqs
         require(not dupes, 'Some requirements are declared as both run and build time', dupes)
 
-        all_reqs = self.get_reqs(self.build)
-        build_reqs = all_reqs - pip_reqs
-        all_runtime_reqs = self.get_reqs(self.runtime)
-        runtime_reqs = all_runtime_reqs - pip_reqs
+        build_reqs = self.get_reqs(self.build)
+        runtime_reqs = self.get_reqs(self.runtime)
         require(runtime_reqs <= build_reqs,
                 'Runtime requirements are not a subset of build requirements',
                 runtime_reqs - build_reqs)
@@ -217,9 +215,9 @@
                 'Ambiguous transitive runtime requirement versions',
                 ambiguities)
 
-        build_only_reqs = build_reqs - runtime_reqs
+        build_only_reqs = build_reqs - pip_reqs - runtime_reqs
         transitive_build_reqs = build_only_reqs - direct_build_reqs
-        transitive_runtime_reqs = runtime_reqs - direct_runtime_reqs
+        transitive_runtime_reqs = runtime_reqs - pip_reqs - direct_runtime_reqs
         assert not transitive_build_reqs & transitive_runtime_reqs
         # Assert that all_reqs really includes everything
         for i, reqs in enumerate([
@@ -228,12 +226,12 @@
             transitive_runtime_reqs,
             direct_build_reqs,
             transitive_build_reqs,
-            all_runtime_reqs
+            runtime_reqs
         ]):
-            assert reqs <= all_reqs, (i, reqs - all_reqs)
+            assert reqs <= build_reqs, (i, reqs - build_reqs)
         self.write_transitive_reqs(transitive_build_reqs, self.build)
         self.write_transitive_reqs(transitive_runtime_reqs, self.runtime)
-        self.write_all_reqs(all_reqs)
+        self.write_all_reqs(build_reqs)
 
     def parse_reqs(self, file_or_str: Union[IO, str]) -> PinnedRequirements:
         parsed_reqs = requirements.parse(file_or_str, recurse=False)
```

It causes 

```
2023-12-18 14:23:17,935   ERROR MainThread __main__: Ambiguous version of transitive runtime requirement pip==23.1.2,==23.3. Consider pinning it to the version used at build time (==23.1.2).
Traceback (most recent call last):
  File "/Users/hannes/workspace/hca/azul/scripts/manage_requirements.py", line 294, in <module>
    main.run()
  File "/Users/hannes/workspace/hca/azul/scripts/manage_requirements.py", line 214, in run
    require(not ambiguities,
  File "/Users/hannes/workspace/hca/azul/src/azul/__init__.py", line 1526, in require
    reject(not condition, *args, exception=exception)
  File "/Users/hannes/workspace/hca/azul/src/azul/__init__.py", line 1545, in reject
    raise exception(*args)
azul.RequirementError: ('Ambiguous transitive runtime requirement versions', Requirements([PinnedRequirement(name='pip', versions=Versions({'23.3', '23.1.2'}))]))
```

during `make requirements_update`.

The solution is to apply the above patch to Azul, remove the upper version bound in our fork of Chalice and bump Azul's dependency on Chalice to include that change.
