### ISSUE TITLE
Authentication on the webservice

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#58]
We need to integrate authentication in the web service.

I think this should be using whatever framework blue provides for authentication

#### Checkpoints for research and planning

- [x] Figure out the authentication process
  - [x] @shiroyuki to discuss with Trent Smith on the authentication process and how to work with Fusillade
  - [x] @shiroyuki to implement a prototype
  - [x] @shiroyuki to discuss with @NoopDog on the exact workflow (required a RFC)
- [x] Figure out the token verification procedure
  - [x] @shiroyuki to implement a prototype

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-45)
┆Project Name: azul
┆Issue Number: AZUL-45
┆Epic: Interactive building of collections

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Include Michael Baumann in design discussions.

**Comment by theathorn** [comment]
This ticket is to support Authentication in the HCA Data Portal and Browser.

**Comment by theathorn** [comment]
From @briandoconnor : This is google ID login via Oauth/OIDC.

**Comment by shiroyuki** [comment]
@theathorn, @hannes-ucsc: Azul will rely on Fusillade + Auth0 which currently only give two options to the users: login with Google ID or HCA's Auth0.

**Other Updates:**
* The prototype code is on the `experimentals/auth` branch.
* I think the prototype code is good enough to turn into a production code. So, I'll clean it up.
* The next stop would be a RFC on the authentication procedure and discuss with @NoopDog on how we want the frontend and backend working together.

**Comment by shiroyuki** [comment]
@NoopDog The RFC is available at https://github.com/DataBiosphere/azul/blob/experiments/auth/rfc/azul-0058-authentication.md.

Per our discussion:
* We will go with option 2 (Begin with Azul redirecting to Fusillade; end with Fusillade redirecting back to UI)
* For the time being, the subject of the given JWT (`sub`) is the user identifier.

**Comment by theathorn** [comment]
@hannes-ucsc wrote:
Hi Trevor, there are a few open questions wrt to authn/authz for Azul/data-browser. Would you be OK with arranging a meeting between me and Brian O, Charles, Michael B, Juti, Dave and me? Agenda items would be

* Should the HCA Orange team attempt to implement authz/authn generically or is it ok to bake in a dependency on Fussilade?
* Specifically, should Azul be involved in authentication exchanges?
* If so, should we try to build on the cgp-dashboard service or should we reimplement it for HCA in Azul as a Lambda function (it currently is a Flask app deployed as a container on EC2 IIRC)?

**Comment by hannes-ucsc** [comment]
PR #563 was merged had to be backed out due to merge errors and two other issues I hadn't caught earlier.
