### ISSUE TITLE
Inspector doesn't scan Docker images for ClamAV & Docker

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5830]
<img width="1354" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/e2baa934-37df-4c93-b921-7e689b7d3ab7">
<img width="1358" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/2367f3bc-a30b-4771-ad41-83a1046f71dd">

The AWS Signing Proxy image is not supported either …

<img width="1370" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/fc30db05-7c65-4985-99f6-23ebfe87f6c4">

… but it's not used within the boundary.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
The Docker and ClamAV images are based on [Alpine 3.19 which is currently not supported by Amazon Inspector](https://github.com/aws/containers-roadmap/issues/2237)

<img width="1476" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/67e6a707-ef07-451a-a726-ca152e1f6495">
<img width="1479" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/dbd8c0bf-b6a4-4131-9d07-318dc4b87f63">

The AWS Signing Proxy image has no base image, since it only contains a statically linked Go binary and some root CA certificates:

<img width="1482" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/96fe86e0-2a23-408a-82aa-8d858d9cc6bb">

**Comment by achave11-ucsc** [comment]
Assignee to monitor upstream issue.

**Comment by hannes-ucsc** [comment]
Upstream issue was fixed. Images are being scanned:

![image](https://github.com/user-attachments/assets/857e842a-1351-4498-ac8b-1447725d6869)
