### ISSUE TITLE
Include GitLab backup in bi-weekly upgrades

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5839]
The backup procedure includes running `yum update` on each instance. The GitLab instance needs to be recreated during updates anyways and is likely to include an update to the AMI, so that's a good opportunity to also apply any interim package updates. This likely requires updating the operator manual, as well as the issue and PR templates for upgrades.

**Comment by dsotirho-ucsc** [comment]
Assignee to also delete the backup issue template.
