### ISSUE TITLE
Dummy S3 lifecycle rule has auto-generated name

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5848]
Follow-up from #5561.

I noticed this after deploying `dev.shared` but it's probably the case on all TF-managed buckets in all components and deployments.

<img width="1061" alt="Screenshot 2024-01-11 at 10 35 14 AM" src="https://github.com/DataBiosphere/azul/assets/5143256/78b05e4e-19d4-4ae4-a8b9-f767f2470ce9">

The rule name should be `azul-dummy-dev`, or, generally speaking, the result of `config.qualified_resource_name('dummy')`.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike to investigate if its even possible to provide an explicit name for lifecycle rules.

**Comment by nadove-ucsc** [comment]
The auto-generated names in the screenshot above appear to correspond to the [`id` attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#id) in the TF config: 

```diff
diff --git a/src/azul/terraform.py b/src/azul/terraform.py
index 6946df2c..1c82681d 100644
--- a/src/azul/terraform.py
+++ b/src/azul/terraform.py
@@ -404,6 +404,7 @@ def set_empty_s3_bucket_lifecycle_config(tf_config: JSON) -> JSON:
             # achieves the goal of preventing/removing policies that originate
             # from outside TF.
             bucket.setdefault('lifecycle_rule', {
+                'id': config.qualified_resource_name('dummy'),
                 'enabled': False,
                 'expiration': {'days': 36500}
             })
```

Output from `terraform plan`:

```
  ~ lifecycle_rule {
          ~ id                                     = "tf-s3-lifecycle-20240111182531674500000001" -> "azul-dummy-dev"
            tags                                   = {}
            # (2 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
```

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce in all four AWS accounts.
