### ISSUE TITLE
Deploying `prod.shared` early breaks scheduled jobs on GitLab

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5856]

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Assignee to split the deployment of shared during promotions into two phases: one using apply_keep_unused and another one using apply just like we do during upgrade PRs."

**Comment by dsotirho-ucsc** [comment]
This was already solved in a prior PR. Assignee to link to solution.

**Comment by hannes-ucsc** [comment]
I was wrong, this hasn't been solved already.

**Comment by hannes-ucsc** [comment]
Assignee to provide description.
