### ISSUE TITLE
Time it takes to index an update 

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#5858]
Low priority.

This is coming from all three platforms (AnVIL, HCA, and LungMAP). 

As the snapshots grow in the various Data Explorer instances, the stakeholders are interested in knowing how long it takes to do the indexing assuming all goes well (no issues are found that disrupts the indexing).

Is it hours, most of a day, two days? 

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
The description does not specify what is wrong or should be improved. It needs more information or should be closed as invalid.

To answer the question (and GitHub issues aren't the best venue to merely ask questions): The lead time for a reindex is usually one week from the time a reindex is requested and when it is actually started in one of the production environments. The lead time could be longer if the request isn't for a production deployment or the team is occupied with higher priority work. 

The actual reindex of an AnVIL or HCA release catalog takes 48h. Sometimes we have to reindex two catalogs, the one for current release and the one for the next release. In that case, a reindex takes twice as long. This typically occurs when we deploy new features or bug fixes that change format of the index at the same time as we deploy the addition of a release, or when we deploy such features or bug fixes while we maintain two catalogs while the new release is under wrangler review.
