### ISSUE TITLE
Update Docker to 25.0.x

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5865]
Docker has now released [25.0.0-rc.3](https://hub.docker.com/_/docker/tags?page=1&name=25.0.0-), and might soon release the stable version.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Let's wait for Docker 25.0.1 or .2 before jumping on this bandwagon."

**Comment by achave11-ucsc** [comment]
Assignee to wait until that release if publicly available and to re-triage when it is.

**Comment by achave11-ucsc** [comment]
Docker 25.0.1 has been released, however 5H CVEs are outstanding.

**Comment by hannes-ucsc** [comment]
Still better than the nine H for the version we're currently on.

https://hub.docker.com/layers/library/docker/24.0.8/images/sha256-0af8023498502dbc2f33369a8465e2faccb2502af2ff57b8f16bfb4a4af28829?context=explore
https://hub.docker.com/layers/library/docker/25.0.1/images/sha256-6863a098da35ab4bae6a3a80ab02997d93624ded0e263a14715dbe6e08260cd0?context=explore

**Comment by achave11-ucsc** [comment]
Docker [25.0.3](https://hub.docker.com/_/docker/tags?page=1&name=25.0.3-) has been released.

**Comment by achave11-ucsc** [comment]
Duplicate of #6072
