### ISSUE TITLE
Create VPC interface endpoint for SQS

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5866]
Follow up on https://github.com/DataBiosphere/azul/issues/5467#issuecomment-1898943445

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
We'll see how the spike for #6767 pans out. If one of the applicable SecurityHub controls stipulates that we create a VPC endpoint for SQS, we will create a new issue.
