### ISSUE TITLE
Delete unused CF functions

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5871]
https://github.com/hashicorp/terraform-provider-aws/issues/25249 prevented me from deleting CF functions that I wanted to rename/consolidate. I had to leave the unused functions in place. They can be deleted as soon as the function association in the cache behavior is updated to not refer to them during a deployment.

I put a FIXME in the unused functions.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "This could be done as part of the PR for #5877 that makes LungMAP a separate deployment."

**Comment by hannes-ucsc** [comment]
For demo, show that no unused CF functions exist in any AWS account.
