### ISSUE TITLE
Metric alarm `api_unauthorized` is not firing for some hits

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5884]
The pattern used by the metric alarm `api_unauthorized` fails to raise an alarm for hits that are found when using the same pattern in a CloudWatch query.

The pattern as written in the generated file `shared.tf.json`:
```
{
    ($.errorCode = \"*UnauthorizedOperation\" || $.errorCode = \"AccessDenied*\")
    && ($.eventSource != \"s3.amazonaws.com\" || $.eventName != \"GetObject\" || $.userIdentity.invokedBy != \"cloudfront.amazonaws.com\")
    && ($.eventSource != \"s3.amazonaws.com\" || $.eventName != \"HeadBucket\" || $.userIdentity.invokedBy != \"config.amazonaws.com\")
    && ($.eventSource != \"s3.amazonaws.com\" || $.eventName != \"HeadObject\" || $.userIdentity.invokedBy != \"cloudfront.amazonaws.com\")
    && ($.eventSource != \"inspector2.amazonaws.com\" || $.eventName != \"DescribeOrganizationConfiguration\")
    && ($.eventSource != \"elasticloadbalancing.amazonaws.com\" || $.eventName != \"DescribeTargetGroupAttributes\" || $.userIdentity.invokedBy != \"inspector2.amazonaws.com\")
    && ($.eventSource != \"ec2.amazonaws.com\" || $.eventName != \"CreateNetworkInterface\")
}
```

Hits found in CloudWatch when filtering with the same pattern. None of these hits raised an `api_unauthorized` alarm.
(The full JSON of the hits was not posted here for security reasons since this is from production. This [link](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-01-24T17*3a25*3a00.000Z~start~'2024-01-23T18*3a11*3a27.096Z~timeType~'ABSOLUTE~tz~'UTC~editorString~'fields*20*40timestamp*2c*20errorCode*2c*20eventSource*2c*20eventName*2c*20userIdentity.invokedBy*2c*20*40message*0a*7c*20filter*20*28*0a*20*20*20*20errorCode*20like*20*2fUnauthorizedOperation*2f*20or*20errorCode*20like*20*2fAccessDenied*2f*0a*20*20*20*20and*20*28*20eventSource*20*21*3d*20*27s3.amazonaws.com*27*20or*20eventName*20*21*3d*20*27GetObject*27*20or*20userIdentity.invokedBy*20*21*3d*20*27cloudfront.amazonaws.com*27*29*0a*20*20*20*20and*20*28*20eventSource*20*21*3d*20*27s3.amazonaws.com*27*20or*20eventName*20*21*3d*20*27HeadBucket*27*20or*20userIdentity.invokedBy*20*21*3d*20*27config.amazonaws.com*27*29*0a*20*20*20*20and*20*28*20eventSource*20*21*3d*20*27s3.amazonaws.com*27*20or*20eventName*20*21*3d*20*27HeadObject*27*20or*20userIdentity.invokedBy*20*21*3d*20*27cloudfront.amazonaws.com*27*29*0a*20*20*20*20and*20*28*20eventSource*20*21*3d*20*27inspector2.amazonaws.com*27*20or*20eventName*20*21*3d*20*27DescribeOrganizationConfiguration*27*29*0a*20*20*20*20and*20*28*20eventSource*20*21*3d*20*27elasticloadbalancing.amazonaws.com*27*20or*20eventName*20*21*3d*20*27DescribeTargetGroupAttributes*27*20or*20userIdentity.invokedBy*20*21*3d*20*27inspector2.amazonaws.com*27*29*0a*20*20*20*20and*20*28*20eventSource*20*21*3d*20*27ec2.amazonaws.com*27*20or*20eventName*20*21*3d*20*27CreateNetworkInterface*27*29*0a*29*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*20100~queryId~'7c9294da-c8b2-488c-9a7f-d6ac0be96230~source~(~'azul-trail-prod))) can be used to view results in the AWS Console.)

![Screenshot 2024-01-24 at 9 33 55 AM](https://github.com/DataBiosphere/azul/assets/46407464/42d98ba8-982f-4ba5-a866-dcf9077d8a24)

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Assignee to summarize findings of our research.

**Comment by dsotirho-ucsc** [comment]
The issues occurs with records that do not contain the `userIdentity.invokedBy` field. The `api_unauthorized` metric filter includes this field with the syntax `$.userIdentity.invokedBy != "foo"`, however contrary to what is desired this is not a TRUE condition for records without the field, even though it is a TRUE condition for a CloudWatch query with a likewise syntax `userIdentity.invokedBy != 'foo'`.

A simplified example tested with the metric filter (Edit metric filter -> test pattern) demonstrated this behavior:

Filter pattern:
```
{($.errorCode = "AccessDenied") && ($.userIdentity.invokedBy != "cloudfront.amazonaws.com")}
```

Test log data:
```
{
    "errorCode": "AccessDenied",
    "userIdentity": {
        "accountId": "anonymous",
    }
}
```

Result: no match

The limitations of the metric filter pattern syntax for [matching JSON log events](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html#matching-terms-json-log-events) seem to offer no solution to solve this issue.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "The failing term in the CloudWatch log metrics query is our own addition. These additions were made in order to silence certain noisy alarms. Due to the additions, Security Hub control is failing because our query deviates from the prescribed one. The long term solution for noisy alarms will be filtering in a Lambda (see #5246 and it's blockees) at which point we can revert the additions (see #5255) and therefor eliminate the buggy term. This ticket will be a freebie of the PR that resolves #5255 which is now a blocker of this ticket."

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "During the demo of #5964 we discovered that wer're currently not getting notification alarms for some true positives. Seems like we have to remove our exception clauses and accept the fact that we'll be getting false positives."

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
