### ISSUE TITLE
`test` job consistently slower on GitLab anvilprod

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5895]

**Comment by hannes-ucsc** [comment]
Spike to validate, provide evidence and diagnose.

**Comment by nadove-ucsc** [comment]
The `test` job on GitLab `anvilprod` is _not_ consistently slower than on any of our other GitLab instances. However, it does take about twice as long to run on GitLab compared to GitHub actions.

| Platform/instance | average test duration | durations |
| ----- | ----- | ----- |
| GitHub (develop branch) | 20:49 | 19:01, 26:49, 19:51, 20:06, 19:23, 19:42, 21:25, 20:44, 20:11, 20:37 |
| GitLab dev | 51:00 | 42:29, 58:12, 56:45, 45:55, 41:47, 63:16, 60:56, 47:16, 45:48, 47:39 |
| GitLab prod | 41:05 | 41:23, 40:48, 40:07, 44:04, 43:44, 43:42, 43:22, 38:27, 37:59, 37:18 |
| GitLab anvildev | 53:51 | 47:14, 65:33, 65:55, 45:06, 44:03, 66:19, 65:10, 47:23, 45:52, 45:57 |
| GitLab anvilprod | 43:47 | 45:44, 47:24, 45:29, 47:07, 41:28, 45:17, 42:12, 41:28, 41:57, 39:44 |
