### ISSUE TITLE
Move bigquery-emulator to DataBiosphere

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5905]
- [x] Fork `goccy/bigquery-emulator` to `DataBiosphere/azul-bigquery-emulator`
  - [x] Fork upstream repository https://www.github.com/goccy/bigquery-emulator
  - [x] Reset `main` branch to the commit where https://github.com/hannes-ucsc/bigquery-emulator was forked
  - [x] Create an `azul` branch
    - [x] Apply commits from https://github.com/hannes-ucsc/bigquery-emulator
    - [x] Replace references to `github.com/hannes-ucsc/go-zetasqlite` with `github.com/DataBiosphere/azul-go-
    - [x] Change build to push to our DockerHub org
    - [x] Add versioning (upstream and our own)
- [x] Fork `goccy/go-zetasqlite` to `DataBiosphere/azul-go-zetasqlite`
  - [x] Fork upstream repository https://www.github.com/goccy/go-zetasqlite
  - [x] Reset `main` branch to the commit where https://www.github.com/hannes-ucsc/go-zetasqlite was forked
  - [x] Create an `azul` branch
    - [x] Apply commits from https://www.github.com/hannes-ucsc/go-zetasqlite
- [x] Modify Azul to use `azul-bigquery-emulator` image from DockerHub

**Comment by dsotirho-ucsc** [comment]
Assignee to complete description and consider next steps.
