### ISSUE TITLE
Move deployment of `shared` components in `upgrade.md` template

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5906]
Based on the successful result of [this experiment](https://github.com/DataBiosphere/azul/pull/5897#issuecomment-1915364604), move the checkboxes for deployment of the `shared` component to be after pushing PR branch to GitHub, right before pushing the `gitlab` components.

```
Subject: [PATCH] Add hash `null` provider
---
Index: .github/PULL_REQUEST_TEMPLATE/upgrade.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/PULL_REQUEST_TEMPLATE/upgrade.md b/.github/PULL_REQUEST_TEMPLATE/upgrade.md
--- a/.github/PULL_REQUEST_TEMPLATE/upgrade.md	(revision c8fbcb74ed42b5d2dcaca5ce2d1b9eda6c92e524)
+++ b/.github/PULL_REQUEST_TEMPLATE/upgrade.md	(date 1706556194723)
@@ -28,9 +28,6 @@
 - [ ] Ran `make requirements_update` <sub>or this PR does not touch requirements*.txt, common.mk, Makefile and Dockerfile</sub>
 - [ ] Added `R` tag to commit title <sub>or this PR does not touch requirements*.txt</sub>
 - [ ] Added `reqs` label to PR <sub>or this PR does not touch requirements*.txt</sub>
-- [ ] Selected `dev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
-- [ ] Selected `anvildev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
-- [ ] Selected `anvilprod.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
 - [ ] `make integration_test` passes in personal deployment <sub>or this PR does not touch functionality that could break the IT</sub>
 
 
@@ -48,8 +45,11 @@
 - [ ] Squashed PR branch and rebased onto `develop`
 - [ ] Sanity-checked history
 - [ ] Pushed PR branch to GitHub
+- [ ] Selected `dev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
 - [ ] Selected `dev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
+- [ ] Selected `anvildev.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
 - [ ] Selected `anvildev.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
+- [ ] Selected `anvilprod.shared` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR does not change any Docker image versions</sub>
 - [ ] Selected `anvilprod.gitlab` and ran `CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
 - [ ] Assigned system administrator <sub>or this PR does not include any changes to files in terraform/gitlab</sub>
 - [ ] Checked the items in the next section <sub>or this PR includes changes to files in terraform/gitlab</sub>

```

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Include this fix in the current upgrade PR https://github.com/DataBiosphere/azul/pull/5897

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/commit/3da53fb5c290036e15a7c6e6013d2d5741e5a37c is insufficient, as it only touches the generated PR template, not the meta-template that is used to generate the PR template.
