### ISSUE TITLE
Periodically enable GitLab cleanup policy

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5908]
https://github.com/DataBiosphere/azul/issues/5822#issuecomment-1868114168

Every four weeks, on every instance, the system administrator should set the number of clean-up workers to 4, wait an hour. Set number back to 0.

**Comment by dsotirho-ucsc** [comment]
Assignee to complete description and consider next steps.

**Comment by achave11-ucsc** [comment]
The data volume usage alarm recently went off in `anvilprod` as well, in addition to `anvildev` where it's been in alarm state for approximately two weeks.

**Comment by dsotirho-ucsc** [comment]
GitLab `dev` data use jumped from 72 to 77% today.

![Screenshot 2024-02-27 at 5 42 41 PM](https://github.com/DataBiosphere/azul/assets/46407464/29b68228-bebf-4e5f-a13d-71d58bf25eeb)

**Comment by hannes-ucsc** [comment]
Assignee to create issue template with four week schedule for the Monday between operator duty changes. Include link to each instance, e.g.,

https://gitlab.dev.singlecell.gi.ucsc.edu/admin/application_settings/ci_cd#application_setting_container_registry_expiration_policies_worker_capacity

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "GitLab recently added an alternative registry implementation which is currently in beta. The beta might have improved garbage collection which may make this ticket obsolete. Assignee to provide links and information."

**Comment by hannes-ucsc** [comment]
This is the respective documentation: https://docs.gitlab.com/ee/administration/packages/container_registry_metadata_database.html

This is the feedback issue: https://gitlab.com/gitlab-org/gitlab/-/issues/423459#supported-feature-status

From that issue it is evident that if we were to adopt this feature now, we would have to provide a dedicated PSQL database. See https://gitlab.com/gitlab-org/gitlab/-/issues/423459#supported-feature-status 

<img width="1009" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/407cc25b-a6ce-4f77-a818-957d20e8b33f">

This would be to much of an effort for us at this time. I'll create a new issue about migrating to the new registry database once it can make use of the omnibus-provided PSQL database.

**Comment by hannes-ucsc** [comment]
Assignee to proceed with the original plan: https://github.com/DataBiosphere/azul/issues/5908#issuecomment-1987534423

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "This clean-up policy is permanently enabled now that we can't reproduce the elevated CPU anymore."
https://github.com/DataBiosphere/azul/issues/5822#issuecomment-2211382952
