### ISSUE TITLE
GitLab runner v16.8.0 prematurely kills `build_image` job

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5916]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/85374

https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/4491#note_1750764742

f28bc831 downgrades the runner again. One of the recommended workarounds is to reduce [the `after_script` timeout.](https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-script-and-after_script-timeouts) Since we don't use `after_script`, we can reduce it to zero for every job (using [`default`](https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-script-and-after_script-timeouts)) . At the configuration site, we need to document that any job timeout needs to include the after script timeout so that if we were to set the after script timeout to, say, 3min, the job timeout would need to be configured to 3min plus what we want the actual job timeout to be.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Next upgrade issue should be blocked by this."

**Comment by achave11-ucsc** [comment]
In this issue's PR:

>@hannes-ucsc: Looks like the [MR was reverted](https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/4491#note_1767849235). Please wait for v16.8.1 of the runner, check if the reversion is included and retriage ticket.

Indeed, this was fixed. From `develop`, we're currently running on version v16.9.0 without issues https://github.com/DataBiosphere/azul/commit/08eb8e42567d6c9b37e853643ea3fd4454434b29.
