### ISSUE TITLE
Coveralls reporting does not work

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5933]
Coveralls:

<img width="1177" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/14a0fb70-c946-4171-afcd-5afe554476dd">

Codecov:

@nadove-ucsc to put screenshot here (works for me, @hannes-ucsc )

**Comment by nadove-ucsc** [comment]
> @nadove-ucsc to put screenshot here (works for me, @hannes-ucsc )

Now it works for me too (can't reproduce the error I saw earlier)

**Comment by hannes-ucsc** [comment]
This is insufficiently described. I can't reproduce the part of the repro that is described.
