### ISSUE TITLE
Add unit test coverage for supplementary bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5934]
- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
Spike for estimate.

**Comment by nadove-ucsc** [comment]
This should be fairly easy as the only substantial work it requires will be adding a supplementary file row to the canned BigQuery tables and canning the result of `fetch_bundle`. Once those changes are in place, all we need to do is add a subtest that mirrors the existing assertions in `test_fetch_bundle`. Suggested estimate: 3.

**Comment by nadove-ucsc** [comment]
However, the approach outlined above does have the disadvantage of storing two different bundles in the same canned table. There's no technical problem with that, but it may be confusing since the bundle UUID is included in the file name. Perhaps it would be better to add a new canned tables file that only includes entities from the supplementary bundle. Might bump the estimate to 4 in that case.

**Comment by hannes-ucsc** [comment]
For demo, show additional coverage on Codecov.io.
