### ISSUE TITLE
Add unit test coverage for DUOS bundles

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5935]
Security Design Review is here:

https://github.com/DataBiosphere/azul/pull/5946#issuecomment-1981590342

**Comment by achave11-ucsc** [comment]
Spike for estimate.

**Comment by nadove-ucsc** [comment]
This will be more involved since we'll need to add new mock responses from both TDR and the DUOS service. Again, a new (small) bundle will be canned, but no changes need to be made to the canned tables.  Estimate 5.

**Comment by hannes-ucsc** [comment]
For demo, show increase in coverage.
