### ISSUE TITLE
Extra EC2 instance in `dev`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5938]
Review completed. There is one extra EC2 instance in `dev`

<img width="762" alt="image" src="https://github.com/DataBiosphere/azul-private/assets/5143256/436e2912-1e3e-4ee1-a08a-cff03cec2de1">

but it is stopped:

<img width="1479" alt="image" src="https://github.com/DataBiosphere/azul-private/assets/5143256/2adccaa7-9526-48e3-8401-6d483973b7b7">

It's currently being used by @dsotirho-ucsc for experiments but I don't recall for what issue. I will create an issue to record the purpose and shut the instance down when the experiments have concluded.

_Originally posted by @hannes-ucsc in https://github.com/DataBiosphere/azul-private/issues/129#issuecomment-1932574540_

**Comment by dsotirho-ucsc** [comment]
> It's currently being used by @dsotirho-ucsc for experiments but I don't recall for what issue. I will create an issue to record the purpose and shut the instance down when the experiments have concluded.

This EC2 instance was used for the testing of https://github.com/DataBiosphere/azul-private/issues/125 (see [comment](https://github.com/DataBiosphere/azul-private/issues/125#issuecomment-1930450273)).
The testing is now complete, and PR https://github.com/DataBiosphere/azul/pull/5930 has been created based on the results. The EC2 instance can now be terminated.

**Comment by dsotirho-ucsc** [comment]
done.

![Screenshot 2024-02-07 at 10 13 00 AM](https://github.com/DataBiosphere/azul/assets/46407464/5ace258f-475f-4b94-a465-124ec31f42b1)

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We will likely need the instance for the demo of https://github.com/DataBiosphere/azul-private/issues/125. Since a new instance will likely have to be created we will leave this open to ensure that the new instance is also terminated."

**Comment by dsotirho-ucsc** [comment]
The EC2 instance created for the demo of https://github.com/DataBiosphere/azul-private/issues/125 has now been terminated.

![Screenshot 2024-02-27 at 3 59 24 PM](https://github.com/DataBiosphere/azul/assets/46407464/85b3fced-00d4-4a69-b2cb-09ec1445b801)
