### ISSUE TITLE
Every rate blocked request is logged, incurring charges

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5939]
![Screenshot 2024-02-07 at 12 06 55 PM](https://github.com/DataBiosphere/azul/assets/19215510/bcb2f48e-22af-4008-bdb5-e508247131e9)

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
It would be possible to prevent WAF from logging rate-blocked requests by setting the default log action to log and the rate rule's action to drop the log. However, there seems to be no way to suppress API Gateway from not logging requests for which the WAF decided to block the request.

Someone on the web [claims that WAF does not sit in front off API Gateway but rather on the side](https://repost.aws/questions/QUT-Ts0igfSrCdZdWeuzwLCA/api-gateway-access-log-still-get-requests-blocked-by-waf). That would explain why both WAF and API Gateway emit log events for blocked requests.

Assignee to 

- [ ] Increase the threshold for the metric alarm for rate-blocked requests to 6000 in 10 min
- [ ] Write a script that modifies the default ACL in the GitLab VPC to add/remove a rule to block any traffic from a given CIDR
- [ ] Test the script with their own local IP

The rationale behind the threshold is that the WAF rate limit is currently 1000/5min (the lowest possible rate limit) but due to the inherent hysteresis that we observed, the effective limit could be as high as 1500. Twice that is 3000/5min = 6000/10min. If someone makes more that 6000 requests for 10 min, they are disregarding the retry-after header in our 429 responses and deserve to be completely blocked, thereby preventing any log messages or consumption of any resources.

**Comment by achave11-ucsc** [comment]
Provide a summary of why this may not proceed as prescribed.

**Comment by achave11-ucsc** [comment]
Adding a blocking rule to the VPC ACL is not causing the desired effect of blocking the specified CIDR. The VPC ACL only controls traffic at the subnet level within the VPC and API Gateway resides outside the VPC. This prevents any rules in the VPC ACL from having an effect since our indexer/service endpoints are staged in API Gateway, except for deployments which are deployed with `AZUL_PRIVATE_API=1` because they use a load balancer which relies on the VPC. A more involved solution is warranted, with some options being [blocking the IP using a resource policy](https://repost.aws/knowledge-center/api-gateway-resource-policy-access) and attaching it to the API Gateway resource. Or creating a private API Gateway with a VPC, which has some limitations [#apigateway-private-api-design-considerations](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html#apigateway-private-api-design-considerations).

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Spike to test the API resource gateway approach to blocking remote IP in a personal deployment. We need to know if this is 1) possible, and 2) reduces the number of logged events for requests blocked in such a way."

**Comment by achave11-ucsc** [comment]
This approach is possible, modifying the of API Gateway resource policy to explicitly block an IP CIDR is effective. However, when the blocked IP continues to make requests, this blocked attempts continue to be logged by API Gateway, in the configured api-gateway logs for the service/indexer Lambdas but also by the execution logs. The following is an example of the types of logs by API Gateway when an IP is blocked by the means of the service resource policy.

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: API-Gateway-Execution-Logs_65jyknf3ud/abrahamsc, /aws/apigateway/azul-service-abrahamsc    
start-time: 2024-02-24T00:25:30.710Z    
end-time: 2024-02-24T00:29:10.463Z    
query-string:
  ```
  fields @timestamp, @message
| filter status not like '200' or @ message like /not authorized/
# | filter @logStream like /c3d4d115ab039d325f8eaf7486eaa43f|75c76f2178c851248fb7ce1e2482b3c7/
| parse @log ":*" as stream
| sort @timestamp desc
| limit 7
  ```
---
| @timestamp | @message | stream |
| --- | --- | --- |
| 2024-02-24 00:29:03.163 | (412e45a2-9321-4077-8b0b-f044a4364918) The client is not authorized to perform this operation. | API-Gateway-Execution-Logs_65jyknf3ud/abrahamsc |
| 2024-02-24 00:29:03.156 | (412e45a2-9321-4077-8b0b-f044a4364918) Extended Request Id: TnW8aHXyIAMEQiQ= | API-Gateway-Execution-Logs_65jyknf3ud/abrahamsc |
| 2024-02-24 00:29:03.156 | {"accountId": "122796619775", "apiId": "65jyknf3ud", "authorizer_claims_property": "-", "authorizer_error": "-", "authorizer_principalId": "-", "authorizer_property": "-", "awsEndpointRequestId": "-", "awsEndpointRequestId2": "-", "customDomain_basePathMatched": "(none)", "dataProcessed": "-", "domainName": "service.abrahamsc.dev.singlecell.gi.ucsc.edu", "domainPrefix": "service", "error_message": "User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-east-1:********9775:65jyknf3ud/abrahamsc/GET/fetch/manifest/files with an explicit deny", "error_messageString": ""User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-east-1:********9775:65jyknf3ud/abrahamsc/GET/fetch/manifest/files with an explicit deny"", "error_responseType": "ACCESS_DENIED", "extendedRequestId": "TnW8aHXyIAMEQiQ=", "httpMethod": "GET", "identity_accountId": "-", "identity_caller": "-", "identity_cognitoAuthenticationProvider": "-", "identity_cognitoAuthenticationType": "-", "identity_cognitoIdentityId": "-", "identity_cognitoIdentityPoolId": "-", "identity_principalOrgId": "-", "identity_clientCert_clientCertPem": "-", "identity_clientCert_subjectDN": "-", "identity_clientCert_issuerDN": "-", "identity_clientCert_serialNumber": "-", "identity_clientCert_validity_notBefore": "-", "identity_clientCert_validity_notAfter": "-", "identity_sourceIp": "75.82.251.66", "identity_user": "-", "identity_userAgent": "curl/8.4.0", "identity_userArn": "-", "integration_error": "-", "integration_integrationStatus": "-", "integration_latency": "-", "integration_requestId": "-", "integration_status": "-", "integrationErrorMessage": "-", "integrationLatency": "-", "integrationStatus": "-", "path": "/fetch/manifest/files", "protocol": "HTTP/1.1", "requestId": "412e45a2-9321-4077-8b0b-f044a4364918", "requestTime": "24/Feb/2024:00:29:03 +0000", "requestTimeEpoch": "1708734543156", "responseLatency": "7", "responseLength": "202", "routeKey": "-", "stage": "abrahamsc", "status": "403"} | /aws/apigateway/azul-service-abrahamsc |
| 2024-02-24 00:29:02.782 | (0c5b3f17-ed86-45bc-9903-9c65b53cedaa) The client is not authorized to perform this operation. | API-Gateway-Execution-Logs_65jyknf3ud/abrahamsc |
| 2024-02-24 00:29:02.773 | {"accountId": "122796619775", "apiId": "65jyknf3ud", "authorizer_claims_property": "-", "authorizer_error": "-", "authorizer_principalId": "-", "authorizer_property": "-", "awsEndpointRequestId": "-", "awsEndpointRequestId2": "-", "customDomain_basePathMatched": "(none)", "dataProcessed": "-", "domainName": "service.abrahamsc.dev.singlecell.gi.ucsc.edu", "domainPrefix": "service", "error_message": "User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-east-1:********9775:65jyknf3ud/abrahamsc/GET/fetch/manifest/files with an explicit deny", "error_messageString": ""User: anonymous is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:us-east-1:********9775:65jyknf3ud/abrahamsc/GET/fetch/manifest/files with an explicit deny"", "error_responseType": "ACCESS_DENIED", "extendedRequestId": "TnW8WF9PoAMEAtQ=", "httpMethod": "GET", "identity_accountId": "-", "identity_caller": "-", "identity_cognitoAuthenticationProvider": "-", "identity_cognitoAuthenticationType": "-", "identity_cognitoIdentityId": "-", "identity_cognitoIdentityPoolId": "-", "identity_principalOrgId": "-", "identity_clientCert_clientCertPem": "-", "identity_clientCert_subjectDN": "-", "identity_clientCert_issuerDN": "-", "identity_clientCert_serialNumber": "-", "identity_clientCert_validity_notBefore": "-", "identity_clientCert_validity_notAfter": "-", "identity_sourceIp": "75.82.251.66", "identity_user": "-", "identity_userAgent": "curl/8.4.0", "identity_userArn": "-", "integration_error": "-", "integration_integrationStatus": "-", "integration_latency": "-", "integration_requestId": "-", "integration_status": "-", "integrationErrorMessage": "-", "integrationLatency": "-", "integrationStatus": "-", "path": "/fetch/manifest/files", "protocol": "HTTP/1.1", "requestId": "0c5b3f17-ed86-45bc-9903-9c65b53cedaa", "requestTime": "24/Feb/2024:00:29:02 +0000", "requestTimeEpoch": "1708734542773", "responseLatency": "9", "responseLength": "202", "routeKey": "-", "stage": "abrahamsc", "status": "403"} | /aws/apigateway/azul-service-abrahamsc |
| 2024-02-24 00:29:02.773 | (0c5b3f17-ed86-45bc-9903-9c65b53cedaa) Extended Request Id: TnW8WF9PoAMEAtQ= | API-Gateway-Execution-Logs_65jyknf3ud/abrahamsc |
| 2024-02-24 00:29:02.418 | (651ef7af-0ebc-41c7-b916-2ec10f59a7c6) The client is not authorized to perform this operation. | API-Gateway-Execution-Logs_65jyknf3ud/abrahamsc |
---

**Comment by achave11-ucsc** [comment]
This can be achieved by incorporating the [api_gateway_rest_api_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_rest_api_policy) Terraform resource to the deployment configuration. We might want to consider making this list of "potentially blocked" CIDRs configurable via a deployment specific environment variable.

The diagram in https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-authorization-flow.html, displays the behavior of API Gateway in regards to its resource policy. If one is included, then it must include a rule to allow all other services and one to explicitly block from our service a specific IP.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "In standup, @achave11-ucsc proposed blocking API Gateway from logging requests from abusive IPs using IAM permissions. Whether this works really depends on whether the source IP condition is set when API Gateway asks CloudWatch to log an event related to a request from such an IP."

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Since there still are at least two log entries per request with the policy based approach, it doesn't seem worth it. API Gateway has its own throttling but it is not per client-IP. Assignee to ask AWS support for guidance:

> We have an issue with abusive client that make an excessive number of requests to our API Gateway. The API is behind AWS WAF which is configured to implement a per-client rate limit and this is working well. However, both WAF and API Gateway make CloudWatch log entries for requests blocked by the WAF. Due to the sheer number of requests, significant log volume accumulates, incurring charges. We think that it is possible to disable WAF logging for rate-blocked requests, but no such mechanism seems to be available for API Gateway, which makes one log entry in the access log and multiple entries the execution log, for each client request. 
> 
> We would also like to know if there is (or could be) a CloudWatch log metric that indicates the number of requests by client IP as that would provide sufficient audit logging for our purposes, essentially simply counting each request, instead of logging it multiple times."

**Comment by dsotirho-ucsc** [comment]
> Assignee to ask AWS support for guidance

AWS Support Case ID [171019951601540](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=171019951601540&language=en) (platform-hca-prod)

**Comment by dsotirho-ucsc** [comment]
Assignee to reply on support case

**Comment by hannes-ucsc** [comment]
According to AWS support it is not possible to prevent rate-blocked requests from being logged. They suggested minimizing the log volume overall, which is not an option in our case. They also to use a CloudWatch Logs Insights query to obtain the number of blocked requests per IP. We are already doing that, in response to the alarm going off.
