### ISSUE TITLE
IAM policies set up inconsistently between accounts for developer and viewer roles

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5944]
The policies are inline in `anvilprod` and `anvildev` but separately managed in `dev` and `prod`. The administrator role has no custom policies either inline or separately managed.

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Assignee to provide screenshots highlighting the differences that I can use in an email to the organization administrator, asking about what the current practice is.

**Comment by achave11-ucsc** [comment]
The following screenshots compare the `dev` accounts at the top and the `prod` accounts at the bottom. AnVIL is the left side and HCA is the right side. 

The first screenshot demonstrates the difference between the inline developer role policy in the AnVIL accounts (left) defined as part of the `developer` role. Compared to the HCA ones, which is an attach custom `developer` policy.
<img width="2050" alt="RolesPanel-developer" src="https://github.com/DataBiosphere/azul/assets/19215510/47493477-cc3c-4ad1-aa09-08f845ad7baa">


This next screenshot makes that difference more obvious. Note the path of the policy definition is different, this exposes the difference of the HCA having a user defined policy called `developer` that is attached to the `developer` role, where as the AnVIL accounts define this policy permissions as part of the role.
<img width="2013" alt="RolePolicyvsAttachmentPolicy" src="https://github.com/DataBiosphere/azul/assets/19215510/3b8dd5f7-0bdf-48ba-af5c-78ede0e34b0a">

Finally, note that AnVIL does not have this `developer` policy whereas HCA does. This also shows the `developer` role/policy relationship for the HCA accounts. 
<img width="2050" alt="RoleAttachmentvsPolicy" src="https://github.com/DataBiosphere/azul/assets/19215510/e5e83ca5-639b-4441-8857-af17258bc440">

**Comment by dsotirho-ucsc** [comment]
Assignee to contact organization administrator.

**Comment by hannes-ucsc** [comment]
Organization admin contacted.

**Comment by hannes-ucsc** [comment]
Org admin reported this as fixed via email.
