### ISSUE TITLE
SC-7(7): Real-Time Scanning that is monitored 24/7 

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#5959]
SC-7(7): Real-time scanning that is monitored 24/7 rollout for all the developers
ITS response on implementation: The team can install the HX agent to add end-point monitoring for a device to the Mandiant services without removing Sentinel One. Many of our systems have Sophos for disk encryption management (https://its.ucsc.edu/computer-encryption/index.html) and SentinelOne Anti-Malware, along with HX (FireEye)

@achave11-ucsc was asked to ensure the scanning tools were installed on his device and monitor performance. Abraham shared the device is working as intended and performance was not impacted.

We need other developers to ensure the scanning Tools ITS recommended is installed with a screenshot for evidence collection

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by nolunwa-ucsc** [comment]
control here https://docs.google.com/document/d/1CdLiDuHOt4jBF-INdQmaSh01xmn29QNQ/edit#bookmark=id.rubauk7tzrlv

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "This was a mitigation requested by AO to work around the fact that we use split tunneling. We will disable split tunneling for production deployment zones (#3995). Therefore, there is no need for this mitigation anymore."
