### ISSUE TITLE
SSM Agent in GitLab lacks sufficient permissions in its role

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#5964]
… which causes alarms when the agent attempts various HEAD and GET requests to an associated SSM bucket.

Currently affecting `dev` and `anvildev`.

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: azul-trail-anvildev    
start-time: -3600s    
end-time: 0s    
query-string:
  ```
  fields @timestamp, errorCode, eventSource, eventName, userIdentity.invokedBy, requestParameters.bucketName
| parse 'assumed-role/*/' as assumed_role
| filter (
    errorCode like /UnauthorizedOperation/ 
    or
    errorCode like /AccessDenied/
    and not (
        eventSource = 's3.amazonaws.com' and eventName = 'GetObject' and userIdentity.invokedBy = 'cloudfront.amazonaws.com'
        or
        eventSource = 's3.amazonaws.com' and eventName = 'HeadBucket' and userIdentity.invokedBy = 'config.amazonaws.com'
        or
        eventSource = 's3.amazonaws.com' and eventName = 'HeadObject' and userIdentity.invokedBy = 'cloudfront.amazonaws.com'
        or
        eventSource = 'inspector2.amazonaws.com' and eventName = 'DescribeOrganizationConfiguration'
        or
        eventSource = 'elasticloadbalancing.amazonaws.com' and eventName = 'DescribeTargetGroupAttributes' and userIdentity.invokedBy = 'inspector2.amazonaws.com'
        or
        eventSource = 'ec2.amazonaws.com' and eventName = 'CreateNetworkInterface'
    )
)
| display @timestamp, errorCode, eventSource, eventName, assumed_role, requestParameters.bucketName
| sort @timestamp asc
| limit 100
  ```
---
| @timestamp | errorCode | eventSource | eventName | assumed_role | requestParameters.bucketName |
| --- | --- | --- | --- | --- | --- |
| 2024-02-16 19:04:36.675 | AccessDenied | s3.amazonaws.com | HeadBucket | azul-gitlab | amazon-ssm-packages-us-east-1 |
| 2024-02-16 19:04:51.514 | AccessDenied | s3.amazonaws.com | HeadObject | azul-gitlab | amazon-ssm-packages-us-east-1 |
| 2024-02-16 19:04:51.514 | AccessDenied | s3.amazonaws.com | GetObject | azul-gitlab | aws-ssm-document-attachments-us-east-1 |
| 2024-02-16 19:06:17.691 | AccessDenied | s3.amazonaws.com | HeadBucket | azul-gitlab | aws-ssm-document-attachments-us-east-1 |
| 2024-02-16 19:11:18.513 | AccessDenied | s3.amazonaws.com | HeadObject | azul-gitlab | amazon-ssm-packages-us-east-1 |
| 2024-02-16 19:11:18.513 | AccessDenied | s3.amazonaws.com | GetObject | azul-gitlab | aws-ssm-document-attachments-us-east-1 |
| 2024-02-16 19:11:18.516 | AccessDenied | s3.amazonaws.com | HeadBucket | azul-gitlab | amazon-ssm-packages-us-east-1 |
| 2024-02-16 19:11:18.516 | AccessDenied | s3.amazonaws.com | HeadObject | azul-gitlab | amazon-ssm-packages-us-east-1 |
---

- [x] Security design review completed; the Resolution of this issue does **not** …
  - [x] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [x] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [x] … affect the permissions of external users like access to
    - TDR snapshots
  - [x] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [x] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [x] … affect monitoring of the system
  - [x] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [x] … add an interface that exposes sensitive or confidential data at the security boundary
  - [x] … affect the encryption of data at rest
  - [x] … require persistence of sensitive or confidential data that might require encryption at rest
  - [x] … require unencrypted transmission of data within the security boundary
  - [x] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [x] Documentation on any unchecked boxes is provided in comments below

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Looks this started when we switched to VPC endpoints for S3 and DynamoDB (PR #5915). [According to Amazon](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent-minimum-s3-permissions.html) we need to then explicitly grant permissions to the s3 buckets that SSM accesses.

**Comment by hannes-ucsc** [comment]
For demo, show absence of trail log messages (see description) in every stable deployment, no earlier than two weeks after the fix lands in that deployment.

**Comment by achave11-ucsc** [comment]
Demo for this issue was unsuccessful.

The changes to the policy were not sufficient to prevent the SSM agent from causing `AccessDenied` errors. It was pointed out by @hannes-ucsc that this is likely due to 1) the boundary policy and 2) the ARN of the allowed buckets in the policy additions.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "The boundary policy is already at the size limit so we may not be able to list the individual buckets there but instead allow s3 read operations wholesale, regardless of bucket."

**Comment by dsotirho-ucsc** [comment]
We decided to track the remaining work in #6141
