### ISSUE TITLE
Documents are not sliced during manifest generation

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#5967]
`ManifestGenerator.field_globs` is meant to specify a subset of document fields to be retrieved when building the manifest. Currently the entire document is always retrieved, irrespective of the field globs.

Here is an en example using the compact manifest. On `develop`, the hits have this shape:

![Screenshot from 2024-02-16 17-19-29](https://github.com/DataBiosphere/azul/assets/48401926/a590446b-acac-4b25-b4e4-eb7211c8faf6)

If [this line](https://github.com/DataBiosphere/azul/blob/814d8482b3fa34cd5739974815d9f76df45530b4/src/azul/service/elasticsearch_service.py#L413) is fixed to return the configured document slice, as I believe in the intent, the hits' shape becomes:

![Screenshot from 2024-02-16 17-18-09](https://github.com/DataBiosphere/azul/assets/48401926/896eb10d-a4d6-4de2-9102-8bab961b292d)

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We should add either an *inexpensive and simple* assertion into the code under test, or add a test that would fail without the fix. The assertion would have to be looking for properties in the document returned by Elasticsearch, properties that would be excluded by the slice."

**Comment by hannes-ucsc** [comment]
<img width="1266" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/4ffd8cab-d5a4-4852-a583-106f7138027d">
<img width="1363" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/255edba6-0e68-4ef3-ba52-641e17ce1182">
<img width="1370" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/4dbf2f17-1a7a-4f06-b2d1-77a6d35cd937">
