### ISSUE TITLE
Annual Review of Event Types (AU-2 and AU-3)

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#5989]
Review and update the event types selected for logging annually and whenever there is a change in the threat environment.

Audit Logging Configuration:

Review current audit logging configuration in AWS. This includes services such as AWS CloudTrail, AWS Config, AWS GuardDuty, and VPC Flow Logs.
Ensure that all relevant AWS services are configured to capture necessary event types and log data.

Due 3/15

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Confirmed that the [AU-3 Content](https://docs.google.com/spreadsheets/d/1XTl3tQmr9wU1o8z8uGNjOU55jYlmWWMBR33QuKfg_S4/edit#gid=311132757) spreadsheet is up to date, and that logging is enabled and active for relevant AWS services.
