### ISSUE TITLE
Add ability to filter on {datasets,projects}.accessible

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5999]
Follow-up on #5268.

https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1709007819693409

**Comment by hannes-ucsc** [comment]
Requirements: 

Since the field is synthetic, using it as a filter would also require special logic. I overlooked that in #5268. On the `/index/{projects,datasets}` endpoint a filter value of `[true]` should only return hits for accessible projects/datasets. A filter value of `[false]` should only return hits for inaccessible projects/datasets. A filter value of `[true, false]` or `[false, true]` should return all hits that match any other filters present in the query. On other `/index/endpoints`, `[false]` should return no hits while any other filter values should return all hits that match any other filters present in the query.

The `/index/summary` endpoint should behave consistently with the above if that's straight-forward to implement, or ignore the filter otherwise.

**Comment by NoopDog** [comment]
Hi @hannes-ucsc do you have any questions for us on this feature?
Cheers,
D

cc: @bvizzier-ucsc

**Comment by hannes-ucsc** [comment]
No demo necessary since system administrator will manually test this change as part of the PR process:

<img width="607" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/fe71db3c-6ea9-4c94-9127-809084df4727">
