### ISSUE TITLE
Azul needs a proper license

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#6]
In the merge, we lost the top level license document.  The 2 licenses in the folders need to be replaced.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-10)
┆Project Name: azul
┆Issue Number: AZUL-10

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
