### ISSUE TITLE
DSS file proxy should pass through DSS 4xx responses

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#601]
When the proxy endpoint is hit without the required `replica` URL parameter, it returns a 500 response. The original body from the DSS 400 response is lost. We should just pass through 400 responses.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-375)
┆Project Name: azul
┆Issue Number: AZUL-375

**Comment by hannes-ucsc** [comment]
Consider translating 5xx responses to 504s.

**Comment by theathorn** [comment]
Closing - DSS is deprecated.
