### ISSUE TITLE
Add unit test coverage for `_list_bundles`

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6010]
https://github.com/DataBiosphere/azul/pull/5946#pullrequestreview-1891878272

![image](https://github.com/DataBiosphere/azul/assets/48401926/96bdc615-891b-46ac-b703-2530636707e4)

https://github.com/DataBiosphere/azul/pull/5946#pullrequestreview-1920531141

> 
> 
> > > Assuming that cans 2370f948 and 6b0f6c0f are related to 826dea02, can we avoid those cans and instead cover DUOS bundles, supplementary bundles and _list_bundles in a single test?
> > 
> > They are not related, they are all from different snapshots.
> 
> I agree that 6b0f6c0f is not related but 2370f948 and 826dea02 refer to the same dataset:
> 
> <img width="1213" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/2abc3e89-4c40-433d-97fc-6db9dd771ed3">
> 
> <p/>
> 
> > > can we avoid those cans and instead cover DUOS bundles, supplementary bundles and _list_bundles in a single test?
> > 
> > I don't understand this. Even if we added coverage for `_list_bundles`, we'd still need these cans to verify the output of `fetch_bundle`.
> > 
> 
> The test I envision covers both `list_bundles`, `fetch_bundle` in the repository plugin as well as the metadata plugin on the code side, and regular, DUOS and supplementary bundles on the data side. It does not assert the output of `fetch_bundle` but instead the index contents.
> 
> I am happy to merge this PR now, since it is an improvement, but what I describe above should be the goal of #6010.

**Comment by hannes-ucsc** [comment]
For demo, show increased coverage.
