### ISSUE TITLE
Support TSV export for AnVIL

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6013]
We are being requested to support TSV export for AnVIL.

Update:  
The following link was provided as an explanation of this feature request:  

- [Document](https://docs.google.com/document/d/1i_JHaJz5POz3IzLZb5O0Xom4e1MxxLRbpcC0JIXjUMI/edit?usp=sharing) 
- [Slack Conversation](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1679448754787529)

**Comment by dsotirho-ucsc** [comment]
Assignee to provide more details in description.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Assignee to review proposed changes and provide estimate.

**Comment by hannes-ucsc** [comment]
I answered all questions in the document and only found one actionable item:

> The exported TSV filename starts with “hca” yet should reasonably start with “anvil”.

The estimate for fixing that is 2.

<img width="1165" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/e7a19ffb-43a8-44bb-873c-8d19075fd925">

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We should use the Atlas name from `AZUL_CATALOGS` instead of the hard coded `hca` prefix for the default manifest file name."

**Comment by hannes-ucsc** [comment]
Re-triaging. I think this is done and can be closed.
