### ISSUE TITLE
Coerce exported manifest to Firecloud TSV

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#602]
The current manifest export feature generates an opinionated TSV of specific metadata.

Firecloud has a specific format for inputting manifests to their platform.

[https://gatkforums.broadinstitute.org/firecloud/discussion/10954/load-files-tsv-files](https://gatkforums.broadinstitute.org/firecloud/discussion/10954/load-files-tsv-files)

An additional feature will have to be added to place alignments and indices on the same row of the TSV, to follow Broad's model.

To close this demonstrate a test that can generate a Broad TSV from our export manifest. The Broad TSV has both participant and specimen primary keys.

When the export feature generates Broad compatible TSV, these will be stored to the s3 bucket.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-379)
┆Project Name: azul
┆Issue Number: AZUL-379
┆Epic: Feature Export from Boardwalk to HCA

**Comment by mjkrause** [comment]
See my comment in #604 re. the closing of this ticket.
