### ISSUE TITLE
Drop dcp1 from `prod`

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6023]
@hannes-ucsc: "The catalog takes up space and consumes time during a full reindex. Any citation links don't refer to a catalog so they won't break. If someone needs the catalog back we can easily reinstate it as long as the underlying snapshot remains in TDR."

**Comment by dsotirho-ucsc** [comment]
Assignee to provide description and consider next steps.

**Comment by hannes-ucsc** [comment]
Updated description. Assignee to remove catalog `dcp1` from `prod`.

**Comment by hannes-ucsc** [comment]
I found 128 requests from five distinct IPs for that catalog in the last month. One of them seems to be CC so feel that we need to give them a heads-up.

**Comment by dsotirho-ucsc** [comment]
Assignee to contact CC.

**Comment by bvizzier-ucsc** [comment]
I've pinged CC.  I will update when I get a response.

**Comment by NoopDog** [comment]
We don't have a dependency on the DCP1 catalog. Thanks for checking.
