### ISSUE TITLE
Make Broad TSV manifest S3 pre-signed URL

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#603]
The TSV manifests generated by request must be made available to Firecloud for initiating a workspace. To support this, add an endpoint that will return pre-signed URLs of the requested TSV manifest so that it can be used when creating a workspace.

https://github.com/DataBiosphere/azul/blob/develop/lambdas/service/app.py#L625

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-378)
┆Project Name: azul
┆Issue Number: AZUL-378
┆Epic: Feature Export from Boardwalk to HCA

**Comment by mjkrause** [comment]
I'm closing this ticket. #626 has a Jupyter notebook, which contains the pre-signed URL part.
