### ISSUE TITLE
VPC CIDRs are wrong

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6038]
Currently we use

| Zone | CIDR |
|---|---|
| `dev` | 172.71.0.0/16 |
| `prod` | 172.72.0.0/16 |
| `anvildev` | 172.73.0.0/16 |
| `anvilprod` | 172.74.0.0/16 |

That should be

| Zone | CIDR |
|---|---|
| `dev` | 172.21.0.0/16 |
| `prod` | 172.22.0.0/16 |
| `anvildev` | 172.23.0.0/16 |
| `anvilprod` | 172.24.0.0/16 |

starting at 21 instead of 71. Only 172.16.0.0 to 172.31.255.255 (172.16.0.0/12) should be used for private addressing. The rest of 172.0.0.0 - 172.255.255.255 (172.0.0.0/8) belongs to some internet provider.

**Comment by hannes-ucsc** [comment]
According to Amazon, it's [not possible to modify the CIDR of a VPC](https://repost.aws/knowledge-center/vpc-ip-address-range), it has to be destroyed and recreated. Hopefully, Terraform can do most of the heavy lifting here. Deployments with a private API have a lot of dependencies on resources in the VPC, so it will be easier to convert them to public APIs before we go ahead with changing the VPC's CIDR.

- [x] Prior to merging any PRs
   - [x] Preview a TF plan with a CIDR modification to confirm that TF picks `destroy-before-create`
   - [x] Destroy deployments with private API or make them public
      - [x] `dev` zone: none
      - [x] `anvildev` zone: `nadove4`, `nadove5` and `achave11`
      - [x] `anvilprod` zone: `nadove6`
   - [x] Enumerate per-deployment resources that depend on the VPC
   - [x] Write script to `terraform destroy` the resources enumerated in the previous step
- [x] For each main deployment
   - [x] Create a PR with the CIDR change for the `gitlab` component of the main deployment
   - [x] When merging the PR
      - [x] For each deployment colocated with the main deployment:
         - [x] Destroy resources that depend on the VPC using the script from above
      - [x] Deploy the `gitlab` component of the main deployment
      - [x] For each deployment colocated with the main deployment: 
         - [x] Run `make deploy` to recreate resources that were destroyed
      - [x] For `anvilprod` only: Make `nadove6` private again
- [ ] Update documentation (network diagram etc)
   - [x] Update CIDR
   - [ ] Update gateway and other public IPs

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Script to destroy VPC-dependent resources

… in personal deployment:

```
terraform plan -out destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan -destroy -target={aws_lambda_function.{indexer{,{_aggregate,_contribute}{,_retry},_indexercachehealth},service{,_manifest,_servicecachehealth}},aws_security_group.{indexer,service}}
terraform show -json destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan > destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan.json
terraform apply destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan
```

… in shared deployment:

```
terraform plan -out destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan -destroy -target={aws_security_group.{elasticsearch,indexer,service},aws_elasticsearch_domain.index}
terraform show -json destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan > destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan.json
terraform apply destroy_${AZUL_DEPLOYMENT_STAGE}.tfplan
```
