### ISSUE TITLE
Export manifest in BDBag to Terra

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#604]
These metadata must be available for the Firecloud data model. The alternative to including these at index time is to make requests for the requisite metadata as necessary.

To close, ensure file index has participant and specimen metadata available in the exported manifest. These metadata will be used to generated a Firecloud TSV input.

Following [~hannes-ucsc] suggestion, this should be done at indexing time, although it is possible to do at query-time.

The current transformer can be viewed here https://github.com/DataBiosphere/azul/blob/prod/src/azul/project/hca/transformers.py#L81 . 

Specimen metadata are added here at the bundle level: https://github.com/DataBiosphere/azul/blob/prod/src/azul/project/hca/transformers.py#L338

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-377)
┆Project Name: azul
┆Issue Number: AZUL-377
┆Epic: Feature Export from Boardwalk to HCA

**Comment by mjkrause** [comment]
To consolidate tickets, the work needed for #602 (Add participant and specimen metadata to manifest) will be part of this ticket. I will close #602.

**Comment by mjkrause** [comment]
Changed the title to better capture the work it entails.
