### ISSUE TITLE
Create PFB-based verbatim manifest format for AnVIL

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6040]
We split #4943 up into this issue and #6028. See the former (#4943) and its parent for details.

The primary objective is to produce a PFB that Terra accepts. Leave the `relations` field of every record—and therefore the `nodes.links` field of the `Metadata` record—an empty array. We'll add entity relations, and the prerequisite topological sort, in sibling #6066.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
For demo, perform a hand-over to Terra in `anvildev` and `anvilprod`, ideally as soon as the resolution lands there.. The filter should span multiple datasets.

**Comment by nadove-ucsc** [comment]
Demo completed on `anvildev`. Awaiting promotion to `anvilprod.`
