### ISSUE TITLE
Plan for  Export to Firecloud changes in Azul

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#605]
We will need to have the main Azul support export to firecloud

The definition of done is a written plan for how this feature could move into the main Azil repo

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-376)
┆Project Name: azul
┆Issue Number: AZUL-376
┆Epic: Feature Export from Boardwalk to HCA

**Comment by mjkrause** [comment]
See my comment re. closing of this ticket at #604.
