### ISSUE TITLE
Schedule monthly review of publicly accessible content

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#6051]
@hannes-ucsc: "We will create a schedule entry to create ticket titled `Monthly review of publicly accessible content` with me as the assignee and labels: `compliance`, `infra`, `doc`, `task`, `-` in the `azul-private` repository."

**Comment by dsotirho-ucsc** [comment]
Assignee to implement solution.

**Comment by nadove-ucsc** [comment]
For demo, show the new issue once it's been created by the schedule.
