### ISSUE TITLE
Annual role-based training - Abraham

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6053]
Please select a course from the following list that is appropriate for your role and one that you have not previously completed.

https://docs.google.com/document/d/11JZlwNppGfjAkYVHnD_bgQIzk7_Rn5sLY_lWpuw_gzo

Once you have selected the training, please add the name and the link as a comment to this issue.

Complete the training by March 29, 2024.   Be prepared to provide an overview of the selected training to the team at a future date.

Once you have completed the training, please close this ticket.

**Comment by achave11-ucsc** [comment]
Product Penetration Testing 101 : https://safecode.org/courses/product-penetration-testing-101/

**Comment by nolunwa-ucsc** [comment]
@achave11-ucsc reminder this is due to be completed on March 29, 2024. Please upload the training slide you intend to present here https://drive.google.com/drive/u/2/folders/1tfSzHu9T_NlarP5bZtd7vNhwMryU8cpy

**Comment by achave11-ucsc** [comment]
The provided drive folder has been updated with my presentation slides.

**Comment by nolunwa-ucsc** [comment]
Thanks, Demo has been scheduled for Monday 04/08 at 10:30am 
![Screenshot 2024-04-03 at 12 31 08 PM](https://github.com/DataBiosphere/azul/assets/67611976/887f947d-83b4-477f-a4aa-99eb17be1e93)
