### ISSUE TITLE
Annual role-based training - Noa

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6054]
Please select a course from the following list that is appropriate for your role and one that you have not previously completed.

https://docs.google.com/document/d/11JZlwNppGfjAkYVHnD_bgQIzk7_Rn5sLY_lWpuw_gzo

Once you have selected the training, please add the name and the link as a comment to this issue.

Complete the training by March 29, 2024. Be prepared to provide an overview of the selected training to the team at a future date.

Once you have completed the training, please close this ticket.

**Comment by nolunwa-ucsc** [comment]
@nadove-ucsc  reminder this is due to be completed on March 29, 2024. Please upload the training slide you intend to present here https://drive.google.com/drive/u/2/folders/1tfSzHu9T_NlarP5bZtd7vNhwMryU8cpy

**Comment by nadove-ucsc** [comment]
[System hardening 101](https://safecode.org/courses/system-hardening-101/)

**Comment by nadove-ucsc** [comment]
https://docs.google.com/presentation/d/1Nm2fqgScaQ42EMd8T_hPgt8ZCx0rXQWL6yQmPaKKCPU/edit?usp=drive_link

**Comment by nolunwa-ucsc** [comment]
Thanks, Demo has been scheduled for Monday 04/08 at 10:30am 
![Screenshot 2024-04-03 at 12 31 08 PM](https://github.com/DataBiosphere/azul/assets/67611976/887f947d-83b4-477f-a4aa-99eb17be1e93)

**Comment by nolunwa-ucsc** [comment]
This has been done and reviewed with the 2024 Assessment
