### ISSUE TITLE
Annual role-based training - Daniel

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6055]
ease select a course from the following list that is appropriate for your role and one that you have not previously completed.

https://docs.google.com/document/d/11JZlwNppGfjAkYVHnD_bgQIzk7_Rn5sLY_lWpuw_gzo

Once you have selected the training, please add the name and the link as a comment to this issue.

Complete the training by March 29, 2024. Be prepared to provide an overview of the selected training to the team at a future date.

Once you have completed the training, please close this ticket.

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc reminder this is due to be completed on March 29, 2024. Please upload the training slide you intend to present here https://drive.google.com/drive/u/2/folders/1tfSzHu9T_NlarP5bZtd7vNhwMryU8cpy

**Comment by dsotirho-ucsc** [comment]
Course: [AWS Security Best Practices for Developers](https://www.linkedin.com/learning/aws-security-best-practices-for-developers/securing-your-application?u=65318132)

**Comment by dsotirho-ucsc** [comment]
Training completed & presentation slide deck (PDF) uploaded to team's [Google Drive](https://drive.google.com/drive/u/2/folders/1tfSzHu9T_NlarP5bZtd7vNhwMryU8cpy).

**Comment by nolunwa-ucsc** [comment]
Thanks, Demo has been scheduled for Monday 04/08 at 10:30am 
![Screenshot 2024-04-03 at 12 31 08 PM](https://github.com/DataBiosphere/azul/assets/67611976/887f947d-83b4-477f-a4aa-99eb17be1e93)

**Comment by nolunwa-ucsc** [comment]
This has been done and reviewed with the 2024 Assessment
