### ISSUE TITLE
Annual role-based training - Hannes

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6056]
Please select a course from the following list that is appropriate for your role and one that you have not previously completed.

https://docs.google.com/document/d/11JZlwNppGfjAkYVHnD_bgQIzk7_Rn5sLY_lWpuw_gzo

Once you have selected the training, please add the name and the link as a comment to this issue.

Complete the training by March 29, 2024. Be prepared to provide an overview of the selected training to the team at a future date.

Once you have completed the training, please close this ticket.

**Comment by nolunwa-ucsc** [comment]
@hannes-ucsc reminder this is due to be completed on March 29, 2024. Please upload the training slide you intend to present here https://drive.google.com/drive/u/2/folders/1tfSzHu9T_NlarP5bZtd7vNhwMryU8cpy

**Comment by hannes-ucsc** [comment]
I'm taking https://www.linkedin.com/learning/securing-containers-and-kubernetes-ecosystem/container-working-environment?autoSkip=true&contextUrn=urn%3Ali%3AlyndaLearningPath%3A5c48d3fc498e244c8376de8c&resume=false&u=65318132

**Comment by hannes-ucsc** [comment]
Slide uploaded to folder: https://docs.google.com/presentation/d/1GDIh0p2jlFMo059Vidn2untQXm-dmjzWAvaE1F7yITQ/edit?usp=sharing

**Comment by nolunwa-ucsc** [comment]
Thanks, Demo has been scheduled for Monday 04/08 at 10:30am 
![Screenshot 2024-04-03 at 12 31 08 PM](https://github.com/DataBiosphere/azul/assets/67611976/887f947d-83b4-477f-a4aa-99eb17be1e93)

**Comment by nolunwa-ucsc** [comment]
This has been done and reviewed with the 2024 Assessment
