### ISSUE TITLE
Data Browser to Terra hand-off

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#606]
We would like to move features of Boardwalk to HCA

* Login
* Export
* streamline of metadata
* Resolution of HCA file DRS URIs to format required by Cromwell for workflow execution
* Anything else?

This may consist of multiple phases:
* MVP - initial implementation to get end-to-end flow working reliably
* Longer-term - final implementation, potentially including authentication/authorization

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-380)
┆containerName: azul
┆Issue Number: AZUL-380

**Comment by theathorn** [comment]
Test comment.

**Comment by theathorn** [comment]
Avro is now Epic #1132.

**Comment by theathorn** [comment]
6 -12 month roadmap is #1024.
