### ISSUE TITLE
Deindex snapshot for duplicate project

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6077]
[Slack discussion](https://humancellatlas.slack.com/archives/C9XD6L0AD/p1710871918535609?thread_ts=1710722156.419459&cid=C9XD6L0AD)

This is the one being kept:
https://explore.data.humancellatlas.org/projects/9c20a245-f2c0-43ae-82c9-2232ec6b594f

This is the one that needs to be redirected:
https://explore.data.humancellatlas.org/projects/c3354786-c17c-4e53-b4d7-c7afbed5b208

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Assignee to pop the snapshot for project `c3354786-c17c-4e53-b4d7-c7afbed5b208` from `dcp36`, no need to expedite with a manual deletion at this point."

**Comment by hannes-ucsc** [comment]
For demo, show that projects c3354786-c17c-4e53-b4d7-c7afbed5b208 and c0fecf0b-af86-41b8-ba82-d5fd81b7542a are absent from dcp36.
