### ISSUE TITLE
Installing `envhook.py` doesn't work on Ubuntu

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#608]
envhooks.py installs a `sitecustomize.py` but on ubuntu this is overwritten by [Apport](https://wiki.ubuntu.com/Apport) from their docs:

> For intercepting Python crashes it installs a /etc/python*/sitecustomize.py to call apport on unhandled exceptions.

If any `sitecustomize.py` is found, the others that would be found later are ignored.

Solution: import sitecustomize. If it fails, install! else if it succeeds, confirm that it is envhook.py. if it's not envhook and it succeeds, warn that sitecustomize is already in use.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-381)
┆Project Name: azul
┆Issue Number: AZUL-381

**Comment by hannes-ucsc** [comment]
`envhook.py install` should check if there already is a `sitecustomize.py` in another place on sys.path before installing its own copy.

**Comment by hannes-ucsc** [comment]
… and if there is, complain and refuse to install.
