### ISSUE TITLE
Add cache-control headers to responses

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6096]
[Slack Thread](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1711476533395239)

This is a request by @NoopDog to add cache control headers to the Data Explorer headers.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Spike to establish which of our sites in `anvilprod` (indexer, service, browser, portal) already return cache-control headers and which ones don't. "

**Comment by NoopDog** [comment]
@dsotirho-ucsc, cc @hannes-ucsc @bvizzier-ucsc, here is a patch to apply the cache control headers to the CloudFront responses. This modifies the "add_response_security_headers.js."

Let me know if you have any questions.

Otherwise, please let me know when this makes it to dev so I can test it.

Thanks,
D
[noopdog-6096-explorer-cache-conntrol-headers.patch](https://github.com/DataBiosphere/azul/files/14780418/noopdog-6096-explorer-cache-conntrol-headers.patch)

**Comment by dsotirho-ucsc** [comment]
> Spike to establish which of our sites in `anvilprod` (indexer, service, browser, portal) already return cache-control headers and which ones don't.

- Data Portal (https://anvilproject.org/) ... YES
- Data Browser (https://explore.anvilproject.org/) ... NO
- Azul service (https://service.explore.anvilproject.org/) ... NO
- Azul indexer (https://indexer.explore.anvilproject.org/) ... NO

**Comment by hannes-ucsc** [comment]
That patch is a bit messy. Here's a cleaned-up version for the `browser` component

```diff
Index: terraform/browser/add_response_security_headers.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/terraform/browser/add_response_security_headers.js b/terraform/browser/add_response_security_headers.js
--- a/terraform/browser/add_response_security_headers.js	(revision 420daa33a829582a135999329f5aea0923788dea)
+++ b/terraform/browser/add_response_security_headers.js	(date 1711583153074)
@@ -15,6 +15,24 @@
     headers['x-frame-options'] = { value: 'DENY' };
     headers['x-xss-protection'] = { value: '1; mode=block' };
 
-    // Return the response to viewers 
+    // Set cache control headers …
+    if (uri.startsWith('/_next/static/')) {
+        // … for files in _next/static (versioned assets like JS, CSS)
+        headers['cache-control'] = { value: 'public, max-age=31536000, immutable' };
+    } else if (uri.startsWith('/api/')) {
+        // … for API routes
+        headers['cache-control'] = { value: 'no-store' };
+    } else if (
+        uri.startsWith('/static/')
+        || uri.match(/\.(jpg|jpeg|png|svg|webp|gif|css|js)$/)
+    ) {
+        // … for images and other static assets
+        headers['cache-control'] = { value: 'public, max-age=86400' };
+    } else {
+        // … for HTML pages and all other content
+        headers['cache-control'] = { value: 'public, max-age=0, must-revalidate' };
+    }
+
+    // Return the response to viewers
     return response;
-}
\ No newline at end of file
+}
```

**Comment by hannes-ucsc** [comment]
For Azul, the header should be set according the following rules:

| Path | Header value | Comment |
|---|---|---|
| / | public, max-age=0, must-revalidate |  |
| /static/* | public, max-age=86400 |  |
| /openapi | public, max-age=500 |  |
| /oauth2_redirect | no-store | in case the default changes |
| ** | no-store | default |

This is for both indexer and service.

**Comment by hannes-ucsc** [comment]
For demo, show headers in a selection of service, indexer and browser responses in a main deployment.

**Comment by dsotirho-ucsc** [comment]
Assignee to request that CC review this in `dev`.

**Comment by NoopDog** [comment]
LGTM @dsotirho-ucsc. Thanks for your work on this!
Cheers,
D
