### ISSUE TITLE
Add managed-access integration test for verbatim manifests

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6098]
Add a managed access subtest to the IT that generates three small verbatim manifests. The first should use filters that include files from both public and private sources and be requested using service account credentials. The second should use the same filters, but the default credentials. The third should use filters that include only the files from the private sources used by the first two manifests. Assert that the third manifest is the set difference of the first manifest and the second, i.e., M3 = M1 \ M2.

[edit: @hannes-ucsc] The test should cover all verbatim formats currently implemented.

**Comment by achave11-ucsc** [comment]
Assignee to provide description.

**Comment by achave11-ucsc** [comment]
Assignee to include this in the PR #6029 for #6028.

**Comment by hannes-ucsc** [comment]
> Assignee to include this in the PR #6029 for #6028.

Decided not to include it.
