### ISSUE TITLE
Automate deployment of the WebService

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#61]
As a system administrator I need to have an automated way of deploying the webservice on AWS Lambda.

DOD: I type `make deploy` on the terminal, the script takes any necessary arguments, and creates an instance of the webservice via chalice on AWS Lambda (serverless deployment)
Repo: https://github.com/DataBiosphere/cgp-dashboard-service

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-42)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-42

**Comment by hannes-ucsc** [comment]
Resolved by 16c907d7cf9a96a3ce0d4d7c4b0a06590a3d0e09
