### ISSUE TITLE
Tallies are wrong when reindexing into a populated index

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#610]
Follow-up on #86/#600

Without deleting the indices before reindexing, the tallies end up being inflated. This could cause excessive, unnecessary updates to the aggregates.

As a stop-gap, what used to be `make delete_and_reindex` is now invoked via `make reindex`.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-385)
┆Project Name: azul
┆Issue Number: AZUL-385

**Comment by theathorn** [comment]
make reindex deletes the index by default - no longer an issue.
