### ISSUE TITLE
ES instance snapshots are enabled again

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6103]
A support ticket against AWS for each account needs to be open to disable it. This feature (only configurable by AWS) was disabled in the Azul ES instances after recreating the domains as part of the work toward fixing #6038.

**Comment by achave11-ucsc** [comment]
Support tickets in …

`dev`: https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=171166432301054&language=en

`anvildev`: https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=171166709601533&language=en

`anvilprod`:https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=171166517401262&language=en

`prod`: https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=171166498501571&language=en

… have been created to disable this feature.

**Comment by achave11-ucsc** [comment]
For the `dev` account, the automatic snapshotting is disabled:
  
<img width="952" alt="dev" src="https://github.com/DataBiosphere/azul/assets/19215510/d67a9bb7-9c29-4e87-8549-9de8bc17b663">
<img width="824" alt="sandbox" src="https://github.com/DataBiosphere/azul/assets/19215510/a40ee2f4-6f8e-4027-8ba7-cda080925ee8">

**Comment by achave11-ucsc** [comment]
For the `anvildev` account, the automatic snapshotting is disabled:
<img width="866" alt="anvildev" src="https://github.com/DataBiosphere/azul/assets/19215510/0274971f-5ae6-4c48-8581-a1d165423dfa">
<img width="844" alt="anvilbox" src="https://github.com/DataBiosphere/azul/assets/19215510/57e82635-2e3a-4a7d-bf63-f8fdc11a5e8c">

**Comment by achave11-ucsc** [comment]
For the `anvilprod` account, the automatic snapshotting is disabled:
<img width="910" alt="anvilprod" src="https://github.com/DataBiosphere/azul/assets/19215510/a8cec2d3-fec3-475f-8e2e-89b7f221245a">
<img width="942" alt="hammerbox" src="https://github.com/DataBiosphere/azul/assets/19215510/1a367dac-aa6c-4a5c-803b-0a7920441f0b">

**Comment by achave11-ucsc** [comment]
For the `prod` account, the automatic snapshotting is disabled:

<img width="861" alt="prod" src="https://github.com/DataBiosphere/azul/assets/19215510/ca3ecde9-1c0e-4194-a87c-1f21ca37de29">

**Comment by dsotirho-ucsc** [comment]
Assignee to close and rate AWS Support tickets.

**Comment by dsotirho-ucsc** [comment]
Resolved and rated AWS Support cases on `dev`, `anvildev`, and `anvilprod`.
Awaiting confirmation response from AWS on `prod` before resolving case.

**Comment by dsotirho-ucsc** [comment]
Resolved and rated AWS Support case on `prod`.
