### ISSUE TITLE
Include unlinked entities when filter is entire AnVIL dataset

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6107]
@hannes-ucsc: "This came in via Slack, initially [disguised](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1711517743299339) as a bug report. I am opposed to implementing it for the reasons outlined in that thread."

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
We are obligated to implement this. It is included in #6529.
