### ISSUE TITLE
Create PFB-based verbatim manifest format for HCA

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6122]

**Comment by hannes-ucsc** [comment]
For demo, perform a large-ish hand-over in `dev` and `prod`. Ideally, two separate demos, each one as soon as the feature lands in each deployment. Larg-ish in `dev` means all files, in `prod` around 10k files.

**Comment by nadove-ucsc** [comment]
Successful handover performed in `dev` using 103 out of 105 projects (2 projects absent due to https://github.com/DataBiosphere/azul/issues/6469) for ~115k files.
