### ISSUE TITLE
Expose the following facets for HCA

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6130]
We need the following facets available to the Data Browser:
* data_use_restriction
* access -> If the user has access to snapshots
* atlases

@NoopDog: Please provide any additional clarification that might be needed.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
> We need the following facets available to the Data Browser:
> 
> * data_use_restriction

New issue: https://github.com/DataBiosphere/azul/issues/6131

> * access -> If the user has access to snapshots

This is already exposed in responses but filterability is missing: https://github.com/DataBiosphere/azul/issues/5999

> 
> * atlases

See https://github.com/DataBiosphere/azul/issues/5519. This is already exposed in responses but we discovered during demos that it is [incomplete](https://github.com/DataBiosphere/azul/issues/5519#issuecomment-2008298328). To completely resolve it, we would need to resolve a [blocker](https://github.com/DataBiosphere/azul/issues/2621) first.

**Comment by dsotirho-ucsc** [comment]
Work is tracked in individual tickets.
