### ISSUE TITLE
Alarm `api_unauthorized` for manifest `GetObject` & `HeadObject`

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6133]
**[CloudWatch Logs Insights](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-04-05T13*3a14*3a08.705Z~start~'2024-04-05T13*3a10*3a18.823Z~timeType~'ABSOLUTE~tz~'LOCAL~editorString~'fields*20*40timestamp*2c*20errorCode*2c*20eventSource*2c*20eventName*2c*20userIdentity.invokedBy*2c*20requestParameters.key*2c*20requestParameters.bucketName*2c*20*40message*0a*7c*20filter*20*28*0a*20*20*20*20errorCode*20like*20*2fUnauthorizedOperation*2f*20*0a*20*20*20*20or*0a*20*20*20*20errorCode*20like*20*2fAccessDenied*2f*0a*29*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*20100~queryId~'2822ac50-978d-4e7f-b0e2-07d0dab8723d~source~(~'azul-trail-dev)))**    
region: us-east-1    
log-group-names: azul-trail-dev    
start-time: 2024-04-05T13:10:18.823Z    
end-time: 2024-04-05T13:14:08.705Z    
query-string:
  ```
  fields @timestamp, errorCode, eventSource, eventName, userIdentity.invokedBy, requestParameters.key, requestParameters.bucketName, @message
| filter (
    errorCode like /UnauthorizedOperation/ 
    or
    errorCode like /AccessDenied/
)
| sort @timestamp asc
| limit 100
  ```
---
| @timestamp | errorCode | eventSource | eventName | userIdentity.invokedBy | requestParameters.key | requestParameters.bucketName | @message |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 2024-04-05 13:12:35.664 | AccessDenied | s3.amazonaws.com | HeadObject |  | manifests/2f3c7abc-b363-5107-b6bb-769dbaca8f71.ad14b32b-dea0-555e-b745-8ebe5bb0958d.tsv | edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1 | {"eventVersion":"1.09","userIdentity":{"type":"AWSAccount","principalId":"","accountId":"anonymous"},"eventTime":"2024-04-05T13:08:44Z","eventSource":"s3.amazonaws.com","eventName":"HeadObject","awsRegion":"us-east-1","sourceIPAddress":"51.15.164.30","userAgent":"[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36]","errorCode":"AccessDenied","errorMessage":"Access Denied","requestParameters":{"bucketName":"edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1","Host":"s3.amazonaws.com","key":"manifests/2f3c7abc-b363-5107-b6bb-769dbaca8f71.ad14b32b-dea0-555e-b745-8ebe5bb0958d.tsv"},"responseElements":null,"additionalEventData":{"CipherSuite":"ECDHE-RSA-AES128-GCM-SHA256","bytesTransferredIn":0,"x-amz-id-2":"KTn6abgIJBhB5W39AuMeiA1xukIGLKpbFqF1J4og1M4NkhGXQJ0flnarqE6Iagga3sK1F7riBco=","bytesTransferredOut":243},"requestID":"QDCZN92TM7Q6SVCE","eventID":"4be0a3f7-4b7a-474b-bdb5-e9d427216c5e","readOnly":true,"resources":[{"type":"AWS::S3::Object","ARN":"arn:aws:s3:::edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1/manifests/2f3c7abc-b363-5107-b6bb-769dbaca8f71.ad14b32b-dea0-555e-b745-8ebe5bb0958d.tsv"},{"accountId":"122796619775","type":"AWS::S3::Bucket","ARN":"arn:aws:s3:::edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1"}],"eventType":"AwsApiCall","managementEvent":false,"recipientAccountId":"122796619775","sharedEventID":"cb7b6ac1-ea9f-452b-9bf4-570aaa2707a8","eventCategory":"Data","tlsDetails":{"tlsVersion":"TLSv1.2","cipherSuite":"ECDHE-RSA-AES128-GCM-SHA256","clientProvidedHostHeader":"s3.amazonaws.com"}} |
---

```
{
    "eventVersion": "1.09",
    "userIdentity": {
        "type": "AWSAccount",
        "principalId": "",
        "accountId": "anonymous"
    },
    "eventTime": "2024-04-05T13:08:44Z",
    "eventSource": "s3.amazonaws.com",
    "eventName": "HeadObject",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "51.15.164.30",
    "userAgent": "[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36]",
    "errorCode": "AccessDenied",
    "errorMessage": "Access Denied",
    "requestParameters": {
        "bucketName": "edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1",
        "Host": "s3.amazonaws.com",
        "key": "manifests/2f3c7abc-b363-5107-b6bb-769dbaca8f71.ad14b32b-dea0-555e-b745-8ebe5bb0958d.tsv"
    },
    "responseElements": null,
    "additionalEventData": {
        "CipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "bytesTransferredIn": 0,
        "x-amz-id-2": "KTn6abgIJBhB5W39AuMeiA1xukIGLKpbFqF1J4og1M4NkhGXQJ0flnarqE6Iagga3sK1F7riBco=",
        "bytesTransferredOut": 243
    },
    "requestID": "QDCZN92TM7Q6SVCE",
    "eventID": "4be0a3f7-4b7a-474b-bdb5-e9d427216c5e",
    "readOnly": true,
    "resources": [
        {
            "type": "AWS::S3::Object",
            "ARN": "arn:aws:s3:::edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1/manifests/2f3c7abc-b363-5107-b6bb-769dbaca8f71.ad14b32b-dea0-555e-b745-8ebe5bb0958d.tsv"
        },
        {
            "accountId": "122796619775",
            "type": "AWS::S3::Bucket",
            "ARN": "arn:aws:s3:::edu-ucsc-gi-platform-hca-dev-storage-sandbox.us-east-1"
        }
    ],
    "eventType": "AwsApiCall",
    "managementEvent": false,
    "recipientAccountId": "122796619775",
    "sharedEventID": "cb7b6ac1-ea9f-452b-9bf4-570aaa2707a8",
    "eventCategory": "Data",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "s3.amazonaws.com"
    }
}
```

Edit: **[@achave11-ucsc]**
And for the `GetObject` instances see https://github.com/DataBiosphere/azul/issues/6133#issuecomment-2071149472

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "This seems to be someone parsing a signed URL to a manifest and making a S3 API request to the manifest object. If that is correct, there should be a very low incident rate, so I don't think this requires any additional work but we will let this sit for a little in order to determine its prevalence."

**Comment by achave11-ucsc** [comment]
Rework this issue to reflect the fact that we also get this for GetObject.

**Comment by achave11-ucsc** [comment]
Incidents with `GetObject`:
[CW Insights](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-345600~timeType~'RELATIVE~unit~'seconds~editorString~'fields*20*40timestamp*2c*20errorCode*2c*20eventSource*2c*20eventName*2c*20userIdentity.type*20as*20identityType*2c*20*0a*20*20*20*20*20*20*20userIdentity.sessionContext.sessionIssuer.userName*20as*20userName*2c*20userIdentity.invokedBy*20as*20invokedBy*2c*20*0a*20*20*20*20*20*20*20requestParameters.key*20as*20requestKey*2c*20requestParameters.bucketName*20as*20requestBucket*2c*20*40message*0a*7c*20filter*20errorCode*20like*20*2fUnauthorizedOperation*7cAccessDenied*2f*0a*7c*20parse*20requestParameters.key*20*2f*5e*28*3f*3cmanifest*3emanifest*3f*29s*5c*2f*2f*0a*23*20*7c*20filter*20*40message*20like*20*22163.221.234.87*22*0a*7c*20filter*20manifest*20like*20*22manifest*22*0a*23*20*7c*20stats*20count*28*2a*29*20by*20errorCode*2c*20eventSource*2c*20identityType*2c*20userName*2c*20invokedBy*2c*20eventName*2c*20requestParameters.bucketName*2c*20manifest*0a*23*20*7c*20order*20by*20*40timestamp*20asc~queryId~'12cf92f3-ce87-4135-9903-60b07a8df297~source~(~'azul-trail-prod~'*2faws*2fapigateway*2fazul-service-prod)))
```
[
    {
        "@timestamp": "2024-04-22 02:56:41.615",
        "errorCode": "AccessDenied",
        "eventSource": "s3.amazonaws.com",
        "eventName": "GetObject",
        "identityType": "AWSAccount",
        "userName": "",
        "invokedBy": "",
        "requestKey": "manifests/9f6b8a24-b7f6-5b70-87d0-ffdc68cdb2ec.3a608926-d03f-5407-a0c6-86306dbf014e.avro",
        "requestBucket": "edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1",
        "@message": {
            "eventVersion": "1.09",
            "userIdentity": {
                "type": "AWSAccount",
                "principalId": "",
                "accountId": "anonymous"
            },
            "eventTime": "2024-04-22T02:53:16Z",
            "eventSource": "s3.amazonaws.com",
            "eventName": "GetObject",
            "awsRegion": "us-east-1",
            "sourceIPAddress": "*.*.234.87",
            "userAgent": "[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0]",
            "errorCode": "AccessDenied",
            "errorMessage": "Access Denied",
            "requestParameters": {
                "bucketName": "edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1",
                "Host": "s3.amazonaws.com",
                "key": "manifests/9f6b8a24-b7f6-5b70-87d0-ffdc68cdb2ec.3a608926-d03f-5407-a0c6-86306dbf014e.avro"
            },
            "responseElements": null,
            "additionalEventData": {
                "CipherSuite": "TLS_AES_128_GCM_SHA256",
                "bytesTransferredIn": 0,
                "x-amz-id-2": "1gDFOtTC8dMlMAOaI5Ws+4A+qI9q6PJFpAAWqkXUGGebCc5bHI0IhOOAzTbeH9L/0hG76SIzu/I=",
                "bytesTransferredOut": 243
            },
            "requestID": "C37BHQ558J402Y9Y",
            "eventID": "979bd94b-9563-4691-9d6a-752ab335a44c",
            "readOnly": true,
            "resources": [
                {
                    "type": "AWS::S3::Object",
                    "ARN": "arn:aws:s3:::edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1/manifests/9f6b8a24-b7f6-5b70-87d0-ffdc68cdb2ec.3a608926-d03f-5407-a0c6-86306dbf014e.avro"
                },
                {
                    "accountId": "542754589326",
                    "type": "AWS::S3::Bucket",
                    "ARN": "arn:aws:s3:::edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1"
                }
            ],
            "eventType": "AwsApiCall",
            "managementEvent": false,
            "recipientAccountId": "542754589326",
            "sharedEventID": "67658f0c-ae44-4aee-914d-809e1d5c8b68",
            "eventCategory": "Data",
            "tlsDetails": {
                "tlsVersion": "TLSv1.3",
                "cipherSuite": "TLS_AES_128_GCM_SHA256",
                "clientProvidedHostHeader": "s3.amazonaws.com"
            }
        }
    },
    {
        "@timestamp": "2024-04-20 16:03:10.367",
        "errorCode": "AccessDenied",
        "eventSource": "s3.amazonaws.com",
        "eventName": "GetObject",
        "identityType": "AWSAccount",
        "userName": "",
        "invokedBy": "",
        "requestKey": "manifests/9b98a7c3-6dcc-51b9-9ec0-d05ee5d1512a.3a608926-d03f-5407-a0c6-86306dbf014e.avro",
        "requestBucket": "edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1",
        "@message": {
            "eventVersion": "1.09",
            "userIdentity": {
                "type": "AWSAccount",
                "principalId": "",
                "accountId": "anonymous"
            },
            "eventTime": "2024-04-20T15:58:41Z",
            "eventSource": "s3.amazonaws.com",
            "eventName": "GetObject",
            "awsRegion": "us-east-1",
            "sourceIPAddress": "*.*.159.229",
            "userAgent": "[Wget/1.21.2]",
            "errorCode": "AccessDenied",
            "errorMessage": "Access Denied",
            "requestParameters": {
                "bucketName": "edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1",
                "Host": "s3.amazonaws.com",
                "key": "manifests/9b98a7c3-6dcc-51b9-9ec0-d05ee5d1512a.3a608926-d03f-5407-a0c6-86306dbf014e.avro"
            },
            "responseElements": null,
            "additionalEventData": {
                "CipherSuite": "TLS_AES_128_GCM_SHA256",
                "bytesTransferredIn": 0,
                "x-amz-id-2": "n3buasLaRaaU2t6itMwhELEk2qmgfRxVyi8tqQ4lKfIWXL5cXtdYeb4Ng/e9lYLFxnYYu8N7lOI=",
                "bytesTransferredOut": 243
            },
            "requestID": "NM0BYS5142SD1GJZ",
            "eventID": "2e1c33c9-2366-45a8-9945-a0d9d5e0ee70",
            "readOnly": true,
            "resources": [
                {
                    "type": "AWS::S3::Object",
                    "ARN": "arn:aws:s3:::edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1/manifests/9b98a7c3-6dcc-51b9-9ec0-d05ee5d1512a.3a608926-d03f-5407-a0c6-86306dbf014e.avro"
                },
                {
                    "accountId": "542754589326",
                    "type": "AWS::S3::Bucket",
                    "ARN": "arn:aws:s3:::edu-ucsc-gi-platform-hca-prod-storage-prod.us-east-1"
                }
            ],
            "eventType": "AwsApiCall",
            "managementEvent": false,
            "recipientAccountId": "542754589326",
            "sharedEventID": "b5b8afa4-e8d7-435b-8cca-f16251cf401b",
            "eventCategory": "Data",
            "tlsDetails": {
                "tlsVersion": "TLSv1.3",
                "cipherSuite": "TLS_AES_128_GCM_SHA256",
                "clientProvidedHostHeader": "s3.amazonaws.com"
            }
        }
    }
]
```

**Comment by dsotirho-ucsc** [comment]
Close `wontfix` when blocker is resolved.

**Comment by hannes-ucsc** [comment]
*(Posted by Claude Code)*

PR #8228 for #8118 should resolve this. It adds a clause to the `api_unauthorized` metric filter that excludes anonymous S3 access to qualified Azul buckets, which covers the manifest `GetObject` and `HeadObject` events reported here:

```python
_or(
    '$.eventSource != "s3.amazonaws.com"',
    '$.userIdentity.accountId NOT EXISTS',
    '$.userIdentity.accountId != "anonymous"',
    '$.requestParameters.bucketName NOT EXISTS',
    f'$.requestParameters.bucketName != "{aws.qualified_bucket_name('*')}"'
)
```
