### ISSUE TITLE
Setting up credentials and environment

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#614]
Following the README in https://github.com/DataBiosphere/azul/tree/develop to set up AWS, PyCharm, Terraform, and run simple integration tests mentioned (e.g.,`make ...`).

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-387)
┆Project Name: azul
┆Issue Number: AZUL-387
┆Epic: Feature Export from Boardwalk to HCA

**Comment by mjkrause** [comment]
* Set up AWS credentials and tested access (thanks @achave11 for help). 

* Ran all `make ...` described in https://github.com/DataBiosphere/azul/tree/develop.

* Set up PyCharm (incl. setting env. vars. using `envhook.py` thanks to @jessebrennan).

* Ran all tests (indexer and service) and all passed. 

* `make reindex` is the only one that hasn't worked yet (0 reindexed).
