### ISSUE TITLE
Add unit test coverage for AnVIL JSONL manifest

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6140]
Add test to `test_manifest.TestAnvilManifests` covering generation of the `verbatim_jsonl` manifest format. Test should mirror the existing test for HCA in `test_manifest.TestManifests`.

**Comment by dsotirho-ucsc** [comment]
Assignee to provide description.

**Comment by nadove-ucsc** [comment]
Freebie of https://github.com/DataBiosphere/azul/pull/6115/commits

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "For demo, show increase in test coverage."
