### ISSUE TITLE
Indexer /health endpoint falsely reports fail queue to be down

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#615]
Also looks like some of the queues are missing from the health endpoint.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-388)
┆Project Name: azul
┆Issue Number: AZUL-388

**Comment by achave11** [comment]
Superseded by #664

**Comment by hannes-ucsc** [comment]
Demoed on 1/18/19 but see #664.
