### ISSUE TITLE
Invalid IAM permission actions specified in policies

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6152]
`s3:HeadBucket` and `s3:HeadObject` are not valid s3 policy actions.

https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html

Recommendation is to use `s3:ListBucket` and `s3:GetObject` instead.

**Comment by dsotirho-ucsc** [comment]
Assignee to include issue with s3:HeadObject and to update title to indicate problem.

**Comment by hannes-ucsc** [comment]
Assignee to replace every mention of `s3:HeadObject` with `s3:GetObject` and every mention of `s3:HeadBucket` with `s3:ListBucket`.
