### ISSUE TITLE
Upgrade to PyCharm 2024.1

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6173]
Wait until 2024.1.1 is out

**Comment by achave11-ucsc** [comment]
Assignee to wait until 2024.1.1 (or later) is released.

**Comment by achave11-ucsc** [comment]
PyCharm 2024.1.1 has been released, https://youtrack.jetbrains.com/articles/PY-A-233538208/PyCharm-2024.1.1-241.15989.155-build-Release-Notes.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Decided to wait for 2024.1.2"

**Comment by dsotirho-ucsc** [comment]
PyCharm 2024.1.2 has been released. https://youtrack.jetbrains.com/articles/PY-A-233538220/PyCharm-2024.1.2-241.17011.127-build-Release-Notes

**Comment by dsotirho-ucsc** [comment]
To be completed with the PR for #6293
