### ISSUE TITLE
Delete personal deployments colocated with `anvilprod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6183]
~Also scale back the infrastructure we scaled up temporarily in order to test verbatim manifests at scale.~

Edit by @dsotirho-ucsc : Tracked in https://github.com/DataBiosphere/azul/issues/6218

**Comment by nadove-ucsc** [comment]
`nadove6` has been destroyed. https://service.nadove6.explore.anvilproject.org/

**Comment by nadove-ucsc** [comment]
I don't know how, when or why, but the deployment exists again. The index endpoints do not appear to be functional.

**Comment by dsotirho-ucsc** [comment]
Assignee to destroy deployment again.

**Comment by nadove-ucsc** [comment]
All resources have been destroyed except for [the GCP IAM role](https://console.cloud.google.com/iam-admin/roles/details/projects%3Cplatform-anvil-prod%3Croles%3Cazul_nadove6_1;returnToCustom=true?project=platform-anvil-prod), which is schedule for deletion.
