### ISSUE TITLE
IR/CP Training and Testing for Noa

### ISSUE THREAD

**Issue by nolunwa-ucsc** [DataBiosphere/azul#6191]
Hello @nadove-ucsc since you missed the IR/CP training and testing, we recording the meeting. Kindly watch it and reach out if the have question. To be completed by 4/30

Link to the video https://ucsc.zoom.us/rec/share/-vYedJaz0FheGjkfFGebE_LwvDOARGgihn9_J822qu9JzCtAADtCFF7X1311TbOd.ve8-BPuKJc-7zsJ8

Meeting note https://docs.google.com/document/d/1mcT_Zz9lteeUHTrWPHe8QozWljpd3Pb4/edit#heading=h.gjdgxs

**Comment by nadove-ucsc** [comment]
I've reviewed the recorded meeting and accompanying notes.
