### ISSUE TITLE
Add endpoint for fetching project details 

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#62]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-41)
┆Project Name: azul
┆Issue Number: AZUL-41

**Comment by theathorn** [comment]
Hannes to comment on how to do this and re-assign to Dave.

**Comment by NoopDog** [comment]
HI @hannes this would then will pull down the description, publications, author list etc. For each project making the /projects api call a bit heavy. Would  be best if possible to have a specific endpoint /project/id that lets us get the extra detail for the project and not have to have that in every list?

We can of course accomidate the heavier /projects api but wanted to see if you felt we can go with /project/id

Cheers,
D

**Comment by hannes-ucsc** [comment]
I'm undecided. I think a large row size is ok as long as there are few rows in the response. Let's try the heavy API and optimize when we need to. I'm sure we will need to at some point when we have larger number of projects, like > 100. Iceboxing this until then.

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
