### ISSUE TITLE
Switch to NIST 800-53 r5 standard in SecurityHub

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6203]
- [x] Disable [AWS Foundational Security Best Practices v1.0.0](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/aws-foundational-security-best-practices-1.0.0)
- [x] Disable [CIS AWS Foundations Benchmark v1.2.0](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/cis-aws-foundations-benchmark-1.2.0)
- [ ] ~Update to [CIS AWS Foundations Benchmark v3.0.0](https://docs.aws.amazon.com/securityhub/latest/userguide/cis-aws-foundations-benchmark.html#cis3v0-standard)~
- [x] Enable *NIST Special Publication 800-53 Revision 5*
- [x] #6220

~If~ we need to keep the CIS standard, ~which I don't think we do~, we ~can~ will switch to version 3.0.0 which does not include the [CloudWatch.2](https://docs.aws.amazon.com/securityhub/latest/userguide/cloudwatch-controls.html#cloudwatch-2) control that requires that alarm.

Also, these links don't work anymore:

<img width="1183" alt="image" src="https://github.com/DataBiosphere/azul/assets/5143256/6f74c8bd-2d63-4ef8-8991-3f73d0765e4b">

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Assign when unblocked.

**Comment by hannes-ucsc** [comment]
As discussed in Questions on compliance controls meeting, Thursday, June 27 there is a change in plans: Upgrade to *CIS AWS Foundations Benchmark v3.0.0*, don't enable *NIST Special Publication 800-53 Revision 5*.

Description and title were updated accordingly.

**Comment by dsotirho-ucsc** [comment]
Assignee to update PR in light of the updated title & description.

**Comment by hannes-ucsc** [comment]
Discussed this again on 7/17/2024. Decided to reconsider including the 800-53 standard. Before we disable CIS Foundations, we should compare CIS Foundations to the 800-53 standard. Assignee to use https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_BatchGetStandardsControlAssociations.html to create a spreadsheet with a row per control and a column per standard (benchmark). The cell would have an "X" in it if the control was in the standard.

**Comment by dsotirho-ucsc** [comment]
Spreadsheet:
https://docs.google.com/spreadsheets/d/1Pe0rtQgFagHSO0bjD0DrZ_HqYqCm6usbSXOrXDL-0KE/edit?gid=0#gid=0

Note: BatchGetStandardsControlAssociations could not be used as the standard has be enabled in the account before the request can be made:

```
$ aws securityhub batch-get-standards-control-associations --standards-control-association-ids SecurityControlId=CloudTrail.1,StandardsArn=arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0
{
    "StandardsControlAssociationDetails": [
        {
            "StandardsArn": "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0",
            "SecurityControlId": "CloudTrail.1",
            "SecurityControlArn": "arn:aws:securityhub:us-east-1:122796619775:security-control/CloudTrail.1",
            "AssociationStatus": "ENABLED",
            "RelatedRequirements": [
                "CIS AWS Foundations 2.1"
            ],
            "UpdatedAt": "2022-10-27T02:05:13.151Z",
            "StandardsControlTitle": "Ensure CloudTrail is enabled in all regions",
            "StandardsControlDescription": "AWS CloudTrail is a web service that records AWS API calls for your account and delivers log files to you. The recorded information includes the identity of the API caller, the time of the API call, the source IP address of the API caller, the request parameters, and the response elements returned by the AWS service.",
            "StandardsControlArns": [
                "arn:aws:securityhub:us-east-1:122796619775:control/cis-aws-foundations-benchmark/v/1.2.0/2.1"
            ]
        }
    ]
}

$ aws securityhub batch-get-standards-control-associations --standards-control-association-ids SecurityControlId=CloudTrail.1,StandardsArn=arn:aws:securityhub:::standards/nist-800-53/v/5.0.0
{
    "StandardsControlAssociationDetails": [],
    "UnprocessedAssociations": [
        {
            "StandardsControlAssociationId": {
                "SecurityControlId": "CloudTrail.1",
                "StandardsArn": "arn:aws:securityhub:::standards/nist-800-53/v/5.0.0"
            },
            "ErrorCode": "RESOURCE_NOT_FOUND",
            "ErrorReason": "Standards Control Link not found. Make sure the Standard has been enabled and supports the given control."
        }
    ]
}
```

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Continue research to see if we can slim down the list of controls applicable only to the moderate baseline."

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc spreadsheet of the NIST SP 800 rev 5 Moderate baseline https://docs.google.com/spreadsheets/d/1LgE_9v_DoEyDpsBkizMy_zsjErV3oRQ3/edit?gid=1005799400#gid=1005799400

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "We'll use tempdev to enable the NIST benchmark in an attempt to retrieve the control association."

**Comment by dsotirho-ucsc** [comment]
Spreadsheet updated with a count of the related moderate NIST control IDs per AWS control
https://docs.google.com/spreadsheets/d/1Pe0rtQgFagHSO0bjD0DrZ_HqYqCm6usbSXOrXDL-0KE/edit?gid=0#gid=0

**Comment by dsotirho-ucsc** [comment]
Assignee to continue spike to determine if we can create custom benchmarks.

**Comment by dsotirho-ucsc** [comment]
> Assignee to continue spike to determine if we can create custom benchmarks.

There does not appear to be an ability to create a custom benchmark, however individual controls can be disabled from an enabled standard.

I've added commit https://github.com/DataBiosphere/azul/pull/6322/commits/b4516749a180aae21be05a04cf3d1c2f1b6b165b to PR #6322 to disable the non-moderate level controls from the `NIST Special Publication 800-53 Revision 5` standard.

Tested on `tempdev`:
![Screenshot 2024-08-09 at 2 21 49 PM](https://github.com/user-attachments/assets/1dfcf1d4-857c-44c4-8581-01a26cb18701)

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "The proposed solution of individually disabling non-moderate controls sounds good to me."

**Comment by hannes-ucsc** [comment]
For demo, show that the correct standard is enabled, and that it is the only standard. Show that there are no findings for non-moderate controls.
