### ISSUE TITLE
Prototype Parquet to BigQuery import

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6214]
- [ ] ~Find AnVIL snapshots in TDR `dev` where `.accessInformation.parquet` is not `null` in the TDR retrieveSnapshot response (none at the moment)~
- [x] Alternatively, but note MA concerns: Find such snapshots in TDR `prod` (there are a few)
- [x] Write a script that, given the ID of a snapshot, …
    - [x] … exports the snapshot from the currently configured TDR instance
    - [ ] ~… confirms that there is one parquet file per table~
    - [x] … downloads each table's parquet files from GCS …
         - [ ] ~… by concatenating the `url` and `sasToken` fields from `.accessInformation.parquet` and requesting the resulting URL (the sasToken seems to expire quickly)~
- [x] Use the URLs returned by `exportSnapshot` to import the parquet files into BigQuery (use the 1000G snapshot in TDR dev for this)
- [ ] Add the views, as described in https://github.com/broadinstitute/jade-data-repo-client-example/blob/24c2ac0c7466ccc077b75af660b0872923574e13/src/main/python/AzureSnapshotExport.ipynb#L1643
- [x] Programmatically configure clustering and/or partitioning using any column that we use in WHERE clauses during indexing.
- [x] Verify that the column schema of the imported tables matches that of  the existing TDR snapshot
- [x] Compare indexing an imported BigQuery snapshot and the original TDR snapshot in personal deployment.
- [x] Investigate Hive partitioning
- [x] Investigate using a generated column for range partitioning
- [ ] ~Demote assignee back to Editor in `platform-anvil-dev`~ Moved to #6355

To be continued.

**Comment by dsotirho-ucsc** [comment]
Assignee to provide description and consider next steps.

**Comment by achave11-ucsc** [comment]
Initial estimate only includes the items from the description as of today.

![Screenshot 2024-06-11 at 11 51 07 AM](https://github.com/DataBiosphere/azul/assets/19215510/30de77cb-9baf-4245-a865-193118f6d1b4)

**Comment by nadove-ucsc** [comment]
I could not find any snapshots with parquet access information in `dev`, and found these ones in `prod`:
```
31042075-1a32-4190-8394-c1577576eb19
85389914-21eb-48c2-9b06-3ff7345d6334
cb177b85-a1ac-493c-a020-2f3b361d1232
d37623f4-4208-4260-90f6-5ddfc5db21f2
d7c1b3c2-92bc-4f29-ab54-01a96777abba
```

**Comment by nadove-ucsc** [comment]
Using the `exportSnapshot` endpoint, I was able to download non-empty parquet files for snapshot `d7c1b3c2-92bc-4f29-ab54-01a96777abba`.

**Comment by nadove-ucsc** [comment]
The 1000G snapshot provides two parquet files for the `anvil_file` table. I suspect this is due to the relatively large size of this table.

**Comment by nadove-ucsc** [comment]
Partitioning is only supported on columns that are integers or date/time values (see [Types of partitioning](https://cloud.google.com/bigquery/docs/partitioned-tables#types_of_partitioning)). There are no such viable candidates among the TDR tables, so I think partitioning is out.

**Comment by nadove-ucsc** [comment]
Clustering does work with strings (see [Cluster column types](https://cloud.google.com/bigquery/docs/clustered-tables#cluster_column_types)), which covers `datarepo_row_id`, all primary keys, and some foreign keys (many foreign keys are arrays which are not supported). These are the columns we most frequently use for filtering. The only other column I can find that appears in a WHERE clause in the AnVIL plugin is `anvil_file.is_supplementary`, which is a bool which is also supported.

EDIT:

The only foreign keys that aren't arrays are `anvil_diagnosis.donor_id` and `anvil_donor.part_of_dataset_id`.

**Comment by nadove-ucsc** [comment]
From https://cloud.google.com/bigquery/docs/clustered-tables:

> Unpartitioned tables larger than 64 MB are likely to benefit from clustering. Similarly, table partitions larger than 64 MB are also likely to benefit from clustering. Clustering smaller tables or partitions is possible, but the performance improvement is usually negligible.

After importing the 1000 Genomes snapshot using the parquet files, the largest table (`anvil_file`) is only about 8 MB:

![Screenshot from 2024-06-16 01-09-49](https://github.com/DataBiosphere/azul/assets/48401926/19b4d4bc-af5c-4f8f-acf2-12c87a233e60)

However, the largest snapshot we currently index (in `anvilprod`) is much larger than 64 MB:

![image](https://github.com/DataBiosphere/azul/assets/48401926/5643b6d5-1ba7-4e6d-ad7e-38e470e40602)

I can't find any indication that clustering ever _hurts_ performance, so I think it makes sense to proceed with clustering.

**Comment by nadove-ucsc** [comment]
> Verify that the column schema of the imported tables matches that of the existing TDR snapshot

The set of imported tables is intentionally a subset of those in the reference snapshot. All imported tables have the name column names and column datatypes as those in the reference snapshot, however all non-array columns in the imported tables are marked as nullable, even the primary keys.

**Comment by nadove-ucsc** [comment]
> Investigate Hive partitioning

AFAICT the only references to Hive partitioning in [the BigQuery docs ](https://cloud.google.com/bigquery/docs/hive-partitioned-queries) are in reference to external data sources. We aren't using an external data source, so the section doesn't apply. The docs warn that querying external sources is usually slower than querying native BigQuery tables, so I don't think we want to look into this further,

**Comment by nadove-ucsc** [comment]
I indexed both TDR's 1000G snapshot and our imported version. Each was indexed as the only source in its catalog, several hours apart in the same deployment. The hits from all `/index/*` endpoints were identical for both catalogs, with the expected exceptions 1. the google cloud project in `hits[].sources[].source_spec` and 2. the catalog name in `hits[].files[].url`.

UPDATE: Repeated this experiment, indexing the entire snapshot this time, without the common prefix. Results unchanged.

**Comment by nadove-ucsc** [comment]
Reindex performance stats:

| Snapshot | Start time | End time | Duration | Average subgraph download time |
| ----- | ----- | ----- | ----- | ----- |
| Reference | 2024-06-20 17:33:38.583 | 2024-06-20 20:03:31.381 | 2:29:52 | 11.7435 |
| Import | 2024-06-20 09:16:21.115 | 2024-06-20 11:34:31.858 | 2:18:10 | 9.031s |
| Improvement | | | 7.8% | 23.1% |

**Comment by nadove-ucsc** [comment]
> Investigate using a generated column for range partitioning

AFAICT partitioning can only be applied to a table when that table is first created. Here's how I think we could achieve partitioning:

 - Import the un-partitioned table
 - Add a new generated column
 - Create a copy of the table, using the new column for partitioning
 - Drop the old table

In order to avoid the temporary table, we'd need to configure the load job to create a new column during the import. I can't find anything in the API to suggest that this is possible.

An alternative (but probably much more difficult) strategy would be to download the parquet files, edit them locally to include the new column, re-upload to GCS, and then import the new files.

**Comment by nadove-ucsc** [comment]
Investigate actual queries from the reindex, considering that there might be different types of subgraphs that use different query profiles. The goal is to ensure that all queries benefit from the clustering, or to find queries that could benefit more from a different type of clustering.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Prototyping is finished, transitioning to implementation (#6355)"
