### ISSUE TITLE
Modify /health response to return 503 response when service is Down

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#624]
Current `/health` request returns with a 200 status response in scenarios when is both 'UP' and 'DOWN' the response should return a '503' status code when is  'DOWN'

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-395)
┆Project Name: azul
┆Issue Number: AZUL-395

**Comment by hannes-ucsc** [comment]
Demoed on 1/18/19
