### ISSUE TITLE
WAF IPSet for blocked IP addresses has unqualified name

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6244]

**Comment by hannes-ucsc** [comment]
Since AWS WAF IPSets can't be renamed without replacing them and can't be replaced without removing all references to them, a first partial PR will add a new IP set under the correct name and a later PR will remove the old IPSet once all deployments were updated to reference the new IPSet.

**Comment by achave11-ucsc** [comment]
Assignee to prepare PR that removes the old IP set.

**Comment by hannes-ucsc** [comment]
For demo, show absence of the old IPSet in all four AWS accounts. Show that the new IPSet has a qualified name.
