### ISSUE TITLE
Scheduled GitLab jobs aren't running in AnVIL prod instance

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6257]
https://gitlab.explore.anvilproject.org/ucsc/azul/-/pipelines
![AnVIL prod GL](https://github.com/DataBiosphere/azul-private/assets/19215510/5de90801-5ed9-489d-8b7a-b4495edd41fa)

**Comment by achave11-ucsc** [comment]
This may be related to the changes that introduced the `anvilprod` branch, schedule jobs usually ran from `develop` perhaps a conditional or a reference enforcing this didn't get updated.

**Comment by hannes-ucsc** [comment]
Good call. I just edited the schedule job to run on the `anvilprod` instead of the `develop` branch. Let's see if that fixes it.

**Comment by achave11-ucsc** [comment]
That did it, scheduled jobs have re-started with `sell_unused_slots` https://gitlab.explore.anvilproject.org/ucsc/azul/-/pipelines/10918.
