### ISSUE TITLE
Create example BdBag for data browser handoff of primary data to Terra

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#626]
From Vicky Horst on 12/20/18:

During this conversation, we made 2 assumptions:
Terra can resolve `https://` URLs, just like it can resolve `gs://` and `dos://` URLs.
Terra prefers BdBag for the handoff over tsv.
Brad, if the 2 assumptions are wrong, please let us know.

As we discussed, there are 2 cases of the handoff based on file types, assuming the 2 assumptions above are correct:
if the handoff is for primary data (BAM, FASTQ, and more to come), then the preferred URL is a DOS string, instead of a `gs://` path, because the DOS string will never change. In this case, the handoff happens from the data store. We envisioned that a row in BdBag would have columns including donor, specimen, cell suspension, DOS string, and other file related columns. Thus, if there are 5 files being handed over from HCA, then there are 5 rows.

As a next step, we agreed that the HCA team will provide sample tables for the 2 types of handoffs listed above, and we as a group will discuss the examples on 1/7 as well as next steps (Trevor agreed to set up the call).

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-396)
┆Project Name: azul
┆Issue Number: AZUL-396
┆Epic: Feature Export from Boardwalk to HCA

**Comment by hannes-ucsc** [comment]
Just to clarify, I think the first step should be to create a BDBag wrapping a manifest for handing off **sequence files** to Single Cell Portal/Terra, not expression matrices. There will be the need to create an example BDBag for matrices as well but that can happen later.

@theathorn we can reduce the scope of this ticket or create two subtickets blocking this one. Your call.

**Comment by mjkrause** [comment]
I've create a BDBag with the two files (containing mocked data) needed for FireCloud upload in its data directory. [Click](https://drive.google.com/drive/folders/14nwdb6C9uVAq6DBkBGo5RFgE2cf9FTZf?usp=sharing) to view the BDBag, it is named `hca_manifest`. 

That folder also had a Jupyter Notebook that contains the code used to create the bag. Also included a requirements file if you want to create the bag in your own virtual env, using the two files `participant.tsv` and `sample.tsv`. 

I've [uploaded the data](https://portal.firecloud.org/#workspaces/firecloud-cgl/azul_626), and gave @hannes-ucsc read access.

**Comment by mjkrause** [comment]
Opened a PR at https://github.com/DataBiosphere/azul/pull/635.

**Comment by hannes-ucsc** [comment]
Example BDBag was uploaded to S3 and demod to Terra group.

See https://github.com/DataBiosphere/azul/pull/635#issuecomment-462993829
