### ISSUE TITLE
Export cart to DSS collection API

### ISSUE THREAD

**Issue by Ben-Wu** [DataBiosphere/azul#627]
Cart items should be sent to the `PUT /collections` endpoint at https://dss.data.humancellatlas.org/

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-397)
┆Project Name: azul
┆Issue Number: AZUL-397
┆Epic: Interactive building of collections

**Comment by shiroyuki** [comment]
Note that it is difficult to test as we have more than 80k bundles registered in the database (ElasticSearch) but there are just 15 bundles in DSS's S3 bucket (`org-humancellatlas-dss-dev`). Missing information would make development very difficult, especially for very large cart.
