### ISSUE TITLE
Parameterize reindex job in GitLab with sources to reindex

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6276]
Continuation of #5336. Not only do we frequently need to reindex a specific catalog, we also need to reindex a specific source of a specific catalog. The variable name should be `azul_current_sources` and the value should be a space-separated list of source globs. I think it would be useful to allow for either or both variables to be set. If only `azul_current_sources` is set, then the matching source(s) would be reindexed in all catalogs.

The handling of multiple source patterns separated by space should be tested carefully.

**Comment by hannes-ucsc** [comment]
For demo, reindex two sources on GitLab, by setting the new environment variable to two short globs, each glob matching exactly one source.

**Comment by nadove-ucsc** [comment]
Demo blocked by https://github.com/DataBiosphere/azul/issues/6342
