### ISSUE TITLE
Spurious update to opensearch_cluster_settings yields 401

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6278]
https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/92841

```
aws_lambda_function.service_manifest: Modifications complete after 5s [id=azul-service-dev-manifest]
╷
│ Error: elastic: Error 401 (Unauthorized)
│ 
│   with opensearch_cluster_settings.index,
│   on elasticsearch.tf.json line 153, in resource[5].opensearch_cluster_settings[0].index:
│  153:                     }
│ 
╵
make[1]: *** [Makefile:64: auto_apply] Error 1
make[1]: Leaving directory '/builds/ucsc/azul/terraform'
make: *** [Makefile:106: auto_terraform] Error 2
Cleaning up project directory and file based variables 00:01
ERROR: Job failed: exit code 1
```
Re-running the job did not resolve the problem,
 https://gitlab.dev.singlecell.gi.ucsc.edu/ucsc/azul/-/jobs/92856

**Comment by achave11-ucsc** [comment]
This may have started after applying the OpenSearch software update for #6272.

**Comment by hannes-ucsc** [comment]
Can you please try 

```
_select dev
make -C lambdas
cd terraform
make validate
terraform state rm opensearch_cluster_settings.index
```

on `develop` as a workaround?

**Comment by hannes-ucsc** [comment]
… and then retrying the job.

**Comment by achave11-ucsc** [comment]
This workaround worked. ✅

**Comment by achave11-ucsc** [comment]
This is a regression from PR #6135 for issue #5675.

@hannes-ucsc [reported](https://github.com/opensearch-project/terraform-provider-opensearch/issues/60#issuecomment-2041280397) this upstream.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Assignee to replace the buggy provider with a local-exec provisioner script that posts directly to the ElasticSearch cluster settings API."
