### ISSUE TITLE
Update GitLab images to 17.x

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6289]
… which my require additional steps and configuration changes in order to prevent failures. See: https://docs.gitlab.com/ee/update/versions/gitlab_17_changes.html#1700

- [x] Switch to the new runner registration process
   - [x] dev
   - [x] anvildev
   - [x] prod
   - [x] anvilprod
- [x] Update the image version

**Comment by achave11-ucsc** [comment]
Assignee to switch to the new runner registration process.

**Comment by dsotirho-ucsc** [comment]
Assignee to amend upgrade PR with update to GitLab 17.x, including runner.
