### ISSUE TITLE
Create example BdBag for data browser handoff of matrix data to Terra

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#630]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-400)
┆Project Name: azul
┆Issue Number: AZUL-400
┆Epic: Feature Export from Boardwalk to HCA

**Comment by theathorn** [comment]
If the handoff is for analysis data (matrix files), then the URL is an https:// path, and it shouldn't change. In this case, the handoff happens from the matrix service. We envisioned that a row in Terra would include just 2 columns: URL to HCA data browser that's used to generate the matrix, and an https:// path that points to the matrix file. This will only handoff 1 matrix at a time, and the matrix is aggregated, and there is always 1 row in the table. In the future, we can look into handing over multiple matrices at a time. We also learned that a retry mechanism to retrieve the https:// URL is needed, and we will need to discuss further technical details.

**Comment by mjkrause** [comment]
(copied from #626)
I've create a BDBag with the two files (containing mocked data) needed for FireCloud upload in its data directory. [Click](https://drive.google.com/drive/folders/14nwdb6C9uVAq6DBkBGo5RFgE2cf9FTZf?usp=sharing) to view the BDBag, it is named hca_manifest.

That folder also had a Jupyter Notebook that contains the code used to create the bag. Also included a requirements file if you want to create the bag in your own virtual env, using the two files participant.tsv and sample.tsv.

I've [uploaded the data](https://portal.firecloud.org/#workspaces/firecloud-cgl/azul_626), and gave @hannes-ucsc read access.

**Comment by achave11** [comment]
Samples BDbag was demoed to The Broad.
