### ISSUE TITLE
CloudWatch metric graph shows inconsistent counts

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6307]
This is disconcerting because the counts for these events are what drive the deployment monitoring, specifically the alarm configurations. The following screenshot illustrates these discrepancies for the `azul-api_unauthorized-prod.alarm` metric.

![CloudWatch](https://github.com/DataBiosphere/azul/assets/19215510/5740e9aa-d4b2-47bb-94f7-8ba312bea2c8)

The three Logs Insights queries (bottom half of the screenshot) are using the same filter for matching AccessDenied events in `azul-trail-prod`, the same time range but differ in the period used by bin. The query encapsulated in the orange box (five-minute bin) contains the matching Logs Insights graph, which was approximately aligned with the metric graph (top half of screenshot). The queries in the blue box (one-day bin), and green box (one-minute bin) generate the same Logs Insights graph, which is why it was omitted for them. The green box additionally includes a zoomed-in metric graph displaying events at a per minute resolution.

It's worth pointing out that the counts seem to make sense when the same period is used for both the metric in the graph and when binning the Logs Insights results. Additionally, when there are consecutive datapoints in the binned (observed) period, the graph is continuous (not broken up into isolated datapoints). This last observation is highlighted by the two orange (5 & 12) and green (1 & 1) datapoints, and their corresponding color-matched boxes encapsulating the associated Logs Insights events.

**Comment by dsotirho-ucsc** [comment]
Assignee to update title.

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
We don't have a reliable reproduction.
