### ISSUE TITLE
GitLab `prod` at disk used percent threshold

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6316]
![Screenshot 2024-06-05 at 12 56 02 PM](https://github.com/DataBiosphere/azul/assets/46407464/4953ce06-c84d-4eec-b1af-e2e83584d398)

**Comment by dsotirho-ucsc** [comment]
Assignee to enable container cleanup on GitLab `prod`

**Comment by hannes-ucsc** [comment]
Kicked off the container registry cleanup in all four GLs.

**Comment by hannes-ucsc** [comment]
While the clean-up did complete, the amount of reclaimed disk space was not sufficient to address the alarm. Assignee to grow the `azul-gitlab` volume to 150 GB in `prod`.

**Comment by dsotirho-ucsc** [comment]
> Assignee to grow the azul-gitlab volume to 150 GB in prod.

This has been done.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Checked during stand-up that the alarm is fixed."
