### ISSUE TITLE
lm7 snapshot uses sequence_file for protocols

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6318]
Snapshot:
```
tdr:datarepo-fc122208:snapshot/lungmap_prod_1977dc4784144263a8706b0f207d8ab3__20240206_20240524_lm7:/0
```

Process link:

```json
{
    "link_type": "process_link",
    "process_id": "66ffb4ac-9542-4d7b-9cfb-f72d375656d0",
    "process_type": "process",
    "inputs": [
        {
            "input_type": "sequence_file",
            "input_id": "14186f8b-d3f8-4c4c-9403-6c9dc1f78c64"
        },
        …
        {
            "input_type": "sequence_file",
            "input_id": "e231f456-a113-4c27-99a4-ca8690769c3c"
        }
    ],
    "outputs": [
        {
            "output_type": "analysis_file",
            "output_id": "9f1bb557-c9e9-4ba9-8a27-3ec79ac55ca5"
        }
    ],
    "protocols": [
        {
            "protocol_type": "sequence_file",
            "protocol_id": "01d25c36-7aa3-410e-b3f2-cf88a94d9106"
        },
        …
        {
            "protocol_type": "sequence_file",
            "protocol_id": "ee51f80d-6d97-4c91-84a4-0222b991d27a"
        }
    ]
},
```

Edit (@hannes-ucsc): Only `…_protocol` entities should be listed under `protocols` in an entry of `links`. Sequence files are files, not protocols.

**Comment by dsotirho-ucsc** [comment]
[DCP/2 Datasets and snapshots](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?usp=sharing) spreadsheet updated for bad snapshot.

**Comment by hannes-ucsc** [comment]
A fix (removal of the defective snapshot) was committed directly to `prod` and pushed to `gitlab.anvilprod`. It needs to be backported to `develop`.

**Comment by JoshuaFortriede** [comment]
@hannes-ucsc, I have found and fixed the error in that dataset. @ebardes will be re-uploading the dataset. Can this be re-submitted for this round, or do we need to submit it for the next round?

Tagging: @nsalomonis

**Comment by hannes-ucsc** [comment]
If we get the snapshot on Monday, we can include it in next week's promotion. Please be sure to notify @bvizzier-ucsc on Slack or create a new issue in this repository to ensure that my team is immediately made aware of the availability of the new snapshot. Note that only @ncalvanese1 can create the snapshot so they will need to be involved. I'm closing this ticket because the removal of the defective snapshot resolves the issue for us.
