### ISSUE TITLE
Reindex lm7 to include the dataset with the protocol_type error

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6324]
The LungMAP team has addressed the issue with the dataset from lm7.  (Ref:  https://github.com/DataBiosphere/azul/issues/6318)

[Slack notification of correction.](https://lungmapdcc.slack.com/archives/C05C5SBPMCP/p1717789634227779)

Please reindex, including this dataset that had the protocol_type specification error.  See '[TDR Datasets and snapshots](https://docs.google.com/spreadsheets/d/1yYiB3TrX0wvLCHvtWY1GTZZcAf5MmMREgn52OKCHsqs/edit?usp=sharing)'.

**Comment by hannes-ucsc** [comment]
The spreadsheet does not list any new snapshots. There is no point in reindexing now.

**Comment by bvizzier-ucsc** [comment]
This morning, [Nate C confirmed a new snapshot has been created](https://lungmapdcc.slack.com/archives/C05C5SBPMCP/p1717982354830289?thread_ts=1717789634.227779&cid=C05C5SBPMCP).
