### ISSUE TITLE
Unable to override `azul_current_sources` on GitLab

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6342]
The environment variable `azul_current_sources` is set to the string "*" in the root `environment.py`. Because the default value is not `None`, it overrides any value entered for the variable via the GitLab UI for running manual jobs.

Change the default value in `environment.py` to `None` and let the default value of "*" be assigned only when the variable is missing from the environment.

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "This is related to #6320, and should be solve in the same PR. Assignee to specify solution."

**Comment by hannes-ucsc** [comment]
The second paragraph of the description already mentions a solution. I think we should go with that.

**Comment by hannes-ucsc** [comment]
For demo, follow demo instructions from https://github.com/DataBiosphere/azul/issues/6276 and label both issues as `demoed`, and remove the `demo blocked` label from that issue.
