### ISSUE TITLE
Deploy browser site for HCA `dev` as TF component of Azul

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6343]
… so that we can take over the deployment and disable CC's administrator-level access to our `platform-hca-dev`  AWS account and Google Cloud project.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Assignee to author PR, once blockers land.

**Comment by achave11-ucsc** [comment]
Assignee to check for leftovers (access and cloud resources).

**Comment by hannes-ucsc** [comment]
Leftovers deleted. Remaining work in https://github.com/DataBiosphere/azul/pull/6643.
