### ISSUE TITLE
Deploy browser site for HCA `prod` as TF component of Azul

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6344]

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Assignee to author PR.

**Comment by achave11-ucsc** [comment]
Assignee to check for leftovers (access and cloud resources).

**Comment by hannes-ucsc** [comment]
Leftovers deleted. Remaining work in https://github.com/DataBiosphere/azul/pull/6643.
