### ISSUE TITLE
Deploy browser site for LungMAP `dev` as a TF component of Azul

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6346]
There is a catalog in `dev` and a hosted zone lungmap.dev.singlecell.gi.ucsc.edu but the browser site is not functional.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
Assignee to author PR, once blockers land.

**Comment by achave11-ucsc** [comment]
Assignee to check for leftovers (access and cloud resources).

**Comment by hannes-ucsc** [comment]
Leftovers deleted. Remaining work in https://github.com/DataBiosphere/azul/pull/6643.
