### ISSUE TITLE
Inspector coverage inconsistent with actual configuration

### ISSUE THREAD

**Issue by achave11-ucsc** [DataBiosphere/azul#6354]
In `anvilprod`, the Inspector console indicates that the container images in ECR are not configured to be actively/continuously monitored and are all listed in the 'Not scanning' tab. Since they are supposedly scanned manually. However, this is contradictory with the information in the scanning settings for the images within the ECR console.

In the following screenshot from the Inspector console, it appears as if non of the images in ECR are configured for continuous scans.
![CleanShot 2024-06-20 at 18 24 05@2x](https://github.com/DataBiosphere/azul/assets/19215510/b407b970-2ad2-4e24-84fd-f3d44f817aa5)

But in ECR, the [scan configuration](https://docs.aws.amazon.com/inspector/latest/user/scanning-ecr.html#ecr-scan-behavior) is contradictory to the one shown in the Inspector console.
![Screenshot 2024-06-20 at 7 28 35 PM](https://github.com/DataBiosphere/azul/assets/19215510/a563cca6-28c3-4b4c-9519-36eb68472ea3)

Furthermore, Inspector's last scanned date for the container images highlighted in the following screenshot …
![Screenshot 2024-06-20 at 7 38 36 PM](https://github.com/DataBiosphere/azul/assets/19215510/7bffa331-beb5-40f1-a718-dcfa1338f973)
is not congruent with the scan details of the image as seen from the ECR console.
![Screenshot 2024-06-20 at 7 35 33 PM](https://github.com/DataBiosphere/azul/assets/19215510/6882a359-585f-481b-870f-d29c807a06df)
![Screenshot 2024-06-20 at 7 39 18 PM](https://github.com/DataBiosphere/azul/assets/19215510/1851b94e-8353-4b1a-b36a-91a17f93fb08)

The expectation for the Inspector console in the affected deployments is for it to resemble the one of the `tempdev`. With most container images configured with the 'Actively monitoring' status.
![CleanShot 2024-06-20 at 18 27 18@2x](https://github.com/DataBiosphere/azul/assets/19215510/46fd428e-b367-4e74-920c-6c9b22a8abf7)

**Comment by achave11-ucsc** [comment]
Assignee to provide screenshots with reproduction.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Assignee to open support ticket with AWS. Focus on the `docker` Docker image."

**Comment by dsotirho-ucsc** [comment]
Opened AWS Support case [171927048400112](https://support.console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=171927048400112&language=en) on anvilprod.

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We discovered during the upgrade PR that newly pushed images are being scanned and show up as covered in Inspector. This leads me to believe that the problem will slowly fix itself once we push updates to all images. Assignee to close AWS Support ticket with the following statement: 'AWS Support confuses custom image tags with base image layers. While it is true that recently the OS in the base image of the image in question had not been supported, support for Alpine 3.20 was recently added. Furthermore, our evidence shows that the error message indicates that the scans are manual, not that the image is not supported (the status message for that would contain the word 'unsupported').' "

**Comment by dsotirho-ucsc** [comment]
Assignee to delete any images still affected and to re-upload them by deploying the shared component, as part of the merging of the upgrade and promotion PRs.

**Comment by dsotirho-ucsc** [comment]
> Assignee to delete any images still affected and to re-upload them by deploying the shared component, as part of the merging of the upgrade and promotion PRs.

Added CL items to current upgrade PR #6361

**Comment by dsotirho-ucsc** [comment]
AWS Support ticket has been closed and feedback about the ticket was submitted

**Comment by hannes-ucsc** [comment]
For demo, attempt to reproduce.
