### ISSUE TITLE
Scheduled CIS Linux scans on AWS Inspector

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6370]
https://docs.aws.amazon.com/inspector/latest/user/scanning-cis.html

- [x] Redo manual permission change on Monday
- [ ] Add IAM infrastructure code to attach CIS policy to GitLab role
- [ ] Add Inspector2 infrastructure code to create scheduled scan (not directly supported as of 7/3/2024, but we can use CloudFormation stack instead)

**Comment by dsotirho-ucsc** [comment]
Assignee to file PR for 2nd checklist item.

**Comment by hannes-ucsc** [comment]
We can use a CloudFormation stack to achieve the 3rd CL item.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspectorv2-cisscanconfiguration.html

The scan should occur weekly on Friday at 7:30pm PST/PDT. It should be a level 2 scan.

Assignee to file PR for all remaining CL items.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by dsotirho-ucsc** [comment]
Closing as a dup of #6428
