### ISSUE TITLE
Operators have SSH access to anvilprod

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6371]

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "Operators should only have SSH access to GitLab instances in non-stable deployments. The solution should make use of the `config.deployment.is_stable` property."

**Comment by hannes-ucsc** [comment]
For demo, show contents of `~/.ssh/authorized_keys` on all GL instances. Needs assistance by system administrator.
