### ISSUE TITLE
Alias `terra.pfb` to `verbatim.pfb`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6378]
Passing `format=terra.pfb` should be equivalent to passing `format=verbatim.pfb`.

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
This is now obsolete.

https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1723662507964749?thread_ts=1723661638.924999&cid=C705Y6G9Z
