### ISSUE TITLE
Update to Docker 27.x

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6379]
https://hub.docker.com/_/docker/tags?page=&page_size=&ordering=&name=27.

**Comment by dsotirho-ucsc** [comment]
Assignee to study the release notes and decide whether we should skip the previous major version update.

**Comment by dsotirho-ucsc** [comment]
We are safe to update to Docker 27.x (currently we are at 25.0.5)
- Features removed in v26 don't apply to us
- There were no features removed in v27

https://docs.docker.com/engine/deprecated/
https://docs.docker.com/engine/release-notes/26.0/
https://docs.docker.com/engine/release-notes/27.0/

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Ok to include in Upgrade PR for #6389."
