### ISSUE TITLE
Viewer role not used for `anvilprod`

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6396]
The `platform-anvil-prod` account started off as a non-stable deployment. We need a `viewer` role there (and a corresponding group in the gateway account) and move all team members from `developer` to that role.

**Comment by achave11-ucsc** [comment]
Assignee to provide description and next steps.

**Comment by hannes-ucsc** [comment]
I think we should solve this in a 20min meeting with Erich. Assignee to coordinate that.

**Comment by achave11-ucsc** [comment]
Meeting was held. Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1725396022536639

**Comment by hannes-ucsc** [comment]
I've modified the `viewer` role in `anvilprod` to mirror `prod`. Erich originally used the AWS-managed `ViewOnlyAccess` policy instead of `ReadOnlyAccess` and, for the custom permissions, he used a inline policy instead of a customer-managed one. I fixed both so that `anvilprod` is identical to `prod` in that aspect.
