### ISSUE TITLE
Set up Production Deployment

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#64]
We need to set up Production Deployment for Orange (index, web service, UI)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-39)
┆Project Name: azul
┆Issue Number: AZUL-39
┆Epic: Setup HCA environments

**Comment by hannes-ucsc** [comment]
https://service.explore.data.humancellatlas.org/

Note the absence of /api in the path.
