### ISSUE TITLE
Clean-up and generalize TDR source specs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6426]
Current spec format:

`tdr:datarepo-dev-6fdac3db:snapshot/hca_dev_e8808cc84ca0409680f2bba73600cba6__20210902_20210907:/1`

1) Rename `TDRSourceSpec.project` to `TDRSourceSpec.subdomain`.

2) Remove `is_snapshot` field (`dataset/` or `snapshot/`) and remove support for `/dataset`:

   `tdr:datarepo-dev-6fdac3db:hca_dev_e8808cc84ca0409680f2bba73600cba6__20210902_20210907:/1`

3) Add `type` field (enum of `bigquery` or `parquet`, but reject `parquet` for now):

   `tdr:bigquery:datarepo-dev-6fdac3db:hca_dev_e8808cc84ca0409680f2bba73600cba6__20210902_20210907:/1`

4) Add `domain` field (enum of `gcp` or `azure`, but reject `azure` for now) and reject the combination of type `bigquery` and provider `azure`:

   `tdr:bigquery:gcp:datarepo-dev-6fdac3db:hca_dev_e8808cc84ca0409680f2bba73600cba6__20210902_20210907:/1`
   
The order of the attributes of `TDRSourceSpec` should be: `prefix` (inherited), `type`, `domain`, `subdomain` and `name`.

**Comment by nadove-ucsc** [comment]
For demo, show new source specs in the service response. Show that the `update_subgraph_counts.py` script still works. Try filtering an index endpoint using a source spec.
