### ISSUE TITLE
Verbatim JSONL manifest issues

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6453]
1. `contents` property should be renamed to `value`
2. Value of the `type` property should be more specific for HCA (e.g. "sequence_file" instead of "file")

**Comment by nadove-ucsc** [comment]
For demo, create a small JSONL manifest on a main HCA deployment. Show that the `content` property has been renamed to `value`. Show that the `type` property now shows more specific entity types (e.g. `sequence_file` instead of `file`).

**Comment by hannes-ucsc** [comment]
~For demo, attempt to reproduce.~ See above.
