### ISSUE TITLE
AnVIL Data Explorer has missing diagnosis for some datasets

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6466]
([Slack report](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1722613743879139))

> Kate Balaconis   08:49
> @Ben Vizzier: could you help us look into what may be happening with how anvil-diagnosis_disease values may be displayed in the explorer. Per our table stats file that we've been reviewing, 126 of the 257 released datasets have the anvil_diagnosis.disease field populated with one or more unique values but these aren't all showing up in the Explorer. Thanks!

I'm filing a ticket under the assumption that it will take some time to investigate.

**Comment by dsotirho-ucsc** [comment]
Spike to diagnose

@hannes-ucsc: "I suspect these diagnoses aren't linked to any files."

**Comment by NoopDog** [comment]
It looks like the front end is taking the diagnosis information from the wrong Azul term facet. The correct term looks to be `diagnoses.disease`. The front end is currently using `diagnoses.phenotype`. I have created a ticket to update the mapping in the front end.  https://github.com/DataBiosphere/data-browser/issues/4095

**Comment by nadove-ucsc** [comment]
There are 97 distinct values in `anvil_diagnosis.disease` column in the example snapshot provided to us by the Broad (https://data.terra.bio/snapshots/2fdba9a4-6593-439a-a7fc-c3a5825c26cd/data). 95 of those values are present in the `diagnoses.disease` field in [the Azul response](https://service.explore.anvilproject.org/index/datasets/90b1d9c3-d365-4461-9e61-40d969fde281). The two missing values are from diagnoses whose donors are not linked to any biosample in the snapshot.

**Comment by dsotirho-ucsc** [comment]
Assignee to contact Broad about the two missing disease values.

**Comment by nadove-ucsc** [comment]
Slack thread [updated ](https://ucsc-gi.slack.com/archives/C03TPJS54DC/p1722977218802829?thread_ts=1722613743.879139&cid=C03TPJS54DC) with latest findings.

**Comment by achave11-ucsc** [comment]
Assignee to consider next steps.

**Comment by hannes-ucsc** [comment]
The issue was in the Data Browser, not Azul.
