### ISSUE TITLE
Swagger UI authorization fails

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6469]
Attempting to authorize through the Swagger UI fails to complete and result in a blank page.
The browser's console displays the following message for the blank page:

```
Refused to execute inline event handler because it violates the following Content Security Policy
directive: "script-src 'self' 'nonce-b97jDZjYMPfYZ-RJsPsqnMGU-rIFGOmhIBVe5VBw5oA'". Either
the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline
execution. Note that hashes do not apply to event handlers, style attributes and javascript:
navigations unless the 'unsafe-hashes' keyword is present.
```

![Screenshot 2024-08-05 at 9 06 38 AM](https://github.com/user-attachments/assets/410148fe-03c4-43c7-856f-a5b29b11b024)

![Screenshot 2024-08-05 at 9 03 49 AM](https://github.com/user-attachments/assets/1041db13-2e63-420e-a7b0-9d445a377763)

**Comment by achave11-ucsc** [comment]
Confirmed it works: https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1722985174150149?thread_ts=1722959534.525459&cid=C705Y6G9Z
