### ISSUE TITLE
`recan_bundle_tdr` script is stale

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6491]
We haven't used this script in a very long time. It's full of type warnings and I also suspect full of bugs due to problems I've found while working on https://github.com/DataBiosphere/azul/pull/6485. 

I also think that its design no longer makes sense given the current state of Azul. It's unlikely that we'll ever need to convert a canned DSS bundle to a TDR bundle again in the future. The ability to convert a canned TDR bundle into canned BigQuery tables may still be useful, however.

**Comment by achave11-ucsc** [comment]
Assignee to move script to the attic.

**Comment by achave11-ucsc** [comment]
Assignee to include change in the PR for #6299.

**Comment by nadove-ucsc** [comment]
This was fully resolved by partial PR https://github.com/DataBiosphere/azul/issues/6299
