### ISSUE TITLE
Overriding `azul_current_sources` removes all other sources from index

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6499]
... because `--delete` is passed to `reindex.py` before the source globs are parsed.

**Comment by nadove-ucsc** [comment]
When using explicit source globs, `--delete` could be interpreted as behaving  like `--deindex`.

**Comment by hannes-ucsc** [comment]
For demo, follow the operator manual instructions for reindexing a single source in a single catalog, using GitLab. Also reindex a single source that is present in more than one catalog, again on GitLab. Demonstrate that it is still possible, using the command line, to deindex in a single source from a given catalog, a single source from all catalogs and to delete an entire catalog. Show that, and which, invalid combinations of flags are rejected.
