### ISSUE TITLE
Draft metadata RFC for groups of related files

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#650]
Edit the draft in collaboration with @hewgreen and @diekhans.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-410)
┆Project Name: azul
┆Issue Number: AZUL-410

**Comment by hannes-ucsc** [comment]
@theathorn, I think this issue blocks the other one, not the other way around.

**Comment by hannes-ucsc** [comment]
Obsoleted by https://github.com/HumanCellAtlas/data-store/issues/1885.
