### ISSUE TITLE
Improve suppression of abstract test cases during test discovery

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#652]
`HealthCheckTestCase` is an abstract class, but it is the first such class that defines test.
The test loader attempts to run this test which fails with undefined abstract methods, we use a dirty work around (deleting the abstract class entry from importing modules and customizing the loader in the module defining the abstract class). That work around does not scale well and we should come up with a better solution.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-411)
┆Project Name: azul
┆Issue Number: AZUL-411

**Comment by jessebrennan** [comment]
One way to avoid this is to put the abstract class as a subclass of another class which effectively hides it from test discovery. This approach was [used in Toil](https://github.com/DataBiosphere/toil/blob/47befdcdbfaa9e43d396ee828cbff87050eb9dde/src/toil/test/batchSystems/batchSystemTest.py#L70). @hannes-ucsc if you approve this design I could add it in my latest PR about health checks.

**Comment by hannes-ucsc** [comment]
I came up with that technique for Toil. In that approach, the abstract class is not a subclass of another class but *nested* in another class. I think it is worse than what we currently use in Azul. It has the same limitations as the current approach in Azul but is more invasive by adding an extra indent and requires qualifying the nesting class (`hidden.`) when extending the abstract class.

**Comment by hannes-ucsc** [comment]
The current method is acceptable.
