### ISSUE TITLE
Inspector CIS scan uses level 1 instead of 2

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6532]
Since R5 of NIST 800.53, CM-6 requires level 2 compliance with the CIS Linux benchmark.

**Comment by dsotirho-ucsc** [comment]
Assignee to manually modify the schedule scan configuration. The permanent configuration will happen as part of #6428 .

**Comment by dsotirho-ucsc** [comment]
Manually updated scheduled scans to Level 2

![Screenshot 2024-09-03 at 9 18 49 AM](https://github.com/user-attachments/assets/922c608a-cf43-4bac-b52c-6f91b0f88e13)
![Screenshot 2024-09-03 at 9 19 10 AM](https://github.com/user-attachments/assets/e22ba496-46a7-4f44-befa-365d43755fbc)
![Screenshot 2024-09-03 at 9 19 25 AM](https://github.com/user-attachments/assets/06d85ea2-eaca-4db5-ad5d-205e8e0aa521)
![Screenshot 2024-09-03 at 9 19 44 AM](https://github.com/user-attachments/assets/a9f6b13f-70b2-4b54-b6f2-fda50fe94800)

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "For demo, show CIS level two results in one of the accounts."
