### ISSUE TITLE
FIXMEs reference closed external issues

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6596]
https://github.com/DataBiosphere/azul/blob/33796d4de83ff10fab3081ec28b3b0e2a2a2f18e/src/azul/plugins/metadata/hca/indexer/transform.py#L1392

[The linked issue](https://github.com/HumanCellAtlas/metadata-schema/issues/623) has been closed. This may manifest as a bug where zarr files are missing from replicas' lists of hub IDs and from the inner entity arrays of cell suspensions and samples.

**Comment by dsotirho-ucsc** [comment]
Spike to investigate.

**Comment by nadove-ucsc** [comment]
There is a related FIXME that references [_another_ closed ticket](https://github.com/HumanCellAtlas/metadata-schema/issues/579): https://github.com/DataBiosphere/azul/blob/319995f1e509e9bf47fec5f1368b51556be51eef/src/azul/plugins/metadata/hca/indexer/transform.py#L1440

**Comment by nadove-ucsc** [comment]
I couldn't find any evidence of what the symptoms might be because I couldn't find any zarray files in the index.

**Comment by nadove-ucsc** [comment]
@hannes-ucsc: "The solution is to remove the FIXMEs. While the blocking issue was resolved, there are no more zarrays in DCP2 and I don't want to touch the code that supports them."
