### ISSUE TITLE
Include orphans in manifest when filtering by only project/dataset

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6619]
This covers the "Service" section of https://github.com/DataBiosphere/azul/issues/6529#issue-2493231920

**Comment by hannes-ucsc** [comment]
For demo, filter by one of the MA datasets and the 1000G dataset. While signed in, perform a hand-over and show that a workspace table row exists for every row in every table in both snapshots, except `datarepo_row_ids`. Sign-out and repeat the hand-over with the same filters, and show that a workspace table row exists for every row in every table of the 1000G dataset.

**Comment by nadove-ucsc** [comment]
Demoed on `anvildev`. Demo again on `anvilprod` after promotion.
