### ISSUE TITLE
Report on the size of HCA DCP datasets

### ISSUE THREAD

**Issue by bvizzier-ucsc** [DataBiosphere/azul#6636]
I have been asked to obtain an estimate of the HCA DCP dataset sizes, ideally over time.

The primary request is for the size of each project/snapshot ID.

Ideally, it would be nice to have the sizes if they have changed over time.  However, I also understand that historical data may not be available.   Additionally, if historical data adds substantially to the effort required, focus on the primary request.  

Some background can be found in this [Slack thread](https://ucsc-gi.slack.com/archives/C705Y6G9Z/p1729032613792609).

**Comment by dsotirho-ucsc** [comment]
@bvizzier-ucsc  Total file sizes for all projects in the `dcp42` catalog has been compiled into this [google sheet](https://docs.google.com/spreadsheets/d/13ITBLp-Bo1uFXfdvWgieBRyR4DMpuP22s4yR_Sczo4Q/edit?gid=480245742#gid=480245742).

**Comment by bvizzier-ucsc** [comment]
This provided Benedict with what he needed.  Thanks.
