### ISSUE TITLE
Error indexing lm8 catalog

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6644]
Catalog: `lm8`
Snapshot `lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8`

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/lambda/azul-indexer-prod-contribute    
start-time: -345600s    
end-time: 0s    
query-string:
  ```
  fields @timestamp, @message
| filter @message like 'Worker failed' and @message like 'lm8'
| sort @timestamp asc
| limit 200
  ```
---
| @timestamp | @message |
| --- | --- |
| 2024-10-21 19:42:37.791 | [WARNING] 2024-10-21T19:42:37.789Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.indexer.index_controller Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': 'a9ea1d4e-4c8f-4c3e-8be8-e1206c56d749', 'bundle_fqid': {'uuid': '1d96f4d7-1013-3ef7-a491-aae9b145837f', 'version': '2023-01-25T18:30:09.464965Z', 'source': {'id': '769fb8a9-dea0-40f8-8c2b-2427cbe73533', 'spec': 'tdr:bigquery:gcp:datarepo-3377446f:lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8:/0'}}}, 'catalog': 'lm8'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 180, in contribute     contributions, replicas = self.transform(catalog, notification, delete)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_controller.py", line 232, in transform     bundle = service.fetch_bundle(catalog, bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_service.py", line 201, in fetch_bundle     return plugin.fetch_bundle(bundle_fqid)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr.py", line 208, in fetch_bundle     bundle = self._emulate_bundle(bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 319, in _emulate_bundle     entities, root_entities, links_jsons = self._stitch_bundles(bundle)                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 390, in _stitch_bundles     upstream = self._find_upstream_bundles(source, all_dangling_inputs)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 512, in _find_upstream_bundles     require(not missing,   File "/var/task/azul/__init__.py", line 1628, in require     reject(not condition, *args, exception=exception)   File "/var/task/azul/__init__.py", line 1647, in reject     raise exception(*args) azul.RequirementError: Dangling inputs not found in any bundle: {'6674bfef-cbb8-4575-b5d6-0e66bded1ccb', 'e0c02288-c7c8-42a4-9223-d53fb6141032', '09044642-a0ca-4bfd-9e87-40fd518ed863', '024b8d4d-c026-4d5b-8053-a5364b35d532', '8bfda167-1b1e-4f30-9872-a70bc0bf21f7', '8353bc56-4c00-4805-92a3-612f93336696', '17b887ce-c20d-4212-a603-14a75ee1fe9f', '7725320f-8202-471e-b25b-593aaaadf41f', '5629897b-db29-4e58-9e84-ff067647cd89', 'eedea912-1900-4cce-872c-b6be5c7a2150', '9c527df7-00f6-473c-9a23-51f40a23c64e', '2e12ebd7-cedc-4f36-b765-3353486b3846', '4f160434-e9ab-4ba4-83cb-7a08bdf62856', '6651d179-559f-4282-b600-6bcaacbebd01', 'f01a486a-7d0b-478b-b0bc-1fab92cc6f1a', '25834d2f-8f5e-4320-9813-ab1fa9bee9a6', '53182c48-805f-43e9-b925-ddeacaac7160'} |
---

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/lambda/azul-indexer-prod-contribute    
start-time: -259200s    
end-time: 0s    
query-string:
  ```
  fields @timestamp, @message
| filter @requestId = '0a950ed3-31d9-574f-96e7-5143813ae6e0'
| sort @timestamp asc
| limit 200
  ```
---
| @timestamp | @message |
| --- | --- |
| 2024-10-21 19:42:34.289 | START RequestId: 0a950ed3-31d9-574f-96e7-5143813ae6e0 Version: $LATEST |
| 2024-10-21 19:42:34.290 | [INFO] 2024-10-21T19:42:34.290Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.indexer.index_controller Worker handling message {'action': 'add', 'notification': {'transaction_id': 'a9ea1d4e-4c8f-4c3e-8be8-e1206c56d749', 'bundle_fqid': {'uuid': '1d96f4d7-1013-3ef7-a491-aae9b145837f', 'version': '2023-01-25T18:30:09.464965Z', 'source': {'id': '769fb8a9-dea0-40f8-8c2b-2427cbe73533', 'spec': 'tdr:bigquery:gcp:datarepo-3377446f:lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8:/0'}}}, 'catalog': 'lm8'}, attempt #'1' (approx). |
| 2024-10-21 19:42:34.290 | [DEBUG] 2024-10-21T19:42:34.290Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.plugins.repository.tdr_hca Retrieving 1 entities of type 'links' ... |
| 2024-10-21 19:42:34.331 | [INFO] 2024-10-21T19:42:34.331Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.deployment Allocated new Boto3 client for 'secretsmanager' with ID 140710037760592 |
| 2024-10-21 19:42:34.924 | [DEBUG] 2024-10-21T19:42:34.924Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.terra Query (296 characters total): "\n            SELECT project_id, content, links_id\n            FROM `datarepo-3377446f.lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8.links`\n            WHERE (links_id, version) IN (('1d96f4d7-1013-3ef7-a491-aae9b145837f', TIMESTAMP('2023-01-25T18:30:09.464965Z')))\n        " |
| 2024-10-21 19:42:36.296 | [DEBUG] 2024-10-21T19:42:36.296Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.terra Job info: {"job_id": "04095230-fffe-46f4-bdf1-c18ed2a3e0cb", "stats": {"estimatedBytesProcessed": "549559", "timeline": [{"elapsedMs": "394", "totalSlotMs": "142", "pendingUnits": "0", "completedUnits": "2", "estimatedRunnableUnits": "0"}], "totalPartitionsProcessed": "1", "totalBytesProcessed": "549559", "totalBytesBilled": "20971520", "billingTier": 1, "totalSlotMs": "142", "cacheHit": false, "searchStatistics": {"indexUsageMode": "UNUSED", "indexUnusedReasons": [{"code": "INDEX_CONFIG_NOT_AVAILABLE", "message": "There is no index configuration for the base table `datarepo-3377446f:lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8.datarepo_row_ids`.", "baseTable": {"projectId": "datarepo-3377446f", "datasetId": "lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8", "tableId": "datarepo_row_ids"}}, {"code": "INDEX_CONFIG_NOT_AVAILABLE", "message": "There is no index configuration for the base table `datarepo-fe8f7d1e:datarepo_lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207.datarepo_raw_links_90f0dbdf_62cd_4de9_b1f9_877e19271ca2`.", "baseTable": {"projectId": "datarepo-fe8f7d1e", "datasetId": "datarepo_lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207", "tableId": "datarepo_raw_links_90f0dbdf_62cd_4de9_b1f9_877e19271ca2"}}]}, "transferredBytes": "0", "metadataCacheStatistics": {"tableMetadataCacheUsage": [{"tableReference": {"projectId": "datarepo-fe8f7d1e", "datasetId": "datarepo_lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207", "tableId": "datarepo_raw_links_90f0dbdf_62cd_4de9_b1f9_877e19271ca2"}, "unusedReason": "OTHER_REASON", "explanation": "Table does not have CMETA."}, {"tableReference": {"projectId": "datarepo-3377446f", "datasetId": "lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8", "tableId": "datarepo_row_ids"}, "unusedReason": "OTHER_REASON", "explanation": "Table does not have CMETA."}]}}, "query": "\n            SELECT project_id, content, links_id\n            FROM `datarepo-3377446f.lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8.links`\n            WHERE (links_id, version) IN (('1d96f4d7-1013-3ef7-a491-aae9b145837f', TIMESTAMP('2023-01-25T18:30:09.464965Z')))\n        "} |
| 2024-10-21 19:42:36.491 | [DEBUG] 2024-10-21T19:42:36.491Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.plugins.repository.tdr_hca Retrieved 1 entities of type 'links' |
| 2024-10-21 19:42:36.569 | [INFO] 2024-10-21T19:42:36.569Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.plugins.repository.tdr_hca There are 17 dangling inputs in bundle TDRBundleFQID(uuid='1d96f4d7-1013-3ef7-a491-aae9b145837f', version='2023-01-25T18:30:09.464965Z', source=TDRSourceRef(id='769fb8a9-dea0-40f8-8c2b-2427cbe73533', spec=TDRSourceSpec(prefix=Prefix(common='', partition=0), type=<Type.bigquery: 'bigquery'>, domain=<Domain.gcp: 'gcp'>, subdomain='datarepo-3377446f', name='lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8'))) |
| 2024-10-21 19:42:36.569 | [DEBUG] 2024-10-21T19:42:36.569Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.plugins.repository.tdr_hca Dangling inputs in bundle TDRBundleFQID(uuid='1d96f4d7-1013-3ef7-a491-aae9b145837f', version='2023-01-25T18:30:09.464965Z', source=TDRSourceRef(id='769fb8a9-dea0-40f8-8c2b-2427cbe73533', spec=TDRSourceSpec(prefix=Prefix(common='', partition=0), type=<Type.bigquery: 'bigquery'>, domain=<Domain.gcp: 'gcp'>, subdomain='datarepo-3377446f', name='lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8'))): {EntityReference(entity_type='analysis_file', entity_id='25834d2f-8f5e-4320-9813-ab1fa9bee9a6'), EntityReference(entity_type='analysis_file', entity_id='53182c48-805f-43e9-b925-ddeacaac7160'), EntityReference(entity_type='analysis_file', entity_id='5629897b-db29-4e58-9e84-ff067647cd89'), EntityReference(entity_type='analysis_file', entity_id='eedea912-1900-4cce-872c-b6be5c7a2150'), EntityReference(entity_type='analysis_file', entity_id='024b8d4d-c026-4d5b-8053-a5364b35d532'), EntityReference(entity_type='analysis_file', entity_id='e0c02288-c7c8-42a4-9223-d53fb6141032'), EntityReference(entity_type='analysis_file', entity_id='2e12ebd7-cedc-4f36-b765-3353486b3846'), EntityReference(entity_type='analysis_file', entity_id='4f160434-e9ab-4ba4-83cb-7a08bdf62856'), EntityReference(entity_type='analysis_file', entity_id='6674bfef-cbb8-4575-b5d6-0e66bded1ccb'), EntityReference(entity_type='analysis_file', entity_id='8353bc56-4c00-4805-92a3-612f93336696'), EntityReference(entity_type='analysis_file', entity_id='6651d179-559f-4282-b600-6bcaacbebd01'), EntityReference(entity_type='analysis_file', entity_id='7725320f-8202-471e-b25b-593aaaadf41f'), EntityReference(entity_type='analysis_file', entity_id='09044642-a0ca-4bfd-9e87-40fd518ed863'), EntityReference(entity_type='analysis_file', entity_id='8bfda167-1b1e-4f30-9872-a70bc0bf21f7'), EntityReference(entity_type='analysis_file', entity_id='17b887ce-c20d-4212-a603-14a75ee1fe9f'), EntityReference(entity_type='analysis_file', entity_id='f01a486a-7d0b-478b-b0bc-1fab92cc6f1a'), EntityReference(entity_type='analysis_file', entity_id='9c527df7-00f6-473c-9a23-51f40a23c64e')} |
| 2024-10-21 19:42:36.570 | [DEBUG] 2024-10-21T19:42:36.570Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.terra Query (1264 characters total): '\n            SELECT links_id, version, JSON_EXTRACT_SCALAR(link_output, "$.output_id") AS output_id\n            FROM `datarepo-3377446f.lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8.links` AS links\n                JOIN UNNEST(JSON_EXTRACT_ARRAY(links.content, \'$.links\')) AS content_links\n                    ON JSON_EXTRACT_SCALAR(content_links, \'$.link_type\') = \'process_link\'\n                JOIN UNNEST(JSON_EXTRACT_ARRAY(content_links, \'$.outputs\')) AS link_output\n                    ON JSON_EXTRACT_SCALAR(link_output, "$.output_id") IN UNNEST([\'25834d2f-8f5e-4320-9813-ab1fa9bee9a6\', \'4f160434-e9ab-4ba4-83cb-7a08bdf62856\', \'6674bfef-cbb8-4575-b5d6-0e66bded1ccb\', \'8353bc56-4c00-4805-92a3-612f93336696\', \'6651d179-559f-4282-b600-6bcaacbebd01\', \'09044642-a0ca-4bfd-9e87-40fd518ed863\', \'9c527df7-00f6-473c-9a23-51f40a23c64e\', \'53182c48-805f-43e9-b925-ddeacaac7160\', \'5629897b-db29-4e58-9e84-ff067647cd89\', \'e0c02288-c7c8-42a4-9223-d53fb6141032\', \'eedea912-1900-4cce-872c-b6be5c7a2150\', \'024b8d4d-c026-4d5b-8053-a5364b35d532\', \'2e12ebd7-cedc-4f36-b765-3353486b3846\', \'7725320f-8202-471e-b25b-593aaaadf41f\', \'8bfda167-1b1e-4f30-9872-a70bc0bf21f7\', \'17b887ce-c20d-4212-a603-14a75ee1fe9f\', \'f01a486a-7d0b-478b-b0bc-1fab92cc6f1a\'])\n        ' |
| 2024-10-21 19:42:37.630 | [DEBUG] 2024-10-21T19:42:37.630Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.terra Job info: {"job_id": "285fce2b-2f07-45be-918a-f8508fe3bfba", "stats": {"estimatedBytesProcessed": "549483", "timeline": [{"elapsedMs": "388", "totalSlotMs": "130", "pendingUnits": "0", "completedUnits": "2", "estimatedRunnableUnits": "0"}], "totalPartitionsProcessed": "1", "totalBytesProcessed": "549483", "totalBytesBilled": "20971520", "billingTier": 1, "totalSlotMs": "130", "cacheHit": false, "searchStatistics": {"indexUsageMode": "UNUSED", "indexUnusedReasons": [{"code": "INDEX_CONFIG_NOT_AVAILABLE", "message": "There is no index configuration for the base table `datarepo-3377446f:lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8.datarepo_row_ids`.", "baseTable": {"projectId": "datarepo-3377446f", "datasetId": "lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8", "tableId": "datarepo_row_ids"}}, {"code": "INDEX_CONFIG_NOT_AVAILABLE", "message": "There is no index configuration for the base table `datarepo-fe8f7d1e:datarepo_lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207.datarepo_raw_links_90f0dbdf_62cd_4de9_b1f9_877e19271ca2`.", "baseTable": {"projectId": "datarepo-fe8f7d1e", "datasetId": "datarepo_lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207", "tableId": "datarepo_raw_links_90f0dbdf_62cd_4de9_b1f9_877e19271ca2"}}]}, "transferredBytes": "0", "metadataCacheStatistics": {"tableMetadataCacheUsage": [{"tableReference": {"projectId": "datarepo-fe8f7d1e", "datasetId": "datarepo_lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207", "tableId": "datarepo_raw_links_90f0dbdf_62cd_4de9_b1f9_877e19271ca2"}, "unusedReason": "OTHER_REASON", "explanation": "Table does not have CMETA."}, {"tableReference": {"projectId": "datarepo-3377446f", "datasetId": "lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8", "tableId": "datarepo_row_ids"}, "unusedReason": "OTHER_REASON", "explanation": "Table does not have CMETA."}]}}, "query": "\n            SELECT links_id, version, JSON_EXTRACT_SCALAR(link_output, \"$.output_id\") AS output_id\n            FROM `datarepo-3377446f.lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8.links` AS links\n                JOIN UNNEST(JSON_EXTRACT_ARRAY(links.content, '$.links')) AS content_links\n                    ON JSON_EXTRACT_SCALAR(content_links, '$.link_type') = 'process_link'\n                JOIN UNNEST(JSON_EXTRACT_ARRAY(content_links, '$.outputs')) AS link_output\n                    ON JSON_EXTRACT_SCALAR(link_output, \"$.output_id\") IN UNNEST(['25834d2f-8f5e-4320-9813-ab1fa9bee9a6', '4f160434-e9ab-4ba4-83cb-7a08bdf62856', '6674bfef-cbb8-4575-b5d6-0e66bded1ccb', '8353bc56-4c00-4805-92a3-612f93336696', '6651d179-559f-4282-b600-6bcaacbebd01', '09044642-a0ca-4bfd-9e87-40fd518ed863', '9c527df7-00f6-473c-9a23-51f40a23c64e', '53182c48-805f-43e9-b925-ddeacaac7160', '5629897b-db29-4e58-9e84-ff067647cd89', 'e0c02288-c7c8-42a4-9223-d53fb6141032', 'eedea912-1900-4cce-872c-b6be5c7a2150', '024b8d4d-c026-4d5b-8053-a5364b35d532', '2e12ebd7-cedc-4f36-b765-3353486b3846', '7725320f-8202-471e-b25b-593aaaadf41f', '8bfda167-1b1e-4f30-9872-a70bc0bf21f7', '17b887ce-c20d-4212-a603-14a75ee1fe9f', 'f01a486a-7d0b-478b-b0bc-1fab92cc6f1a'])\n        "} |
| 2024-10-21 19:42:37.791 | [WARNING] 2024-10-21T19:42:37.789Z 0a950ed3-31d9-574f-96e7-5143813ae6e0 azul.indexer.index_controller Worker failed to handle message {'action': 'add', 'notification': {'transaction_id': 'a9ea1d4e-4c8f-4c3e-8be8-e1206c56d749', 'bundle_fqid': {'uuid': '1d96f4d7-1013-3ef7-a491-aae9b145837f', 'version': '2023-01-25T18:30:09.464965Z', 'source': {'id': '769fb8a9-dea0-40f8-8c2b-2427cbe73533', 'spec': 'tdr:bigquery:gcp:datarepo-3377446f:lungmap_prod_6135382f487d4adb9cf84d6634125b68__20230207_20241002_lm8:/0'}}}, 'catalog': 'lm8'}. Traceback (most recent call last):   File "/var/task/azul/indexer/index_controller.py", line 180, in contribute     contributions, replicas = self.transform(catalog, notification, delete)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_controller.py", line 232, in transform     bundle = service.fetch_bundle(catalog, bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/indexer/index_service.py", line 201, in fetch_bundle     return plugin.fetch_bundle(bundle_fqid)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr.py", line 208, in fetch_bundle     bundle = self._emulate_bundle(bundle_fqid)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 319, in _emulate_bundle     entities, root_entities, links_jsons = self._stitch_bundles(bundle)                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 390, in _stitch_bundles     upstream = self._find_upstream_bundles(source, all_dangling_inputs)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/var/task/azul/plugins/repository/tdr_hca/__init__.py", line 512, in _find_upstream_bundles     require(not missing,   File "/var/task/azul/__init__.py", line 1628, in require     reject(not condition, *args, exception=exception)   File "/var/task/azul/__init__.py", line 1647, in reject     raise exception(*args) azul.RequirementError: Dangling inputs not found in any bundle: {'6674bfef-cbb8-4575-b5d6-0e66bded1ccb', 'e0c02288-c7c8-42a4-9223-d53fb6141032', '09044642-a0ca-4bfd-9e87-40fd518ed863', '024b8d4d-c026-4d5b-8053-a5364b35d532', '8bfda167-1b1e-4f30-9872-a70bc0bf21f7', '8353bc56-4c00-4805-92a3-612f93336696', '17b887ce-c20d-4212-a603-14a75ee1fe9f', '7725320f-8202-471e-b25b-593aaaadf41f', '5629897b-db29-4e58-9e84-ff067647cd89', 'eedea912-1900-4cce-872c-b6be5c7a2150', '9c527df7-00f6-473c-9a23-51f40a23c64e', '2e12ebd7-cedc-4f36-b765-3353486b3846', '4f160434-e9ab-4ba4-83cb-7a08bdf62856', '6651d179-559f-4282-b600-6bcaacbebd01', 'f01a486a-7d0b-478b-b0bc-1fab92cc6f1a', '25834d2f-8f5e-4320-9813-ab1fa9bee9a6', '53182c48-805f-43e9-b925-ddeacaac7160'} |
| 2024-10-21 19:42:37.828 | END RequestId: 0a950ed3-31d9-574f-96e7-5143813ae6e0 |
| 2024-10-21 19:42:37.828 | REPORT RequestId: 0a950ed3-31d9-574f-96e7-5143813ae6e0 Duration: 3539.32 ms Billed Duration: 3540 ms Memory Size: 256 MB Max Memory Used: 160 MB Init Duration: 3057.58 ms |
---

**Comment by hannes-ucsc** [comment]
Note that it is unclear from the description how many bundles are affected and if the list is exhaustive. The ultimate authority on indexing failures is the notification fail queue which the description does not mention.

Assuming that the list of affected snapshots in the description is exhaustive for the lm8 catalog, assignee to file temporary hotfix removing the offending snapshot.

Assignee to communicate the error to LungMAP.

**Comment by hannes-ucsc** [comment]
The fix (removal of the problematic snapshot) has been hotfixed on `prod` and backported to `develop`.
