### ISSUE TITLE
anvil8 snapshot not available

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6661]
The `anvil8` catalog caused a failure during `post_deploy_tdr.py` on hammerbox

https://gitlab.explore.anvilproject.org/ucsc/azul/-/jobs/35457

```
google.api_core.exceptions.Forbidden: 403 Access Denied: 
Table datarepo-647d4494:ANVIL_CCDG_Broad_AI_IBD_McCauley_WGS_20240114_ANV5_202409261945.anvil_biosample: 
User does not have permission to query table datarepo-647d4494:ANVIL_CCDG_Broad_AI_IBD_McCauley_WGS_20240114_ANV5_202409261945.anvil_biosample, 
or perhaps it does not exist.
```

Confirmed snapshot is not available via BigQuery

```
select * from `datarepo-647d4494.ANVIL_CCDG_Broad_AI_IBD_McCauley_WGS_20240114_ANV5_202409261945.anvil_dataset`

Access Denied: Table datarepo-647d4494:ANVIL_CCDG_Broad_AI_IBD_McCauley_WGS_20240114_ANV5_202409261945.anvil_dataset: 
User does not have permission to query table datarepo-647d4494:ANVIL_CCDG_Broad_AI_IBD_McCauley_WGS_20240114_ANV5_202409261945.anvil_dataset, 
or perhaps it does not exist.

**Comment by ncalvanese1** [comment]
I'm seeing the same issue when trying to query on my end. The project and dataset specified here seem to be correct. Rather than dig through the Google permissions nuances here, I think this one is safe to leave out for this release and I will build a new snapshot for the next release.

**Comment by hannes-ucsc** [comment]
The fix (removal of the problematic snapshot) has been hotfixed on `anvilprod` and backported to `develop`.
