### ISSUE TITLE
Various problems in can_bundle script

### ISSUE THREAD

**Issue by nadove-ucsc** [DataBiosphere/azul#6669]
- Inaccurate module-level docstring
- Faulty/brittle default value for `source` parameter
- Incorrect help message for `version` parameter
- Inference for AnVIL-specific bundle FQID fields will stop working once [replica bundles are introduced](https://github.com/DataBiosphere/azul/issues/6626)

**Comment by hannes-ucsc** [comment]
For demo, can one bundle from a source indexed by `prod` and a bundle of every type from a source indexed by `anvilprod`.
