### ISSUE TITLE
Left-overs from orphan-related PRs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6691]
In this issue, I'll collect nits from orphan-releated PRs for sibling issues in the parent epic.

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/pull/6677#pullrequestreview-2419228671

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/pull/6627#pullrequestreview-2422785437

**Comment by hannes-ucsc** [comment]
https://github.com/DataBiosphere/azul/pull/6623#pullrequestreview-2425598194

**Comment by achave11-ucsc** [comment]
Blocker landed.
