### ISSUE TITLE
Use controller logs to drive top 10 downloader reports

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6738]
![CleanShot 2024-12-04 at 09 23 25@2x](https://github.com/user-attachments/assets/3eeadb67-3bfa-4e05-8f72-a34389cacf7c)

`[INFO]	2024-12-04T17:21:48.288Z	8c0f8ee5-3f20-47eb-ab0a-6f690d0bfb06	azul.service.repository_controller	Download of file {"file_name": "GSM4906345_D110.mtx.gz", "file_uuid": "9a8d3322-a658-474f-a589-9c379c3105e3", "file_version": "2023-06-14T16:56:30.246000Z", "catalog": "dcp43", "fetch": false, "range": null, "host": "service.azul.data.humancellatlas.org", "user-agent": "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36", "x-forwarded-for": "REDACTED, 18.68.30.136"}`

**Comment by dsotirho-ucsc** [comment]
Added saved query to CloudWatch Insights.

![Screenshot 2024-12-04 at 6 02 38 PM](https://github.com/user-attachments/assets/297a8e12-31e8-4ec8-bcdf-3176ed5eaeb5)
