### ISSUE TITLE
Remove left-over resources from platform-hca-dev

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#6748]
Inventory review revealed the following items that should be removed:

- arn:aws:states:us-east-1:122796619775:stateMachine:azul-cartitems-nadove2
- arn:aws:states:us-east-1:122796619775:stateMachine:azul-cartexport-nadove2

… and the following items that may need to be removed:

- arn:aws:secretsmanager:us-east-1:122796619775:secret:dcp/azul/dev/slack_webhook-rgNmy3

_Originally posted by @hannes-ucsc in https://github.com/DataBiosphere/azul-private/issues/213#issuecomment-2524677668_

**Comment by dsotirho-ucsc** [comment]
@nadove-ucsc to take care of step functions. @achave11-ucsc to check if the secret is needed, and remove it if not.

**Comment by achave11-ucsc** [comment]
The resource `arn:aws:secretsmanager:us-east-1:122796619775:secret:dcp/azul/dev/slack_webhook-rgNmy3` has been scheduled for deletion in seven days (minimum waiting period):
<img width="862" alt="secret" src="https://github.com/user-attachments/assets/7ee89639-784a-4059-ac8e-32edf7b4bc79">

**Comment by nadove-ucsc** [comment]
The step functions have been deleted.
![image](https://github.com/user-attachments/assets/c476232b-0ea6-4143-af1a-db103a32c552)
