### ISSUE TITLE
Refactor service/app.py so that endpoint code is extracted into "services"

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#678]
`service/app.py` is getting too large! All of the code that does not directly deal with the HTTP request should be extracted into service classes (service is meant not in the sense of webservice, but more generally).

These services should include:
- repository
- version
- health
- manifest
- cart
- etc.

Which are imported into `app.py` and instantiated in the endpoint methods.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-423)
┆Project Name: azul
┆Issue Number: AZUL-423

**Comment by hannes-ucsc** [comment]
Demoed on 3/1/2019
