### ISSUE TITLE
Handle gateway timeouts during large manifest downloads

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#68]
How do we handle gateway timeouts when serving a manifest? If the client is slow, we will likely not be able to send the entire manifest in 30s. Similarly, if the manifest is larger than 10MB, another limit imposed by API gateway, the request will fail also.

The only solution is to store the manifest in S3 and redirect the user agent to a signed URL. This will also enable download resumption in browsers that support it.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-35)
┆Project Name: azul
┆Issue Number: AZUL-35

**Comment by hannes-ucsc** [comment]
Duplicates #356.
