### ISSUE TITLE
Default sort of projects tab and files tab is incorrect

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#683]
The default sort is coming back as specimenId on the first hit for both. 
This should be projectTitle  for project and filename for files.

Thanks!

![Screen Shot 2019-01-24 at 8.29.37 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/9dd0a542-d2a5-45a1-95be-40b232ea9d38)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-425)
┆Project Name: azul
┆Issue Number: AZUL-425

**Comment by hannes-ucsc** [comment]
BTW, I'd prefer a default sort that showed most recent entities first. Unfortunately there is no column for that so even if the made it the default, the user could not revert to it.
