### ISSUE TITLE
Download of small files is too slow

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#686]
After selecting a very small file (e.g. 32KB pdf) for single file download, the download takes approx. 10 seconds when it should be almost instantaneous. @NoopDog theorized that Azul is polling the file creation in S3 at a fixed interval and that we could speed up the process by polling at a very short interval initially and then backing off exponentially.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-426)
┆Project Name: azul
┆Issue Number: AZUL-426

**Comment by theathorn** [comment]
10s delay if checkout required. Fast if checkout already happened.
data-store issue.

**Comment by hannes-ucsc** [comment]
In our DSS proxy, we could ignore the Retry-After header sent back by DSS and implement exponential back-off: 1, 2, 4, 10 or so like we do for TSVs. But still file a ticket against DSS.

**Comment by hannes-ucsc** [comment]
Demo-ed on 5/13/2019
