### ISSUE TITLE
HCA DCP user metrics

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#69]
Logging should be integrated into the indexer.

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-34)
┆Project Name: azul
┆Issue Number: AZUL-34

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

This came up in an email thread by Marcio today… [~theathor] should coordinate with Adrienne at CZI to identify what key info should be logged and logging (ideally centralized logging would be a configuration option for the HCA project) would be added so that key info can be data mined later.  This will let us answer the questions about what’s the most popular way people are downloading data.

**Comment by hannes-ucsc** [comment]
I've added messages during indexing and am satisfied with the current log level.

In order to not drop the action item mentioned by @briandoconnor above, I'll be reassigning this to @theathorn.

**Comment by theathorn** [comment]
Re-purposing this ticket to specify the specific user metrics that Adrienne and Marcio wish to collect.

**Comment by theathorn** [comment]
Adrienne's doc: https://docs.google.com/document/d/1gqAwyv3k2ad3y7YH9iVMDPYxRskz6MJiueGikz1hCoI/edit

**Comment by theathorn** [comment]
All of the requested metrics (e.g. total # downloads) will need to be hooked up in the browser code. Need a plan to prioritize which ones get hooked up when.

**Comment by theathorn** [comment]
Matt Weiden's metrics plan: https://czi.quip.com/KanhAvUuZkE5/Analytics-instrumentation-plan

**Comment by theathorn** [comment]
Remaining work is covered by humancellatlas/data-browser#453.
