### ISSUE TITLE
Allow restricting the search query by entity ID

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#692]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-429)
┆Project Name: azul
┆Issue Number: AZUL-429

**Comment by theathorn** [comment]
Needs a usability discussion first.

**Comment by hannes-ucsc** [comment]
`&filter={"entryId": {"is":[…]}}` does that.
