### ISSUE TITLE
M2.3: Ensure the data browser indexing software can scale up to handle the maximum number of concurrent requests from users

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#698]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-433)
┆Project Name: azul
┆Issue Number: AZUL-433

**Comment by mweiden** [comment]
SLOs requirements document: https://docs.google.com/document/d/1OrKjfDR97fTugXprgkundI8i4k8SNOizcoz5fRTb8PU/edit#

**Comment by mweiden** [comment]
SLOs requirements document: https://docs.google.com/document/d/1OrKjfDR97fTugXprgkundI8i4k8SNOizcoz5fRTb8PU/edit#

**Comment by hannes-ucsc** [comment]
Applies to DCP/1 only. If the need arises to implement this for future compliance/certification, we'll open a new ticket.
