### ISSUE TITLE
Change organ_part to an array

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#699]
https://github.com/HumanCellAtlas/metadata-schema/pull/767

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-434)
┆Project Name: azul
┆Issue Number: AZUL-434

**Comment by theathorn** [comment]
metadata-api change required.

**Comment by hannes-ucsc** [comment]
Demoed on 3/1/2019
