### ISSUE TITLE
Add all available metadata fields to the manifest

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#705]
Add all the indexed facet fields to the file manifest used for cli download of files.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-436)
┆Project Name: azul
┆Issue Number: AZUL-436
┆Epic: Improved metadata access for user

**Comment by theathorn** [comment]
@briandoconnor suggests adding a "file path" column to the manifest which is the relative patrh to the file starting with the bundle_uuid
![Improved_download.jpg](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/5c78c783-b446-4942-b412-7dead1f0f031)

**Comment by hannes-ucsc** [comment]
The configuration about which ES document fields are included and what the corresponding column names in the TSV areype is currently configured in a [child dictionary](https://github.com/DataBiosphere/azul/blob/94ca44e11e74d48624652317d8bd49412d57f7c9/src/azul/service/service_config/request_config.json#L49) of `request_config.json`. 

That dict should be extended to include all inner entity types and all fields that make sense including (`_type` doesn't, for example). Avoid hard-coding inner entity types and instead iterate over the items.

**Comment by hannes-ucsc** [comment]
… over the items of `request_config['manifest']`.

**Comment by theathorn** [comment]
From #cli-downlaod-layout:
6) Have the CLI rewrite the manifest during download to include paths to the downloaded files

**Comment by hannes-ucsc** [comment]
Adding the paths to the manifest would happen locally in the CLI, not server-side in Azul, @theathorn.
