### ISSUE TITLE
Maintain a full, per-project metadata TSV file

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#706]
Ideally the metadata file would be updated automatically every time a new bundle which updates that project is ingested. Alternatively the metadata file could be generated on demand when the user requests the metadata file download in the Data Browser.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-437)
┆Project Name: azul
┆Issue Number: AZUL-437

**Comment by hannes-ucsc** [comment]
At indexing time call Simon Jupp's json-to-csv script and store its result in the index. Have the TSV links in the project tab point at a special endpoint that joins the per-bundles slices (each document is a slice) into a full TSV.
