### ISSUE TITLE
Python exception error during paging request

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#709]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-439)
┆Project Name: azul
┆Issue Number: AZUL-439

**Comment by theathorn** [comment]
See details in blocked bug.

**Comment by achave11** [comment]
This is the info about the offending document.

```
{
  "_index": "azul_projects_aggregate_integration",
  "_type": "doc",
  "_id": "fbf2302f-7a3a-4dca-bd82-1241e070299a",
  "_version": 2,
  "found": true,
  "_source": {
    "entity_id": "fbf2302f-7a3a-4dca-bd82-1241e070299a",
    "contents": {},
    "num_contributions": 1,
    "bundles": [
      {
        "uuid": "65628db7-a26c-4dc8-9e9d-b5c7ba944056",
        "version": "2019-01-11T000417.723770Z"
      }
    ]
  }
}
```

**Comment by hannes-ucsc** [comment]
Check DSS storage bucket in integration to see if the bundle is truly absent or has a tombstone hiding it.

**Comment by achave11** [comment]
DSS integration has indeed tombstone that bundle uuid. But the file document referenced by the bundle is still visible, I do not have the expertise to determine if it should also be tombstone.

**Comment by theathorn** [comment]
Azul should be resilient to this situation rather than generating an exception.

**Comment by hannes-ucsc** [comment]
@achave11 thank you, that confirms my suspicion. The bundle deletion removed the inner entities from the project aggregate. Now the question is whether we should leave the "empty" project document in the index and handle this case at query time or if we should remove it at bundle deletion time.

To confirm that the project document is actually empty, could you please post here what the contribution documents and the aggregate document look like for that project?

**Comment by hannes-ucsc** [comment]
I reindexed integration last night so the empty documents are probably gone.

@achave11 We should attempt to reproduce this by sending a mock deletion event to the indexer. Can you please write a script that composes a bundle deletion notification and sends it to the Azul service? This script should reproduce the empty project document. The script will also help us quickly and surgically take down index content without having to blacklist and reindex. So it will be very useful in the long run.

Also note

https://github.com/DataBiosphere/azul/blob/develop/test/indexer/test_hca_indexer.py#L67

which confirms that the current deletion behavior is to create an empty aggregate document. I'm still deciding if that is the right thing to do or not. For now we should focus on a reproduction of this issue now that I reindexed integration.

**Comment by hannes-ucsc** [comment]
I saw this in production just now.

The index can be fixed manually as follows: 

```
POST /azul_projects_aggregate_prod/_search
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "contents.projects"
                }
            }
        }
    }
}

POST /azul_projects_aggregate_prod/_delete_by_query
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "contents.projects"
                }
            }
        }
    }
}

POST /azul_specimens_aggregate_prod/_search
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "contents.specimens"
                }
            }
        }
    }
}

POST /azul_specimens_aggregate_prod/_delete_by_query
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "contents.specimens"
                }
            }
        }
    }
}

POST /azul_files_aggregate_prod/_search
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "contents.files"
                }
            }
        }
    }
}

POST /azul_files_aggregate_prod/_delete_by_query
{
    "query": {
        "bool": {
            "must_not": {
                "exists": {
                    "field": "contents.files"
                }
            }
        }
    }
}
```

**Comment by hannes-ucsc** [comment]
After observing this in production, I've reached a decision on how to address it.

**Comment by hannes-ucsc** [comment]
Demoed on 3/1/2019
