### ISSUE TITLE
Merge cgp-dashboard-service and cgp-dss-azul-indexer Data Biosphere repos

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#71]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-77)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-77

**Comment by hannes-ucsc** [comment]
The ticket migration reopened this but it should be closed.

https://github.com/HumanCellAtlas/data-browser/issues/115
