### ISSUE TITLE
Include Azul on DCP status page

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/azul#716]
Azul should be represented on page https://humancellatlas.github.io/

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-446)
┆Project Name: azul
┆Issue Number: AZUL-446

**Comment by mweiden** [comment]
Everything seems to be working except the `dev` environment https://humancellatlas.github.io/owners/ucsc/

Please check that your health check's name matches the one here https://github.com/HumanCellAtlas/humancellatlas.github.io/blob/master/config.json#L223

**Comment by achave11** [comment]
Demoed 04-02-19
