### ISSUE TITLE
Versioned (release snapshot) views of data

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#718]
Versioning on files, releases and workflows, no UI for that yet.

* Versions: Ingest currently only allows one version of a file. Allow user to select from multiple versions of the same file from our UI when Ingest supports that.
* A “Data Release” is a snapshot of different versions of many files and associated workflows that form a meaningful collection.  Post-pilot, coordinate with Data Release Working Group.
* Add a "Releases" facet to the Data Browser to allow facet searching, facet download, and matrix hand-off based on a Data Release view.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-448)
┆containerName: azul
┆Issue Number: AZUL-448

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Initial support for a Data Release could consist of a list of Manifest files stored in S3.
Each Manifest file would contain references to all the file versions in that release.

**Comment by theathorn** [comment]
Proposed views:
  - "live" view of all current bundle versions (possibly restricted to Data Ops)
  - "release" view of "version complete" data, as verified by Data Ops
  - "snapshot" views of point-in-time snapshots of curated data

**Comment by theathorn** [comment]
Superseded by DCP/2 - closing.
