### ISSUE TITLE
Frequent DSS client timeouts in indexer lambda

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#72]
```[WARNING]    2018-06-18T18:17:00.890Z    bd07bb4e-7323-11e8-b135-61fcd9ba1be4    Retrying (RetryPolicy(total=8, connect=None, read=8, redirect=None, status=10)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='dss.data.humancellatlas.org', port=443): Read timed out. (read timeout=10)",)': /v1/files/ecaa3899-d72d-4afc-953b-d655674e4d66?replica=aws```

Related to https://github.com/HumanCellAtlas/dcp-cli/issues/128

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-78)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-78

**Comment by cricketsloan** [comment]
➤ Hannes Schmidt commented:

Blocked on merge of https://github.com/HumanCellAtlas/dcp-cli/pull/130

**Comment by hannes-ucsc** [comment]
Ticket migration reopened this but it was originally closed:

https://github.com/HumanCellAtlas/data-browser/issues/110
