### ISSUE TITLE
Fastq Counts not matching between facet terms and file type summaries

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#725]
Looking at the below the file type summary for the first hit says we have 16377 fastq. However, the term facets only show a few files and only 1 fastq. I am expecting the term facets show at least 16377 fast qs.

This is in prod on the 1.3 M Brain Cells from E18 mice.

![Screen Shot 2019-02-25 at 2.18.32 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/ad463e05-b357-403b-aa35-40a913444981)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-450)
┆Project Name: azul
┆Issue Number: AZUL-450

**Comment by theathorn** [comment]
This is a bug in Production so we need to prioritize a fix.

**Comment by hannes-ucsc** [comment]
In a response to `/repository/projects`, the counts in `termFacets` represent number of projects, not number of files. In this case, for example, the `termFacets` counts means that there are 16 projects with `fastq.gz` files and 1 project with `fastq` files.
