### ISSUE TITLE
Download Manifest Crashes for Large File Sets

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#73]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-79)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-79

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Trevor Heathorn [5:06 PM]
Does manifest file contain file uuids or bundle uuids (+ timestamps) or both?

caaespin [5:07 PM]
I think it should be at a minimum a list of file uuids. But brian was saying it should have more stuff to allow people to open it in excel and stuff like that

So it should be made so it can pull out whatever fields from each elasticsearch result

**Comment by cricketsloan** [comment]
➤ Hannes Schmidt commented:

We think we saw that yesterday again.

**Comment by hannes-ucsc** [comment]
Ticket migration reopened this but it was originally closed:

https://github.com/HumanCellAtlas/data-browser/issues/58
