### ISSUE TITLE
Attempt a data browser and portal deployment using the runbooks

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#732]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-452)
┆Project Name: azul
┆Issue Number: AZUL-452

**Comment by theathorn** [comment]
Verify the instructions in humancellatlas/data-browser#235 and humancellatlas/data-portal#244.

**Comment by GPelayo** [comment]
The instructions for automated and manual deployment are correct. But in order for me to access the project settings I needed more permissions.
