### ISSUE TITLE
Test DCP-CLI with Python 3.7

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#739]
## User Story
As a DSS CLI user that keeps my system up to date with the latest Python version, I want the DSS CLI to work with Python 3.7

Note: I have not tried running the DCP CLI using Python 3.7, it may or may not work properly.
I'll estimate the story points at 2 for setting-up GitLab dcp-cli CI to include Python 3.7, and if significant issues are found, additional tickets can be opened to resolve them.

## Done When
The DCP CLI is tested with Python 3.7 as part of standard CI, and all tests pass successfully.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-457)
┆Project Name: azul
┆Issue Number: AZUL-457

**Comment by theathorn** [comment]
@mikebaumann Why is this ticket in azul and not dcp-cli?

**Comment by mikebaumann** [comment]
This issue should have been created in the `HumanCellAtlas/dcp-cli` repo.
I have recreated it there, and am closing this one.

/HumanCellAtlas/dcp-cli#259
