### ISSUE TITLE
Improve search to use synonyms for example searching human will find homo sapiens

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#74]
* need to come up with synonym for each facet term if required. 
* look at log at of search terms to see what people are looking for?

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-60)
┆Project Name: azul
┆Issue Number: AZUL-60

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
