### ISSUE TITLE
Write contributions guidelines

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#750]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-462)
┆Project Name: azul
┆Issue Number: AZUL-462

**Comment by hannes-ucsc** [comment]
No demo necessary. Guidelines are here: https://github.com/DataBiosphere/azul/blob/develop/CONTRIBUTING.rst
