### ISSUE TITLE
A developer onboarding and offboarding process is followed

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/azul#757]
As a DCP stakeholder
I want an onboarding and off-boarding process to be followed for developers
so we maintain the integrity of the DCP source code when people leave the team.

We need to follow an onboarding and off-boarding process both:
- at the DCP level - that addresses things such as GitHub organization access and PaaS access
- and at the component/ team level, that addresses specific needs for that component

Onboarding and offboarding documents should be linked to from the [DCP Ops Wiki Home](https://allspark.dev.data.humancellatlas.org/dcp-ops/docs/wikis/home)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-469)
┆Project Name: azul
┆Issue Number: AZUL-469

**Comment by hannes-ucsc** [comment]
Applies to DCP/1 only. If the need arises to implement this for future compliance/certification, we'll open a new ticket.
