### ISSUE TITLE
Consider shorter interval for sampling JVM memory pressure metric

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#759]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-470)
┆Project Name: azul
┆Issue Number: AZUL-470

**Comment by hannes-ucsc** [comment]
It appears that we missed a memory pressure spike incurred by a load test. The only possible explanation is that the spike occurred between two samples taken by CloudWatch.

**Comment by theathorn** [comment]
Sampling granularity is already at sampling maximum of 1 minute.
