### ISSUE TITLE
Ensure only code approved by appropriate reviewers gets merged into the DCP

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/azul#760]
We will use a service/tool called "Pull Approve" to achieve this (https://www.pullapprove.com/).

Overview:
The DevSecOps team are going to sign up for a pullapprove account.
[PullApprove Overview](https://www.pullapprove.com/docs/)
[Enabling required status checks - GitHub](https://help.github.com/en/articles/enabling-required-status-checks)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-472)
┆Project Name: azul
┆Issue Number: AZUL-472

**Comment by hannes-ucsc** [comment]
Applies to DCP/1 only. If the need arises to implement this for future compliance/certification, we'll open a new ticket.
