### ISSUE TITLE
Add security.txt file to all repos

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/azul#761]
Add a security.txt file to all repo.
This is as a way for people to communicate security issues to us.
security.txt contents:
```
If you'd like to report a security issue please contact us
Contact: security-leads@data.humancellatlas.org
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-473)
┆Project Name: azul
┆Issue Number: AZUL-473

**Comment by theathorn** [comment]
Also do metadata-api repo.
