### ISSUE TITLE
Review HCA repositories and verify that the list of readers/writers is following principle of least access

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/azul#762]
The HumanCellAtlas GitHub teams have been restructured.
To ease the transition to this structured world, everyone is currently in a team called "HCA" that has WRITE access to all repos.  We want to move away from this.

Each component team lead needs to audit the GitHub teams that have access to their repos.
Ensure only appropriate teams (e.g. CZI, UCSC, etc) have write access to your component's repos.
Ensure that you approve of any collaborators.
Then remove access from team HCA.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-474)
┆Project Name: azul
┆Issue Number: AZUL-474
┆Epic: DevSecOps tasks for Q2 2019

**Comment by hannes-ucsc** [comment]
I did just set HCA to only have write permissions on metadata-api.

**Comment by hannes-ucsc** [comment]
Azul is writable by https://github.com/orgs/DataBiosphere/teams/ucscwrite/members which overlaps largely with https://github.com/orgs/HumanCellAtlas/teams/ucsc/members but not fully. There are five members in the former that are not in the latter. All of them are UCSC employees or interns. Azul *was* administered by https://github.com/orgs/DataBiosphere/teams/ucscadmin/members which has two members that are not in https://github.com/orgs/HumanCellAtlas/teams/ucsc/members. I've removed admin privileges from https://github.com/orgs/DataBiosphere/teams/ucscadmin/members and gave them write access only. I can vouch for the current members of both https://github.com/orgs/DataBiosphere/teams/ucscwrite/members and https://github.com/orgs/DataBiosphere/teams/ucscadmin/members to trust them with write access to the repository.

Ultimately, a better solution would be to move Azul (or a fork of it) into the HCA organisation on Github. This is above my paygrade to decide. I would recommend it.

cc: @theathorn @briandoconnor @cricketsloan

**Comment by hannes-ucsc** [comment]
Closing this as it eliminates write access for the HCA team of the HumanCellAtlas organisation.
