### ISSUE TITLE
3rd party libraries in use are tracked and analyzed for security risk

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/azul#765]
DevSecOps team needs to tell us what tools to use to do this.
Then we will update all the component team tickets with that information.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-476)
┆Project Name: azul
┆Issue Number: AZUL-476
┆Epic: DevSecOps tasks for Q2 2019

**Comment by stahiri** [comment]
Per #308, DevSecOps recommendation is for everyone to use the same tool. Both Snyk and SourceClear are good options here. Prior recommendation from the team is to start with Snyk since it's open source (SourceClear requires procurement).

**Comment by GPelayo** [comment]
@stahiri @sampierson The Azul repo is now using Snyk. Will we still be using SourceClear?

**Comment by hannes-ucsc** [comment]
We are using SNYK now as part of our PR approval process.
