### ISSUE TITLE
Extract Indexer code into schema accessor library for use by Orange and Green boxes

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#77]
Isolate Indexer code from metadata changes by implementing (largely from existing code) and accessor library for the desired facets.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-81)
┆Project Name: azul
┆Issue Number: AZUL-81

**Comment by theathorn** [comment]
Dup of #97.
