### ISSUE TITLE
DOS URL for BDBag export starts with dos://...

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#774]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-479)
┆Project Name: azul
┆Issue Number: AZUL-479

**Comment by theathorn** [comment]
I thought we were supposed to use "drs" not "dos" from now on...

**Comment by hannes-ucsc** [comment]
`dos://` is required by DRS v0.1.

**Comment by hannes-ucsc** [comment]
Either way, we should use whatever protocol works. If both work we'll go with `drs://`. Precedence is `dos://` and we should try that first to minimize risk.

**Comment by hannes-ucsc** [comment]
This was demo'ed by @mjkrause.
