### ISSUE TITLE
SNYK checks interfere with PR builds for HCA

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#776]
@mikebaumann and @coverbeck it looks like both of you configured SNYK on this repository. Sometimes those checks fail for mysterious reasons and that interferes with my team's workflow.  Is there a way to disable these checks for PR targeting `develop`? Or only enable them on *your* protected branches? At the very least one of you should disable their checks.

The failing check for this PR is one of those sporadic failures.

![Screen Shot 2019-03-09 at 12 26 00 AM](https://user-images.githubusercontent.com/5143256/54068475-04d5d080-4202-11e9-9407-082974e7795e.png)

The `Details` link  goes here:

![Screen Shot 2019-03-09 at 12 26 19 AM](https://user-images.githubusercontent.com/5143256/54068476-056e6700-4202-11e9-927c-c839375ae014.png)

Here's a screenshot show the two sets of redundant checks.

![Screen Shot 2019-03-09 at 12 29 13 AM](https://user-images.githubusercontent.com/5143256/54068523-80d01880-4202-11e9-9a01-d8694a98a2f6.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-480)
┆Project Name: azul
┆Issue Number: AZUL-480

**Comment by theathorn** [comment]
@kozbo Can you prioritize this ticket?

**Comment by coverbeck** [comment]
I believe I have just now removed my checks.

I did not intentionally add them; perhaps when I first signed up with Synk it automatically added them; or maybe I inadvertently did it.

In any case, let me know if it is still an issue.

**Comment by mikebaumann** [comment]
We (@coverbeck  and @mikebaumann) have removed our use of Snyk integrations from the `azul` repo.
@hannes-ucsc will setup/manage the Snyk integration with Azul going forward, and this work is represented by: https://github.com/DataBiosphere/azul/issues/765
