### ISSUE TITLE
Logging integrated with the web service

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#78]
Logging should be integrated with the web service

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-84)
┆Project Name: azul
┆Issue Number: AZUL-84
┆Epic: Data Browser integration with logging and analytics

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

See also #29. We log to Cloudwatch and Airbrake picks that up automatically.

**Comment by hannes-ucsc** [comment]
See https://github.com/DataBiosphere/azul/issues/69#issuecomment-406905668

This ticket is redundant.
