### ISSUE TITLE
Test projects appearing in prod data browser despite underlying bundles being deleted

### ISSUE THREAD

**Issue by parthshahva** [DataBiosphere/azul#780]
Projects:
https://prod.data.humancellatlas.org/explore/projects/303679d6-2ace-4ced-9db6-d601182f30d4
https://prod.data.humancellatlas.org/explore/projects/35d5fc68-ab51-41ed-8d73-b40f9c7944b1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-482)
┆Project Name: azul
┆Issue Number: AZUL-482

**Comment by hannes-ucsc** [comment]
Duplicates #734 which will be rolled out tomorrow.
