### ISSUE TITLE
Exclude deprecated prod dataset; include new version of dataset

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#786]
I have recently re-ingested the meyer dataset in prod to remove redacted external accessions.

Could you please: 
- [ ] exclude the old version of the dataset (submission ID: `5c07e2029460a300075019b1`; project UUID: `209e6402-d854-49ea-815f-421dae5e3f4d`)
- [x] include the new version of the dataset (submission ID: `5c863a8bcefdf1000731395f`; project UUID: `6ac9d7b5-f86d-4c23-82a9-485a6642b278`)

The new IDs have been updated in the CBeta spreadsheet. Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-486)
┆Project Name: azul
┆Issue Number: AZUL-486

**Comment by theathorn** [comment]
Superseded by humancellatlas/data-store#1976.
