### ISSUE TITLE
Evaluate relationship between ES instance type and max. # of concurrent users

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#795]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-495)
┆Project Name: azul
┆Issue Number: AZUL-495
┆Epic: Review/reduce AWS Elasticsearch costs

**Comment by hannes-ucsc** [comment]
@achave11 can you list specific instance types you plan on testing? 

We also need to document the number of nodes per cluster and the number of bundles that match the DSS query used for reindexing. In the end, we need to produce a table that lists the test cases as rows and the measured performance metrics as columns. I'd like to review that table with you before we run any tests.

**Comment by achave11** [comment]
The following table captures a few configurations that enable Azul to make a selection on the most optimal ES instance type. In an effort to reduce cost and optimize indexing time as well as responses time to the clients.
@hannes-ucsc please let me know if I am missing any other key pieces of information or any other suggestions you may have.
Notice that we will fill in the fields missing and labeled **TBD** as well as adding more entries to the table with other instance types. Fields to the right of `Indexing Time Warm DSS` should be sectioned into sub tables capturing data for an increased number of users.  
This table shall also be captured in the a file called `elasticsearch_analysis.md` in the project's root directory. 

| ES Instance Type | ES Type Cost | Nodes Per Cluster | Bundles Matching DSS Query | Indexing Time Cool DSS | Indexing Time Warm DSS | Number of Users | RPS | Fail Rate % | Max Request/sec| Max response Time| Min Response Time| 
|---|---|---|---|---|---|---|---|---|---|---|---|
|r4.2xlarge.elasticsearch|$0.785 per Hour| 2| TBD| TBD|TBD|TBD|TBD|TBD|TBD|TBD|TBD|

**Comment by hannes-ucsc** [comment]
It's becoming clear to me that we should do this is as a Google Spreadsheet. My apologies of not specifying this earlier. Link to the spreadsheet here but set permissions so it is only shared with the team.

I wouldn't put "TBD" in each cell, but instead leave them empty. Using "TBD" makes it harder to tell visually which cells have actual values in them. Ultimately, all cells should be filled in so it there is no risk in leaving them empty.

Please also add the core parameters of each type: vCPU, Memory (GiB) and Instance Storage (GB) from https://aws.amazon.com/elasticsearch-service/pricing/.

**Comment by theathorn** [comment]
Superseded by DCP/2 - closing.
