### ISSUE TITLE
create pull request for Boardwalk to Xena

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#8]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-18)
┆Project Name: azul
┆Issue Number: AZUL-18

**Comment by david4096** [comment]
@wshands Do you know where the code for this is?

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

[https://github.com/DataBiosphere/cgp-dashboard/tree/feature/Xena-Button](https://github.com/DataBiosphere/cgp-dashboard/tree/feature/Xena-Button)

**Comment by david4096** [comment]
Thanks!

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
