### ISSUE TITLE
Configure Azul indexer mapping config for selected metadata

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#80]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-5)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-5
┆Epic: Add Support for Selected Metadata Schema

**Comment by cricketsloan** [comment]
➤ Abraham Chavez commented:

[~gpelayo1] is this done?

**Comment by cricketsloan** [comment]
➤ Geryl Pelayo commented:

Not yet. Some fields from the blue box are not mapped correctly with the fields in the indexer/dcc-dashboard.

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

[~gpelayo1] is there a task here that [~achave11] can be working on?

**Comment by hannes-ucsc** [comment]
This is done in JIRA. Closing.
