### ISSUE TITLE
Add cell_suspension.selected_cell_type to the Azul index

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#800]
See blocked data-browser ticket for details.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-490)
┆Project Name: azul
┆Issue Number: AZUL-490
┆Epic: Improve or Replace Specimens Tab

**Comment by hannes-ucsc** [comment]
https://github.com/HumanCellAtlas/metadata-api/releases/tag/release%2F1.0b12

**Comment by danielsotirhos** [comment]
I demoed this on 04/02/2019
