### ISSUE TITLE
Consolidate ES instances for lesser deployments

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#809]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-503)
┆Project Name: azul
┆Issue Number: AZUL-503
┆Epic: Review/reduce AWS Elasticsearch costs

**Comment by theathorn** [comment]
Have dev, integration and staging use 1 shared ES instance.

**Comment by achave11** [comment]
Demoed 04-02-19
