### ISSUE TITLE
Iterate over the indexer

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#81]
Continue refactoring and refining the indexer code.

┆Issue is synchronized with this [JIRA Task](https://ucsc-cgl.atlassian.net/browse/AZUL-2)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-2

**Comment by cricketsloan** [comment]
➤ Carlos Alberto Espinosa Méndez commented:

UPDATE: Didn't get a chance to do this.

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

This is an area of work that should be represented as an epic (in HCA) to create a production quality indexer, and have multiple, specific stories under it.

**Comment by caaespin** [comment]
Closing since it's very vague. This has happened way too many times.
