### ISSUE TITLE
Implement method to write different types of indexes

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#82]
We should come up with a couple algorithms for indexing the data into different types of indexes. 

We need the following indexes:

* Project
* Assays
* Donor
* Samples
* Bundles
* Files

We already have files and bundles indexes. We just need to create indexes for the remaining categories

The reason for this will be to facilitate querying in ElasticSearch

┆Issue is synchronized with this [JIRA Task](https://ucsc-cgl.atlassian.net/browse/AZUL-4)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-4

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

working on

  * [x] Donor

**Comment by cricketsloan** [comment]
➤ Cricket Alicia Sloan commented:

@caaespin What is the status of this task?  Is this for HCA schema?

**Comment by cricketsloan** [comment]
➤ Michael Krause commented:

This ticket is at least 3 months old and thus stale. If Carlos hasn't responded I assume it is obsolete by now and will reject it.

**Comment by caaespin** [comment]
resolved DataBiosphere/cgp-dss-azul-indexer#35
