### ISSUE TITLE
Remove duplicate subscription from Gitlab account in integration

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#822]
... and possibly other deployments as well.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-511)
┆Project Name: azul
┆Issue Number: AZUL-511

**Comment by hannes-ucsc** [comment]
Both `staging` and `integration` had subscriptions owned by Gitlab. I removed those. The `prod` has never been been touched by `gitlab` so it should be ok. `dev` didn't have subscription owned by `gitlab`.
