### ISSUE TITLE
Detect duplicate subscriptions

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#823]
It could be useful for debugging if there is an alarm or warning in the case where there are duplicate subscriptions to DSS.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-510)
┆Project Name: azul
┆Issue Number: AZUL-510

**Comment by jessebrennan** [comment]
According to the [Airbrake docs](https://airbrake.io/docs/airbrake-faq/what-triggers-a-new-email/#resolved-notices) if an issue is marked resolved, that won't prevent the issue from showing up again (it just removes the cruft from your immediate view.

Also from [the docs](https://airbrake.io/docs/airbrake-faq/what-triggers-a-new-email/#error-severity) if the error is of severity `warning` it will be logged, but it won't create an email notification. One possible solution would be to log at lever `error` when duplicate notifications are detected.

**Comment by hannes-ucsc** [comment]
Seems like Airbrake (or at least the free plan) is currently insufficient for what we are trying to achieve. Lets go ahead with your proposition to log that particular at ERROR severity and call it a day.

**Comment by jessebrennan** [comment]
I agree (although interestingly, we have a paid plan).

**Comment by jessebrennan** [comment]
Since duplicate notifications happen during integration tests (intentionally) This error would be raised every time integration tests are run which is impractical. Instead we need a measure to check for duplicate notifications.

**Comment by jessebrennan** [comment]
A decision was made during standup to ignore this issues unless it's possible to receive warning level messages from Airbrake. I'm contacting Matt to see about this possibility.

**Comment by jessebrennan** [comment]
It's possible to set the error severity with Airbrake, but it all has to be done manually by examining the error. Originally, @hannes-ucsc and I were under the impression that Airbrake figures out which exceptions should be logged. This was incorrect. Instead, any log message containing 
```
'stacktrace',
'traceback',
'error',
'exception',
'critical'
``` 
(this comes from https://github.com/HumanCellAtlas/logs/blob/master/scripts/secret_templates.py#L46)

will be automatically sent to Airbrake. So while it IS possible to add specify the severity, it would be complicated and involve parsing the logged messages.

If we wanted to make full use of Airbrake's features, we would be better off integrating Airbrake into Azul directly which seems pretty straight forward, and would isolate us from the noise of DSS errors, etc. While that's a possibility worth considering, @hannes-ucsc I think this is probably ok to close.

**Comment by hannes-ucsc** [comment]
I may have an idea of how we could make this change relatively easily. Let's talk. Hint: turn `airbrake_whitelisted_log_message_terms` into a dict mapping an Airbrake severity into list of terms.

**Comment by theathorn** [comment]
Obsolete DCP/1 issue.
