### ISSUE TITLE
Relax assertion on `file_version` in service/app.py

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#828]
The assertion in the DRS endpoint is too strict (https://github.com/DataBiosphere/azul/blob/develop/lambdas/service/app.py#L1542), as `file_version` can be `None` in some cases.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-515)
┆Project Name: azul
┆Issue Number: AZUL-515

**Comment by hannes-ucsc** [comment]
Skipping demo since @mjkrause is on different team now.
