### ISSUE TITLE
Add bundle deletion to integration test

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#838]
This will also have the added benefit of leaving test projects around.

Ideally the test would leave the index as it originally was. This may require careful thought. I am not 100% certain that deletion is the right way to undo the indexing of bundles with the project name patch in place. But it may well be.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-518)
┆Project Name: azul
┆Issue Number: AZUL-518

**Comment by jessebrennan** [comment]
while doing the integration test no genuine notifications should be processed because they may collide with the test set.

**Comment by hannes-ucsc** [comment]
Demo-ed on 5/13/2019

but @jessebrennan to file follow-up ticket about clean-up.
