### ISSUE TITLE
Re-index operation with Elasticsearch causes "Error 429 - too many requests"

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#84]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-80)
┆Project Name: Azul Indexer
┆Issue Number: AZUL-80

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Decide approach on #files in bundle (freak bundles with large number of files [> 200]).

**Comment by hannes-ucsc** [comment]
Ticket migration reopened this but it was originally closed:

https://github.com/HumanCellAtlas/data-browser/issues/109
