### ISSUE TITLE
Make each row in BDBag's `samples.tsv` unique

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/azul#845]
According to the Terra/Broad entity data model, in any given row the combination of and`participant_id` and `entitiy:samples_id` is the primary key for that row in that table, and needs to be a unique in `samples.tsv`. 

If two or more files have a the same primary key we need to add columns in the already existing row for that key and add the additional values to that row.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-523)
┆Project Name: azul
┆Issue Number: AZUL-523

**Comment by mjkrause** [comment]
Here's an example of a [samples.tsv](https://github.com/DataBiosphere/azul/files/3011136/samples.txt) with corresponding [participants.tsv](https://github.com/DataBiosphere/azul/files/3011146/participants.txt)
to illustrate the problem. Filenames end in `.txt` as GitHub doesn't permit upload of files ending in `.tsv`. The manifest was generated with filter `{"file":{"organ":{"is":["spleen"]},"biologicalSex":{"is":["male"]},"fileFormat":{"is":["fastq.gz"]}}}` and format `bdbag`.

If we look at `participant.tsv` we see that data are only from two participants (i.e., donors). Note that `samples.tsv`  has 12 rows and 14 columns
* each row has a one duplicate as the same file is in two distinct bundles (i.e., file URLs and file versions are identical)
* even if make each row unique with respect to file URL/version we're still left with 3 duplicates with identical `participant_id` and `entity:sample_id`
* so we need to create new columns for distinct values of a given unique participant-sample pair
* those are values such as 
     * `bundle_version`
     * `bundle_uuid`
     * `file_name`
     * `file_sha256`
     * `file_size`
     * `file_uuid`
     * `file_version`
     * `file_url`
     * `file_indexed`
     * `dos_url`
* to make `samples.tsv` compliant with the Terra entity data model the it will have three rows and 14 + 10 + 10 = 34 columns
* to create distinct column headers we postfix them with `_01`, `_02`, etc.

**Comment by hannes-ucsc** [comment]
Obsoleted by #856.
