### ISSUE TITLE
Set up a Development, Integration, Staging and Production environments for the browser and all its components

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#85]
This can probably be broken down in a ticket per environment and componente

* [ ] Development
* [ ] Integration
* [ ] Staging
* [ ] Production

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-61)
┆Project Name: azul
┆Issue Number: AZUL-61
┆Epic: Setup HCA environments

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

From Pilot planning meeting: We are moving all deployments of services to gitlab.

**Comment by hannes-ucsc** [comment]
See https://github.com/HumanCellAtlas/data-browser/issues/178 for Data Browser.
