### ISSUE TITLE
Expose full metadata files as https:// rather than http:// URLs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#850]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-526)
┆Project Name: azul
┆Issue Number: AZUL-526
┆Epic: Maintain a full, per-project metadata TSV file

**Comment by theathorn** [comment]
Will become obsolete when #902 is done.
