### ISSUE TITLE
Create per-project TSVs in all deployments

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#851]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-529)
┆Project Name: azul
┆Issue Number: AZUL-529
┆Epic: Maintain a full, per-project metadata TSV file

**Comment by theathorn** [comment]
Will be obsolete once auto metadata tsv generation is done (#902).
