### ISSUE TITLE
Create per-project metadata JSONs and publish them

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#852]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-528)
┆Project Name: azul
┆Issue Number: AZUL-528

**Comment by diekhans** [comment]
prototype code is here:
https://github.com/diekhans/hca-metadata-merge

**Comment by theathorn** [comment]
Closing in favor of #2693.
