### ISSUE TITLE
Maintain per-project metadata JSONs

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#853]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-527)
┆Project Name: azul
┆Issue Number: AZUL-527

**Comment by diekhans** [comment]
Some empirical testing of Hannes'  observation that updating the metadata  aper-bundle event will be disastrously slow verifies this conclusion.  While a simple increment metadata.json when adding a bundle can be linear, the kind of update that will happen when metadata is migrated is O(N^2) for building metadata.json.  Empirically, O(N^2) is multiple days or even weeks with a single core.

Bundle events gives us 'map', but we don't have 'reduce'.   Higher-level events are needed to do the 'reduce' phase.   

Updating project-level data incrementally also creates a consistent-view problem of the project data.  You may have a project that is partially metadata migrated that a user is seeing.

Until we have an architectural solution I would suggest we have the download client build metadata.json.

**Comment by theathorn** [comment]
See #852.

**Comment by theathorn** [comment]
Closing in favor of #2693.
