### ISSUE TITLE
Recreate per-project TSVs with fixed file_metadata_to_csv.py script 

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#855]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-530)
┆Project Name: azul
┆Issue Number: AZUL-530

**Comment by GPelayo** [comment]
Used script from https://github.com/HumanCellAtlas/hca_bundles_to_csv/blob/%233/hca_bundle_tools/file_metadata_to_csv.py

**Comment by hannes-ucsc** [comment]
http://url.data.humancellatlas.org/projects/0c7bbbce-3c70-4d6b-a443-1b92c1f205c8.tsv
http://url.data.humancellatlas.org/projects/0ec2b05f-ddbe-4e5a-b30f-e81f4b1e330c.tsv
http://url.data.humancellatlas.org/projects/179bf9e6-5b33-4c5b-ae26-96c7270976b8.tsv
http://url.data.humancellatlas.org/projects/1a0f98b8-746a-489d-8af9-d5c657482aab.tsv
http://url.data.humancellatlas.org/projects/29f53b7e-071b-44b5-998a-0ae70d0229a4.tsv
http://url.data.humancellatlas.org/projects/34ec62a2-9643-430d-b41a-1e342bd615fc.tsv
http://url.data.humancellatlas.org/projects/5dfe932f-159d-4cab-8039-d32f22ffbbc2.tsv
http://url.data.humancellatlas.org/projects/5f256182-5dfc-4070-8404-f6fa71d37c73.tsv
http://url.data.humancellatlas.org/projects/6ac9d7b5-f86d-4c23-82a9-485a6642b278.tsv
http://url.data.humancellatlas.org/projects/aabbec1a-1215-43e1-8e42-6489af25c12c.tsv
http://url.data.humancellatlas.org/projects/c765e3f9-7cfc-4501-8832-79e5f7abd321.tsv
http://url.data.humancellatlas.org/projects/d96c2451-6e22-441f-a3e6-70fd0878bb1b.tsv
http://url.data.humancellatlas.org/projects/e8642221-4c2c-4fd7-b926-a68bce363c88.tsv
http://url.data.humancellatlas.org/projects/f396fa53-2a2d-4b8a-ad18-03bf4bd46833.tsv
http://url.data.humancellatlas.org/projects/f8880be0-210c-4aa3-9348-f5a423e07421.tsv
http://url.data.humancellatlas.org/projects/ff481f29-3d0b-4533-9de2-a760c61c162d.tsv

**Comment by GPelayo** [comment]
https://github.com/HumanCellAtlas/hca_bundles_to_csv/pull/6

**Comment by GPelayo** [comment]
The PR, https://github.com/DataBiosphere/azul/issues/855, for the fix to the script has been merged.
