### ISSUE TITLE
Specify algorithm for supporting multiple files per BDBag TSV row

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#856]
UCSC owes algorithm for identifying sets of file columns given 1) the set of files a user selected for hand-off by the data browser and 2) the bundles those files belong (knowing that each bundle will be a distinct row and therefore unit of work in Terra)

Don't use file name heuristic but derive from metadata columns (like sequence_file.read_index for fastqs).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-531)
┆Project Name: azul
┆Issue Number: AZUL-531

**Comment by hannes-ucsc** [comment]
Obsoletes #845.

**Comment by mjkrause** [comment]
Brain storming on the algorithm design of creating a TSV file where each row is represented by one bundle UUID, with multiple files in that row. Shown below are photographs of notes by Hannes on the white board from 2019-03-28 that sketches out the basic ideas.

![20190328_120702_board_left](https://user-images.githubusercontent.com/15079157/55432928-04063500-5549-11e9-85b9-000fac549054.jpg)
![20190328_120714_board_right](https://user-images.githubusercontent.com/15079157/55432940-09637f80-5549-11e9-8e25-d94e07925c63.jpg)
![20190328_120725_board_center](https://user-images.githubusercontent.com/15079157/55432946-0cf70680-5549-11e9-8cbb-d11ef41874a6.jpg)
