### ISSUE TITLE
"One Cell per Bundle" for SmartSeq2 creates ~100K+ bundles referring to the same Specimen or Project

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#86]
One cell per bundle output for SmartSeq2 data will be challenging for the search, download and wrangling experience after the files are downloaded. We were planning on making downloads create a directory per bundle, this may not be practical. 

Greebox is looking for ways to group cells from a single sequencer run into a more compact format. 

We should track progress on this and make sure we understand the ramifications for orange box for any progress or lack of progress on this issue.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-62)
┆Project Name: azul
┆Issue Number: AZUL-62
┆Epic: Reindexing is slow

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Is this: https://docs.google.com/document/d/1T5YrLNCtv7_PbvNRiD-1FDT0a-rBFE_57nhTxY-PV8M/edit#heading=h.93bxgjvsvr4u

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

@NoopDog please discuss with @hannes-ucsc

**Comment by hannes-ucsc** [comment]
Who created this initially? I can't comprehend any part of the description.

**Comment by theathorn** [comment]
@hannes-ucsc This ticket was originally created by @NoopDog as data-browser issue 45 on 5/5/18.
I'm not sure it serves a useful purpose any more as we know that Ingest has chosen the SmartSeq2 bundle structure to have 1 cell per bundle and we are now handling that situation.

**Comment by theathorn** [comment]
Re-purposing this to handle data sets with approx. 100K bundles referring to the same Specimen or Project (e.g. Tabula Muris).
