### ISSUE TITLE
Establish SOP with metadata group for releasing of new schema versioning and handling on all of the Orange Box

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#87]
As a developer I would like to have a consistent protocol for updating the browser components (indexing, web service, UI) each time a new schema version is released

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-63)
┆Project Name: azul
┆Issue Number: AZUL-63

**Comment by hannes-ucsc** [comment]
Agreed procedure is to deploy schema changes to prod and promoted fixes for potential issues normally. Missing piece of functionality is how to trigger the reprocessing of failed bundles in prod. But this is not an Azul issue.
