### ISSUE TITLE
Components SHOULD implement Level 2 Health Checks

### ISSUE THREAD

**Issue by sampierson** [DataBiosphere/azul#878]
_The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119._

**As a DCP Operator,
I want to know not only that a component is up, but that it is nominally functional,
so that we may take action if necessary to remedy the situation.**

Most components currently only have what we will call a "Level 1" Health Check in place.  They have a `/heath` endpoint that will respond if the REST API part of the service is available, but it indicates no more than the REST API part of the service is functioning.

A "Level 2" health check tests other parts of the component service and its internal dependencies, to give a clearer indication that the entire component is healthy.

I suspect that it is unlikely that these checks can be completed in real time (i.e. please don't block for ages when `/health` is polled), and that the `/health` endpoint will be reporting results of the last time that periodic health checks ran in the background.

This ticket was created at the request of the Tech Arch committee, 2019/03/22 meeting.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-546)
┆Project Name: azul
┆Issue Number: AZUL-546

**Comment by mweiden** [comment]
@hannes-ucsc @achave11 This is complete, true?

**Comment by hannes-ucsc** [comment]
```
$ http 'https://service.explore.data.humancellatlas.org/health'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 610
Content-Type: application/json
Date: Fri, 19 Jul 2019 16:15:07 GMT
Via: 1.1 7b5e90ec4988c1c340392b828c6f9f4b.cloudfront.net (CloudFront)
X-Amz-Cf-Id: FWuAz1wLcrBIIipdPQsLxJ0mQuX6RVSML0W1lNIi5TZP8X4xifZupQ==
X-Amz-Cf-Pop: SFO5-C1
X-Amzn-Trace-Id: Root=1-5d31ec8b-574ff6a03a7f2c1041007a00;Sampled=0
X-Cache: Miss from cloudfront
x-amz-apigw-id: dFHlwElPIAMFczg=
x-amzn-RequestId: 5fb77c13-aa40-11e9-aeff-7d5e62d71307

{
    "elastic_search": {
        "up": true
    },
    "indexer": {
        "up": true
    },
    "queues": {
        "azul-documents-prod": {
            "messages": {
                "delayed": 0,
                "invisible": 0,
                "queued": 0
            },
            "up": true
        },
        "azul-documents-prod.fifo": {
            "messages": {
                "delayed": 0,
                "invisible": 0,
                "queued": 0
            },
            "up": true
        },
        "azul-fail-prod": {
            "messages": {
                "delayed": 0,
                "invisible": 0,
                "queued": 0
            },
            "up": true
        },
        "azul-fail-prod.fifo": {
            "messages": {
                "delayed": 0,
                "invisible": 0,
                "queued": 0
            },
            "up": true
        },
        "azul-notify-prod": {
            "messages": {
                "delayed": 0,
                "invisible": 0,
                "queued": 0
            },
            "up": true
        },
        "up": true
    },
    "unindexed_bundles": 0,
    "unindexed_documents": 0,
    "up": true
}
```

**Comment by mweiden** [comment]
@hannes-ucsc great, ty!
