### ISSUE TITLE
`/repository/specimens/{uuid}` returns 404 even with valid UUID of existing specimen

### ISSUE THREAD

**Issue by GPelayo** [DataBiosphere/azul#879]
The endpoint `/repository/specimens/{uuid}` returns a 404 `NotFoundError` even when `{uuid}` is the correct id of a specimen indexed in Azul.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-547)
┆Project Name: azul
┆Issue Number: AZUL-547

**Comment by hannes-ucsc** [comment]
I found this too, and https://github.com/DataBiosphere/azul/pull/874 fixes it.

**Comment by hannes-ucsc** [comment]
Demoed on 5/28/2019
