### ISSUE TITLE
Shopping cart: support for interactive building of collections

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#88]
From https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/dcp/34:

As a user of the DCP, I will approach it and it's vast amounts of data and, after searching for the data that meets the requirements of my study or analysis, I will want to take those search results and treat them as a unit.

A user can create a persistent list of data, view existing lists, export or download the list. This feature is analogous to a shopping cart capability on an e-commerce site.

Original User Story for #88:

As a user I would like to iteratively add entities to a continually growing list, and then save that list.

This could be done using a Dynamo DB table, and providing some REST api to allow users to do simple CRUD operations on their current collection, and upon clicking save, we would save that collection via the collections API.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-64)
┆containerName: azul
┆Issue Number: AZUL-64

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Will eventually be blocked by #31.

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

From CGP Tech Leads Meeting on 7/12:
Work on making collections support in Orange for use by download shopping cart, be able to mint into blue box collections, using a collections JSON schema.

**Comment by theathorn** [comment]
- shopping cart to save search results
- shopping cart per entity type (Files, Projects, ...)
- click button in UI to make a named collection (or use Collection ID)
- share, rename a collection
- once saved, user can't alter content of collection

**Comment by theathorn** [comment]
See https://docs.google.com/document/d/1dvz7ij5JDAHSFZmpAHsw3_xbDge-EEhuLcvA5SIkhc8/

**Comment by theathorn** [comment]
Blue Box Collections API: https://dss.integration.data.humancellatlas.org/

**Comment by theathorn** [comment]
*User Story #1*
As a user I wish to select files according to a faceted search and save the results in a "shopping cart".
I can conduct additional searches and add or delete files to the shopping cart.
When I'm ready I can download all the files in the shopping cart.
See the GDC Data Portal (https://portal.gdc.cancer.gov/projects) for an example.
This can be achieved by creating an (immutable) Collection for the selected files which will return a UUID or url for the Collection.
The Collection UUID/url can be passed to the HCA CLI to perform bulk file download.

*User Story #2*
As a user I can create a Collection (as above) and pass the Collection url to the Matrix Service for further analysis.

*User Story #3*
As a user I can create a Collection (as above) and pass a reference to the Collection url to a selected "Red Box" (portal analysis application) for further analysis (see https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/6).

*User Story #4*
As a user I wish to manage my Collections by being able to:
  - create multiple Collections
  - view my list of Collections
  - delete a Collection (just the Collection, not the underlying data)
  - share a Collection with another user (via a url)

**Comment by shiroyuki** [comment]
> **NOTE:** This is just a rough draft.

### Data Models

#### Collection
| Property | Type | Description |
| --- | --- | --- |
| `id` | UUID-like `str` | Collection ID |
| `owner_id` | TBD | The ID of the user that owns the collection |

#### CollectionItem
| Property | Type | Description |
| --- | --- | --- |
| `id` | UUID-like `str` | Collection Item ID |
| `collection_id` | UUID-like `str` | Associated `Collection.id` |
| `file_id` | UUID-like `str` (?) | File ID |

#### CollectionAccessibility

This is to allow the service to explicitly grant a user with their own temporary access key / URL.

| Property | Type | Description |
| --- | --- | --- |
| `id` | UUID-like `str` | Collection Accessibility ID |
| `collection_id` | UUID-like `str` | Associated `Collection.id` |
| `user_id` | UUID-like `str` (?) or `None` | Accessible User ID (If this field is not specified, the collection is publicly accessible by any login user.) |
| `enabled` | `bool` | Flag to indicate whether the access is still enabled or temporarily disabled |

##### Usage Scenario

###### Share

When the user decides to share a link, the user will prompt the UI to *create a new `CollectionAccessibility` resource`* with `POST /resources/collections/`. While the backend will only provide the minimum information of the new resource, the UI will generate a URL for the user to access via browser. For example, suppose the ID of the new `CollectionAccessibility` resource is `5E01978D-449A-42D3-95FA-D39FBF849536`. The UI may provide the URL `https://explore.data.humancellatlas.org/#external-collections/{id|jwt}` (either use the resource ID or JWT).

###### Access with ID

When the user uses that URL to access a specific shared collection, the UI will first call `GET /share/collections/{id}` to get the necessary information to access the actual collection with `GET /resources/collection/{id}`.

###### Access with JWT

Alternatively, the user may use the resource JWT to directly access to the collection.

### Web API Specification

#### `POST /resources/collections/`

Create a new collection for a particular login user.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

#### `GET /resources/collections/`

Get the list of collections owned the login user.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

#### `GET /resources/collections/{id}`

Get a particular collection by ID.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

> The access control can be done automatically by using the ID of the login user.

#### `DELETE /resources/collections/{id}`

Delete a particular collection by ID owned by the login user.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

#### `POST /share/collections/`

Share a collection from the login user to a particular user.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

##### Request

###### JSON Schema

```json
{
  "type": "object",
  "required": ["collection_id"],
  "properties": {
    "user_id": {
      "type": "string",
      "description": "User ID"
    },
    "collection_id": {
      "type": "string",
      "description": "Collection ID"
    }
  }
}
```

###### Example

```json
{
  "collection_id": "35FC3421-555C-4487-9FA4-6095144D8C86",
  "user_id": "37F03132-FBB1-46EB-8B48-C6280766CF83"
}
```

##### Response

###### JSON Schema

```json
{
  "type": "object",
  "required": ["id"],
  "properties": {
    "id": {
      "type": "string",
      "description": "Collection Accessibility ID"
    }
  }
}
```

###### Example

```javascript
{
  "id": "5E01978D-449A-42D3-95FA-D39FBF849536",
  // ↓ Only for JWT approach
  "_jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVFMDE5NzhELTQ0OUEtNDJEMy05NUZBLUQzOUZCRjg0OTUzNiIsImNvbGxlY3Rpb25faWQiOiIzNUZDMzQyMS01NTVDLTQ0ODctOUZBNC02MDk1MTQ0RDhDODYiLCJ1c2VyX2lkIjoiMzdGMDMxMzItRkJCMS00NkVCLThCNDgtQzYyODA3NjZDRjgzIn0.dmDgoLlaXGTxLy5tk9DeBMMQ2JItQX_KmlbUZ9VtFAE"
}
```

#### `GET /share/collections/`

Get the list of collection accessibilities managed by the login user.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

#### `GET /share/collections/{id}`

> For sans-JWT approach

Get a specific collection accessibility information by ID.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

#### `DELETE /share/collections/{id}`

Delete the collection accessibilities managed by the login user by ID.

| Type | Key | Description | Required | Default | Example |
| --- | --- | --- | --- | --- | --- |
| HTTP Header | `X-Access-Key` | Access key for the login user | Yes, always | - | TBD |

**Comment by Ben-Wu** [comment]
Some additional considerations to the draft:
- Collection names set by the user
- Endpoints to add and remove files in a collection
- A separate CollectionAccessibility object might be awkward to use or not performant if we use a non-relational datastore (probably a non-issue but something to consider when we start implementation)
- Using DSS to store collections (I think this was mentioned at some point)

**Comment by shiroyuki** [comment]
All `X-Access-Key` headers are replaced with `Authorization` for JWT Authorization Bearer Tokens.

**Comment by shiroyuki** [comment]
@Ben-Wu, you can find the second draft at https://github.com/DataBiosphere/azul/wiki/%5BFor-Discussion%5D-Technical-Considerations-for-Issue-88-(Version-0,-Draft-2).

**Comment by shiroyuki** [comment]
@hannes-ucsc @Ben-Wu The RFC is now available at https://github.com/DataBiosphere/azul/pull/417.

**Comment by shiroyuki** [comment]
@theathorn, as @hannes-ucsc and I discuss on the default cart, we wonder whether we should allow only one entity type per cart or multiple types?

**Comment by theathorn** [comment]
@shiroyuki @Ben-Wu Is it relatively simple to allow multiple entity types per cart? If so, we could allow that in the cart service implementation and then, if we chose to, restrict to a single-entity-per-cart at the UI level (@NoopDog).

**Comment by Ben-Wu** [comment]
It shouldn't be a problem to allow multiple entity types per cart.  It would probably be simpler for us to allow it.

**Comment by theathorn** [comment]
You could add a "cart type" parameter to the cart creation API that specifies the cart type as "multiple-entity-type" vs. "single-entity-type".

**Comment by shiroyuki** [comment]
@theathorn Cool. So, the RFC #475 (PR #417) will be updated accordingly.

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

See the specs:

  * https://docs.google.com/document/d/1y5bxYR5Y_Xtf4omFFIwzVTBarCn3e87Hqp0kYKo6Nv0/edit#
  * https://docs.google.com/document/d/1zrDNitaClnAZgeBgw2gZ6RMgrWCQtUHu82CzaxMsr50/edit#

**Comment by theathorn** [comment]
Test comment added on Zenhub.

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Test comment added on Jira.

**Comment by shiroyuki** [comment]
@theathorn, Sorry for the late request for verification. I have a few questions/updates regarding to [the user stories (within this ticket)](https://github.com/DataBiosphere/azul/issues/88#issuecomment-426853892).

From my understanding, **user stories 2 & 3** allow a user to create a collection from a selected shopping cart and pass the reference of the collection to a selected service (the Matrix Service and "Red Box". So, my questions are:

- What is the Matrix Service? Is it deployed in the development environment?
- From the description of "Red Box", is the Matrix Service a "Red Box"?
- Is there anyway to see the API spec of both services?
- From the description, if the user can pass the collection URL to a selected Red Box or the Matrix Service, Azul just needs to provide the full URL to the resource (on DSS), right?

In **user story 4**, according to [the API doc](https://dss.dev.data.humancellatlas.org/) for `PUT /collections` (what we use to create a collection),

> New collections are private to the authenticated user.

That means we can't share a collection with another user (via a URL) directly from DSS with the creator's JWT. Ben and I confirmed this. One way we can do this is to copy the idea of implementing pre-signed URLs from AWS S3. I would need some input from @hannes-ucsc on any better approach that implementing the pre-signed URL generator.

@hannes-ucsc, according to [the API doc](https://dss.dev.data.humancellatlas.org/), we cannot list collections that belong to the requesting user. So, I discussed with Ben on adding `collection_id` to the `Cart` table to let Azul track any collections created by the login user.

**Comment by theathorn** [comment]
To satisfy the SOW-3 M1(c) requirement it is sufficient to be able to create a shopping cart and then optionally be able to turn it into a collection. Collections are intended to be long-lived items and therefore it may be decided to only use them for such items as Data Releases.

For *User Story #2" (pass Collection URL to Matrix service) and *User Story #3* (pass Collection URL to a Red Box): It hasn't been decided whether or not to use the Collections API for these.

For *User Story #4* (manage my Collections):  Currently the Collections API does not support shareable collections (data-store#1728), listing collections (data-store#1729) or notifying when a collection is made public (data-store#1729).

**Comment by shiroyuki** [comment]
@theathorn Just to update on this ticket. According to your comment on December 12, 2018, #629 should satisfy the requirement on the shopping cart part. #627 and #628 will enable data export to DSS as a collection (still non-sharable).

**Comment by hannes-ucsc** [comment]
Shopping cart has been deprecated.
