### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#888]
**6.1.2 Prepare for promotion**
The first step should not include the snipped
`git log --pretty=oneline --topo-order --abbrev-commit`
it should be moved further down in the section, after merge step is completed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-551)
┆Project Name: azul
┆Issue Number: AZUL-551

**Comment by achave11** [comment]
- [ ] Section `6.1.3 Finishing up deployment / promotion` should specify `_select deployment_stage` before generating the tag when running the `make tag` command

**Comment by jessebrennan** [comment]
Incorporate notes about warning wranglers https://humancellatlas.slack.com/archives/C9ENBPVNW/p1555513190049000
