### ISSUE TITLE
Add specified metadata fields to content exported to Terra

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#892]
The data currently exported from the HCA Data Browser to Terra does not contain all the metadata fields that the Broad has requested. The specific set of fields is being defined now, and a proposed specification is available here:

HCA Handoff to Terra MVP - Data Columns
https://docs.google.com/document/d/1zeoUjs_iNsUGFm31EDA4JF4lIknyC0LQPt7z8mkt5S8

Done when:
The approved set of metadata columns identified in the specification above are successfully exported from the HCA Data Browser and imported into Terra.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-552)
┆Project Name: azul
┆Issue Number: AZUL-552
┆Epic: Terra hand-off

**Comment by hannes-ucsc** [comment]
The bdbag config in request_config.josno should be the same as for manifests.

**Comment by hannes-ucsc** [comment]
Demo-ed on 5/13/2019
