### ISSUE TITLE
Correlate project short name and UUID in term facets response

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#894]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-553)
┆Project Name: azul
┆Issue Number: AZUL-553

**Comment by hannes-ucsc** [comment]
Looks like we can use a nested `term` aggregation to associate each project short name term with the set of corresponding project UUID terms at very little cost. Note that there could be more than one UUID per short name.
