### ISSUE TITLE
Add secondary analysis workflow type to index

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/azul#896]
The browser needs to be able to distinguish the workflow type for secondary analysis files (e.g. Cellranger vs SS2 vs Optimus, etc.)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-555)
┆Project Name: azul
┆Issue Number: AZUL-555
┆Epic: Improved Matrix Service Integration

**Comment by hannes-ucsc** [comment]
Demo-ed on 5/13/2019
