### ISSUE TITLE
Boardwalk RESTful API update for Commons metadata

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#9]
The RESTful API needs to evolve to accommodate the new metadata structure from the commons project.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-20)
┆Project Name: azul
┆Issue Number: AZUL-20

**Comment by hannes-ucsc** [comment]
Closing old, obsolete dashboard tickets.
