### ISSUE TITLE
Subgraphs tab

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#904]
┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-559)
┆Project Name: azul
┆Issue Number: AZUL-559

**Comment by theathorn** [comment]
Superseded by DCP/2 - closing.

**Comment by hannes-ucsc** [comment]
I'd still like to see a "subgraphs" tab in the data browser. I've been pushing for years now. Do I have to keep fighting the windmills on this one?

**Comment by hannes-ucsc** [comment]
CC refused to take this on.
