### ISSUE TITLE
Disable main indexer lambda during reindexing

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#907]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-562)
┆Project Name: azul
┆Issue Number: AZUL-562

**Comment by hannes-ucsc** [comment]
So unsubscribing doesn't make sense as we won't get notified for bundles that arrive while we are unsubscribed. However, disabling the lambda, either via setting the concurrency limit or by setting TEST_MODE should do the trick as long as this doesn't take longer than one week, the DSS retry period. I will adjust the ticket title accordingly.

**Comment by hannes-ucsc** [comment]
Note that disabling the main indexer lambda causes the indexer's /health endpoint to be down (500 status with a body of `{"message": "Internal server error"}`) which in turn cause the service's /health endpoint to return 503 with `"up": false`.

```
{
  "up": false,
  "elastic_search": {
    "up": true
  },
  "queues": {
    "up": true,
    "azul-documents-prod": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 338,
        "queued": 2859
      }
    },
    "azul-documents-prod.fifo": {
      "up": true,
      "messages": {
        "delayed": 1032,
        "invisible": 696,
        "queued": 758
      }
    },
    "azul-fail-prod": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 0,
        "queued": 1733
      }
    },
    "azul-fail-prod.fifo": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 0,
        "queued": 0
      }
    },
    "azul-notify-prod": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 204,
        "queued": 94626
      }
    }
  },
  "indexer": {
    "up": false,
    "message": "'up'"
  },
  "unindexed_bundles": 94830,
  "unindexed_documents": 2486
}
```

**Comment by hannes-ucsc** [comment]
Another challenge is that there is no simple way to detect when reindexing is done. The best solution I can think of is to have the nudge lambda enable the main lambda IF the queues are empty and the main lambda is disabled. Note that the big red button scripts also disables all lambdas. There might be a race there.

**Comment by theathorn** [comment]
Closing in favor of #908.
