### ISSUE TITLE
Exclude old neuron_diff dataset in prod

### ISSUE THREAD

**Issue by cjvillar** [DataBiosphere/azul#915]
The neuron_diff dataset has been re-ingested in prod.

Could the older version of the dataset (submission ID: 5bf53a6a9460a300074dc824; project UUID: f8880be0-210c-4aa3-9348-f5a423e07421) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cb75991d96dad0008532bdb project UUID: b6dc9b93-929a-45d0-beb2-5cf8e64872fe) has already appeared in the Browser, with additional metadata! 👍

The new IDs have been updated in the CBeta spreadsheet in the "Dataset Re-Ingestion Progress in Prod" tab. Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-567)
┆Project Name: azul
┆Issue Number: AZUL-567

**Comment by hannes-ucsc** [comment]
Assigning to @jessebrennan so this is done as part of the next production promotion next week. @jessebrennan is the release engineer that week.

**Comment by hannes-ucsc** [comment]
@jessebrennan, today's deployment was our best shot at resolving this. Please discuss proposed course of action with me.
