### ISSUE TITLE
Add None to Facets for when the Data is not Tagged

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#92]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-82)
┆Project Name: azul
┆Issue Number: AZUL-82

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Discuss with BrianO.

**Comment by cricketsloan** [comment]
➤ Trevor Heathorn commented:

Delaying since priority is refactoring accessor library.

**Comment by theathorn** [comment]
Dup of #99
