### ISSUE TITLE
DRS endpoint returns cloud-native URL; involves Retry-After

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#920]
Revise the HCA Azul DRS endpoint (/ga4gh/dos/v1/dataobjects/{uuid}) to behave as follows:

Perform a DSS GET /files/{uuid} operation:
- If the DSS response code is 301, wait and retry DSS operation.
Monitor Lambda remaining lifetime, and if getting close to expiration, return a 5xx to Martha with a message indicating the file was not yet available from the DSS
- Else if the DSS response code is 302, obtain the gs:// URL from the DSS response and compose a DRS format response body including the gs://URL and respond with code 200.

For more information, see:
[Terra/Cromwell Access to Files Identified by DRS URIs for the HCA MVP](https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg/edit#)

The final implementation of this should obtain the cloud native URLs from the DSS directly using an enhanced version of `GET /files/{uuid}` with `directurls=true` (https://github.com/HumanCellAtlas/data-store/issues/2045), but as a temporary workaround, a cloud native URL could be derived from the presigned URL currently returned by the DSS.

Done when:
The HCA DRS resolver behaves as described above for all HCA deployments.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-571)
┆Project Name: azul
┆Issue Number: AZUL-571
┆Epic: Terra hand-off

**Comment by hannes-ucsc** [comment]
> The final implementation of this should obtain the cloud native URLs from the DSS directly using an enhanced version of GET /files/{uuid} with directurls=true (HumanCellAtlas/data-store#2045), but as a temporary workaround a cloud native URL could be derived from the presigned URL currently returned by the DSS.

We should decide which alternative to implement. If we go for the final implementation, HumanCellAtlas/data-store#2045 should be marked as blocker.

**Comment by mikebaumann** [comment]
Agreed, I previously tried to configure HumanCellAtlas/data-store#2045 as blocker for this issue, yet ZenHub didn't seem to accept it. Perhaps you know the trick to do so?

Kevin originally thought HumanCellAtlas/data-store#2045 could be done this sprint, yet yesterday he said any new work for his team would need to be done next sprint.
It is a very small amount of work, so I will revisit this with Kevin and, depending on the outcome of that, perhaps the Boardwalk team (e.g. me?) could pick it up.

**Comment by hannes-ucsc** [comment]
I set the blocker.

**Comment by mikebaumann** [comment]
I just now updated the description (at the top) of this issue to be consistent with the recently revised description in [Terra/Cromwell Access to Files Identified by DRS URIs for the HCA MVP](https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg/edit#)
The document should be considered the authoritative description of the work to be done, yet if any differences are identified in the future, please contact me.

**Comment by hannes-ucsc** [comment]
Unfortunately, I didn't test PR #1028 in the sandbox and Murphy then had it fail on `develop`:

https://gitlab.dev.explore.data.humancellatlas.org/azul/azul/-/jobs/1548

This log message coincides with that build error:

```
  | [DEBUG]	2019-05-22T01:20:18.663Z	42927b8f-bada-427b-9549-2d20b7bf0444	Caught exception for <function get_data_object at 0x7efe6fd957b8> Traceback (most recent call last):   File "/var/task/chalice/app.py", line 726, in _get_view_function_response     response = view_function(**function_args)   File "/var/task/app.py", line 1613, in get_data_object     data_obj = file_to_drs(doc)   File "/var/task/app.py", line 1568, in file_to_drs     gs_url(doc['uuid'], doc['version'])   File "/var/task/app.py", line 1631, in gs_url     assert url.startswith('gs') AssertionError
-- | --
```

I'll revert the commit from `develop` and send this back to in progress.

**Comment by hannes-ucsc** [comment]
@jessebrennan ^^^

**Comment by mikebaumann** [comment]
The current implementation is using a default minimum sleep of 10 seconds before retrying, it should be 1 second instead.
Given this endpoint primarily exists for the HCA/Terra handoff MVP, and this is all on Google, and the DSS checkout time for Google is typically very fast (<= 1 second) this endpoint should retry the request very quickly (sleep time of 1 second).
We had discussed this with the Broad and verbally agreed on this as the plan, yet it had not yet been incorporated into our documentation. Sorry about that, I am working on incorporating it now.
