### ISSUE TITLE
Coordinate with the Broad to resolve Terra silent import failure

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#921]
On 4/17/19 it was observed that HCA Data Browser (https://ux-dev.data.humancellatlas.org/explore/projects) appeared to complete successfully (no user-visible errors, and redirected to new Terra workspace), yet the workspace did not contain any exported data. Roughly two weeks earlier, exports from the HCA Data Browser to Terra were working as expected (workspace was populated with exported data). There have been a number of changes to the HCA exported content since then, yet without any error indication or import logs, it is hard to know where the problem lies.

The same BDBag `samples.tsv` file can be manually imported into Terra successfully, resulting in the Terra workspace being populated as expected.

Interestingly, the Commons Data Browser export to Terra still works successfully/as-expected (workspace data is populated), however, it is not working for HCA Data Browser export.

This _may_ be related to the content of the BDBag/`samples.tsv` being exported to Terra, yet even so, there may be a defect/limitation in Terra if it is not displaying such problems back to the end user.

The HCA work here is to coordinate with the Broad (starting with Brad Taylor) to resolve the problem.

Done when:
The export to Terra is working again for the current HCA exported data, or the problem with the HCA exported data is identified (in this case Terra should be updated to display the error to the user, but that is not part of the done criteria for this ticket).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-572)
┆Project Name: azul
┆Issue Number: AZUL-572
┆Epic: Terra hand-off

**Comment by hannes-ucsc** [comment]
Not sure this qualifies for urgency, @mikebaumann.

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

Update from Brad Taylor (Broad) on 5/3/19 via Slack:

{quote}I'm working with our eng team now to scope. I want to have an ETA for you Tuesday
Sorry for the slowness, we had to track it down
We're committed to fixing asap
I'm hoping we get this done this month
finer grain estimate to follow

{quote}

**Comment by cricketsloan** [comment]
➤ Michael Baumann commented:

This is work that is understood and being done by the Broad.
I am passing this to Trevor to track from this point forward.
