### ISSUE TITLE
Identify specific set of HCA bundles for hand-off to Terra acceptance testing

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#922]
Identifying a specific set of HCA bundles that must be handled correctly by the HCA Data Browser handoff to Terra will facilitate definition/specification and acceptance testing.
Knowing which "bundle shapes" are thought to be most important to, and most often used by, researchers exporting data to Terra will help focus efforts and provide a clear definition of done for the HCA Data Browser handoff to Terra.
It is possible/likely that additional bundle shapes of interest/importance will be identified over time, and these can be prioritized and addressed over time, after the MVP has been meaningfully declared as done.

Work with Tim Tickle (Broad) to identify these shapes, and specific existing bundles with these shapes to use for testing.

Done when:
Key specific bundle shapes and existing bundles with these shapes have been identified and captured in writing.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-573)
┆Project Name: azul
┆Issue Number: AZUL-573
┆Epic: Terra hand-off

**Comment by cricketsloan** [comment]
➤ Stefan Kuhn commented:

[~accountid:5ade518154b5e72468e788d9] - Discussed during TLP standup. We believe this should be owned by Team Boardwalk

**Comment by theathorn** [comment]
Consider creating Terra workspace templates for these types of bundles.

**Comment by melainalegaspi** [comment]
@hannes-ucsc "We shouldn't be in the business of making sure that Terra workflows work with HCA metadata and data."
