### ISSUE TITLE
Create concise description of HCA export to Terra process/content

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#923]
Create a brief/concise description of HCA Data Browser export process/content that could be developed into end user documentation. This should in include the following topics:
- Columns and column header name conventions (algorithms, heuristics, etc.)
- Export processing (such as filtering primary bundles if the corresponding analysis bundle is also included in the export)
- Supported bundle types/"shapes"
- etc.

Done when:
The above document exists in a form that could be provided to the UX/beta test team.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-574)
┆Project Name: azul
┆Issue Number: AZUL-574
┆Epic: Terra hand-off

**Comment by cricketsloan** [comment]
➤ Stefan Kuhn commented:

[~accountid:5ade518154b5e72468e788d9] - Discussed during TLP Storytime. Determined this should belong to Team Boardwalk

**Comment by melainalegaspi** [comment]
superseded by Avro/PFB tickets #1430 and #1132
