### ISSUE TITLE
Kibana proxy session with AWS times out after 1 hr

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#925]
Kibana proxy should refresh the session and obtain a new access token from AWS in the background. Alternatively, the README should indicate how to proceed when session expires.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-575)
┆Project Name: azul
┆Issue Number: AZUL-575

**Comment by melainalegaspi** [comment]
@hannes-ucsc : "1 hour is sufficient, won't fix."
