### ISSUE TITLE
Test indexer using a freak bundle

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#93]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-69)
┆Project Name: azul
┆Issue Number: AZUL-69

**Comment by hannes-ucsc** [comment]
I thought this was already done, @alex-hancock? Can you comment.

**Comment by alex-hancock** [comment]
Not done, this was pushed back due to the various CI issues. It faces similar problems as #125, although I suppose we could just compare the keys present in expected/actual and verify a handful of values.

**Comment by alex-hancock** [comment]
Hannes and I have determined that `TestDataExtractorTestCase.test_hca_extraction` is sufficient to cover freak bundle cases, as it includes freak bundles in the suite of bundles it uses and confirms the total number of file/specimen results from those bundles. Therefore, fixing #207 fixes this issue.
