### ISSUE TITLE
Change the Broad's Martha v2 to handle Retry-After from HCA DRS service

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#938]
**NOTE: This change will not be necessary if the HCA DSS reduces the Google file checkout copy time such that the vast majority of requests complete in under 30 seconds.
See: https://github.com/HumanCellAtlas/data-store/issues/2124**

Change Martha (v2) to handle 301 response codes (with Retry-After header) from the HCA DRS Resolver.
This includes changing Martha to check the HCA DRS response code, and if 301, wait for the interval indicated in the Retry-After header, then request again using the value of the Location header.

Also, likely increase the timeout value for the Martha GCF to allow time for the HCA DSS file checkout to occur. The default value is one minute, the maximum supported value is 9 minutes. https://cloud.google.com/functions/docs/concepts/exec#timeout

For more information, see:
[Terra/Cromwell Access to Files Identified by DRS URIs for the HCA/Terra MVP](https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg/edit?ts=5cc0d988#)

The Martha component is in the GitHub broadinstitute organization, and is written in JavaScript.

Although it is reasonable to expect the Broad to make this change as part of the HCA handoff to Terra collaboration, it is unclear if/when they will do so.

Done when:
Martha v2 supports DRS responses with Retry-After, and this functionality has been deployed appropriately for use by the production instance of Terra/Cromwell.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-584)
┆Project Name: azul
┆Issue Number: AZUL-584
┆Epic: Terra hand-off

**Comment by hannes-ucsc** [comment]
We'll be switching to TDR's DRS endpoint.
