### ISSUE TITLE
Change the Broad's Cromwell DRS client to handle Retry-After from Martha

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#939]
**NOTE: This change will not be necessary *if* the HCA DSS reduces the Google file checkout copy time such that the vast majority of requests complete in under 30 seconds.
See: HumanCellAtlas/data-store#2124**

Change the Cromwell DRS client to handle Retry-After from Martha.

Cromwell DRS client code is here:
https://github.com/broadinstitute/cromwell/blob/7411e663d3740e69752708d74c4372f49ce2a0cd/scripts/docker-dos/dosUrlLocalizer.sc

This includes consideration of what response value Martha should provide to Cromwell when the HCA DRS Resolver is still providing Martha 301 codes and Martha is approaching its timeout value, and what Cromwell should do in this case.

Currently the largest data file in HCA production is 45.6 GB (a fastq.gz file), with many other fastq.gz files in the 15-30GB range. Dividing the largest value by the bucket-to-bucket copy rate (~ 200 MiB/s for AWS anyway) yields ~225 seconds, so a timeout of 5 minutes may be sufficient for MVP purposes (cold storage is not currently used), yet this warrants further discussion.

Also need to check/adjust the timeout value Cromwell is using for its request to Martha.

The Cromwell component is in the GitHub broadinstitute organization, and is written in Scala.

Although it is reasonable to expect the Broad to make this change as part of the HCA handoff to Terra collaboration, it is unclear if/when they will do so.

Done when:
The Cromwell DRS client successfully handles Retry-After from Martha and this is available in the Terra production deployment.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-585)
┆Project Name: azul
┆Issue Number: AZUL-585
┆Epic: Terra hand-off

**Comment by hannes-ucsc** [comment]
We'll be switching to TDR's DRS endpoint.
