### ISSUE TITLE
Exclude old BM_PC dataset in prod

### ISSUE THREAD

**Issue by cjvillar** [DataBiosphere/azul#944]
The BM_PC dataset has been re-ingested in prod.

Could the older version of the dataset (submission ID:5bfe4d3a9460a300074eebc8 ; project UUID: 1f9a699a-262c-40a0-8b2c-7ba960ca388c) please be excluded from the Browser.

The new version of the dataset (submission ID: 5cb8e061d96dad000854f36e project UUID: e6fe3456-0849-4b75-a7a4-44f075ef0079) has already appeared in the Browser, with additional metadata! 👍

The new IDs have been updated in the CBeta spreadsheet in the "Dataset Re-Ingestion Progress in Prod" tab. Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-588)
┆Project Name: azul
┆Issue Number: AZUL-588

**Comment by achave11** [comment]
I was unable to correlate the given project uuids to existing projects in Azul. 
However, I was able to correlate the project short name to two different project uuids.

So the project with the oldest version being `2018-11-28T114357.044837Z` and project uuid `0c7bbbce-3c70-4d6b-a443-1b92c1f205c8` was excluded.

The other project with uuid `e1f2a0e4-1ec8-431e-a6df-c975b3a1131f` was left in the production index. 
If this is not the intended arrangement, please let me know.
