### ISSUE TITLE
Support duplicate notifications

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#947]
This assert https://github.com/DataBiosphere/azul/blob/develop/src/azul/indexer.py#L158 (I believe) can fail if we are receiving duplicates notifications.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-590)
┆Project Name: azul
┆Issue Number: AZUL-590

**Comment by hannes-ucsc** [comment]
```
Traceback (most recent call last):
  File "/var/task/app.py", line 155, in new_handler
    return old_handler(self, event, context)
  File "/var/task/chalice/app.py", line 989, in __call__
    return self.func(event_obj)
  File "/var/task/app.py", line 275, in write
    indexer.aggregate(writer, tallies)
  File "/var/task/azul/indexer.py", line 158, in aggregate
    assert all(tallies[entity] <= actual_tally for entity, actual_tally in actual_tallies.items())
AssertionError
```

fires too in conjunction with duplicate notifications.

**Comment by jessebrennan** [comment]
If a deletion and an addition are processed at the same time this will also cause the assertion to fail.
