### ISSUE TITLE
Projects response has `projectSummary.donorCount != donorOrganisms.id.length()`

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#953]
![Screen Shot 2019-05-01 at 10.11.00 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/8ac893b4-80d6-43f1-90cc-e0c30e80d31a)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-591)
┆Project Name: azul
┆Issue Number: AZUL-591

**Comment by hannes-ucsc** [comment]
Demo-ed on 5/13/2019
