### ISSUE TITLE
Validate authenticity of incoming notifications

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#96]
As a developer, I want to a way to secure the indexer so that it doesn't index based on random 'events'. 

DOD: The indexer authenticates/validates the event, uses HMAC when creating the subscription, implement this package https://pypi.org/project/requests-http-signature/#description to validate the signature. Unit tests proves that a random malicious event won't be able to proceed with indexing vs an appropriate signed event which goes through.

- [x] Write test for basic interaction between sender (reindex.py) and receiver (indexer/app.py)
- [x] ~Manage HMAC secret key and id using secrets manager and provision via Terraform~
- [x] Rename Reindexer to AzulClient, add deletion support and integrate with scripts/
- [x] Add test covering authenticity checking of deletions
- [x] extend `subscription.py` to supply HMAC key and ID to DSS when subscribing

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-68)
┆Project Name: azul
┆Issue Number: AZUL-68

**Comment by theathorn** [comment]
@hannes-ucsc Any idea where this stands?

**Comment by theathorn** [comment]
Alex status: #96 is a fairly serious ticket that I will continue working on when I get the go-ahead from Brian (O'Connor). I would say it should go in the backlog until I return: it's important, but not time-critical.

**Comment by achave11** [comment]
Demoed 04-02-19
