### ISSUE TITLE
Add `metadata` field to documents in bundles index

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#965]
Include ~`manifest`~ `metadata` field in the contributions and aggregate bundles index with a dictionary structure of 
```
'metadata': [
    {
        'column_name_1': 'value_1',
        'column_name_2': 'value_2',
        ...
    },
    {...},
    ...
}
```

Most viable approach should contain the ~manifest~ metadata ~filed~ field outside of the contents field.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-596)
┆Project Name: azul
┆Issue Number: AZUL-596
┆Epic: Dynamically generate full metadata TSV

**Comment by hannes-ucsc** [comment]
The top-level field name is `metadata`, not `manifest`. It's type is a list not a dict. Both things were clearly represented on the whiteboard. Any particular reason you deviated from that, or was this just in error? If the former it would have been nice to be part of that decision. If the latter, please try to avoid these types of error in the future.

I made the necessary edits to the description. Talk to me before reverting those.

**Comment by hannes-ucsc** [comment]
It's also worth noting that `metadata` field will be populated using the script in https://github.com/HumanCellAtlas/hca_bundles_to_csv. I think we should probably cannabalize that script and make it part of the Azul code base.
