### ISSUE TITLE
Generate full metadata TSV in response to `/fetch/manifest/files?format=metadata`

### ISSUE THREAD

**Issue by achave11** [DataBiosphere/azul#967]
Generate aggregate `tsv`, this should take into account that different bundles contribute or might contribute different fields therefore changing the column names.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-598)
┆Project Name: azul
┆Issue Number: AZUL-598
┆Epic: Dynamically generate full metadata TSV

**Comment by hannes-ucsc** [comment]
Or should we use `/fetch/manifest/bundles`?
