### ISSUE TITLE
Check API endpoints as part of Azul DCP Health Check

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/azul#971]
DCP Status is returning OK for Azul even though there is a 500 on the projects request.  Can we adjust the health check to test the main endpoints, projects, specimens, files, summary?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-602)
┆Project Name: azul
┆Issue Number: AZUL-602

**Comment by hannes-ucsc** [comment]
I think we should do this but there are implications. If `/health` involves a request to `/repository/{projects,samples,files,bundles}` it would become fairly expensive. Considering that Data Browser invokes `/health` on every page load, this would increase the server load by a factor of two at least.

I think we should expose the "indexing progress" part of the `/health` response separately under `/progress`, and switch the data browser to using `/progress` instead of `/health`. Then we can exercise `/repository/{projects,samples,files,bundles}` as part of `/health` because only the Route53 health check will be hitting it, not every Data Browser user.

**Comment by GPelayo** [comment]
@NoopDog @hannes-ucsc 
Just to clarify, are these only API endpoints that need to be checked?

`/repository/projects`
`/repository/samples`
`/repository/files`
`/repository/bundles`

**Comment by hannes-ucsc** [comment]
Yes, but let's add the summary endpoint as well.

**Comment by GPelayo** [comment]
Got it. The following is my current implementation for the `/health` and `/progress` endpoints

**/health**
```
{
  "up": false,
  "elastic_search": {
    "up": true
  },
  "indexer": {
    "up": true
  },
  "api_endpoints": {
    "up": false,
    "/repository/files": {
      "up": true
    },
    "/repository/projects": {
      "up": true
    },
    "/repository/samples": {
      "up": true
    },
    "/repository/bundles": {
      "up": true
    },
    "/repository/summary": {
      "up": true
    },
    "/bad-endpoint-example": {
      "up": false,
      "message": "403 Client Error: Forbidden for url: https://service.geryl.dev.explore.data.humancellatlas.org/bad-endpoint"
    }
  }
}
```

**/progress**
```
{
  "queues": {
    "up": true,
    "azul-documents-geryl": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 0,
        "queued": 0
      }
    },
    "azul-documents-geryl.fifo": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 0,
        "queued": 0
      }
    },
    "azul-fail-geryl": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 0,
        "queued": 4
      }
    },
    "azul-fail-geryl.fifo": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 0,
        "queued": 0
      }
    },
    "azul-notify-geryl": {
      "up": true,
      "messages": {
        "delayed": 0,
        "invisible": 0,
        "queued": 0
      }
    }
  },
  "unindexed_bundles": 0,
  "unindexed_documents": 0
}
```

**Comment by hannes-ucsc** [comment]
The `queues` response element should go back to `/health`. The `/progress` response should only contain `unindexed_bundles` and `unindexed_documents`. I assume you intend to remove `/bad-endpoint-example` eventually. If not, LMK.

**Comment by GPelayo** [comment]
Yes of course, `/bad-endpoint-example` was only added to show how a broken endpoint is displayed in `/health`.
