### ISSUE TITLE
Make indexing of organs more consistent

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#977]
Problems:
- Can't search for projects/samples/files derived from organ "brain" or model_organ "brain" due to `organ` and `model_organ` being separate facets.
- Organ count in the project summary ignores model_organ
- CellSuspensionVisitor looks at all ancestor entities of a cell_suspension and pulls in the `organ` and `organ_part` fields using a entity type based priority instead of which entity is a closer ancestor to the cell suspension.

Solution:
- Add a new field `effective_organ` to the `samples` entity type.  The value stored in this field should be a copy of the sample's `organ` or `model_organ` field based on the entity type of the biomaterial used to create the sample.
- Use the new `contents.samples.effective_organ` when fetching an `organCount` from Elastic Search.
- Remove CellSuspensionVisitor and use the recursive function `SampleTransformer.get_ancestor_samples` to walk up the ancestor tree from the cell suspension finding the first sample (specimen/cell_line/organoid) found up each tree branch. With this list of samples then add each sample's `organ` or `model_organ` to the cell_suspension_dict.
- Change elastic-search group_by_organ aggregation to be based off cell suspension

Base the PR for this off of the branch `issues/danielsotirhos/930-index-cell-line-fields` https://github.com/DataBiosphere/azul/issues/930

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-606)
┆Project Name: azul
┆Issue Number: AZUL-606

**Comment by theathorn** [comment]
Demoed 5/28/19
