### ISSUE TITLE
Exclude old pancreas6decades dataset in prod

### ISSUE THREAD

**Issue by cjvillar** [DataBiosphere/azul#978]
The pancreas6decades dataset has been re-ingested in prod.

Could the **older** version of the dataset (submission ID: **5bdc209b9460a300074b7e67**; **project UUID: e8642221-4c2c-4fd7-b926-a68bce363c88**) please be excluded from the Browser.

The **new** version of the dataset (**submission ID: 5cd4445cd96dad000855adba** ; **project UUID: dadbdb31-5f69-485b-85f3-b244b74123f1** ) has already appeared in the Browser, with additional metadata! 

The new IDs have been updated in the CBeta spreadsheet in the "Dataset Re-Ingestion Progress in Prod" tab. Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-607)
┆Project Name: azul
┆Issue Number: AZUL-607

**Comment by hannes-ucsc** [comment]
Assigned to @jessebrennan, the release engineer next week.

**Comment by zperova** [comment]
Please hold on with this issue until the pipelines team have confirmed that analysis has successfully finished.
