### ISSUE TITLE
Broad: Change Martha to bypass request to Bond for HCA DRS URIs

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#982]
Related to: https://github.com/DataBiosphere/azul/issues/981

For more info, see: [Terra/Cromwell Access to Files Identified by DRS URI for the HCA/Terra MVP](https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg/edit#heading=h.9strq6o3dhsc)

Owned by Greg Polumbo (Broad)

Done when:
The Broad's Martha component has been updated to request the HCA provider for HCA DRS URIs

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-611)
┆Project Name: azul
┆Issue Number: AZUL-611

**Comment by mikebaumann** [comment]
This change is in progress and being addressed by the following PR:
https://github.com/broadinstitute/martha/pull/125

**Comment by mikebaumann** [comment]
I have updated the PR noted in the comment above, and those (final?) changes are now available for review. All automated checks are passing.

The PR consists of a few, simple and isolated code changes, but there are not yet any automated test updates included in this PR. I am not a JS/Node developer, but will look into updating some of the existing tests for this change.

**Comment by gpolumbo-broad** [comment]
Thanks @mikebaumann for implementing this, I think you're right that a few tests are needed at least for determining the provider:  https://github.com/broadinstitute/martha/blob/ad6f28a0f28cb0196331cfb296994c349b48cecc/test/common/helpers.test.js#L108 and also for the two `maybeTalkToBond` methods.

**Comment by mikebaumann** [comment]
Moving back to in-progress for the creation of automated tests for these functional changes.

**Comment by mikebaumann** [comment]
Thanks for the test code reference, @gpolumbo-broad.

I started setting up my system for Martha test development, yet I will be out of the office today for another commitment.

Are the Development Setup instructions in the Martha readme all current?
For example, should I be using Node 8, which the readme says is the current LTS, or Node 10, which is the actual current LTS? It would be helpful if you would review the readme to ensure all the Development Setup instructions are current and correct.
I am not a JS/Node developer, and I appreciate all the good work that has been on the Development Setup instructions in the readme already, and I just want to check that it is all current.

Thanks!

**Comment by gpolumbo-broad** [comment]
Thanks for the note on the LTS version.  Node 8 is the correct version to
use.  FWIW, there was someone else at the Broad recently who went through
the setup and said it all worked as explained in the readme, so I'm hopeful
that you will have a similar smooth experience.  If not, let me know and I
can put you in contact with this other developer to see if there are other
other improvements we can make to the readme.

**Comment by mikebaumann** [comment]
@gpolumbo-broad Unit tests have now been added for all HCA-related functional changes to Martha. Please re-review.

The development setup went pretty well, there were a few items I can update you on later.

Thanks!

**Comment by bradtaylor** [comment]
https://github.com/broadinstitute/martha/pull/125
has been merged and should be released tomorrow.
