### ISSUE TITLE
Add HCA Azul endpoint to return Google Service Account keys

### ISSUE THREAD

**Issue by mikebaumann** [DataBiosphere/azul#984]
Add HCA Azul endpoint to return Google Service Account keys that enable access to the HCA DSS checkout bucket for Google.

Related to: https://github.com/DataBiosphere/azul/issues/980

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-613)
┆Project Name: azul
┆Issue Number: AZUL-613

**Comment by hannes-ucsc** [comment]
If feel like something is missing here. Do we really want a publicly accessible endpoint to hand out secrets to unauthenticated clients?

**Comment by theathorn** [comment]
Fence-like API endpoint.

**Comment by hannes-ucsc** [comment]
In response to my own comment, and as discussed today with @mikebaumann and @theathorn, for MVP we must verify the bearer token to ensure that the requester is a valid Terra user.

**Comment by mikebaumann** [comment]
We have discussed some design considerations and options regarding this issue, yet the detailed design is still in progress, and implementation should not begin until the detailed design is documented and reviewed. I expect the detailed design work to be complete sometime during the week of 5/27/19.

**Comment by jessebrennan** [comment]
Ok I'll hold off

**Comment by theathorn** [comment]
@mikebaumann Is the design ready for @jessebrennan to proceed?

**Comment by mikebaumann** [comment]
No, but I'll be at the Broad meeting with their developers regarding this tomorrow and Friday (6/6-7/19).

**Comment by mikebaumann** [comment]
Based on discussions with Broad developers and security staff, the Broad will be deploying a service (based on https://github.com/broadinstitute/mock-provider) to perform this function for the MVP timeframe (and probably lasting until HCA begins implementing support for controlled access data).
No credential-related changes are required for Azul and this specific issue is therefore closed.
The following document is currently being updated for the new approach:
https://docs.google.com/document/d/18WDYr3uS82Eu1GhHmeH6PX7tFY6Zk8piKd3ixOoE8Bg/
