### ISSUE TITLE
Add None to Facets for when the Data is not Tagged

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#99]
┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/AZUL-66)
┆Project Name: azul
┆Issue Number: AZUL-66

**Comment by theathorn** [comment]
Dup of #92.

**Comment by hannes-ucsc** [comment]
I don't understand what this is about. @NoopDog, do you?

**Comment by theathorn** [comment]
If (e.g. Male/Female) facet does not have a value then we need a catch-all for a non-specified value, such as "unspecified" or "unknown".

**Comment by NoopDog** [comment]
For Biological Sex we have this:

![Screen Shot 2018-08-21 at 8.19.57 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/5dd49e6c-7db7-4577-9bdc-a29d4bfc0e3e)

I think the question here is weather this is generic across all facets.

**Comment by theathorn** [comment]
@mpanik please review and assign to @Ben-Wu

**Comment by theathorn** [comment]
We want to return an unspecified value as a json null (without quotes) value leaving the UI to decide on the appropriate display name.
