### ISSUE TITLE
Rename field cell_line_type to type

### ISSUE THREAD

**Issue by danielsotirhos** [DataBiosphere/azul#990]
https://github.com/humancellatlas/metadata-api/issues/75

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-617)
┆Project Name: azul
┆Issue Number: AZUL-617

**Comment by hannes-ucsc** [comment]
Note that @jessebrennan already pushed a [hotfix](https://github.com/DataBiosphere/azul/commit/23f4fe634bf440fca15480650503f0f5f71f1985) to production. I think you just need to merge that back into `develop`. Try filing a PR from `prod`, targetting `develop`

**Comment by theathorn** [comment]
Demoed 5/28/19
