### ISSUE TITLE
Designate per-file and global columns by name prefix in BDBag

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#997]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-623)
┆Project Name: azul
┆Issue Number: AZUL-623

**Comment by hannes-ucsc** [comment]
It doesn't make sense to make the column names longer while the `__` hack to work around #1089 is in place.

**Comment by theathorn** [comment]
Obsoleted by #1430.
