### ISSUE TITLE
Exclude old and incorrect pancreas6decades datasets in prod

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/azul#999]
The pancreas6decades dataset has been re-ingested (multiple times) in prod.

Could the 3 older/incorrect versions of the dataset please be excluded from the Browser:
- [x] submission ID: 5cd5973ed96dad00085668cb; project UUID: 5e6c0ede-5648-4b0e-83ce-4644c437b4c0 (reingested but with incorrect metadata)
- [x] submission ID: 5cd4445cd96dad000855adba; project UUID: dadbdb31-5f69-485b-85f3-b244b74123f1 (reingested but with incorrect metadata, indicated as the "new" version in https://github.com/DataBiosphere/azul/issues/978 but this version actually needs to be excluded)
- [x] submission ID: 5bdc209b9460a300074b7e67; project UUID: e8642221-4c2c-4fd7-b926-a68bce363c88 (original version)

The newest version of the dataset (submission ID: 5cd588a4d96dad00085634a2; project UUID: cddab57b-6868-4be4-806f-395ed9dd635a) has already appeared in the Browser, with additional metadata! 👍

The new IDs have been updated in the CBeta spreadsheet in the "Dataset Re-Ingestion Progress in Prod" tab. Thank you!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/AZUL-624)
┆Project Name: azul
┆Issue Number: AZUL-624

**Comment by zperova** [comment]
@xbrianh

**Comment by zperova** [comment]
Please hold on with this issue until the pipelines team have confirmed that analysis has successfully finished.
